import type { CrmComponentKnowledge } from "./schemas.js";
import {
	CLINICAL_COMPONENTS,
	ODONTOGRAM_ARCH_COMPONENT,
	PERIO_CHARTING_MAP_COMPONENT,
	SCHEDULE_GRID_COMPONENT,
	TREATMENT_PLAN_BUILDER_COMPONENT,
	VISIT_DIARY_COMPONENT,
} from "./registry/clinicalComponents.js";
import {
	CBCT_MPR_STUDIO_COMPONENT,
	DENTAL_LAB_ORDERS_COMPONENT,
	DIAGNOSTIC_WAREHOUSE_COMPONENTS,
	SANPIN_STERILIZATION_JOURNAL_COMPONENT,
	WAREHOUSE_FEFO_COMPONENT,
} from "./registry/diagnosticWarehouseComponents.js";
import {
	ANALYTICS_DASHBOARD_COMPONENT,
	CHAIRSIDE_COPILOT_COMPONENT,
	DOCUMENT_GENERATOR_COMPONENT,
	FINANCE_ADMIN_COMPONENTS,
	KKT_CASHIER_COMPONENT,
	PATIENT_CARD_RECORD_COMPONENT,
} from "./registry/financeAdminComponents.js";

/**
 * CRM Component Knowledge Registry — 14 Canonical CRM Modules
 * DENTE Dental CRM — Mandates 8l (Knowledge Inquisitor), 8e (Doctor Autonomy), 8n (Solo Doctor Sovereignty), 8b (Anti-Monolith <800 lines)
 */
export const CRM_COMPONENT_REGISTRY: readonly CrmComponentKnowledge[] = [
	// 1. Clinical Core
	SCHEDULE_GRID_COMPONENT,
	ODONTOGRAM_ARCH_COMPONENT,
	VISIT_DIARY_COMPONENT,
	// 2. Diagnostics & MPR
	CBCT_MPR_STUDIO_COMPONENT,
	// 3. Finance & Cashier 54-FZ
	KKT_CASHIER_COMPONENT,
	// 4. Treatment Plans & 3-Tiers
	TREATMENT_PLAN_BUILDER_COMPONENT,
	// 5. Patient Profile & Somatic Status
	PATIENT_CARD_RECORD_COMPONENT,
	// 6. Warehouse & FEFO
	WAREHOUSE_FEFO_COMPONENT,
	// 7. Laboratory Orders
	DENTAL_LAB_ORDERS_COMPONENT,
	// 8. SanPiN & Autoclave
	SANPIN_STERILIZATION_JOURNAL_COMPONENT,
	// 9. Analytics Dashboard & KPI
	ANALYTICS_DASHBOARD_COMPONENT,
	// 10. Clinical AI Copilot DENTE
	CHAIRSIDE_COPILOT_COMPONENT,
	// 11. Perio Charting Map
	PERIO_CHARTING_MAP_COMPONENT,
	// 12. Documents, Consents & Tax Deduction
	DOCUMENT_GENERATOR_COMPONENT,
];

export {
	SCHEDULE_GRID_COMPONENT,
	ODONTOGRAM_ARCH_COMPONENT,
	VISIT_DIARY_COMPONENT,
	TREATMENT_PLAN_BUILDER_COMPONENT,
	PERIO_CHARTING_MAP_COMPONENT,
	CBCT_MPR_STUDIO_COMPONENT,
	WAREHOUSE_FEFO_COMPONENT,
	DENTAL_LAB_ORDERS_COMPONENT,
	SANPIN_STERILIZATION_JOURNAL_COMPONENT,
	KKT_CASHIER_COMPONENT,
	PATIENT_CARD_RECORD_COMPONENT,
	ANALYTICS_DASHBOARD_COMPONENT,
	CHAIRSIDE_COPILOT_COMPONENT,
	DOCUMENT_GENERATOR_COMPONENT,
	CLINICAL_COMPONENTS,
	DIAGNOSTIC_WAREHOUSE_COMPONENTS,
	FINANCE_ADMIN_COMPONENTS,
};
