/**
 * packages/shared/src/orthodontics/stomxTaxonomyData.ts
 *
 * StomX Orthodontic Diagnostic Taxonomy Options, ICD-10 Classifiers & Clinical Presets.
 *
 * Compliant with:
 * - Supreme Law: THE HAMMER (Zero Mocks, Absolute Parity)
 * - Mandate 8e: Doctor Autonomy — 1-click clinical presets
 * - Mandate 8d & Sin 7: Absolute ban on cartoon emojis
 * - Engineering Rule: Anti-monolith <= 800 lines (Data module < 700 lines)
 */

import type { AngleClass } from "../diagnostics/photoProtocolEngine.js";
import type {
	AngleClassification,
	BadHabit,
	LowerArchForm,
	OrthodonticDiagnosticRecord,
	ProfileType,
	SagittalIncisorRelation,
	TransversalRelation,
	UpperArchForm,
	VerticalIncisorRelation,
} from "./stomxTaxonomy.js";
import { createDefaultOrthodonticNormRecord } from "./stomxTaxonomy.js";

export interface TaxonomyOption<T = string> {
	value: T;
	label: string;
	description?: string;
}

export const DENTAL_ARCH_FORMS_UPPER: TaxonomyOption<UpperArchForm>[] = [
	{ value: "semi_ellipse", label: "Полуэллипс (физиологическая норма ВЧ)", description: "Правильная анатомическая дуга постоянного прикуса" },
	{ value: "parabola", label: "Парабола", description: "Суженная или сглаженная дуга" },
	{ value: "v_shaped", label: "V-образная (сужение в области премоляров)", description: "Резкое сужение в боковых отделах, выступание резцов" },
	{ value: "trapezoid", label: "Трапециевидная (уплощение во фронтальном отделе)", description: "Ретрузия передней группы зубов, уплощенный фас" },
	{ value: "triangular", label: "Треугольная", description: "Выраженное сужение зубной дуги с острым углом у резцов" },
	{ value: "saddle", label: "Седловидная", description: "Сужение в области премоляров и первых моляров" },
	{ value: "asymmetric", label: "Асимметричная", description: "Одностороннее сужение или смещение сегмента зубного ряда" },
];

export const DENTAL_ARCH_FORMS_LOWER: TaxonomyOption<LowerArchForm>[] = [
	{ value: "parabola", label: "Парабола (физиологическая норма НЧ)", description: "Правильная анатомическая параболическая дуга" },
	{ value: "trapezoid", label: "Трапециевидная", description: "Уплощение во фронтальном отделе" },
	{ value: "v_shaped", label: "V-образная", description: "Сужение боковых сегментов" },
	{ value: "triangular", label: "Треугольная", description: "Остроугольная форма зубного ряда" },
	{ value: "saddle", label: "Седловидная", description: "Сужение в области моляров/премоляров" },
	{ value: "asymmetric", label: "Асимметричная", description: "Односторонняя деформация или неравномерное прорезывание" },
];

export const PROFILE_TYPES: TaxonomyOption<ProfileType>[] = [
	{ value: "straight", label: "Прямой (ортогнатический)", description: "Гармоничный профиль, угол профиля лица в норме" },
	{ value: "convex", label: "Выпуклый (II класс / ретрогнатия НЧ)", description: "Выступание верхней губы или дистальное положение подбородка" },
	{ value: "concave", label: "Вогнутый (III класс / прогения)", description: "Выступание подбородка вперед, уплощение средней зоны лица" },
];

export const BAD_HABITS_OPTIONS: TaxonomyOption<BadHabit>[] = [
	{ value: "none", label: "Нет вредных привычек" },
	{ value: "fingers", label: "Сосание пальцев", description: "Приводит к открытому прикусу и протрузии резцов" },
	{ value: "up_lip", label: "Сосание верхней губы", description: "Приводит к ретрузии верхних резцов и прогении" },
	{ value: "down_lip", label: "Сосание/закусывание нижней губы", description: "Приводит к глубокому резцовому перекрытию и оверджету" },
	{ value: "tongue", label: "Прокладывание языка между зубами", description: "Формирует фронтальную вертикальную дизокклюзию" },
	{ value: "objects", label: "Сосание/прикусывание предметов (ручки, карандаши)", description: "Локальные диастемы и деформации зубной дуги" },
];

export const VERTICAL_RELATION_OPTIONS: TaxonomyOption<VerticalIncisorRelation>[] = [
	{ value: "normal", label: "В норме (перекрытие на 1/3 коронки)", description: "Физиологическое резцовое перекрытие 1.5-3.0 мм" },
	{ value: "deep_1_3", label: "Глубокое перекрытие (от 1/3 до 1/2 коронки)", description: "Увеличенное вертикальное перекрытие без травмы слизистой" },
	{ value: "deep_1_2", label: "Глубокий прикус (>1/2 коронки)", description: "Резцы перекрывают более половины высоты нижних коронок" },
	{ value: "traumatic_occlusion", label: "Глубокий травмирующий прикус", description: "Контакт режущих краев резцов со слизистой оболочкой неба/десны" },
	{ value: "straight_incisal", label: "Прямой прикус (краевое смыкание / edge-to-edge)", description: "Смыкание режущими краями стык-в-стык, риск повышенной стираемости" },
	{ value: "open_bite", label: "Открытый прикус (вертикальная дизокклюзия)", description: "Отсутствие смыкания во фронтальном или боковом отделе" },
];

export const SAGITTAL_RELATION_OPTIONS: TaxonomyOption<SagittalIncisorRelation>[] = [
	{ value: "normal", label: "В норме (физиологический контакт 1-2 мм)", description: "Нижние резцы контактируют с небной поверхностью верхних" },
	{ value: "sagittal_cleft", label: "Сагиттальная щель (оверджет > 2 мм)", description: "Протрузия верхних резцов или ретрогнатия нижней челюсти" },
	{ value: "reverse_incisal_occlusion", label: "Обратная резцовая окклюзия (стык/перекрытие)", description: "Нижние резцы перекрывают верхние спереди" },
	{ value: "reverse_sagittal_cleft", label: "Обратная сагиттальная щель", description: "Выраженный мезиальный прикус с щелью между резцами" },
];

export const TRANSVERSAL_RELATION_OPTIONS: TaxonomyOption<TransversalRelation>[] = [
	{ value: "normal", label: "В норме (щечные бугры верхних перекрывают нижние)" },
	{ value: "crossbite_buccal", label: "Буккальный перекрестный прикус (вестибулоокклюзия)", description: "Верхний ряд шире нижнего, щечные бугры снаружи" },
	{ value: "crossbite_lingual", label: "Лингвальный перекрестный прикус (лингвоокклюзия)", description: "Верхний ряд уже нижнего, язычные бугры внутри" },
	{ value: "crossbite_palatal", label: "Палатоокклюзия", description: "Смыкание бугров с полным перекрытием небной поверхности" },
];

export const ANGLE_CLASSES_DETAILED: { id: AngleClass; label: string; short: string; engleNorm: string }[] = [
	{ id: "class_1", label: "I класс по Энглю (нейтральный прикус)", short: "I класс", engleNorm: "Мезиально-щечный бугор первого моляра ВЧ ложится в межбугорковую фиссуру первого моляра НЧ" },
	{ id: "class_2_div_1", label: "II класс 1 подкласс (дистальный прикус, протрузия резцов ВЧ)", short: "II/1 класс", engleNorm: "Мезиально-щечный бугор первого моляра ВЧ ложится кпереди от фиссуры нижнего, веерообразная протрузия" },
	{ id: "class_2_div_2", label: "II класс 2 подкласс (дистальный прикус, ретрузия резцов ВЧ)", short: "II/2 класс", engleNorm: "Мезиально-щечный бугор первого моляра ВЧ кпереди от фиссуры, небный наклон (ретрузия) резцов" },
	{ id: "class_3", label: "III класс по Энглю (мезиальный прикус)", short: "III класс", engleNorm: "Мезиально-щечный бугор первого моляра ВЧ ложится кзади от фиссуры первого моляра НЧ" },
];

export const ICD10_ORTHODONTIC_CODES = [
	{ code: "K07.0", label: "K07.0 — Основные аномалии размеров челюстей (макро-/микрогнатия)" },
	{ code: "K07.1", label: "K07.1 — Аномалии челюстно-черепных соотношений (асимметрия, прогнатия, ретрогнатия)" },
	{ code: "K07.2", label: "K07.2 — Аномалии соотношений зубных дуг (дистальный, мезиальный, глубокий, перекрестный)" },
	{ code: "K07.3", label: "K07.3 — Аномалии положения зубов (скученность, диастема, тортоаномалии)" },
	{ code: "K07.4", label: "K07.4 — Челюстно-лицевые аномалии неуточненные" },
	{ code: "K07.8", label: "K07.8 — Другие челюстно-лицевые аномалии" },
];

// ─────────────────────────────────────────────────────────────────────────────
// CLINICAL CASE PRESETS (StomX Diagnostic Profiles)
// ─────────────────────────────────────────────────────────────────────────────

export interface OrthodonticDiagnosticPreset {
	id: string;
	label: string;
	shortLabel: string;
	description: string;
	record: OrthodonticDiagnosticRecord;
}

export const ORTHODONTIC_DIAGNOSTIC_PRESETS: OrthodonticDiagnosticPreset[] = [
	{
		id: "norm_class_1",
		label: "Ортодонтическая норма (ортогнатический прикус, I класс)",
		shortLabel: "Норма (I класс)",
		description: "Физиологическая норма: гармоничный профиль, соотношение моляров I класс, правильные дуги, норма ТРГ",
		record: createDefaultOrthodonticNormRecord(),
	},
	{
		id: "class_2_div_1",
		label: "Дистальный прикус (II класс 1 подкласс: протрузия резцов ВЧ, оверджет 6 мм)",
		shortLabel: "II класс 1 подкласс",
		description: "Выпуклый профиль, сагиттальная щель 6 мм, веерообразное расхождение верхних резцов, II класс по Энглю",
		record: createDefaultOrthodonticNormRecord({
			id: "preset_class_2_1",
			complaintsAnamnesis: {
				aesthetic: true,
				morphological: true,
				lipIncompetence: true,
				mouthBreathing: true,
				badHabits: ["down_lip", "fingers"],
				teethEruptionTiming: "задержка смены боковых зубов",
				concomitantDiseases: ["ent_organs"],
				allergies: "не отягощен",
				speechDisorders: false,
				speechDisordersComment: "",
				mandibularHabitualShift: "none",
				bruxism: false,
				sluggishChewing: false,
				pregnancyTrimester: "no",
				deliveryTerm: "on_time",
				feedingType: "artificial",
				feedingTypeExtra: "",
				heredityAnomalies: ["parents"],
				hasPriorOrthoTreatment: false,
				priorOrthoType: "none",
				priorOrthoDuration: "",
				tmjDysfunction: false,
				infantileSwallowing: false,
			},
			faceExamination: {
				faceSymmetry: "symmetric",
				facialThirdsProportion: "lower_third_decreased",
				profileType: "convex",
				chinPosition: "retruding",
				upperLipPosition: "protruding",
				lowerLipPosition: "retruding",
				supramentalFold: "pronounced",
				nasolabialFolds: "normal",
				lipsClosedInRepose: "incompetent",
				gummySmile: true,
				gummySmileMm: 2.5,
				incisorDisplayRestMm: 5.0,
				incisorDisplaySmilePercent: 100,
				chinShift: "none",
				chinShiftMm: 0,
			},
			oralExamination: {
				upperArchForm: "v_shaped",
				lowerArchForm: "trapezoid",
				archSymmetry: "preserved",
				archSymmetryComment: "симметричны",
				midlineShift: "none",
				midlineShiftMm: 0,
				angleMolarLeft: "class_2_div_1",
				angleMolarRight: "class_2_div_1",
				angleCanineLeft: "class_2_div_1",
				angleCanineRight: "class_2_div_1",
				sagittalRelation: "sagittal_cleft",
				sagittalCleftMm: 6,
				verticalRelation: "deep_1_3",
				verticalOpenBiteMm: 0,
				lateralDisocclusion: "none",
				transversalRelation: "normal",
				transversalSide: "none",
				diastemaUpperMm: 1.5,
				diastemaLowerMm: 0,
				tremasUpper: true,
				tremasLower: false,
				crowdingUpper: "mild",
				crowdingUpperMm: 2,
				crowdingLower: "moderate",
				crowdingLowerMm: 3.5,
				teethPositionAnomalies: "протрузия резцов 12, 11, 21, 22",
				upperLipFrenulum: "normal",
				lowerLipFrenulum: "normal",
				tongueFrenulum: "normal",
				tongueSize: "normal",
				vestibuleDepth: "normal",
				mucousMembrane: "normal",
				dentitionPeriod: "persistent",
				oralHygiene: "allowable",
			},
			trgDiagnostics: {
				sna: 83,
				snb: 77,
				anb: 6,
				wits: 3.5,
				fma: 24,
				u1NaAngle: 29,
				u1NaMm: 7,
				l1NbAngle: 22,
				l1NbMm: 3,
				u1Nl: 118,
				l1Ml: 88,
				interincisalAngle: 122,
				bjorkSum: 394,
				jarabakRatio: 64,
				skeletalClass: "class_2",
				growthDirection: "neutral",
				maxillarySagittalType: "normognathic",
				mandibularSagittalType: "retrognathic",
				eschlerBittnerTest: "improved",
				condyleShiftEdgeToEdge: "possible",
				lipsStrainOnClosure: "tensely",
				date: new Date().toISOString().slice(0, 10),
			},
			clinicalDiagnosisIcd10: "K07.2",
			clinicalDiagnosisText: "Дистальная окклюзия (II класс 1 подкласс по Энглю). Скелетный II класс за счет ретрогнатии нижней челюсти. Протрузия резцов верхней челюсти, сагиттальная щель 6 мм. Скученность во фронтальном отделе нижней челюсти I-II степени.",
			treatmentPlanText: "1. Профессиональная гигиена полости рта (A16.07.051). 2. Фиксация самолигирующей брекет-системы (A16.07.048). 3. Нивелирование на дугах CuNiTi .014-.018. 4. Дистализация моляров или межчелюстная эластическая тяга по II классу. 5. Юстировка и закрытие промежутков на дугах SS .019x.025.",
			retentionPlanText: "Несъемные ретейнеры 13-23, 33-43 + ретенционная каппа на верхний зубной ряд.",
			nomenclature804nCodes: ["A16.07.048", "A16.07.048.002", "A06.07.006", "A02.07.010"],
			notes: "Пациент мотивирован на ортодонтическое лечение. Проба Эшлера-Битнера положительная (профиль улучшается при выдвижении челюсти вперед).",
		}),
	},
	{
		id: "class_2_div_2",
		label: "Дистальный прикус (II класс 2 подкласс: ретрузия резцов ВЧ, глубокий травмирующий прикус)",
		shortLabel: "II класс 2 подкласс",
		description: "Палатинальный наклон центральных резцов, вестибулярный наклон боковых резцов, глубокий травмирующий прикус, сниженная нижняя треть",
		record: createDefaultOrthodonticNormRecord({
			id: "preset_class_2_2",
			complaintsAnamnesis: {
				aesthetic: true,
				morphological: true,
				tmjDysfunction: true,
				sluggishChewing: true,
				badHabits: ["none"],
				concomitantDiseases: ["none"],
				allergies: "не отягощен",
				speechDisorders: false,
				speechDisordersComment: "",
				mandibularHabitualShift: "none",
				mouthBreathing: false,
				bruxism: true,
				pregnancyTrimester: "no",
				deliveryTerm: "on_time",
				feedingType: "natural",
				feedingTypeExtra: "",
				teethEruptionTiming: "в срок",
				heredityAnomalies: ["parents"],
				hasPriorOrthoTreatment: false,
				priorOrthoType: "none",
				priorOrthoDuration: "",
				lipIncompetence: false,
				infantileSwallowing: false,
			},
			faceExamination: {
				faceSymmetry: "symmetric",
				facialThirdsProportion: "lower_third_decreased",
				profileType: "straight",
				chinPosition: "normal",
				upperLipPosition: "retruding",
				lowerLipPosition: "normal",
				supramentalFold: "pronounced",
				nasolabialFolds: "pronounced",
				lipsClosedInRepose: "closed_relaxed",
				gummySmile: false,
				gummySmileMm: 0,
				incisorDisplayRestMm: 1.0,
				incisorDisplaySmilePercent: 70,
				chinShift: "none",
				chinShiftMm: 0,
			},
			oralExamination: {
				upperArchForm: "trapezoid",
				lowerArchForm: "parabola",
				archSymmetry: "preserved",
				archSymmetryComment: "симметричны",
				midlineShift: "none",
				midlineShiftMm: 0,
				angleMolarLeft: "class_2_div_2",
				angleMolarRight: "class_2_div_2",
				angleCanineLeft: "class_2_div_2",
				angleCanineRight: "class_2_div_2",
				sagittalRelation: "normal",
				sagittalCleftMm: 1,
				verticalRelation: "traumatic_occlusion",
				verticalOpenBiteMm: 0,
				lateralDisocclusion: "none",
				transversalRelation: "normal",
				transversalSide: "none",
				diastemaUpperMm: 0,
				diastemaLowerMm: 0,
				tremasUpper: false,
				tremasLower: false,
				crowdingUpper: "moderate",
				crowdingUpperMm: 4,
				crowdingLower: "moderate",
				crowdingLowerMm: 4,
				teethPositionAnomalies: "палатинальный наклон 11, 21, вестибулопозиция 12, 22",
				upperLipFrenulum: "normal",
				lowerLipFrenulum: "normal",
				tongueFrenulum: "normal",
				tongueSize: "normal",
				vestibuleDepth: "normal",
				mucousMembrane: "hyperemic",
				dentitionPeriod: "persistent",
				oralHygiene: "good",
			},
			trgDiagnostics: {
				sna: 81,
				snb: 77,
				anb: 4,
				wits: 2.0,
				fma: 18,
				u1NaAngle: 12,
				u1NaMm: 1,
				l1NbAngle: 18,
				l1NbMm: 2,
				u1Nl: 95,
				l1Ml: 82,
				interincisalAngle: 148,
				bjorkSum: 384,
				jarabakRatio: 68,
				skeletalClass: "class_2",
				growthDirection: "horizontal",
				maxillarySagittalType: "normognathic",
				mandibularSagittalType: "retrognathic",
				eschlerBittnerTest: "not_changed",
				condyleShiftEdgeToEdge: "impossible",
				lipsStrainOnClosure: "stress_free",
				date: new Date().toISOString().slice(0, 10),
			},
			clinicalDiagnosisIcd10: "K07.2",
			clinicalDiagnosisText: "Дистальная окклюзия (II класс 2 подкласс по Энглю). Глубокий травмирующий прикус. Ретрузия центральных резцов ВЧ, вестибулярное положение латеральных резцов. Горизонтальный тип роста лицевого скелета. Дисфункция ВНЧС.",
			treatmentPlanText: "1. Разобщение прикуса (окклюзионные накладки / bite turbos). 2. Фиксация брекет-системы с высоким положительным торком на резцы ВЧ (+17° Damon Q2). 3. Протрузия и интрузия резцов, нивелирование кривой Шпее. 4. Нормализация высоты нижней трети лица.",
			retentionPlanText: "Несъемные ретейнеры 13-23, 33-43 + каппа для защиты от ночного бруксизма.",
			nomenclature804nCodes: ["A16.07.048", "A16.07.048.002", "A06.07.006"],
			notes: "Травма десневого сосочка с небной стороны при смыкании. Выраженная компрессия головок ВНЧС.",
		}),
	},
	{
		id: "class_3_progenia",
		label: "Мезиальный прикус (III класс по Энглю: обратная резцовая окклюзия, истинная прогения)",
		shortLabel: "III класс (мезиальный)",
		description: "Вогнутый профиль, выступающий массивный подбородок, обратное резцовое перекрытие 3 мм, мезиальное соотношение моляров",
		record: createDefaultOrthodonticNormRecord({
			id: "preset_class_3",
			complaintsAnamnesis: {
				aesthetic: true,
				morphological: true,
				speechDisorders: true,
				speechDisordersComment: "нарушение произношения шипящих и свистящих звуков",
				mandibularHabitualShift: "forward",
				badHabits: ["none"],
				concomitantDiseases: ["none"],
				allergies: "не отягощен",
				tmjDysfunction: true,
				lipIncompetence: false,
				infantileSwallowing: false,
				mouthBreathing: false,
				bruxism: false,
				sluggishChewing: false,
				pregnancyTrimester: "no",
				deliveryTerm: "on_time",
				feedingType: "natural",
				feedingTypeExtra: "",
				teethEruptionTiming: "раннее прорезывание постоянных зубов",
				heredityAnomalies: ["parents", "relatives"],
				hasPriorOrthoTreatment: false,
				priorOrthoType: "none",
				priorOrthoDuration: "",
			},
			faceExamination: {
				faceSymmetry: "symmetric",
				facialThirdsProportion: "lower_third_increased",
				profileType: "concave",
				chinPosition: "protruding",
				upperLipPosition: "retruding",
				lowerLipPosition: "protruding",
				supramentalFold: "smoothed",
				nasolabialFolds: "pronounced",
				lipsClosedInRepose: "closed_relaxed",
				gummySmile: false,
				gummySmileMm: 0,
				incisorDisplayRestMm: 2.0,
				incisorDisplaySmilePercent: 80,
				chinShift: "none",
				chinShiftMm: 0,
			},
			oralExamination: {
				upperArchForm: "trapezoid",
				lowerArchForm: "parabola",
				archSymmetry: "preserved",
				archSymmetryComment: "симметричны",
				midlineShift: "none",
				midlineShiftMm: 0,
				angleMolarLeft: "class_3",
				angleMolarRight: "class_3",
				angleCanineLeft: "class_3",
				angleCanineRight: "class_3",
				sagittalRelation: "reverse_incisal_occlusion",
				sagittalCleftMm: -3,
				verticalRelation: "normal",
				verticalOpenBiteMm: 0,
				lateralDisocclusion: "none",
				transversalRelation: "crossbite_buccal",
				transversalSide: "bilateral",
				diastemaUpperMm: 0,
				diastemaLowerMm: 1.0,
				tremasUpper: false,
				tremasLower: true,
				crowdingUpper: "moderate",
				crowdingUpperMm: 3.5,
				crowdingLower: "none",
				crowdingLowerMm: 0,
				teethPositionAnomalies: "обратное резцовое перекрытие 12, 11, 21, 22",
				upperLipFrenulum: "normal",
				lowerLipFrenulum: "normal",
				tongueFrenulum: "short",
				tongueSize: "macroglossia",
				vestibuleDepth: "normal",
				mucousMembrane: "normal",
				dentitionPeriod: "persistent",
				oralHygiene: "good",
			},
			trgDiagnostics: {
				sna: 79,
				snb: 84,
				anb: -5,
				wits: -4.5,
				fma: 28,
				u1NaAngle: 28,
				u1NaMm: 6,
				l1NbAngle: 18,
				l1NbMm: 2,
				u1Nl: 116,
				l1Ml: 82,
				interincisalAngle: 126,
				bjorkSum: 400,
				jarabakRatio: 61,
				skeletalClass: "class_3",
				growthDirection: "vertical",
				maxillarySagittalType: "retrognathic",
				mandibularSagittalType: "prognathic",
				eschlerBittnerTest: "worsened",
				condyleShiftEdgeToEdge: "impossible",
				lipsStrainOnClosure: "stress_free",
				date: new Date().toISOString().slice(0, 10),
			},
			clinicalDiagnosisIcd10: "K07.2",
			clinicalDiagnosisText: "Мезиальная окклюзия (III класс по Энглю). Скелетный III класс (сочетание микрогнатии верхней челюсти и макрогнатии нижней челюсти). Обратная резцовая окклюзия со щелью -3 мм. Сужение верхнего зубного ряда.",
			treatmentPlanText: "1. Консультация ЧЛХ (оценка необходимости ортогнатической хирургии vs камуфляж). 2. Быстрое небное расширение RPE (аппарат Марко Роса / Хаас). 3. Фиксация брекет-системы с обратным торком. 4. Эластики по III классу или скелетная опора (минивинты IZC / buccal shelf).",
			retentionPlanText: "Несъемные ретейнеры 13-23, 33-43 + ночная позиционирующая каппа.",
			nomenclature804nCodes: ["A16.07.048", "A16.07.046", "A06.07.006"],
			notes: "Отягощенная наследственность по материнской линии (прогения у матери и дедушки).",
		}),
	},
	{
		id: "open_bite_vertical",
		label: "Открытый прикус (вертикальная дизокклюзия 4 мм, инфантильное глотание, ротовое дыхание)",
		shortLabel: "Открытый прикус",
		description: "Фронтальная вертикальная щель 4 мм, несмыкание губ, гипердивергентный вертикальный рост, инфантильное глотание",
		record: createDefaultOrthodonticNormRecord({
			id: "preset_open_bite",
			complaintsAnamnesis: {
				aesthetic: true,
				morphological: true,
				speechDisorders: true,
				speechDisordersComment: "межзубный сигматизм, шепелявость",
				infantileSwallowing: true,
				mouthBreathing: true,
				sluggishChewing: true,
				lipIncompetence: true,
				badHabits: ["tongue", "fingers"],
				concomitantDiseases: ["ent_organs"],
				allergies: "аллергический ринит",
				tmjDysfunction: false,
				mandibularHabitualShift: "none",
				bruxism: false,
				pregnancyTrimester: "no",
				deliveryTerm: "on_time",
				feedingType: "artificial",
				feedingTypeExtra: "",
				teethEruptionTiming: "в срок",
				heredityAnomalies: ["none"],
				hasPriorOrthoTreatment: false,
				priorOrthoType: "none",
				priorOrthoDuration: "",
			},
			faceExamination: {
				faceSymmetry: "symmetric",
				facialThirdsProportion: "lower_third_increased",
				profileType: "convex",
				chinPosition: "retruding",
				upperLipPosition: "normal",
				lowerLipPosition: "normal",
				supramentalFold: "smoothed",
				nasolabialFolds: "smoothed",
				lipsClosedInRepose: "incompetent",
				gummySmile: false,
				gummySmileMm: 0,
				incisorDisplayRestMm: 4.5,
				incisorDisplaySmilePercent: 60,
				chinShift: "none",
				chinShiftMm: 0,
			},
			oralExamination: {
				upperArchForm: "v_shaped",
				lowerArchForm: "trapezoid",
				archSymmetry: "preserved",
				archSymmetryComment: "симметричны",
				midlineShift: "none",
				midlineShiftMm: 0,
				angleMolarLeft: "class_1",
				angleMolarRight: "class_1",
				angleCanineLeft: "class_1",
				angleCanineRight: "class_1",
				sagittalRelation: "sagittal_cleft",
				sagittalCleftMm: 3,
				verticalRelation: "open_bite",
				verticalOpenBiteMm: 4,
				lateralDisocclusion: "none",
				transversalRelation: "normal",
				transversalSide: "none",
				diastemaUpperMm: 0,
				diastemaLowerMm: 0,
				tremasUpper: false,
				tremasLower: false,
				crowdingUpper: "mild",
				crowdingUpperMm: 2,
				crowdingLower: "mild",
				crowdingLowerMm: 2,
				teethPositionAnomalies: "инфраокклюзия резцов 12, 11, 21, 22, 32, 31, 41, 42",
				upperLipFrenulum: "normal",
				lowerLipFrenulum: "normal",
				tongueFrenulum: "short",
				tongueSize: "macroglossia",
				vestibuleDepth: "normal",
				mucousMembrane: "normal",
				dentitionPeriod: "persistent",
				oralHygiene: "allowable",
			},
			trgDiagnostics: {
				sna: 81,
				snb: 77,
				anb: 4,
				wits: 1.5,
				fma: 34,
				u1NaAngle: 26,
				u1NaMm: 5,
				l1NbAngle: 28,
				l1NbMm: 5,
				u1Nl: 112,
				l1Ml: 94,
				interincisalAngle: 118,
				bjorkSum: 408,
				jarabakRatio: 58,
				skeletalClass: "class_2",
				growthDirection: "vertical",
				maxillarySagittalType: "normognathic",
				mandibularSagittalType: "retrognathic",
				eschlerBittnerTest: "not_changed",
				condyleShiftEdgeToEdge: "possible",
				lipsStrainOnClosure: "tensely",
				date: new Date().toISOString().slice(0, 10),
			},
			clinicalDiagnosisIcd10: "K07.2",
			clinicalDiagnosisText: "Вертикальная резцовая дизокклюзия (открытый прикус 4 мм). Вертикальный гипердивергентный тип роста лицевого скелета (FMA 34°). Инфантильный тип глотания, ротовое дыхание.",
			treatmentPlanText: "1. Консультация ЛОР-врача (восстановление носового дыхания). 2. Миогимнастика + логопед (коррекция положения языка). 3. Фиксация небного бюгеля с шипами / заслонкой для языка. 4. Интрузия боковых моляров на минивинтах для ротации нижней челюсти против часовой стрелки.",
			retentionPlanText: "Несъемные ретейнеры + ретенционная пластинка с упором для языка.",
			nomenclature804nCodes: ["A16.07.048", "A16.07.046", "A06.07.006"],
			notes: "Несмыкание губ в покое. Высокий риск рецидива при сохранении инфантильного глотания.",
		}),
	},
	{
		id: "crossbite_transverse",
		label: "Трансверзальная аномалия (односторонний перекрестный прикус, смещение центра 3 мм)",
		shortLabel: "Перекрестный прикус",
		description: "Асимметричное сужение верхнего зубного ряда, перекрестный прикус справа, смещение косметического центра на 3 мм",
		record: createDefaultOrthodonticNormRecord({
			id: "preset_crossbite",
			complaintsAnamnesis: {
				aesthetic: true,
				morphological: true,
				tmjDysfunction: true,
				mandibularHabitualShift: "to_side",
				badHabits: ["none"],
				concomitantDiseases: ["none"],
				allergies: "не отягощен",
				speechDisorders: false,
				speechDisordersComment: "",
				mouthBreathing: false,
				bruxism: false,
				sluggishChewing: false,
				pregnancyTrimester: "no",
				deliveryTerm: "on_time",
				feedingType: "natural",
				feedingTypeExtra: "",
				teethEruptionTiming: "в срок",
				heredityAnomalies: ["none"],
				hasPriorOrthoTreatment: false,
				priorOrthoType: "none",
				priorOrthoDuration: "",
				lipIncompetence: false,
				infantileSwallowing: false,
			},
			faceExamination: {
				faceSymmetry: "asymmetric",
				facialThirdsProportion: "proportional",
				chinShift: "right",
				chinShiftMm: 3,
				profileType: "straight",
				chinPosition: "normal",
				upperLipPosition: "normal",
				lowerLipPosition: "normal",
				supramentalFold: "normal",
				nasolabialFolds: "normal",
				lipsClosedInRepose: "closed_relaxed",
				gummySmile: false,
				gummySmileMm: 0,
				incisorDisplayRestMm: 2.5,
				incisorDisplaySmilePercent: 85,
			},
			oralExamination: {
				upperArchForm: "asymmetric",
				lowerArchForm: "parabola",
				archSymmetry: "disturbed",
				archSymmetryComment: "сужение правого бокового сегмента верхнего зубного ряда",
				midlineShift: "right",
				midlineShiftMm: 3,
				angleMolarLeft: "class_1",
				angleMolarRight: "class_2_div_1",
				angleCanineLeft: "class_1",
				angleCanineRight: "class_2_div_1",
				sagittalRelation: "normal",
				sagittalCleftMm: 2,
				verticalRelation: "normal",
				verticalOpenBiteMm: 0,
				lateralDisocclusion: "none",
				transversalRelation: "crossbite_buccal",
				transversalSide: "right",
				diastemaUpperMm: 0,
				diastemaLowerMm: 0,
				tremasUpper: false,
				tremasLower: false,
				crowdingUpper: "moderate",
				crowdingUpperMm: 3,
				crowdingLower: "mild",
				crowdingLowerMm: 2,
				teethPositionAnomalies: "палатоокклюзия 14, 15, 16",
				upperLipFrenulum: "normal",
				lowerLipFrenulum: "normal",
				tongueFrenulum: "normal",
				tongueSize: "normal",
				vestibuleDepth: "normal",
				mucousMembrane: "normal",
				dentitionPeriod: "persistent",
				oralHygiene: "good",
			},
			trgDiagnostics: {
				sna: 82,
				snb: 80,
				anb: 2,
				wits: 0.5,
				fma: 25,
				u1NaAngle: 22,
				u1NaMm: 4,
				l1NbAngle: 25,
				l1NbMm: 4,
				u1Nl: 110,
				l1Ml: 90,
				interincisalAngle: 131,
				bjorkSum: 396,
				jarabakRatio: 63,
				skeletalClass: "class_1",
				growthDirection: "neutral",
				maxillarySagittalType: "normognathic",
				mandibularSagittalType: "normognathic",
				eschlerBittnerTest: "none",
				condyleShiftEdgeToEdge: "possible",
				lipsStrainOnClosure: "stress_free",
				date: new Date().toISOString().slice(0, 10),
			},
			clinicalDiagnosisIcd10: "K07.2",
			clinicalDiagnosisText: "Трансверзальная аномалия окклюзии (односторонний перекрестный буккальный прикус справа в области 14, 15, 16). Асимметричное сужение верхней зубной дуги. Смещение центральной линии вправо на 3 мм.",
			treatmentPlanText: "1. Асимметричное расширение верхнего зубного ряда (аппарат Quad-Helix или брекеты с индивидуализированной дугой). 2. Перекрестные межчелюстные эластики (Cross-elastics 3/16 4.5 oz). 3. Юстировка центральной линии.",
			retentionPlanText: "Несъемный ретейнер на нижний зубной ряд + каппа с усиленным окклюзионным разобщением справа.",
			nomenclature804nCodes: ["A16.07.048", "A16.07.047", "A06.07.006"],
			notes: "Привычное смещение нижней челюсти вправо при смыкании зубных рядов.",
		}),
	},
];
