import type { Statutory804nItem } from "./types.js";

/**
 * 1. НОМЕНКЛАТУРА МЕДИЦИНСКИХ УСЛУГ (ПРИКАЗ МИНЗДРАВА РФ № 804Н)
 */
export const STATUTORY_804N_CATALOG: readonly Statutory804nItem[] = [
	// Терапия и кариесология
	{
		code: "A16.07.002.001",
		name: "Восстановление зуба пломбой I, V, VI класс по Блэку (светоотверждаемый композит)",
		category: "therapy",
		defaultPriceRub: 3800,
		defaultPriceKopecks: 380000,
		isBaseDmsCovered: true,
		requiresToothNumber: true,
		requiresXrayProof: false,
	},
	{
		code: "A16.07.002.002",
		name: "Восстановление зуба пломбой II, III класс по Блэку (лечение глубокого кариеса)",
		category: "therapy",
		defaultPriceRub: 4500,
		defaultPriceKopecks: 450000,
		isBaseDmsCovered: true,
		requiresToothNumber: true,
		requiresXrayProof: false,
	},
	{
		code: "A16.07.002.003",
		name: "Восстановление зуба пломбой IV класс по Блэку (реставрация фронтальной группы)",
		category: "therapy",
		defaultPriceRub: 5600,
		defaultPriceKopecks: 560000,
		isBaseDmsCovered: true,
		requiresToothNumber: true,
		requiresXrayProof: false,
	},
	{
		code: "A16.07.002.005",
		name: "Наложение пломбы при клиновидных дефектах и эрозии эмали (светоотверждаемый композит)",
		category: "therapy",
		defaultPriceRub: 3800,
		defaultPriceKopecks: 380000,
		isBaseDmsCovered: true,
		requiresToothNumber: true,
		requiresXrayProof: false,
	},
	{
		code: "A16.07.003",
		name: "Восстановление зуба пломбировочными материалами с использованием штифта (Build-up)",
		category: "therapy",
		defaultPriceRub: 4500,
		defaultPriceKopecks: 450000,
		isBaseDmsCovered: true,
		requiresToothNumber: true,
		requiresXrayProof: true,
	},
	{
		code: "A16.07.030.001",
		name: "Инструментальная и медикаментозная обработка 1 корневого канала",
		category: "therapy",
		defaultPriceRub: 2100,
		defaultPriceKopecks: 210000,
		isBaseDmsCovered: true,
		requiresToothNumber: true,
		requiresXrayProof: true,
	},
	{
		code: "A16.07.030.002",
		name: "Инструментальная и медикаментозная обработка 2 корневых каналов",
		category: "therapy",
		defaultPriceRub: 3800,
		defaultPriceKopecks: 380000,
		isBaseDmsCovered: true,
		requiresToothNumber: true,
		requiresXrayProof: true,
	},
	{
		code: "A16.07.030.003",
		name: "Инструментальная и медикаментозная обработка 3 корневых каналов",
		category: "therapy",
		defaultPriceRub: 5200,
		defaultPriceKopecks: 520000,
		isBaseDmsCovered: true,
		requiresToothNumber: true,
		requiresXrayProof: true,
	},
	{
		code: "A16.07.008.002",
		name: "Пломбирование корневого канала зуба гуттаперчевыми штифтами (1 канал)",
		category: "therapy",
		defaultPriceRub: 2400,
		defaultPriceKopecks: 240000,
		isBaseDmsCovered: true,
		requiresToothNumber: true,
		requiresXrayProof: true,
	},
	{
		code: "A16.07.008.003",
		name: "Пломбирование 3 корневых каналов зуба гуттаперчевыми штифтами",
		category: "therapy",
		defaultPriceRub: 6000,
		defaultPriceKopecks: 600000,
		isBaseDmsCovered: true,
		requiresToothNumber: true,
		requiresXrayProof: true,
	},
	{
		code: "A16.07.004",
		name: "Наложение девитализирующей пасты (неотложная помощь при пульпите)",
		category: "therapy",
		defaultPriceRub: 1500,
		defaultPriceKopecks: 150000,
		isBaseDmsCovered: true,
		requiresToothNumber: true,
		requiresXrayProof: false,
	},
	{
		code: "A11.07.010",
		name: "Инъекционное введение анестетика (инфильтрационная / проводниковая анестезия)",
		category: "anesthesia",
		defaultPriceRub: 950,
		defaultPriceKopecks: 95000,
		isBaseDmsCovered: true,
		requiresToothNumber: false,
		requiresXrayProof: false,
	},
	// Хирургия и имплантология
	{
		code: "A16.07.001.001",
		name: "Удаление временного зуба",
		category: "surgery",
		defaultPriceRub: 1800,
		defaultPriceKopecks: 180000,
		isBaseDmsCovered: true,
		requiresToothNumber: true,
		requiresXrayProof: false,
	},
	{
		code: "A16.07.001.002",
		name: "Удаление постоянного зуба простое",
		category: "surgery",
		defaultPriceRub: 3200,
		defaultPriceKopecks: 320000,
		isBaseDmsCovered: true,
		requiresToothNumber: true,
		requiresXrayProof: false,
	},
	{
		code: "A16.07.001.003",
		name: "Удаление зуба сложное с разъединением корней",
		category: "surgery",
		defaultPriceRub: 5500,
		defaultPriceKopecks: 550000,
		isBaseDmsCovered: true,
		requiresToothNumber: true,
		requiresXrayProof: true,
	},
	{
		code: "A16.07.024",
		name: "Операция удаления ретинированного, дистопированного зуба",
		category: "surgery",
		defaultPriceRub: 8500,
		defaultPriceKopecks: 850000,
		isBaseDmsCovered: false,
		requiresToothNumber: true,
		requiresXrayProof: true,
	},
	{
		code: "A16.07.011",
		name: "Вскрытие поднадкостничного очага воспаления (периостотомия с дренированием)",
		category: "surgery",
		defaultPriceRub: 2500,
		defaultPriceKopecks: 250000,
		isBaseDmsCovered: true,
		requiresToothNumber: true,
		requiresXrayProof: false,
	},
	{
		code: "A16.07.006",
		name: "Вскрытие поднадкостничного очага воспаления (периостотомия)",
		category: "surgery",
		defaultPriceRub: 2500,
		defaultPriceKopecks: 250000,
		isBaseDmsCovered: true,
		requiresToothNumber: true,
		requiresXrayProof: false,
	},
	{
		code: "A16.07.007",
		name: "Резекция верхушки корня",
		category: "surgery",
		defaultPriceRub: 7500,
		defaultPriceKopecks: 750000,
		isBaseDmsCovered: false,
		requiresToothNumber: true,
		requiresXrayProof: true,
	},
	{
		code: "A16.07.054.001",
		name: "Внутрикостная дентальная имплантация (установка имплантата)",
		category: "surgery",
		defaultPriceRub: 35000,
		defaultPriceKopecks: 3500000,
		isBaseDmsCovered: false,
		requiresToothNumber: true,
		requiresXrayProof: true,
	},
	{
		code: "A16.07.041",
		name: "Костная пластика челюстно-лицевой области (аугментация кости)",
		category: "surgery",
		defaultPriceRub: 28000,
		defaultPriceKopecks: 2800000,
		isBaseDmsCovered: false,
		requiresToothNumber: true,
		requiresXrayProof: true,
	},
	{
		code: "A16.07.055",
		name: "Синус-лифтинг (субантральная аугментация)",
		category: "surgery",
		defaultPriceRub: 32000,
		defaultPriceKopecks: 3200000,
		isBaseDmsCovered: false,
		requiresToothNumber: true,
		requiresXrayProof: true,
	},
	// Гигиена и профилактика
	{
		code: "A16.07.051",
		name: "Профессиональная гигиена полости рта и зубов (комплекс: УЗ-скейлинг + AirFlow + полировка)",
		category: "hygiene",
		defaultPriceRub: 4500,
		defaultPriceKopecks: 450000,
		isBaseDmsCovered: true,
		requiresToothNumber: false,
		requiresXrayProof: false,
	},
	{
		code: "A16.07.051.001",
		name: "Ультразвуковое удаление наддесневых и поддесневых зубных отложений в области зуба / челюсти",
		category: "hygiene",
		defaultPriceRub: 3800,
		defaultPriceKopecks: 380000,
		isBaseDmsCovered: true,
		requiresToothNumber: false,
		requiresXrayProof: false,
	},
	{
		code: "A16.07.050",
		name: "Профессиональное отбеливание зубов клиническое (холодным светом / лазерное)",
		category: "hygiene",
		defaultPriceRub: 18000,
		defaultPriceKopecks: 1800000,
		isBaseDmsCovered: false,
		requiresToothNumber: false,
		requiresXrayProof: false,
	},
	// Пародонтология
	{
		code: "A16.07.019",
		name: "Временное шинирование при заболеваниях пародонта (1 челюсть)",
		category: "periodontics",
		defaultPriceRub: 7200,
		defaultPriceKopecks: 720000,
		isBaseDmsCovered: false,
		requiresToothNumber: false,
		requiresXrayProof: true,
	},
	{
		code: "A16.07.039",
		name: "Закрытый кюретаж пародонтальных карманов в области 1 зуба",
		category: "periodontics",
		defaultPriceRub: 900,
		defaultPriceKopecks: 90000,
		isBaseDmsCovered: true,
		requiresToothNumber: true,
		requiresXrayProof: true,
	},
	// Ортопедия
	{
		code: "A16.07.004.001",
		name: "Восстановление зуба коронкой металлокерамической",
		category: "orthopedics",
		defaultPriceRub: 14500,
		defaultPriceKopecks: 1450000,
		isBaseDmsCovered: false,
		requiresToothNumber: true,
		requiresXrayProof: true,
	},
	{
		code: "A16.07.004.002",
		name: "Восстановление зуба коронкой безметалловой (диоксид циркония / E.max)",
		category: "orthopedics",
		defaultPriceRub: 24000,
		defaultPriceKopecks: 2400000,
		isBaseDmsCovered: false,
		requiresToothNumber: true,
		requiresXrayProof: true,
	},
	{
		code: "A16.07.006.004",
		name: "Восстановление зуба коронкой из диоксида циркония с винтовой фиксацией на имплантате",
		category: "orthopedics",
		defaultPriceRub: 26000,
		defaultPriceKopecks: 2600000,
		isBaseDmsCovered: false,
		requiresToothNumber: true,
		requiresXrayProof: true,
	},
	{
		code: "A16.07.006.005",
		name: "Протезирование коронкой на имплантате с индивидуальным абатментом (Ti-Base / Zirconia)",
		category: "orthopedics",
		defaultPriceRub: 34000,
		defaultPriceKopecks: 3400000,
		isBaseDmsCovered: false,
		requiresToothNumber: true,
		requiresXrayProof: true,
	},
	{
		code: "A16.07.005",
		name: "Восстановление целостности зубного ряда несъемным мостовидным протезом",
		category: "orthopedics",
		defaultPriceRub: 38000,
		defaultPriceKopecks: 3800000,
		isBaseDmsCovered: false,
		requiresToothNumber: true,
		requiresXrayProof: true,
	},
	{
		code: "A16.07.023",
		name: "Протезирование частичными съемными пластиночными протезами",
		category: "orthopedics",
		defaultPriceRub: 22000,
		defaultPriceKopecks: 2200000,
		isBaseDmsCovered: false,
		requiresToothNumber: false,
		requiresXrayProof: true,
	},
	{
		code: "A16.07.035",
		name: "Протезирование съемными бюгельными протезами с кламмерной фиксацией",
		category: "orthopedics",
		defaultPriceRub: 36000,
		defaultPriceKopecks: 3600000,
		isBaseDmsCovered: false,
		requiresToothNumber: false,
		requiresXrayProof: true,
	},
	// Ортодонтия
	{
		code: "A16.07.048",
		name: "Ортодонтическая коррекция с применением брекет-системы (1 челюсть)",
		category: "orthodontics",
		defaultPriceRub: 45000,
		defaultPriceKopecks: 4500000,
		isBaseDmsCovered: false,
		requiresToothNumber: false,
		requiresXrayProof: true,
	},
	{
		code: "A16.07.047",
		name: "Ортодонтическая коррекция с применением съемного аппарата (пластинки)",
		category: "orthodontics",
		defaultPriceRub: 16000,
		defaultPriceKopecks: 1600000,
		isBaseDmsCovered: false,
		requiresToothNumber: false,
		requiresXrayProof: false,
	},
	// Рентгенология
	{
		code: "A06.07.003",
		name: "Прицельная внутриротовая контактная радиовизиография",
		category: "radiology",
		defaultPriceRub: 650,
		defaultPriceKopecks: 65000,
		isBaseDmsCovered: true,
		requiresToothNumber: true,
		requiresXrayProof: false,
	},
	{
		code: "A06.07.004",
		name: "Ортопантомография челюстей (панорамный снимок ОПТГ)",
		category: "radiology",
		defaultPriceRub: 1400,
		defaultPriceKopecks: 140000,
		isBaseDmsCovered: true,
		requiresToothNumber: false,
		requiresXrayProof: false,
	},
	{
		code: "A06.07.013",
		name: "Компьютерная 3D томография челюстно-лицевой области (КЛКТ)",
		category: "radiology",
		defaultPriceRub: 3200,
		defaultPriceKopecks: 320000,
		isBaseDmsCovered: false,
		requiresToothNumber: false,
		requiresXrayProof: false,
	},
	// Консультации и приемы
	{
		code: "B01.065.001",
		name: "Прием (осмотр, консультация) врача-стоматолога-терапевта первичный",
		category: "consultation",
		defaultPriceRub: 1000,
		defaultPriceKopecks: 100000,
		isBaseDmsCovered: true,
		requiresToothNumber: false,
		requiresXrayProof: false,
	},
	{
		code: "B01.066.001",
		name: "Прием (осмотр, консультация) врача-стоматолога-хирурга первичный",
		category: "consultation",
		defaultPriceRub: 1000,
		defaultPriceKopecks: 100000,
		isBaseDmsCovered: true,
		requiresToothNumber: false,
		requiresXrayProof: false,
	},
	{
		code: "B01.067.001",
		name: "Прием (осмотр, консультация) врача-стоматолога-ортопеда первичный",
		category: "consultation",
		defaultPriceRub: 1000,
		defaultPriceKopecks: 100000,
		isBaseDmsCovered: true,
		requiresToothNumber: false,
		requiresXrayProof: false,
	},
	{
		code: "B01.063.001",
		name: "Прием (осмотр, консультация) врача-ортодонта первичный",
		category: "consultation",
		defaultPriceRub: 1500,
		defaultPriceKopecks: 150000,
		isBaseDmsCovered: false,
		requiresToothNumber: false,
		requiresXrayProof: false,
	},
	{
		code: "B01.064.001",
		name: "Прием (осмотр, консультация) врача-детского стоматолога первичный",
		category: "consultation",
		defaultPriceRub: 1000,
		defaultPriceKopecks: 100000,
		isBaseDmsCovered: true,
		requiresToothNumber: false,
		requiresXrayProof: false,
	},
];

/**
 * Фильтрация номенклатуры 804н
 */
export function getStatutory804nCatalog(options?: { q?: string; category?: string }): readonly Statutory804nItem[] {
	let list = STATUTORY_804N_CATALOG;
	if (options?.category) {
		const cat = options.category.toLowerCase().trim();
		list = list.filter((item) => item.category.toLowerCase() === cat);
	}
	if (options?.q) {
		const q = options.q.toLowerCase().trim();
		list = list.filter((item) => 
			item.code.toLowerCase().includes(q) || item.name.toLowerCase().includes(q)
		);
	}
	return list;
}