/**
 * workspaceFlagDefaults.ts — Layer 1: Pure Defaults and Scale Presets for Clinic Workspaces.
 *
 * Mandate 8s (Sovereign Scale):
 * - Solo Doctor / Therapist (1 chair, autonomous, no forced assistant/inventory)
 * - Small Clinic / Family Clinic (2-4 chairs)
 * - Multi-specialty / Enterprise Network
 */

import type {
	PresetName,
	WorkspaceFeatureFlags,
	WorkspacePresetFeatureFlags,
} from "./types.js";

/**
 * Умолчания для клиники, которая ещё не настраивалась.
 *
 * Ровно те значения, которые раньше стояли литералом в ответе GET
 * /api/workspace/profile. Оставлены как есть намеренно: у работающих клиник
 * колонка пуста, и смена умолчаний прямо сейчас скрыла бы у них разделы, к
 * которым они привыкли. Настроит клиника модули — в базе появится её набор.
 */
export const DEFAULT_WORKSPACE_FEATURE_FLAGS: WorkspaceFeatureFlags = {
	hasAssistants: true,
	hasMultipleChairs: true,
	hasDentalLab: true,
	hasInsuranceCoPay: true,
	hasInstallments: true,
	hasOrthodontics: true,
	hasTasks: true,
	hasReclamations: true,
	hasPediatricMode: false,
	isOmniRole: false,
	workspacePreset: "enterprise",
	onboardingCompleted: true,
	hasPayrollModule: true,
	hasMarketingModule: true,
	hasAnalyticsModule: true,
	hasInventoryModule: true,
	aiEnableTreatmentPlan: true,
	aiEnableRecommendations: true,
	aiEnableDocuments: true,
	// Девять признаков, которых здесь не было: умолчания взяты из DEFAULT_FLAGS
	// клиента (hooks/useWorkspaceProfile.ts), чтобы у работающих клиник ни один
	// раздел не появился и не исчез от самого расширения контракта.
	hasGnathology: false,
	hasCsoScanner: false,
	hasLeadsKanban: false,
	hasOmnichannel: false,
	hasEngineeringStatus: false,
	hasClinicalRules: true,

	hasReferralModule: false,
	hasBpmWorkflows: false,
	numberOfDoctors: 4,
};

// ————————————————————————————————————————————————————————————————————————————
// Preset definitions
// ————————————————————————————————————————————————————————————————————————————
export const WORKSPACE_PRESETS: Record<
	Exclude<PresetName, "custom">,
	WorkspacePresetFeatureFlags
> = {
	solo_therapist: {
		hasAssistants: false,
		hasMultipleChairs: false,
		hasDentalLab: false,
		hasInsuranceCoPay: false,
		hasInstallments: true,
		hasOrthodontics: true,
		hasTasks: true,
		hasReclamations: true,
		hasPediatricMode: false,
		isOmniRole: true,
		workspacePreset: "solo_therapist",
		onboardingCompleted: true,
		hasPayrollModule: false,
		hasMarketingModule: false,
		hasAnalyticsModule: false,
		hasInventoryModule: false,
		aiEnableTreatmentPlan: true,
		aiEnableRecommendations: true,
		aiEnableDocuments: true,
	},
	prosthodontist: {
		hasAssistants: true,
		hasMultipleChairs: false,
		hasDentalLab: true,
		hasInsuranceCoPay: false,
		hasInstallments: true,
		hasOrthodontics: true,
		hasTasks: true,
		hasReclamations: true,
		hasPediatricMode: false,
		isOmniRole: false,
		workspacePreset: "prosthodontist",
		onboardingCompleted: true,
		hasPayrollModule: false,
		hasMarketingModule: false,
		hasAnalyticsModule: false,
		hasInventoryModule: true,
		aiEnableTreatmentPlan: true,
		aiEnableRecommendations: true,
		aiEnableDocuments: true,
	},
	pediatric: {
		hasAssistants: true,
		hasMultipleChairs: true,
		hasDentalLab: false,
		hasInsuranceCoPay: true,
		hasInstallments: false,
		hasOrthodontics: true,
		hasTasks: true,
		hasReclamations: true,
		hasPediatricMode: true,
		isOmniRole: false,
		workspacePreset: "pediatric",
		onboardingCompleted: true,
		hasPayrollModule: true,
		hasMarketingModule: true,
		hasAnalyticsModule: true,
		hasInventoryModule: true,
		aiEnableTreatmentPlan: true,
		aiEnableRecommendations: true,
		aiEnableDocuments: true,
	},
	orthodontic: {
		hasAssistants: true,
		hasMultipleChairs: false,
		hasDentalLab: true,
		hasInsuranceCoPay: true,
		hasInstallments: true,
		hasOrthodontics: true,
		hasTasks: true,
		hasReclamations: true,
		hasPediatricMode: false,
		isOmniRole: false,
		workspacePreset: "orthodontic",
		onboardingCompleted: true,
		hasPayrollModule: true,
		hasMarketingModule: false,
		hasAnalyticsModule: true,
		hasInventoryModule: true,
		aiEnableTreatmentPlan: true,
		aiEnableRecommendations: true,
		aiEnableDocuments: true,
	},
	surgery_center: {
		hasAssistants: true,
		hasMultipleChairs: true,
		hasDentalLab: false,
		hasInsuranceCoPay: true,
		hasInstallments: true,
		hasOrthodontics: true,
		hasTasks: true,
		hasReclamations: true,
		hasPediatricMode: false,
		isOmniRole: false,
		workspacePreset: "surgery_center",
		onboardingCompleted: true,
		hasPayrollModule: true,
		hasMarketingModule: true,
		hasAnalyticsModule: true,
		hasInventoryModule: true,
		aiEnableTreatmentPlan: true,
		aiEnableRecommendations: true,
		aiEnableDocuments: true,
	},
	implant_center: {
		hasAssistants: true,
		hasMultipleChairs: true,
		hasDentalLab: true,
		hasInsuranceCoPay: true,
		hasInstallments: true,
		hasOrthodontics: true,
		hasTasks: true,
		hasReclamations: true,
		hasPediatricMode: false,
		isOmniRole: false,
		workspacePreset: "implant_center",
		onboardingCompleted: true,
		hasPayrollModule: true,
		hasMarketingModule: true,
		hasAnalyticsModule: true,
		hasInventoryModule: true,
		aiEnableTreatmentPlan: true,
		aiEnableRecommendations: true,
		aiEnableDocuments: true,
	},
	family_clinic: {
		hasAssistants: true,
		hasMultipleChairs: true,
		hasDentalLab: true,
		hasInsuranceCoPay: true,
		hasInstallments: true,
		hasOrthodontics: true,
		hasTasks: true,
		hasReclamations: true,
		hasPediatricMode: true,
		isOmniRole: false,
		workspacePreset: "family_clinic",
		onboardingCompleted: true,
		hasPayrollModule: true,
		hasMarketingModule: true,
		hasAnalyticsModule: true,
		hasInventoryModule: true,
		aiEnableTreatmentPlan: true,
		aiEnableRecommendations: true,
		aiEnableDocuments: true,
	},
	multi_specialty: {
		hasAssistants: true,
		hasMultipleChairs: true,
		hasDentalLab: true,
		hasInsuranceCoPay: true,
		hasInstallments: true,
		hasOrthodontics: true,
		hasTasks: true,
		hasReclamations: true,
		hasPediatricMode: true,
		isOmniRole: false,
		workspacePreset: "multi_specialty",
		onboardingCompleted: true,
		hasPayrollModule: true,
		hasMarketingModule: true,
		hasAnalyticsModule: true,
		hasInventoryModule: true,
		aiEnableTreatmentPlan: true,
		aiEnableRecommendations: true,
		aiEnableDocuments: true,
	},
	enterprise: {
		hasAssistants: true,
		hasMultipleChairs: true,
		hasDentalLab: true,
		hasInsuranceCoPay: true,
		hasInstallments: true,
		hasOrthodontics: true,
		hasTasks: true,
		hasReclamations: true,
		hasPediatricMode: true,
		isOmniRole: false,
		workspacePreset: "enterprise",
		onboardingCompleted: true,
		hasPayrollModule: true,
		hasMarketingModule: true,
		hasAnalyticsModule: true,
		hasInventoryModule: true,
		aiEnableTreatmentPlan: true,
		aiEnableRecommendations: true,
		aiEnableDocuments: true,
	},
};
