ALTER TABLE "advance_deposit_taggings" ADD COLUMN IF NOT EXISTS "tagged_target_name" text;
ALTER TABLE "cancellation_reasons_two_level" ADD COLUMN IF NOT EXISTS "reason_code" text;
ALTER TABLE "communication_outbox" ADD COLUMN IF NOT EXISTS "campaign_id" text;
ALTER TABLE "communication_outbox" ADD COLUMN IF NOT EXISTS "dedupe_key" text;
ALTER TABLE "communication_outbox" ADD COLUMN IF NOT EXISTS "locked_at" timestamp with time zone;
ALTER TABLE "communication_outbox" ADD COLUMN IF NOT EXISTS "recipient_address" text;
ALTER TABLE "communication_settings" ADD COLUMN IF NOT EXISTS "block_marketing_in_quiet_hours" boolean DEFAULT false;
ALTER TABLE "communication_settings" ADD COLUMN IF NOT EXISTS "channel_fallback_json" jsonb;
ALTER TABLE "communication_settings" ADD COLUMN IF NOT EXISTS "defer_service_in_quiet_hours" boolean DEFAULT false;
ALTER TABLE "communication_settings" ADD COLUMN IF NOT EXISTS "quiet_hours_start_minute" integer;
ALTER TABLE "communication_settings" ADD COLUMN IF NOT EXISTS "timezone" text;
ALTER TABLE "crm_email_dispatch_logs" ADD COLUMN IF NOT EXISTS "document_title" text;
ALTER TABLE "dadata_geocoded_addresses" ADD COLUMN IF NOT EXISTS "geo_lat" numeric;
ALTER TABLE "extended_odontogram_states" ADD COLUMN IF NOT EXISTS "mobility_degree" text;
ALTER TABLE "extended_odontogram_states" ADD COLUMN IF NOT EXISTS "pediatric_crown_present" boolean DEFAULT false;
ALTER TABLE "migration_entity_links" ADD COLUMN IF NOT EXISTS "source_entity_id" text;
ALTER TABLE "migration_entity_links" ADD COLUMN IF NOT EXISTS "source_system" text;
ALTER TABLE "migration_entity_links" ADD COLUMN IF NOT EXISTS "target_entity_id" text;
ALTER TABLE "migration_quarantine_records" ADD COLUMN IF NOT EXISTS "blocking" boolean DEFAULT false;
ALTER TABLE "migration_quarantine_records" ADD COLUMN IF NOT EXISTS "field_path" text;
ALTER TABLE "migration_quarantine_records" ADD COLUMN IF NOT EXISTS "message" text;
ALTER TABLE "migration_quarantine_records" ADD COLUMN IF NOT EXISTS "staging_record_id" text;
ALTER TABLE "migration_quarantine_records" ADD COLUMN IF NOT EXISTS "suggested_fix" text;
ALTER TABLE "migration_reconciliations" ADD COLUMN IF NOT EXISTS "balanced" boolean DEFAULT true;
ALTER TABLE "migration_reconciliations" ADD COLUMN IF NOT EXISTS "checks_json" jsonb;
ALTER TABLE "migration_reconciliations" ADD COLUMN IF NOT EXISTS "entity_breakdown_json" jsonb;
ALTER TABLE "migration_reconciliations" ADD COLUMN IF NOT EXISTS "source_money_total_rub" numeric;
ALTER TABLE "migration_runs" ADD COLUMN IF NOT EXISTS "detected_encoding" text;
ALTER TABLE "migration_runs" ADD COLUMN IF NOT EXISTS "dry_run" boolean DEFAULT false;
ALTER TABLE "migration_runs" ADD COLUMN IF NOT EXISTS "llm_calls" integer DEFAULT 0;
ALTER TABLE "migration_runs" ADD COLUMN IF NOT EXISTS "mapping_json" jsonb;
ALTER TABLE "migration_runs" ADD COLUMN IF NOT EXISTS "source_fingerprint" text;
ALTER TABLE "migration_runs" ADD COLUMN IF NOT EXISTS "source_name" text;
ALTER TABLE "migration_runs" ADD COLUMN IF NOT EXISTS "source_rows" integer DEFAULT 0;
ALTER TABLE "migration_runs" ADD COLUMN IF NOT EXISTS "vendor_profile" text;
ALTER TABLE "migration_staging_records" ADD COLUMN IF NOT EXISTS "confidence" numeric;
ALTER TABLE "migration_staging_records" ADD COLUMN IF NOT EXISTS "lineage_json" jsonb;
ALTER TABLE "migration_staging_records" ADD COLUMN IF NOT EXISTS "natural_key" text;
ALTER TABLE "migration_staging_records" ADD COLUMN IF NOT EXISTS "normalized_json" jsonb;
ALTER TABLE "migration_staging_records" ADD COLUMN IF NOT EXISTS "raw_hash" text;
ALTER TABLE "migration_staging_records" ADD COLUMN IF NOT EXISTS "raw_json" jsonb;
ALTER TABLE "migration_staging_records" ADD COLUMN IF NOT EXISTS "source_table" text;
ALTER TABLE "migration_staging_records" ADD COLUMN IF NOT EXISTS "target_entity_id" text;
ALTER TABLE "non_dental_examination_forms" ADD COLUMN IF NOT EXISTS "form_name" text;
ALTER TABLE "patient_communication_consents" ADD COLUMN IF NOT EXISTS "source" text;
ALTER TABLE "patient_reclamations" ADD COLUMN IF NOT EXISTS "doctor_id" uuid;
ALTER TABLE "patient_reclamations" ADD COLUMN IF NOT EXISTS "status" text;
ALTER TABLE "patient_task_tickets" ADD COLUMN IF NOT EXISTS "assigned_to_id" uuid;
ALTER TABLE "patient_task_tickets" ADD COLUMN IF NOT EXISTS "organization_id" uuid;
ALTER TABLE "patient_task_tickets" ADD COLUMN IF NOT EXISTS "priority" text;
ALTER TABLE "patient_task_tickets" ADD COLUMN IF NOT EXISTS "status" text;
ALTER TABLE "portal_otp_codes" ADD COLUMN IF NOT EXISTS "channel" text;
ALTER TABLE "portal_otp_codes" ADD COLUMN IF NOT EXISTS "code_hash" text;
ALTER TABLE "portal_otp_codes" ADD COLUMN IF NOT EXISTS "delivery_error_class" text;
ALTER TABLE "portal_otp_codes" ADD COLUMN IF NOT EXISTS "delivery_status" text;
ALTER TABLE "rebooking_conversion_rules" ADD COLUMN IF NOT EXISTS "appointment_date" timestamp with time zone;
ALTER TABLE "rebooking_conversion_rules" ADD COLUMN IF NOT EXISTS "time_delta_minutes" integer;
ALTER TABLE "schedule_time_reservations" ADD COLUMN IF NOT EXISTS "start_time" text;