const fs = require('fs');
let code = fs.readFileSync('C:/Clinic_MVP/dental-crm/apps/api/src/db/imagingQuery.ts', 'utf8');
code = code.replace(/toothCode\?\: string \| null;/g, 'toothCode?: string | null | undefined;');
code = code.replace(/region\?\: string \| null;/g, 'region?: string | null | undefined;');
code = code.replace(/storagePath\?\: string \| null;/g, 'storagePath?: string | null | undefined;');
code = code.replace(/dicomStudyUid\?\: string \| null;/g, 'dicomStudyUid?: string | null | undefined;');
code = code.replace(/capturedAt\?\: string \| null;/g, 'capturedAt?: string | null | undefined;');
code = code.replace(/aiSummary\?\: string \| null;/g, 'aiSummary?: string | null | undefined;');
fs.writeFileSync('C:/Clinic_MVP/dental-crm/apps/api/src/db/imagingQuery.ts', code);
console.log('imagingQuery types updated');
