/**
 * Полный канонический реестр 74+ стандартизированных токенов подстановки
 * для печатных форм и медицинских документов Минздрава РФ.
 */

export interface DocumentTemplateVariableSpec {
	token: string;
	domain: string;
	name: string;
	description: string;
	exampleValue: string;
	resolverPath: string;
}

const STATIC_DOCUMENT_TEMPLATE_VARIABLES: readonly DocumentTemplateVariableSpec[] = [
	// Пациент
	{
		token: "Пациент.ФИО",
		domain: "patient",
		name: "ФИО пациента",
		description: "Фамилия Имя Отчество пациента полностью",
		exampleValue: "Иванов Петр Алексеевич",
		resolverPath: "patient.fullName",
	},
	{
		token: "Пациент.ID",
		domain: "patient",
		name: "ID пациента",
		description: "Уникальный идентификатор пациента в базе данных",
		exampleValue: "101",
		resolverPath: "patient.id",
	},
	{
		token: "Пациент.НомерКарты",
		domain: "patient",
		name: "Номер амбулаторной карты",
		description: "Номер медицинской карты стоматологического больного (Карта приёма)",
		exampleValue: "333",
		resolverPath: "patient.cardNumber",
	},
	{
		token: "Пациент.Фамилия",
		domain: "patient",
		name: "Фамилия пациента",
		description: "Фамилия пациента",
		exampleValue: "Иванов",
		resolverPath: "patient.lastName",
	},
	{
		token: "Пациент.Имя",
		domain: "patient",
		name: "Имя пациента",
		description: "Имя пациента",
		exampleValue: "Петр",
		resolverPath: "patient.firstName",
	},
	{
		token: "Пациент.Отчество",
		domain: "patient",
		name: "Отчество пациента",
		description: "Отчество пациента",
		exampleValue: "Алексеевич",
		resolverPath: "patient.middleName",
	},
	{
		token: "Пациент.Пол",
		domain: "patient",
		name: "Пол пациента",
		description: "Пол пациента (муж / жен)",
		exampleValue: "муж",
		resolverPath: "patient.gender",
	},
	{
		token: "Пациент.Адрес",
		domain: "patient",
		name: "Адрес регистрации пациента",
		description: "Адрес регистрации по паспорту",
		exampleValue: "ул. Ленина, д. 33, кв. 115",
		resolverPath: "patient.address",
	},
	{
		token: "Пациент.Телефон",
		domain: "patient",
		name: "Телефон пациента",
		description: "Основной контактный телефон пациента",
		exampleValue: "+7 911 090 5544",
		resolverPath: "patient.phone",
	},
	{
		token: "Пациент.ИНН",
		domain: "patient",
		name: "ИНН пациента",
		description: "Идентификационный номер налогоплательщика",
		exampleValue: "123456789012",
		resolverPath: "patient.inn",
	},
	{
		token: "Пациент.ФамилияИО",
		domain: "patient",
		name: "Фамилия и инициалы пациента",
		description: "Фамилия и сокращенные инициалы (Иванов П.А.)",
		exampleValue: "Иванов П.А.",
		resolverPath: "patient.initials",
	},
	{
		token: "Пациент.ДеньРождения",
		domain: "patient",
		name: "Дата рождения пациента",
		description: "Дата рождения пациента в формате ДД.ММ.ГГГГ",
		exampleValue: "20.12.1985",
		resolverPath: "patient.birthDate",
	},
	{
		token: "Пациент.Возраст",
		domain: "patient",
		name: "Возраст пациента",
		description: "Полных лет с русским склонением",
		exampleValue: "30 лет",
		resolverPath: "patient.age",
	},
	{
		token: "Пациент.ФактическийАдрес",
		domain: "patient",
		name: "Фактический адрес пациента",
		description: "Адрес фактического проживания",
		exampleValue: "ул. Ленина, д. 33, кв. 115",
		resolverPath: "patient.actualAddress",
	},
	{
		token: "Пациент.Email",
		domain: "patient",
		name: "Электронная почта пациента",
		description: "Email адрес пациента",
		exampleValue: "email@email.ru",
		resolverPath: "patient.email",
	},
	{
		token: "Пациент.СНИЛС",
		domain: "patient",
		name: "СНИЛС пациента",
		description: "Страховой номер индивидуального лицевого счета",
		exampleValue: "123-456-789-01",
		resolverPath: "patient.snils",
	},
	{
		token: "Пациент.Инвалидность",
		domain: "patient",
		name: "Инвалидность пациента",
		description: "Группа инвалидности или отметка об отсутствии",
		exampleValue: "нет",
		resolverPath: "patient.disability",
	},
	{
		token: "Пациент.Льготы",
		domain: "patient",
		name: "Льготы пациента",
		description: "Категория льгот пациента",
		exampleValue: "нет",
		resolverPath: "patient.benefits",
	},
	{
		token: "Пациент.Профессия",
		domain: "patient",
		name: "Профессия пациента",
		description: "Род деятельности или профессия",
		exampleValue: "водитель",
		resolverPath: "patient.profession",
	},
	{
		token: "Пациент.ОсобыеОтметки",
		domain: "patient",
		name: "Особые клинические отметки",
		description: "Аллергологический анамнез, соматические патологии",
		exampleValue: "Аллергия на пенициллин",
		resolverPath: "patient.specialNotes",
	},
	{
		token: "Пациент.Полисы",
		domain: "patient",
		name: "Все полисы пациента",
		description: "Сводные данные полисов ОМС и ДМС",
		exampleValue: "ОМС 123-456-789-01",
		resolverPath: "patient.policies",
	},
	{
		token: "Пациент.ПолисОМС",
		domain: "patient",
		name: "Полис ОМС",
		description: "Номер полиса обязательного медицинского страхования",
		exampleValue: "123-456-789-01",
		resolverPath: "patient.omsPolicy",
	},
	{
		token: "Пациент.ПолисДМС",
		domain: "patient",
		name: "Полис ДМС",
		description: "Номер полиса добровольного медицинского страхования",
		exampleValue: "123-456-789-01",
		resolverPath: "patient.dmsPolicy",
	},
	{
		token: "Пациент.Аванс",
		domain: "patient",
		name: "Аванс / Баланс пациента",
		description: "Текущий финансовый баланс пациента в рублях",
		exampleValue: "25 000",
		resolverPath: "patient.advance",
	},
	{
		token: "Пациент.Паспорт.Номер",
		domain: "patient",
		name: "Паспорт: номер",
		description: "Номер паспорта пациента",
		exampleValue: "123456",
		resolverPath: "patient.passport.number",
	},
	{
		token: "Пациент.Паспорт.СерияНомер",
		domain: "patient",
		name: "Паспорт: серия и номер",
		description: "Серия и номер паспорта пациента через пробел",
		exampleValue: "4510 123456",
		resolverPath: "patient.passport.seriesNumber",
	},
	{
		token: "Пациент.Паспорт.Серия",
		domain: "patient",
		name: "Серия паспорта пациента",
		description: "4 цифры серии паспорта",
		exampleValue: "4321",
		resolverPath: "patient.passport.series",
	},
	{
		token: "Пациент.Паспорт.ДатаВыдачи",
		domain: "patient",
		name: "Дата выдачи паспорта пациента",
		description: "Дата выдачи паспорта (ДД.ММ.ГГГГ)",
		exampleValue: "20.01.2001",
		resolverPath: "patient.passport.issuedDate",
	},
	{
		token: "Пациент.Паспорт.КемВыдан",
		domain: "patient",
		name: "Кем выдан паспорт пациента",
		description: "Орган, выдавший документ, удостоверяющий личность",
		exampleValue: "Отдел УФМС России по г. Москве №133",
		resolverPath: "patient.passport.issuedBy",
	},
	{
		token: "Пациент.Паспорт.КодПодразделения",
		domain: "patient",
		name: "Код подразделения паспорта пациента",
		description: "Код подразделения (XXX-XXX)",
		exampleValue: "123-456",
		resolverPath: "patient.passport.divisionCode",
	},

	// Представитель
	{
		token: "Представитель.ФИО",
		domain: "representative",
		name: "ФИО законного представителя",
		description: "ФИО родителя, опекуна или попечителя полностью",
		exampleValue: "Петров Алексей Иванович",
		resolverPath: "representative.fullName",
	},
	{
		token: "Представитель.ФамилияИнициалы",
		domain: "representative",
		name: "Фамилия и инициалы представителя",
		description: "Фамилия и инициалы представителя",
		exampleValue: "Петров А. И.",
		resolverPath: "representative.initials",
	},
	{
		token: "Представитель.Телефон",
		domain: "representative",
		name: "Телефон представителя",
		description: "Контактный телефон законного представителя",
		exampleValue: "+7 933 090 5544",
		resolverPath: "representative.phone",
	},
	{
		token: "Представитель.Паспорт.Номер",
		domain: "representative",
		name: "Номер паспорта представителя",
		description: "Номер паспорта законного представителя",
		exampleValue: "123456",
		resolverPath: "representative.passport.number",
	},
	{
		token: "Представитель.Паспорт.Серия",
		domain: "representative",
		name: "Серия паспорта представителя",
		description: "Серия паспорта законного представителя",
		exampleValue: "4321",
		resolverPath: "representative.passport.series",
	},
	{
		token: "Представитель.Паспорт.ДатаВыдачи",
		domain: "representative",
		name: "Дата выдачи паспорта представителя",
		description: "Дата выдачи паспорта представителя (ДД.ММ.ГГГГ)",
		exampleValue: "20.01.2001",
		resolverPath: "representative.passport.issuedDate",
	},
	{
		token: "Представитель.Паспорт.КемВыдан",
		domain: "representative",
		name: "Кем выдан паспорт представителя",
		description: "Орган, выдавший паспорт законному представителю",
		exampleValue: "Отдел УФМС России по г. Москве №133",
		resolverPath: "representative.passport.issuedBy",
	},
	{
		token: "Представитель.Паспорт.КодПодразделения",
		domain: "representative",
		name: "Код подразделения представителя",
		description: "Код подразделения органа выдачи паспорта",
		exampleValue: "123-456",
		resolverPath: "representative.passport.divisionCode",
	},
	{
		token: "Представитель.ДеньРождения",
		domain: "representative",
		name: "Дата рождения представителя",
		description: "Дата рождения представителя (ДД.ММ.ГГГГ)",
		exampleValue: "20.12.1985",
		resolverPath: "representative.birthDate",
	},
	{
		token: "Представитель.Адрес",
		domain: "representative",
		name: "Адрес представителя",
		description: "Адрес места жительства законного представителя",
		exampleValue: "ул. Ленина, д. 33, кв. 115",
		resolverPath: "representative.address",
	},
	{
		token: "Представитель.СНИЛС",
		domain: "representative",
		name: "СНИЛС представителя",
		description: "СНИЛС законного представителя",
		exampleValue: "123-456-789-01",
		resolverPath: "representative.snils",
	},
	{
		token: "Представитель.НаОсновании",
		domain: "representative",
		name: "Основание полномочий представителя",
		description: "Документ-основание (Паспорт, Свидетельство о рождении)",
		exampleValue: "Паспорт",
		resolverPath: "representative.basis",
	},
	{
		token: "Представитель.Тип",
		domain: "representative",
		name: "Тип родства законного представителя",
		description: "родитель, опекун, Муж, Жена, Отец, Мать, Дочь, Сын, Сестра, Брат",
		exampleValue: "Отец",
		resolverPath: "representative.relationType",
	},
	{
		token: "Представитель.Основание",
		domain: "representative",
		name: "Основание представителя (алиас)",
		description: "Документ-основание (Паспорт, Свидетельство о рождении)",
		exampleValue: "Паспорт",
		resolverPath: "representative.basis",
	},
	{
		token: "Представитель.Родство",
		domain: "representative",
		name: "Родство представителя (алиас)",
		description: "Отец, Мать, Опекун и т.д.",
		exampleValue: "Мать",
		resolverPath: "representative.relationType",
	},

	// Полномочный
	{
		token: "Полномочный.ФИО",
		domain: "authorizedPerson",
		name: "ФИО уполномоченного лица",
		description: "ФИО лица по доверенности",
		exampleValue: "Петров Алексей Иванович",
		resolverPath: "authorizedPerson.fullName",
	},
	{
		token: "Полномочный.ФамилияИнициалы",
		domain: "authorizedPerson",
		name: "Фамилия и инициалы уполномоченного",
		description: "Фамилия и инициалы поверенного",
		exampleValue: "Петров А.И.",
		resolverPath: "authorizedPerson.initials",
	},
	{
		token: "Полномочный.Телефон",
		domain: "authorizedPerson",
		name: "Телефон уполномоченного лица",
		description: "Телефон поверенного по доверенности",
		exampleValue: "+7 933 090 5544",
		resolverPath: "authorizedPerson.phone",
	},
	{
		token: "Полномочный.Паспорт.Номер",
		domain: "authorizedPerson",
		name: "Номер паспорта уполномоченного",
		description: "Номер паспорта доверенного лица",
		exampleValue: "123456",
		resolverPath: "authorizedPerson.passport.number",
	},
	{
		token: "Полномочный.Паспорт.Серия",
		domain: "authorizedPerson",
		name: "Серия паспорта уполномоченного",
		description: "Серия паспорта доверенного лица",
		exampleValue: "4321",
		resolverPath: "authorizedPerson.passport.series",
	},
	{
		token: "Полномочный.Паспорт.ДатаВыдачи",
		domain: "authorizedPerson",
		name: "Дата выдачи паспорта уполномоченного",
		description: "Дата выдачи паспорта (ДД.ММ.ГГГГ)",
		exampleValue: "20.01.2001",
		resolverPath: "authorizedPerson.passport.issuedDate",
	},
	{
		token: "Полномочный.Паспорт.КемВыдан",
		domain: "authorizedPerson",
		name: "Кем выдан паспорт уполномоченного",
		description: "Орган, выдавший паспорт доверенному лицу",
		exampleValue: "Отдел УФМС России по г. Москве №133",
		resolverPath: "authorizedPerson.passport.issuedBy",
	},
	{
		token: "Полномочный.Паспорт.КодПодразделения",
		domain: "authorizedPerson",
		name: "Код подразделения уполномоченного",
		description: "Код подразделения паспорта доверенного лица",
		exampleValue: "123-456",
		resolverPath: "authorizedPerson.passport.divisionCode",
	},
	{
		token: "Полномочный.ДеньРождения",
		domain: "authorizedPerson",
		name: "Дата рождения уполномоченного",
		description: "Дата рождения доверенного лица (ДД.ММ.ГГГГ)",
		exampleValue: "20.12.1985",
		resolverPath: "authorizedPerson.birthDate",
	},
	{
		token: "Полномочный.Адрес",
		domain: "authorizedPerson",
		name: "Адрес уполномоченного лица",
		description: "Адрес регистрации доверенного лица",
		exampleValue: "ул. Ленина, д. 33, кв. 115",
		resolverPath: "authorizedPerson.address",
	},
	{
		token: "Полномочный.СНИЛС",
		domain: "authorizedPerson",
		name: "СНИЛС уполномоченного лица",
		description: "СНИЛС доверенного лица",
		exampleValue: "123-456-789-01",
		resolverPath: "authorizedPerson.snils",
	},

	// Врачи и персонал
	{
		token: "ПоследнийПриём.Врач.ФИО",
		domain: "doctor",
		name: "ФИО врача последнего приема",
		description: "ФИО врача, проводившего предыдущий прием",
		exampleValue: "Васильев Иван Петрович",
		resolverPath: "lastDoctor.fullName",
	},
	{
		token: "ПоследнийПриём.Врач.ФамилияИнициалы",
		domain: "doctor",
		name: "Фамилия и инициалы врача последнего приема",
		description: "Фамилия и инициалы лечащего врача",
		exampleValue: "Васильев И. П.",
		resolverPath: "lastDoctor.initials",
	},
	{
		token: "ПоследнийПриём.Врач.Должность",
		domain: "doctor",
		name: "Должность врача последнего приема",
		description: "Штатная медицинская должность врача",
		exampleValue: "Врач-стоматолог терапевт",
		resolverPath: "lastDoctor.position",
	},
	{
		token: "ПоследнийПриём.Врач.Специальность",
		domain: "doctor",
		name: "Специальность врача последнего приема",
		description: "Врачебная специальность",
		exampleValue: "Стоматология терапевтическая",
		resolverPath: "lastDoctor.specialty",
	},
	{
		token: "Администратор.ФИО",
		domain: "administrator",
		name: "ФИО администратора",
		description: "ФИО администратора клиники, оформившего документ",
		exampleValue: "Васильев Иван Петрович",
		resolverPath: "administrator.fullName",
	},
	{
		token: "Администратор.ФамилияИнициалы",
		domain: "administrator",
		name: "Фамилия и инициалы администратора",
		description: "Фамилия и инициалы администратора",
		exampleValue: "Васильев И. П.",
		resolverPath: "administrator.initials",
	},
	{
		token: "Администратор.Должность",
		domain: "administrator",
		name: "Должность администратора",
		description: "Штатная должность сотрудника регистратуры",
		exampleValue: "Администратор",
		resolverPath: "administrator.position",
	},
	{
		token: "Администратор.Специальность",
		domain: "administrator",
		name: "Специальность администратора",
		description: "Специальность сотрудника",
		exampleValue: "Администратор клиники",
		resolverPath: "administrator.specialty",
	},
	{
		token: "АктивныйВрач.ФИО",
		domain: "doctor",
		name: "ФИО активного врача",
		description: "ФИО врача текущего приема / подписывающего врача",
		exampleValue: "Васильев Иван Петрович",
		resolverPath: "doctor.fullName",
	},
	{
		token: "АктивныйВрач.ФамилияИнициалы",
		domain: "doctor",
		name: "Фамилия и инициалы активного врача",
		description: "Фамилия и инициалы врача текущего приема",
		exampleValue: "Васильев И. П.",
		resolverPath: "doctor.initials",
	},
	{
		token: "АктивныйВрач.Должность",
		domain: "doctor",
		name: "Должность активного врача",
		description: "Должность врача текущего приема",
		exampleValue: "Врач-стоматолог терапевт",
		resolverPath: "doctor.position",
	},
	{
		token: "АктивныйВрач.Специальность",
		domain: "doctor",
		name: "Специальность активного врача",
		description: "Клиническая специальность врача",
		exampleValue: "Стоматология общей практики",
		resolverPath: "doctor.specialty",
	},

	// Даты
	{
		token: "ТекущаяДата",
		domain: "date",
		name: "Текущая дата",
		description: "Дата формирования документа в формате ДД.ММ.ГГГГ",
		exampleValue: "03.09.2026",
		resolverPath: "currentDate.short",
	},
	{
		token: "ТекущаяПолнаяДата",
		domain: "date",
		name: "Текущая полная дата прописью",
		description: "Дата прописью по-русски (3 сентября 2026 г.)",
		exampleValue: "03 сентября 2026",
		resolverPath: "currentDate.full",
	},

	// Клиника
	{
		token: "Клиника.Название",
		domain: "clinic",
		name: "Название клиники",
		description: "Фирменное или юридическое наименование медицинской организации",
		exampleValue: "СтомХ стоматология",
		resolverPath: "clinic.name",
	},
	{
		token: "Клиника.ИНН",
		domain: "clinic",
		name: "ИНН клиники",
		description: "Идентификационный номер налогоплательщика клиники",
		exampleValue: "123456789",
		resolverPath: "clinic.inn",
	},
	{
		token: "Клиника.КПП",
		domain: "clinic",
		name: "КПП клиники",
		description: "Код причины постановки на учет",
		exampleValue: "773601001",
		resolverPath: "clinic.kpp",
	},
	{
		token: "Клиника.Адрес",
		domain: "clinic",
		name: "Адрес клиники",
		description: "Юридический и фактический адрес места оказания медицинских услуг",
		exampleValue: "г.Москва ул. Стоматологов, д.15",
		resolverPath: "clinic.address",
	},
	{
		token: "Клиника.Телефон",
		domain: "clinic",
		name: "Телефон клиники",
		description: "Контактный телефон регистратуры клиники",
		exampleValue: "+7(900)123-45-67",
		resolverPath: "clinic.phone",
	},
	{
		token: "Клиника.Лицензия.Номер",
		domain: "clinic",
		name: "Номер медицинской лицензии",
		description: "Регистрационный номер лицензии на осуществление меддеятельности",
		exampleValue: "1234564654",
		resolverPath: "clinic.licenseNumber",
	},
	{
		token: "Клиника.Лицензия.ДатаВыдачи",
		domain: "clinic",
		name: "Дата выдачи лицензии",
		description: "Дата предоставления лицензии (ДД.ММ.ГГГГ)",
		exampleValue: "25.01.2020",
		resolverPath: "clinic.licenseIssuedDate",
	},
	{
		token: "Клиника.Лицензия.СрокДействия",
		domain: "clinic",
		name: "Срок действия лицензии",
		description: "Срок действия или 'Бессрочно'",
		exampleValue: "25.01.2020",
		resolverPath: "clinic.licenseValidity",
	},
	{
		token: "Клиника.Лицензия.КемВыдана",
		domain: "clinic",
		name: "Орган, выдавший лицензию",
		description: "Лицензирующий орган (Министерство / Департамент здравоохранения)",
		exampleValue: "Клуб Стоматологов",
		resolverPath: "clinic.licenseIssuer",
	},

	// Прием
	{
		token: "Прием.Ид",
		domain: "appointment",
		name: "ID приема",
		description: "Идентификатор визита / записи на прием",
		exampleValue: "1",
		resolverPath: "appointment.id",
	},
	{
		token: "Прием.Дата",
		domain: "appointment",
		name: "Дата приема",
		description: "Дата приема в формате ДД.ММ.ГГГГ",
		exampleValue: "05.05.2025",
		resolverPath: "appointment.date",
	},
	{
		token: "Прием.ПолнаяДата",
		domain: "appointment",
		name: "Полная дата приема",
		description: "Дата приема прописью (5 мая 2025 г.)",
		exampleValue: "5 марта 2025",
		resolverPath: "appointment.fullDate",
	},
	{
		token: "Прием.Время",
		domain: "appointment",
		name: "Время приема",
		description: "Время начала приема (ЧЧ:ММ)",
		exampleValue: "12:12",
		resolverPath: "appointment.time",
	},

	// Склад
	{
		token: "Склад.Название",
		domain: "warehouse",
		name: "Название склада",
		description: "Наименование склада хранения материалов",
		exampleValue: "Основной",
		resolverPath: "warehouse.name",
	},
	{
		token: "Склад.Материалы.Название",
		domain: "warehouse",
		name: "Наименование материала",
		description: "Название расходного медицинского материала",
		exampleValue: "Маска",
		resolverPath: "warehouse.materialName",
	},
	{
		token: "Склад.Материалы.МинимальныйПорог",
		domain: "warehouse",
		name: "Минимальный порог остатка",
		description: "Неснижаемый остаток на складе",
		exampleValue: "9",
		resolverPath: "warehouse.minThreshold",
	},
	{
		token: "Склад.Материалы.Остаток",
		domain: "warehouse",
		name: "Остаток материала",
		description: "Текущий фактический остаток материала на складе",
		exampleValue: "7",
		resolverPath: "warehouse.balance",
	},

	// Документ
	{
		token: "Документ.ID",
		domain: "document",
		name: "ID документа",
		description: "Идентификатор документа в архиве",
		exampleValue: "125",
		resolverPath: "document.id",
	},
	{
		token: "Документ.Номер",
		domain: "document",
		name: "Номер документа",
		description: "Регистрационный номер бланка или договора",
		exampleValue: "Б123/ПА",
		resolverPath: "document.number",
	},
	{
		token: "Документ.ДатаНачала",
		domain: "document",
		name: "Дата начала действия",
		description: "Дата начала действия договора или плана",
		exampleValue: "2025-01-01",
		resolverPath: "document.startDate",
	},
	{
		token: "Документ.ДатаОкончания",
		domain: "document",
		name: "Дата окончания действия",
		description: "Дата завершения действия договора или гарантии",
		exampleValue: "2025-01-01",
		resolverPath: "document.endDate",
	},
	// ─── ИДЕНТ (IDENT) & DENTALPRO СОВМЕСТИМОСТЬ: ПЛОСКИЕ ТЕГИ ПАЦИЕНТА ───
	{
		token: "ФАМИЛИЯИмяОтчество",
		domain: "patient",
		name: "ФАМИЛИЯ Имя Отчество пациента",
		description: "ФИО пациента с фамилией заглавными буквами (ИВАНОВ Петр Алексеевич)",
		exampleValue: "ИВАНОВ Петр Алексеевич",
		resolverPath: "patient.lastNameUpperFullName",
	},
	{
		token: "ФамилияИмяОтчество",
		domain: "patient",
		name: "Фамилия Имя Отчество пациента",
		description: "ФИО пациента полностью в формате Фамилия Имя Отчество",
		exampleValue: "Иванов Петр Алексеевич",
		resolverPath: "patient.fullName",
	},
	{
		token: "ФамилияИО",
		domain: "patient",
		name: "Фамилия и инициалы пациента",
		description: "Фамилия и сокращенные инициалы (Иванов П. А.)",
		exampleValue: "Иванов П. А.",
		resolverPath: "patient.initials",
	},
	{
		token: "Фамилия",
		domain: "patient",
		name: "Фамилия пациента",
		description: "Фамилия пациента",
		exampleValue: "Иванов",
		resolverPath: "patient.lastName",
	},
	{
		token: "Имя",
		domain: "patient",
		name: "Имя пациента",
		description: "Имя пациента",
		exampleValue: "Петр",
		resolverPath: "patient.firstName",
	},
	{
		token: "Отчество",
		domain: "patient",
		name: "Отчество пациента",
		description: "Отчество пациента",
		exampleValue: "Алексеевич",
		resolverPath: "patient.middleName",
	},
	{
		token: "ДатаРождения",
		domain: "patient",
		name: "Дата рождения пациента",
		description: "Дата рождения пациента прописью (20 декабря 1985)",
		exampleValue: "20 декабря 1985",
		resolverPath: "patient.birthDateFull",
	},
	{
		token: "ГодРождения",
		domain: "patient",
		name: "Год рождения пациента",
		description: "Год рождения пациента (ГГГГ)",
		exampleValue: "1985",
		resolverPath: "patient.birthYear",
	},
	{
		token: "Возраст",
		domain: "patient",
		name: "Возраст пациента",
		description: "Возраст пациента полных лет",
		exampleValue: "30 лет",
		resolverPath: "patient.age",
	},
	{
		token: "Пол",
		domain: "patient",
		name: "Пол пациента",
		description: "Пол пациента (мужской / женский)",
		exampleValue: "мужской",
		resolverPath: "patient.gender",
	},
	{
		token: "Телефоны",
		domain: "patient",
		name: "Телефоны пациента",
		description: "Контактные телефоны пациента (мобильный и домашний)",
		exampleValue: "+7 (911) 090-55-44; (812) 123-45-67",
		resolverPath: "patient.phones",
	},
	{
		token: "МобТелефон",
		domain: "patient",
		name: "Мобильный телефон пациента",
		description: "Основной мобильный телефон пациента",
		exampleValue: "+7 (911) 090-55-44",
		resolverPath: "patient.mobilePhone",
	},
	{
		token: "ДомТелефон",
		domain: "patient",
		name: "Домашний телефон пациента",
		description: "Стационарный или домашний телефон пациента",
		exampleValue: "(812) 123-45-67",
		resolverPath: "patient.homePhone",
	},
	{
		token: "Email",
		domain: "patient",
		name: "Email пациента",
		description: "Адрес электронной почты пациента",
		exampleValue: "patient@example.ru",
		resolverPath: "patient.email",
	},
	{
		token: "Адрес",
		domain: "patient",
		name: "Адрес проживания пациента",
		description: "Фактический адрес проживания пациента",
		exampleValue: "г. Москва, ул. Ленина, д. 33, кв. 115",
		resolverPath: "patient.address",
	},
	{
		token: "АдресРегистрации",
		domain: "patient",
		name: "Адрес регистрации пациента",
		description: "Адрес постоянной регистрации по паспорту",
		exampleValue: "г. Москва, ул. Ленина, д. 33, кв. 115",
		resolverPath: "patient.registrationAddress",
	},
	{
		token: "ДатаРегистрации",
		domain: "patient",
		name: "Дата регистрации пациента",
		description: "Дата регистрации по месту жительства (ДД.ММ.ГГГГ)",
		exampleValue: "05.04.1994",
		resolverPath: "patient.registrationDate",
	},
	{
		token: "ИНН",
		domain: "patient",
		name: "ИНН пациента",
		description: "Идентификационный номер налогоплательщика",
		exampleValue: "123456789012",
		resolverPath: "patient.inn",
	},
	{
		token: "СНИЛС",
		domain: "patient",
		name: "СНИЛС пациента",
		description: "Страховой номер индивидуального лицевого счета",
		exampleValue: "123-456-789 01",
		resolverPath: "patient.snils",
	},
	{
		token: "ИИН",
		domain: "patient",
		name: "ИИН пациента (Казахстан)",
		description: "Индивидуальный идентификационный номер",
		exampleValue: "760724300757",
		resolverPath: "patient.iin",
	},
	{
		token: "МестоРаботы",
		domain: "patient",
		name: "Место работы пациента",
		description: "Организация или предприятие — место работы",
		exampleValue: "ООО СтомХ",
		resolverPath: "patient.workplace",
	},
	{
		token: "Профессия",
		domain: "patient",
		name: "Профессия пациента",
		description: "Профессия или род занятий",
		exampleValue: "Инженер",
		resolverPath: "patient.profession",
	},
	{
		token: "Полисы",
		domain: "patient",
		name: "Все полисы пациента",
		description: "Сводные данные полисов ОМС и ДМС",
		exampleValue: "ОМС 123-456-789-01",
		resolverPath: "patient.policies",
	},
	{
		token: "Комментарий",
		domain: "patient",
		name: "Клинический комментарий",
		description: "Комментарий к карточке пациента (аллергии, соматика)",
		exampleValue: "Аллергик",
		resolverPath: "patient.comment",
	},
	{
		token: "НомерКарты",
		domain: "patient",
		name: "Номер амбулаторной карты",
		description: "Номер карты пациента",
		exampleValue: "123",
		resolverPath: "patient.cardNumber",
	},
	{
		token: "НомерМедкарты",
		domain: "patient",
		name: "Номер медицинской карты",
		description: "Номер медицинской карты пациента",
		exampleValue: "123",
		resolverPath: "patient.cardNumber",
	},
	{
		token: "ДатаПервогоПриема",
		domain: "patient",
		name: "Дата первого приема прописью",
		description: "Дата первого визита в формате: число месяц год г.",
		exampleValue: "22 мар 2022 г.",
		resolverPath: "patient.firstVisitDate",
	},
	{
		token: "ДатаПервогоПриемаЧислом",
		domain: "patient",
		name: "Дата первого приема числом",
		description: "Дата первого приема в формате ДД.ММ.ГГГГ",
		exampleValue: "22.03.2022",
		resolverPath: "patient.firstVisitDateShort",
	},
	{
		token: "Родитель",
		domain: "patient",
		name: "Данные родителя",
		description: "ФИО родителя из карточки ребенка",
		exampleValue: "Иванов Алексей Иванович",
		resolverPath: "patient.parentName",
	},
	{
		token: "МестоРождения",
		domain: "patient",
		name: "Место рождения пациента",
		description: "Город / населенный пункт места рождения по паспорту",
		exampleValue: "г. Москва",
		resolverPath: "patient.birthPlace",
	},
	{
		token: "Документ",
		domain: "patient",
		name: "Документ удостоверяющий личность",
		description: "Полная сводная строка паспортных данных пациента",
		exampleValue: "Паспорт РФ: 4010 №232567, Выдан: 10.09.2010, ТП № 42, Код подразделения: 600-004",
		resolverPath: "patient.passportFull",
	},
	{
		token: "Документ.ТипДокумента",
		domain: "patient",
		name: "Тип документа пациента",
		description: "Наименование документа (Паспорт РФ, Свидетельство о рождении)",
		exampleValue: "Паспорт РФ",
		resolverPath: "patient.passport.type",
	},
	{
		token: "Документ.СерияНомер",
		domain: "patient",
		name: "Серия и номер документа",
		description: "Серия и номер паспорта через пробел",
		exampleValue: "4010 232567",
		resolverPath: "patient.passport.seriesNumber",
	},
	{
		token: "Документ.СерияНомер.Серия",
		domain: "patient",
		name: "Серия документа",
		description: "Серия паспорта пациента",
		exampleValue: "4010",
		resolverPath: "patient.passport.series",
	},
	{
		token: "Документ.СерияНомер.Номер",
		domain: "patient",
		name: "Номер документа",
		description: "Номер паспорта пациента",
		exampleValue: "232567",
		resolverPath: "patient.passport.number",
	},
	{
		token: "Документ.Выдан",
		domain: "patient",
		name: "Сведения о выдаче документа",
		description: "Строка выдачи паспорта (дата, кем выдан, код)",
		exampleValue: "Выдан: 10.09.2010, ТП № 42, Код подразделения: 420-017",
		resolverPath: "patient.passport.issuedFull",
	},
	{
		token: "Документ.Выдан.ДатаВыдачи",
		domain: "patient",
		name: "Дата выдачи документа",
		description: "Дата выдачи паспорта (ДД.ММ.ГГГГ)",
		exampleValue: "10.09.2010",
		resolverPath: "patient.passport.issuedDate",
	},
	{
		token: "Документ.Выдан.КодПодразделения",
		domain: "patient",
		name: "Код подразделения",
		description: "Код подразделения органа выдачи (XXX-XXX)",
		exampleValue: "420-017",
		resolverPath: "patient.passport.divisionCode",
	},
	{
		token: "Документ.Выдан.КемВыдан",
		domain: "patient",
		name: "Орган выдачи документа",
		description: "Наименование органа, выдавшего паспорт",
		exampleValue: "ТП № 42 ОУФМС",
		resolverPath: "patient.passport.issuedBy",
	},

	// ─── СОМАТИЧЕСКИЙ И АЛЛЕРГОЛОГИЧЕСКИЙ СТАТУС ───
	{
		token: "Пациент.СоматическийСтатус",
		domain: "patient",
		name: "Соматический статус пациента",
		description: "Общий соматический статус (соматически здоров / сопутствующие патологии)",
		exampleValue: "Соматически здоров, хронических заболеваний не выявлено",
		resolverPath: "patient.somaticStatus",
	},
	{
		token: "СоматическийСтатус",
		domain: "patient",
		name: "Соматический статус",
		description: "Соматический статус пациента (алиас)",
		exampleValue: "Соматически здоров, сопутствующих патологий нет",
		resolverPath: "patient.somaticStatus",
	},
	{
		token: "Аллергостатус",
		domain: "patient",
		name: "Аллергологический статус",
		description: "Аллергологический анамнез пациента",
		exampleValue: "Аллергологический анамнез не отягощен",
		resolverPath: "patient.allergyStatus",
	},
	{
		token: "Аллергии",
		domain: "patient",
		name: "Аллергии пациента",
		description: "Перечень выявленных аллергических реакций",
		exampleValue: "Аллергии не выявлены",
		resolverPath: "patient.allergyStatus",
	},
	{
		token: "НепереносимостьПрепаратов",
		domain: "patient",
		name: "Непереносимость лекарственных препаратов",
		description: "Сведения о лекарственной непереносимости",
		exampleValue: "Непереносимость местных анестетиков и антибиотиков отрицает",
		resolverPath: "patient.drugIntolerance",
	},

	// ─── ПРЕДСТАВИТЕЛЬ (ИДЕНТ АЛИАСЫ) ───
	{
		token: "Представитель.ФАМИЛИЯИмяОтчество",
		domain: "representative",
		name: "ФАМИЛИЯ Имя Отчество представителя",
		description: "ФИО законного представителя с фамилией заглавными буквами",
		exampleValue: "ПЕТРОВ Алексей Иванович",
		resolverPath: "representative.lastNameUpperFullName",
	},
	{
		token: "Представитель.ФамилияИмяОтчество",
		domain: "representative",
		name: "Фамилия Имя Отчество представителя",
		description: "ФИО законного представителя полностью",
		exampleValue: "Петров Алексей Иванович",
		resolverPath: "representative.fullName",
	},
	{
		token: "Представитель.ФамилияИО",
		domain: "representative",
		name: "Фамилия и инициалы представителя",
		description: "Фамилия и инициалы представителя (Петров А. И.)",
		exampleValue: "Петров А. И.",
		resolverPath: "representative.initials",
	},
	{
		token: "Представитель.Фамилия",
		domain: "representative",
		name: "Фамилия представителя",
		description: "Фамилия представителя",
		exampleValue: "Петров",
		resolverPath: "representative.lastName",
	},
	{
		token: "Представитель.Имя",
		domain: "representative",
		name: "Имя представителя",
		description: "Имя представителя",
		exampleValue: "Алексей",
		resolverPath: "representative.firstName",
	},
	{
		token: "Представитель.Отчество",
		domain: "representative",
		name: "Отчество представителя",
		description: "Отчество представителя",
		exampleValue: "Иванович",
		resolverPath: "representative.middleName",
	},
	{
		token: "Представитель.ДатаРождения",
		domain: "representative",
		name: "Дата рождения представителя",
		description: "Дата рождения законного представителя",
		exampleValue: "28 января 1960",
		resolverPath: "representative.birthDate",
	},
	{
		token: "Представитель.ГодРождения",
		domain: "representative",
		name: "Год рождения представителя",
		description: "Год рождения представителя (ГГГГ)",
		exampleValue: "1960",
		resolverPath: "representative.birthYear",
	},
	{
		token: "Представитель.Возраст",
		domain: "representative",
		name: "Возраст представителя",
		description: "Возраст представителя в годах",
		exampleValue: "62 года",
		resolverPath: "representative.age",
	},
	{
		token: "Представитель.Пол",
		domain: "representative",
		name: "Пол представителя",
		description: "Пол представителя (мужской / женский)",
		exampleValue: "мужской",
		resolverPath: "representative.gender",
	},
	{
		token: "Представитель.Телефоны",
		domain: "representative",
		name: "Телефоны представителя",
		description: "Контактные телефоны представителя",
		exampleValue: "+7 (973) 014-24-76",
		resolverPath: "representative.phones",
	},
	{
		token: "Представитель.МобТелефон",
		domain: "representative",
		name: "Мобильный телефон представителя",
		description: "Мобильный телефон представителя",
		exampleValue: "+7 (973) 014-24-76",
		resolverPath: "representative.phone",
	},
	{
		token: "Представитель.ДомТелефон",
		domain: "representative",
		name: "Домашний телефон представителя",
		description: "Домашний телефон представителя",
		exampleValue: "(812) 529-89-55",
		resolverPath: "representative.homePhone",
	},
	{
		token: "Представитель.Email",
		domain: "representative",
		name: "Email представителя",
		description: "Адрес электронной почты представителя",
		exampleValue: "representative@ident.ru",
		resolverPath: "representative.email",
	},
	{
		token: "Представитель.АдресРегистрации",
		domain: "representative",
		name: "Адрес регистрации представителя",
		description: "Адрес постоянной регистрации представителя",
		exampleValue: "г. Москва, ул. Арбат, д. 10, кв. 25",
		resolverPath: "representative.address",
	},
	{
		token: "Представитель.ДатаРегистрации",
		domain: "representative",
		name: "Дата регистрации представителя",
		description: "Дата регистрации представителя (ДД.ММ.ГГГГ)",
		exampleValue: "05.05.1995",
		resolverPath: "representative.registrationDate",
	},
	{
		token: "Представитель.ИНН",
		domain: "representative",
		name: "ИНН представителя",
		description: "ИНН законного представителя",
		exampleValue: "780204893183",
		resolverPath: "representative.inn",
	},
	{
		token: "Представитель.ИИН",
		domain: "representative",
		name: "ИИН представителя (Казахстан)",
		description: "ИИН представителя",
		exampleValue: "760720302335",
		resolverPath: "representative.iin",
	},
	{
		token: "Представитель.МестоРождения",
		domain: "representative",
		name: "Место рождения представителя",
		description: "Место рождения представителя по паспорту",
		exampleValue: "г. Вологда",
		resolverPath: "representative.birthPlace",
	},
	{
		token: "Представитель.Документ",
		domain: "representative",
		name: "Документ представителя",
		description: "Полная строка реквизитов документа представителя",
		exampleValue: "Паспорт РФ: 4015 №235542, Выдан: 01.05.2001, ТП № 42, Код подразделения: 600-004",
		resolverPath: "representative.passportFull",
	},
	{
		token: "Представитель.Документ.ТипДокумента",
		domain: "representative",
		name: "Тип документа представителя",
		description: "Тип документа представителя",
		exampleValue: "Паспорт РФ",
		resolverPath: "representative.passport.type",
	},
	{
		token: "Представитель.Документ.СерияНомер",
		domain: "representative",
		name: "Серия и номер документа представителя",
		description: "Серия и номер документа представителя",
		exampleValue: "4010 232567",
		resolverPath: "representative.passport.seriesNumber",
	},
	{
		token: "Представитель.Документ.СерияНомер.Серия",
		domain: "representative",
		name: "Серия документа представителя",
		description: "Серия паспорта представителя",
		exampleValue: "4010",
		resolverPath: "representative.passport.series",
	},
	{
		token: "Представитель.Документ.СерияНомер.Номер",
		domain: "representative",
		name: "Номер документа представителя",
		description: "Номер паспорта представителя",
		exampleValue: "232567",
		resolverPath: "representative.passport.number",
	},
	{
		token: "Представитель.Документ.Выдан",
		domain: "representative",
		name: "Сведения о выдаче документа представителя",
		description: "Строка выдачи документа представителя",
		exampleValue: "Выдан: 10.09.2010, ТП № 42, Код подразделения: 420-017",
		resolverPath: "representative.passport.issuedFull",
	},
	{
		token: "Представитель.Документ.Выдан.ДатаВыдачи",
		domain: "representative",
		name: "Дата выдачи документа представителя",
		description: "Дата выдачи паспорта представителя",
		exampleValue: "10.09.2010",
		resolverPath: "representative.passport.issuedDate",
	},
	{
		token: "Представитель.Документ.Выдан.КодПодразделения",
		domain: "representative",
		name: "Код подразделения представителя",
		description: "Код подразделения паспорта представителя",
		exampleValue: "420-017",
		resolverPath: "representative.passport.divisionCode",
	},
	{
		token: "Представитель.Документ.Выдан.КемВыдан",
		domain: "representative",
		name: "Орган выдачи документа представителя",
		description: "Кем выдан паспорт представителя",
		exampleValue: "ТП № 42 ОУФМС",
		resolverPath: "representative.passport.issuedBy",
	},

	// ─── КЛИНИКА И ТЕКУЩИЙ ПОЛЬЗОВАТЕЛЬ ───
	{
		token: "КомпанияНазвание",
		domain: "clinic",
		name: "Название компании (клиники)",
		description: "Название стоматологической клиники",
		exampleValue: "ООО Денте Премиум",
		resolverPath: "clinic.name",
	},
	{
		token: "КомпанияТелефон",
		domain: "clinic",
		name: "Телефон компании",
		description: "Контактный телефон клиники",
		exampleValue: "+7 (800) 333-09-41",
		resolverPath: "clinic.phone",
	},
	{
		token: "КомпанияАдрес",
		domain: "clinic",
		name: "Адрес компании",
		description: "Юридический и фактический адрес клиники",
		exampleValue: "г. Москва, ул. Стоматологов, д. 15",
		resolverPath: "clinic.address",
	},
	{
		token: "Логотип",
		domain: "clinic",
		name: "Логотип клиники",
		description: "HTML-изображение фирменного логотипа клиники",
		exampleValue: "<img src=\"/logo.png\" alt=\"Логотип\" class=\"clinic-logo\" />",
		resolverPath: "clinic.logoHtml",
	},
	{
		token: "ТекущаяДатаПолная",
		domain: "date",
		name: "Текущая дата полная (алиас)",
		description: "Дата прописью по-русски (3 сентября 2026 г.)",
		exampleValue: "03 сентября 2026",
		resolverPath: "currentDate.full",
	},
	{
		token: "ТекущийПользователь.Должность",
		domain: "administrator",
		name: "Должность текущего пользователя",
		description: "Штатная должность сотрудника, печатающего документ",
		exampleValue: "Администратор",
		resolverPath: "currentUser.position",
	},
	{
		token: "ТекущийПользователь.ФАМИЛИЯИмяОтчество",
		domain: "administrator",
		name: "ФАМИЛИЯ Имя Отчество текущего пользователя",
		description: "ФИО сотрудника с фамилией заглавными буквами",
		exampleValue: "МАРТЮКОВА Галина Александровна",
		resolverPath: "currentUser.lastNameUpperFullName",
	},
	{
		token: "ТекущийПользователь.ФамилияИмяОтчество",
		domain: "administrator",
		name: "Фамилия Имя Отчество текущего пользователя",
		description: "Полное имя сотрудника, печатающего документ",
		exampleValue: "Мартюкова Галина Александровна",
		resolverPath: "currentUser.fullName",
	},
	{
		token: "ТекущийПользователь.ФамилияИО",
		domain: "administrator",
		name: "Фамилия и инициалы текущего пользователя",
		description: "Фамилия и инициалы сотрудника (Мартюкова Г. А.)",
		exampleValue: "Мартюкова Г. А.",
		resolverPath: "currentUser.initials",
	},
	{
		token: "ТекущийПользователь.Фамилия",
		domain: "administrator",
		name: "Фамилия текущего пользователя",
		description: "Фамилия сотрудника клиники",
		exampleValue: "Мартюкова",
		resolverPath: "currentUser.lastName",
	},
	{
		token: "ТекущийПользователь.Имя",
		domain: "administrator",
		name: "Имя текущего пользователя",
		description: "Имя сотрудника клиники",
		exampleValue: "Галина",
		resolverPath: "currentUser.firstName",
	},
	{
		token: "ТекущийПользователь.Отчество",
		domain: "administrator",
		name: "Отчество текущего пользователя",
		description: "Отчество сотрудника клиники",
		exampleValue: "Александровна",
		resolverPath: "currentUser.middleName",
	},

	// ─── ФИНАНСОВЫЕ ТОКЕНЫ И ДЕНЬГИ ПРОПИСЬЮ ───
	{
		token: "Сумма",
		domain: "finance",
		name: "Сумма операции числом и прописью",
		description: "Сумма операции числом и прописью в рублях и копейках",
		exampleValue: "1 000,00 ₽ (Одна тысяча рублей 00 копеек)",
		resolverPath: "financial.amountFull",
	},
	{
		token: "СуммаЧислом",
		domain: "finance",
		name: "Сумма операции числом",
		description: "Сумма операции числом в формате 1 000,00",
		exampleValue: "1 000,00",
		resolverPath: "financial.amountNumeric",
	},
	{
		token: "СуммаПрописью",
		domain: "finance",
		name: "Сумма операции прописью",
		description: "Сумма операции прописью с указанием рублей и копеек",
		exampleValue: "Одна тысяча рублей 00 копеек",
		resolverPath: "financial.amountWords",
	},
	{
		token: "СуммаПрописьюРублей",
		domain: "finance",
		name: "Сумма рублей прописью",
		description: "Целое число рублей прописью со склонением",
		exampleValue: "одна тысяча рублей",
		resolverPath: "financial.amountRublesWords",
	},
	{
		token: "Счет.Сумма",
		domain: "finance",
		name: "Сумма по счету",
		description: "Полная сумма счета с копейками",
		exampleValue: "15 000,00 ₽ (Пятнадцать тысяч рублей 00 копеек)",
		resolverPath: "financial.invoiceAmount",
	},
	{
		token: "Счет.СуммаЧислом",
		domain: "finance",
		name: "Сумма по счету числом",
		description: "Сумма по счету числом",
		exampleValue: "15 000,00",
		resolverPath: "financial.invoiceAmountNumeric",
	},
	{
		token: "Счет.СуммаПрописью",
		domain: "finance",
		name: "Сумма по счету прописью",
		description: "Сумма по счету прописью с копейками",
		exampleValue: "Пятнадцать тысяч рублей 00 копеек",
		resolverPath: "financial.invoiceAmountWords",
	},
	{
		token: "Счет.Номер",
		domain: "finance",
		name: "Номер счета",
		description: "Номер выставленного счета на оплату",
		exampleValue: "СЧ-2026/105",
		resolverPath: "financial.invoiceNumber",
	},
	{
		token: "Счет.Дата",
		domain: "finance",
		name: "Дата счета",
		description: "Дата формирования счета (ДД.ММ.ГГГГ)",
		exampleValue: "03.09.2026",
		resolverPath: "financial.invoiceDate",
	},
	{
		token: "Договор.Сумма",
		domain: "finance",
		name: "Сумма договора",
		description: "Сумма договора на оказание платных медицинских услуг",
		exampleValue: "50 000,00 ₽",
		resolverPath: "financial.contractAmount",
	},
	{
		token: "Договор.СуммаЧислом",
		domain: "finance",
		name: "Сумма договора числом",
		description: "Сумма договора числом",
		exampleValue: "50 000,00",
		resolverPath: "financial.contractAmountNumeric",
	},
	{
		token: "Договор.СуммаПрописью",
		domain: "finance",
		name: "Сумма договора прописью",
		description: "Сумма договора прописью",
		exampleValue: "Пятьдесят тысяч рублей 00 копеек",
		resolverPath: "financial.contractAmountWords",
	},
	{
		token: "Акт.Сумма",
		domain: "finance",
		name: "Сумма акта выполненных работ",
		description: "Сумма по акту сдачи-приемки оказанных услуг",
		exampleValue: "25 000,00 ₽",
		resolverPath: "financial.actAmount",
	},
	{
		token: "Акт.СуммаЧислом",
		domain: "finance",
		name: "Сумма акта числом",
		description: "Сумма акта выполненных работ числом",
		exampleValue: "25 000,00",
		resolverPath: "financial.actAmountNumeric",
	},
	{
		token: "Акт.СуммаПрописью",
		domain: "finance",
		name: "Сумма акта прописью",
		description: "Сумма акта выполненных работ прописью",
		exampleValue: "Двадцать пять тысяч рублей 00 копеек",
		resolverPath: "financial.actAmountWords",
	},

	// ─── КЛИНИЧЕСКИЙ ОСМОТР, ДНЕВНИК И ИСТОРИЯ БОЛЕЗНИ ───
	{
		token: "ДатаОсмотра",
		domain: "clinicalExamination",
		name: "Дата первичного осмотра",
		description: "Дата первичного осмотра в формате ДД.ММ.ГГГГ",
		exampleValue: "03.09.2026",
		resolverPath: "clinicalExamination.examinationDate",
	},
	{
		token: "ДатаЛечения",
		domain: "clinicalExamination",
		name: "Дата лечения",
		description: "Дата проведения лечебного вмешательства",
		exampleValue: "03.09.2026",
		resolverPath: "clinicalExamination.examinationDate",
	},
	{
		token: "ДатаИВремяЛечения",
		domain: "clinicalExamination",
		name: "Дата и время лечения",
		description: "Дата и фактическое время начала приема",
		exampleValue: "03.09.2026 14:30",
		resolverPath: "clinicalExamination.treatmentDateTime",
	},
	{
		token: "ФамилияИОВрача",
		domain: "clinicalExamination",
		name: "Фамилия и инициалы лечащего врача",
		description: "Фамилия и инициалы врача, проводившего осмотр или лечение",
		exampleValue: "Иванов И. И.",
		resolverPath: "clinicalExamination.doctorInitials",
	},
	{
		token: "Диагноз",
		domain: "clinicalExamination",
		name: "Клинический диагноз",
		description: "Основной и сопутствующий клинический диагноз по МКБ-10",
		exampleValue: "K02.1 Кариес дентина",
		resolverPath: "clinicalExamination.diagnosis",
	},
	{
		token: "Жалобы",
		domain: "clinicalExamination",
		name: "Жалобы пациента",
		description: "Субъективные жалобы пациента при обращении",
		exampleValue: "Жалобы на кратковременные боли от сладкого и холодного в зубе 16",
		resolverPath: "clinicalExamination.complaints",
	},
	{
		token: "Анамнез",
		domain: "clinicalExamination",
		name: "Анамнез заболевания",
		description: "Анамнез настоящего заболевания (Anamnesis morbi)",
		exampleValue: "Боли появились около недели назад, ранее зуб не лечен",
		resolverPath: "clinicalExamination.anamnesis",
	},
	{
		token: "ПеренесенныеЗаболевания",
		domain: "clinicalExamination",
		name: "Перенесенные заболевания",
		description: "Перенесенные и сопутствующие соматические заболевания",
		exampleValue: "ОРВИ, детские инфекции; гепатит, туберкулез, ВИЧ отрицает",
		resolverPath: "clinicalExamination.pastDiseases",
	},
	{
		token: "РазвитиеЗаболевания",
		domain: "clinicalExamination",
		name: "Развитие настоящего заболевания",
		description: "Динамика и особенности развития патологического процесса",
		exampleValue: "Процесс прогрессировал постепенно без предшествующего вмешательства",
		resolverPath: "clinicalExamination.diseaseHistory",
	},
	{
		token: "ВнешнийОсмотр",
		domain: "clinicalExamination",
		name: "Внешний осмотр",
		description: "Данные объективного исследования, внешний осмотр ЧЛО",
		exampleValue: "Конфигурация лица не изменена, регионарные лимфоузлы не увеличены, пальпация безболезненна",
		resolverPath: "clinicalExamination.externalExam",
	},
	{
		token: "Прикус",
		domain: "clinicalExamination",
		name: "Прикус",
		description: "Вид прикуса и окклюзионные взаимоотношения",
		exampleValue: "Ортогнатический прикус",
		resolverPath: "clinicalExamination.bite",
	},
	{
		token: "СостояниеСлизистой",
		domain: "clinicalExamination",
		name: "Состояние слизистой оболочки",
		description: "Состояние слизистой оболочки полости рта, десен и неба",
		exampleValue: "Слизистая бледно-розовая, умеренно увлажнена, патологических элементов нет",
		resolverPath: "clinicalExamination.mucousCondition",
	},
	{
		token: "Рентген",
		domain: "clinicalExamination",
		name: "Данные рентгенографии",
		description: "Данные рентгеновских, визиографических и лабораторных исследований",
		exampleValue: "На прицельной рентгенограмме зуба 16: очагов деструкции костной ткани нет",
		resolverPath: "clinicalExamination.xray",
	},
	{
		token: "Объективно",
		domain: "clinicalExamination",
		name: "Объективный статус (Status localis)",
		description: "Данные объективного стоматологического осмотра полости рта",
		exampleValue: "На окклюзионной поверхности зуба 16 глубокая кариозная полость",
		resolverPath: "clinicalExamination.objective",
	},
	{
		token: "Лечение",
		domain: "clinicalExamination",
		name: "Проведенное лечение",
		description: "Подробный протокол проведенного лечения",
		exampleValue: "Препарирование, медикаментозная обработка, пломбирование композитом светового отверждения",
		resolverPath: "clinicalExamination.treatment",
	},
	{
		token: "Рекомендации",
		domain: "clinicalExamination",
		name: "Клинические рекомендации",
		description: "Назначения и рекомендации пациенту после приема",
		exampleValue: "Воздержаться от приема пищи в течение 2 часов, контрольный осмотр через 6 месяцев",
		resolverPath: "clinicalExamination.recommendations",
	},

	// ─── ЗУБНАЯ ФОРМУЛА И ОДОНТОГРАММА ───
	{
		token: "ЗубнаяФормула.Расшифровка",
		domain: "dentalFormula",
		name: "Расшифровка зубной формулы словами",
		description: "Текстовая расшифровка выявленных патологий зубов на русском языке",
		exampleValue: "Кариес: зубы 16, 24; Пломба: зубы 36, 46; Отсутствует: зубы 18, 28, 38, 48; Интактные: остальные зубы",
		resolverPath: "dentalFormula.breakdownText",
	},
	{
		token: "ЗубнаяФормула.Текст",
		domain: "dentalFormula",
		name: "Текстовая расшифровка зубной формулы (алиас)",
		description: "Текстовая расшифровка зубной формулы на русском языке",
		exampleValue: "Кариес: зубы 16, 24; Пломба: зубы 36, 46; Интактные: остальные зубы",
		resolverPath: "dentalFormula.breakdownText",
	},
	{
		token: "ПервичныйОсмотр.ЗубнаяФормула",
		domain: "dentalFormula",
		name: "Зубная формула первичного осмотра (HTML/SVG)",
		description: "Векторная анатомическая схема зубной формулы",
		exampleValue: "<div class=\"dental-formula-svg\">...</div>",
		resolverPath: "dentalFormula.graphicalHtml",
	},
	{
		token: "ЗубнаяФормула",
		domain: "dentalFormula",
		name: "Графическая зубная формула (HTML/SVG)",
		description: "Векторная анатомическая зубная формула",
		exampleValue: "<div class=\"dental-formula-svg\">...</div>",
		resolverPath: "dentalFormula.graphicalHtml",
	},
] as const;

const ALL_FDI_TEETH_NUMBERS: readonly number[] = [
	18, 17, 16, 15, 14, 13, 12, 11,
	21, 22, 23, 24, 25, 26, 27, 28,
	31, 32, 33, 34, 35, 36, 37, 38,
	41, 42, 43, 44, 45, 46, 47, 48,
];

const TEETH_DOCUMENT_TEMPLATE_VARIABLES: DocumentTemplateVariableSpec[] =
	ALL_FDI_TEETH_NUMBERS.flatMap((tooth) => [
		{
			token: String(tooth),
			domain: "dentalFormula",
			name: `Обозначение зуба ${tooth}`,
			description: `Символический код клинического статуса зуба ${tooth} (H, C, P, Pt, П, К, И, 0, R, N)`,
			exampleValue: "C",
			resolverPath: `dentalFormula.teeth.${tooth}.code`,
		},
		{
			token: `${tooth}т`,
			domain: "dentalFormula",
			name: `Статус зуба ${tooth} текстом`,
			description: `Клинический статус зуба ${tooth} на русском языке`,
			exampleValue: "Кариес",
			resolverPath: `dentalFormula.teeth.${tooth}.label`,
		},
	]);

export const ALL_DOCUMENT_TEMPLATE_VARIABLES: readonly DocumentTemplateVariableSpec[] = [
	...STATIC_DOCUMENT_TEMPLATE_VARIABLES,
	...TEETH_DOCUMENT_TEMPLATE_VARIABLES,
];

