/**
 * Полный канонический реестр 74+ стандартизированных токенов подстановки
 * для печатных форм и медицинских документов Минздрава РФ.
 */

export interface DocumentTemplateVariableSpec {
	token: string;
	domain: string;
	name: string;
	description: string;
	exampleValue: string;
	resolverPath: string;
}

export const ALL_DOCUMENT_TEMPLATE_VARIABLES: readonly DocumentTemplateVariableSpec[] = [
	// Пациент
	{
		token: "Пациент.ФИО",
		domain: "patient",
		name: "ФИО пациента",
		description: "Фамилия Имя Отчество пациента полностью",
		exampleValue: "Иванов Петр Алексеевич",
		resolverPath: "patient.fullName",
	},
	{
		token: "Пациент.ID",
		domain: "patient",
		name: "ID пациента",
		description: "Уникальный идентификатор пациента в базе данных",
		exampleValue: "101",
		resolverPath: "patient.id",
	},
	{
		token: "Пациент.НомерКарты",
		domain: "patient",
		name: "Номер амбулаторной карты",
		description: "Номер медицинской карты стоматологического больного 043/у",
		exampleValue: "333",
		resolverPath: "patient.cardNumber",
	},
	{
		token: "Пациент.Фамилия",
		domain: "patient",
		name: "Фамилия пациента",
		description: "Фамилия пациента",
		exampleValue: "Иванов",
		resolverPath: "patient.lastName",
	},
	{
		token: "Пациент.Имя",
		domain: "patient",
		name: "Имя пациента",
		description: "Имя пациента",
		exampleValue: "Петр",
		resolverPath: "patient.firstName",
	},
	{
		token: "Пациент.Отчество",
		domain: "patient",
		name: "Отчество пациента",
		description: "Отчество пациента",
		exampleValue: "Алексеевич",
		resolverPath: "patient.middleName",
	},
	{
		token: "Пациент.Пол",
		domain: "patient",
		name: "Пол пациента",
		description: "Пол пациента (муж / жен)",
		exampleValue: "муж",
		resolverPath: "patient.gender",
	},
	{
		token: "Пациент.Адрес",
		domain: "patient",
		name: "Адрес регистрации пациента",
		description: "Адрес регистрации по паспорту",
		exampleValue: "ул. Ленина, д. 33, кв. 115",
		resolverPath: "patient.address",
	},
	{
		token: "Пациент.Телефон",
		domain: "patient",
		name: "Телефон пациента",
		description: "Основной контактный телефон пациента",
		exampleValue: "+7 911 090 5544",
		resolverPath: "patient.phone",
	},
	{
		token: "Пациент.ИНН",
		domain: "patient",
		name: "ИНН пациента",
		description: "Идентификационный номер налогоплательщика",
		exampleValue: "123456789012",
		resolverPath: "patient.inn",
	},
	{
		token: "Пациент.ФамилияИО",
		domain: "patient",
		name: "Фамилия и инициалы пациента",
		description: "Фамилия и сокращенные инициалы (Иванов П.А.)",
		exampleValue: "Иванов П.А.",
		resolverPath: "patient.initials",
	},
	{
		token: "Пациент.ДеньРождения",
		domain: "patient",
		name: "Дата рождения пациента",
		description: "Дата рождения пациента в формате ДД.ММ.ГГГГ",
		exampleValue: "20.12.1985",
		resolverPath: "patient.birthDate",
	},
	{
		token: "Пациент.Возраст",
		domain: "patient",
		name: "Возраст пациента",
		description: "Полных лет с русским склонением",
		exampleValue: "30 лет",
		resolverPath: "patient.age",
	},
	{
		token: "Пациент.ФактическийАдрес",
		domain: "patient",
		name: "Фактический адрес пациента",
		description: "Адрес фактического проживания",
		exampleValue: "ул. Ленина, д. 33, кв. 115",
		resolverPath: "patient.actualAddress",
	},
	{
		token: "Пациент.Email",
		domain: "patient",
		name: "Электронная почта пациента",
		description: "Email адрес пациента",
		exampleValue: "email@email.ru",
		resolverPath: "patient.email",
	},
	{
		token: "Пациент.СНИЛС",
		domain: "patient",
		name: "СНИЛС пациента",
		description: "Страховой номер индивидуального лицевого счета",
		exampleValue: "123-456-789-01",
		resolverPath: "patient.snils",
	},
	{
		token: "Пациент.Инвалидность",
		domain: "patient",
		name: "Инвалидность пациента",
		description: "Группа инвалидности или отметка об отсутствии",
		exampleValue: "нет",
		resolverPath: "patient.disability",
	},
	{
		token: "Пациент.Льготы",
		domain: "patient",
		name: "Льготы пациента",
		description: "Категория льгот пациента",
		exampleValue: "нет",
		resolverPath: "patient.benefits",
	},
	{
		token: "Пациент.Профессия",
		domain: "patient",
		name: "Профессия пациента",
		description: "Род деятельности или профессия",
		exampleValue: "водитель",
		resolverPath: "patient.profession",
	},
	{
		token: "Пациент.ОсобыеОтметки",
		domain: "patient",
		name: "Особые клинические отметки",
		description: "Аллергологический анамнез, соматические патологии",
		exampleValue: "Аллергия на пенициллин",
		resolverPath: "patient.specialNotes",
	},
	{
		token: "Пациент.Полисы",
		domain: "patient",
		name: "Все полисы пациента",
		description: "Сводные данные полисов ОМС и ДМС",
		exampleValue: "ОМС 123-456-789-01",
		resolverPath: "patient.policies",
	},
	{
		token: "Пациент.ПолисОМС",
		domain: "patient",
		name: "Полис ОМС",
		description: "Номер полиса обязательного медицинского страхования",
		exampleValue: "123-456-789-01",
		resolverPath: "patient.omsPolicy",
	},
	{
		token: "Пациент.ПолисДМС",
		domain: "patient",
		name: "Полис ДМС",
		description: "Номер полиса добровольного медицинского страхования",
		exampleValue: "123-456-789-01",
		resolverPath: "patient.dmsPolicy",
	},
	{
		token: "Пациент.Аванс",
		domain: "patient",
		name: "Аванс / Баланс пациента",
		description: "Текущий финансовый баланс пациента в рублях",
		exampleValue: "25 000",
		resolverPath: "patient.advance",
	},
	{
		token: "Пациент.Паспорт.Номер",
		domain: "patient",
		name: "Паспорт: номер",
		description: "Номер паспорта пациента",
		exampleValue: "123456",
		resolverPath: "patient.passport.number",
	},
	{
		token: "Пациент.Паспорт.СерияНомер",
		domain: "patient",
		name: "Паспорт: серия и номер",
		description: "Серия и номер паспорта пациента через пробел",
		exampleValue: "4510 123456",
		resolverPath: "patient.passport.seriesNumber",
	},
	{
		token: "Пациент.Паспорт.Серия",
		domain: "patient",
		name: "Серия паспорта пациента",
		description: "4 цифры серии паспорта",
		exampleValue: "4321",
		resolverPath: "patient.passport.series",
	},
	{
		token: "Пациент.Паспорт.ДатаВыдачи",
		domain: "patient",
		name: "Дата выдачи паспорта пациента",
		description: "Дата выдачи паспорта (ДД.ММ.ГГГГ)",
		exampleValue: "20.01.2001",
		resolverPath: "patient.passport.issuedDate",
	},
	{
		token: "Пациент.Паспорт.КемВыдан",
		domain: "patient",
		name: "Кем выдан паспорт пациента",
		description: "Орган, выдавший документ, удостоверяющий личность",
		exampleValue: "Отдел УФМС России по г. Москве №133",
		resolverPath: "patient.passport.issuedBy",
	},
	{
		token: "Пациент.Паспорт.КодПодразделения",
		domain: "patient",
		name: "Код подразделения паспорта пациента",
		description: "Код подразделения (XXX-XXX)",
		exampleValue: "123-456",
		resolverPath: "patient.passport.divisionCode",
	},

	// Представитель
	{
		token: "Представитель.ФИО",
		domain: "representative",
		name: "ФИО законного представителя",
		description: "ФИО родителя, опекуна или попечителя полностью",
		exampleValue: "Петров Алексей Иванович",
		resolverPath: "representative.fullName",
	},
	{
		token: "Представитель.ФамилияИнициалы",
		domain: "representative",
		name: "Фамилия и инициалы представителя",
		description: "Фамилия и инициалы представителя",
		exampleValue: "Петров А. И.",
		resolverPath: "representative.initials",
	},
	{
		token: "Представитель.Телефон",
		domain: "representative",
		name: "Телефон представителя",
		description: "Контактный телефон законного представителя",
		exampleValue: "+7 933 090 5544",
		resolverPath: "representative.phone",
	},
	{
		token: "Представитель.Паспорт.Номер",
		domain: "representative",
		name: "Номер паспорта представителя",
		description: "Номер паспорта законного представителя",
		exampleValue: "123456",
		resolverPath: "representative.passport.number",
	},
	{
		token: "Представитель.Паспорт.Серия",
		domain: "representative",
		name: "Серия паспорта представителя",
		description: "Серия паспорта законного представителя",
		exampleValue: "4321",
		resolverPath: "representative.passport.series",
	},
	{
		token: "Представитель.Паспорт.ДатаВыдачи",
		domain: "representative",
		name: "Дата выдачи паспорта представителя",
		description: "Дата выдачи паспорта представителя (ДД.ММ.ГГГГ)",
		exampleValue: "20.01.2001",
		resolverPath: "representative.passport.issuedDate",
	},
	{
		token: "Представитель.Паспорт.КемВыдан",
		domain: "representative",
		name: "Кем выдан паспорт представителя",
		description: "Орган, выдавший паспорт законному представителю",
		exampleValue: "Отдел УФМС России по г. Москве №133",
		resolverPath: "representative.passport.issuedBy",
	},
	{
		token: "Представитель.Паспорт.КодПодразделения",
		domain: "representative",
		name: "Код подразделения представителя",
		description: "Код подразделения органа выдачи паспорта",
		exampleValue: "123-456",
		resolverPath: "representative.passport.divisionCode",
	},
	{
		token: "Представитель.ДеньРождения",
		domain: "representative",
		name: "Дата рождения представителя",
		description: "Дата рождения представителя (ДД.ММ.ГГГГ)",
		exampleValue: "20.12.1985",
		resolverPath: "representative.birthDate",
	},
	{
		token: "Представитель.Адрес",
		domain: "representative",
		name: "Адрес представителя",
		description: "Адрес места жительства законного представителя",
		exampleValue: "ул. Ленина, д. 33, кв. 115",
		resolverPath: "representative.address",
	},
	{
		token: "Представитель.СНИЛС",
		domain: "representative",
		name: "СНИЛС представителя",
		description: "СНИЛС законного представителя",
		exampleValue: "123-456-789-01",
		resolverPath: "representative.snils",
	},
	{
		token: "Представитель.НаОсновании",
		domain: "representative",
		name: "Основание полномочий представителя",
		description: "Документ-основание (Паспорт, Свидетельство о рождении)",
		exampleValue: "Паспорт",
		resolverPath: "representative.basis",
	},
	{
		token: "Представитель.Тип",
		domain: "representative",
		name: "Тип родства законного представителя",
		description: "родитель, опекун, Муж, Жена, Отец, Мать, Дочь, Сын, Сестра, Брат",
		exampleValue: "Отец",
		resolverPath: "representative.relationType",
	},
	{
		token: "Представитель.Основание",
		domain: "representative",
		name: "Основание представителя (алиас)",
		description: "Документ-основание (Паспорт, Свидетельство о рождении)",
		exampleValue: "Паспорт",
		resolverPath: "representative.basis",
	},
	{
		token: "Представитель.Родство",
		domain: "representative",
		name: "Родство представителя (алиас)",
		description: "Отец, Мать, Опекун и т.д.",
		exampleValue: "Мать",
		resolverPath: "representative.relationType",
	},

	// Полномочный
	{
		token: "Полномочный.ФИО",
		domain: "authorizedPerson",
		name: "ФИО уполномоченного лица",
		description: "ФИО лица по доверенности",
		exampleValue: "Петров Алексей Иванович",
		resolverPath: "authorizedPerson.fullName",
	},
	{
		token: "Полномочный.ФамилияИнициалы",
		domain: "authorizedPerson",
		name: "Фамилия и инициалы уполномоченного",
		description: "Фамилия и инициалы поверенного",
		exampleValue: "Петров А.И.",
		resolverPath: "authorizedPerson.initials",
	},
	{
		token: "Полномочный.Телефон",
		domain: "authorizedPerson",
		name: "Телефон уполномоченного лица",
		description: "Телефон поверенного по доверенности",
		exampleValue: "+7 933 090 5544",
		resolverPath: "authorizedPerson.phone",
	},
	{
		token: "Полномочный.Паспорт.Номер",
		domain: "authorizedPerson",
		name: "Номер паспорта уполномоченного",
		description: "Номер паспорта доверенного лица",
		exampleValue: "123456",
		resolverPath: "authorizedPerson.passport.number",
	},
	{
		token: "Полномочный.Паспорт.Серия",
		domain: "authorizedPerson",
		name: "Серия паспорта уполномоченного",
		description: "Серия паспорта доверенного лица",
		exampleValue: "4321",
		resolverPath: "authorizedPerson.passport.series",
	},
	{
		token: "Полномочный.Паспорт.ДатаВыдачи",
		domain: "authorizedPerson",
		name: "Дата выдачи паспорта уполномоченного",
		description: "Дата выдачи паспорта (ДД.ММ.ГГГГ)",
		exampleValue: "20.01.2001",
		resolverPath: "authorizedPerson.passport.issuedDate",
	},
	{
		token: "Полномочный.Паспорт.КемВыдан",
		domain: "authorizedPerson",
		name: "Кем выдан паспорт уполномоченного",
		description: "Орган, выдавший паспорт доверенному лицу",
		exampleValue: "Отдел УФМС России по г. Москве №133",
		resolverPath: "authorizedPerson.passport.issuedBy",
	},
	{
		token: "Полномочный.Паспорт.КодПодразделения",
		domain: "authorizedPerson",
		name: "Код подразделения уполномоченного",
		description: "Код подразделения паспорта доверенного лица",
		exampleValue: "123-456",
		resolverPath: "authorizedPerson.passport.divisionCode",
	},
	{
		token: "Полномочный.ДеньРождения",
		domain: "authorizedPerson",
		name: "Дата рождения уполномоченного",
		description: "Дата рождения доверенного лица (ДД.ММ.ГГГГ)",
		exampleValue: "20.12.1985",
		resolverPath: "authorizedPerson.birthDate",
	},
	{
		token: "Полномочный.Адрес",
		domain: "authorizedPerson",
		name: "Адрес уполномоченного лица",
		description: "Адрес регистрации доверенного лица",
		exampleValue: "ул. Ленина, д. 33, кв. 115",
		resolverPath: "authorizedPerson.address",
	},
	{
		token: "Полномочный.СНИЛС",
		domain: "authorizedPerson",
		name: "СНИЛС уполномоченного лица",
		description: "СНИЛС доверенного лица",
		exampleValue: "123-456-789-01",
		resolverPath: "authorizedPerson.snils",
	},

	// Врачи и персонал
	{
		token: "ПоследнийПриём.Врач.ФИО",
		domain: "doctor",
		name: "ФИО врача последнего приема",
		description: "ФИО врача, проводившего предыдущий прием",
		exampleValue: "Васильев Иван Петрович",
		resolverPath: "lastDoctor.fullName",
	},
	{
		token: "ПоследнийПриём.Врач.ФамилияИнициалы",
		domain: "doctor",
		name: "Фамилия и инициалы врача последнего приема",
		description: "Фамилия и инициалы лечащего врача",
		exampleValue: "Васильев И. П.",
		resolverPath: "lastDoctor.initials",
	},
	{
		token: "ПоследнийПриём.Врач.Должность",
		domain: "doctor",
		name: "Должность врача последнего приема",
		description: "Штатная медицинская должность врача",
		exampleValue: "Врач-стоматолог терапевт",
		resolverPath: "lastDoctor.position",
	},
	{
		token: "ПоследнийПриём.Врач.Специальность",
		domain: "doctor",
		name: "Специальность врача последнего приема",
		description: "Врачебная специальность",
		exampleValue: "Стоматология терапевтическая",
		resolverPath: "lastDoctor.specialty",
	},
	{
		token: "Администратор.ФИО",
		domain: "administrator",
		name: "ФИО администратора",
		description: "ФИО администратора клиники, оформившего документ",
		exampleValue: "Васильев Иван Петрович",
		resolverPath: "administrator.fullName",
	},
	{
		token: "Администратор.ФамилияИнициалы",
		domain: "administrator",
		name: "Фамилия и инициалы администратора",
		description: "Фамилия и инициалы администратора",
		exampleValue: "Васильев И. П.",
		resolverPath: "administrator.initials",
	},
	{
		token: "Администратор.Должность",
		domain: "administrator",
		name: "Должность администратора",
		description: "Штатная должность сотрудника регистратуры",
		exampleValue: "Администратор",
		resolverPath: "administrator.position",
	},
	{
		token: "Администратор.Специальность",
		domain: "administrator",
		name: "Специальность администратора",
		description: "Специальность сотрудника",
		exampleValue: "Администратор клиники",
		resolverPath: "administrator.specialty",
	},
	{
		token: "АктивныйВрач.ФИО",
		domain: "doctor",
		name: "ФИО активного врача",
		description: "ФИО врача текущего приема / подписывающего врача",
		exampleValue: "Васильев Иван Петрович",
		resolverPath: "doctor.fullName",
	},
	{
		token: "АктивныйВрач.ФамилияИнициалы",
		domain: "doctor",
		name: "Фамилия и инициалы активного врача",
		description: "Фамилия и инициалы врача текущего приема",
		exampleValue: "Васильев И. П.",
		resolverPath: "doctor.initials",
	},
	{
		token: "АктивныйВрач.Должность",
		domain: "doctor",
		name: "Должность активного врача",
		description: "Должность врача текущего приема",
		exampleValue: "Врач-стоматолог терапевт",
		resolverPath: "doctor.position",
	},
	{
		token: "АктивныйВрач.Специальность",
		domain: "doctor",
		name: "Специальность активного врача",
		description: "Клиническая специальность врача",
		exampleValue: "Стоматология общей практики",
		resolverPath: "doctor.specialty",
	},

	// Даты
	{
		token: "ТекущаяДата",
		domain: "date",
		name: "Текущая дата",
		description: "Дата формирования документа в формате ДД.ММ.ГГГГ",
		exampleValue: "03.09.2026",
		resolverPath: "currentDate.short",
	},
	{
		token: "ТекущаяПолнаяДата",
		domain: "date",
		name: "Текущая полная дата прописью",
		description: "Дата прописью по-русски (3 сентября 2026 г.)",
		exampleValue: "03 сентября 2026",
		resolverPath: "currentDate.full",
	},

	// Клиника
	{
		token: "Клиника.Название",
		domain: "clinic",
		name: "Название клиники",
		description: "Фирменное или юридическое наименование медицинской организации",
		exampleValue: "СтомХ стоматология",
		resolverPath: "clinic.name",
	},
	{
		token: "Клиника.ИНН",
		domain: "clinic",
		name: "ИНН клиники",
		description: "Идентификационный номер налогоплательщика клиники",
		exampleValue: "123456789",
		resolverPath: "clinic.inn",
	},
	{
		token: "Клиника.КПП",
		domain: "clinic",
		name: "КПП клиники",
		description: "Код причины постановки на учет",
		exampleValue: "773601001",
		resolverPath: "clinic.kpp",
	},
	{
		token: "Клиника.Адрес",
		domain: "clinic",
		name: "Адрес клиники",
		description: "Юридический и фактический адрес места оказания медицинских услуг",
		exampleValue: "г.Москва ул. Стоматологов, д.15",
		resolverPath: "clinic.address",
	},
	{
		token: "Клиника.Телефон",
		domain: "clinic",
		name: "Телефон клиники",
		description: "Контактный телефон регистратуры клиники",
		exampleValue: "+7(900)123-45-67",
		resolverPath: "clinic.phone",
	},
	{
		token: "Клиника.Лицензия.Номер",
		domain: "clinic",
		name: "Номер медицинской лицензии",
		description: "Регистрационный номер лицензии на осуществление меддеятельности",
		exampleValue: "1234564654",
		resolverPath: "clinic.licenseNumber",
	},
	{
		token: "Клиника.Лицензия.ДатаВыдачи",
		domain: "clinic",
		name: "Дата выдачи лицензии",
		description: "Дата предоставления лицензии (ДД.ММ.ГГГГ)",
		exampleValue: "25.01.2020",
		resolverPath: "clinic.licenseIssuedDate",
	},
	{
		token: "Клиника.Лицензия.СрокДействия",
		domain: "clinic",
		name: "Срок действия лицензии",
		description: "Срок действия или 'Бессрочно'",
		exampleValue: "25.01.2020",
		resolverPath: "clinic.licenseValidity",
	},
	{
		token: "Клиника.Лицензия.КемВыдана",
		domain: "clinic",
		name: "Орган, выдавший лицензию",
		description: "Лицензирующий орган (Министерство / Департамент здравоохранения)",
		exampleValue: "Клуб Стоматологов",
		resolverPath: "clinic.licenseIssuer",
	},

	// Прием
	{
		token: "Прием.Ид",
		domain: "appointment",
		name: "ID приема",
		description: "Идентификатор визита / записи на прием",
		exampleValue: "1",
		resolverPath: "appointment.id",
	},
	{
		token: "Прием.Дата",
		domain: "appointment",
		name: "Дата приема",
		description: "Дата приема в формате ДД.ММ.ГГГГ",
		exampleValue: "05.05.2025",
		resolverPath: "appointment.date",
	},
	{
		token: "Прием.ПолнаяДата",
		domain: "appointment",
		name: "Полная дата приема",
		description: "Дата приема прописью (5 мая 2025 г.)",
		exampleValue: "5 марта 2025",
		resolverPath: "appointment.fullDate",
	},
	{
		token: "Прием.Время",
		domain: "appointment",
		name: "Время приема",
		description: "Время начала приема (ЧЧ:ММ)",
		exampleValue: "12:12",
		resolverPath: "appointment.time",
	},

	// Склад
	{
		token: "Склад.Название",
		domain: "warehouse",
		name: "Название склада",
		description: "Наименование склада хранения материалов",
		exampleValue: "Основной",
		resolverPath: "warehouse.name",
	},
	{
		token: "Склад.Материалы.Название",
		domain: "warehouse",
		name: "Наименование материала",
		description: "Название расходного медицинского материала",
		exampleValue: "Маска",
		resolverPath: "warehouse.materialName",
	},
	{
		token: "Склад.Материалы.МинимальныйПорог",
		domain: "warehouse",
		name: "Минимальный порог остатка",
		description: "Неснижаемый остаток на складе",
		exampleValue: "9",
		resolverPath: "warehouse.minThreshold",
	},
	{
		token: "Склад.Материалы.Остаток",
		domain: "warehouse",
		name: "Остаток материала",
		description: "Текущий фактический остаток материала на складе",
		exampleValue: "7",
		resolverPath: "warehouse.balance",
	},

	// Документ
	{
		token: "Документ.ID",
		domain: "document",
		name: "ID документа",
		description: "Идентификатор документа в архиве",
		exampleValue: "125",
		resolverPath: "document.id",
	},
	{
		token: "Документ.Номер",
		domain: "document",
		name: "Номер документа",
		description: "Регистрационный номер бланка или договора",
		exampleValue: "Б123/ПА",
		resolverPath: "document.number",
	},
	{
		token: "Документ.ДатаНачала",
		domain: "document",
		name: "Дата начала действия",
		description: "Дата начала действия договора или плана",
		exampleValue: "2025-01-01",
		resolverPath: "document.startDate",
	},
	{
		token: "Документ.ДатаОкончания",
		domain: "document",
		name: "Дата окончания действия",
		description: "Дата завершения действия договора или гарантии",
		exampleValue: "2025-01-01",
		resolverPath: "document.endDate",
	},
	{
		token: "Документ.ДатаСоздания",
		domain: "document",
		name: "Дата создания документа",
		description: "Дата формирования документа в системе",
		exampleValue: "2025-01-01",
		resolverPath: "document.createdAt",
	},
] as const;
