/**
 * packages/shared/src/pricelist/order804n/surgicalAndOrthoCatalog.ts
 * Layer 1: Statutory Catalog for Surgical, Implantology, Orthopedic & Orthodontic Services.
 *
 * Implements Mandates 8b, 8c, 8e, 8l, 8n, 8s, 8t, 8z.
 * Zero synthetic mocks — 100% statutory Minzdrav Order 804n positions.
 */

import type { StatutoryNomenclatureEntry } from "./types.js";

/**
 * Surgical & dental implantology statutory 804n services.
 */
export const SURGICAL_804N_CATALOG: readonly StatutoryNomenclatureEntry[] = [
	// ─── 6. Хирургическая стоматология (A16.07) ───────────────────────────────
	{
		code: "A16.07.001",
		title: "Удаление зуба (простое / сложное)",
		category: "surgery",
		specialty: "surgeon",
		primaryKeywords: [
			/удалени.*зуб/i,
			/экстракц.*зуб/i,
			/удаление.*постоянн.*зуб/i,
			/удаление.*корн/i,
			/простое.*удаление/i,
			/сложное.*удаление/i,
			/удаление.*однокорневого/i,
			/удаление.*многокорневого/i,
		],
		secondaryKeywords: [/щипцы/i, /элеватор/i, /люксатор/i, /альвеолит/i],
		defaultPriceRub: 3500,
		defaultDurationMinutes: 40,
		taxDeductible: true,
	},
	{
		code: "A16.07.024",
		title: "Удаление ретинированного, дистопированного зуба (зуб мудрости)",
		category: "surgery",
		specialty: "surgeon",
		primaryKeywords: [
			/ретинирован/i,
			/дистопирован/i,
			/зуб.*мудрост/i,
			/восьмерк/i,
			/полуретинирован/i,
			/сверхкомплектн/i,
			/атипичн.*удален/i,
			/удаление.*8[-\s]?ки/i,
		],
		secondaryKeywords: [/выпиливание.*кост/i, /разъединение.*корней/i, /пьезохирурги/i],
		defaultPriceRub: 8500,
		defaultDurationMinutes: 60,
		taxDeductible: true,
	},
	{
		code: "A16.07.017",
		title: "Вскрытие поднадкостничного очага воспаления (периостотомия)",
		category: "surgery",
		specialty: "surgeon",
		primaryKeywords: [
			/периостотоми/i,
			/вскрытие.*абсцесс/i,
			/дренирован.*очаг/i,
			/дренаж/i,
			/разрез.*по.*переходн/i,
			/флюс/i,
		],
		secondaryKeywords: [/гной/i, /резиновый.*дренаж/i],
		defaultPriceRub: 3000,
		defaultDurationMinutes: 20,
		taxDeductible: true,
	},
	{
		code: "A16.07.016",
		title: "Цистотомия или цистэктомия в области челюсти",
		category: "surgery",
		specialty: "surgeon",
		primaryKeywords: [
			/цистэктоми/i,
			/цистотоми/i,
			/кист.*челюст/i,
			/удаление.*кист/i,
			/радукулярн.*кист/i,
		],
		secondaryKeywords: [/оболочк.*кист/i, /костный.*дефект/i],
		defaultPriceRub: 7500,
		defaultDurationMinutes: 45,
		taxDeductible: true,
	},
	{
		code: "A16.07.007",
		title: "Резекция верхушки корня",
		category: "surgery",
		specialty: "surgeon",
		primaryKeywords: [
			/резекци.*верхушк/i,
			/апикоэктоми/i,
			/ретроградн.*пломбирован/i,
		],
		secondaryKeywords: [/апикальн/i, /мта/i, /mta/i],
		defaultPriceRub: 8000,
		defaultDurationMinutes: 60,
		taxDeductible: true,
	},
	{
		code: "A16.07.097",
		title: "Наложение шва на слизистую оболочку рта",
		category: "surgery",
		specialty: "surgeon",
		primaryKeywords: [
			/наложение.*шв/i,
			/ушивание.*лунк/i,
			/шов.*викрил/i,
			/шов.*пролен/i,
			/снятие.*шв/i,
		],
		secondaryKeywords: [/шовный.*материал/i, /атравматическ.*игла/i],
		defaultPriceRub: 1500,
		defaultDurationMinutes: 15,
		taxDeductible: true,
	},
	{
		code: "A16.07.058",
		title: "Пластика уздечки языка или губы (френулопластика)",
		category: "surgery",
		specialty: "surgeon",
		primaryKeywords: [
			/пластик.*уздечк/i,
			/френулопластик/i,
			/френулотоми/i,
			/подрезание.*уздечк/i,
		],
		secondaryKeywords: [/лазер.*уздечк/i, /диастема/i],
		defaultPriceRub: 4500,
		defaultDurationMinutes: 30,
		taxDeductible: true,
	},

	// ─── 7. Дентальная имплантация (A16.07) ───────────────────────────────────
	{
		code: "A16.07.054",
		title: "Внутрикостная дентальная имплантация",
		category: "surgery",
		specialty: "surgeon",
		primaryKeywords: [
			/имплант/i,
			/имплантат/i,
			/установк.*имплант/i,
			/дентальн.*имплантац/i,
			/straumann/i,
			/nobel/i,
			/osstem/i,
			/dentium/i,
			/astra.*tech/i,
			/anyridge/i,
			/neodent/i,
			/(?:^|[\s(])mis(?:[\s)]|$)/i,
			/ankylos/i,
			/hi-tec/i,
			/dentis/i,
			/megagen/i,
		],
		secondaryKeywords: [/хирургическ.*этап/i, /навигационн.*шаблон/i, /титан.*винт/i],
		defaultPriceRub: 35000,
		defaultDurationMinutes: 60,
		taxDeductible: true,
	},
	{
		code: "A16.07.054.005",
		title: "Установка формирователя десны (ФДМ)",
		category: "surgery",
		specialty: "surgeon",
		primaryKeywords: [
			/формировател.*десн/i,
			/установк.*фдм/i,
			/(?:^|[\s(])фдм(?:[\s)]|$)/i,
			/десневой.*формировател/i,
			/раскрытие.*имплант/i,
		],
		secondaryKeywords: [/второй.*этап.*имплант/i, /гингивальный/i],
		defaultPriceRub: 4500,
		defaultDurationMinutes: 30,
		taxDeductible: true,
	},
	{
		code: "A16.07.055",
		title: "Синус-лифтинг (открытый / закрытый)",
		category: "surgery",
		specialty: "surgeon",
		primaryKeywords: [
			/синус[-\s]?лифтинг/i,
			/субантральн.*аугментац/i,
			/поднятие.*дна.*гайморов/i,
			/открыт.*синус/i,
			/закрыт.*синус/i,
		],
		secondaryKeywords: [/гайморов.*пазух/i, /мембран.*шнайдер/i],
		defaultPriceRub: 30000,
		defaultDurationMinutes: 60,
		taxDeductible: true,
	},
	{
		code: "A16.07.041",
		title: "Костная пластика челюстно-лицевой области (НКР)",
		category: "surgery",
		specialty: "surgeon",
		primaryKeywords: [
			/костн.*пластик/i,
			/аугментац.*кост/i,
			/остеопластик/i,
			/направленн.*костн.*регенерирац/i,
			/(?:^|[\s(])нкр(?:[\s)]|$)/i,
			/bio[-\s]?oss/i,
			/костн.*материал/i,
			/коллагенов.*мембран/i,
			/титанов.*сетк/i,
		],
		secondaryKeywords: [/костн.*стружк/i, /расщепление.*гребн/i, /забор.*блока/i],
		defaultPriceRub: 25000,
		defaultDurationMinutes: 60,
		taxDeductible: true,
	},
];

/**
 * Orthopedic, prosthetics & orthodontics statutory 804n services.
 */
export const ORTHO_AND_PROSTHETIC_804N_CATALOG: readonly StatutoryNomenclatureEntry[] = [
	// ─── 8. Ортопедическая стоматология (A16.07, A02.07) ───────────────────────
	{
		code: "A16.07.004",
		title: "Восстановление зуба коронкой постоянной",
		category: "prosthetics",
		specialty: "orthopedist",
		primaryKeywords: [
			/коронк.*постоянн/i,
			/коронк/i,
			/металлокерамик/i,
			/диоксид.*циркони/i,
			/циркони/i,
			/e[-\s]?max/i,
			/цельнокерамическ.*коронк/i,
			/цельнолит.*коронк/i,
			/(?:^|[\s(])мк(?:[\s)]|$).*коронк/i,
			/мостовидн.*протез/i,
			/коронка.*на.*имплант/i,
		],
		secondaryKeywords: [/колпачок/i, /эмаль.*глазурь/i, /культев.*вкладк/i, /абатмент/i],
		defaultPriceRub: 18000,
		defaultDurationMinutes: 60,
		taxDeductible: true,
	},
	{
		code: "A16.07.004.002",
		title: "Изготовление и фиксация временной провизорной коронки",
		category: "prosthetics",
		specialty: "orthopedist",
		primaryKeywords: [
			/временн.*коронк/i,
			/провизорн.*коронк/i,
			/коронк.*pmma/i,
			/пластмассов.*коронк/i,
			/luxatemp/i,
		],
		secondaryKeywords: [/прямой.*метод/i, /лабораторн.*временн/i],
		defaultPriceRub: 2500,
		defaultDurationMinutes: 30,
		taxDeductible: true,
	},
	{
		code: "A16.07.005",
		title: "Восстановление зуба виниром, полукоронкой",
		category: "prosthetics",
		specialty: "orthopedist",
		primaryKeywords: [
			/винир/i,
			/люминир/i,
			/керамическ.*накладк/i,
			/полукоронк/i,
			/вкладк.*overlay/i,
			/вкладк.*inlay/i,
			/керамическ.*вкладк/i,
		],
		secondaryKeywords: [/полевошпат/i, /рефрактор/i, /эмалевый.*срез/i],
		defaultPriceRub: 22000,
		defaultDurationMinutes: 60,
		taxDeductible: true,
	},
	{
		code: "A16.07.003",
		title: "Восстановление зуба культевой вкладкой",
		category: "prosthetics",
		specialty: "orthopedist",
		primaryKeywords: [
			/культев.*вкладк/i,
			/вкладка.*кхс/i,
			/вкладка.*циркони/i,
			/литая.*вкладка/i,
			/штифтов.*культев/i,
		],
		secondaryKeywords: [/разборная.*вкладка/i, /моделировка/i],
		defaultPriceRub: 6500,
		defaultDurationMinutes: 45,
		taxDeductible: true,
	},
	{
		code: "A16.07.006",
		title: "Протезирование съемными бюгельными протезами",
		category: "prosthetics",
		specialty: "orthopedist",
		primaryKeywords: [
			/бюгельн.*протез/i,
			/бюгел/i,
			/кламмерн.*бюгел/i,
			/замков.*бюгел/i,
			/аттачмен.*бюгел/i,
		],
		secondaryKeywords: [/дуга.*протез/i, /литье.*бюгел/i],
		defaultPriceRub: 42000,
		defaultDurationMinutes: 60,
		taxDeductible: true,
	},
	{
		code: "A16.07.023",
		title: "Протезирование зубов съемными пластиночными протезами (полными/частичными)",
		category: "prosthetics",
		specialty: "orthopedist",
		primaryKeywords: [
			/съемн.*протез/i,
			/пластиночн.*протез/i,
			/акри-фри/i,
			/acry[-\s]?free/i,
			/нейлонов.*протез/i,
			/акрилов.*протез/i,
			/полн.*съемн/i,
			/частичн.*съемн/i,
			/протез.*квадротти/i,
			/quattro.*ti/i,
		],
		secondaryKeywords: [/базис.*протез/i, /искусственн.*зубы/i, /гарнитур/i],
		defaultPriceRub: 28000,
		defaultDurationMinutes: 60,
		taxDeductible: true,
	},
	{
		code: "A02.07.010",
		title: "Снятие оттиска с одной челюсти",
		category: "prosthetics",
		specialty: "orthopedist",
		primaryKeywords: [
			/оттиск/i,
			/слепок/i,
			/альгинат/i,
			/силикон/i,
			/а[-\s]?силикон/i,
			/с[-\s]?силикон/i,
			/интраоральн.*сканирован/i,
			/цифров.*слепок/i,
		],
		secondaryKeywords: [/индивидуальн.*ложк/i, /ложка.*слепочн/i],
		defaultPriceRub: 1500,
		defaultDurationMinutes: 20,
		taxDeductible: true,
	},
	{
		code: "A16.07.049",
		title: "Фиксация на постоянный цемент несъемных ортопедических конструкций",
		category: "prosthetics",
		specialty: "orthopedist",
		primaryKeywords: [
			/фиксаци.*коронк/i,
			/постоянн.*цемент/i,
			/fuji/i,
			/цементировк/i,
			/фиксация.*протез/i,
			/цемент.*variolink/i,
		],
		secondaryKeywords: [/стеклоиономер/i, /адгезивн.*фиксац/i],
		defaultPriceRub: 1800,
		defaultDurationMinutes: 20,
		taxDeductible: true,
	},
	{
		code: "A16.07.053",
		title: "Снятие несъемной ортопедической конструкции (коронки)",
		category: "prosthetics",
		specialty: "orthopedist",
		primaryKeywords: [
			/снятие.*коронк/i,
			/распиливание.*коронк/i,
			/снятие.*мостовидн/i,
			/снятие.*протез/i,
		],
		secondaryKeywords: [/коронкосниматель/i, /распил/i],
		defaultPriceRub: 1500,
		defaultDurationMinutes: 20,
		taxDeductible: true,
	},

	// ─── 9. Ортодонтия (A16.07) ───────────────────────────────────────────────
	{
		code: "A16.07.048",
		title: "Ортодонтическая коррекция с применением брекет-систем",
		category: "orthodontics",
		specialty: "orthodontist",
		primaryKeywords: [
			/брекет/i,
			/элайнер/i,
			/damon/i,
			/активаци.*дуг/i,
			/фиксаци.*брекет/i,
			/снятие.*брекет/i,
			/ортодонтическ.*коррекц/i,
			/flexiligner/i,
			/invisalign/i,
			/(?:^|[\s(])spark(?:[\s)]|$)/i,
			/евро капп/i,
		],
		secondaryKeywords: [/лигатур/i, /замок.*брекет/i, /эластик/i, /сепарац/i],
		defaultPriceRub: 35000,
		defaultDurationMinutes: 45,
		taxDeductible: true,
	},
	{
		code: "A16.07.047",
		title: "Ортодонтическая коррекция съемным аппаратом (пластинка / трейнер)",
		category: "orthodontics",
		specialty: "orthodontist",
		primaryKeywords: [
			/ортодонтическ.*пластинк/i,
			/съемн.*ортодонтическ/i,
			/трейнер/i,
			/пластинка.*расширяющ/i,
			/аппарат.*хааса/i,
			/аппарат.*марко.*роса/i,
		],
		secondaryKeywords: [/винт.*бертони/i, /кламмер.*адамс/i],
		defaultPriceRub: 18000,
		defaultDurationMinutes: 30,
		taxDeductible: true,
	},
	{
		code: "A16.07.046",
		title: "Ортодонтическая коррекция с применением ретенционного аппарата (ретейнер)",
		category: "orthodontics",
		specialty: "orthodontist",
		primaryKeywords: [
			/ретейнер/i,
			/фиксаци.*ретейнер/i,
			/ретенционн.*капп/i,
			/проволочн.*ретейнер/i,
			/починка.*ретейнер/i,
		],
		secondaryKeywords: [/ретенция/i, /стабилизац.*прикус/i],
		defaultPriceRub: 6500,
		defaultDurationMinutes: 30,
		taxDeductible: true,
	},
];

/**
 * Combined surgical, implant, orthopedic, prosthetics & orthodontics catalog.
 */
export const SURGICAL_AND_ORTHO_804N_CATALOG: readonly StatutoryNomenclatureEntry[] = [
	...SURGICAL_804N_CATALOG,
	...ORTHO_AND_PROSTHETIC_804N_CATALOG,
];
