/**
 * DENTE Dental CRM — Canonical Minzdrav Order 804n Statutory Nomenclature Registry
 *
 * Implements Mandates 8b, 8c, 8e, 8l, 8n, 8s, 8t, 8z:
 * 1. 100% Statutory Minzdrav Order 804n nomenclature codes (ZERO synthetic mocks).
 * 2. Complete clinical coverage:
 *    - Therapy & Endodontics (A16.07.002, A16.07.008, A16.07.030, A16.07.031, A16.07.082, A16.07.091, A16.07.093)
 *    - Surgery & Extraction (A16.07.001, A16.07.001.001..003, A16.07.024, A16.07.017, A16.07.016, A16.07.007, A16.07.097, A16.07.058)
 *    - Dental Implantology (A16.07.054, A16.07.054.005, A16.07.055, A16.07.041)
 *    - Orthopedics & Prosthetics (A16.07.004, A16.07.004.002, A16.07.005, A16.07.006, A16.07.023, A02.07.010, A16.07.049, A16.07.003, A16.07.053)
 *    - Hygiene & Bleaching (A16.07.051, A16.07.051.001, A16.07.020, A11.07.012, A16.07.050, A14.07.008, A16.07.019)
 *    - Periodontology (A16.07.018, A16.07.026, A16.07.027)
 *    - Radiology & Diagnostics (A06.07.007, A06.07.010, A06.07.013, A06.07.006, B01.065.001, B01.065.002, B01.065.009)
 *    - Anesthesiology (B01.003.004.005, B01.003.004.004, B01.003.004.001)
 *    - Orthodontics (A16.07.048, A16.07.047, A16.07.046)
 *    - Pediatric Dentistry (A16.07.002.009, A16.07.009, A11.07.010, A16.07.057)
 * 3. Clinical stems, synonyms, brand tokens, and statutory defaults.
 */

import type { DentalSpecialty, ServiceCategory } from "../index.js";

export interface StatutoryNomenclatureEntry {
	readonly code: string;
	readonly title: string;
	readonly category: ServiceCategory;
	readonly specialty: DentalSpecialty;
	readonly primaryKeywords: readonly RegExp[];
	readonly secondaryKeywords: readonly RegExp[];
	readonly defaultPriceRub: number;
	readonly defaultDurationMinutes: number;
	readonly taxDeductible: boolean;
}

export const ORDER_804N_STATUTORY_REGISTRY: readonly StatutoryNomenclatureEntry[] = [
	// ─── 1. Консультации и приемы (B01.065) ──────────────────────────────────
	{
		code: "B01.065.001",
		title: "Прием (осмотр, консультация) врача-стоматолога первичный",
		category: "consultation",
		specialty: "therapist",
		primaryKeywords: [
			/первичн.*(?:консультац|осмотр|прием|приём)/i,
			/консультаци.*врач/i,
			/осмотр.*стоматолог/i,
			/осмотр.*врач.*консультац/i,
			/консультация.*пародонтолог/i,
			/составление.*план.*лечен/i,
			/консилиум/i,
		],
		secondaryKeywords: [/анкета/i, /опрос/i, /онкоскрининг/i, /статус/i],
		defaultPriceRub: 1000,
		defaultDurationMinutes: 30,
		taxDeductible: true,
	},
	{
		code: "B01.065.002",
		title: "Прием (осмотр, консультация) врача-стоматолога повторный",
		category: "consultation",
		specialty: "therapist",
		primaryKeywords: [
			/повторн.*(?:консультац|осмотр|прием|приём)/i,
			/контрольн.*осмотр/i,
			/диспансерн.*наблюден/i,
		],
		secondaryKeywords: [/динамик/i, /коррекц.*лечен/i],
		defaultPriceRub: 500,
		defaultDurationMinutes: 20,
		taxDeductible: true,
	},
	{
		code: "B01.065.009",
		title: "Прием (осмотр, консультация) врача-стоматолога детского первичный",
		category: "consultation",
		specialty: "pediatric",
		primaryKeywords: [
			/консультаци.*детск.*стоматолог/i,
			/осмотр.*детск.*стоматолог/i,
			/прием.*детск.*стоматолог/i,
			/адаптационн.*прием/i,
		],
		secondaryKeywords: [/ребенок/i, /детск.*прием/i],
		defaultPriceRub: 1200,
		defaultDurationMinutes: 30,
		taxDeductible: true,
	},
	{
		code: "B01.065.005",
		title: "Прием (осмотр, консультация) врача-стоматолога-ортопеда первичный",
		category: "consultation",
		specialty: "orthopedist",
		primaryKeywords: [
			/консультаци.*ортопед/i,
			/осмотр.*ортопед/i,
			/прием.*ортопед/i,
			/план.*протезирован/i,
		],
		secondaryKeywords: [/диагностическ.*моделирован/i, /восковое/i],
		defaultPriceRub: 1200,
		defaultDurationMinutes: 30,
		taxDeductible: true,
	},
	{
		code: "B01.065.003",
		title: "Прием (осмотр, консультация) врача-стоматолога-хирурга первичный",
		category: "consultation",
		specialty: "surgeon",
		primaryKeywords: [
			/консультаци.*хирург/i,
			/консультаци.*имплантолог/i,
			/осмотр.*хирург/i,
			/прием.*хирург/i,
		],
		secondaryKeywords: [/кт.*планирован/i, /шаблон/i],
		defaultPriceRub: 1200,
		defaultDurationMinutes: 30,
		taxDeductible: true,
	},
	{
		code: "B01.065.007",
		title: "Прием (осмотр, консультация) врача-ортодонта первичный",
		category: "consultation",
		specialty: "orthodontist",
		primaryKeywords: [
			/консультаци.*ортодонт/i,
			/осмотр.*ортодонт/i,
			/диагностик.*прикус/i,
			/расчет.*трг/i,
		],
		secondaryKeywords: [/фотометри/i, /слепки.*диагност/i],
		defaultPriceRub: 1500,
		defaultDurationMinutes: 40,
		taxDeductible: true,
	},

	// ─── 2. Анестезиология (B01.003) ──────────────────────────────────────────
	{
		code: "B01.003.004.005",
		title: "Инфильтрационная анестезия",
		category: "other",
		specialty: "universal",
		primaryKeywords: [
			/инфильтрационн.*анестези/i,
			/ультракаин/i,
			/септанест/i,
			/убистезин/i,
			/артикаин/i,
			/карпульн.*анестези/i,
			/анестезия.*инфильтрац/i,
		],
		secondaryKeywords: [/карпул/i, /обезболиван/i, /адреналин/i],
		defaultPriceRub: 800,
		defaultDurationMinutes: 10,
		taxDeductible: true,
	},
	{
		code: "B01.003.004.004",
		title: "Проводниковая анестезия",
		category: "other",
		specialty: "surgeon",
		primaryKeywords: [
			/проводников.*анестези/i,
			/торусальн.*анестези/i,
			/мандибулярн.*анестези/i,
			/мандибулярк/i,
			/туберальн.*анестези/i,
		],
		secondaryKeywords: [/блокад.*нерв/i, /стволов/i],
		defaultPriceRub: 950,
		defaultDurationMinutes: 15,
		taxDeductible: true,
	},
	{
		code: "B01.003.004.001",
		title: "Аппликационная анестезия",
		category: "other",
		specialty: "universal",
		primaryKeywords: [
			/аппликационн.*анестези/i,
			/гель.*обезболив/i,
			/лидокаин.*спрей/i,
			/дисилан/i,
			/анестезия.*десн.*гель/i,
		],
		secondaryKeywords: [/смазывание/i, /вкусов/i],
		defaultPriceRub: 400,
		defaultDurationMinutes: 5,
		taxDeductible: true,
	},

	// ─── 3. Лучевая диагностика и рентгенология (A06.07) ───────────────────────
	{
		code: "A06.07.007",
		title: "Внутриротовая рентгенография (прицельный снимок / визиограф)",
		category: "imaging",
		specialty: "radiologist",
		primaryKeywords: [
			/прицельн.*снимок/i,
			/визиограф/i,
			/\brvg\b/i,
			/радиовизиограф/i,
			/внутриротов.*рентген/i,
			/дентальн.*снимок/i,
			/снимок.*зуб/i,
		],
		secondaryKeywords: [/датчик/i, /контрольн.*снимок/i],
		defaultPriceRub: 600,
		defaultDurationMinutes: 10,
		taxDeductible: true,
	},
	{
		code: "A06.07.010",
		title: "Панорамная рентгенография челюстей (ОПТГ)",
		category: "imaging",
		specialty: "radiologist",
		primaryKeywords: [
			/(?:^|[\s(])оптг(?:[\s)]|$)/i,
			/панорамн.*снимок/i,
			/ортопантомограмм/i,
			/обзорн.*снимок.*челюст/i,
		],
		secondaryKeywords: [/пленка/i, /диск/i, /челюст/i],
		defaultPriceRub: 1500,
		defaultDurationMinutes: 15,
		taxDeductible: true,
	},
	{
		code: "A06.07.013",
		title: "Компьютерная томография челюстно-лицевой области (КЛКТ / КТ 3D)",
		category: "imaging",
		specialty: "radiologist",
		primaryKeywords: [
			/(?:^|[\s(])клкт(?:[\s)]|$)/i,
			/(?:^|[\s(])кт(?:[\s)]|$).*челюст/i,
			/компьютерн.*томограф/i,
			/3d[-\s]?снимок/i,
			/томографи.*чло/i,
			/конусно[-\s]?лучев/i,
			/кт.*двух.*челюст/i,
			/кт.*сегмент/i,
			/исследование.*на.*диск/i,
			/запись.*исследования/i,
		],
		secondaryKeywords: [/dicom/i, /запись.*на.*диск/i, /fov/i, /носитель/i, /cd[-\s]?диск/i],
		defaultPriceRub: 3500,
		defaultDurationMinutes: 20,
		taxDeductible: true,
	},
	{
		code: "A06.07.006",
		title: "Телерентгенография челюстей (ТРГ в боковой проекции)",
		category: "imaging",
		specialty: "radiologist",
		primaryKeywords: [
			/телерентгенограф/i,
			/телерентгенограмм/i,
			/трг.*боков/i,
			/трг.*прям/i,
			/(?:^|[\s(])трг(?:[\s)]|$)/i,
		],
		secondaryKeywords: [/цефалометри/i, /ортодонтическ.*снимок/i],
		defaultPriceRub: 2000,
		defaultDurationMinutes: 15,
		taxDeductible: true,
	},

	// ─── 4. Терапевтическая стоматология (A16.07) ─────────────────────────────
	{
		code: "A16.07.002",
		title: "Восстановление зуба пломбой (лечение кариеса)",
		category: "therapy",
		specialty: "therapist",
		primaryKeywords: [
			/кариес/i,
			/пломб/i,
			/реставрац.*зуб/i,
			/светоотвержд.*пломб/i,
			/фотополимер/i,
			/световая.*пломба/i,
			/композит/i,
			/клиновидн.*дефект/i,
			/эстетическ.*реставрац/i,
			/эмаль/i,
			/дентин/i,
			/filtek/i,
			/estelite/i,
			/gradia/i,
			/градиа/i,
			/charisma/i,
		],
		secondaryKeywords: [/изолирующ.*прокладк/i, /коффердам/i, /матрица/i, /бондинг/i],
		defaultPriceRub: 4500,
		defaultDurationMinutes: 45,
		taxDeductible: true,
	},
	{
		code: "A16.07.031",
		title: "Препарирование твердых тканей зуба при лечении кариеса",
		category: "therapy",
		specialty: "therapist",
		primaryKeywords: [
			/препарирован.*зуб/i,
			/некрэктоми/i,
			/раскрытие.*кариозн.*полост/i,
			/формирование.*полост/i,
		],
		secondaryKeywords: [/бор/i, /водное.*охлаждение/i],
		defaultPriceRub: 1200,
		defaultDurationMinutes: 20,
		taxDeductible: true,
	},
	{
		code: "A16.07.008",
		title: "Пломбирование корневого канала зуба (эндодонтия)",
		category: "therapy",
		specialty: "therapist",
		primaryKeywords: [
			/пульпит/i,
			/периодонтит/i,
			/корнев.*канал/i,
			/эндодонт/i,
			/депульпир/i,
			/обтурац.*канал/i,
			/гуттаперч/i,
			/пломбирование.*канал/i,
			/латеральн.*конденсац/i,
			/вертикальн.*конденсац/i,
			/термафил/i,
			/лечение.*канал/i,
		],
		secondaryKeywords: [/апекслокац/i, /силер/i, /биокерамик/i, /ah.*plus/i],
		defaultPriceRub: 5500,
		defaultDurationMinutes: 60,
		taxDeductible: true,
	},
	{
		code: "A16.07.030",
		title: "Инструментальная и медикаментозная обработка корневого канала",
		category: "therapy",
		specialty: "therapist",
		primaryKeywords: [
			/механическ.*обработк.*канал/i,
			/инструментальн.*обработк.*канал/i,
			/медикаментозн.*обработк.*канал/i,
			/эндодонтическ.*обработк.*канал/i,
			/обработк.*корнев.*канал/i,
			/ротационн.*файл/i,
			/расширение.*канал/i,
			/прохождение.*канал/i,
			/эндомотор/i,
			/протейпер/i,
		],
		secondaryKeywords: [/гипохлорит/i, /эдта/i, /ирригаци/i, /ультразвук.*активац/i],
		defaultPriceRub: 3500,
		defaultDurationMinutes: 45,
		taxDeductible: true,
	},
	{
		code: "A16.07.082",
		title: "Распломбирование корневого канала",
		category: "therapy",
		specialty: "therapist",
		primaryKeywords: [
			/распломбиров/i,
			/перелечиван.*канал/i,
			/извлечение.*штифт/i,
			/извлечение.*вкладк/i,
			/извлечение.*обломк.*инструмент/i,
			/удаление.*гуттаперч/i,
		],
		secondaryKeywords: [/резорцин.*формалин/i, /фосфат.*цемент/i, /микроскоп/i],
		defaultPriceRub: 2500,
		defaultDurationMinutes: 45,
		taxDeductible: true,
	},
	{
		code: "A16.07.091",
		title: "Временное пломбирование лекарственным препаратом корневого канала",
		category: "therapy",
		specialty: "therapist",
		primaryKeywords: [
			/временн.*пломбирован.*канал/i,
			/каласепт/i,
			/метапекс/i,
			/кальци/i,
			/гидроокис.*кальци/i,
			/лечебн.*повязк.*канал/i,
			/паста.*в.*канал/i,
		],
		secondaryKeywords: [/дентин.*паста/i, /септомп/i],
		defaultPriceRub: 2000,
		defaultDurationMinutes: 30,
		taxDeductible: true,
	},
	{
		code: "A16.07.093",
		title: "Фиксация внутриканального штифта",
		category: "therapy",
		specialty: "therapist",
		primaryKeywords: [
			/стекловолоконн.*штифт/i,
			/анкерн.*штифт/i,
			/внутриканальн.*штифт/i,
			/установка.*штифт/i,
			/фиксация.*штифт/i,
		],
		secondaryKeywords: [/корневой.*штифт/i, /билд.*ап/i, /build.*up/i],
		defaultPriceRub: 2800,
		defaultDurationMinutes: 30,
		taxDeductible: true,
	},

	// ─── 5. Профессиональная гигиена и пародонтология (A16.07, A11.07, A14.07) ─
	{
		code: "A16.07.051",
		title: "Профессиональная гигиена полости рта и зубов",
		category: "hygiene",
		specialty: "hygienist",
		primaryKeywords: [
			/профессиональн.*гигиен/i,
			/профгигиен/i,
			/комплексн.*чистк/i,
			/чистк.*зуб/i,
			/гигиеническ.*чистк/i,
			/гигиена.*полост.*рта/i,
		],
		secondaryKeywords: [/полировка/i, /паста/i, /индивидуальн.*гигиен/i],
		defaultPriceRub: 4500,
		defaultDurationMinutes: 60,
		taxDeductible: true,
	},
	{
		code: "A16.07.020",
		title: "Удаление наддесневых и поддесневых зубных отложений ультразвуком",
		category: "hygiene",
		specialty: "hygienist",
		primaryKeywords: [
			/ультразвук.*чистк/i,
			/скейлинг/i,
			/снятие.*камн/i,
			/удаление.*камн/i,
			/зубн.*камен/i,
			/зубн.*отложен/i,
			/снятие.*зубн.*отложен/i,
			/удаление.*зубн.*отложен/i,
			/ультразвук/i,
			/наддеснев.*отложен/i,
			/поддеснев.*отложен/i,
		],
		secondaryKeywords: [/пьезо/i, /скейлер/i],
		defaultPriceRub: 2500,
		defaultDurationMinutes: 30,
		taxDeductible: true,
	},
	{
		code: "A16.07.051.001",
		title: "Воздушно-абразивная обработка зубов (AirFlow)",
		category: "hygiene",
		specialty: "hygienist",
		primaryKeywords: [
			/air[-\s]?flow/i,
			/аир[-\s]?флоу/i,
			/воздушно[-\s]?абразивн/i,
			/порошк.*чистк/i,
			/снятие.*налет.*курильщик/i,
			/снятие.*пигмент/i,
		],
		secondaryKeywords: [/глицин/i, /сода/i, /эритритол/i],
		defaultPriceRub: 2500,
		defaultDurationMinutes: 30,
		taxDeductible: true,
	},
	{
		code: "A11.07.012",
		title: "Глубокое фторирование эмали зуба",
		category: "hygiene",
		specialty: "hygienist",
		primaryKeywords: [
			/фторирован/i,
			/фторлак/i,
			/реминерализац/i,
			/глубок.*фторир/i,
			/бифлюорид/i,
			/эмаль[-\s]?герметизирующ.*ликвид/i,
		],
		secondaryKeywords: [/бифлюорид/i, /аппликация.*фтор/i, /капа.*фтор/i],
		defaultPriceRub: 1200,
		defaultDurationMinutes: 15,
		taxDeductible: true,
	},
	{
		code: "A16.07.050",
		title: "Профессиональное отбеливание зубов",
		category: "hygiene",
		specialty: "hygienist",
		primaryKeywords: [
			/отбеливан.*зуб/i,
			/zoom/i,
			/amazing.*white/i,
			/(?:^|[\s(])flash(?:[\s)]|$)/i,
			/клиническ.*отбеливан/i,
			/капп.*для.*отбеливан/i,
			/домашн.*отбеливан/i,
			/лазерн.*отбеливан/i,
		],
		secondaryKeywords: [/пероксид.*водород/i, /гель.*отбеливан/i, /коффердам/i],
		defaultPriceRub: 25000,
		defaultDurationMinutes: 90,
		taxDeductible: true,
	},
	{
		code: "A14.07.008",
		title: "Обучение гигиене полости рта и зубов, подбор средств гигиены",
		category: "hygiene",
		specialty: "hygienist",
		primaryKeywords: [
			/обучение.*гигиен/i,
			/подбор.*средств.*гигиен/i,
			/подбор.*средств.*уход/i,
			/урок.*гигиен/i,
			/контролируемая.*чистка/i,
		],
		secondaryKeywords: [/индекс.*гигиен/i, /мотивация/i],
		defaultPriceRub: 800,
		defaultDurationMinutes: 20,
		taxDeductible: true,
	},
	{
		code: "A16.07.018",
		title: "Закрытый кюретаж при заболеваниях пародонта",
		category: "periodontology",
		specialty: "periodontist",
		primaryKeywords: [
			/кюретаж/i,
			/пародонтальн.*карман/i,
			/vector[-\s]?терапи/i,
			/вектор[-\s]?терапи/i,
			/пародонтит/i,
			/закрыт.*кюретаж/i,
			/открыт.*кюретаж/i,
		],
		secondaryKeywords: [/кюрета.*грейси/i, /грануляц/i],
		defaultPriceRub: 3500,
		defaultDurationMinutes: 45,
		taxDeductible: true,
	},
	{
		code: "A16.07.019",
		title: "Временное шинирование при заболеваниях пародонта",
		category: "periodontology",
		specialty: "periodontist",
		primaryKeywords: [
			/шинирован/i,
			/гласспан/i,
			/ribbond/i,
			/стекловолоконн.*шин/i,
			/подвижност.*зуб.*шин/i,
		],
		secondaryKeywords: [/подвижн.*зуб/i, /фиксаци.*блоком/i],
		defaultPriceRub: 2200,
		defaultDurationMinutes: 30,
		taxDeductible: true,
	},
	{
		code: "A16.07.026",
		title: "Гингивопластика (пластика десны)",
		category: "surgery",
		specialty: "periodontist",
		primaryKeywords: [
			/гингивопластик/i,
			/пластик.*десн/i,
			/вестибулопластик/i,
			/удлинение.*коронков.*част/i,
		],
		secondaryKeywords: [/соединительнотканн.*трансплантат/i, /сдт/i, /сст/i],
		defaultPriceRub: 4500,
		defaultDurationMinutes: 45,
		taxDeductible: true,
	},
	{
		code: "A16.07.027",
		title: "Медикаментозная обработка пародонтальных карманов",
		category: "periodontology",
		specialty: "periodontist",
		primaryKeywords: [
			/обработка.*пародонтальн.*карман/i,
			/инстилляци.*пародонтальн/i,
			/лечебн.*повязк.*пародонт/i,
			/аппликация.*десн/i,
		],
		secondaryKeywords: [/метрогил/i, /хлоргексидин.*гель/i],
		defaultPriceRub: 1200,
		defaultDurationMinutes: 20,
		taxDeductible: true,
	},

	// ─── 6. Хирургическая стоматология (A16.07) ───────────────────────────────
	{
		code: "A16.07.001",
		title: "Удаление зуба (простое / сложное)",
		category: "surgery",
		specialty: "surgeon",
		primaryKeywords: [
			/удалени.*зуб/i,
			/экстракц.*зуб/i,
			/удаление.*постоянн.*зуб/i,
			/удаление.*корн/i,
			/простое.*удаление/i,
			/сложное.*удаление/i,
			/удаление.*однокорневого/i,
			/удаление.*многокорневого/i,
		],
		secondaryKeywords: [/щипцы/i, /элеватор/i, /люксатор/i, /альвеолит/i],
		defaultPriceRub: 3500,
		defaultDurationMinutes: 40,
		taxDeductible: true,
	},
	{
		code: "A16.07.024",
		title: "Удаление ретинированного, дистопированного зуба (зуб мудрости)",
		category: "surgery",
		specialty: "surgeon",
		primaryKeywords: [
			/ретинирован/i,
			/дистопирован/i,
			/зуб.*мудрост/i,
			/восьмерк/i,
			/полуретинирован/i,
			/сверхкомплектн/i,
			/атипичн.*удален/i,
			/удаление.*8[-\s]?ки/i,
		],
		secondaryKeywords: [/выпиливание.*кост/i, /разъединение.*корней/i, /пьезохирурги/i],
		defaultPriceRub: 8500,
		defaultDurationMinutes: 60,
		taxDeductible: true,
	},
	{
		code: "A16.07.017",
		title: "Вскрытие поднадкостничного очага воспаления (периостотомия)",
		category: "surgery",
		specialty: "surgeon",
		primaryKeywords: [
			/периостотоми/i,
			/вскрытие.*абсцесс/i,
			/дренирован.*очаг/i,
			/дренаж/i,
			/разрез.*по.*переходн/i,
			/флюс/i,
		],
		secondaryKeywords: [/гной/i, /резиновый.*дренаж/i],
		defaultPriceRub: 3000,
		defaultDurationMinutes: 20,
		taxDeductible: true,
	},
	{
		code: "A16.07.016",
		title: "Цистотомия или цистэктомия в области челюсти",
		category: "surgery",
		specialty: "surgeon",
		primaryKeywords: [
			/цистэктоми/i,
			/цистотоми/i,
			/кист.*челюст/i,
			/удаление.*кист/i,
			/радукулярн.*кист/i,
		],
		secondaryKeywords: [/оболочк.*кист/i, /костный.*дефект/i],
		defaultPriceRub: 7500,
		defaultDurationMinutes: 45,
		taxDeductible: true,
	},
	{
		code: "A16.07.007",
		title: "Резекция верхушки корня",
		category: "surgery",
		specialty: "surgeon",
		primaryKeywords: [
			/резекци.*верхушк/i,
			/апикоэктоми/i,
			/ретроградн.*пломбирован/i,
		],
		secondaryKeywords: [/апикальн/i, /мта/i, /mta/i],
		defaultPriceRub: 8000,
		defaultDurationMinutes: 60,
		taxDeductible: true,
	},
	{
		code: "A16.07.097",
		title: "Наложение шва на слизистую оболочку рта",
		category: "surgery",
		specialty: "surgeon",
		primaryKeywords: [
			/наложение.*шв/i,
			/ушивание.*лунк/i,
			/шов.*викрил/i,
			/шов.*пролен/i,
			/снятие.*шв/i,
		],
		secondaryKeywords: [/шовный.*материал/i, /атравматическ.*игла/i],
		defaultPriceRub: 1500,
		defaultDurationMinutes: 15,
		taxDeductible: true,
	},
	{
		code: "A16.07.058",
		title: "Пластика уздечки языка или губы (френулопластика)",
		category: "surgery",
		specialty: "surgeon",
		primaryKeywords: [
			/пластик.*уздечк/i,
			/френулопластик/i,
			/френулотоми/i,
			/подрезание.*уздечк/i,
		],
		secondaryKeywords: [/лазер.*уздечк/i, /диастема/i],
		defaultPriceRub: 4500,
		defaultDurationMinutes: 30,
		taxDeductible: true,
	},

	// ─── 7. Дентальная имплантация (A16.07) ───────────────────────────────────
	{
		code: "A16.07.054",
		title: "Внутрикостная дентальная имплантация",
		category: "surgery",
		specialty: "surgeon",
		primaryKeywords: [
			/имплант/i,
			/имплантат/i,
			/установк.*имплант/i,
			/дентальн.*имплантац/i,
			/straumann/i,
			/nobel/i,
			/osstem/i,
			/dentium/i,
			/astra.*tech/i,
			/anyridge/i,
			/neodent/i,
			/(?:^|[\s(])mis(?:[\s)]|$)/i,
			/ankylos/i,
			/hi-tec/i,
			/dentis/i,
			/megagen/i,
		],
		secondaryKeywords: [/хирургическ.*этап/i, /навигационн.*шаблон/i, /титан.*винт/i],
		defaultPriceRub: 35000,
		defaultDurationMinutes: 60,
		taxDeductible: true,
	},
	{
		code: "A16.07.054.005",
		title: "Установка формирователя десны (ФДМ)",
		category: "surgery",
		specialty: "surgeon",
		primaryKeywords: [
			/формировател.*десн/i,
			/установк.*фдм/i,
			/(?:^|[\s(])фдм(?:[\s)]|$)/i,
			/десневой.*формировател/i,
			/раскрытие.*имплант/i,
		],
		secondaryKeywords: [/второй.*этап.*имплант/i, /гингивальный/i],
		defaultPriceRub: 4500,
		defaultDurationMinutes: 30,
		taxDeductible: true,
	},
	{
		code: "A16.07.055",
		title: "Синус-лифтинг (открытый / закрытый)",
		category: "surgery",
		specialty: "surgeon",
		primaryKeywords: [
			/синус[-\s]?лифтинг/i,
			/субантральн.*аугментац/i,
			/поднятие.*дна.*гайморов/i,
			/открыт.*синус/i,
			/закрыт.*синус/i,
		],
		secondaryKeywords: [/гайморов.*пазух/i, /мембран.*шнайдер/i],
		defaultPriceRub: 30000,
		defaultDurationMinutes: 60,
		taxDeductible: true,
	},
	{
		code: "A16.07.041",
		title: "Костная пластика челюстно-лицевой области (НКР)",
		category: "surgery",
		specialty: "surgeon",
		primaryKeywords: [
			/костн.*пластик/i,
			/аугментац.*кост/i,
			/остеопластик/i,
			/направленн.*костн.*регенерирац/i,
			/(?:^|[\s(])нкр(?:[\s)]|$)/i,
			/bio[-\s]?oss/i,
			/костн.*материал/i,
			/коллагенов.*мембран/i,
			/титанов.*сетк/i,
		],
		secondaryKeywords: [/костн.*стружк/i, /расщепление.*гребн/i, /забор.*блока/i],
		defaultPriceRub: 25000,
		defaultDurationMinutes: 60,
		taxDeductible: true,
	},

	// ─── 8. Ортопедическая стоматология (A16.07, A02.07) ───────────────────────
	{
		code: "A16.07.004",
		title: "Восстановление зуба коронкой постоянной",
		category: "prosthetics",
		specialty: "orthopedist",
		primaryKeywords: [
			/коронк.*постоянн/i,
			/коронк/i,
			/металлокерамик/i,
			/диоксид.*циркони/i,
			/циркони/i,
			/e[-\s]?max/i,
			/цельнокерамическ.*коронк/i,
			/цельнолит.*коронк/i,
			/(?:^|[\s(])мк(?:[\s)]|$).*коронк/i,
			/мостовидн.*протез/i,
			/коронка.*на.*имплант/i,
		],
		secondaryKeywords: [/колпачок/i, /эмаль.*глазурь/i, /культев.*вкладк/i, /абатмент/i],
		defaultPriceRub: 18000,
		defaultDurationMinutes: 60,
		taxDeductible: true,
	},
	{
		code: "A16.07.004.002",
		title: "Изготовление и фиксация временной провизорной коронки",
		category: "prosthetics",
		specialty: "orthopedist",
		primaryKeywords: [
			/временн.*коронк/i,
			/провизорн.*коронк/i,
			/коронк.*pmma/i,
			/пластмассов.*коронк/i,
			/luxatemp/i,
		],
		secondaryKeywords: [/прямой.*метод/i, /лабораторн.*временн/i],
		defaultPriceRub: 2500,
		defaultDurationMinutes: 30,
		taxDeductible: true,
	},
	{
		code: "A16.07.005",
		title: "Восстановление зуба виниром, полукоронкой",
		category: "prosthetics",
		specialty: "orthopedist",
		primaryKeywords: [
			/винир/i,
			/люминир/i,
			/керамическ.*накладк/i,
			/полукоронк/i,
			/вкладк.*overlay/i,
			/вкладк.*inlay/i,
			/керамическ.*вкладк/i,
		],
		secondaryKeywords: [/полевошпат/i, /рефрактор/i, /эмалевый.*срез/i],
		defaultPriceRub: 22000,
		defaultDurationMinutes: 60,
		taxDeductible: true,
	},
	{
		code: "A16.07.003",
		title: "Восстановление зуба культевой вкладкой",
		category: "prosthetics",
		specialty: "orthopedist",
		primaryKeywords: [
			/культев.*вкладк/i,
			/вкладка.*кхс/i,
			/вкладка.*циркони/i,
			/литая.*вкладка/i,
			/штифтов.*культев/i,
		],
		secondaryKeywords: [/разборная.*вкладка/i, /моделировка/i],
		defaultPriceRub: 6500,
		defaultDurationMinutes: 45,
		taxDeductible: true,
	},
	{
		code: "A16.07.006",
		title: "Протезирование съемными бюгельными протезами",
		category: "prosthetics",
		specialty: "orthopedist",
		primaryKeywords: [
			/бюгельн.*протез/i,
			/бюгел/i,
			/кламмерн.*бюгел/i,
			/замков.*бюгел/i,
			/аттачмен.*бюгел/i,
		],
		secondaryKeywords: [/дуга.*протез/i, /литье.*бюгел/i],
		defaultPriceRub: 42000,
		defaultDurationMinutes: 60,
		taxDeductible: true,
	},
	{
		code: "A16.07.023",
		title: "Протезирование зубов съемными пластиночными протезами (полными/частичными)",
		category: "prosthetics",
		specialty: "orthopedist",
		primaryKeywords: [
			/съемн.*протез/i,
			/пластиночн.*протез/i,
			/акри-фри/i,
			/acry[-\s]?free/i,
			/нейлонов.*протез/i,
			/акрилов.*протез/i,
			/полн.*съемн/i,
			/частичн.*съемн/i,
			/протез.*квадротти/i,
			/quattro.*ti/i,
		],
		secondaryKeywords: [/базис.*протез/i, /искусственн.*зубы/i, /гарнитур/i],
		defaultPriceRub: 28000,
		defaultDurationMinutes: 60,
		taxDeductible: true,
	},
	{
		code: "A02.07.010",
		title: "Снятие оттиска с одной челюсти",
		category: "prosthetics",
		specialty: "orthopedist",
		primaryKeywords: [
			/оттиск/i,
			/слепок/i,
			/альгинат/i,
			/силикон/i,
			/а[-\s]?силикон/i,
			/с[-\s]?силикон/i,
			/интраоральн.*сканирован/i,
			/цифров.*слепок/i,
		],
		secondaryKeywords: [/индивидуальн.*ложк/i, /ложка.*слепочн/i],
		defaultPriceRub: 1500,
		defaultDurationMinutes: 20,
		taxDeductible: true,
	},
	{
		code: "A16.07.049",
		title: "Фиксация на постоянный цемент несъемных ортопедических конструкций",
		category: "prosthetics",
		specialty: "orthopedist",
		primaryKeywords: [
			/фиксаци.*коронк/i,
			/постоянн.*цемент/i,
			/fuji/i,
			/цементировк/i,
			/фиксация.*протез/i,
			/цемент.*variolink/i,
		],
		secondaryKeywords: [/стеклоиономер/i, /адгезивн.*фиксац/i],
		defaultPriceRub: 1800,
		defaultDurationMinutes: 20,
		taxDeductible: true,
	},
	{
		code: "A16.07.053",
		title: "Снятие несъемной ортопедической конструкции (коронки)",
		category: "prosthetics",
		specialty: "orthopedist",
		primaryKeywords: [
			/снятие.*коронк/i,
			/распиливание.*коронк/i,
			/снятие.*мостовидн/i,
			/снятие.*протез/i,
		],
		secondaryKeywords: [/коронкосниматель/i, /распил/i],
		defaultPriceRub: 1500,
		defaultDurationMinutes: 20,
		taxDeductible: true,
	},

	// ─── 9. Ортодонтия (A16.07) ───────────────────────────────────────────────
	{
		code: "A16.07.048",
		title: "Ортодонтическая коррекция с применением брекет-систем",
		category: "orthodontics",
		specialty: "orthodontist",
		primaryKeywords: [
			/брекет/i,
			/элайнер/i,
			/damon/i,
			/активаци.*дуг/i,
			/фиксаци.*брекет/i,
			/снятие.*брекет/i,
			/ортодонтическ.*коррекц/i,
			/flexiligner/i,
			/invisalign/i,
			/(?:^|[\s(])spark(?:[\s)]|$)/i,
			/евро капп/i,
		],
		secondaryKeywords: [/лигатур/i, /замок.*брекет/i, /эластик/i, /сепарац/i],
		defaultPriceRub: 35000,
		defaultDurationMinutes: 45,
		taxDeductible: true,
	},
	{
		code: "A16.07.047",
		title: "Ортодонтическая коррекция съемным аппаратом (пластинка / трейнер)",
		category: "orthodontics",
		specialty: "orthodontist",
		primaryKeywords: [
			/ортодонтическ.*пластинк/i,
			/съемн.*ортодонтическ/i,
			/трейнер/i,
			/пластинка.*расширяющ/i,
			/аппарат.*хааса/i,
			/аппарат.*марко.*роса/i,
		],
		secondaryKeywords: [/винт.*бертони/i, /кламмер.*адамс/i],
		defaultPriceRub: 18000,
		defaultDurationMinutes: 30,
		taxDeductible: true,
	},
	{
		code: "A16.07.046",
		title: "Ортодонтическая коррекция с применением ретенционного аппарата (ретейнер)",
		category: "orthodontics",
		specialty: "orthodontist",
		primaryKeywords: [
			/ретейнер/i,
			/фиксаци.*ретейнер/i,
			/ретенционн.*капп/i,
			/проволочн.*ретейнер/i,
			/починка.*ретейнер/i,
		],
		secondaryKeywords: [/ретенция/i, /стабилизац.*прикус/i],
		defaultPriceRub: 6500,
		defaultDurationMinutes: 30,
		taxDeductible: true,
	},

	// ─── 10. Детская стоматология (A16.07, A11.07) ────────────────────────────
	{
		code: "A16.07.002.009",
		title: "Лечение кариеса временного (молочного) зуба",
		category: "therapy",
		specialty: "pediatric",
		primaryKeywords: [
			/молочн.*зуб.*пломб/i,
			/кариес.*молочн/i,
			/лечение.*кариес.*дет/i,
			/лечение.*кариес.*молочн/i,
			/цветн.*пломб/i,
			/twinky.*star/i,
			/витремер.*дет/i,
		],
		secondaryKeywords: [/серебрение/i],
		defaultPriceRub: 3000,
		defaultDurationMinutes: 30,
		taxDeductible: true,
	},
	{
		code: "A16.07.009",
		title: "Пульпотомия (ампутация пульпы молочного зуба)",
		category: "therapy",
		specialty: "pediatric",
		primaryKeywords: [
			/пульпотоми/i,
			/ампутаци.*пульп.*молочн/i,
			/пульпит.*молочн.*зуб/i,
			/пульпит.*детск/i,
		],
		secondaryKeywords: [/пульпотек/i, /формокрезол/i],
		defaultPriceRub: 3500,
		defaultDurationMinutes: 30,
		taxDeductible: true,
	},
	{
		code: "A11.07.010",
		title: "Серебрение твердых тканей зуба",
		category: "therapy",
		specialty: "pediatric",
		primaryKeywords: [
			/серебрени/i,
			/сафорайд/i,
			/аргенат/i,
			/нитрат.*серебр/i,
		],
		secondaryKeywords: [/детск.*зуб/i],
		defaultPriceRub: 800,
		defaultDurationMinutes: 15,
		taxDeductible: true,
	},
	{
		code: "A16.07.057",
		title: "Герметизация фиссур зуба",
		category: "hygiene",
		specialty: "pediatric",
		primaryKeywords: [
			/герметизаци.*фиссур/i,
			/неинвазивн.*герметизац/i,
			/инвазивн.*герметизац/i,
			/силант/i,
			/запечатывание.*фиссур/i,
		],
		secondaryKeywords: [/фиссур/i, /профилактик.*кариес/i],
		defaultPriceRub: 1800,
		defaultDurationMinutes: 20,
		taxDeductible: true,
	},
	{
		code: "A16.07.001.001",
		title: "Удаление временного (молочного) зуба",
		category: "surgery",
		specialty: "pediatric",
		primaryKeywords: [
			/удаление.*молочн.*зуб/i,
			/удаление.*временн.*зуб/i,
			/удаление.*подвижн.*молочн/i,
			/экстракция.*молочн/i,
		],
		secondaryKeywords: [/смена.*прикус/i, /физиологическ.*рассасыван/i],
		defaultPriceRub: 1800,
		defaultDurationMinutes: 20,
		taxDeductible: true,
	},
];
