import type { MigrationEntityKind } from "@dental/shared";
import type { VendorFieldRule } from "../types.js";

/**
 * Обобщённый российский профиль. Применяется, когда ни один конкретный не
 * опознан, и покрывает главный реальный случай: таблица, собранная
 * администратором в Excel руками.
 *
 * Живёт отдельно от VENDOR_PROFILES, потому что не должен участвовать в
 * состязании за лучшее совпадение — он всегда доступен как основа.
 */
export const GENERIC_RU_RULES: Partial<
	Record<MigrationEntityKind, VendorFieldRule[]>
> = {
	patient: [
		{
			columns: [
				"id",
				"код",
				"номер",
				"no",
				"№",
				"номеркарты",
				"карта",
				"кодпациента",
				"внешнийид",
				"externalid",
			],
			targetField: "patient.externalId",
		},
		{
			columns: [
				"фио",
				"фиополностью",
				"пациент",
				"клиент",
				"имяпациента",
				"полноеимя",
				"наименование",
				"fio",
				"fullname",
				"name",
				"patient",
				"patientname",
				"client",
			],
			targetField: "patient.fullName",
		},
		{
			columns: ["фамилия", "surname", "lastname", "lname", "familiya", "fam"],
			targetField: "patient.lastName",
		},
		{
			columns: ["имя", "firstname", "fname", "imya"],
			targetField: "patient.firstName",
		},
		{
			columns: ["отчество", "middlename", "patronymic", "otchestvo", "otch"],
			targetField: "patient.middleName",
		},
		{
			columns: [
				"датарождения",
				"дата рождения",
				"др",
				"дррождения",
				"рождение",
				"деньрождения",
				"birthdate",
				"birthday",
				"dob",
				"dateofbirth",
				"datarojdeniya",
				"datarojd",
			],
			targetField: "patient.birthDate",
		},
		{
			columns: [
				"телефон",
				"тел",
				"мобильный",
				"мобильныйтелефон",
				"сотовый",
				"номертелефона",
				"контакт",
				"контактныйтелефон",
				"whatsapp",
				"phone",
				"tel",
				"telephone",
				"mobile",
				"cellphone",
				"mobilephone",
				"telefon",
			],
			targetField: "patient.phone",
		},
		{
			columns: [
				"телефон2",
				"второйтелефон",
				"доптелефон",
				"дополнительныйтелефон",
				"домашнийтелефон",
				"рабочийтелефон",
				"phone2",
				"secondphone",
				"workphone",
				"homephone",
			],
			targetField: "patient.secondaryPhone",
		},
		{
			columns: [
				"email",
				"почта",
				"электроннаяпочта",
				"элпочта",
				"мейл",
				"мыло",
				"mail",
				"emailaddress",
			],
			targetField: "patient.email",
		},
		{ columns: ["пол", "gender", "sex"], targetField: "patient.gender" },
		{
			columns: [
				"адрес",
				"адреспроживания",
				"адресрегистрации",
				"address",
				"street",
				"city",
				"город",
			],
			targetField: "patient.address",
		},
		{
			columns: [
				"комментарий",
				"коммент",
				"примечание",
				"примечания",
				"заметка",
				"заметки",
				"описание",
				"прочее",
				"инфо",
				"comment",
				"comments",
				"note",
				"notes",
				"memo",
				"remark",
				"description",
			],
			targetField: "patient.notes",
		},
		{
			columns: [
				"статус",
				"состояние",
				"активен",
				"архив",
				"status",
				"patstatus",
			],
			targetField: "patient.status",
		},
		{
			columns: [
				"датасоздания",
				"датарегистрации",
				"созданадата",
				"created",
				"createdat",
				"regdate",
			],
			targetField: "patient.createdAt",
		},
	],
	doctor: [
		{
			columns: ["id", "код", "кодврача", "doctorid", "provnum", "provider"],
			targetField: "doctor.externalId",
		},
		{
			columns: [
				"фио",
				"врач",
				"доктор",
				"специалист",
				"doctor",
				"provider",
				"fullname",
			],
			targetField: "doctor.fullName",
		},
		{
			columns: [
				"специальность",
				"специализация",
				"должность",
				"specialty",
				"speciality",
				"position",
			],
			targetField: "doctor.specialty",
		},
		{ columns: ["телефон", "тел", "phone"], targetField: "doctor.phone" },
		{ columns: ["email", "почта"], targetField: "doctor.email" },
	],
	service: [
		{
			columns: ["id", "код", "кодуслуги", "артикул", "serviceid", "code"],
			targetField: "service.externalId",
		},
		{
			columns: [
				"кодуслуги",
				"кодпономенклатуре",
				"код804н",
				"кодминздрава",
				"кодпоприказу",
				"код804",
				"номенклатура",
				"кодпосправочнику",
				"артикул",
				"код",
				"шифр",
				"code",
				"servicecode",
			],
			targetField: "service.code",
		},
		{
			columns: [
				"услуга",
				"наименование",
				"название",
				"наименованиеуслуги",
				"service",
				"name",
				"description",
			],
			targetField: "service.name",
		},
		{
			columns: [
				"цена",
				"стоимость",
				"прайс",
				"суммауслуги",
				"price",
				"fee",
				"amount",
				"cost",
			],
			targetField: "service.priceRub",
		},
	],
	appointment: [
		{
			columns: ["id", "код", "номерзаписи", "apptid", "aptnum"],
			targetField: "appointment.externalId",
		},
		{
			columns: [
				"пациент",
				"кодпациента",
				"номеркарты",
				"фиопациента",
				"patient",
				"patnum",
				"patientid",
			],
			targetField: "appointment.patientRef",
		},
		{
			columns: [
				"врач",
				"доктор",
				"кодврача",
				"специалист",
				"doctor",
				"provider",
				"provnum",
			],
			targetField: "appointment.doctorRef",
		},
		{
			columns: [
				"дата",
				"датаприема",
				"датавремя",
				"начало",
				"времяначала",
				"datetime",
				"startsat",
				"aptdatetime",
				"startdatetime",
				"date",
			],
			targetField: "appointment.startsAt",
		},
		{
			columns: [
				"окончание",
				"времяокончания",
				"конец",
				"endsat",
				"enddatetime",
			],
			targetField: "appointment.endsAt",
		},
		{
			columns: [
				"длительность",
				"продолжительность",
				"минут",
				"duration",
				"length",
				"minutes",
			],
			targetField: "appointment.durationMinutes",
		},
		{
			columns: ["статус", "состояние", "status", "aptstatus"],
			targetField: "appointment.status",
		},
		{
			columns: [
				"повод",
				"причина",
				"услуга",
				"назначение",
				"reason",
				"procdescript",
				"description",
			],
			targetField: "appointment.reason",
		},
		{
			columns: [
				"комментарий",
				"примечание",
				"коммент",
				"comment",
				"note",
				"notes",
			],
			targetField: "appointment.comment",
		},
	],
	visit: [
		{
			columns: ["id", "код", "номерприема", "visitid"],
			targetField: "visit.externalId",
		},
		{
			columns: ["пациент", "кодпациента", "номеркарты", "patient", "patnum"],
			targetField: "visit.patientRef",
		},
		{
			columns: ["дата", "датаприема", "датапосещения", "date", "visitdate"],
			targetField: "visit.date",
		},
		{
			columns: [
				"жалобы",
				"жалоба",
				"обращение",
				"complaint",
				"complaints",
				"chiefcomplaint",
			],
			targetField: "visit.complaint",
		},
		{
			columns: [
				"анамнез",
				"анамнезжизни",
				"историязаболевания",
				"anamnesis",
				"history",
			],
			targetField: "visit.anamnesis",
		},
		{
			columns: [
				"объективно",
				"объективныйстатус",
				"осмотр",
				"статус",
				"objective",
				"examination",
			],
			targetField: "visit.objectiveStatus",
		},
		{
			columns: [
				"диагноз",
				"диагнозпомкб",
				"коддиагноза",
				"диагнозкод",
				"мкб",
				"мкб10",
				"icd",
				"icd10",
				"кодпоэкб",
				"заключениедиагноз",
				"diagnosis",
				"dx",
			],
			targetField: "visit.diagnosis",
		},
		{
			columns: [
				"планлечения",
				"лечение",
				"проведенолечение",
				"treatment",
				"treatmentplan",
				"plan",
			],
			targetField: "visit.treatmentPlan",
		},
		{
			columns: [
				"заключение",
				"рекомендации",
				"итог",
				"summary",
				"recommendations",
				"conclusion",
			],
			targetField: "visit.doctorSummary",
		},
	],
	payment: [
		{
			columns: [
				"id",
				"код",
				"номер",
				"номерчека",
				"номердокумента",
				"paynum",
				"paymentid",
				"receiptno",
			],
			targetField: "payment.externalId",
		},
		{
			columns: [
				"пациент",
				"кодпациента",
				"номеркарты",
				"плательщик",
				"patient",
				"patnum",
				"patientid",
			],
			targetField: "payment.patientRef",
		},
		{
			columns: ["приемid", "кодприема", "визит", "visitid", "procnum"],
			targetField: "payment.visitRef",
		},
		{
			columns: [
				"сумма",
				"суммаоплаты",
				"оплачено",
				"квитанция",
				"итого",
				"стоимость",
				"amount",
				"payamt",
				"sum",
				"total",
				"paid",
			],
			targetField: "payment.amountRub",
		},
		{
			columns: [
				"способоплаты",
				"видоплаты",
				"типоплаты",
				"форма оплаты",
				"method",
				"paytype",
				"paymentmethod",
			],
			targetField: "payment.method",
		},
		{
			columns: ["статус", "состояниеоплаты", "status", "paystatus"],
			targetField: "payment.status",
		},
		{
			columns: [
				"дата",
				"датаоплаты",
				"датаплатежа",
				"paiddate",
				"paydate",
				"date",
			],
			targetField: "payment.paidAt",
		},
		{
			columns: [
				"комментарий",
				"примечание",
				"назначение",
				"назначениеплатежа",
				"note",
				"paynote",
				"comment",
			],
			targetField: "payment.note",
		},
	],
	tooth_state: [
		{
			columns: ["пациент", "кодпациента", "номеркарты", "patient", "patnum"],
			targetField: "toothState.patientRef",
		},
		{
			columns: [
				"зуб",
				"номерзуба",
				"зубformula",
				"tooth",
				"toothnum",
				"toothcode",
			],
			targetField: "toothState.toothCode",
		},
		{
			columns: [
				"состояние",
				"диагноззуба",
				"статус",
				"condition",
				"state",
				"diagnosis",
			],
			targetField: "toothState.condition",
		},
		{
			columns: ["комментарий", "примечание", "note", "comment"],
			targetField: "toothState.note",
		},
	],
};
