import type { DicomGpuRenderPlan, DicomViewerToolStateBundleResponse, ImagingSourceKind } from "@dental/shared";
import type { CtPlanningGeometrySummary } from "./ctPlanningGeometry";
import type { CtPlanningExportScenarioSummary } from "./ctPlanningExportScenarioSummary";
import type { CtPlanningImplantModelPlan } from "./ctPlanningImplantModel";
import type { CtPlanningMeasurementPlan } from "./ctPlanningMeasurementPlan";
import type { CtPlanningReconstructionPlan } from "./ctPlanningReconstruction";
import type { CtPlanningValidationSummary, CtPlanningValidationStatus } from "./ctPlanningValidation";

export type CtPlanningExportOwner = "doctor" | "admin" | "lab";
export type CtPlanningExportStatus = "ready" | "warning" | "blocked";

export type CtPlanningExportLane = {
  id: string;
  owner: CtPlanningExportOwner;
  title: string;
  status: CtPlanningExportStatus;
  value: string;
  detail: string;
  nextAction: string;
};

export type CtPlanningExportFact = {
  id: string;
  title: string;
  tone: CtPlanningExportStatus;
  value: string;
  detail: string;
};

export type CtPlanningRuntimeSourceMode = "local_offline_available" | "remote_online_required" | "server_or_uploaded_copy";
export type CtPlanningRuntimeExecutionLane =
  | "metadata_only_no_pixels"
  | "mobile_or_constrained_preview"
  | "desktop_browser_planning_preview"
  | "desktop_app_or_external_diagnostic";

export type CtPlanningRuntimeTruthPolicy = {
  version: "dental-crm-ct-runtime-truth-v1";
  sourceMode: CtPlanningRuntimeSourceMode;
  executionLane: CtPlanningRuntimeExecutionLane;
  memoryBudgetClass: DicomGpuRenderPlan["memoryBudgetClass"];
  hardwareQualityWeight: number;
  progressiveSliceWindowCap: number;
  targetSliceBatch: number;
  estimatedGpuMemoryMb: number;
  diagnosticPixelPolicy: DicomGpuRenderPlan["diagnosticPixelPolicy"];
  containsDiagnosticPixels: false;
  containsMeshGeometry: false;
  browserStoresHeavyGeometry: false;
  heavyDataOwner: "external_viewer_or_local_3d_module";
  summary: string;
};

export type CtPlanningExportPacket = {
  version: "dental-crm-ct-planning-export-v1";
  modelOutputKind: "planning_parameters_only";
  cadExportReady: false;
  surfaceModelRequired: true;
  outputBoundarySummary: string;
  runtimeTruthPolicy: CtPlanningRuntimeTruthPolicy;
  activeQuickActionId: string | null;
  activeScenarioSummary: CtPlanningExportScenarioSummary | null;
  volumeReady: boolean;
  score: number;
  status: CtPlanningExportStatus;
  title: string;
  handoffSummary: string;
  nextAction: string;
  clinicalFacts: CtPlanningExportFact[];
  lanes: CtPlanningExportLane[];
  missingArtifacts: string[];
};

function exportStatusFromValidation(status: CtPlanningValidationStatus): CtPlanningExportStatus {
  if (status === "pass") return "ready";
  if (status === "warn") return "warning";
  return "blocked";
}

function laneStatus(ready: boolean, partial: boolean): CtPlanningExportStatus {
  if (ready) return "ready";
  if (partial) return "warning";
  return "blocked";
}

function exportFact(id: string, title: string, tone: CtPlanningExportStatus, value: string, detail: string): CtPlanningExportFact {
  return { id, title, tone, value, detail };
}

function uniqueList(values: string[]) {
  return Array.from(new Set(values.filter(Boolean))).slice(0, 8);
}

function statusTitle(status: CtPlanningExportStatus) {
  if (status === "ready") return "готов к передаче";
  if (status === "warning") return "черновик плана";
  return "нельзя отдавать дальше";
}

const exportOutputBoundarySummary = "Route/planning bundle only; CAD/STL is generated by lab/local bridge, not CRM browser.";

function sourceModeFor(sourceKind: ImagingSourceKind | null | undefined): CtPlanningRuntimeSourceMode {
  if (sourceKind === "dicomweb" || sourceKind === "pacs") return "remote_online_required";
  if (sourceKind === "dicom_file" || sourceKind === "folder_watch" || sourceKind === "twain_wia" || sourceKind === "sensor_bridge") {
    return "local_offline_available";
  }
  return "server_or_uploaded_copy";
}

function executionLaneFor(renderPlan: DicomGpuRenderPlan | null): CtPlanningRuntimeExecutionLane {
  if (!renderPlan || renderPlan.textureStrategy === "metadata_only" || renderPlan.diagnosticPixelPolicy === "metadata_only_no_pixels") {
    return "metadata_only_no_pixels";
  }
  if (renderPlan.diagnosticPixelPolicy === "desktop_app_or_external_review" || renderPlan.textureStrategy === "external_viewer") {
    return "desktop_app_or_external_diagnostic";
  }
  if (renderPlan.hardwareQualityWeight <= 0.35 || renderPlan.memoryBudgetClass === "minimum" || renderPlan.memoryBudgetClass === "constrained") {
    return "mobile_or_constrained_preview";
  }
  return "desktop_browser_planning_preview";
}

function clampRuntimeWeight(value: number | null | undefined) {
  return typeof value === "number" && Number.isFinite(value) ? Math.min(1, Math.max(0, Math.round(value * 100) / 100)) : 0;
}

export function buildCtPlanningRuntimeTruthPolicy(input: {
  renderPlan: DicomGpuRenderPlan | null;
  sourceKind: ImagingSourceKind | null | undefined;
}): CtPlanningRuntimeTruthPolicy {
  const renderPlan = input.renderPlan;
  const executionLane = executionLaneFor(renderPlan);
  const sourceMode = sourceModeFor(input.sourceKind);
  const hardwareQualityWeight = clampRuntimeWeight(renderPlan?.hardwareQualityWeight ?? 0);
  const progressiveSliceWindowCap = Math.max(1, renderPlan?.progressiveSliceWindowCap ?? 1);
  const targetSliceBatch = Math.max(1, Math.min(renderPlan?.targetSliceBatch ?? 1, progressiveSliceWindowCap));
  const memoryBudgetClass = renderPlan?.memoryBudgetClass ?? "minimum";
  const estimatedGpuMemoryMb = Math.max(0, renderPlan?.estimatedGpuMemoryMb ?? 0);
  const diagnosticPixelPolicy = renderPlan?.diagnosticPixelPolicy ?? "metadata_only_no_pixels";
  return {
    version: "dental-crm-ct-runtime-truth-v1",
    sourceMode,
    executionLane,
    memoryBudgetClass,
    hardwareQualityWeight,
    progressiveSliceWindowCap,
    targetSliceBatch,
    estimatedGpuMemoryMb,
    diagnosticPixelPolicy,
    containsDiagnosticPixels: false,
    containsMeshGeometry: false,
    browserStoresHeavyGeometry: false,
    heavyDataOwner: "external_viewer_or_local_3d_module",
    summary:
      "CRM packet contains planning metadata and bounded viewer policy only; CT pixels, skull/surface meshes, and CAD geometry stay in the external viewer or local 3D module."
  };
}

export function buildCtPlanningExportPacket(input: {
  toolStateBundle: DicomViewerToolStateBundleResponse | null;
  activeQuickActionId?: string | null;
  geometrySummary: CtPlanningGeometrySummary;
  validationSummary: CtPlanningValidationSummary;
  readinessScore: number;
  totalTasks: number;
  blockedTasks: number;
  volumeBlockedTasks: number;
  unsavedArtifactCount: number;
  measurementPlan: CtPlanningMeasurementPlan;
  implantModelPlan: CtPlanningImplantModelPlan;
  reconstructionPlan: CtPlanningReconstructionPlan;
  hasImplantPlan: boolean;
  hasPanoramicRoute: boolean;
  hasCanalRoute: boolean;
  hasGuideRoute: boolean;
}): CtPlanningExportPacket {
  const runtimeTruthPolicy = buildCtPlanningRuntimeTruthPolicy({
    renderPlan: input.toolStateBundle?.renderPlan ?? null,
    sourceKind: input.toolStateBundle?.seriesRef.sourceKind
  });
  const validationStatus = exportStatusFromValidation(input.validationSummary.status);
  const volumeReady = input.volumeBlockedTasks === 0;
  const transferReady = Boolean(input.toolStateBundle) && volumeReady;
  const transferPartial = Boolean(input.toolStateBundle);
  const routeReadyCount = [input.hasPanoramicRoute, input.hasCanalRoute, input.hasGuideRoute].filter(Boolean).length;
  const opgReconstructionReady = input.reconstructionPlan.status === "ready" && input.reconstructionPlan.crossSectionCount > 0;
  const measurementReadyCount = input.measurementPlan.readyCardCount;
  const implantModelReady = input.implantModelPlan.status === "ready";
  const labReady = input.implantModelPlan.guideReady && input.validationSummary.status !== "fail";
  const labPartial = input.hasGuideRoute || input.hasImplantPlan || input.implantModelPlan.hasAxis;
  const taskReadinessScore = input.totalTasks > 0 ? input.readinessScore : input.validationSummary.score;
  const score = Math.round((taskReadinessScore + input.validationSummary.score) / 2);
  const status: CtPlanningExportStatus =
    validationStatus === "blocked" || !transferPartial
      ? "blocked"
      : validationStatus === "warning" || input.blockedTasks > 0 || input.unsavedArtifactCount > 0
        ? "warning"
        : "ready";

  const missingArtifacts = uniqueList([
    ...input.validationSummary.checks
      .filter((check) => check.status !== "pass")
      .map((check) => `${check.title}: ${check.value}`),
    input.unsavedArtifactCount > 0 ? `${input.unsavedArtifactCount} элементов плана нужно сохранить в пакет просмотра` : "",
    input.toolStateBundle ? "" : "состояние просмотрщика",
    input.volumeBlockedTasks > 0 ? "готовая объемная КТ-серия" : "",
    input.hasPanoramicRoute ? "" : "ОПТГ-дуга и поперечные срезы",
    opgReconstructionReady ? "" : "план построения ОПТГ и поперечных срезов",
    input.hasCanalRoute ? "" : "трасса нижнечелюстного канала",
    input.hasImplantPlan ? "" : "типоразмер импланта",
    implantModelReady ? "" : "модель импланта, апекса и втулки",
    input.implantModelPlan.guideReady ? "" : "готовность маршрута хирургического шаблона: маршрут, втулка, ось и отступ до канала",
    input.geometrySummary.areaCount > 0 || input.geometrySummary.volumeCount > 0 ? "" : "контур площади или объема",
    input.measurementPlan.status === "ready" ? "" : "карта измерений КТ-плана"
  ]);

  const lanes: CtPlanningExportLane[] = [
    {
      id: "doctor-check",
      owner: "doctor",
      title: "Врач",
      status: validationStatus,
      value: `${input.validationSummary.score}%`,
      detail: input.validationSummary.label,
      nextAction: input.validationSummary.status === "pass" ? "Фиксировать план и отдавать дальше." : "Закрыть клинические предупреждения."
    },
    {
      id: "measurements",
      owner: "doctor",
      title: "Измерения",
      status: laneStatus(input.measurementPlan.status === "ready", measurementReadyCount > 0),
      value: `${measurementReadyCount}/${input.measurementPlan.cards.length}`,
      detail: input.measurementPlan.summaryLabel,
      nextAction: input.measurementPlan.status === "ready" ? "Проверить подпись." : "Закрыть карту измерений."
    },
    {
      id: "opg-canal",
      owner: "doctor",
      title: "ОПТГ и канал",
      status: laneStatus(opgReconstructionReady && input.hasCanalRoute, routeReadyCount > 0 || input.reconstructionPlan.curvePointCount > 0),
      value: opgReconstructionReady ? `${input.reconstructionPlan.crossSectionCount} срезов` : `${routeReadyCount}/3 маршрута`,
      detail: "Панорамная дуга, поперечные срезы, канал и шаблон должны переноситься как структурные кривые.",
      nextAction: opgReconstructionReady && input.hasCanalRoute ? "Проверить поперечные срезы." : "Достроить дугу, срезы или канал."
    },
    {
      id: "admin-transfer",
      owner: "admin",
      title: "Администратор",
      status: laneStatus(transferReady, transferPartial),
      value: input.toolStateBundle ? `${input.toolStateBundle.viewports.length} окна` : "нет пакета",
      detail: "Переносит рабочее место, разметки, выбранный имплант, инструменты и подсказки без тяжелых исходных снимков.",
      nextAction: input.unsavedArtifactCount > 0 ? "Сначала обновить пакет просмотра с текущими элементами плана." : transferReady ? "Сохранить пакет плана в историю." : "Собрать состояние просмотрщика."
    },
    {
      id: "lab-handoff",
      owner: "lab",
      title: "Лаборатория",
      status: laneStatus(labReady, labPartial),
      value: labReady ? "маршрут готов" : input.implantModelPlan.guideRouteLengthMm ? `${input.implantModelPlan.guideRouteLengthMm} мм маршрут` : input.implantModelPlan.sleeveDiameterMm ? `${input.implantModelPlan.sleeveDiameterMm} мм втулка` : input.hasImplantPlan ? "есть имплант" : "нет оси",
      detail: "Пакет содержит маршрут и параметры планирования. CAD/STL создает лаборатория или локальный bridge, не браузер CRM.",
      nextAction: labReady ? "Передать маршрут и параметры в лабораторию или локальный bridge." : "Закрыть имплант, ось, апекс, втулку и контроль канала."
    }
  ];

  const model = input.implantModelPlan;
  const reconstruction = input.reconstructionPlan;
  const measurement = input.measurementPlan;
  const geometry = input.geometrySummary;
  const implantValue =
    model.implantDiameterMm !== null && model.implantLengthMm !== null
      ? `${model.implantDiameterMm} x ${model.implantLengthMm} мм`
      : input.hasImplantPlan
        ? "выбранный имплант"
        : "нет";
  const sleeveValue =
    model.sleeveDiameterMm !== null && model.sleeveLengthMm !== null ? `втулка ${model.sleeveDiameterMm} x ${model.sleeveLengthMm} мм` : "нет втулки";
  const opgValue = opgReconstructionReady ? `${reconstruction.crossSectionCoveragePercent}%` : `${reconstruction.curvePointCount} точ.`;
  const opgDetail =
    reconstruction.curveLengthMm === null
      ? "ОПТГ-дуга без полной длины."
      : `ОПТГ ${reconstruction.curveLengthMm} мм; ${reconstruction.crossSectionCount}/${reconstruction.crossSectionRequiredCount} срезов; ${reconstruction.crossSectionStationPreview}.`;
  const roiValue =
    geometry.volumeCount > 0
      ? measurement.roiVolumeTotalLabel
      : geometry.areaCount > 0
        ? measurement.roiAreaTotalLabel
        : "нет";
  const roiDetail =
    geometry.volumeCount > 0
      ? `Контур и слой ${measurement.roiVolumeSlabMm} мм; не сегментация.`
      : geometry.areaCount > 0
        ? `Площадь ${measurement.roiAreaTotalLabel}.`
        : measurement.roiDraftCount > 0
          ? "Контур начат; нужно 3 точки."
          : "Нужен контур площади или объема.";
  const densityValue = measurement.densityValueCount > 0 ? measurement.densityRangeLabel : `${measurement.densityProbeCount} точ.`;
  const guideValue =
    geometry.minimumClearanceMm !== null
      ? `${geometry.minimumClearanceMm} мм до канала`
      : model.guideRouteLengthMm !== null
        ? `${model.guideRouteLengthMm} мм маршрут`
        : "нет";
  const guidePartial = model.hasGuideRoute || input.hasCanalRoute || model.hasAxis || input.hasImplantPlan;
  const clinicalFacts: CtPlanningExportFact[] = [
    exportFact("implant", "Имплант и втулка", laneStatus(implantModelReady, input.hasImplantPlan || model.hasAxis), implantValue, `${sleeveValue}; ось ${model.axisLengthMm === null ? "нет" : `${model.axisLengthMm} мм`}.`),
    exportFact("opg-coverage", "ОПТГ и срезы", laneStatus(opgReconstructionReady, reconstruction.curvePointCount > 0 || input.hasPanoramicRoute), opgValue, opgDetail),
    exportFact("roi", "Контур площади/объема", laneStatus(geometry.areaCount > 0 || geometry.volumeCount > 0, measurement.roiDraftCount > 0), roiValue, roiDetail),
    exportFact("density", "Плотность", laneStatus(measurement.densityValueCount > 0, measurement.densityProbeCount > 0), densityValue, measurement.densityProtocolLabel),
    exportFact("canal-guide", "Канал и маршрут", laneStatus(model.guideReady, guidePartial), guideValue, model.guideReady ? "Маршрут и параметры готовы; CAD/STL делает лаборатория или локальный bridge." : "Нужны маршрут, втулка, ось и канал.")
  ];

  const title = statusTitle(status);
  const handoffSummary =
    status === "ready"
      ? "КТ-план можно передавать врачу, администратору и лаборатории: критические маршруты и проверки закрыты."
      : status === "warning"
        ? "КТ-план можно сохранить как черновик, но перед лабораторией нужно закрыть оставшиеся пункты."
        : "КТ-план нельзя отдавать дальше: нет переносимого состояния или есть клинический блокер.";
  const handoffSummaryWithBoundary = `${handoffSummary} ${exportOutputBoundarySummary}`;
  const nextAction =
    missingArtifacts.length > 0
      ? `Сначала закрыть: ${missingArtifacts.slice(0, 3).join(", ")}.`
      : "Сохранить пакет плана и привязать его к приему.";

  return {
    version: "dental-crm-ct-planning-export-v1",
    modelOutputKind: "planning_parameters_only",
    cadExportReady: false,
    surfaceModelRequired: true,
    outputBoundarySummary: exportOutputBoundarySummary,
    runtimeTruthPolicy,
    activeQuickActionId: input.activeQuickActionId ?? input.toolStateBundle?.activeQuickActionId ?? null,
    activeScenarioSummary: null,
    volumeReady,
    score,
    status,
    title,
    handoffSummary: handoffSummaryWithBoundary,
    nextAction,
    clinicalFacts,
    lanes,
    missingArtifacts
  };
}
