import { type Kopecks, parseKopecks } from "@dental/shared";
import type { ClinicalMaterialDefinition } from "./clinicalWriteoffPresets.js";

/**
 * 3. Базовый каталог стоматологических медикаментов и расходных материалов
 */
export const CLINICAL_MATERIALS_CATALOG: readonly ClinicalMaterialDefinition[] = [
	// Композиты и адгезивы
	{
		id: "mat_filtek_ultimate",
		sku: "COMP-FILT-ULT",
		nameRu: "Нанокомпозит Filtek Ultimate (шприц 4 г, 3M ESPE)",
		category: "composite",
		unit: "г",
		okeiCode: "166",
		defaultUnitCostKopecks: parseKopecks("1350.00"), // 1350 ₽ за 1 г
		requiresLotTracking: false,
		requiresSerialNumber: false,
		standardPackagingRu: "шприц 4 г",
		descriptionRu: "Универсальный наногибридный реставрационный композит (прямое списание FIFO)",
	},
	{
		id: "mat_gradia_direct",
		sku: "COMP-GRAD-DIR",
		nameRu: "Композит светового отверждения Gradia Direct (шприц 4 г, GC)",
		category: "composite",
		unit: "г",
		okeiCode: "166",
		defaultUnitCostKopecks: parseKopecks("1280.00"),
		requiresLotTracking: false,
		requiresSerialNumber: false,
		standardPackagingRu: "шприц 4 г",
		descriptionRu: "Светоотверждаемый микронаполненный гибридный композит (прямое списание FIFO)",
	},
	{
		id: "mat_single_bond_universal",
		sku: "ADH-SBU-5ML",
		nameRu: "Адгезив Single Bond Universal (флакон 5 мл, 3M)",
		category: "adhesive",
		unit: "мл",
		okeiCode: "111",
		defaultUnitCostKopecks: parseKopecks("1950.00"), // 1950 ₽ за 1 мл
		requiresLotTracking: false,
		requiresSerialNumber: false,
		standardPackagingRu: "флакон 5 мл",
		descriptionRu: "Самопротравливающий адгезив 7-го поколения (прямое списание FIFO)",
	},
	{
		id: "mat_phosphoric_acid_37",
		sku: "ETCH-GEL-37",
		nameRu: "Протравочный гель 37% фосфорная кислота (шприц 3 мл)",
		category: "adhesive",
		unit: "мл",
		okeiCode: "111",
		defaultUnitCostKopecks: parseKopecks("180.00"), // 180 ₽ за 1 мл
		requiresLotTracking: false,
		requiresSerialNumber: false,
		standardPackagingRu: "шприц 3 мл",
		descriptionRu: "Ортофосфорная кислота для кондиционирования эмали и дентина",
	},
	{
		id: "mat_cofferdam_sheet",
		sku: "COFF-SANC-BLUE",
		nameRu: "Платок коффердама латексный Sanctuary Dental Dam (комплект с клампом)",
		category: "auxiliary",
		unit: "шт",
		okeiCode: "796",
		defaultUnitCostKopecks: parseKopecks("115.00"),
		requiresLotTracking: false,
		requiresSerialNumber: false,
		standardPackagingRu: "упаковка 36 шт",
		descriptionRu: "Абсолютная изоляция зуба от ротовой жидкости и десневой жидкости",
	},
	{
		id: "mat_matrix_sectional_system",
		sku: "MATR-TOR-3D",
		nameRu: "Секционная матричная система контурная 3D + деревянный клин Tor VM",
		category: "auxiliary",
		unit: "компл",
		okeiCode: "839",
		defaultUnitCostKopecks: parseKopecks("95.00"),
		requiresLotTracking: false,
		requiresSerialNumber: false,
		standardPackagingRu: "набор 50 матриц + клинья",
		descriptionRu: "Восстановление анатомического контактного пункта и краевого валика",
	},
	{
		id: "mat_dental_burs_set",
		sku: "BURS-NTI-SET",
		nameRu: "Бор алмазный турбинный терапевтический (NTI / Komet)",
		category: "auxiliary",
		unit: "шт",
		okeiCode: "796",
		defaultUnitCostKopecks: parseKopecks("210.00"),
		requiresLotTracking: false,
		requiresSerialNumber: false,
		standardPackagingRu: "блистер 5 шт",
		descriptionRu: "Препарирование твердых тканей зуба и формирование полости",
	},
	{
		id: "mat_polishing_enhance",
		sku: "POL-ENHANCE-01",
		nameRu: "Полировочная силиконовая головка Enhance / паста Prisma Gloss",
		category: "auxiliary",
		unit: "шт",
		okeiCode: "796",
		defaultUnitCostKopecks: parseKopecks("160.00"),
		requiresLotTracking: false,
		requiresSerialNumber: false,
		standardPackagingRu: "упаковка 40 шт",
		descriptionRu: "Финишная полировка реставраций до сухого зеркального блеска",
	},

	// Эндодонтия
	{
		id: "mat_gutta_percha_points",
		sku: "ENDO-GUTTA-04",
		nameRu: "Гуттаперчевые штифты конусность .04/.06 калиброванные",
		category: "endo",
		unit: "шт",
		okeiCode: "796",
		defaultUnitCostKopecks: parseKopecks("75.00"),
		requiresLotTracking: false,
		requiresSerialNumber: false,
		standardPackagingRu: "коробка 60 шт",
		descriptionRu: "Мастер-штифты для трехмерной обтурации корневых каналов (прямое списание FIFO)",
	},
	{
		id: "mat_sealer_ah_plus",
		sku: "ENDO-AH-PLUS",
		nameRu: "Силер эпоксидный AH Plus / Эндометазон (паста A+B)",
		category: "endo",
		unit: "г",
		okeiCode: "166",
		defaultUnitCostKopecks: parseKopecks("4900.00"), // 4900 ₽ за 1 г
		requiresLotTracking: false,
		requiresSerialNumber: false,
		standardPackagingRu: "тюбик 15 г",
		descriptionRu: "Двухкомпонентный полимерный герметик корневых каналов (прямое списание FIFO)",
	},
	{
		id: "mat_hypochlorite_na_3",
		sku: "ENDO-HYPO-3PCT",
		nameRu: "Раствор натрия гипохлорита 3% стабилизированный (флакон 250 мл)",
		category: "endo",
		unit: "мл",
		okeiCode: "111",
		defaultUnitCostKopecks: parseKopecks("12.00"), // 12 ₽ за 1 мл
		requiresLotTracking: false,
		requiresSerialNumber: false,
		standardPackagingRu: "флакон 250 мл",
		descriptionRu: "Основной антисептический ирригант для растворения органики (прямое списание FIFO)",
	},
	{
		id: "mat_edta_gel_17",
		sku: "ENDO-EDTA-17",
		nameRu: "Гель ЭДТА 17% для хемомеханического расширения каналов",
		category: "endo",
		unit: "мл",
		okeiCode: "111",
		defaultUnitCostKopecks: parseKopecks("240.00"), // 240 ₽ за 1 мл
		requiresLotTracking: false,
		requiresSerialNumber: false,
		standardPackagingRu: "шприц 5 мл",
		descriptionRu: "Хелатный агент для удаления смазанного слоя со стенок канала",
	},
	{
		id: "mat_endo_needle_side_vent",
		sku: "ENDO-NDL-VENT",
		nameRu: "Эндодонтическая игла одноразовая с боковым спилом 30G",
		category: "endo",
		unit: "шт",
		okeiCode: "796",
		defaultUnitCostKopecks: parseKopecks("45.00"),
		requiresLotTracking: false,
		requiresSerialNumber: false,
		standardPackagingRu: "упаковка 100 шт",
		descriptionRu: "Безопасная игла для апикальной ирригации без риска выведения",
	},
	{
		id: "mat_paper_points",
		sku: "ENDO-PAPER-PTS",
		nameRu: "Штифты бумажные абсорбирующие стерильные (пины)",
		category: "endo",
		unit: "шт",
		okeiCode: "796",
		defaultUnitCostKopecks: parseKopecks("18.00"),
		requiresLotTracking: false,
		requiresSerialNumber: false,
		standardPackagingRu: "коробка 200 шт",
		descriptionRu: "Осушение корневого канала перед введением силера",
	},

	// Имплантация и хирургия
	{
		id: "mat_implant_osstem_ts3",
		sku: "IMP-OSST-TS3",
		nameRu: "Дентальный имплантат Osstem TS III SA (Ø4.0 x 10 мм)",
		category: "implant",
		unit: "шт",
		okeiCode: "796",
		defaultUnitCostKopecks: parseKopecks("12500.00"),
		requiresLotTracking: true,
		requiresSerialNumber: true,
		standardPackagingRu: "стерильный блистер",
		descriptionRu: "Титановый винтовой дентальный имплантат (МДЛП серийный номер)",
	},
	{
		id: "mat_healing_abutment",
		sku: "IMP-HEAL-ABUT",
		nameRu: "Заглушка винта / формирователь десны титановый",
		category: "implant",
		unit: "шт",
		okeiCode: "796",
		defaultUnitCostKopecks: parseKopecks("2400.00"),
		requiresLotTracking: true,
		requiresSerialNumber: false,
		standardPackagingRu: "стерильный флакон",
		descriptionRu: "Формирователь десневого контура вокруг платформы имплантата",
	},
	{
		id: "mat_surg_drape_gown_set",
		sku: "SURG-GOWN-SET",
		nameRu: "Стерильный хирургический халат и операционная простыня с липким краем",
		category: "ppe",
		unit: "компл",
		okeiCode: "839",
		defaultUnitCostKopecks: parseKopecks("650.00"),
		requiresLotTracking: false,
		requiresSerialNumber: false,
		standardPackagingRu: "стерильный комплект",
		descriptionRu: "Хирургическое накрытие операционного поля и хирурга",
	},
	{
		id: "mat_suture_vicryl_40",
		sku: "SUT-VICR-40",
		nameRu: "Шовный материал Викрил / Монофил 4-0 с атравматической колющей иглой",
		category: "suture",
		unit: "шт",
		okeiCode: "796",
		defaultUnitCostKopecks: parseKopecks("380.00"),
		requiresLotTracking: false,
		requiresSerialNumber: false,
		standardPackagingRu: "пакет с нитью",
		descriptionRu: "Рассасывающаяся полифиламентная нить для ушивания слизистой",
	},
	{
		id: "mat_surg_blade_15",
		sku: "SURG-BLADE-15",
		nameRu: "Лезвие скальпеля хирургическое №15 Swann-Morton",
		category: "surgery",
		unit: "шт",
		okeiCode: "796",
		defaultUnitCostKopecks: parseKopecks("85.00"),
		requiresLotTracking: false,
		requiresSerialNumber: false,
		standardPackagingRu: "стерильный фольгированный блистер",
		descriptionRu: "Микрохирургическое лезвие для разрезов десны и надкостницы",
	},
	{
		id: "mat_saline_500ml",
		sku: "SURG-SALINE-500",
		nameRu: "Раствор натрия хлорида 0.9% стерильный 500 мл (физраствор для физдиодиспансера)",
		category: "surgery",
		unit: "фл",
		okeiCode: "796",
		defaultUnitCostKopecks: parseKopecks("120.00"),
		requiresLotTracking: false,
		requiresSerialNumber: false,
		standardPackagingRu: "флакон 500 мл",
		descriptionRu: "Стерильное охлаждение костного ложа при препарировании",
	},
	{
		id: "mat_hemostatic_sponge",
		sku: "SURG-SPONGE-ALV",
		nameRu: "Гемостатическая коллагеновая губка Альвостаз / Тахокомб",
		category: "surgery",
		unit: "шт",
		okeiCode: "796",
		defaultUnitCostKopecks: parseKopecks("320.00"),
		requiresLotTracking: false,
		requiresSerialNumber: false,
		standardPackagingRu: "банка 30 шт",
		descriptionRu: "Остановка капиллярного кровотечения и защита кровяного сгустка",
	},

	// Анестезия
	{
		id: "mat_articaine_ultracain",
		sku: "ANES-ULTRA-DS",
		nameRu: "Анестетик артикаиновый 4% с эпинефрином 1:100000 (Ультракаин Д-С) 1.7 мл",
		category: "anesthesia",
		unit: "карп",
		okeiCode: "796",
		defaultUnitCostKopecks: parseKopecks("230.00"),
		requiresLotTracking: true,
		requiresSerialNumber: false,
		standardPackagingRu: "карпула 1.7 мл",
		descriptionRu: "Местный анестетик прямого действия с вазоконстриктором (МДЛП)",
	},
	{
		id: "mat_dental_needle_30g",
		sku: "ANES-NEEDLE-30G",
		nameRu: "Игла карпульная стоматологическая 30G евростандарт 25 мм",
		category: "anesthesia",
		unit: "шт",
		okeiCode: "796",
		defaultUnitCostKopecks: parseKopecks("30.00"),
		requiresLotTracking: false,
		requiresSerialNumber: false,
		standardPackagingRu: "коробка 100 шт",
		descriptionRu: "Стерильная инъекционная игла с силиконовым покрытием",
	},
	{
		id: "mat_topical_anesthesia_gel",
		sku: "ANES-TOPICAL-GEL",
		nameRu: "Гель для аппликационной анестезии Джен-Релиф / Топикал",
		category: "anesthesia",
		unit: "мл",
		okeiCode: "111",
		defaultUnitCostKopecks: parseKopecks("50.00"),
		requiresLotTracking: false,
		requiresSerialNumber: false,
		standardPackagingRu: "баночка 30 мл",
		descriptionRu: "Обезболивание места укола карпульной иглы",
	},
	{
		id: "mat_antiseptic_chlorhexidine",
		sku: "DIS-CHLOR-005",
		nameRu: "Антисептик инъекционного поля (Хлоргексидина биглюконат 0.05% / салфетка)",
		category: "anesthesia",
		unit: "шт",
		okeiCode: "796",
		defaultUnitCostKopecks: parseKopecks("15.00"),
		requiresLotTracking: false,
		requiresSerialNumber: false,
		standardPackagingRu: "салфетка спиртовая / раствор",
		descriptionRu: "Антисептическая обработка слизистой оболочки перед инъекцией анестетика",
	},

	// СИЗ и базовые расходники приема (СанПиН 3.3686-21)
	{
		id: "mat_saliva_ejector",
		sku: "PPE-SALIVA-EJ",
		nameRu: "Слюноотсос одноразовый стоматологический с гибким наконечником",
		category: "ppe",
		unit: "шт",
		okeiCode: "796",
		defaultUnitCostKopecks: parseKopecks("14.00"),
		requiresLotTracking: false,
		requiresSerialNumber: false,
		standardPackagingRu: "пакет 100 шт",
		descriptionRu: "Эвакуация ротовой жидкости из подъязычной области",
	},
	{
		id: "mat_cotton_rolls",
		sku: "PPE-COTTON-ROLLS",
		nameRu: "Ватные валики стоматологические стерильные №2",
		category: "ppe",
		unit: "шт",
		okeiCode: "796",
		defaultUnitCostKopecks: parseKopecks("4.00"),
		requiresLotTracking: false,
		requiresSerialNumber: false,
		standardPackagingRu: "рулон 500 шт",
		descriptionRu: "Изоляция операционного поля от слюны",
	},
	{
		id: "mat_patient_bib",
		sku: "PPE-PATIENT-BIB",
		nameRu: "Салфетка нагрудная стоматологическая двухслойная (нагрудник)",
		category: "ppe",
		unit: "шт",
		okeiCode: "796",
		defaultUnitCostKopecks: parseKopecks("8.00"),
		requiresLotTracking: false,
		requiresSerialNumber: false,
		standardPackagingRu: "пакет 500 шт",
		descriptionRu: "Защита одежды пациента во время стоматологического приема (нагрудник)",
	},
	{
		id: "mat_nitrile_gloves",
		sku: "PPE-NITRILE-GLV",
		nameRu: "Перчатки нитриловые неопудренные текстурированные (пара)",
		category: "ppe",
		unit: "пар",
		okeiCode: "715",
		defaultUnitCostKopecks: parseKopecks("38.00"),
		requiresLotTracking: false,
		requiresSerialNumber: false,
		standardPackagingRu: "коробка 50 пар",
		descriptionRu: "Защита рук медицинского персонала",
	},
	{
		id: "mat_surgical_mask",
		sku: "PPE-SURG-MASK",
		nameRu: "Маска медицинская защитная трехслойная с носовым фиксатором",
		category: "ppe",
		unit: "шт",
		okeiCode: "796",
		defaultUnitCostKopecks: parseKopecks("16.00"),
		requiresLotTracking: false,
		requiresSerialNumber: false,
		standardPackagingRu: "коробка 50 шт",
		descriptionRu: "Защита дыхательных путей врача и ассистента",
	},
	{
		id: "mat_air_flow_powder",
		sku: "HYG-AIRFLOW-POWDER",
		nameRu: "Порошок для воздушно-абразивной обработки Air-Flow Clinpro / EMS Plus",
		category: "hygiene",
		unit: "г",
		okeiCode: "166",
		defaultUnitCostKopecks: parseKopecks("22.00"),
		requiresLotTracking: false,
		requiresSerialNumber: false,
		standardPackagingRu: "флакон 120 г",
		descriptionRu: "Удаление мягкого налета и биопленки с эмали зубов (прямое списание FIFO)",
	},
	{
		id: "mat_prophy_paste",
		sku: "HYG-PROPHY-PASTE",
		nameRu: "Паста полировочная абразивная Cleanic / Detartrine",
		category: "hygiene",
		unit: "г",
		okeiCode: "166",
		defaultUnitCostKopecks: parseKopecks("42.00"),
		requiresLotTracking: false,
		requiresSerialNumber: false,
		standardPackagingRu: "туба 100 г",
		descriptionRu: "Механическая чистка и полировка эмали циркулярной щеткой",
	},
	{
		id: "mat_optragate",
		sku: "HYG-OPTRAGATE",
		nameRu: "Ретрактор губ и щек мягкий OptraGate (Ivoclar)",
		category: "hygiene",
		unit: "шт",
		okeiCode: "796",
		defaultUnitCostKopecks: parseKopecks("220.00"),
		requiresLotTracking: false,
		requiresSerialNumber: false,
		standardPackagingRu: "упаковка 80 шт",
		descriptionRu: "Комфортный трехмерный доступ к операционному полю",
	},
	{
		id: "mat_fluoride_varnish",
		sku: "HYG-FLUOR-VARNISH",
		nameRu: "Фторсодержащий защитный лак Clinpro White Varnish (флакон 0.5 мл)",
		category: "hygiene",
		unit: "мл",
		okeiCode: "111",
		defaultUnitCostKopecks: parseKopecks("680.00"),
		requiresLotTracking: false,
		requiresSerialNumber: false,
		standardPackagingRu: "унидоза 0.5 мл",
		descriptionRu: "Глубокое фторирование и снижение гиперестезии эмали (прямое списание FIFO)",
	},
	{
		id: "mat_bio_oss_graft",
		sku: "SURG-BIO-OSS-05",
		nameRu: "Костнозамещающий натуральный графт Geistlich Bio-Oss (гранулы 0.5 г / 1.0 г)",
		category: "surgery",
		unit: "упак",
		okeiCode: "796",
		defaultUnitCostKopecks: parseKopecks("12500.00"),
		requiresLotTracking: true,
		requiresSerialNumber: true,
		standardPackagingRu: "стерильный флакон 0.5 г",
		descriptionRu: "Натуральный остеокондуктивный костнозамещающий материал (Швейцария)",
	},
	{
		id: "mat_bio_gide_membrane",
		sku: "SURG-BIO-GIDE-25",
		nameRu: "Коллагеновая резорбируемая барьерная мембрана Geistlich Bio-Gide 25×25 мм",
		category: "surgery",
		unit: "шт",
		okeiCode: "796",
		defaultUnitCostKopecks: parseKopecks("16800.00"),
		requiresLotTracking: true,
		requiresSerialNumber: true,
		standardPackagingRu: "стерильный блистер",
		descriptionRu: "Двухслойная свиная коллагеновая мембрана для направленной костной регенерации",
	},
	{
		id: "mat_prolene_50",
		sku: "SUT-PROL-50",
		nameRu: "Шовный материал монофиламентный Пролен (Prolene) 5-0 с атравматической иглой",
		category: "suture",
		unit: "шт",
		okeiCode: "796",
		defaultUnitCostKopecks: parseKopecks("540.00"),
		requiresLotTracking: false,
		requiresSerialNumber: false,
		standardPackagingRu: "пакет с нитью",
		descriptionRu: "Нерассасывающаяся полипропиленовая мононить для прецизионного ушивания десны",
	},
	{
		id: "mat_estelite_asteria",
		sku: "COMP-ESTEL-AST",
		nameRu: "Светоотверждаемый нанокомпозит Estelite Asteria (шприц 4 г, Tokuyama Dental)",
		category: "composite",
		unit: "г",
		okeiCode: "166",
		defaultUnitCostKopecks: parseKopecks("1450.00"),
		requiresLotTracking: false,
		requiresSerialNumber: false,
		standardPackagingRu: "шприц 4 г",
		descriptionRu: "Высокоэстетичный светоотверждаемый нанокомпозит с эффектом хамелеона (прямое списание FIFO)",
	},
	{
		id: "mat_articaine_1_200000",
		sku: "ANES-ULTRA-DS-200",
		nameRu: "Анестетик артикаиновый 4% с эпинефрином 1:200 000 (Ультракаин Д-С) 1.7 мл",
		category: "anesthesia",
		unit: "карп",
		okeiCode: "796",
		defaultUnitCostKopecks: parseKopecks("210.00"),
		requiresLotTracking: true,
		requiresSerialNumber: false,
		standardPackagingRu: "карпула 1.7 мл",
		descriptionRu: "Местный анестетик артикаинового ряда с уменьшенной концентрацией вазоконстриктора",
	},
];


/**
 * Вспомогательная функция поиска в каталоге
 */
export function getClinicalMaterialById(materialId: string): ClinicalMaterialDefinition | undefined {
	return CLINICAL_MATERIALS_CATALOG.find((m) => m.id === materialId);
}

