import { type Kopecks, parseKopecks } from "@dental/shared";
import type { CabinetStockBatch } from "./clinicalWriteoffPresets.js";

export const DENTAL_CABINET_STOCK_PRESETS: readonly CabinetStockBatch[] = [
	{
		batchId: "bat_bio_oss_01",
		materialId: "mat_bio_oss_graft",
		cabinetId: "cab_02_surgery",
		cabinetNameRu: "Кабинет №2 (Хирургия)",
		lotNumber: "LOT-BIO-OSS-771",
		serialNumber: "SN-OSS-90218",
		expirationDate: "2028-10-31",
		manufactureDate: "2024-10-01",
		quantityAvailable: 6, // 6 упаковок
		criticalThreshold: 2,
		unitCostKopecks: parseKopecks("12500.00"),
		supplierNameRu: "Geistlich Pharma AG (Швейцария)",
	},
	{
		batchId: "bat_bio_gide_01",
		materialId: "mat_bio_gide_membrane",
		cabinetId: "cab_02_surgery",
		cabinetNameRu: "Кабинет №2 (Хирургия)",
		lotNumber: "LOT-BIO-GIDE-442",
		serialNumber: "SN-GIDE-10492",
		expirationDate: "2028-12-31",
		manufactureDate: "2024-12-01",
		quantityAvailable: 4, // 4 мембраны
		criticalThreshold: 1,
		unitCostKopecks: parseKopecks("16800.00"),
		supplierNameRu: "Geistlich Pharma AG (Швейцария)",
	},
	{
		batchId: "bat_prolene_01",
		materialId: "mat_prolene_50",
		cabinetId: "cab_02_surgery",
		cabinetNameRu: "Кабинет №2 (Хирургия)",
		lotNumber: "LOT-PROL-119",
		expirationDate: "2029-05-31",
		manufactureDate: "2024-05-01",
		quantityAvailable: 15,
		criticalThreshold: 5,
		unitCostKopecks: parseKopecks("540.00"),
		supplierNameRu: "Ethicon (Johnson & Johnson)",
	},
	{
		batchId: "bat_estelite_01",
		materialId: "mat_estelite_asteria",
		cabinetId: "cab_01_therapy",
		cabinetNameRu: "Кабинет №1 (Терапия)",
		lotNumber: "LOT-EST-3301",
		expirationDate: "2028-08-31",
		manufactureDate: "2025-01-15",
		quantityAvailable: 8.0, // 8 г (2 шприца)
		criticalThreshold: 2.0,
		unitCostKopecks: parseKopecks("1450.00"),
		supplierNameRu: "Tokuyama Dental (Япония)",
	},
	{
		batchId: "bat_articaine_200_01",
		materialId: "mat_articaine_1_200000",
		cabinetId: "cab_01_therapy",
		cabinetNameRu: "Кабинет №1 (Терапия)",
		lotNumber: "LOT-ULT-200-881",
		expirationDate: "2027-09-30",
		manufactureDate: "2024-09-01",
		quantityAvailable: 40,
		criticalThreshold: 10,
		unitCostKopecks: parseKopecks("210.00"),
		supplierNameRu: "Sanofi-Aventis",
	},
	{
		batchId: "bat_filtek_2026_01",
		materialId: "mat_filtek_ultimate",
		cabinetId: "cab_01_therapy",
		cabinetNameRu: "Кабинет №1 (Терапия)",
		lotNumber: "LOT-FLT-8821",
		expirationDate: "2027-11-30",
		manufactureDate: "2024-11-01",
		quantityAvailable: 12.0, // 12 г (3 шприца)
		criticalThreshold: 2.0,
		unitCostKopecks: parseKopecks("1350.00"),
		supplierNameRu: "ООО «3М Россия»",
	},
	{
		batchId: "bat_filtek_expiring_soon",
		materialId: "mat_filtek_ultimate",
		cabinetId: "cab_01_therapy",
		cabinetNameRu: "Кабинет №1 (Терапия)",
		lotNumber: "LOT-FLT-OLD-19",
		expirationDate: "2026-09-10", // истекает через < 30 дней от августа 2026
		manufactureDate: "2023-09-01",
		quantityAvailable: 1.2,
		criticalThreshold: 2.0,
		unitCostKopecks: parseKopecks("1200.00"),
		supplierNameRu: "ООО «3М Россия»",
	},
	{
		batchId: "bat_sbu_2026_01",
		materialId: "mat_single_bond_universal",
		cabinetId: "cab_01_therapy",
		cabinetNameRu: "Кабинет №1 (Терапия)",
		lotNumber: "LOT-SBU-4401",
		expirationDate: "2028-04-15",
		manufactureDate: "2025-04-01",
		quantityAvailable: 4.5, // 4.5 мл
		criticalThreshold: 1.0,
		unitCostKopecks: parseKopecks("1950.00"),
		supplierNameRu: "ООО «3М Россия»",
	},
	{
		batchId: "bat_etch_2026_01",
		materialId: "mat_phosphoric_acid_37",
		cabinetId: "cab_01_therapy",
		cabinetNameRu: "Кабинет №1 (Терапия)",
		lotNumber: "LOT-ETCH-909",
		expirationDate: "2027-08-31",
		manufactureDate: "2025-08-01",
		quantityAvailable: 8.0,
		criticalThreshold: 2.0,
		unitCostKopecks: parseKopecks("180.00"),
		supplierNameRu: "АО «ВладМиВа»",
	},
	{
		batchId: "bat_enhance_2026_01",
		materialId: "mat_polishing_enhance",
		cabinetId: "cab_01_therapy",
		cabinetNameRu: "Кабинет №1 (Терапия)",
		lotNumber: "LOT-ENH-311",
		expirationDate: "2029-12-31",
		manufactureDate: "2025-01-10",
		quantityAvailable: 25,
		criticalThreshold: 5,
		unitCostKopecks: parseKopecks("160.00"),
		supplierNameRu: "Dentsply Sirona",
	},
	{
		batchId: "bat_cofferdam_2026_01",
		materialId: "mat_cofferdam_sheet",
		cabinetId: "cab_01_therapy",
		cabinetNameRu: "Кабинет №1 (Терапия)",
		lotNumber: "LOT-COFF-991",
		expirationDate: "2029-06-30",
		manufactureDate: "2024-06-01",
		quantityAvailable: 40,
		criticalThreshold: 10,
		unitCostKopecks: parseKopecks("115.00"),
		supplierNameRu: "Sanctuary Dental",
	},
	{
		batchId: "bat_matrix_2026_01",
		materialId: "mat_matrix_sectional_system",
		cabinetId: "cab_01_therapy",
		cabinetNameRu: "Кабинет №1 (Терапия)",
		lotNumber: "LOT-MATR-772",
		expirationDate: "2030-01-31",
		manufactureDate: "2025-01-01",
		quantityAvailable: 35,
		criticalThreshold: 8,
		unitCostKopecks: parseKopecks("95.00"),
		supplierNameRu: "ТОР ВМ",
	},
	{
		batchId: "bat_burs_2026_01",
		materialId: "mat_dental_burs_set",
		cabinetId: "cab_01_therapy",
		cabinetNameRu: "Кабинет №1 (Терапия)",
		lotNumber: "LOT-BURS-441",
		expirationDate: "2031-12-31",
		manufactureDate: "2025-02-01",
		quantityAvailable: 20,
		criticalThreshold: 5,
		unitCostKopecks: parseKopecks("210.00"),
		supplierNameRu: "NTI Kahla GmbH",
	},

	// Эндодонтия
	{
		batchId: "bat_gutta_2026_01",
		materialId: "mat_gutta_percha_points",
		cabinetId: "cab_01_therapy",
		cabinetNameRu: "Кабинет №1 (Терапия)",
		lotNumber: "LOT-GUT-552",
		expirationDate: "2028-06-30",
		manufactureDate: "2024-06-01",
		quantityAvailable: 45,
		criticalThreshold: 10,
		unitCostKopecks: parseKopecks("75.00"),
		supplierNameRu: "VDW Dental GmbH",
	},
	{
		batchId: "bat_ahplus_2026_01",
		materialId: "mat_sealer_ah_plus",
		cabinetId: "cab_01_therapy",
		cabinetNameRu: "Кабинет №1 (Терапия)",
		lotNumber: "LOT-AHP-771",
		expirationDate: "2027-10-31",
		manufactureDate: "2024-10-01",
		quantityAvailable: 8.5,
		criticalThreshold: 2.0,
		unitCostKopecks: parseKopecks("4900.00"),
		supplierNameRu: "Dentsply Sirona",
	},
	{
		batchId: "bat_hypo_2026_01",
		materialId: "mat_hypochlorite_na_3",
		cabinetId: "cab_01_therapy",
		cabinetNameRu: "Кабинет №1 (Терапия)",
		lotNumber: "LOT-HYP-101",
		expirationDate: "2027-01-31",
		manufactureDate: "2026-01-01",
		quantityAvailable: 220,
		criticalThreshold: 50,
		unitCostKopecks: parseKopecks("12.00"),
		supplierNameRu: "АО «Омега-Дент»",
	},
	{
		batchId: "bat_edta_2026_01",
		materialId: "mat_edta_gel_17",
		cabinetId: "cab_01_therapy",
		cabinetNameRu: "Кабинет №1 (Терапия)",
		lotNumber: "LOT-EDTA-882",
		expirationDate: "2027-05-31",
		manufactureDate: "2025-05-01",
		quantityAvailable: 15,
		criticalThreshold: 3,
		unitCostKopecks: parseKopecks("240.00"),
		supplierNameRu: "АО «ВладМиВа»",
	},
	{
		batchId: "bat_endondl_2026_01",
		materialId: "mat_endo_needle_side_vent",
		cabinetId: "cab_01_therapy",
		cabinetNameRu: "Кабинет №1 (Терапия)",
		lotNumber: "LOT-NDL-441",
		expirationDate: "2029-03-31",
		manufactureDate: "2024-03-01",
		quantityAvailable: 60,
		criticalThreshold: 10,
		unitCostKopecks: parseKopecks("45.00"),
		supplierNameRu: "Cerkamed",
	},
	{
		batchId: "bat_paper_2026_01",
		materialId: "mat_paper_points",
		cabinetId: "cab_01_therapy",
		cabinetNameRu: "Кабинет №1 (Терапия)",
		lotNumber: "LOT-PAP-992",
		expirationDate: "2028-12-31",
		manufactureDate: "2024-12-01",
		quantityAvailable: 120,
		criticalThreshold: 20,
		unitCostKopecks: parseKopecks("18.00"),
		supplierNameRu: "VDW Dental GmbH",
	},

	// Имплантация и хирургия (Кабинет №2)
	{
		batchId: "bat_osstem_ts3_sn01",
		materialId: "mat_implant_osstem_ts3",
		cabinetId: "cab_02_surgery",
		cabinetNameRu: "Кабинет №2 (Хирургия)",
		lotNumber: "LOT-OS-2026B1",
		serialNumber: "SN-OSST-7849120",
		expirationDate: "2029-12-31",
		manufactureDate: "2024-12-01",
		quantityAvailable: 1,
		criticalThreshold: 2,
		unitCostKopecks: parseKopecks("12500.00"),
		supplierNameRu: "Osstem Implant Co.",
	},
	{
		batchId: "bat_osstem_ts3_sn02",
		materialId: "mat_implant_osstem_ts3",
		cabinetId: "cab_02_surgery",
		cabinetNameRu: "Кабинет №2 (Хирургия)",
		lotNumber: "LOT-OS-2026B1",
		serialNumber: "SN-OSST-7849121",
		expirationDate: "2029-12-31",
		manufactureDate: "2024-12-01",
		quantityAvailable: 1,
		criticalThreshold: 2,
		unitCostKopecks: parseKopecks("12500.00"),
		supplierNameRu: "Osstem Implant Co.",
	},
	{
		batchId: "bat_abutment_2026_01",
		materialId: "mat_healing_abutment",
		cabinetId: "cab_02_surgery",
		cabinetNameRu: "Кабинет №2 (Хирургия)",
		lotNumber: "LOT-HAB-110",
		expirationDate: "2030-01-31",
		manufactureDate: "2025-01-01",
		quantityAvailable: 8,
		criticalThreshold: 2,
		unitCostKopecks: parseKopecks("2400.00"),
		supplierNameRu: "Osstem Implant Co.",
	},
	{
		batchId: "bat_gown_2026_01",
		materialId: "mat_surg_drape_gown_set",
		cabinetId: "cab_02_surgery",
		cabinetNameRu: "Кабинет №2 (Хирургия)",
		lotNumber: "LOT-GWN-982",
		expirationDate: "2028-09-30",
		manufactureDate: "2025-09-01",
		quantityAvailable: 14,
		criticalThreshold: 3,
		unitCostKopecks: parseKopecks("650.00"),
		supplierNameRu: "ЗАО «Здравмедтех»",
	},
	{
		batchId: "bat_vicryl_2026_01",
		materialId: "mat_suture_vicryl_40",
		cabinetId: "cab_02_surgery",
		cabinetNameRu: "Кабинет №2 (Хирургия)",
		lotNumber: "LOT-VIC-664",
		expirationDate: "2028-05-31",
		manufactureDate: "2024-05-01",
		quantityAvailable: 18,
		criticalThreshold: 4,
		unitCostKopecks: parseKopecks("380.00"),
		supplierNameRu: "Ethicon / Johnson & Johnson",
	},
	{
		batchId: "bat_blade_2026_01",
		materialId: "mat_surg_blade_15",
		cabinetId: "cab_02_surgery",
		cabinetNameRu: "Кабинет №2 (Хирургия)",
		lotNumber: "LOT-BLD-019",
		expirationDate: "2029-08-31",
		manufactureDate: "2024-08-01",
		quantityAvailable: 40,
		criticalThreshold: 10,
		unitCostKopecks: parseKopecks("85.00"),
		supplierNameRu: "Swann-Morton Ltd",
	},
	{
		batchId: "bat_saline_2026_01",
		materialId: "mat_saline_500ml",
		cabinetId: "cab_02_surgery",
		cabinetNameRu: "Кабинет №2 (Хирургия)",
		lotNumber: "LOT-SAL-332",
		expirationDate: "2027-04-30",
		manufactureDate: "2025-04-01",
		quantityAvailable: 12,
		criticalThreshold: 3,
		unitCostKopecks: parseKopecks("120.00"),
		supplierNameRu: "ОАО «Гротекс» (Solopharm)",
	},
	{
		batchId: "bat_sponge_2026_01",
		materialId: "mat_hemostatic_sponge",
		cabinetId: "cab_02_surgery",
		cabinetNameRu: "Кабинет №2 (Хирургия)",
		lotNumber: "LOT-ALV-771",
		expirationDate: "2027-11-30",
		manufactureDate: "2024-11-01",
		quantityAvailable: 22,
		criticalThreshold: 5,
		unitCostKopecks: parseKopecks("320.00"),
		supplierNameRu: "АО «Омега-Дент»",
	},

	// Анестетики (все кабинеты)
	{
		batchId: "bat_ultracain_cab1",
		materialId: "mat_articaine_ultracain",
		cabinetId: "cab_01_therapy",
		cabinetNameRu: "Кабинет №1 (Терапия)",
		lotNumber: "LOT-ULTRA-2026F",
		expirationDate: "2028-02-28",
		manufactureDate: "2025-02-01",
		quantityAvailable: 48,
		criticalThreshold: 10,
		unitCostKopecks: parseKopecks("230.00"),
		supplierNameRu: "Sanofi Aventis",
	},
	{
		batchId: "bat_needle_cab1",
		materialId: "mat_dental_needle_30g",
		cabinetId: "cab_01_therapy",
		cabinetNameRu: "Кабинет №1 (Терапия)",
		lotNumber: "LOT-NDL-998",
		expirationDate: "2029-06-30",
		manufactureDate: "2024-06-01",
		quantityAvailable: 95,
		criticalThreshold: 20,
		unitCostKopecks: parseKopecks("30.00"),
		supplierNameRu: "Septodont",
	},
	{
		batchId: "bat_topical_cab1",
		materialId: "mat_topical_anesthesia_gel",
		cabinetId: "cab_01_therapy",
		cabinetNameRu: "Кабинет №1 (Терапия)",
		lotNumber: "LOT-TOP-112",
		expirationDate: "2027-03-31",
		manufactureDate: "2025-03-01",
		quantityAvailable: 25,
		criticalThreshold: 5,
		unitCostKopecks: parseKopecks("50.00"),
		supplierNameRu: "Jen-Dental",
	},
	{
		batchId: "bat_chlorhex_cab1",
		materialId: "mat_antiseptic_chlorhexidine",
		cabinetId: "cab_01_therapy",
		cabinetNameRu: "Кабинет №1 (Терапия)",
		lotNumber: "LOT-CHX-2026",
		expirationDate: "2028-12-31",
		manufactureDate: "2025-01-01",
		quantityAvailable: 100,
		criticalThreshold: 10,
		unitCostKopecks: parseKopecks("15.00"),
		supplierNameRu: "ОАО «Фармстандарт»",
	},
	{
		batchId: "bat_chlorhex_cab2",
		materialId: "mat_antiseptic_chlorhexidine",
		cabinetId: "cab_02_surgery",
		cabinetNameRu: "Кабинет №2 (Хирургия)",
		lotNumber: "LOT-CHX-2026S",
		expirationDate: "2028-12-31",
		manufactureDate: "2025-01-01",
		quantityAvailable: 100,
		criticalThreshold: 10,
		unitCostKopecks: parseKopecks("15.00"),
		supplierNameRu: "ОАО «Фармстандарт»",
	},

	// Общие СИЗ
	{
		batchId: "bat_saliva_cab1",
		materialId: "mat_saliva_ejector",
		cabinetId: "cab_01_therapy",
		cabinetNameRu: "Кабинет №1 (Терапия)",
		lotNumber: "LOT-SE-2026",
		expirationDate: "2030-12-31",
		manufactureDate: "2025-01-01",
		quantityAvailable: 150,
		criticalThreshold: 30,
		unitCostKopecks: parseKopecks("14.00"),
		supplierNameRu: "Euronda",
	},
	{
		batchId: "bat_cotton_cab1",
		materialId: "mat_cotton_rolls",
		cabinetId: "cab_01_therapy",
		cabinetNameRu: "Кабинет №1 (Терапия)",
		lotNumber: "LOT-CR-2026",
		expirationDate: "2030-12-31",
		manufactureDate: "2025-01-01",
		quantityAvailable: 350,
		criticalThreshold: 50,
		unitCostKopecks: parseKopecks("4.00"),
		supplierNameRu: "Euronda",
	},
	{
		batchId: "bat_gloves_cab1",
		materialId: "mat_nitrile_gloves",
		cabinetId: "cab_01_therapy",
		cabinetNameRu: "Кабинет №1 (Терапия)",
		lotNumber: "LOT-GLV-882",
		expirationDate: "2029-08-31",
		manufactureDate: "2024-08-01",
		quantityAvailable: 75,
		criticalThreshold: 15,
		unitCostKopecks: parseKopecks("38.00"),
		supplierNameRu: "Top Glove Corp.",
	},
	{
		batchId: "bat_mask_cab1",
		materialId: "mat_surgical_mask",
		cabinetId: "cab_01_therapy",
		cabinetNameRu: "Кабинет №1 (Терапия)",
		lotNumber: "LOT-MSK-119",
		expirationDate: "2029-05-31",
		manufactureDate: "2024-05-01",
		quantityAvailable: 120,
		criticalThreshold: 20,
		unitCostKopecks: parseKopecks("16.00"),
		supplierNameRu: "ООО «КИТ»",
	},
	{
		batchId: "bat_airflow_cab1",
		materialId: "mat_air_flow_powder",
		cabinetId: "cab_01_therapy",
		cabinetNameRu: "Кабинет №1 (Терапия)",
		lotNumber: "LOT-AIR-774",
		expirationDate: "2027-10-31",
		manufactureDate: "2024-10-01",
		quantityAvailable: 80,
		criticalThreshold: 25,
		unitCostKopecks: parseKopecks("22.00"),
		supplierNameRu: "3M ESPE",
	},
	{
		batchId: "bat_prophy_cab1",
		materialId: "mat_prophy_paste",
		cabinetId: "cab_01_therapy",
		cabinetNameRu: "Кабинет №1 (Терапия)",
		lotNumber: "LOT-PST-991",
		expirationDate: "2028-01-31",
		manufactureDate: "2025-01-01",
		quantityAvailable: 45,
		criticalThreshold: 10,
		unitCostKopecks: parseKopecks("42.00"),
		supplierNameRu: "Kerr Dental",
	},
	{
		batchId: "bat_optragate_cab1",
		materialId: "mat_optragate",
		cabinetId: "cab_01_therapy",
		cabinetNameRu: "Кабинет №1 (Терапия)",
		lotNumber: "LOT-OPT-441",
		expirationDate: "2029-07-31",
		manufactureDate: "2024-07-01",
		quantityAvailable: 30,
		criticalThreshold: 5,
		unitCostKopecks: parseKopecks("220.00"),
		supplierNameRu: "Ivoclar Vivadent",
	},
	{
		batchId: "bat_varnish_cab1",
		materialId: "mat_fluoride_varnish",
		cabinetId: "cab_01_therapy",
		cabinetNameRu: "Кабинет №1 (Терапия)",
		lotNumber: "LOT-VAR-332",
		expirationDate: "2027-06-30",
		manufactureDate: "2025-06-01",
		quantityAvailable: 10,
		criticalThreshold: 2,
		unitCostKopecks: parseKopecks("680.00"),
		supplierNameRu: "3M ESPE",
	},
];
