/**
 * ═══════════════════════════════════════════════════════════════════════════
 * СПРАВОЧНИКИ ЛЕКАРСТВЕННЫХ ФОРМ, ПУТЕЙ ВВЕДЕНИЯ И СТОМАТОЛОГИЧЕСКИХ ПРЕПАРАТОВ
 * ═══════════════════════════════════════════════════════════════════════════
 */

export interface PrescriptionDosageFormMeta {
	readonly code: string;
	readonly nameRu: string;
	readonly nameLatin: string;
	readonly latinAbbr: string;
	readonly dispensePatternLatin: string; // e.g. "D.t.d. N {count} in tab."
	readonly defaultUnitRu: string;
}

export const PRESCRIPTION_DOSAGE_FORMS_CATALOG: readonly PrescriptionDosageFormMeta[] = [
	{
		code: "tablets",
		nameRu: "таблетки",
		nameLatin: "Tabulettae",
		latinAbbr: "tab.",
		dispensePatternLatin: "D.t.d. N {count} in tab.",
		defaultUnitRu: "таб.",
	},
	{
		code: "tablets_coated",
		nameRu: "таблетки, покрытые пленочной оболочкой",
		nameLatin: "Tabulettae obductae",
		latinAbbr: "tab. obd.",
		dispensePatternLatin: "D.t.d. N {count} in tab.",
		defaultUnitRu: "таб.",
	},
	{
		code: "tablets_dispersible",
		nameRu: "таблетки диспергируемые (растворимые)",
		nameLatin: "Tabulettae dispersibiles",
		latinAbbr: "tab. dispers.",
		dispensePatternLatin: "D.t.d. N {count} in tab.",
		defaultUnitRu: "таб.",
	},
	{
		code: "capsules",
		nameRu: "капсулы",
		nameLatin: "Capsulae",
		latinAbbr: "caps.",
		dispensePatternLatin: "D.t.d. N {count} in caps.",
		defaultUnitRu: "капс.",
	},
	{
		code: "granules_suspension",
		nameRu: "гранулы для приготовления суспензии для приема внутрь",
		nameLatin: "Granulae pro suspensionis oralis",
		latinAbbr: "gran.",
		dispensePatternLatin: "D.t.d. N {count} in gran.",
		defaultUnitRu: "пакет.",
	},
	{
		code: "powder_oral",
		nameRu: "порошок для приготовления раствора для приема внутрь",
		nameLatin: "Pulvis pro solutione orali",
		latinAbbr: "pulv.",
		dispensePatternLatin: "D.t.d. N {count} in chart.",
		defaultUnitRu: "пакет.",
	},
	{
		code: "solution_injection",
		nameRu: "раствор для инъекций (в/м, в/в)",
		nameLatin: "Solutio pro injectionibus",
		latinAbbr: "sol.",
		dispensePatternLatin: "D.t.d. N {count} in amp.",
		defaultUnitRu: "амп.",
	},
	{
		code: "solution_oral_topical",
		nameRu: "раствор для местного применения / ротовых ванночек",
		nameLatin: "Solutio ad usum externum / localem",
		latinAbbr: "sol.",
		dispensePatternLatin: "D.t.d. N {count} in flac.",
		defaultUnitRu: "флак.",
	},
	{
		code: "dental_gel",
		nameRu: "гель стоматологический / для местного применения",
		nameLatin: "Gelum dentale",
		latinAbbr: "gel.",
		dispensePatternLatin: "D.t.d. N {count} in tuba",
		defaultUnitRu: "туба",
	},
	{
		code: "dental_paste",
		nameRu: "дентальная адгезивная паста",
		nameLatin: "Pasta dentalis adhesiva",
		latinAbbr: "past.",
		dispensePatternLatin: "D.t.d. N {count} in tuba",
		defaultUnitRu: "туба",
	},
	{
		code: "spray_topical",
		nameRu: "спрей для местного применения дозированный",
		nameLatin: "Aerosolum / Spray",
		latinAbbr: "aeros.",
		dispensePatternLatin: "D.t.d. N {count} in flac.",
		defaultUnitRu: "флак.",
	},
	{
		code: "suppositories",
		nameRu: "суппозитории ректальные",
		nameLatin: "Suppositoria rectalia",
		latinAbbr: "supp.",
		dispensePatternLatin: "D.t.d. N {count} in supp.",
		defaultUnitRu: "супп.",
	},
];

export interface PrescriptionAdministrationRouteMeta {
	readonly code: string;
	readonly nameRu: string;
	readonly nameLatin: string;
	readonly signaPrefixRu: string;
	readonly commonInstructionsRu: readonly string[];
}

export const PRESCRIPTION_ADMINISTRATION_ROUTES_CATALOG: readonly PrescriptionAdministrationRouteMeta[] = [
	{
		code: "per_os",
		nameRu: "Внутрь (перорально)",
		nameLatin: "Per os",
		signaPrefixRu: "Внутрь",
		commonInstructionsRu: [
			"по 1 таб. 2 раза в день после еды, запивая водой",
			"по 1 таб. 3 раза в день во время еды",
			"по 1 пакетику 2 раза в день после еды, предварительно растворив в 100 мл теплой воды",
			"по 1 капсуле 1 раз в сутки утром натощак за 30 мин до еды",
			"по 1 таб. при выраженном болевом синдроме (не более 4 таб./сутки)",
		],
	},
	{
		code: "sublingual",
		nameRu: "Под язык (сублингвально)",
		nameLatin: "Sublingualiter",
		signaPrefixRu: "Под язык",
		commonInstructionsRu: [
			"по 1 таб. под язык до полного рассасывания при приступе боли",
			"по 1 таб. под язык 3 раза в день за 15 минут до еды",
		],
	},
	{
		code: "in_cavum_oris",
		nameRu: "Местно / В полость рта (ротовые ванночки, аппликации)",
		nameLatin: "In cavum oris / Localiter",
		signaPrefixRu: "Местно",
		commonInstructionsRu: [
			"ротовые ванночки по 10-15 мл неразведенного раствора 2-3 раза в день по 1 минуте после еды (не полоскать активно!)",
			"наносить полоской 1 см на пораженный участок десны 2-3 раза в день после чистки зубов (не принимать пищу 30 мин)",
			"аппликации на область послеоперационной раны 2 раза в сутки по 15 минут",
		],
	},
	{
		code: "intramuscular",
		nameRu: "Внутримышечно (в/м)",
		nameLatin: "Intramusculariter (i.m.)",
		signaPrefixRu: "Внутримышечно",
		commonInstructionsRu: [
			"в/м по 1 ампуле (1-2 мл) 1-2 раза в сутки при остром болевом синдроме",
			"в/м по 1 ампуле 1 раз в сутки глубоко в ягодичную мышцу, курс 3 дня",
		],
	},
	{
		code: "intravenous",
		nameRu: "Внутривенно (в/в)",
		nameLatin: "Intravenose (i.v.)",
		signaPrefixRu: "Внутривенно",
		commonInstructionsRu: [
			"в/в струйно медленно по 1 ампуле, разведенной в 10 мл 0.9% раствора натрия хлорида",
			"в/в капельно в 100-200 мл физиологического раствора со скоростью 40-60 кап/мин",
		],
	},
];


/** ═══════════════════════════════════════════════════════════════════════════
 * СПРАВОЧНИК СТОМАТОЛОГИЧЕСКИХ И МЕДИЦИНСКИХ ПРЕПАРАТОВ
 * ═══════════════════════════════════════════════════════════════════════════ */

export interface DentalPrescriptionDrugPreset {
	readonly id: string;
	readonly tradeNameRu: string;
	readonly activeSubstanceRu: string;
	readonly category: "nsaid" | "antibiotic" | "controlled_pku" | "antihistamine" | "antiseptic" | "corticosteroid" | "hemostatic" | "gastroprotective" | "preferential_somatic" | "other";
	readonly categoryLabel: string;
	readonly latinRp: string;
	readonly formRu: string;
	readonly dosageRu: string;
	readonly quantityLabel: string;
	readonly dispenseLatin: string;
	readonly signaRu: string;
	readonly recommendedForIcd10: readonly string[];
	readonly defaultValidityDays?: "15" | "30" | "60" | "365";
	readonly isPkuStrictAccounting?: boolean;
	readonly categoryLabelRu?: string;
	readonly adultDosageStandard?: string;
	readonly pediatricDosageStandard?: string;
	readonly validityDays?: number;
	readonly specialInstructions?: string;
}


export const DENTAL_PRESCRIPTION_DRUG_CATALOG: readonly DentalPrescriptionDrugPreset[] = [
	// ── НПВС и анальгетики ──
	{
		id: "nimesulide_100",
		tradeNameRu: "Нимесил (Нимесулид)",
		activeSubstanceRu: "Нимесулид",
		category: "nsaid",
		categoryLabel: "НПВС / Анальгетик",
		latinRp: "Rp.: Nimesulidi 100 mg",
		formRu: "гранулы для приготовления суспензии для приема внутрь",
		dosageRu: "100 мг",
		quantityLabel: "N. 10 (пакетики)",
		dispenseLatin: "D.t.d. N 10 in gran.",
		signaRu: "S. Внутрь по 1 пакетику (100 мг) 2 раза в день после еды, предварительно растворив содержимое пакетика в 100 мл теплой воды, 3-5 дней при боли.",
		recommendedForIcd10: ["K04.0", "K04.4", "K04.5", "K08.1", "K05.3", "K05.2"],
		defaultValidityDays: "60",
	},
	{
		id: "ibuprofen_400",
		tradeNameRu: "Ибупрофен (Нурофен Форте)",
		activeSubstanceRu: "Ибупрофен",
		category: "nsaid",
		categoryLabel: "НПВС / Анальгетик",
		latinRp: "Rp.: Ibuprofeni 400 mg",
		formRu: "таблетки, покрытые пленочной оболочкой",
		dosageRu: "400 мг",
		quantityLabel: "N. 20 (таблетки)",
		dispenseLatin: "D.t.d. N 20 in tab.",
		signaRu: "S. Внутрь по 1 таблетке (400 мг) 2-3 раза в день после еды, запивая водой. Не более 1200 мг в сутки, курс 3-5 дней.",
		recommendedForIcd10: ["K02.1", "K04.0", "K04.5", "K08.1"],
		defaultValidityDays: "60",
	},
	{
		id: "ketorolac_10",
		tradeNameRu: "Кеторолак (Кетанов)",
		activeSubstanceRu: "Кеторолак трометамин",
		category: "nsaid",
		categoryLabel: "НПВС (сильный анальгетик)",
		latinRp: "Rp.: Ketorolaci 10 mg",
		formRu: "таблетки, покрытые пленочной оболочкой",
		dosageRu: "10 мг",
		quantityLabel: "N. 10 (таблетки)",
		dispenseLatin: "D.t.d. N 10 in tab.",
		signaRu: "S. Внутрь по 1 таблетке (10 мг) при выраженном болевом синдроме (не более 4 таб./сутки, курс не более 3-5 дней).",
		recommendedForIcd10: ["K04.0", "K04.4", "K08.1"],
		defaultValidityDays: "60",
	},
	{
		id: "ketorol_10",
		tradeNameRu: "Кеторол (Кеторолак 10 мг)",
		activeSubstanceRu: "Кеторолак трометамин",
		category: "nsaid",
		categoryLabel: "НПВС (сильный анальгетик)",
		latinRp: "Rp.: Ketorolaci 10 mg",
		formRu: "таблетки, покрытые пленочной оболочкой",
		dosageRu: "10 мг",
		quantityLabel: "N. 10 (таблетки)",
		dispenseLatin: "D.t.d. N 10 in tab.",
		signaRu: "S. Внутрь по 1 таблетке (10 мг) при выраженном болевом синдроме (не более 4 таб./сутки, курс не более 3-5 дней).",
		recommendedForIcd10: ["K04.0", "K04.4", "K08.1"],
		defaultValidityDays: "60",
	},
	{
		id: "dexketoprofen_25",
		tradeNameRu: "Декскетопрофен (Дексалгин)",
		activeSubstanceRu: "Декскетопрофен трометамол",
		category: "nsaid",
		categoryLabel: "НПВС быстрого действия",
		latinRp: "Rp.: Dexketoprofeni 25 mg",
		formRu: "таблетки, покрытые пленочной оболочкой",
		dosageRu: "25 мг",
		quantityLabel: "N. 10 (таблетки)",
		dispenseLatin: "D.t.d. N 10 in tab.",
		signaRu: "S. Внутрь по 1 таблетке (25 мг) каждые 8 часов при болях (максимум 75 мг в сутки, курс до 3-5 дней).",
		recommendedForIcd10: ["K04.0", "K08.1"],
		defaultValidityDays: "60",
	},
	{
		id: "ketoprofen_150",
		tradeNameRu: "Кетонал Дуо (Кетопрофен)",
		activeSubstanceRu: "Кетопрофен",
		category: "nsaid",
		categoryLabel: "НПВС пролонгированного действия",
		latinRp: "Rp.: Caps. Ketoprofeni 150 mg",
		formRu: "капсулы с модифицированным высвобождением",
		dosageRu: "150 мг",
		quantityLabel: "N. 10 (капсулы)",
		dispenseLatin: "D.t.d. N 10 in caps.",
		signaRu: "S. Внутрь по 1 капсуле (150 мг) 1 раз в сутки после еды, запивая достаточным количеством воды, 3-5 дней.",
		recommendedForIcd10: ["K04.4", "K08.1"],
		defaultValidityDays: "60",
	},

	// ── Антибиотики и противомикробные средства ──
	{
		id: "amoxiclav_875_125",
		tradeNameRu: "Амоксиклав (Амоксициллин + Клавулановая кислота)",
		activeSubstanceRu: "Амоксициллин + [Клавулановая кислота]",
		category: "antibiotic",
		categoryLabel: "Антибиотик широкого спектра (защищенный пенициллин)",
		latinRp: "Rp.: Amoxicillini 875 mg + Acidi clavulanici 125 mg",
		formRu: "таблетки, покрытые пленочной оболочкой",
		dosageRu: "875 мг + 125 мг (1000 мг)",
		quantityLabel: "N. 14 (таблетки)",
		dispenseLatin: "D.t.d. N 14 in tab.",
		signaRu: "S. Внутрь по 1 таблетке (875/125 мг) 2 раза в сутки в начале приема пищи через равные интервалы (12 ч) в течение 5-7 дней.",
		recommendedForIcd10: ["K04.4", "K04.5", "K08.1", "K05.3", "K05.2"],
		defaultValidityDays: "60",
	},
	{
		id: "amoxiclav_500_125",
		tradeNameRu: "Амоксиклав 500/125",
		activeSubstanceRu: "Амоксициллин + [Клавулановая кислота]",
		category: "antibiotic",
		categoryLabel: "Антибиотик",
		latinRp: "Rp.: Amoxicillini 500 mg + Acidi clavulanici 125 mg",
		formRu: "таблетки, покрытые пленочной оболочкой",
		dosageRu: "500 мг + 125 мг",
		quantityLabel: "N. 15 (таблетки)",
		dispenseLatin: "D.t.d. N 15 in tab.",
		signaRu: "S. Внутрь по 1 таблетке 3 раза в сутки в начале приема пищи через каждые 8 часов в течение 5-7 дней.",
		recommendedForIcd10: ["K04.4", "K04.5", "K08.1", "K05.3"],
		defaultValidityDays: "60",
	},
	{
		id: "amoxicillin_500",
		tradeNameRu: "Амоксициллин (Флемоксин Солютаб)",
		activeSubstanceRu: "Амоксициллин",
		category: "antibiotic",
		categoryLabel: "Антибиотик (Пенициллин полусинтетический)",
		latinRp: "Rp.: Amoxicillini 500 mg",
		formRu: "капсулы / таблетки диспергируемые",
		dosageRu: "500 мг",
		quantityLabel: "N. 20 (капсулы)",
		dispenseLatin: "D.t.d. N 20 in caps.",
		signaRu: "S. Внутрь по 1 капсуле (500 мг) 3 раза в день через каждые 8 часов, курс 5-7 дней.",
		recommendedForIcd10: ["K04.4", "K04.5", "K08.1", "K05.3"],
		defaultValidityDays: "60",
	},
	{
		id: "azithromycin_500",
		tradeNameRu: "Сумамед (Азитромицин)",
		activeSubstanceRu: "Азитромицин",
		category: "antibiotic",
		categoryLabel: "Антибиотик-макролид (3-дневный курс)",
		latinRp: "Rp.: Azithromycini 500 mg",
		formRu: "капсулы / таблетки",
		dosageRu: "500 мг",
		quantityLabel: "N. 3 (капсулы)",
		dispenseLatin: "D.t.d. N 3 in caps.",
		signaRu: "S. Внутрь по 1 капсуле (500 мг) 1 раз в сутки за 1 час до еды или через 2 часа после еды, строго 3 дня (курсовая доза 1.5 г).",
		recommendedForIcd10: ["K04.4", "K05.3", "K08.1"],
		defaultValidityDays: "60",
	},
	{
		id: "clarithromycin_500",
		tradeNameRu: "Кларитромицин (Клацид 500 мг)",
		activeSubstanceRu: "Кларитромицин",
		category: "antibiotic",
		categoryLabel: "Антибиотик резерва (макролид при аллергии на пенициллины)",
		latinRp: "Rp.: Clarithromycini 500 mg",
		formRu: "таблетки, покрытые пленочной оболочкой",
		dosageRu: "500 мг",
		quantityLabel: "N. 10 (таблетки)",
		dispenseLatin: "D.t.d. N 10 in tab.",
		signaRu: "S. По 1 таблетке 1 раз в день 5-7 дней.",
		recommendedForIcd10: ["K04.4", "K04.5", "K08.1", "K05.3", "K05.2"],
		defaultValidityDays: "60",
	},
	{
		id: "ciprofloxacin_500",
		tradeNameRu: "Ципрофлоксацин (Цифран)",
		activeSubstanceRu: "Ципрофлоксацин",
		category: "antibiotic",
		categoryLabel: "Антибиотик (фторхинолон)",
		latinRp: "Rp.: Ciprofloxacini 500 mg",
		formRu: "таблетки, покрытые пленочной оболочкой",
		dosageRu: "500 мг",
		quantityLabel: "N. 10 (таблетки)",
		dispenseLatin: "D.t.d. N 10 in tab.",
		signaRu: "S. Внутрь по 1 таблетке (500 мг) 2 раза в сутки за 1 час до еды или через 2 часа после еды, запивая стаканом воды, 5-7 дней.",
		recommendedForIcd10: ["K04.4", "K08.1", "K05.3"],
		defaultValidityDays: "60",
	},
	{
		id: "cyfran_st",
		tradeNameRu: "Цифран СТ (Ципрофлоксацин + Тинидазол)",
		activeSubstanceRu: "Ципрофлоксацин + Тинидазол",
		category: "antibiotic",
		categoryLabel: "Антибиотик комбинированный (фторхинолон + нитроимидазол)",
		latinRp: "Rp.: Tab. 'Cifran ST' (Ciprofloxacini 500 mg + Tinidazoli 600 mg)",
		formRu: "таблетки, покрытые оболочкой",
		dosageRu: "500 мг + 600 мг",
		quantityLabel: "N. 10 (таблетки)",
		dispenseLatin: "D.t.d. N 10 in tab.",
		signaRu: "S. Внутрь по 1 таблетке 2 раза в сутки после еды через каждые 12 часов, запивая водой, курс 5 дней (пародонтальный абсцесс, перикоронит).",
		recommendedForIcd10: ["K04.4", "K05.2", "K05.3", "K08.1"],
		defaultValidityDays: "60",
	},
	{
		id: "metronidazole_500",
		tradeNameRu: "Метронидазол (Трихопол)",
		activeSubstanceRu: "Метронидазол",
		category: "antibiotic",
		categoryLabel: "Противомикробное (антианаэробное)",
		latinRp: "Rp.: Metronidazoli 500 mg",
		formRu: "таблетки",
		dosageRu: "500 мг",
		quantityLabel: "N. 20 (таблетки)",
		dispenseLatin: "D.t.d. N 20 in tab.",
		signaRu: "S. Внутрь по 1 таблетке (500 мг) 2 раза в день во время или после еды, не разжевывая, в течение 7 дней (при пародонтите / перикороните).",
		recommendedForIcd10: ["K05.3", "K05.2", "K04.4"],
		defaultValidityDays: "60",
	},
	{
		id: "lincomycin_500",
		tradeNameRu: "Линкомицин",
		activeSubstanceRu: "Линкомицин",
		category: "antibiotic",
		categoryLabel: "Антибиотик остеотропный",
		latinRp: "Rp.: Caps. Lincomycini hydrochloridi 0.5",
		formRu: "капсулы",
		dosageRu: "500 мг",
		quantityLabel: "N. 20 (капсулы)",
		dispenseLatin: "D.t.d. N 20 in caps.",
		signaRu: "S. Внутрь по 1 капсуле (500 мг) 3-4 раза в день за 1-2 часа до еды, запивая водой, 7-10 дней (при остеомиелите / периодонтите).",
		recommendedForIcd10: ["K04.4", "K04.5", "K10.2"],
		defaultValidityDays: "60",
	},
	{
		id: "amoxiclav_625",
		tradeNameRu: "Амоксиклав 625 мг",
		activeSubstanceRu: "Амоксициллин + [Клавулановая кислота]",
		category: "antibiotic",
		categoryLabel: "Антибиотик широкого спектра (защищенный пенициллин)",
		latinRp: "Rp.: Amoxicillini 500 mg + Acidi clavulanici 125 mg",
		formRu: "таблетки, покрытые пленочной оболочкой",
		dosageRu: "625 мг",
		quantityLabel: "N. 14 (таблетки)",
		dispenseLatin: "D.t.d. N 14 in tab.",
		signaRu: "S. Внутрь по 1 таблетке 2 раза в день 7 дней.",
		recommendedForIcd10: ["K04.4", "K04.5", "K08.1", "K05.3", "K05.2"],
		defaultValidityDays: "60",
	},
	{
		id: "ciprolet_500",
		tradeNameRu: "Ципролет 500 мг (Ципрофлоксацин)",
		activeSubstanceRu: "Ципрофлоксацин",
		category: "antibiotic",
		categoryLabel: "Антибиотик резерва (фторхинолон при аллергии на пенициллин)",
		latinRp: "Rp.: Ciprofloxacini 500 mg",
		formRu: "таблетки, покрытые пленочной оболочкой",
		dosageRu: "500 мг",
		quantityLabel: "N. 10 (таблетки)",
		dispenseLatin: "D.t.d. N 10 in tab.",
		signaRu: "S. Внутрь по 1 таблетке (500 мг) 2 раза в день 5-7 дней при аллергии на пенициллин.",
		recommendedForIcd10: ["K04.4", "K08.1", "K05.3"],
		defaultValidityDays: "60",
	},

	// ── Антисептики и стоматологические топические средства ──
	{
		id: "chlorhexidine_005",
		tradeNameRu: "Хлоргексидина биглюконат 0.05%",
		activeSubstanceRu: "Хлоргексидин",
		category: "antiseptic",
		categoryLabel: "Антисептик для полости рта",
		latinRp: "Rp.: Sol. Chlorhexidini bigluconatis 0.05% - 100 ml",
		formRu: "раствор для местного и наружного применения 0.05%",
		dosageRu: "0.05%",
		quantityLabel: "1 флакон (100 мл)",
		dispenseLatin: "D.t.d. N 1",
		signaRu: "S. Ротовые ванночки по 10-15 мл неразведенного раствора 2-3 раза в день по 1 минуте после еды (не полоскать активно!) в течение 5-7 дней.",
		recommendedForIcd10: ["K05.1", "K05.3", "K08.1", "Z01.2", "K05.2"],
		defaultValidityDays: "60",
	},
	{
		id: "metrogyl_denta",
		tradeNameRu: "Метрогил Дента",
		activeSubstanceRu: "Метронидазол + Хлоргексидин",
		category: "antiseptic",
		categoryLabel: "Стоматологический антибактериальный гель",
		latinRp: "Rp.: Gel. 'Metrogyl Denta' 20.0",
		formRu: "гель стоматологический",
		dosageRu: "20 г",
		quantityLabel: "1 туба (20 г)",
		dispenseLatin: "D.t.d. N 1 in tuba",
		signaRu: "S. Наносить на область десен 2 раза в день после чистки зубов в течение 7-10 дней. После нанесения не пить и не принимать пищу 30 минут.",
		recommendedForIcd10: ["K05.1", "K05.3", "K05.2"],
		defaultValidityDays: "60",
	},
	{
		id: "cholisal_gel",
		tradeNameRu: "Холисал гель",
		activeSubstanceRu: "Холина салицилат + Цеталкония хлорид",
		category: "antiseptic",
		categoryLabel: "Стоматологический противовоспалительный гель",
		latinRp: "Rp.: Gel. 'Cholisal' 10.0",
		formRu: "гель стоматологический",
		dosageRu: "10 г",
		quantityLabel: "1 туба (10 г)",
		dispenseLatin: "D.t.d. N 1 in tuba",
		signaRu: "S. Наносить полоской 1 см на пораженную слизистую/десну чистым пальцем 2-3 раза в день за 15 мин до еды или на ночь.",
		recommendedForIcd10: ["K05.1", "K12.0", "K12.1"],
		defaultValidityDays: "60",
	},
	{
		id: "miramistin_001",
		tradeNameRu: "Мирамистин 0.01%",
		activeSubstanceRu: "Бензилдиметил-миристоиламино-пропиламмоний",
		category: "antiseptic",
		categoryLabel: "Антисептик широкого спектра",
		latinRp: "Rp.: Sol. 'Miramistin' 0.01% - 150 ml",
		formRu: "раствор для местного применения",
		dosageRu: "0.01%",
		quantityLabel: "1 флакон (150 мл)",
		dispenseLatin: "D.t.d. N 1 in flac.",
		signaRu: "S. Орошать полость рта 3-4 раза в сутки путем 3-4 нажатий на насадку-распылитель после еды, 7 дней.",
		recommendedForIcd10: ["K05.1", "K12.0", "K08.1"],
		defaultValidityDays: "60",
	},
	{
		id: "stomatophyt_100",
		tradeNameRu: "Стоматофит",
		activeSubstanceRu: "Экстракт растительный (ромашка, кора дуба, шалфей, арника, аир, мята, тимьян)",
		category: "antiseptic",
		categoryLabel: "Фитопрепарат противовоспалительный / антисептик",
		latinRp: "Rp.: Extracti 'Stomatophyt' 100 ml",
		formRu: "экстракт для приготовления раствора для местного применения",
		dosageRu: "100 мл",
		quantityLabel: "1 флакон (100 мл)",
		dispenseLatin: "D.t.d. N 1 in flac.",
		signaRu: "S. Для полоскания полости рта: развести 7.5 мл (1/2 мерного стаканчика) в 1/4 стакана теплой воды, полоскать 3-4 раза в день после еды, 7-10 дней.",
		recommendedForIcd10: ["K05.1", "K05.3", "K12.0", "K08.1"],
		defaultValidityDays: "60",
	},
	{
		id: "chlorhexidine_012",
		tradeNameRu: "Хлоргексидин 0.12%",
		activeSubstanceRu: "Хлоргексидин",
		category: "antiseptic",
		categoryLabel: "Стоматологический антисептик для полоскания",
		latinRp: "Rp.: Sol. Chlorhexidini bigluconatis 0.12% - 300 ml",
		formRu: "раствор для полоскания полости рта 0.12%",
		dosageRu: "0.12%",
		quantityLabel: "1 флакон (300 мл)",
		dispenseLatin: "D.t.d. N 1 in flac.",
		signaRu: "S. Полоскание полости рта по 15 мл 2-3 раза в день в течение 1 минуты.",
		recommendedForIcd10: ["K05.1", "K05.3", "K05.2"],
		defaultValidityDays: "60",
	},
	{
		id: "solcoseryl_dental",
		tradeNameRu: "Солкосерил (дентальная адгезивная паста 5 г)",
		activeSubstanceRu: "Депротеинизированный диализат из крови телят + Полидоканол",
		category: "antiseptic",
		categoryLabel: "Стоматологическая адгезивная паста / регенерирующее средство",
		latinRp: "Rp.: Pastae Solcoseryl dentalis adhesivae 5.0",
		formRu: "паста дентальная адгезивная",
		dosageRu: "5 г",
		quantityLabel: "1 туба (5 г)",
		dispenseLatin: "D.t.d. N 1 in tuba",
		signaRu: "S. Наносить полоску пасты около 0.5 см на предварительно высушенный пораженный участок слизистой тонким слоем 3-5 раз в сутки после еды и перед сном.",
		recommendedForIcd10: ["K12.0", "K12.1", "K05.1", "K08.1"],
		defaultValidityDays: "60",
	},

	// ── Антигистаминные / Противоотечные средства ──
	{
		id: "suprastin_25",
		tradeNameRu: "Супрастин (Хлоропирамин)",
		activeSubstanceRu: "Хлоропирамин",
		category: "antihistamine",
		categoryLabel: "Антигистаминное / Противоотечное",
		latinRp: "Rp.: Tab. Chloropyramini 25 mg",
		formRu: "таблетки",
		dosageRu: "25 мг",
		quantityLabel: "N. 20 (таблетки)",
		dispenseLatin: "D.t.d. N 20 in tab.",
		signaRu: "S. Внутрь по 1 таблетке (25 мг) 2-3 раза в день во время еды, курс 3-5 дней для снижения послеоперационного отека.",
		recommendedForIcd10: ["K08.1", "K04.4", "K10.2"],
		defaultValidityDays: "60",
	},
	{
		id: "loratadine_10",
		tradeNameRu: "Лоратадин (Кларитин)",
		activeSubstanceRu: "Лоратадин",
		category: "antihistamine",
		categoryLabel: "Антигистаминное / Противоотечное",
		latinRp: "Rp.: Loratadini 10 mg",
		formRu: "таблетки",
		dosageRu: "10 мг",
		quantityLabel: "N. 10 (таблетки)",
		dispenseLatin: "D.t.d. N 10 in tab.",
		signaRu: "S. Внутрь по 1 таблетке (10 мг) 1 раз в сутки независимо от приема пищи в течение 5 дней для уменьшения постоперационного отека.",
		recommendedForIcd10: ["K08.1", "K04.4"],
		defaultValidityDays: "60",
	},
	{
		id: "cetirizine_10",
		tradeNameRu: "Цетрин (Цетиризин)",
		activeSubstanceRu: "Цетиризин",
		category: "antihistamine",
		categoryLabel: "Антигистаминное 2-го поколения",
		latinRp: "Rp.: Tab. Cetirizini 10 mg",
		formRu: "таблетки",
		dosageRu: "10 мг",
		quantityLabel: "N. 10 (таблетки)",
		dispenseLatin: "D.t.d. N 10 in tab.",
		signaRu: "S. Внутрь по 1 таблетке (10 мг) 1 раз в сутки вечером, запивая стаканом воды, 3-5 дней после имплантации / удаления.",
		recommendedForIcd10: ["K08.1", "K04.4"],
		defaultValidityDays: "60",
	},

	// ── Гемостатики ──
	{
		id: "tranexamic_acid_500",
		tradeNameRu: "Транексам (Транексамовая кислота)",
		activeSubstanceRu: "Транексамовая кислота",
		category: "hemostatic",
		categoryLabel: "Гемостатик (ингибитор фибринолиза)",
		latinRp: "Rp.: Acidi tranexamici 500 mg",
		formRu: "таблетки, покрытые пленочной оболочкой",
		dosageRu: "500 мг",
		quantityLabel: "N. 10 (таблетки)",
		dispenseLatin: "D.t.d. N 10 in tab.",
		signaRu: "S. Внутрь по 1 таблетке (500 мг) 3 раза в день при склонности к луночковому кровотечению после экстракции зуба, 2-3 дня.",
		recommendedForIcd10: ["K08.1", "T81.0"],
		defaultValidityDays: "60",
	},

	// ── Гастропротекторы (прикрытие НПВС) ──
	{
		id: "omeprazole_20",
		tradeNameRu: "Омепразол (Омез)",
		activeSubstanceRu: "Омепразол",
		category: "gastroprotective",
		categoryLabel: "Ингибитор протонной помпы (гастропротекция)",
		latinRp: "Rp.: Caps. Omeprazoli 20 mg",
		formRu: "капсулы кишечнорастворимые",
		dosageRu: "20 мг",
		quantityLabel: "N. 14 (капсулы)",
		dispenseLatin: "D.t.d. N 14 in caps.",
		signaRu: "S. Внутрь по 1 капсуле (20 мг) 1 раз в сутки утром за 30 минут до завтрака на весь период приема НПВС.",
		recommendedForIcd10: ["K04.0", "K04.4", "K08.1"],
		defaultValidityDays: "60",
	},
	{
		id: "linex_forte",
		tradeNameRu: "Линекс Форте (Пробиотик)",
		activeSubstanceRu: "Lactobacillus acidophilus + Bifidobacterium animalis",
		category: "gastroprotective",
		categoryLabel: "Эубиотик / Пробиотик (защита микробиоты)",
		latinRp: "Rp.: Caps. 'Linex Forte'",
		formRu: "капсулы",
		dosageRu: "стандартная",
		quantityLabel: "N. 14 (капсулы)",
		dispenseLatin: "D.t.d. N 14 in caps.",
		signaRu: "S. Внутрь по 1 капсуле 2 раза в день во время еды через 2 часа после приема антибиотика, курс 10-14 дней.",
		recommendedForIcd10: ["K04.4", "K05.3", "K08.1"],
		defaultValidityDays: "60",
	},

	{
		id: "drotaverine_40",
		tradeNameRu: "Дротаверин (Но-шпа)",
		activeSubstanceRu: "Дротаверин",
		category: "other",
		categoryLabel: "Миотропный спазмолитик",
		latinRp: "Rp.: Drotaverini 40 mg",
		formRu: "таблетки",
		dosageRu: "40 мг",
		quantityLabel: "N. 20 (таблетки)",
		dispenseLatin: "D.t.d. N 20 in tab.",
		signaRu: "S. Внутрь по 1 таблетке (40 мг) 2 раза в день как спазмолитик.",
		recommendedForIcd10: ["K04.0", "K04.1", "K04.2"],
		defaultValidityDays: "60",
	},
];

/** Выделенные пресеты для бланков строгой отчетности 148-1/у-88 */
export const CONTROLLED_DRUG_PRESETS = DENTAL_PRESCRIPTION_DRUG_CATALOG.filter(
	(d) => d.category === "controlled_pku",
);

/** Выделенные пресеты для льготных бланков 148-1/у-04(л) */
export const PREFERENTIAL_DRUG_PRESETS = DENTAL_PRESCRIPTION_DRUG_CATALOG.filter(
	(d) => d.category === "preferential_somatic" || d.category === "antibiotic" || d.category === "nsaid",
);

