/**
 * Patient Personal Portal & SMS/OTP Cabinet Presets & Scenarios
 * (DOMAIN: PORTAL PATIENT CABINET)
 *
 * Эталонные клинические сценарии и профили пациентов для тестирования и демонстрации:
 * 1. Алексей Владимирович Воронов — комплексная реабилитация, имплантация Osstem, неоплаченный счет СБП, неподписанное ИДС на синус-лифтинг.
 * 2. Елена Сергеевна Миронова — эстетическая реабилитация, виниры E.max, все счета оплачены, активный гарантийный паспорт.
 * 3. Дмитрий Константинович Соколов — первичный пациент с острой болью, пульпит #4.6, неподписанное согласие на эндодонтию.
 */

import type {
	PatientInvoiceItem,
	PatientPersonalCabinetData,
	PatientStatutoryConsent,
	PatientTreatmentPlan,
	PatientWarrantyCard,
} from "./patientCabinetEngine";

// ============================================================================
// PROFILE 1: Алексей Владимирович Воронов (Комплексная имплантация & ортопедия)
// ============================================================================

export const PATIENT_CABINET_PRESET_ALEXEY: PatientPersonalCabinetData = {
	patientId: "pat-8842",
	fullName: "Воронов Алексей Владимирович",
	phone: "+7 (999) 123-45-67",
	email: "alexey.voronov@example.com",
	birthDate: "1984-05-14",
	cardNumber: "043-8842",
	curatingDoctor: "Д-р Смирнов А. В. (Хирург-имплантолог, ортопед)",
	loyaltyBonusBalance: 12500,
	loyaltyTierRu: "Золотой (10%)",
	cashbackEarnedRub: 23500,
	dmsInsuranceName: "СОГАЗ ДМС Стоматология Премиум",
	dmsBalanceLimitRub: 150000,
	invoices: [
		{
			id: "inv-2026-089",
			invoiceNumber: "СЧ-2026/089",
			issueDateIso: "2026-08-20",
			dueDateIso: "2026-08-27",
			titleRu: "Фиксация постоянной циркониевой коронки Katana ML на имплант #2.6",
			totalAmountRub: 35000,
			paidAmountRub: 0,
			remainingAmountRub: 35000,
			status: "unpaid",
			items: [
				{
					code: "A16.07.006.002",
					titleRu: "Установка коронки из диоксида циркония Katana ML на имплантат Osstem",
					quantity: 1,
					priceRub: 29000,
					totalRub: 29000,
					toothFdi: "2.6",
				},
				{
					code: "A16.07.004",
					titleRu: "Индивидуальный титановый абатмент Osstem с винтовой фиксацией",
					quantity: 1,
					priceRub: 6000,
					totalRub: 6000,
					toothFdi: "2.6",
				},
			],
		},
		{
			id: "inv-2026-074",
			invoiceNumber: "СЧ-2026/074",
			issueDateIso: "2026-08-10",
			dueDateIso: "2026-08-10",
			titleRu: "Фиксация керамических виниров E.max (#1.1, #1.2, #2.1, #2.2) и коронки #1.6",
			totalAmountRub: 89000,
			paidAmountRub: 89000,
			remainingAmountRub: 0,
			status: "paid",
			paymentMethod: "sbp",
			paidAtIso: "2026-08-10T12:45:00Z",
			fiscalReceiptNumber: "ФД-982410",
			fiscalReceiptUrl: "https://receipt.nalog.ru/v1/check/inv-2026-074",
			items: [
				{
					code: "A16.07.003",
					titleRu: "Адгезивная фиксация керамического винира IPS e.max Press",
					quantity: 4,
					priceRub: 18000,
					totalRub: 72000,
					toothFdi: "1.1, 1.2, 2.1, 2.2",
				},
				{
					code: "A16.07.006",
					titleRu: "Винтовая фиксация циркониевой коронки на имплант Osstem #1.6",
					quantity: 1,
					priceRub: 17000,
					totalRub: 17000,
					toothFdi: "1.6",
				},
			],
		},
		{
			id: "inv-2026-052",
			invoiceNumber: "СЧ-2026/052",
			issueDateIso: "2026-06-25",
			dueDateIso: "2026-06-25",
			titleRu: "Навигационная установка 2 имплантатов Osstem TS III (#1.6, #2.6)",
			totalAmountRub: 110000,
			paidAmountRub: 110000,
			remainingAmountRub: 0,
			status: "paid",
			paymentMethod: "pos_terminal",
			paidAtIso: "2026-06-25T16:15:00Z",
			fiscalReceiptNumber: "ФД-773120",
			fiscalReceiptUrl: "https://receipt.nalog.ru/v1/check/inv-2026-052",
			items: [
				{
					code: "A16.07.054",
					titleRu: "Дентальная имплантация системы Osstem TS III SA (Южная Корея)",
					quantity: 2,
					priceRub: 45000,
					totalRub: 90000,
					toothFdi: "1.6, 2.6",
				},
				{
					code: "A16.07.054.001",
					titleRu: "Применение хирургического 3D шаблона навигационной хирургии",
					quantity: 1,
					priceRub: 20000,
					totalRub: 20000,
				},
			],
		},
	],
	appointments: [
		{
			id: "apt-8842-1",
			dateIso: "2026-09-05",
			timeRu: "14:30",
			doctorId: "doc-smirnov",
			doctorName: "Д-р Смирнов Андрей Васильевич",
			doctorSpecialtyRu: "Стоматолог-ортопед, хирург-имплантолог",
			doctorAvatarUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=200&q=80",
			roomNumber: "Кабинет № 4 (Хирургия / Ортопедия)",
			clinicName: "DENTE Премиум на Невском",
			clinicAddressRu: "г. Санкт-Петербург, Невский пр-т, д. 140, 2 этаж",
			titleRu: "Примерка и постоянная фиксация циркониевой коронки на зуб #2.6",
			status: "scheduled",
			priceRub: 35000,
			reminderSent: true,
			reminderChannel: "whatsapp",
			preparationInstructionsRu: [
				"За 1 час до приема рекомендуется легкий прием пищи",
				"При себе иметь паспорт для подтверждения личности",
				"После фиксации воздержаться от горячей и вязкой пищи 2 часа",
			],
		},
		{
			id: "apt-8842-2",
			dateIso: "2026-09-15",
			timeRu: "11:00",
			doctorId: "doc-kuznetsova",
			doctorName: "Д-р Кузнецова Ольга Игоревна",
			doctorSpecialtyRu: "Терапевт-эндодонтист",
			doctorAvatarUrl: "https://images.unsplash.com/photo-1594824813590-95b8cb4a88f4?auto=format&fit=crop&w=200&q=80",
			roomNumber: "Кабинет № 2 (Терапия)",
			clinicName: "DENTE Премиум на Невском",
			clinicAddressRu: "г. Санкт-Петербург, Невский пр-т, д. 140, 2 этаж",
			titleRu: "Контрольный осмотр и фотопротокол после эндолечения зуба #3.6",
			status: "scheduled",
			priceRub: 0,
			reminderSent: false,
		},
		{
			id: "apt-8842-past-1",
			dateIso: "2026-08-10",
			timeRu: "12:00",
			doctorId: "doc-smirnov",
			doctorName: "Д-р Смирнов Андрей Васильевич",
			doctorSpecialtyRu: "Стоматолог-ортопед",
			roomNumber: "Кабинет № 4",
			clinicName: "DENTE Премиум на Невском",
			clinicAddressRu: "г. Санкт-Петербург, Невский пр-т, д. 140",
			titleRu: "Фиксация постоянной коронки #1.6 и виниров #1.1-2.2",
			status: "completed",
			priceRub: 89000,
			reminderSent: true,
			reminderChannel: "sms",
		},
		{
			id: "apt-8842-past-2",
			dateIso: "2026-06-25",
			timeRu: "15:00",
			doctorId: "doc-smirnov",
			doctorName: "Д-р Смирнов Андрей Васильевич",
			doctorSpecialtyRu: "Хирург-имплантолог",
			roomNumber: "Кабинет № 4",
			clinicName: "DENTE Премиум на Невском",
			clinicAddressRu: "г. Санкт-Петербург, Невский пр-т, д. 140",
			titleRu: "Установка дентальных имплантатов Osstem (#1.6, #2.6)",
			status: "completed",
			priceRub: 110000,
			reminderSent: true,
			reminderChannel: "sms",
		},
	],
	treatmentPlans: [
		{
			id: "plan-8842-complex",
			planNumber: "ПЛАН-2026/042",
			titleRu: "Комплексная тотальная реабилитация: Имплантация + Цирконий + Виниры",
			curatingDoctor: "Д-р Смирнов А. В.",
			createdAtIso: "2026-06-10",
			totalCostRub: 340000,
			paidCostRub: 235000,
			remainingDueRub: 105000,
			progressPercent: 70,
			status: "in_progress",
			stages: [
				{
					id: "st-1",
					orderIndex: 1,
					titleRu: "Этап 1: Профессиональная гигиена и санация очагов кариеса",
					categoryRu: "Гигиена",
					teethFdi: ["1.1-4.8", "1.4"],
					costRub: 16000,
					status: "completed",
					procedures: [
						"Ультразвуковой скейлинг и Air-Flow Clinpro",
						"Лечение глубокого кариеса зуба #1.4 световым композитом",
					],
					targetDateRu: "Июнь 2026",
				},
				{
					id: "st-2",
					orderIndex: 2,
					titleRu: "Этап 2: Навигационная имплантация Osstem TS III",
					categoryRu: "Хирургия",
					teethFdi: ["1.6", "2.6"],
					costRub: 110000,
					status: "completed",
					procedures: [
						"Установка имплантата Osstem TS III в позиции #1.6",
						"Установка имплантата Osstem TS III в позиции #2.6",
						"Установка формирователей десны",
					],
					targetDateRu: "Июнь 2026",
				},
				{
					id: "st-3",
					orderIndex: 3,
					titleRu: "Этап 3: Эндодонтическое лечение под микроскопом",
					categoryRu: "Терапия",
					teethFdi: ["3.6"],
					costRub: 28000,
					status: "completed",
					procedures: [
						"Распломбировка и механическая обработка каналов VDW Reciproc",
						"Трехмерная обтурация горячей гуттаперчей BeeFill под микроскопом 25x",
					],
					targetDateRu: "Июль 2026",
				},
				{
					id: "st-4",
					orderIndex: 4,
					titleRu: "Этап 4: Эстетическая зона — Керамические виниры E.max",
					categoryRu: "Ортопедия",
					teethFdi: ["1.1", "1.2", "2.1", "2.2"],
					costRub: 89000,
					status: "completed",
					procedures: [
						"Микропрепарирование в пределах эмали 0.3 мм",
						"Адгезивная фиксация 4 виниров IPS e.max Press VITA A1",
						"Винтовая фиксация циркониевой коронки #1.6",
					],
					targetDateRu: "Август 2026",
				},
				{
					id: "st-5",
					orderIndex: 5,
					titleRu: "Этап 5: Завершение протезирования на импланте #2.6 и коронка #4.6",
					categoryRu: "Ортопедия",
					teethFdi: ["2.6", "4.6"],
					costRub: 97000,
					status: "in_progress",
					procedures: [
						"Винтовая фиксация циркониевой коронки Katana на имплант #2.6",
						"Препарирование и фиксация циркониевой коронки на зуб #4.6",
						"Финальная окклюзионная балансировка T-Scan",
					],
					targetDateRu: "Август - Сентябрь 2026",
				},
			],
		},
	],
	warranties: [
		{
			certificateId: "WAR-2026-8842-01",
			issueDateIso: "2026-06-25",
			expirationDateIso: "2031-06-25", // 5 лет гарантии
			adjustedWarrantyMonths: 60,
			doctorName: "Д-р Смирнов А. В.",
			status: "active",
			nextCheckupDueDateIso: "2026-10-05", // Через 44 дня от августа
			checkupIntervalMonths: 6,
			checkupScheduleCount: 10,
			verificationUrl: "https://dente-clinic.ru/portal/warranty?cert=WAR-2026-8842-01&card=043-8842",
			items: [
				{
					toothFdi: "1.6",
					workTitleRu: "Дентальный имплантат Osstem TS III SA с формирователем десны",
					materialName: "Титан Grade 4 (Osstem Implant)",
					manufacturer: "Osstem Implant Co., Ltd (Южная Корея)",
					lotNumber: "LOT #OSS-883419",
				},
				{
					toothFdi: "2.6",
					workTitleRu: "Дентальный имплантат Osstem TS III SA с формирователем десны",
					materialName: "Титан Grade 4 (Osstem Implant)",
					manufacturer: "Osstem Implant Co., Ltd (Южная Корея)",
					lotNumber: "LOT #OSS-883420",
				},
			],
		},
		{
			certificateId: "WAR-2026-8842-02",
			issueDateIso: "2026-08-10",
			expirationDateIso: "2028-08-10", // 24 месяца
			adjustedWarrantyMonths: 24,
			doctorName: "Д-р Смирнов А. В.",
			status: "active",
			nextCheckupDueDateIso: "2026-10-05",
			checkupIntervalMonths: 6,
			checkupScheduleCount: 4,
			verificationUrl: "https://dente-clinic.ru/portal/warranty?cert=WAR-2026-8842-02&card=043-8842",
			items: [
				{
					toothFdi: "1.1, 1.2, 2.1, 2.2",
					workTitleRu: "Керамические виниры IPS e.max Press",
					materialName: "Дисиликат лития IPS e.max",
					manufacturer: "Ivoclar Vivadent (Лихтенштейн)",
					vitaShade: "A1",
					lotNumber: "LOT #EMX-4410",
				},
				{
					toothFdi: "1.6",
					workTitleRu: "Коронка из диоксида циркония Katana ML на имплантат",
					materialName: "Высокотранслюцентный диоксид циркония Katana",
					manufacturer: "Kuraray Noritake Dental (Япония)",
					vitaShade: "A2",
					lotNumber: "LOT #KTN-9912",
				},
			],
		},
	],
	consents: [
		{
			id: "c-pending-1",
			code: "ИДС-ХИР-02",
			titleRu: "Информированное добровольное согласие на операцию синус-лифтинга и костной пластики",
			categoryRu: "Хирургия & Имплантация",
			statutoryBasis: "323-ФЗ",
			status: "pending_signature",
			diagnosisIcd: "K08.2 Атрофия альвеолярного края верхней челюсти",
			toothNumbers: "2.6, 2.7",
			summaryTextRu:
				"Проведение закрытого/открытого субантрального аугментирования дна гайморовой пазухи (синус-лифтинг) с использованием остеопластического биоматериала Bio-Oss и барьерной мембраны Bio-Gide.",
			fullTextContent:
				"Я, Воронов Алексей Владимирович, подтверждаю, что лечащий врач разъяснил мне цели, методы и возможные риски операции субантральной аугментации (синус-лифтинга) в области зубов #2.6, #2.7. Мне понятна необходимость соблюдения послеоперационного режима (исключение сморкания, перелетов и перепадов давления в течение 14 дней). Даю добровольное согласие в соответствии со ст. 20 Федерального закона № 323-ФЗ.",
		},
		{
			id: "c-signed-1",
			code: "ИДС-ТЕР-01",
			titleRu: "Информированное согласие на терапевтическое лечение и эндодонтию под микроскопом",
			categoryRu: "Терапия",
			statutoryBasis: "323-ФЗ",
			status: "signed",
			diagnosisIcd: "K04.0 Пульпит зуба #3.6",
			toothNumbers: "3.6",
			summaryTextRu: "Механическая и медикаментозная обработка корневых каналов под операционным дентальным микроскопом 25x.",
			fullTextContent: "Подтверждаю согласие на эндодонтическое лечение зуба #3.6. Подписано через SMS/OTP (63-ФЗ ПЭП).",
			signedAtIso: "2026-07-20T15:42:10Z",
			signatureAudit: {
				verificationMethod: "sms_otp",
				phone: "+7 (999) 123-45-67",
				smsOtpCode: "748291",
				integrityHash: "3f8a42b109cde8714041b312ef901452a819b9901723c0a1b2410f983419bbca",
				timestamp: 1784562130000,
				signedAtIso: "2026-07-20T15:42:10Z",
				legalBasis: "63-ФЗ ПЭП",
			},
			pdfDownloadUrl: "/portal/documents/consent-ids-ter-01-pat8842.pdf",
		},
		{
			id: "c-signed-2",
			code: "СОГЛ-ПД-152",
			titleRu: "Согласие на обработку персональных данных и врачебную тайну",
			categoryRu: "Персональные данные",
			statutoryBasis: "152-ФЗ",
			status: "signed",
			summaryTextRu: "Обработка специальных категорий персональных данных о состоянии здоровья в соответствии с 152-ФЗ.",
			fullTextContent: "Согласие на обработку ПДн пациента Воронова А. В. в МИС DENTE. Подписано при первичном приеме.",
			signedAtIso: "2026-06-10T10:15:00Z",
			signatureAudit: {
				verificationMethod: "sms_otp",
				phone: "+7 (999) 123-45-67",
				smsOtpCode: "884120",
				integrityHash: "a1c49802bf1e7842c9038204910248abef014285918237491029481920381029",
				timestamp: 1781086500000,
				signedAtIso: "2026-06-10T10:15:00Z",
				legalBasis: "63-ФЗ ПЭП",
			},
			pdfDownloadUrl: "/portal/documents/consent-pd-152-pat8842.pdf",
		},
	],
	threeTierModel: {
		selectedTier: "standard",
		tiers: [
			{
				tierId: "basic",
				tierNameRu: "Базовый (Эконом)",
				subtitleRu: "Функциональное восстановление базовыми материалами",
				totalCostRub: 195000,
				warrantyMonths: 12,
				durationWeeks: 4,
				benefits: [
					"Качественное световое пломбирование (композит)",
					"Стандартная металлокерамика на имплантах",
					"Базовая гарантия 1 год",
				],
				stages: [
					{
						id: "st-b1",
						orderIndex: 1,
						titleRu: "Санация и гигиеническая подготовка",
						categoryRu: "Гигиена",
						teethFdi: ["1.1-4.8"],
						costRub: 15000,
						status: "completed",
						procedures: ["Профессиональная гигиена полости рта", "Лечение кариеса 1.4"],
					},
					{
						id: "st-b2",
						orderIndex: 2,
						titleRu: "Имплантация и металлокерамические коронки",
						categoryRu: "Хирургия",
						teethFdi: ["1.6", "2.6"],
						costRub: 180000,
						status: "in_progress",
						procedures: ["Установка имплантатов", "Металлокерамические коронки"],
					},
				],
			},
			{
				tierId: "standard",
				tierNameRu: "Оптимальный (Стандарт)",
				subtitleRu: "Тотальная реабилитация: Импланты Osstem + Диоксид циркония + Виниры e.max",
				totalCostRub: 340000,
				warrantyMonths: 24,
				durationWeeks: 6,
				benefits: [
					"Высокоэстетичные виниры IPS e.max",
					"Коронки из монолитного диоксида циркония Katana ML",
					"Эндодонтия под операционным микроскопом 25x",
					"Гарантия 2 года",
				],
				stages: [
					{
						id: "st-s1",
						orderIndex: 1,
						titleRu: "Профессиональная гигиена и санация очагов кариеса",
						categoryRu: "Гигиена",
						teethFdi: ["1.1-4.8", "1.4"],
						costRub: 16000,
						status: "completed",
						procedures: ["Ультразвуковой скейлинг и Air-Flow", "Лечение глубокого кариеса #1.4"],
					},
					{
						id: "st-s2",
						orderIndex: 2,
						titleRu: "Навигационная имплантация Osstem TS III",
						categoryRu: "Хирургия",
						teethFdi: ["1.6", "2.6"],
						costRub: 110000,
						status: "completed",
						procedures: ["Установка имплантата #1.6", "Установка имплантата #2.6"],
					},
					{
						id: "st-s3",
						orderIndex: 3,
						titleRu: "Эндодонтическое лечение под микроскопом",
						categoryRu: "Терапия",
						teethFdi: ["3.6"],
						costRub: 28000,
						status: "completed",
						procedures: ["Механическая обработка каналов", "Обтурация BeeFill под микроскопом"],
					},
					{
						id: "st-s4",
						orderIndex: 4,
						titleRu: "Ортопедическая фиксация виниров E.max и коронки #1.6",
						categoryRu: "Ортопедия",
						teethFdi: ["1.1", "1.2", "2.1", "2.2", "1.6"],
						costRub: 89000,
						status: "completed",
						procedures: ["Фиксация 4 виниров e.max", "Винтовая коронка Katana ML на имплант #1.6"],
					},
					{
						id: "st-s5",
						orderIndex: 5,
						titleRu: "Постоянное циркониевое протезирование импланта #2.6",
						categoryRu: "Ортопедия",
						teethFdi: ["2.6"],
						costRub: 35000,
						status: "in_progress",
						procedures: ["Индивидуальный титановый абатмент", "Циркониевая коронка Katana ML"],
					},
				],
			},
			{
				tierId: "premium",
				tierNameRu: "Премиум (VIP All-Inclusive)",
				subtitleRu: "Премиум импланты Straumann, ультратонкие виниры и куратор 24/7",
				totalCostRub: 580000,
				warrantyMonths: 60,
				durationWeeks: 8,
				benefits: [
					"Импланты Straumann BLX Roxolid SLA",
					"Премиальная керамика e.max с послойным нанесением",
					"Персональный врач-куратор 24/7",
					"Расширенная гарантия 5 лет",
				],
				stages: [
					{
						id: "st-p1",
						orderIndex: 1,
						titleRu: "Digital Smile Design и SPA-гигиена",
						categoryRu: "Диагностика",
						teethFdi: ["1.1-4.8"],
						costRub: 40000,
						status: "completed",
						procedures: ["3D-моделирование улыбки", "Комплексная SPA-гигиена"],
					},
					{
						id: "st-p2",
						orderIndex: 2,
						titleRu: "Имплантация Straumann BLX",
						categoryRu: "Хирургия",
						teethFdi: ["1.6", "2.6"],
						costRub: 240000,
						status: "completed",
						procedures: ["Установка премиум-имплантатов Straumann", "Навигационный шаблон"],
					},
					{
						id: "st-p3",
						orderIndex: 3,
						titleRu: "Керамическая реабилитация All-Ceramic",
						categoryRu: "Ортопедия",
						teethFdi: ["1.1", "1.2", "2.1", "2.2", "1.6", "2.6"],
						costRub: 300000,
						status: "in_progress",
						procedures: ["Ультратонкие виниры", "Циркониевые коронки на абатментах Straumann"],
					},
				],
			},
		],
	},
	somaticRiskProfile: {
		hasCardiovascularRisk: true,
		hasSulfiteAllergy: false,
		hasLocalAnestheticsAllergy: false,
		hasBronchialAsthma: false,
		hasBleedingDisorder: false,
		hasDiabetes: false,
		isPregnantOrLactating: false,
		customNotes: "Контролируемая артериальная гипертензия, принимает ингибиторы АПФ.",
	},
	somaticAlerts: [
		{
			id: "alert_cardio",
			severity: "warning",
			title: "КАРДИОВАСКУЛЯРНЫЙ РИСК: Артериальная гипертензия",
			message: "Лимит эпинефрина: не более 0.04 мг. Контроль АД перед операцией.",
			recommendedAction: "Ультракаин Д-С 1:200 000 не более 4 карпул или Скандонест 3%.",
			category: "cardio",
		},
	],
	somaticRiskLevel: "moderate",
};

// ============================================================================
// PROFILE 2: Елена Сергеевна Миронова (Эстетика, виниры E.max, все оплачено)
// ============================================================================

export const PATIENT_CABINET_PRESET_ELENA: PatientPersonalCabinetData = {
	patientId: "pat-9201",
	fullName: "Миронова Елена Сергеевна",
	phone: "+7 (911) 987-65-43",
	email: "elena.mironova@example.com",
	birthDate: "1992-11-28",
	cardNumber: "043-9201",
	curatingDoctor: "Д-р Кузнецова О. И. (Ортопед-эстетист)",
	loyaltyBonusBalance: 34200,
	loyaltyTierRu: "Платиновый VIP (15%)",
	cashbackEarnedRub: 51300,
	invoices: [
		{
			id: "inv-9201-01",
			invoiceNumber: "СЧ-2026/099",
			issueDateIso: "2026-08-15",
			dueDateIso: "2026-08-15",
			titleRu: "Тотальное преображение улыбки: 8 керамических виниров IPS e.max Press",
			totalAmountRub: 220000,
			paidAmountRub: 220000,
			remainingAmountRub: 0,
			status: "paid",
			paymentMethod: "sbp",
			paidAtIso: "2026-08-15T14:30:00Z",
			fiscalReceiptNumber: "ФД-993821",
			fiscalReceiptUrl: "https://receipt.nalog.ru/v1/check/inv-9201-01",
			items: [
				{
					code: "A16.07.003",
					titleRu: "Керамический винир IPS e.max Press (Bleach 2)",
					quantity: 8,
					priceRub: 27500,
					totalRub: 220000,
					toothFdi: "1.4-2.4",
				},
			],
		},
	],
	appointments: [
		{
			id: "apt-9201-1",
			dateIso: "2026-08-27",
			timeRu: "16:00",
			doctorId: "doc-lebedeva",
			doctorName: "Д-р Лебедева Елена Михайловна",
			doctorSpecialtyRu: "Гигиенист-пародонтолог",
			roomNumber: "Кабинет № 1 (Профгигиена)",
			clinicName: "DENTE Премиум на Невском",
			clinicAddressRu: "г. Санкт-Петербург, Невский пр-т, д. 140",
			titleRu: "Контрольный осмотр гигиены и полировка виниров пастой Prisma Gloss",
			status: "scheduled",
			priceRub: 0,
			reminderSent: true,
			reminderChannel: "push",
		},
	],
	treatmentPlans: [
		{
			id: "plan-9201-esthetic",
			planNumber: "ПЛАН-2026/088",
			titleRu: "Эстетическая реабилитация зоны улыбки 8 винирами E.max",
			curatingDoctor: "Д-р Кузнецова О. И.",
			createdAtIso: "2026-07-01",
			totalCostRub: 220000,
			paidCostRub: 220000,
			remainingDueRub: 0,
			progressPercent: 100,
			status: "completed",
			stages: [
				{
					id: "st-9201-1",
					orderIndex: 1,
					titleRu: "Digital Smile Design (DSD) & Mock-up",
					categoryRu: "Диагностика",
					teethFdi: ["1.4-2.4"],
					costRub: 20000,
					status: "completed",
					procedures: ["Интраоральное 3D сканирование Trios", "Эстетический Mock-up в полости рта"],
				},
				{
					id: "st-9201-2",
					orderIndex: 2,
					titleRu: "Адгезивная фиксация 8 виниров E.max",
					categoryRu: "Ортопедия",
					teethFdi: ["1.4-2.4"],
					costRub: 200000,
					status: "completed",
					procedures: ["Препарирование 0.3 мм", "Адгезивная фиксация на цемент Variolink Esthetic"],
				},
			],
		},
	],
	warranties: [
		{
			certificateId: "WAR-2026-9201-01",
			issueDateIso: "2026-08-15",
			expirationDateIso: "2029-08-15", // 3 года
			adjustedWarrantyMonths: 36,
			doctorName: "Д-р Кузнецова О. И.",
			status: "active",
			nextCheckupDueDateIso: "2026-09-05", // Через 14 дней (urgent)
			checkupIntervalMonths: 6,
			checkupScheduleCount: 6,
			verificationUrl: "https://dente-clinic.ru/portal/warranty?cert=WAR-2026-9201-01&card=043-9201",
			items: [
				{
					toothFdi: "1.4-2.4",
					workTitleRu: "Керамические виниры IPS e.max Press (8 единиц)",
					materialName: "Дисиликат лития IPS e.max Press",
					manufacturer: "Ivoclar Vivadent (Лихтенштейн)",
					vitaShade: "Bleach 2",
					lotNumber: "LOT #EMX-9821",
				},
			],
		},
	],
	consents: [
		{
			id: "c-elena-1",
			code: "ИДС-ОРТ-01",
			titleRu: "Информированное согласие на ортопедическое лечение керамическими винирами",
			categoryRu: "Ортопедия",
			statutoryBasis: "323-ФЗ",
			status: "signed",
			summaryTextRu: "Препарирование твердых тканей зубов под микроскопом и адгезивная фиксация виниров E.max.",
			fullTextContent: "Согласие на эстетическую реставрацию 8 зубов винирами E.max. Подписано через SMS/OTP.",
			signedAtIso: "2026-08-01T11:00:00Z",
			signatureAudit: {
				verificationMethod: "sms_otp",
				phone: "+7 (911) 987-65-43",
				smsOtpCode: "192834",
				integrityHash: "591823abce901283419023841029384019238401928340192834019283401928",
				timestamp: 1785582000000,
				signedAtIso: "2026-08-01T11:00:00Z",
				legalBasis: "63-ФЗ ПЭП",
			},
			pdfDownloadUrl: "/portal/documents/consent-ids-ort-01-pat9201.pdf",
		},
	],
};

// ============================================================================
// PROFILE 3: Дмитрий Константинович Соколов (Острая боль, первичный прием)
// ============================================================================

export const PATIENT_CABINET_PRESET_DMITRY: PatientPersonalCabinetData = {
	patientId: "pat-9914",
	fullName: "Соколов Дмитрий Константинович",
	phone: "+7 (903) 555-12-34",
	birthDate: "1978-03-22",
	cardNumber: "043-9914",
	curatingDoctor: "Д-р Кузнецова О. И. (Терапевт-эндодонтист)",
	loyaltyBonusBalance: 1500,
	loyaltyTierRu: "Базовый",
	cashbackEarnedRub: 1500,
	invoices: [
		{
			id: "inv-9914-01",
			invoiceNumber: "СЧ-2026/104",
			issueDateIso: "2026-08-22",
			dueDateIso: "2026-08-22",
			titleRu: "Неотложная помощь при остром пульпите зуба #4.6 и анестезия",
			totalAmountRub: 6500,
			paidAmountRub: 0,
			remainingAmountRub: 6500,
			status: "unpaid",
			items: [
				{
					code: "A16.07.030",
					titleRu: "Неотложное купирование острой боли: раскрытие полости зуба, наложение пасты",
					quantity: 1,
					priceRub: 4500,
					totalRub: 4500,
					toothFdi: "4.6",
				},
				{
					code: "B01.003.004",
					titleRu: "Проводниковая мандибулярная анестезия препаратом Убистезин Форте",
					quantity: 1,
					priceRub: 2000,
					totalRub: 2000,
				},
			],
		},
	],
	appointments: [
		{
			id: "apt-9914-1",
			dateIso: "2026-08-22",
			timeRu: "18:30",
			doctorId: "doc-kuznetsova",
			doctorName: "Д-р Кузнецова Ольга Игоревна",
			doctorSpecialtyRu: "Терапевт-эндодонтист",
			roomNumber: "Кабинет № 2",
			clinicName: "DENTE Премиум на Невском",
			clinicAddressRu: "г. Санкт-Петербург, Невский пр-т, д. 140",
			titleRu: "Неотложный прием по острой боли (пульпит зуба #4.6)",
			status: "confirmed",
			priceRub: 6500,
			reminderSent: true,
			reminderChannel: "sms",
		},
	],
	treatmentPlans: [
		{
			id: "plan-9914-endo",
			planNumber: "ПЛАН-2026/104",
			titleRu: "Эндодонтическое лечение пульпита #4.6 и реставрация коронкой",
			curatingDoctor: "Д-р Кузнецова О. И.",
			createdAtIso: "2026-08-22",
			totalCostRub: 38000,
			paidCostRub: 0,
			remainingDueRub: 38000,
			progressPercent: 0,
			status: "in_progress",
			stages: [
				{
					id: "st-9914-1",
					orderIndex: 1,
					titleRu: "Неотложная помощь и девитализация",
					categoryRu: "Терапия",
					teethFdi: ["4.6"],
					costRub: 6500,
					status: "in_progress",
					procedures: ["Купирование боли, временная повязка"],
				},
				{
					id: "st-9914-2",
					orderIndex: 2,
					titleRu: "Инструментация и пломбирование 3 каналов",
					categoryRu: "Терапия",
					teethFdi: ["4.6"],
					costRub: 16500,
					status: "planned",
					procedures: ["Пломбирование каналов горячей гуттаперчей"],
				},
				{
					id: "st-9914-3",
					orderIndex: 3,
					titleRu: "Покрытие зуба циркониевой коронкой",
					categoryRu: "Ортопедия",
					teethFdi: ["4.6"],
					costRub: 15000,
					status: "planned",
					procedures: ["Циркониевая коронка для предотвращения раскола зуба"],
				},
			],
		},
	],
	warranties: [],
	consents: [
		{
			id: "c-dmitry-1",
			code: "ИДС-ПЕРВ-01",
			titleRu: "Информированное добровольное согласие на медицинское вмешательство и анестезию",
			categoryRu: "Анестезия",
			statutoryBasis: "323-ФЗ",
			status: "pending_signature",
			diagnosisIcd: "K04.0 Острый пульпит зуба #4.6",
			toothNumbers: "4.6",
			summaryTextRu:
				"Согласие на первичный осмотр, рентгенодиагностику, проводниковую анестезию и механическую обработку полости зуба.",
			fullTextContent:
				"Я, Соколов Дмитрий Константинович, даю информированное добровольное согласие на проведение лечебно-диагностических мероприятий и местной анестезии в клинике DENTE. Предупрежден о возможных временных парестезиях и аллергических реакциях.",
		},
	],
};

export const DEMO_PATIENT_CABINET = PATIENT_CABINET_PRESET_ALEXEY;
