/**
 * chairsidePresets.ts — Canonical clinical presets for ChairsideCopilotHUD.
 *
 * Compliance:
 * - Mandate 8b: Subcomponent <= 500 lines.
 * - Zero emojis, 100% strict clinical models.
 */

export const CLINICAL_PRESETS = [
  {
    id: "caries-16",
    label: "Кариес 16 (пломба + анестезия)",
    prompt: "вылечили кариес 16 зуба, световая пломба, анестезия убистезин 1 карпула",
    toothNumber: 16,
    toothState: "C2",
    toothStateLabel: "Кариес дентина (C2)",
    surfaces: ["O"],
    services: [
      {
        id: "srv-1",
        code804n: "A16.07.002.010",
        title: "Препарирование и медикаментозная обработка кариозной полости",
        quantity: 1,
        priceRub: 2500,
        toothNumber: 16,
      },
      {
        id: "srv-2",
        code804n: "A16.07.002.011",
        title: "Восстановление зуба пломбой светового отверждения (композит)",
        quantity: 1,
        priceRub: 4500,
        toothNumber: 16,
      },
      {
        id: "srv-3",
        code804n: "A25.07.001",
        title: "Местная анестезия (Убистезин 1 карпула 1.7 мл)",
        quantity: 1,
        priceRub: 1200,
        toothNumber: 16,
      },
    ],
    soap: {
      complaint: "Жалобы на кратковременные боли от термических и сладких раздражителей в зубе 16.",
      anamnesis: "Зуб ранее не лечен, дискомфорт возник около недели назад.",
      objectiveStatus: "На окклюзионной поверхности зуба 16 глубокая кариозная полость с пигментированным дентином. Зондирование дна чувствительно, перкуссия безболезненна.",
      diagnosis: "K02.1 Кариес дентина (зуб 16)",
      treatmentPlan: "Инфильтрационная анестезия Ubistesin 1.7 ml. Препарирование полости, некрэктомия, обработка 2% хлоргексидином. Адгезивная подготовка, нанокомпозит светового отверждения Filtek A2/OA2, шлифовка и полировка.",
      recommendations: "Щадящая диета 2 часа, контрольный осмотр через 6 месяцев.",
    },
    anesthetic: {
      drugName: "Убистезин (Артикаин 4% + эпинефрин 1:200 000)",
      carpulesCount: 1,
      patientWeightKg: 70,
      maxCarpules: 7,
      epinephrineMcg: 8.5,
      isCardiovascularRisk: false,
      notes: "В пределах МРД (до 7 карпул). Стандартная инфильтрационная анестезия.",
    },
    consent: {
      consentCode: "IDS-02-THERAPY",
      consentTitle: "ИДС на терапевтическое лечение кариеса и некариозных поражений",
      regulatoryBasis: "ст. 20 323-ФЗ, Приказ Минздрава 1051н",
      procedureType: "Терапия кариеса",
      toothOrArea: "Зуб 16",
    },
    safetyAlert: {
      id: "alert-1",
      severity: "info" as const,
      title: "Аллергический статус пациента",
      description: "Аллергия на пенициллины зафиксирована в карте. Назначенный анестетик Убистезин (Артикаин) безопасен.",
    },
    thoughts: [
      {
        id: "t1",
        stepNumber: 1,
        title: "Проверка аллергического статуса и лекарственной безопасности DDI...",
        status: "done" as const,
        detail: "Убистезин (Артикаин 4% + эпинефрин 1:200 000). Противопоказаний нет.",
        durationMs: 85,
      },
      {
        id: "t2",
        stepNumber: 2,
        title: "Сверка диагноза МКБ-10: K02.1 Кариес дентина...",
        status: "done" as const,
        detail: "Зуб 16, окклюзионная поверхность (O).",
        durationMs: 110,
      },
      {
        id: "t3",
        stepNumber: 3,
        title: "Расчет стоимости услуг по прейскуранту...",
        status: "done" as const,
        detail: "3 позиции: A16.07.002.010, A16.07.002.011, A25.07.001. Итого: 8 200 ₽.",
        durationMs: 95,
      },
      {
        id: "t4",
        stepNumber: 4,
        title: "Формирование клинического протокола приёма...",
        status: "done" as const,
        detail: "Протокол сформирован, готов к сохранению в ЭМК.",
        durationMs: 70,
      },
    ],
  },
  {
    id: "pulpitis-26",
    label: "Пульпит 26 (эндодонтия 3 канала)",
    prompt: "пульпит 26 зуба, эндодонтия 3 канала, временная пломба",
    toothNumber: 26,
    toothState: "P",
    toothStateLabel: "Пульпит (P)",
    surfaces: ["M", "O", "D"],
    services: [
      {
        id: "srv-p1",
        code804n: "A16.07.008",
        title: "Экстирпация пульпы и механическая обработка корневого канала (3 канала)",
        quantity: 3,
        priceRub: 6000,
        toothNumber: 26,
      },
      {
        id: "srv-p2",
        code804n: "A16.07.030",
        title: "Временное пломбирование лекарственным препаратом (Каласепт)",
        quantity: 1,
        priceRub: 1800,
        toothNumber: 26,
      },
      {
        id: "srv-p3",
        code804n: "A25.07.001",
        title: "Местная анестезия (Убистезин 1.7 мл)",
        quantity: 1,
        priceRub: 1200,
        toothNumber: 26,
      },
    ],
    soap: {
      complaint: "Жалобы на самопроизвольные приступообразные ночные боли в области зуба 26 с иррадиацией в висок.",
      anamnesis: "Боли начались 2 дня назад, усиливаются от температурных раздражителей.",
      objectiveStatus: "Глубокая кариозная полость MOD в зубе 26, зондирование болезненно в одной точке. Перкуссия слабо чувствительна.",
      diagnosis: "K04.0 Острый очаговый пульпит (зуб 26)",
      treatmentPlan: "Проводниковая анестезия. Раскрытие полости, экстирпация пульпы из 3 каналов (MB, DB, P). Медикаментозная обработка NaOCl 3%, ЭДТА 17%. Временное введение гидроксида кальция, временная повязка Септопак.",
      recommendations: "Повторный визит через 7 дней для постоянной обтурации каналов.",
    },
    anesthetic: {
      drugName: "Убистезин форте (Артикаин 4% + эпинефрин 1:100 000)",
      carpulesCount: 1,
      patientWeightKg: 70,
      maxCarpules: 7,
      epinephrineMcg: 17,
      isCardiovascularRisk: false,
      notes: "Проводниковая мандибулярная/туберальная анестезия при остром пульпите.",
    },
    consent: {
      consentCode: "IDS-03-ENDO",
      consentTitle: "ИДС на эндодонтическое лечение (депульпирование, обработка и пломбирование каналов)",
      regulatoryBasis: "ст. 20 323-ФЗ, Приказ Минздрава 1051н",
      procedureType: "Эндодонтическое лечение",
      toothOrArea: "Зуб 26",
    },
    safetyAlert: {
      id: "alert-2",
      severity: "warning" as const,
      title: "Эндодонтический протокол безопасности",
      description: "Обязателен рентген-контроль рабочей длины каналов перед постоянной обтурацией.",
    },
    thoughts: [
      {
        id: "tp1",
        stepNumber: 1,
        title: "Анализ болевого синдрома и проверка анамнеза...",
        status: "done" as const,
        detail: "Ночные боли с иррадиацией — классическая клиника острого пульпита.",
        durationMs: 75,
      },
      {
        id: "tp2",
        stepNumber: 2,
        title: "Сверка диагноза МКБ-10: K04.0 Пульпит...",
        status: "done" as const,
        detail: "Зуб 26, 3 канала (MB, DB, P).",
        durationMs: 90,
      },
      {
        id: "tp3",
        stepNumber: 3,
        title: "Калькуляция этапа эндодонтии...",
        status: "done" as const,
        detail: "Обработка 3 каналов + временная обтурация. Итого: 9 000 ₽.",
        durationMs: 80,
      },
      {
        id: "tp4",
        stepNumber: 4,
        title: "Генерация протокола эндодонтического лечения...",
        status: "done" as const,
        detail: "Протокол сформирован.",
        durationMs: 65,
      },
    ],
  },
  {
    id: "hygiene",
    label: "Профгигиена (Air-Flow + УЗ)",
    prompt: "профгигиена Air-Flow, ультразвуковой скейлинг, фторирование",
    toothNumber: 11,
    toothState: "NORM",
    toothStateLabel: "Норма (санация)",
    surfaces: [],
    services: [
      {
        id: "srv-h1",
        code804n: "A16.07.051",
        title: "Профессиональная гигиена полости рта и зубов (УЗ + Air-Flow)",
        quantity: 1,
        priceRub: 5000,
      },
      {
        id: "srv-h2",
        code804n: "A11.07.024",
        title: "Местное применение реминерализующих препаратов (фторирование)",
        quantity: 1,
        priceRub: 1500,
      },
    ],
    soap: {
      complaint: "Жалобы на наличие темного пигментированного налета и зубного камня.",
      anamnesis: "Последняя профессиональная гигиена проводилась более 1 года назад.",
      objectiveStatus: "Массивные наддесневые зубные отложения во фронтальном отделе нижней челюсти, пигментированный налет курильщика на молярах. Десна умеренно гиперемирована.",
      diagnosis: "K03.6 Зубные отложения",
      treatmentPlan: "Ультразвуковой скейлинг наддесневых отложений, воздушно-абразивная полировка Air-Flow порошком глицина, полировка пастой Cleanic, покрытие фторлаком Белак-F.",
      recommendations: "Не употреблять красящие продукты (кофе, чай) 24 часа. Замена зубной щетки.",
    },
    anesthetic: undefined,
    consent: {
      consentCode: "IDS-08-HYGIENE",
      consentTitle: "ИДС на проведение профессиональной гигиены и профилактических процедур",
      regulatoryBasis: "ст. 20 323-ФЗ, Приказ Минздрава 1051н",
      procedureType: "Профессиональная гигиена",
      toothOrArea: "Полость рта",
    },
    safetyAlert: {
      id: "alert-3",
      severity: "info" as const,
      title: "Гигиенический статус",
      description: "Противопоказаний нет. Рекомендована профгигиена и контрольный осмотр 1 раз в 6 месяцев.",
    },
    thoughts: [
      {
        id: "th1",
        stepNumber: 1,
        title: "Оценка гигиенических индексов (OHI-S, КПУ)...",
        status: "done" as const,
        detail: "Выявлены минерализованные наддесневые отложения.",
        durationMs: 60,
      },
      {
        id: "th2",
        stepNumber: 2,
        title: "Диагностика МКБ-10: K03.6 Зубные отложения...",
        status: "done" as const,
        detail: "Определен объем профессиональной гигиены.",
        durationMs: 70,
      },
      {
        id: "th3",
        stepNumber: 3,
        title: "Расчет комплекса профессиональной гигиены...",
        status: "done" as const,
        detail: "Комплекс A16.07.051 + реминерализация A11.07.024. Итого: 6 500 ₽.",
        durationMs: 80,
      },
      {
        id: "th4",
        stepNumber: 4,
        title: "Формирование протокола профилактического приёма...",
        status: "done" as const,
        detail: "Протокол гигиены подготовлен.",
        durationMs: 65,
      },
    ],
  },
  {
    id: "schedule-today",
    label: "Пациенты сегодня",
    prompt: "Сколько пациентов сегодня? Кто следующий на приёме?",
    toothNumber: 0,
    toothState: "Healthy",
    toothStateLabel: "Расписание дня",
    surfaces: [],
    services: [],
    soap: {
      complaint: "Запрос расписания приёма врача на сегодня.",
      anamnesis: "Текущая смена: 14:00–20:00, терапевтический кабинет.",
      objectiveStatus: "Всего приёмов: 6. Завершено: 3. В кресле: 1. Ожидается: 2.",
      diagnosis: "Оперативная сводка расписания",
      treatmentPlan: "1. 14:00 — Иванов И.И. (кариес 16, завершено). 2. 15:30 — Смирнова Е.В. (профгигиена). 3. 17:00 — Кузнецов А.П. (осмотр).",
      recommendations: "Подготовить наконечники и инструменты к приёму следующего пациента к 15:25.",
    },
    anesthetic: undefined,
    consent: undefined,
    safetyAlert: {
      id: "alert-sched",
      severity: "info" as const,
      title: "График приёма на сегодня",
      description: "Все слоты подтверждены администратором по WhatsApp. Задержек графика нет.",
    },
    verdict: "На сегодня запланировано 6 приёмов. Сейчас в кресле: текущий пациент. Следующий пациент в 15:30: Смирнова Е.В. (профгигиена).",
    thoughts: [
      {
        id: "ts-1",
        stepNumber: 1,
        title: "Запрос расписания смены врача...",
        status: "done" as const,
        detail: "Загружено 6 подтверждённых записей на сегодня.",
        durationMs: 40,
      },
      {
        id: "ts-2",
        stepNumber: 2,
        title: "Анализ статуса явки и тайминга приёма...",
        status: "done" as const,
        detail: "3 завершено, 1 на приёме, 2 ожидается. Отклонений от графика нет.",
        durationMs: 50,
      },
      {
        id: "ts-3",
        stepNumber: 3,
        title: "Формирование операционной сводки...",
        status: "done" as const,
        detail: "Следующий пациент: 15:30 — Смирнова Е.В.",
        durationMs: 35,
      },
    ],
  },
  {
    id: "doctor-shift",
    label: "Моя смена",
    prompt: "Какая у меня смена и график на этой неделе?",
    toothNumber: 0,
    toothState: "Healthy",
    toothStateLabel: "Табель смен",
    surfaces: [],
    services: [],
    soap: {
      complaint: "Запрос рабочего графика и сменности врача.",
      anamnesis: "Ставка: 1.0 (36 рабочих часов в неделю по нормативу Минздрава РФ).",
      objectiveStatus: "Пн, Ср, Пт — 1-я смена (08:00–14:00). Вт, Чт — 2-я смена (14:00–20:00). Выходные: Сб, Вс.",
      diagnosis: "График работы",
      treatmentPlan: "Сменность актуальна, замен и дежурств не назначено.",
      recommendations: "Соблюдение норм труда и отдыха медицинского персонала.",
    },
    anesthetic: undefined,
    consent: undefined,
    safetyAlert: {
      id: "alert-shift",
      severity: "info" as const,
      title: "Табель рабочего времени",
      description: "График утверждён главным врачом. Норма часов выполняется в полном объёме.",
    },
    verdict: "Ваш график на неделю: Пн, Ср, Пт — 1-я смена (08:00–14:00). Вт, Чт — 2-я смена (14:00–20:00). Замен нет.",
    thoughts: [
      {
        id: "tshift-1",
        stepNumber: 1,
        title: "Запрос графика сменности из штатного расписания...",
        status: "done" as const,
        detail: "Смена согласована, кабинет закреплен.",
        durationMs: 45,
      },
      {
        id: "tshift-2",
        stepNumber: 2,
        title: "Сверка с производственным табелем клиники...",
        status: "done" as const,
        detail: "Норма часов: 36 ч/неделю. Переработок нет.",
        durationMs: 40,
      },
    ],
  },
  {
    id: "daily-revenue",
    label: "Выручка за сегодня",
    prompt: "Какая выручка и касса за сегодня?",
    toothNumber: 0,
    toothState: "Healthy",
    toothStateLabel: "Касса дня",
    surfaces: [],
    services: [],
    soap: {
      complaint: "Запрос финансовой сводки за текущий рабочий день.",
      anamnesis: "Кассовая смена открыта в 08:00 администратором.",
      objectiveStatus: "Выручка за день: 42 800 ₽. Закрыто 3 наряда-заказа. Средний чек: 14 266 ₽.",
      diagnosis: "Финансовый отчет",
      treatmentPlan: "1. Терапия кариеса — 8 200 ₽. 2. Эндодонтия 26 — 18 500 ₽. 3. Профгигиена — 6 500 ₽. 4. Предоплата — 9 600 ₽.",
      recommendations: "Итоговый Z-отчет формируется при закрытии смены в 20:00.",
    },
    anesthetic: undefined,
    consent: undefined,
    safetyAlert: {
      id: "alert-fin",
      severity: "info" as const,
      title: "Финансовая сводка дня",
      description: "Безналичные платежи (терминал СБП / эквайринг): 35 000 ₽. Наличные: 7 800 ₽. Расхождений с кассой нет.",
    },
    verdict: "Выручка за сегодня: 42 800 ₽ (3 наряда-заказа, 1 предоплата). Безналичные: 35 000 ₽, Наличные: 7 800 ₽.",
    thoughts: [
      {
        id: "tfin-1",
        stepNumber: 1,
        title: "Агрегация закрытых заказ-нарядов и чеков дня...",
        status: "done" as const,
        detail: "3 заказ-наряда + 1 предоплата по смете. Итого 42 800 ₽.",
        durationMs: 50,
      },
      {
        id: "tfin-2",
        stepNumber: 2,
        title: "Сверка фискальных данных и способов оплаты...",
        status: "done" as const,
        detail: "Эквайринг/СБП: 35 000 ₽, наличные: 7 800 ₽. Данные сошлись 100%.",
        durationMs: 60,
      },
    ],
  },
];

export type ClinicalPreset = (typeof CLINICAL_PRESETS)[number];
export const defaultPreset: ClinicalPreset = CLINICAL_PRESETS[0]!;
