/**
 * Patient Mobile Portal & Online Booking Presets
 * (DOMAIN: PATIENT PORTAL PRESETS & CLINICAL SCENARIOS)
 */

import type {
	BookingBranch,
	BookingDoctor,
	BookingService,
	BookingTimeSlot,
	FiscalReceipt54Fz,
	PatientPortalProfile,
	PortalDocumentItem,
	PortalInvoiceItem,
	PortalTreatmentPlan,
	PortalTreatmentStage,
	PortalTreatmentProcedure,
	RadiologyScanItem,
	VisitProtocol043,
} from "./patientPortalTypes";

export const SAMPLE_PORTAL_PROFILE: PatientPortalProfile = {
	patientId: "PAT-2026-0891",
	fullName: "Смирнова Екатерина Васильевна",
	phone: "+7 (926) 555-12-34",
	email: "ekaterina.smirnova@example.com",
	birthDate: "1988-06-14",
	cardNumber: "043/у-2026/891",
	curatingDoctor: "Д-р Смирнов Алексей Петрович",
	curatingDoctorSpecialty: "Врач-стоматолог терапевт-эндодонтист",
	curatingDoctorAvatar: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=200&q=80",
	depositBalanceRub: 14500,
	loyaltyBonusRub: 4200,
	loyaltyTier: "Золотой статус (10%)",
	cashbackPercent: 10,
	dmsPolicy: {
		insurerName: "АО «СОГАЗ» Стоматология Премиум",
		policyNumber: "СГЗ-77-991283",
		coverageLimitRub: 150000,
		validUntilIso: "2026-12-31",
	},
};

export const SAMPLE_VISIT_PROTOCOLS: VisitProtocol043[] = [
	{
		id: "visit-2026-0828",
		dateIso: "2026-08-28",
		timeRu: "10:00",
		doctorId: "doc-smirnov",
		doctorName: "Д-р Смирнов Алексей Петрович",
		doctorSpecialty: "Врач-стоматолог терапевт-эндодонтист",
		branchName: "Филиал «Центральный — Невский пр-т»",
		cabinetNumber: "Кабинет № 1 (Терапия)",
		toothFdi: "1.6",
		diagnosisIcd10: "K04.0",
		diagnosisText: "Острый очаговый пульпит зуба 1.6",
		complaints: "Самопроизвольные приступообразные боли в зубе 1.6, усиливающиеся в ночное время и от температурных раздражителей (холодное/горячее).",
		anamnesis: "Зуб 1.6 ранее лечен 2 года назад по поводу глубокого кариеса. Боли появились 2 дня назад, интенсивность нарастает.",
		statusLocalis: "На жевательно-медиальной поверхности зуба 1.6 глубокая кариозная полость под дефектной пломбой. Зондирование дна резко болезненно в области медиально-щечного рога пульпы. Перкуссия зуба слабо болезненна. Слизистая оболочка переходной складки без признаков воспаления.",
		treatmentProtocol: "Под инфильтрационной анестезией Sol. Ultracaini DS Forte 1.7 ml проведено снятие старой пломбы, некрэктомия, раскрытие полости зуба, экстирпация пульпы из 3 корневых каналов (MB, DB, Palatal). Механическая обработка никель-титановыми файлами Reciproc Blue R25 с ирригацией 3% NaOCl и 17% EDTA. Высушивание бумажными штифтами, трехмерная обтурация термопластифицированной гуттаперчей GuttaCore и силером AH Plus. Наложена герметичная временная пломба Cavit / Septo-pack.",
		anesthesia: {
			anestheticName: "Sol. Ultracaini DS Forte (Артикаин 4% + Эпинефрин 1:100 000)",
			volumeMl: 1.7,
			method: "Инфильтрационная",
		},
		materialsUsed: [
			{ name: "Набор машинных файлов Reciproc Blue R25", quantity: 1, unit: "упак." },
			{ name: "Обтураторы GuttaCore для зуба 16", quantity: 3, unit: "шт." },
			{ name: "Силер эпоксидный AH Plus", quantity: 1, unit: "доза" },
			{ name: "Временный пломбировочный материал Cavit", quantity: 1, unit: "порция" },
		],
		postOpRecommendations: [
			"Не принимать пищу в течение 2 часов до полной стабилизации временной пломбы.",
			"При возникновении постоперационной чувствительности принять НПВС: Ибупрофен 400 мг или Нимесил 100 мг (не более 3 дней).",
			"Исключить жевание твердой и вязкой пищи на правой стороне челюсти.",
			"Явка на контрольный прием 04.09.2026 для постоянного ортопедического восстановления зуба 1.6 коронкой Katana ML.",
		],
		nextVisitRecommendedIso: "2026-09-04",
		status: "completed",
	},
	{
		id: "visit-2026-0814",
		dateIso: "2026-08-14",
		timeRu: "14:00",
		doctorId: "doc-smirnov",
		doctorName: "Д-р Смирнов Алексей Петрович",
		doctorSpecialty: "Врач-стоматолог терапевт",
		branchName: "Филиал «Центральный — Невский пр-т»",
		cabinetNumber: "Кабинет № 1 (Терапия)",
		toothFdi: "2.4",
		diagnosisIcd10: "K02.1",
		diagnosisText: "Кариес дентина (средний кариес) зуба 2.4",
		complaints: "Застревание волокнистой пищи в межзубном промежутке 2.4–2.5, кратковременная реакция на сладкое.",
		anamnesis: "Полость обнаружена при профилактическом осмотре.",
		statusLocalis: "Кариозная полость II класса по Блэку на дистально-аппроксимальной поверхности зуба 2.4. Зондирование эмалево-дентинной границы чувствительно.",
		treatmentProtocol: "Под инфильтрационной анестезией Sol. Ultracaini DS 1.7 ml проведено препарирование кариозной полости, изоляция коффердамом Sanctuary, пескоструйная обработка оксидом алюминия 27 мкм. Тотальное протравливание 37% фосфорной кислотой 15 сек, адгезивный протокол OptiBond FL. Послойное моделирование наногибридным композитом Estelite Asteria (оттенки A2B, NE). Шлифовка и финишная полировка головками Enhance и пастой Prisma Gloss.",
		anesthesia: {
			anestheticName: "Sol. Ultracaini DS (Артикаин 4% + Эпинефрин 1:200 000)",
			volumeMl: 1.7,
			method: "Инфильтрационная",
		},
		materialsUsed: [
			{ name: "Коффердам латексный Sanctuary", quantity: 1, unit: "лист" },
			{ name: "Адгезивная система OptiBond FL", quantity: 1, unit: "доза" },
			{ name: "Композит светоотверждаемый Estelite Asteria", quantity: 1, unit: "шприц" },
		],
		postOpRecommendations: [
			"Ограничить употребление сильно красящих продуктов (черный кофе, свекла, черника) в первые 24 часа.",
			"Соблюдать стандартную гигиену с использованием межзубной нити.",
		],
		status: "completed",
	},
	{
		id: "visit-2026-0610",
		dateIso: "2026-06-10",
		timeRu: "11:30",
		doctorId: "doc-vasilieva",
		doctorName: "Д-р Васильева Ольга Игоревна",
		doctorSpecialty: "Врач-стоматолог гигиенист-пародонтолог",
		branchName: "Филиал «Центральный — Невский пр-т»",
		cabinetNumber: "Кабинет № 3 (Гигиена)",
		toothFdi: "11-48",
		diagnosisIcd10: "K05.1",
		diagnosisText: "Хронический простой гингивит",
		complaints: "Кровоточивость десен при чистке зубов, наличие плотного пигментированного налета.",
		anamnesis: "Профессиональная гигиена не проводилась более 10 месяцев.",
		statusLocalis: "Обильные наддесневые минерализованные отложения во фронтальном отделе нижней челюсти (зубы 3.3-4.3). Пигментированный налет курильщика/чая. Десневой край гиперемирован, отечен.",
		treatmentProtocol: "Аппликационная анестезия гелем Лидоксор. Ультразвуковой скейлинг аппаратом EMS Piezon Master No-Pain для удаления зубного камня. Воздушно-абразивная полировка AirFlow с порошком на основе эритритола 14 мкм (AirFlow Plus). Межзубная сепарация штрипсами. Глубокое фторирование эмали лаком Bifluorid 12.",
		anesthesia: {
			anestheticName: "Гель Лидоксор (Лидокаин 15%)",
			volumeMl: 0.5,
			method: "Аппликационная",
		},
		materialsUsed: [
			{ name: "Порошок EMS AirFlow Plus (Эритритол)", quantity: 1, unit: "флакон" },
			{ name: "Лак фторсодержащий Bifluorid 12", quantity: 1, unit: "доза" },
		],
		postOpRecommendations: [
			"Заменить зубную щетку на новую с мягкой щетиной (Curaprox CS 5460).",
			"В течение 3 дней полоскать полость рта раствором Мирамистина 0.01% после чистки зубов.",
			"Контрольный осмотр и повторная профгигиена через 6 месяцев.",
		],
		status: "completed",
	},
];

export const SAMPLE_RADIOLOGY_SCANS: RadiologyScanItem[] = [
	{
		id: "scan-rvg-16",
		studyDateIso: "2026-08-28 10:45",
		modality: "rvg",
		modalityLabel: "Прицельная радиовизиография RVG",
		toothFdi: ["16"],
		effectiveDoseMicrosv: 3.0,
		imageUrl: "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=800&q=80",
		diagnosticConclusion: "Контрольная радиовизиография зуба 16 после механической обработки и обтурации корневых каналов. 3 корневых канала (MB, DB, Palatal) равномерно и плотно обтурированы гуттаперчей до физиологических верхушек. Периапикальная костная ткань без признаков деструкции.",
		doctorName: "Д-р Смирнов Алексей Петрович",
		clinicName: "ООО «Стоматологическая клиника ДЕНТЕ»",
		apparatusModel: "Vatech EzSensor Classic (РФ Рег. уд. ФСЗ 2011/10542)",
		metadata: {
			kv: 65,
			ma: 7.0,
			exposureSec: 0.08,
			resolution: "25 пар линий/мм (1200x900 px)",
		},
	},
	{
		id: "scan-optg-panoramic",
		studyDateIso: "2026-06-10 11:15",
		modality: "optg",
		modalityLabel: "Ортопантомография (ОПТГ обзорная)",
		toothFdi: ["11-18", "21-28", "31-38", "41-48"],
		effectiveDoseMicrosv: 18.5,
		imageUrl: "https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=800&q=80",
		diagnosticConclusion: "Обзорная цифровая ортопантомограмма челюстей. Альвеолярная кость сохранена, признаков генерализованного пародонтита нет. Зубы 1.8, 2.8, 3.8, 4.8 ретенированы в челюстной кости. В области зуба 1.6 — глубокий кариозный дефект под пломбой.",
		doctorName: "Д-р Васильева Ольга Игоревна",
		clinicName: "ООО «Стоматологическая клиника ДЕНТЕ»",
		apparatusModel: "Vatech PaX-i 2D Panoramic",
		metadata: {
			kv: 72,
			ma: 10.0,
			exposureSec: 10.4,
			resolution: "2400x1200 px",
		},
	},
	{
		id: "scan-cbct-3d",
		studyDateIso: "2026-05-15 16:00",
		modality: "cbct",
		modalityLabel: "3D Конусно-лучевая томография (КЛКТ)",
		toothFdi: ["16", "17", "26", "27"],
		effectiveDoseMicrosv: 42.0,
		imageUrl: "https://images.unsplash.com/photo-1530497610245-94d3c16cda28?auto=format&fit=crop&w=800&q=80",
		diagnosticConclusion: "3D КЛКТ верхней челюсти (FOV 8x8 см). В зубе 1.6 верифицировано 4 канала (MB1, MB2, DB, Palatal). Дно верхнечелюстного синуса интактно, толщина костной перегородки 12.4 мм. Слизистая пазухи без утолщений.",
		doctorName: "Д-р Барабаш Сергей Владимирович",
		clinicName: "ООО «Стоматологическая клиника ДЕНТЕ»",
		apparatusModel: "Vatech Green 16 CBCT 3D",
		metadata: {
			kv: 90,
			ma: 6.5,
			exposureSec: 14.0,
			resolution: "Voxel size 0.12 mm (FOV 80x80 mm)",
		},
	},
];

export const SAMPLE_FISCAL_RECEIPT_1: FiscalReceipt54Fz = {
	receiptNumber: "ЧЕК-2026/891",
	dateIso: "2026-08-28T11:05:00+03:00",
	fnNumber: "9960440301824190",
	fdNumber: "48291",
	fpdNumber: "3892014821",
	ofdName: "ООО «Платформа ОФД»",
	fnsUrl: "https://receipt.nalog.ru/v1/check/48291",
	totalAmountRub: 14500,
	vatRateRu: "Без НДС (пп. 2 п. 2 ст. 149 НК РФ)",
	paymentMethod: "sbp",
	fiscalQrData: "t=20260828T1105&s=14500.00&fn=9960440301824190&i=48291&fp=3892014821&n=1",
	items: [
		{
			code804n: "A16.07.030.002",
			titleRu: "Инструментальная и медикаментозная обработка 3 корневых каналов",
			quantity: 1,
			priceRub: 8500,
			totalRub: 8500,
			toothFdi: "1.6",
		},
		{
			code804n: "A16.07.008",
			titleRu: "Пломбирование корневых каналов термопластичной гуттаперчей GuttaCore",
			quantity: 1,
			priceRub: 4800,
			totalRub: 4800,
			toothFdi: "1.6",
		},
		{
			code804n: "A16.07.002.001",
			titleRu: "Анестезия инфильтрационная Sol. Ultracaini DS Forte 1.7 ml",
			quantity: 1,
			priceRub: 1200,
			totalRub: 1200,
			toothFdi: "1.6",
		},
	],
};

export const SAMPLE_PORTAL_INVOICES: PortalInvoiceItem[] = [
	{
		id: "inv-2026-891",
		invoiceNumber: "СЧ-2026/891",
		issueDateIso: "2026-08-28",
		dueDateIso: "2026-08-28",
		titleRu: "Эндодонтическое лечение 3 корневых каналов зуба 1.6",
		totalAmountRub: 14500,
		paidAmountRub: 14500,
		remainingAmountRub: 0,
		status: "paid",
		paymentMethod: "sbp",
		paidAtIso: "2026-08-28T11:05:00+03:00",
		fiscalReceipt: SAMPLE_FISCAL_RECEIPT_1,
		items: [
			{ code: "A16.07.030.002", titleRu: "Обработка 3 каналов Reciproc Blue", quantity: 1, priceRub: 8500, totalRub: 8500, toothFdi: "1.6" },
			{ code: "A16.07.008", titleRu: "Обтурация каналов GuttaCore", quantity: 1, priceRub: 4800, totalRub: 4800, toothFdi: "1.6" },
			{ code: "A16.07.002.001", titleRu: "Анестезия Ultracain DS Forte", quantity: 1, priceRub: 1200, totalRub: 1200, toothFdi: "1.6" },
		],
	},
	{
		id: "inv-2026-914",
		invoiceNumber: "СЧ-2026/914",
		issueDateIso: "2026-08-28",
		dueDateIso: "2026-09-04",
		titleRu: "Изготовление и установка коронки из диоксида циркония Katana ML на зуб 1.6",
		totalAmountRub: 28000,
		paidAmountRub: 0,
		remainingAmountRub: 28000,
		status: "unpaid",
		items: [
			{ code: "A16.07.004.001", titleRu: "Восстановление зуба коронкой из диоксида циркония Katana Multi-layer", quantity: 1, priceRub: 25000, totalRub: 25000, toothFdi: "1.6" },
			{ code: "A16.07.004.002", titleRu: "Цифровое интраоральное 3D-сканирование челюстей (iTero Element)", quantity: 1, priceRub: 3000, totalRub: 3000, toothFdi: "1.6" },
		],
	},
	{
		id: "inv-2026-780",
		invoiceNumber: "СЧ-2026/780",
		issueDateIso: "2026-08-14",
		dueDateIso: "2026-08-14",
		titleRu: "Эстетическая реставрация зуба 2.4 нанокомпозитом Estelite Asteria",
		totalAmountRub: 6800,
		paidAmountRub: 6800,
		remainingAmountRub: 0,
		status: "paid",
		paymentMethod: "pos",
		paidAtIso: "2026-08-14T14:50:00+03:00",
		items: [
			{ code: "A16.07.002.002", titleRu: "Восстановление зуба пломбой Estelite Asteria (II класс)", quantity: 1, priceRub: 5600, totalRub: 5600, toothFdi: "2.4" },
			{ code: "A16.07.002.001", titleRu: "Анестезия инфильтрационная Ultracain DS", quantity: 1, priceRub: 1200, totalRub: 1200, toothFdi: "2.4" },
		],
	},
];

export const SAMPLE_PORTAL_DOCUMENTS: PortalDocumentItem[] = [
	{
		id: "doc-ids-1051n-endo",
		titleRu: "Информированное добровольное согласие (ИДС) на эндодонтическое лечение",
		category: "consent",
		codeOrderRu: "Приказ Минздрава России № 1051н / ст. 20 323-ФЗ",
		dateIso: "2026-08-28",
		status: "signed",
		signMethod: "sms_otp",
		signedAtIso: "2026-08-28T09:55:00+03:00",
		details: "Подписано простой электронной подписью (SMS-код верификации 7788 на номер +7 (926) ***-12-34). Врач: Д-р Смирнов А. П.",
	},
	{
		id: "doc-contract-891",
		titleRu: "Договор об оказании платных медицинских услуг № ДОГ-2026/891",
		category: "contract",
		codeOrderRu: "Постановление Правительства РФ № 736 от 11.05.2023",
		dateIso: "2026-06-10",
		status: "signed",
		signMethod: "paper",
		signedAtIso: "2026-06-10T11:00:00+03:00",
		details: "Двусторонний договор на стоматологические услуги. Лицензия клиники № ЛО-77-01-019842 от 15.04.2020.",
	},
	{
		id: "doc-fns-tax-2026",
		titleRu: "Справка об оплате медицинских услуг для представления в налоговый орган (ФНС КНД 1151156)",
		category: "tax_deduction",
		codeOrderRu: "Приказ ФНС России от 08.11.2023 № ЕА-7-11/824@",
		dateIso: "2026-08-28",
		status: "ready",
		details: "Справка для социального налогового вычета по НДФЛ за 2026 год на сумму 21 300 ₽. Код услуги: 1 (Обычное лечение).",
	},
	{
		id: "doc-warranty-card",
		titleRu: "Гарантийный паспорт на терапевтические и ортопедические работы",
		category: "warranty",
		codeOrderRu: "Положение о гарантиях ООО «ДЕНТЕ» по закону РФ № 2300-1",
		dateIso: "2026-08-14",
		status: "signed",
		details: "Гарантия на реставрацию зуба 2.4 — 24 месяца при условии прохождения профосмотра раз в 6 месяцев.",
	},
];

// ONLINE BOOKING PRESETS

export const SAMPLE_BOOKING_BRANCHES: BookingBranch[] = [
	{
		id: "branch-central",
		nameRu: "Филиал «Центральный — Невский пр-т»",
		addressRu: "г. Санкт-Петербург, Невский пр-т, д. 140, 2 этаж",
		metroStationRu: "Площадь Восстания / Маяковская",
		metroLineColor: "#ef4444",
		phone: "+7 (812) 600-40-50",
		workHoursRu: "Пн-Вс: 08:00 – 21:30",
		parkingInfoRu: "Бесплатная охраняемая парковка во дворе для пациентов",
		imageUrl: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=400&q=80",
	},
	{
		id: "branch-petrograd",
		nameRu: "Филиал «Петроградский — Каменноостровский»",
		addressRu: "г. Санкт-Петербург, Каменноостровский пр-т, д. 42",
		metroStationRu: "Петроградская",
		metroLineColor: "#3b82f6",
		phone: "+7 (812) 600-40-51",
		workHoursRu: "Пн-Вс: 09:00 – 21:00",
		parkingInfoRu: "Городская платная парковка (клиника компенсирует)",
		imageUrl: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=400&q=80",
	},
	{
		id: "branch-moscow",
		nameRu: "Филиал «Московский — Парк Победы»",
		addressRu: "г. Санкт-Петербург, пр-т Юрия Гагарина, д. 18",
		metroStationRu: "Парк Победы",
		metroLineColor: "#3b82f6",
		phone: "+7 (812) 600-40-52",
		workHoursRu: "Пн-Сб: 08:30 – 20:30, Вс: 09:00 – 18:00",
		parkingInfoRu: "Собственный паркинг на 12 машиномест",
		imageUrl: "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&w=400&q=80",
	},
];

export const SAMPLE_BOOKING_DOCTORS: BookingDoctor[] = [
	{
		id: "doc-smirnov",
		fullName: "Д-р Смирнов Алексей Петрович",
		specialtyRu: "Главный врач, стоматолог терапевт-эндодонтист",
		specialtyCategory: "therapy",
		avatarUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=200&q=80",
		experienceYears: 16,
		rating: 4.98,
		reviewsCount: 214,
		nextSlotTextRu: "Сегодня, 16:30",
		branchIds: ["branch-central", "branch-petrograd"],
		priceFromRub: 3500,
		educationRu: "СПбГМУ им. акад. И.П. Павлова, постдипломная эндодонтия Carl Zeiss",
	},
	{
		id: "doc-barabash",
		fullName: "Д-р Барабаш Сергей Владимирович",
		specialtyRu: "Ведущий хирург-имплантолог, ЧЛХ",
		specialtyCategory: "surgery",
		avatarUrl: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=200&q=80",
		experienceYears: 18,
		rating: 4.96,
		reviewsCount: 189,
		nextSlotTextRu: "Завтра, 11:00",
		branchIds: ["branch-central", "branch-moscow"],
		priceFromRub: 4500,
		educationRu: "ВМедА им. С.М. Кирова, стажировка Straumann / Osstem AIC Seoul",
	},
	{
		id: "doc-mironova",
		fullName: "Д-р Миронова Елена Сергеевна",
		specialtyRu: "Стоматолог-ортопед, гнатолог (E.max, виниры)",
		specialtyCategory: "orthopedics",
		avatarUrl: "https://images.unsplash.com/photo-1594824813593-36bb33979853?auto=format&fit=crop&w=200&q=80",
		experienceYears: 12,
		rating: 4.95,
		reviewsCount: 134,
		nextSlotTextRu: "Завтра, 14:30",
		branchIds: ["branch-central", "branch-petrograd"],
		priceFromRub: 4000,
		educationRu: "СПбГУ, член Европейской ассоциации эстетической стоматологии",
	},
	{
		id: "doc-kovaleva",
		fullName: "Д-р Ковалева Анна Дмитриевна",
		specialtyRu: "Врач-ортодонт (Элайнеры Spark/FlexiLigner, Damon)",
		specialtyCategory: "orthodontics",
		avatarUrl: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=200&q=80",
		experienceYears: 9,
		rating: 4.94,
		reviewsCount: 98,
		nextSlotTextRu: "Пт, 12:00",
		branchIds: ["branch-petrograd", "branch-moscow"],
		priceFromRub: 3000,
		educationRu: "СЗГМУ им. И.И. Мечникова, сертифицированный эксперт Spark Aligners",
	},
	{
		id: "doc-vasilieva",
		fullName: "Д-р Васильева Ольга Игоревна",
		specialtyRu: "Стоматолог-гигиенист, пародонтолог (AirFlow, Vector)",
		specialtyCategory: "hygiene",
		avatarUrl: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&w=200&q=80",
		experienceYears: 8,
		rating: 4.97,
		reviewsCount: 167,
		nextSlotTextRu: "Сегодня, 18:00",
		branchIds: ["branch-central", "branch-petrograd", "branch-moscow"],
		priceFromRub: 2500,
		educationRu: "СПбГМУ им. акад. И.П. Павлова, мастер-курсы Swiss Dental Academy",
	},
];

export const SAMPLE_BOOKING_SERVICES: BookingService[] = [
	{
		id: "srv-consult-0",
		code804n: "B01.065.001",
		titleRu: "Первичный осмотр и комплексный план лечения с фотопротоколом",
		specialtyCategory: "therapy",
		durationMinutes: 30,
		priceRub: 0,
		isFreeConsultation: true,
		descriptionRu: "Осмотр полости рта, цифровая фотосъемка зубов, составление 3-уровневого финансового плана лечения.",
		badgeRu: "Бесплатно",
	},
	{
		id: "srv-hygiene-airflow",
		code804n: "A16.07.051",
		titleRu: "Комплексная гигиена полости рта AirFlow + ультразвук EMS",
		specialtyCategory: "hygiene",
		durationMinutes: 60,
		priceRub: 6500,
		isFreeConsultation: false,
		descriptionRu: "Удаление зубного камня ультразвуком Piezon, бережная полировка порошком эритритол AirFlow, ремотерапия.",
		badgeRu: "Популярно",
	},
	{
		id: "srv-emergency-pain",
		code804n: "B01.065.002",
		titleRu: "Неотложная помощь при острой зубной боли (Срочный прием)",
		specialtyCategory: "therapy",
		durationMinutes: 45,
		priceRub: 3000,
		isFreeConsultation: false,
		descriptionRu: "Снятие острой боли, анестезия, диагностическая радиовизиография, купирование воспаления пульпы.",
		badgeRu: "Срочно",
	},
	{
		id: "srv-caries-restoration",
		code804n: "A16.07.002",
		titleRu: "Лечение кариеса с анатомической реставрацией Estelite Asteria",
		specialtyCategory: "therapy",
		durationMinutes: 60,
		priceRub: 4800,
		isFreeConsultation: false,
		descriptionRu: "Изоляция коффердамом, микропрепарирование, восстановление анатомии бугров и фиссур нанокомпозитом.",
	},
	{
		id: "srv-implant-consult",
		code804n: "B01.066.001",
		titleRu: "Консультация хирурга-имплантолога с 3D планированием",
		specialtyCategory: "surgery",
		durationMinutes: 45,
		priceRub: 1500,
		isFreeConsultation: false,
		descriptionRu: "Анализ КЛКТ томограммы, подбор имплантационной системы (Osstem/Straumann), расчет хирургического шаблона.",
	},
	{
		id: "srv-ortho-aligners",
		code804n: "B01.063.001",
		titleRu: "Консультация ортодонта (Элайнеры и брекет-системы)",
		specialtyCategory: "orthodontics",
		durationMinutes: 45,
		priceRub: 1500,
		isFreeConsultation: false,
		descriptionRu: "Оценка окклюзии, расчет срока исправления прикуса, 3D виртуальный сетап улыбки.",
	},
];

export const SAMPLE_PORTAL_TREATMENT_PLAN: PortalTreatmentPlan = {
	id: "plan-2026-0891",
	planNumber: "ПЛАН-2026/891",
	titleRu: "Комплексный план санации и ортопедической реабилитации",
	createdDateIso: "2026-08-14",
	curatingDoctorName: "Д-р Смирнов Алексей Петрович",
	totalAmountRub: 84500,
	completedAmountRub: 21300,
	remainingAmountRub: 63200,
	progressPercent: 25,
	teethFdiSummary: ["1.6", "2.4", "4.6", "11-48"],
	stages: [
		{
			id: "stage-1-therapy",
			stageNumber: 1,
			titleRu: "Этап 1: Неотложная терапия и эндодонтия",
			descriptionRu: "Купирование пульпита зуба 1.6, эндодонтическое пломбирование каналов и лечение среднего кариеса 2.4",
			status: "completed",
			teethFdi: ["1.6", "2.4"],
			totalAmountRub: 21300,
			completedAmountRub: 21300,
			remainingAmountRub: 0,
			targetDateRu: "Август 2026",
			procedures: [
				{
					id: "proc-1-1",
					code804n: "A16.07.030.002",
					nameRu: "Инструментальная и медикаментозная обработка 3 каналов (Reciproc Blue)",
					toothFdi: "1.6",
					priceRub: 8500,
					status: "completed",
					doctorName: "Д-р Смирнов А. П.",
				},
				{
					id: "proc-1-2",
					code804n: "A16.07.008",
					nameRu: "Трехмерная обтурация каналов термопластичной гуттаперчей GuttaCore",
					toothFdi: "1.6",
					priceRub: 4800,
					status: "completed",
					doctorName: "Д-р Смирнов А. П.",
				},
				{
					id: "proc-1-3",
					code804n: "A16.07.002.002",
					nameRu: "Эстетическая реставрация зуба 2.4 нанокомпозитом Estelite Asteria",
					toothFdi: "2.4",
					priceRub: 6800,
					status: "completed",
					doctorName: "Д-р Смирнов А. П.",
				},
				{
					id: "proc-1-4",
					code804n: "A16.07.002.001",
					nameRu: "Анестезия инфильтрационная Sol. Ultracaini DS Forte (2 карпулы)",
					toothFdi: "1.6, 2.4",
					priceRub: 1200,
					status: "completed",
					doctorName: "Д-р Смирнов А. П.",
				},
			],
		},
		{
			id: "stage-2-ortho",
			stageNumber: 2,
			titleRu: "Этап 2: Ортопедическое восстановление",
			descriptionRu: "Цифровой интраоральный 3D скан челюстей и фиксация анатомической коронки из диоксида циркония Katana ML",
			status: "in_progress",
			teethFdi: ["1.6"],
			totalAmountRub: 28000,
			completedAmountRub: 0,
			remainingAmountRub: 28000,
			targetDateRu: "Сентябрь 2026",
			procedures: [
				{
					id: "proc-2-1",
					code804n: "A16.07.004.002",
					nameRu: "Оптический 3D-скан челюстей iTero Element",
					toothFdi: "1.6",
					priceRub: 3000,
					status: "in_progress",
					doctorName: "Д-р Миронова Е. С.",
				},
				{
					id: "proc-2-2",
					code804n: "A16.07.004.001",
					nameRu: "Коронка из диоксида циркония Katana Multi-Layer (CAD/CAM)",
					toothFdi: "1.6",
					priceRub: 25000,
					status: "planned",
					doctorName: "Д-р Миронова Е. С.",
				},
			],
		},
		{
			id: "stage-3-hygiene-implant",
			stageNumber: 3,
			titleRu: "Этап 3: Профгигиена и имплантация",
			descriptionRu: "Комплекс гигиены AirFlow и дентальная имплантация в области отсутствующего зуба 4.6 (Osstem TS III)",
			status: "planned",
			teethFdi: ["4.6", "11-48"],
			totalAmountRub: 35200,
			completedAmountRub: 0,
			remainingAmountRub: 35200,
			targetDateRu: "Октябрь 2026",
			procedures: [
				{
					id: "proc-3-1",
					code804n: "A16.07.051",
					nameRu: "Комплексная гигиена полости рта AirFlow + ультразвук EMS",
					toothFdi: "11-48",
					priceRub: 6500,
					status: "planned",
					doctorName: "Д-р Васильева О. И.",
				},
				{
					id: "proc-3-2",
					code804n: "A16.07.054.001",
					nameRu: "Установка дентального имплантата Osstem TS III (Южная Корея)",
					toothFdi: "4.6",
					priceRub: 28700,
					status: "planned",
					doctorName: "Д-р Барабаш С. В.",
				},
			],
		},
	],
};

export const SAMPLE_UPCOMING_VISIT = {
	id: "visit-upcoming-2026-0902",
	patientId: "PAT-2026-0891",
	patientFullName: "Смирнова Екатерина Васильевна",
	dateIso: "2026-09-02",
	timeRu: "14:30",
	doctorId: "doc-smirnov",
	doctorName: "Д-р Смирнов Алексей Петрович",
	doctorSpecialty: "Врач-стоматолог терапевт-ортопед",
	doctorAvatarUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=200&q=80",
	clinicName: "ООО «Стоматологическая клиника ДЕНТЕ»",
	clinicAddress: "г. Санкт-Петербург, Невский пр-т, д. 140, лит. А",
	metroStationRu: "Площадь Восстания / Маяковская",
	metroLineColor: "#ef4444", // Red line 1
	clinicPhone: "+7 (812) 409-32-10",
	cabinetNumber: "104 (Ортопедия / Терапия)",
	procedureTitle: "Примерка и фиксация коронки из диоксида циркония Katana ML на зуб 1.6",
	directionsRu: "Главный вход с Невского проспекта, 2-й этаж, домофон 104. При себе иметь паспорт для оформления.",
	parkingInfoRu: "Бесплатная закрытая парковка во дворе (заезд с ул. Жуковского, въезд под шлагбаум по звонку администратору).",
	preparationInstructionsRu: "Перед приёмом рекомендуется провести стандартную гигиену полости рта щёткой и пастой. Приём пищи разрешён за 1.5–2 часа до визита.",
	cachedAtIso: "2026-09-01T12:00:00.000Z",
};

