/**
 * dentalLabDemoData.ts — Эталонные демонстрационные наряды ЗТЛ (МАНДАТ 8y).
 *
 * 7 канонических клинических и технологических этапов без эмодзи и советских шифров:
 * 1. Слепок / интраоральный скан (STL/PLY 3D scan, A2)
 * 2. Моделирование (IPS e.max Press, VITA 3D-Master 2M2)
 * 3. Фрезеровка / литье (мостовидный протез ZrO2 Prettau, A3)
 * 4. Примерка каркаса (Co-Cr металлокерамика Noritake, A3.5)
 * 5. Нанесение керамики (виниры E.max, VITA 3D-Master 1M1)
 * 6. Контрольная сдача (Ti-Base индивидуальный абатмент ZrO2, A2)
 * 7. Зафиксировано / сдано (E.max Press, A1)
 */

import {
	type DentalLabOrderRecord,
	createDentalLabOrderRecord,
	toIsoDate,
} from "./dentalLabOrderEngine";
import type { DentalLabOrderData } from "./labMath";
import {
	createDentalLabOrder,
	type DentalLabWorkflowOrder,
} from "./dentalLabWorkflowModel";

export function getDemoDentalLabOrderRecords(): DentalLabOrderRecord[] {
	const today = new Date();
	return [
		createDentalLabOrderRecord({
			id: "demo-ztl-1",
			orderNumber: "ЗТЛ-2026-101",
			patientId: "demo-pat-1",
			patientName: "Барабаш С.В.",
			doctorId: "doc-orlov",
			doctorName: "Д-р Орлов А.В. (Ортопед)",
			labName: "CAD/CAM Центр Дентал-Мастер",
			technicianName: "Техник Соколов М.",
			teethFdi: [16],
			constructionType: "crown_zirconia",
			materialRu: "Диоксид циркония Katana HTML (Multi-Layer)",
			vitaShade: "A2",
			translucency: "MT",
			stumpShade: "ND2",
			sentDate: toIsoDate(new Date(Date.now() - 1 * 86400000)),
			deadlineDate: toIsoDate(new Date(Date.now() + 5 * 86400000)),
			status: "sent_to_lab",
			patientPriceKopecks: 2400000,
			ztlCostKopecks: 750000,
			doctorSharePercent: 20,
			clinicalNotes: "Интраоральный цифровой 3D-скан (STL/PLY). Плечевой уступ 0.8 мм, анатомическая редукция.",
			attachedScanUrl: "storage/scans/upper_jaw_scan_16.stl",
		}),
		createDentalLabOrderRecord({
			id: "demo-ztl-2",
			orderNumber: "ЗТЛ-2026-102",
			patientId: "demo-pat-2",
			patientName: "Смирнова Е.А.",
			doctorId: "doc-melnikov",
			doctorName: "Д-р Мельников П.И. (Ортопед)",
			labName: "ArtDent Премиум Лаб",
			technicianName: "Техник Васильев А.",
			teethFdi: [11, 21],
			constructionType: "crown_emax",
			materialRu: "IPS e.max Press (дисиликат лития)",
			vitaShade: "2M2",
			translucency: "HT",
			stumpShade: "ND1",
			sentDate: toIsoDate(new Date(Date.now() - 2 * 86400000)),
			deadlineDate: toIsoDate(new Date(Date.now() + 4 * 86400000)),
			status: "in_progress",
			patientPriceKopecks: 5600000,
			ztlCostKopecks: 1800000,
			doctorSharePercent: 25,
			clinicalNotes: "Фронтальная группа. 3D виртуальное моделирование Wax-up. Эффект мамелонов в режущей трети.",
		}),
		createDentalLabOrderRecord({
			id: "demo-ztl-3",
			orderNumber: "ЗТЛ-2026-103",
			patientId: "demo-pat-3",
			patientName: "Кузнецов И.П.",
			doctorId: "doc-orlov",
			doctorName: "Д-р Орлов А.В. (Ортопед)",
			labName: "ZirconLab Pro",
			technicianName: "Техник Григорьев Д.",
			teethFdi: [45, 46, 47],
			constructionType: "crown_zirconia",
			materialRu: "Мостовидный протез ZrO2 Prettau 3 ед.",
			vitaShade: "A3",
			translucency: "LT",
			stumpShade: "ND3",
			sentDate: toIsoDate(new Date(Date.now() - 3 * 86400000)),
			deadlineDate: toIsoDate(new Date(Date.now() + 3 * 86400000)),
			status: "in_progress",
			patientPriceKopecks: 7200000,
			ztlCostKopecks: 2250000,
			doctorSharePercent: 20,
			clinicalNotes: "5-осевая фрезеровка мостовидного каркаса, сепарация и спекание в печи Zirkonzahn.",
		}),
		createDentalLabOrderRecord({
			id: "demo-ztl-4",
			orderNumber: "ЗТЛ-2026-104",
			patientId: "demo-pat-4",
			patientName: "Волкова Т.Н.",
			doctorId: "doc-melnikov",
			doctorName: "Д-р Мельников П.И. (Ортопед)",
			labName: "Центральная зуботехническая лаборатория",
			technicianName: "Техник Новиков К.",
			teethFdi: [24, 25],
			constructionType: "metal_ceramic",
			materialRu: "Co-Cr металлокерамика Noritake EX-3",
			vitaShade: "A3.5",
			translucency: "MT",
			sentDate: toIsoDate(new Date(Date.now() - 5 * 86400000)),
			deadlineDate: toIsoDate(today),
			scheduledVisitDate: toIsoDate(today),
			status: "try_in",
			patientPriceKopecks: 2800000,
			ztlCostKopecks: 900000,
			doctorSharePercent: 20,
			clinicalNotes: "Примерка металлического каркаса в полости рта. Оценка окклюзии и краевого прилегания.",
		}),
		createDentalLabOrderRecord({
			id: "demo-ztl-5",
			orderNumber: "ЗТЛ-2026-105",
			patientId: "demo-pat-5",
			patientName: "Морозов Д.С.",
			doctorId: "doc-orlov",
			doctorName: "Д-р Орлов А.В. (Ортопед)",
			labName: "ArtDent Премиум Лаб",
			technicianName: "Техник Васильев А.",
			teethFdi: [12, 11, 21, 22],
			constructionType: "crown_emax",
			materialRu: "Виниры IPS e.max Press с послойным нанесением",
			vitaShade: "1M1",
			translucency: "HT",
			stumpShade: "ND1",
			sentDate: toIsoDate(new Date(Date.now() - 6 * 86400000)),
			deadlineDate: toIsoDate(new Date(Date.now() + 2 * 86400000)),
			status: "in_progress",
			patientPriceKopecks: 11200000,
			ztlCostKopecks: 3600000,
			doctorSharePercent: 25,
			clinicalNotes: "Послойная эстетическая облицовка керамикой IPS e.max Ceram, индивидуализация микрорельефа.",
		}),
		createDentalLabOrderRecord({
			id: "demo-ztl-6",
			orderNumber: "ЗТЛ-2026-106",
			patientId: "demo-pat-6",
			patientName: "Павлова О.В.",
			doctorId: "doc-orlov",
			doctorName: "Д-р Орлов А.В. (Ортопед)",
			labName: "CAD/CAM Центр Дентал-Мастер",
			technicianName: "Техник Соколов М.",
			teethFdi: [36],
			constructionType: "crown_zirconia",
			materialRu: "Ti-Base индивидуальный абатмент + коронка ZrO2",
			vitaShade: "A2",
			translucency: "MT",
			stumpShade: "ND2",
			sentDate: toIsoDate(new Date(Date.now() - 7 * 86400000)),
			deadlineDate: toIsoDate(new Date(Date.now() - 1 * 86400000)),
			scheduledVisitDate: toIsoDate(new Date(Date.now() + 1 * 86400000)),
			status: "ready_in_clinic",
			patientPriceKopecks: 3500000,
			ztlCostKopecks: 1100000,
			doctorSharePercent: 20,
			clinicalNotes: "Работа принята курьером, продезинфицирована, находится в боксе ортопедического кабинета №2.",
		}),
		createDentalLabOrderRecord({
			id: "demo-ztl-7",
			orderNumber: "ЗТЛ-2026-107",
			patientId: "demo-pat-7",
			patientName: "Лебедев К.М.",
			doctorId: "doc-melnikov",
			doctorName: "Д-р Мельников П.И. (Ортопед)",
			labName: "ArtDent Премиум Лаб",
			technicianName: "Техник Васильев А.",
			teethFdi: [26],
			constructionType: "crown_emax",
			materialRu: "IPS e.max Press (анатомическая коронка)",
			vitaShade: "A1",
			translucency: "MT",
			stumpShade: "ND2",
			sentDate: toIsoDate(new Date(Date.now() - 14 * 86400000)),
			deadlineDate: toIsoDate(new Date(Date.now() - 7 * 86400000)),
			status: "delivered_to_patient",
			patientPriceKopecks: 2800000,
			ztlCostKopecks: 850000,
			doctorSharePercent: 25,
			clinicalNotes: "Постоянная фиксация на RelyX Ultimate, окклюзия выверена копиркой 12 мкм. Акт подписан.",
		}),
	];
}

export function getDemoDentalLabOrderData(): DentalLabOrderData[] {
	const today = new Date();
	return [
		{
			id: "demo-ztl-1",
			patientId: "demo-pat-1",
			patientName: "Барабаш С.В.",
			doctorId: "doc-orlov",
			doctorName: "Д-р Орлов А.В. (Ортопед)",
			toothFdi: "16",
			selectedTeeth: [16],
			constructionType: "Коронка цирконий",
			material: "Диоксид циркония Katana HTML",
			colorVita: "A2",
			shadeSystem: "classical",
			translucency: "MT",
			status: "sent",
			currentStage: "impression_scan",
			dueDate: toIsoDate(new Date(Date.now() + 5 * 86400000)),
			clinicalNotes: "Интраоральный цифровой 3D-скан (STL/PLY). Плечевой уступ 0.8 мм, анатомическая редукция.",
			priceRub: 24000,
			clinicSharePct: 80,
			doctorSharePct: 20,
			createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
			updatedAt: new Date().toISOString(),
		},
		{
			id: "demo-ztl-2",
			patientId: "demo-pat-2",
			patientName: "Смирнова Е.А.",
			doctorId: "doc-melnikov",
			doctorName: "Д-р Мельников П.И. (Ортопед)",
			toothFdi: "11, 21",
			selectedTeeth: [11, 21],
			constructionType: "Коронка / винир E.max",
			material: "IPS e.max Press (дисиликат лития)",
			colorVita: "2M2",
			shadeSystem: "3d_master",
			translucency: "HT",
			status: "in_progress",
			currentStage: "cad_modeling",
			dueDate: toIsoDate(new Date(Date.now() + 4 * 86400000)),
			clinicalNotes: "Фронтальная группа. 3D виртуальное моделирование Wax-up. Эффект мамелонов в режущей трети.",
			priceRub: 56000,
			clinicSharePct: 75,
			doctorSharePct: 25,
			createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
			updatedAt: new Date().toISOString(),
		},
		{
			id: "demo-ztl-3",
			patientId: "demo-pat-3",
			patientName: "Кузнецов И.П.",
			doctorId: "doc-orlov",
			doctorName: "Д-р Орлов А.В. (Ортопед)",
			toothFdi: "45, 46, 47",
			selectedTeeth: [45, 46, 47],
			constructionType: "Мостовидный протез",
			material: "Мостовидный протез ZrO2 Prettau 3 ед.",
			colorVita: "A3",
			shadeSystem: "classical",
			translucency: "LT",
			status: "in_progress",
			currentStage: "milling_casting",
			dueDate: toIsoDate(new Date(Date.now() + 3 * 86400000)),
			clinicalNotes: "5-осевая фрезеровка мостовидного каркаса, сепарация и спекание в печи Zirkonzahn.",
			priceRub: 72000,
			clinicSharePct: 80,
			doctorSharePct: 20,
			createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
			updatedAt: new Date().toISOString(),
		},
		{
			id: "demo-ztl-4",
			patientId: "demo-pat-4",
			patientName: "Волкова Т.Н.",
			doctorId: "doc-melnikov",
			doctorName: "Д-р Мельников П.И. (Ортопед)",
			toothFdi: "24, 25",
			selectedTeeth: [24, 25],
			constructionType: "Металлокерамика",
			material: "Co-Cr Noritake EX-3",
			colorVita: "A3.5",
			shadeSystem: "classical",
			translucency: "MT",
			status: "fitting",
			currentStage: "framework_fitting",
			dueDate: toIsoDate(today),
			clinicalNotes: "Примерка металлического каркаса в полости рта. Оценка окклюзии и краевого прилегания.",
			priceRub: 28000,
			clinicSharePct: 80,
			doctorSharePct: 20,
			createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
			updatedAt: new Date().toISOString(),
		},
		{
			id: "demo-ztl-5",
			patientId: "demo-pat-5",
			patientName: "Морозов Д.С.",
			doctorId: "doc-orlov",
			doctorName: "Д-р Орлов А.В. (Ортопед)",
			toothFdi: "12, 11, 21, 22",
			selectedTeeth: [12, 11, 21, 22],
			constructionType: "Виниры E.max",
			material: "Виниры IPS e.max Press с послойным нанесением",
			colorVita: "1M1",
			shadeSystem: "3d_master",
			translucency: "HT",
			status: "refitting",
			currentStage: "ceramic_layering",
			dueDate: toIsoDate(new Date(Date.now() + 2 * 86400000)),
			clinicalNotes: "Послойная эстетическая облицовка керамикой IPS e.max Ceram, индивидуализация микрорельефа.",
			priceRub: 112000,
			clinicSharePct: 75,
			doctorSharePct: 25,
			createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
			updatedAt: new Date().toISOString(),
		},
		{
			id: "demo-ztl-6",
			patientId: "demo-pat-6",
			patientName: "Павлова О.В.",
			doctorId: "doc-orlov",
			doctorName: "Д-р Орлов А.В. (Ортопед)",
			toothFdi: "36",
			selectedTeeth: [36],
			constructionType: "Индивидуальный абатмент Ti-Base + коронка",
			material: "Ti-Base индивидуальный абатмент + коронка ZrO2",
			colorVita: "A2",
			shadeSystem: "classical",
			translucency: "MT",
			status: "ready_in_clinic",
			currentStage: "ready_in_clinic",
			dueDate: toIsoDate(new Date(Date.now() - 1 * 86400000)),
			clinicalNotes: "Работа принята курьером, продезинфицирована, находится в боксе ортопедического кабинета №2.",
			priceRub: 35000,
			clinicSharePct: 80,
			doctorSharePct: 20,
			createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
			updatedAt: new Date().toISOString(),
		},
		{
			id: "demo-ztl-7",
			patientId: "demo-pat-7",
			patientName: "Лебедев К.М.",
			doctorId: "doc-melnikov",
			doctorName: "Д-р Мельников П.И. (Ортопед)",
			toothFdi: "26",
			selectedTeeth: [26],
			constructionType: "Коронка E.max",
			material: "IPS e.max Press (анатомическая коронка)",
			colorVita: "A1",
			shadeSystem: "classical",
			translucency: "MT",
			status: "completed",
			currentStage: "patient_fixation",
			dueDate: toIsoDate(new Date(Date.now() - 7 * 86400000)),
			clinicalNotes: "Постоянная фиксация на RelyX Ultimate, окклюзия выверена копиркой 12 мкм. Акт подписан.",
			priceRub: 28000,
			clinicSharePct: 75,
			doctorSharePct: 25,
			createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
			updatedAt: new Date().toISOString(),
		},
	];
}

export function getDemoDentalLabWorkflowOrders(): DentalLabWorkflowOrder[] {
	return [
		createDentalLabOrder({
			patientId: "demo-pat-1",
			patientName: "Барабаш С.В.",
			doctorId: "doc-orlov",
			doctorName: "Д-р Орлов А.В. (Ортопед)",
			labName: "CAD/CAM Центр Дентал-Мастер",
			workTypeId: "crown_zirconia",
			materialName: "Диоксид циркония Katana HTML (Multi-Layer)",
			selectedTeeth: [16],
			shadeCode: "A2",
			translucency: "MT",
			initialStatus: "sent_to_lab",
			techStage: "milling_framework",
			pricePerUnitRub: 24000,
			costPerUnitRub: 7500,
			orderNumber: "ЗТЛ-2026-101",
			clinicalNotes: "Интраоральный цифровой 3D-скан (STL/PLY). Плечевой уступ 0.8 мм, анатомическая редукция.",
		}),
		createDentalLabOrder({
			patientId: "demo-pat-2",
			patientName: "Смирнова Е.А.",
			doctorId: "doc-melnikov",
			doctorName: "Д-р Мельников П.И. (Ортопед)",
			labName: "ArtDent Премиум Лаб",
			workTypeId: "crown_emax",
			materialName: "IPS e.max Press (дисиликат лития)",
			selectedTeeth: [11, 21],
			shadeCode: "2M2",
			translucency: "HT",
			initialStatus: "fitting_scheduled",
			techStage: "ready_in_clinic",
			pricePerUnitRub: 28000,
			costPerUnitRub: 8000,
			orderNumber: "ЗТЛ-2026-102",
			clinicalNotes: "Примерка коронок во рту. Оценка эстетики фронтальной группы, прилегания и окклюзии.",
		}),
		createDentalLabOrder({
			patientId: "demo-pat-3",
			patientName: "Кузнецов М.И.",
			doctorId: "doc-melnikov",
			doctorName: "Д-р Мельников П.И. (Ортопед)",
			labName: "CAD/CAM Центр Дентал-Мастер",
			workTypeId: "crown_zirconia",
			materialName: "Диоксид циркония Prettau (мостовидный протез)",
			selectedTeeth: [14, 15, 16],
			shadeCode: "A3",
			translucency: "MT",
			initialStatus: "draft",
			techStage: "impression_scan",
			pricePerUnitRub: 24000,
			costPerUnitRub: 7500,
			orderNumber: "ЗТЛ-2026-103",
			clinicalNotes: "Скан зубных рядов, препарирование под цельноциркониевый мостовидный протез 14-16.",
		}),
		createDentalLabOrder({
			patientId: "demo-pat-7",
			patientName: "Лебедев К.М.",
			doctorId: "doc-melnikov",
			doctorName: "Д-р Мельников П.И. (Ортопед)",
			labName: "ArtDent Премиум Лаб",
			workTypeId: "crown_emax",
			materialName: "IPS e.max Press (анатомическая коронка)",
			selectedTeeth: [26],
			shadeCode: "A1",
			translucency: "MT",
			initialStatus: "installed_completed",
			techStage: "patient_fixation",
			pricePerUnitRub: 28000,
			costPerUnitRub: 8000,
			orderNumber: "ЗТЛ-2026-107",
			clinicalNotes: "Постоянная фиксация на RelyX Ultimate, окклюзия выверена копиркой 12 мкм. Акт подписан.",
		}),
	];
}
