/**
 * @dental/shared/hardware - Layer 1: Dental Hardware Presets across all 5 Equipment Families.
 *
 * Compliance: THE HAMMER, Mandates 2 (Zero Mocks), 8e (Doctor Autonomy), 8s (Anti-bloat), 8n (Solo Doctor Sovereignty).
 */

import type { DentalHardwareFamily, DentalHardwarePreset, DentalHardwareVendor } from "./types.js";
export { detectHardwareVendorFromPath } from "./vendorDetector.js";

/**
 * Multi-Vendor Hardware Presets covering all 5 families (RVG, CBCT, 3D Scanners, MFPs, Photo Protocol).
 */
export const DENTAL_HARDWARE_PRESETS: readonly DentalHardwarePreset[] = [
	// -------------------------------------------------------------------------
	// Family A: RVG (Радиовизиографы и ПО)
	// -------------------------------------------------------------------------
	{
		id: "preset-vatech-ezdent",
		vendor: "vatech",
		family: "rvg",
		name: "Vatech (EzDent-i / EasyDent / EzSensor)",
		description: "Top-1 интраоральный радиовизиограф в РФ (EzSensor Classic HD, Soft, Wave)",
		defaultPaths: [
			"C:\\EzDent-i\\Capture",
			"C:\\EzDent-i\\Data",
			"C:\\EzDent-i\\Link",
			"C:\\Program Files (x86)\\Vatech\\EasyDent4",
			"C:\\Vatech\\Data",
			"C:\\EasyDent\\Capture",
		],
		protocol: "watch_folder",
		filePatterns: ["vatech", "ezdent", "easydent", "ezsensor", "vth", "ezd"],
		exchangeFileName: "Link.ini",
		defaultModality: "IO",
		cliTemplate: '"{exePath}" -c {patientId}',
	},
	{
		id: "preset-sirona-sidexis",
		vendor: "sirona",
		family: "rvg",
		name: "Dentsply Sirona (Sidexis 4 / Sidexis XG / XIOS)",
		description: "Стандарт SLIDA (Sidexis Link Interface for Dental Applications) и датчики XIOS XG",
		defaultPaths: [
			"C:\\Sidexis",
			"C:\\Program Files\\Sirona\\Sidexis4",
			"C:\\Program Files (x86)\\Sirona Dental Systems\\Sidexis",
			"C:\\PDATA",
			"C:\\Sirona\\Data",
		],
		protocol: "slida",
		filePatterns: ["sidexis", "sirona", "pdata", "slida", "sdx", "si", "xios"],
		exchangeFileName: "sidexis.ini",
		defaultModality: "IO",
		cliTemplate: '"{exePath}" /P:{patientId} /N:"{lastName}^{firstName}" /DOB:{birthDate}',
	},
	{
		id: "preset-planmeca-romexis",
		vendor: "planmeca",
		family: "rvg",
		name: "Planmeca (Romexis / ProSensor HD)",
		description: "Planmeca Romexis 2D Imaging и ProSensor HD датчики",
		defaultPaths: [
			"C:\\Planmeca\\Romexis",
			"C:\\Program Files\\Planmeca\\Romexis",
			"C:\\Planmeca\\Data",
			"C:\\Dimaxis",
		],
		protocol: "cli_bridge",
		filePatterns: ["planmeca", "romexis", "prosensor", "promax", "dimaxis"],
		exchangeFileName: "RomexisLink.xml",
		defaultModality: "IO",
		cliTemplate: '"{exePath}" -p {patientId} -l "{lastName}" -f "{firstName}" -b {birthDateRaw}',
	},
	{
		id: "preset-carestream-trophy",
		vendor: "carestream",
		family: "rvg",
		name: "Carestream Dental / Kodak / Trophy (CS Imaging / RVG 5200/6200)",
		description: "Интраоральные визиографы RVG 5100/5200/6200 и ПО CS Imaging v7/v8",
		defaultPaths: [
			"C:\\Trophy\\Data",
			"C:\\Trophy",
			"C:\\Program Files (x86)\\Carestream\\CSImaging\\Data",
			"C:\\Program Files (x86)\\Trophy\\Data",
			"C:\\Carestream\\Data",
			"C:\\Kodak\\Data",
		],
		protocol: "watch_folder",
		filePatterns: ["trophy", "carestream", "csimaging", "kodak", "rvg", "rvg5200", "rvg6200"],
		exchangeFileName: "cslink.ini",
		defaultModality: "IO",
		cliTemplate: '"{exePath}" /P:{patientId} /LN:"{lastName}" /FN:"{firstName}" /DOB:{birthDate}',
	},
	{
		id: "preset-kavo-gendex",
		vendor: "kavo",
		family: "rvg",
		name: "KaVo / Gendex / Instrumentarium (VixWin Platinum / GXS-700 / CliniView)",
		description: "Визиографы GXS-700, ПО VixWin Platinum, CliniView, фосфорные пластины Digora",
		defaultPaths: [
			"C:\\VixWin",
			"C:\\Gendex",
			"C:\\CliniView",
			"C:\\Program Files (x86)\\KaVo\\CliniView",
			"C:\\Digora",
			"C:\\KaVo\\Data",
		],
		protocol: "watch_folder",
		filePatterns: ["kavo", "gendex", "vixwin", "cliniview", "digora", "instrumentarium", "soredex"],
		exchangeFileName: "vixwin.ini",
		defaultModality: "IO",
		cliTemplate: '"{exePath}" /P:{patientId} /N:"{lastName},{firstName}"',
	},
	{
		id: "preset-woodpecker-isensor",
		vendor: "woodpecker",
		family: "rvg",
		name: "Woodpecker (i-Sensor H1 / H2)",
		description: "Популярный надежный радиовизиограф Woodpecker i-Sensor H1 и H2 с ультратонким сенсором 4.4 мм",
		defaultPaths: [
			"C:\\Woodpecker\\iSensor",
			"C:\\Program Files\\Woodpecker\\i-Sensor",
			"C:\\i-Sensor\\Data",
			"C:\\Woodpecker\\Images",
		],
		protocol: "watch_folder",
		filePatterns: ["woodpecker", "isensor", "i-sensor"],
		exchangeFileName: "isensor_bridge.ini",
		defaultModality: "IO",
		cliTemplate: '"{exePath}" /patient:{patientId} /name:"{lastName}"',
	},
	{
		id: "preset-eighteeth-nanopix",
		vendor: "eighteeth",
		family: "rvg",
		name: "Eighteeth (NanoPix 1 / NanoPix 2)",
		description: "Интраоральный радиовизиограф Eighteeth NanoPix 1/2 с разрешением 20 пар линий/мм",
		defaultPaths: [
			"C:\\Eighteeth\\NanoPix",
			"C:\\Program Files\\Eighteeth\\NanoPix",
			"C:\\Program Files (x86)\\Eighteeth",
			"C:\\NanoPix\\Images",
		],
		protocol: "watch_folder",
		filePatterns: ["eighteeth", "nanopix"],
		exchangeFileName: "nanopix_link.ini",
		defaultModality: "IO",
		cliTemplate: '"{exePath}" -pid {patientId} -pname "{lastName} {firstName}"',
	},
	{
		id: "preset-owandy-quickvision",
		vendor: "owandy",
		family: "rvg",
		name: "Owandy (QuickVision / Owandy-One)",
		description: "Французские визиографы Owandy-One и ПО QuickVision для 2D визуализации",
		defaultPaths: [
			"C:\\Owandy\\QuickVision",
			"C:\\Program Files\\Owandy\\QuickVision",
			"C:\\Program Files (x86)\\Owandy",
			"C:\\QuickVision\\Images",
		],
		protocol: "cli_bridge",
		filePatterns: ["owandy", "quickvision", "owandy-one"],
		exchangeFileName: "quickvision.ini",
		defaultModality: "IO",
		cliTemplate: '"{exePath}" -p {patientId} -n "{lastName}"',
	},
	{
		id: "preset-xpect-vision",
		vendor: "xpect_vision",
		family: "rvg",
		name: "Xpect Vision (XVSensor / Mammo CdTe)",
		description: "Квантовый радиовизиограф прямого подсчёта фотонов на теллуриде кадмия (CdTe, 35 мкм питч)",
		defaultPaths: [
			"C:\\Program Files (x86)\\XVSensor\\XVSensor\\Images",
			"C:\\Program Files (x86)\\XVSensor\\Images",
			"C:\\XVSensor\\Images",
			"C:\\XVSensor",
		],
		protocol: "watch_folder",
		filePatterns: ["xvsensor", "xpect", "mammo", "zraw"],
		exchangeFileName: "xvsensor_export.ini",
		defaultModality: "IO",
		cliTemplate: '"{exePath}" /pid:{patientId} /tooth:{toothCode}',
	},
	{
		id: "preset-handy-dentist",
		vendor: "handy",
		family: "rvg",
		name: "Handy (HDR-500 / HDR-600 / HandyDentist)",
		description: "Доступный цифровой визиограф Handy HDR-500/600 и ПО HandyDentist",
		defaultPaths: [
			"C:\\HandyDentist\\Images",
			"C:\\Program Files\\HandyDentist",
			"C:\\Handy\\Capture",
			"C:\\Program Files (x86)\\HandyDentist",
		],
		protocol: "watch_folder",
		filePatterns: ["handy", "handydentist", "hdr-500", "hdr-600"],
		exchangeFileName: "handy_link.ini",
		defaultModality: "IO",
		cliTemplate: '"{exePath}" /ID:{patientId} /Name:"{lastName} {firstName}"',
	},
	{
		id: "preset-trident-iview",
		vendor: "trident",
		family: "rvg",
		name: "Trident (I-View / I-View Gold / Deep View)",
		description: "Итальянский радиовизиограф Trident I-View Gold и программный пакет Deep View",
		defaultPaths: [
			"C:\\Trident\\I-View",
			"C:\\DeepView\\Data",
			"C:\\Program Files\\Trident\\DeepView",
			"C:\\Trident\\Data",
		],
		protocol: "watch_folder",
		filePatterns: ["trident", "iview", "deepview"],
		exchangeFileName: "trident_link.ini",
		defaultModality: "IO",
		cliTemplate: '"{exePath}" -patid {patientId} -patname "{lastName}"',
	},

	// -------------------------------------------------------------------------
	// Family B: CBCT 3D & OPG (Томографы КЛКТ 3D и ОПТГ)
	// -------------------------------------------------------------------------
	{
		id: "preset-vatech-green-pax",
		vendor: "vatech",
		family: "cbct_opg",
		name: "Vatech (PaX-i3D / Green 16 / Ez3D-i)",
		description: "Конусно-лучевые томографы КЛКТ Vatech Green 16, PaX-i3D Smart Plus и ПО Ez3D-i",
		defaultPaths: [
			"C:\\Ez3D-i\\Data",
			"C:\\Vatech\\PaX-i3D",
			"C:\\Ez3D-i\\Capture",
			"C:\\Vatech\\Green16",
			"C:\\Vatech\\PaX",
		],
		protocol: "watch_folder",
		filePatterns: ["green16", "pax-i", "ez3d", "vatech_3d", "pax-i3d", "pax"],
		exchangeFileName: "Ez3DLink.ini",
		defaultModality: "CT",
		cliTemplate: '"{exePath}" -p {patientId} -3d',
	},
	{
		id: "preset-kavo-op3d",
		vendor: "kavo",
		family: "cbct_opg",
		name: "KaVo OP 3D / OP 3D Pro / OnDemand3D",
		description: "КЛКТ томографы KaVo OP 3D, OP300 и рабочая станция OnDemand3D App",
		defaultPaths: [
			"C:\\KaVo\\OP3D",
			"C:\\OnDemand3DApp",
			"C:\\Program Files\\CyberMed\\OnDemand3D",
			"C:\\KaVo\\OP300",
		],
		protocol: "cli_bridge",
		filePatterns: ["op3d", "ondemand3d", "kavo3d", "op300"],
		exchangeFileName: "kavo_3d_link.ini",
		defaultModality: "CT",
		cliTemplate: '"{exePath}" -patientID {patientId} -patientName "{lastName} {firstName}"',
	},
	{
		id: "preset-sirona-orthophos-galileos",
		vendor: "sirona",
		family: "cbct_opg",
		name: "Dentsply Sirona (Orthophos SL / Galileos 3D)",
		description: "Томографы Orthophos SL 3D, Orthophos XG 3D и Galileos Comfort Plus",
		defaultPaths: [
			"C:\\Sidexis\\Galileos",
			"C:\\Sirona\\Orthophos",
			"C:\\PDATA\\3D",
			"C:\\Program Files\\Sirona\\Galileos",
		],
		protocol: "slida",
		filePatterns: ["orthophos", "galileos", "sirona3d", "galileos3d"],
		exchangeFileName: "sidexis.ini",
		defaultModality: "CT",
		cliTemplate: '"{exePath}" /P:{patientId} /N:"{lastName}^{firstName}" /CT',
	},
	{
		id: "preset-planmeca-promax-3d",
		vendor: "planmeca",
		family: "cbct_opg",
		name: "Planmeca (ProMax 3D / Romexis 3D)",
		description: "Томографы Planmeca ProMax 3D Classic / Mid / Max и Romexis 3D Imaging",
		defaultPaths: [
			"C:\\Planmeca\\Romexis3D",
			"C:\\Planmeca\\ProMax",
			"C:\\Romexis\\3D",
			"C:\\Planmeca\\ProMax3D",
		],
		protocol: "cli_bridge",
		filePatterns: ["promax", "promax3d", "romexis3d"],
		exchangeFileName: "RomexisLink.xml",
		defaultModality: "CT",
		cliTemplate: '"{exePath}" -p {patientId} -l "{lastName}" -f "{firstName}" -3d',
	},
	{
		id: "preset-carestream-cs9600",
		vendor: "carestream",
		family: "cbct_opg",
		name: "Carestream Dental (CS 8100 3D / CS 9600)",
		description: "Томографы Carestream CS 8100 3D, CS 8200 3D, флагман CS 9600 и CS 3D Imaging",
		defaultPaths: [
			"C:\\Carestream\\CS9600",
			"C:\\Carestream\\CS8100_3D",
			"C:\\CSImaging\\3D",
			"C:\\Carestream\\Data\\3D",
		],
		protocol: "watch_folder",
		filePatterns: ["cs9600", "cs8100", "cs3d", "cs8200"],
		exchangeFileName: "cslink3d.ini",
		defaultModality: "CT",
		cliTemplate: '"{exePath}" /P:{patientId} /3D',
	},
	{
		id: "preset-newtom-nnt",
		vendor: "newtom",
		family: "cbct_opg",
		name: "NewTom / MyRay (NNT / iRYS)",
		description: "Итальянские экспертные томографы NewTom VGi evo, GiANO HR, MyRay Hyperion X9 и ПО NNT/iRYS",
		defaultPaths: [
			"C:\\NNT\\Data",
			"C:\\Program Files\\NNT",
			"C:\\iRYS\\Data",
			"C:\\MyRay\\Data",
			"C:\\Program Files\\Cefla\\iRYS",
		],
		protocol: "cli_bridge",
		filePatterns: ["newtom", "nnt", "myray", "irys", "giano"],
		exchangeFileName: "nnt_bridge.ini",
		defaultModality: "CT",
		cliTemplate: '"{exePath}" -id {patientId} -name "{lastName}^{firstName}"',
	},
	{
		id: "preset-morita-idixel",
		vendor: "morita",
		family: "cbct_opg",
		name: "J. Morita (i-Dixel / Veraviewepocs 3D / Veraview X800)",
		description: "Японские премиум томографы Morita Veraview X800, Veraviewepocs 3D R100 и ПО i-Dixel",
		defaultPaths: [
			"C:\\i-Dixel\\Data",
			"C:\\Morita\\iDixel",
			"C:\\Program Files\\Morita\\iDixel",
			"C:\\Morita\\Data",
		],
		protocol: "cli_bridge",
		filePatterns: ["morita", "idixel", "i-dixel", "veraview", "x800"],
		exchangeFileName: "idixel_link.ini",
		defaultModality: "CT",
		cliTemplate: '"{exePath}" /ID:{patientId} /N:"{lastName}"',
	},
	{
		id: "preset-pointnix-realscan",
		vendor: "pointnix",
		family: "cbct_opg",
		name: "PointNix (Point 3D Combi / RealScan)",
		description: "Корейские томографы PointNix Point 3D Combi 500 и диагностический софт RealScan",
		defaultPaths: [
			"C:\\PointNix\\RealScan",
			"C:\\PointNix\\Data",
			"C:\\Point3D",
			"C:\\Program Files\\PointNix",
		],
		protocol: "watch_folder",
		filePatterns: ["pointnix", "point3d", "realscan"],
		exchangeFileName: "pointnix.ini",
		defaultModality: "CT",
		cliTemplate: '"{exePath}" -p {patientId} -n "{lastName}"',
	},
	{
		id: "preset-genoray-papaya",
		vendor: "genoray",
		family: "cbct_opg",
		name: "Genoray (Papaya 3D / Triana / The Smile Designer)",
		description: "Томографы Genoray Papaya 3D Plus, панорамные аппараты и просмотрщик Triana",
		defaultPaths: [
			"C:\\Genoray\\Papaya",
			"C:\\TheSmileDesigner",
			"C:\\Triana\\Data",
			"C:\\Program Files\\Genoray",
		],
		protocol: "cli_bridge",
		filePatterns: ["genoray", "papaya", "triana", "smiledesigner"],
		exchangeFileName: "genoray.ini",
		defaultModality: "CT",
		cliTemplate: '"{exePath}" /P:{patientId} /N:"{lastName}"',
	},

	// -------------------------------------------------------------------------
	// Family C: 3D Intraoral Scanners (3D Интраоральные сканеры)
	// -------------------------------------------------------------------------
	{
		id: "preset-medit-link",
		vendor: "medit",
		family: "scanner_3d",
		name: "Medit (Medit Link / i500 / i700 / i900)",
		description: "Интраоральные 3D-сканеры Medit i500, i700 Wireless, i900 и интеграционный протокол Medit Link",
		defaultPaths: [
			"C:\\Medit\\Medit Link",
			"C:\\Medit Link\\Data",
			"C:\\Program Files\\Medit\\Medit Link",
			"C:\\Medit\\Scans",
		],
		protocol: "cli_bridge",
		filePatterns: ["medit", "meditlink", "i500", "i700", "i900"],
		exchangeFileName: "medit_case.json",
		defaultModality: "3D_SCAN",
		cliTemplate: "meditlink://open?patientId={patientId}",
	},
	{
		id: "preset-3shape-trios",
		vendor: "threeshape",
		family: "scanner_3d",
		name: "3Shape (TRIOS 3 / 4 / 5 / Dental Desktop)",
		description: "Золотой стандарт ортопедического сканирования 3Shape TRIOS и ПО Dental Desktop",
		defaultPaths: [
			"C:\\3Shape\\DentalDesktop",
			"C:\\Program Files\\3Shape\\Dental Desktop\\Data",
			"C:\\TRIOS\\Scans",
			"C:\\3Shape\\Scans",
		],
		protocol: "cli_bridge",
		filePatterns: ["3shape", "threeshape", "trios", "dentaldesktop"],
		exchangeFileName: "3shape_order.xml",
		defaultModality: "3D_SCAN",
		cliTemplate: "3shape://open?patientId={patientId}",
	},
	{
		id: "preset-shining3d-aoralscan",
		vendor: "shining3d",
		family: "scanner_3d",
		name: "Shining 3D (Aoralscan 2 / Aoralscan 3 / 3 Wireless)",
		description: "Высокоскоростной сканер Shining 3D Aoralscan 3 для ортопедии и имплантологии",
		defaultPaths: [
			"C:\\Shining3D\\Aoralscan",
			"C:\\Program Files\\Shining3D\\Dental\\Data",
			"C:\\Aoralscan\\Export",
			"C:\\Shining3D\\Data",
		],
		protocol: "watch_folder",
		filePatterns: ["shining3d", "shining", "aoralscan"],
		exchangeFileName: "shining_order.json",
		defaultModality: "3D_SCAN",
		cliTemplate: '"{exePath}" --patient-id {patientId} --name "{lastName} {firstName}"',
	},
	{
		id: "preset-panda-scanner",
		vendor: "panda",
		family: "scanner_3d",
		name: "Panda Scanner (Panda P2 / Panda P3 / BAMBOO)",
		description: "Компактный легкий сканер Panda Scanner P2/P3 и софт BAMBOO",
		defaultPaths: [
			"C:\\PandaScanner\\Data",
			"C:\\Program Files\\Panda\\BAMBOO",
			"C:\\Panda\\Scans",
			"C:\\BAMBOO\\Export",
		],
		protocol: "watch_folder",
		filePatterns: ["panda", "pandascan", "bamboo"],
		exchangeFileName: "panda_project.json",
		defaultModality: "3D_SCAN",
		cliTemplate: '"{exePath}" -pid {patientId}',
	},
	{
		id: "preset-alliedstar-as",
		vendor: "alliedstar",
		family: "scanner_3d",
		name: "Alliedstar (AS 100 / AS 200 Wireless)",
		description: "Интраоральный 3D-сканер нового поколения Alliedstar AS 100/200",
		defaultPaths: [
			"C:\\Alliedstar\\Scans",
			"C:\\Program Files\\Alliedstar",
			"C:\\AS100\\Export",
			"C:\\Alliedstar\\Data",
		],
		protocol: "watch_folder",
		filePatterns: ["alliedstar", "as100", "as200"],
		exchangeFileName: "alliedstar_order.json",
		defaultModality: "3D_SCAN",
		cliTemplate: '"{exePath}" /patient:{patientId}',
	},
	{
		id: "preset-runyes-3ds",
		vendor: "runyes",
		family: "scanner_3d",
		name: "Runyes (Runyes 3DS / QuickScan)",
		description: "Интраоральный 3D-сканер Runyes 3DS (M3) и экспорт моделей PLY/STL/OBJ",
		defaultPaths: [
			"C:\\Runyes\\3DS",
			"C:\\Runyes\\Scans",
			"C:\\Program Files\\Runyes\\3DS",
			"C:\\Program Files (x86)\\Runyes",
			"C:\\Runyes\\Data",
			"C:\\Runyes",
		],
		protocol: "watch_folder",
		filePatterns: ["runyes", "3ds", "quickscan", "ply", "stl"],
		exchangeFileName: "runyes_project.json",
		defaultModality: "3D_SCAN",
		cliTemplate: '"{exePath}" -patient {patientId}',
	},
	{
		id: "preset-carestream-cs3700",
		vendor: "carestream",
		family: "scanner_3d",
		name: "Carestream Dental (CS 3600 / CS 3700 / CS 3800 Wireless)",
		description: "Интраоральные 3D-сканеры Carestream CS 3600, CS 3700 и беспроводной CS 3800",
		defaultPaths: [
			"C:\\Carestream\\CS3600\\Data",
			"C:\\Carestream\\CS3700\\Data",
			"C:\\CS3800\\Scans",
			"C:\\Carestream\\ScannerData",
		],
		protocol: "watch_folder",
		filePatterns: ["cs3600", "cs3700", "cs3800"],
		exchangeFileName: "cs_scanner_case.xml",
		defaultModality: "3D_SCAN",
		cliTemplate: '"{exePath}" /P:{patientId} /SCAN3D',
	},

	// -------------------------------------------------------------------------
	// Family D: MFPs & Document Scanners (МФУ и документные сканеры)
	// -------------------------------------------------------------------------
	{
		id: "preset-kyocera-taskalfa",
		vendor: "kyocera",
		family: "document_scanner",
		name: "Kyocera (TASKalfa / ECOSYS SMB/FTP)",
		description: "Сетевые МФУ Kyocera ECOSYS M2040dn, TASKalfa со сканированием в сетевую папку SMB/FTP",
		defaultPaths: [
			"C:\\Kyocera\\Scan",
			"C:\\Scans\\Kyocera",
			"C:\\SMB\\KyoceraScan",
			"C:\\Scan\\Kyocera",
		],
		protocol: "watch_folder",
		filePatterns: ["kyocera", "taskalfa", "ecosys"],
		exchangeFileName: "kyocera_config.ini",
		defaultModality: "DOC",
		cliTemplate: '"{exePath}" /scan /dest:"{outputDir}"',
	},
	{
		id: "preset-hp-scanjet",
		vendor: "hp",
		family: "document_scanner",
		name: "HP (LaserJet MFP / ScanJet Pro)",
		description: "МФУ HP LaserJet Enterprise и поточные документ-сканеры ScanJet Pro",
		defaultPaths: [
			"C:\\HP\\Scan",
			"C:\\Scans\\HP",
			"C:\\ScanJet\\Data",
			"C:\\Scan\\HP",
		],
		protocol: "watch_folder",
		filePatterns: ["scanjet", "laserjet", "hp_scan"],
		exchangeFileName: "hp_scan.ini",
		defaultModality: "DOC",
		cliTemplate: '"{exePath}" /scan /output:"{outputDir}"',
	},
	{
		id: "preset-canon-imagerunner",
		vendor: "canon_scanner",
		family: "document_scanner",
		name: "Canon (imageRUNNER / CanoScan / imageFORMULA)",
		description: "Офисные МФУ Canon imageRUNNER ADVANCE и документные сканеры imageFORMULA",
		defaultPaths: [
			"C:\\Canon\\Scan",
			"C:\\Scans\\Canon",
			"C:\\imageRUNNER\\Data",
			"C:\\Scan\\Canon",
		],
		protocol: "watch_folder",
		filePatterns: ["canoscan", "imagerunner", "imageformula"],
		exchangeFileName: "canon_scan.ini",
		defaultModality: "DOC",
		cliTemplate: '"{exePath}" /scan /save:"{outputDir}"',
	},
	{
		id: "preset-xerox-workcentre",
		vendor: "xerox",
		family: "document_scanner",
		name: "Xerox (WorkCentre / VersaLink / AltaLink)",
		description: "Сетевые МФУ Xerox VersaLink B405, WorkCentre с прямой отправкой сканов паспортов и согласий",
		defaultPaths: [
			"C:\\Xerox\\Scan",
			"C:\\Scans\\Xerox",
			"C:\\WorkCentre\\Data",
			"C:\\Scan\\Xerox",
		],
		protocol: "watch_folder",
		filePatterns: ["xerox", "workcentre", "versalink", "altalink"],
		exchangeFileName: "xerox_scan.ini",
		defaultModality: "DOC",
		cliTemplate: '"{exePath}" -scan -out "{outputDir}"',
	},
	{
		id: "preset-brother-dcp",
		vendor: "brother",
		family: "document_scanner",
		name: "Brother (DCP / MFC Series / ADS Scanners)",
		description: "МФУ Brother DCP-L2500, MFC-L2700 и потоковые сканеры Brother ADS-2800",
		defaultPaths: [
			"C:\\Brother\\Scan",
			"C:\\Scans\\Brother",
			"C:\\Brother\\ControlCenter",
			"C:\\Scan\\Brother",
		],
		protocol: "watch_folder",
		filePatterns: ["brother", "dcp-", "mfc-", "ads-"],
		exchangeFileName: "brother_scan.ini",
		defaultModality: "DOC",
		cliTemplate: '"{exePath}" /SCAN /DIR:"{outputDir}"',
	},
	{
		id: "preset-pantum-scanner",
		vendor: "pantum",
		family: "document_scanner",
		name: "Pantum (M6500 / M7100 / BM5100 Series)",
		description: "Сетевые МФУ и документ-сканеры Pantum для оцифровки паспортов, полисов, согласий и анализов",
		defaultPaths: [
			"C:\\Pantum\\Scan",
			"C:\\Pantum",
			"C:\\Program Files\\Pantum",
			"C:\\Program Files (x86)\\Pantum",
			"C:\\Scans\\Pantum",
			"C:\\Scan\\Pantum",
		],
		protocol: "watch_folder",
		filePatterns: ["pantum", "ptm", "scan"],
		exchangeFileName: "scan_config.ini",
		defaultModality: "CR",
		cliTemplate: '"{exePath}" /scan /out:"{outputDir}"',
	},
	{
		id: "preset-fujitsu-scansnap",
		vendor: "fujitsu_avision",
		family: "document_scanner",
		name: "Fujitsu / Avision (ScanSnap / fi-Series / Avision FB)",
		description: "Профессиональные скоростные документ-сканеры Fujitsu fi-7160, ScanSnap iX1600 и Avision",
		defaultPaths: [
			"C:\\ScanSnap\\Data",
			"C:\\Fujitsu\\Scans",
			"C:\\Avision\\Data",
			"C:\\Scans\\Fujitsu",
		],
		protocol: "watch_folder",
		filePatterns: ["fujitsu", "scansnap", "avision", "fi-7160", "fi-"],
		exchangeFileName: "scansnap_job.ini",
		defaultModality: "DOC",
		cliTemplate: '"{exePath}" /ScanToFolder:"{outputDir}"',
	},

	// -------------------------------------------------------------------------
	// Family E: Clinical Photo Protocol (Фотопротокол и камеры)
	// -------------------------------------------------------------------------
	{
		id: "preset-canon-eos-photo",
		vendor: "canon_photo",
		family: "photo_protocol",
		name: "Canon (EOS Utility / DCIM Auto-Import)",
		description: "Зеркальные и беззеркальные камеры Canon (EOS R/RP/90D) для дентального фотопротокола",
		defaultPaths: [
			"C:\\EOS_Utility\\Photos",
			"D:\\DCIM\\100CANON",
			"E:\\DCIM\\100CANON",
			"F:\\DCIM\\100CANON",
			"C:\\Photos\\Canon",
		],
		protocol: "watch_folder",
		filePatterns: ["canon_eos", "eos_utility", "dcim", "100canon"],
		exchangeFileName: "canon_tether.ini",
		defaultModality: "PHOTO",
		cliTemplate: '"{exePath}" /download /dest:"{outputDir}"',
	},
	{
		id: "preset-nikon-photo",
		vendor: "nikon_photo",
		family: "photo_protocol",
		name: "Nikon (Camera Control Pro / DCIM Auto-Import)",
		description: "Камеры Nikon (Z5/Z6/D7500) для портретной и макро внутриротовой съемки с кольцевой вспышкой",
		defaultPaths: [
			"C:\\Nikon\\Photos",
			"D:\\DCIM\\100NIKON",
			"E:\\DCIM\\100NIKON",
			"F:\\DCIM\\100NIKON",
			"C:\\Photos\\Nikon",
		],
		protocol: "watch_folder",
		filePatterns: ["nikon", "100nikon", "camera_control"],
		exchangeFileName: "nikon_tether.ini",
		defaultModality: "PHOTO",
		cliTemplate: '"{exePath}" /import /dest:"{outputDir}"',
	},
	{
		id: "preset-sony-alpha-photo",
		vendor: "sony_photo",
		family: "photo_protocol",
		name: "Sony (Imaging Edge Desktop / DCIM Auto-Import)",
		description: "Камеры Sony Alpha (A7 IV, A6700) для протокольной съемки улыбки и окклюзии",
		defaultPaths: [
			"C:\\Sony\\ImagingEdge",
			"D:\\DCIM\\100MSDCF",
			"E:\\DCIM\\100MSDCF",
			"F:\\DCIM\\100MSDCF",
			"C:\\Photos\\Sony",
		],
		protocol: "watch_folder",
		filePatterns: ["sony", "imaging_edge", "100msdcf"],
		exchangeFileName: "sony_tether.ini",
		defaultModality: "PHOTO",
		cliTemplate: '"{exePath}" /import /folder:"{outputDir}"',
	},
];

/**
 * Returns preset configuration by vendor code.
 */
export function getHardwarePresetByVendor(vendor: DentalHardwareVendor): DentalHardwarePreset | undefined {
	return DENTAL_HARDWARE_PRESETS.find((p) => p.vendor === vendor);
}

/**
 * Returns preset configuration by unique ID.
 */
export function getHardwarePresetById(id: string): DentalHardwarePreset | undefined {
	return DENTAL_HARDWARE_PRESETS.find((p) => p.id === id);
}

/**
 * Filters presets by equipment family.
 */
export function getPresetsByFamily(family: DentalHardwareFamily): readonly DentalHardwarePreset[] {
	return DENTAL_HARDWARE_PRESETS.filter((p) => p.family === family);
}
