/**
 * treatmentPlanTherapyNorms.ts — Эталонные нормы расхода стоматологических материалов
 * по Номенклатуре Минздрава РФ № 804н для терапевтических, гигиенических и эндодонтических процедур.
 */

import type { ProcedureMaterialNorm } from "./types";

export const THERAPY_MATERIAL_NORMS: Record<string, readonly ProcedureMaterialNorm[]> = {
	// A06.07.004: КЛКТ 3D диагностика
	"A06.07.004": [
		{
			id: "norm-ct-protective-cover",
			materialName: "Одноразовый чехол для позиционера томографа",
			category: "Расходные материалы",
			quantityPerProcedure: 1,
			unitOfMeasure: "шт.",
			defaultUnitCostRub: 35,
			mandatory: true,
			hideInPatientPresentation: true,
		},
		{
			id: "norm-ct-antiseptic-wipe",
			materialName: "Дезинфицирующая салфетка спиртовая Саникон",
			category: "Дезинфекция",
			quantityPerProcedure: 2,
			unitOfMeasure: "шт.",
			defaultUnitCostRub: 15,
			mandatory: true,
			hideInPatientPresentation: true,
		},
	],

	// A16.07.051: Профессиональная гигиена полости рта (Air-Flow + УЗ)
	"A16.07.051": [
		{
			id: "norm-hyg-powder",
			materialName: "Порошок для Air-Flow глициновый (EMS Plus / Clinpro)",
			category: "Гигиена",
			quantityPerProcedure: 25,
			unitOfMeasure: "г",
			defaultUnitCostRub: 18, // 18 ₽ / грамм = 450 ₽
			mandatory: true,
		},
		{
			id: "norm-hyg-prophy-paste",
			materialName: "Полировочная паста Cleanic / Detartrine",
			category: "Гигиена",
			quantityPerProcedure: 3,
			unitOfMeasure: "г",
			defaultUnitCostRub: 40,
			mandatory: true,
		},
		{
			id: "norm-hyg-brush",
			materialName: "Щетка полировочная циркулярная нейлоновая",
			category: "Расходные материалы",
			quantityPerProcedure: 1,
			unitOfMeasure: "шт.",
			defaultUnitCostRub: 65,
			mandatory: true,
		},
		{
			id: "norm-hyg-varnish",
			materialName: "Фторлак защитный Clinpro White Varnish",
			category: "Профилактика",
			quantityPerProcedure: 0.5,
			unitOfMeasure: "мл",
			defaultUnitCostRub: 320,
			mandatory: true,
		},
		{
			id: "norm-hyg-optoragate",
			materialName: "Роторасширитель мягкий OptraGate (Ivoclar)",
			category: "Расходные материалы",
			quantityPerProcedure: 1,
			unitOfMeasure: "шт.",
			defaultUnitCostRub: 210,
			mandatory: true,
		},
	],

	// A16.07.002.001: Лечение кариеса фотополимером
	"A16.07.002.001": [
		{
			id: "norm-caries-composite",
			materialName: "Нанокомпозит светоотверждаемый (Estelite Asteria / Filtek)",
			category: "Терапия",
			quantityPerProcedure: 0.4,
			unitOfMeasure: "г",
			defaultUnitCostRub: 1250, // 500 ₽ за порцию
			mandatory: true,
		},
		{
			id: "norm-caries-adhesive",
			materialName: "Самопротравливающий адгезив 7-го поколения (Single Bond / Tokuyama EE)",
			category: "Терапия",
			quantityPerProcedure: 0.1,
			unitOfMeasure: "мл",
			defaultUnitCostRub: 1800, // 180 ₽
			mandatory: true,
		},
		{
			id: "norm-caries-etching",
			materialName: "Гель травильный 37% ортофосфорная кислота",
			category: "Терапия",
			quantityPerProcedure: 0.2,
			unitOfMeasure: "мл",
			defaultUnitCostRub: 150,
			mandatory: true,
		},
		{
			id: "norm-caries-matrix",
			materialName: "Секционная контурная матрица + деревянный клин Tor VM",
			category: "Расходные материалы",
			quantityPerProcedure: 1,
			unitOfMeasure: "компл.",
			defaultUnitCostRub: 85,
			mandatory: true,
		},
		{
			id: "norm-caries-anesthesia",
			materialName: "Анестетик артикаиновый 4% с эпинефрином 1:100000 (Убистезин / Септонест)",
			category: "Анестезия",
			quantityPerProcedure: 1,
			unitOfMeasure: "карп.",
			defaultUnitCostRub: 195,
			mandatory: true,
			lotTrackingRequired: true,
		},
		{
			id: "norm-caries-needle",
			materialName: "Игла карпульная 30G евростандарт",
			category: "Расходные материалы",
			quantityPerProcedure: 1,
			unitOfMeasure: "шт.",
			defaultUnitCostRub: 25,
			mandatory: true,
		},
		{
			id: "norm-caries-cofferdam",
			materialName: "Платок латексный коффердама Sanctuary Dental Dam",
			category: "Изоляция",
			quantityPerProcedure: 1,
			unitOfMeasure: "шт.",
			defaultUnitCostRub: 110,
			mandatory: true,
		},
	],

	// ==========================================
	// ЭНДОДОНТИЯ 804Н (ОБРАБОТКА И ОБТУРАЦИЯ 1..4 КАНАЛОВ)
	// ==========================================

	// A16.07.030.001: Инструментальная и медикаментозная обработка корневого канала (1-канальный зуб)
	"A16.07.030.001": [
		{
			id: "norm-prep1-files",
			materialName: "Машинные никель-титановые ротационные файлы WaveOne Gold / ProTaper",
			category: "Эндодонтия",
			quantityPerProcedure: 1,
			unitOfMeasure: "шт.",
			defaultUnitCostRub: 850,
			mandatory: true,
		},
		{
			id: "norm-prep1-hypochlorite",
			materialName: "Раствор натрия гипохлорита 3% парфюмированный для ирригации",
			category: "Дезинфекция",
			quantityPerProcedure: 15,
			unitOfMeasure: "мл",
			defaultUnitCostRub: 6,
			mandatory: true,
		},
		{
			id: "norm-prep1-edta",
			materialName: "Гель ЭДТА 17% для расширения каналов (Endo-Prep)",
			category: "Эндодонтия",
			quantityPerProcedure: 0.5,
			unitOfMeasure: "мл",
			defaultUnitCostRub: 90,
			mandatory: true,
		},
		{
			id: "norm-prep1-paper-points",
			materialName: "Штифты бумажные абсорбирующие стерильные",
			category: "Эндодонтия",
			quantityPerProcedure: 3,
			unitOfMeasure: "шт.",
			defaultUnitCostRub: 15,
			mandatory: true,
		},
		{
			id: "norm-prep1-anesthesia",
			materialName: "Анестетик артикаиновый 4% форте 1:100000",
			category: "Анестезия",
			quantityPerProcedure: 1,
			unitOfMeasure: "карп.",
			defaultUnitCostRub: 195,
			mandatory: true,
			lotTrackingRequired: true,
		},
	],

	// A16.07.030.002: Инструментальная и медикаментозная обработка корневых каналов (2-канальный зуб)
	"A16.07.030.002": [
		{
			id: "norm-prep2-files",
			materialName: "Машинные никель-титановые ротационные файлы WaveOne Gold / ProTaper",
			category: "Эндодонтия",
			quantityPerProcedure: 1,
			unitOfMeasure: "шт.",
			defaultUnitCostRub: 850,
			mandatory: true,
		},
		{
			id: "norm-prep2-hypochlorite",
			materialName: "Раствор натрия гипохлорита 3% парфюмированный для ирригации",
			category: "Дезинфекция",
			quantityPerProcedure: 20,
			unitOfMeasure: "мл",
			defaultUnitCostRub: 6,
			mandatory: true,
		},
		{
			id: "norm-prep2-edta",
			materialName: "Гель ЭДТА 17% для расширения каналов (Endo-Prep)",
			category: "Эндодонтия",
			quantityPerProcedure: 1,
			unitOfMeasure: "мл",
			defaultUnitCostRub: 90,
			mandatory: true,
		},
		{
			id: "norm-prep2-paper-points",
			materialName: "Штифты бумажные абсорбирующие стерильные",
			category: "Эндодонтия",
			quantityPerProcedure: 6,
			unitOfMeasure: "шт.",
			defaultUnitCostRub: 15,
			mandatory: true,
		},
		{
			id: "norm-prep2-anesthesia",
			materialName: "Анестетик артикаиновый 4% форте 1:100000",
			category: "Анестезия",
			quantityPerProcedure: 1,
			unitOfMeasure: "карп.",
			defaultUnitCostRub: 195,
			mandatory: true,
			lotTrackingRequired: true,
		},
	],

	// A16.07.030.003: Инструментальная и медикаментозная обработка корневых каналов (3-канальный зуб)
	"A16.07.030.003": [
		{
			id: "norm-prep3-files",
			materialName: "Машинные никель-титановые ротационные файлы WaveOne Gold / ProTaper",
			category: "Эндодонтия",
			quantityPerProcedure: 1,
			unitOfMeasure: "шт.",
			defaultUnitCostRub: 850,
			mandatory: true,
		},
		{
			id: "norm-prep3-hypochlorite",
			materialName: "Раствор натрия гипохлорита 3% парфюмированный для ирригации",
			category: "Дезинфекция",
			quantityPerProcedure: 25,
			unitOfMeasure: "мл",
			defaultUnitCostRub: 6,
			mandatory: true,
		},
		{
			id: "norm-prep3-edta",
			materialName: "Гель ЭДТА 17% для расширения каналов (Endo-Prep)",
			category: "Эндодонтия",
			quantityPerProcedure: 1.5,
			unitOfMeasure: "мл",
			defaultUnitCostRub: 90,
			mandatory: true,
		},
		{
			id: "norm-prep3-paper-points",
			materialName: "Штифты бумажные абсорбирующие стерильные",
			category: "Эндодонтия",
			quantityPerProcedure: 9,
			unitOfMeasure: "шт.",
			defaultUnitCostRub: 15,
			mandatory: true,
		},
		{
			id: "norm-prep3-anesthesia",
			materialName: "Анестетик артикаиновый 4% форте 1:100000",
			category: "Анестезия",
			quantityPerProcedure: 2,
			unitOfMeasure: "карп.",
			defaultUnitCostRub: 195,
			mandatory: true,
			lotTrackingRequired: true,
		},
	],

	// A16.07.030.004: Инструментальная и медикаментозная обработка корневых каналов (4-канальный зуб)
	"A16.07.030.004": [
		{
			id: "norm-prep4-files",
			materialName: "Машинные никель-титановые ротационные файлы WaveOne Gold / ProTaper",
			category: "Эндодонтия",
			quantityPerProcedure: 2,
			unitOfMeasure: "шт.",
			defaultUnitCostRub: 850,
			mandatory: true,
		},
		{
			id: "norm-prep4-hypochlorite",
			materialName: "Раствор натрия гипохлорита 3% парфюмированный для ирригации",
			category: "Дезинфекция",
			quantityPerProcedure: 30,
			unitOfMeasure: "мл",
			defaultUnitCostRub: 6,
			mandatory: true,
		},
		{
			id: "norm-prep4-edta",
			materialName: "Гель ЭДТА 17% для расширения каналов (Endo-Prep)",
			category: "Эндодонтия",
			quantityPerProcedure: 2.0,
			unitOfMeasure: "мл",
			defaultUnitCostRub: 90,
			mandatory: true,
		},
		{
			id: "norm-prep4-paper-points",
			materialName: "Штифты бумажные абсорбирующие стерильные",
			category: "Эндодонтия",
			quantityPerProcedure: 12,
			unitOfMeasure: "шт.",
			defaultUnitCostRub: 15,
			mandatory: true,
		},
		{
			id: "norm-prep4-anesthesia",
			materialName: "Анестетик артикаиновый 4% форте 1:100000",
			category: "Анестезия",
			quantityPerProcedure: 2,
			unitOfMeasure: "карп.",
			defaultUnitCostRub: 195,
			mandatory: true,
			lotTrackingRequired: true,
		},
	],

	// A16.07.008.001: Пломбирование корневого канала зуба (1 канал) / Пульпотомия временного зуба
	"A16.07.008.001": [
		{
			id: "norm-obt1-gutta",
			materialName: "Гуттаперчевые конусные штифты калиброванные 0.04/0.06",
			category: "Эндодонтия",
			quantityPerProcedure: 1,
			unitOfMeasure: "шт.",
			defaultUnitCostRub: 60,
			mandatory: true,
		},
		{
			id: "norm-obt1-sealer",
			materialName: "Биокерамический силер для 3D-обтурации (TotalFill / AH Plus)",
			category: "Эндодонтия",
			quantityPerProcedure: 0.1,
			unitOfMeasure: "г",
			defaultUnitCostRub: 1400,
			mandatory: true,
		},
		{
			id: "norm-obt1-paper-points",
			materialName: "Штифты бумажные абсорбирующие стерильные",
			category: "Эндодонтия",
			quantityPerProcedure: 2,
			unitOfMeasure: "шт.",
			defaultUnitCostRub: 15,
			mandatory: true,
		},
		{
			id: "norm-pulpotomy-biodentine",
			materialName: "Биоактивный заменитель дентина Septodont Biodentine / ProRoot MTA",
			category: "Детская терапия",
			quantityPerProcedure: 1,
			unitOfMeasure: "порц.",
			defaultUnitCostRub: 1450,
			mandatory: true,
			lotTrackingRequired: true,
		},
	],

	// A16.07.008.002: Пломбирование корневых каналов зуба (2 канала) / Эндодонтическое лечение пульпита
	"A16.07.008.002": [
		{
			id: "norm-endo-files",
			materialName: "Машинные никель-титановые ротационные файлы WaveOne Gold / ProTaper",
			category: "Эндодонтия",
			quantityPerProcedure: 1,
			unitOfMeasure: "шт.",
			defaultUnitCostRub: 850,
			mandatory: true,
		},
		{
			id: "norm-endo-hypochlorite",
			materialName: "Раствор натрия гипохлорита 3% парфюмированный для ирригации",
			category: "Дезинфекция",
			quantityPerProcedure: 25,
			unitOfMeasure: "мл",
			defaultUnitCostRub: 6,
			mandatory: true,
		},
		{
			id: "norm-endo-edta",
			materialName: "Гель ЭДТА 17% для расширения каналов (Endo-Prep)",
			category: "Эндодонтия",
			quantityPerProcedure: 1,
			unitOfMeasure: "мл",
			defaultUnitCostRub: 90,
			mandatory: true,
		},
		{
			id: "norm-endo-gutta",
			materialName: "Гуттаперчевые конусные штифты калиброванные 0.04/0.06",
			category: "Эндодонтия",
			quantityPerProcedure: 2,
			unitOfMeasure: "шт.",
			defaultUnitCostRub: 60,
			mandatory: true,
		},
		{
			id: "norm-endo-sealer",
			materialName: "Биокерамический силер для 3D-обтурации (TotalFill / AH Plus)",
			category: "Эндодонтия",
			quantityPerProcedure: 0.2,
			unitOfMeasure: "г",
			defaultUnitCostRub: 1400,
			mandatory: true,
		},
		{
			id: "norm-endo-anesthesia",
			materialName: "Анестетик артикаиновый 4% форте 1:100000",
			category: "Анестезия",
			quantityPerProcedure: 2,
			unitOfMeasure: "карп.",
			defaultUnitCostRub: 195,
			mandatory: true,
			lotTrackingRequired: true,
		},
		{
			id: "norm-endo-paper-points",
			materialName: "Штифты бумажные абсорбирующие стерильные",
			category: "Эндодонтия",
			quantityPerProcedure: 6,
			unitOfMeasure: "шт.",
			defaultUnitCostRub: 15,
			mandatory: true,
		},
	],

	// A16.07.008.003: Пломбирование корневых каналов зуба (3 канала)
	"A16.07.008.003": [
		{
			id: "norm-obt3-gutta",
			materialName: "Гуттаперчевые конусные штифты калиброванные 0.04/0.06",
			category: "Эндодонтия",
			quantityPerProcedure: 3,
			unitOfMeasure: "шт.",
			defaultUnitCostRub: 60,
			mandatory: true,
		},
		{
			id: "norm-obt3-sealer",
			materialName: "Биокерамический силер для 3D-обтурации (TotalFill / AH Plus)",
			category: "Эндодонтия",
			quantityPerProcedure: 0.3,
			unitOfMeasure: "г",
			defaultUnitCostRub: 1400,
			mandatory: true,
		},
		{
			id: "norm-obt3-paper-points",
			materialName: "Штифты бумажные абсорбирующие стерильные",
			category: "Эндодонтия",
			quantityPerProcedure: 6,
			unitOfMeasure: "шт.",
			defaultUnitCostRub: 15,
			mandatory: true,
		},
	],

	// A16.07.008.004: Пломбирование корневых каналов зуба (4 канала)
	"A16.07.008.004": [
		{
			id: "norm-obt4-gutta",
			materialName: "Гуттаперчевые конусные штифты калиброванные 0.04/0.06",
			category: "Эндодонтия",
			quantityPerProcedure: 4,
			unitOfMeasure: "шт.",
			defaultUnitCostRub: 60,
			mandatory: true,
		},
		{
			id: "norm-obt4-sealer",
			materialName: "Биокерамический силер для 3D-обтурации (TotalFill / AH Plus)",
			category: "Эндодонтия",
			quantityPerProcedure: 0.4,
			unitOfMeasure: "г",
			defaultUnitCostRub: 1400,
			mandatory: true,
		},
		{
			id: "norm-obt4-paper-points",
			materialName: "Штифты бумажные абсорбирующие стерильные",
			category: "Эндодонтия",
			quantityPerProcedure: 8,
			unitOfMeasure: "шт.",
			defaultUnitCostRub: 15,
			mandatory: true,
		},
	],

	// A16.07.091: Временное пломбирование лекарственным препаратом корневого канала (Ca(OH)2)
	"A16.07.091": [
		{
			id: "norm-caoh2-paste",
			materialName: "Лечебная гидроокись кальция UltraCal XS с радиопаком",
			category: "Эндодонтия",
			quantityPerProcedure: 0.5,
			unitOfMeasure: "мл",
			defaultUnitCostRub: 380,
			mandatory: true,
		},
		{
			id: "norm-caoh2-temp-fill",
			materialName: "Временный пломбировочный материал безэвгенольный Cavit / Дентин-паста",
			category: "Терапия",
			quantityPerProcedure: 0.3,
			unitOfMeasure: "г",
			defaultUnitCostRub: 80,
			mandatory: true,
		},
		{
			id: "norm-caoh2-paper-points",
			materialName: "Штифты бумажные абсорбирующие стерильные",
			category: "Эндодонтия",
			quantityPerProcedure: 3,
			unitOfMeasure: "шт.",
			defaultUnitCostRub: 15,
			mandatory: true,
		},
	],

	// A16.07.082: Распломбирование корневого канала зуба
	"A16.07.082": [
		{
			id: "norm-unseal-solvent",
			materialName: "Органический растворитель гуттаперчи D-Solv / Эндосольв",
			category: "Эндодонтия",
			quantityPerProcedure: 0.5,
			unitOfMeasure: "мл",
			defaultUnitCostRub: 220,
			mandatory: true,
		},
		{
			id: "norm-unseal-files",
			materialName: "Машинные ретритмент-файлы для распломбирования ProTaper D1-D3",
			category: "Эндодонтия",
			quantityPerProcedure: 1,
			unitOfMeasure: "шт.",
			defaultUnitCostRub: 920,
			mandatory: true,
		},
		{
			id: "norm-unseal-hypochlorite",
			materialName: "Раствор натрия гипохлорита 3% парфюмированный для ирригации",
			category: "Дезинфекция",
			quantityPerProcedure: 15,
			unitOfMeasure: "мл",
			defaultUnitCostRub: 6,
			mandatory: true,
		},
	],

	// A16.07.009.001: Лечение периодонтита
	"A16.07.009.001": [
		{
			id: "norm-perio-calcium",
			materialName: "Лечебная гидроокись кальция UltraCal XS с радиопаком",
			category: "Эндодонтия",
			quantityPerProcedure: 0.5,
			unitOfMeasure: "мл",
			defaultUnitCostRub: 380,
			mandatory: true,
		},
		{
			id: "norm-perio-chlorhexidine",
			materialName: "Хлоргексидина биглюконат 2% для финишной антисептики",
			category: "Дезинфекция",
			quantityPerProcedure: 15,
			unitOfMeasure: "мл",
			defaultUnitCostRub: 8,
			mandatory: true,
		},
		{
			id: "norm-perio-files",
			materialName: "Файлы ротационные Ni-Ti Reciproc Blue",
			category: "Эндодонтия",
			quantityPerProcedure: 1,
			unitOfMeasure: "шт.",
			defaultUnitCostRub: 890,
			mandatory: true,
		},
		{
			id: "norm-perio-gutta-sealer",
			materialName: "Гуттаперча термопластическая + биокерамика CeraSeal",
			category: "Эндодонтия",
			quantityPerProcedure: 1,
			unitOfMeasure: "компл.",
			defaultUnitCostRub: 550,
			mandatory: true,
		},
	],
};
