/**
 * endoAndOrthoMaterialsData.ts — Реестр эндодонтических и ортодонтических материалов
 * с охватом до 90% рынка РФ/СНГ (ранжирование строго по убыванию популярности).
 *
 * Mandate 8b: строго <= 800 строк
 * Mandate 8e: Doctor Autonomy (1 клик)
 * Mandate 8d: ноль мультяшных эмодзи
 * UTF-8 без BOM
 */

import type { ClinicalMarketMaterialItem } from "./implantAndBoneMaterialsData.js";

// ─────────────────────────────────────────────────────────────────────────────
// 3. ЭНДОДОНТИЯ (Файлы, силеры, ирригаторы, вложения)
// ─────────────────────────────────────────────────────────────────────────────
export const ENDODONTIC_MATERIALS_REGISTRY: readonly ClinicalMarketMaterialItem[] = [
	// Машинные файлы
	{
		id: "endo_protaper_gold",
		domain: "endo_file",
		nameRu: "ProTaper Gold / Next (Dentsply Sirona)",
		brandName: "ProTaper",
		manufacturer: "Dentsply Sirona",
		country: "Швейцария/США",
		marketRank: 1,
		isMarketLeader: true,
		tier: "premium",
		descriptionRu: "Золотой эталон машинной ротации: термообработанный никель-титан Gold с переменной конусностью.",
		clinicalIndicationsRu: "Crown-Down обработка прямых и умеренно искривленных каналов моляров и премоляров.",
		defaultUnit: "упак. (6 шт)",
		approximatePriceRub: 4200,
		requiresLotTracking: false,
		aliases: ["ProTaper Gold", "ProTaper Next", "Протейпер", "Dentsply"],
	},
	{
		id: "endo_soco_sc_pro",
		domain: "endo_file",
		nameRu: "SOCO SC / SC Pro NiTi (SOCO)",
		brandName: "SOCO SC",
		manufacturer: "SOCO Dental",
		country: "Китай",
		marketRank: 2,
		isMarketLeader: false,
		tier: "mainstream",
		descriptionRu: "Чрезвычайно популярная ротационная система с памятью формы, мягкий сплав, устойчивость к циклической усталости.",
		clinicalIndicationsRu: "Массовый терапевтический прием, бережное прохождение сильно изогнутых каналов.",
		defaultUnit: "упак. (6 шт)",
		approximatePriceRub: 1600,
		requiresLotTracking: false,
		aliases: ["SOCO SC", "SOCO SC Pro", "Соко", "СОКО"],
	},
	{
		id: "endo_waveone_gold",
		domain: "endo_file",
		nameRu: "WaveOne Gold (Dentsply Sirona, реципрок)",
		brandName: "WaveOne Gold",
		manufacturer: "Dentsply Sirona",
		country: "Швейцария",
		marketRank: 3,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Реципрокная однофайловая система (Single-File Reciprocating), золото-термообработанный NiTi.",
		clinicalIndicationsRu: "Быстрая и безопасная механическая обработка узких каналов одним основным файлом (Primary 25.07).",
		defaultUnit: "упак. (3 шт)",
		approximatePriceRub: 3400,
		requiresLotTracking: false,
		aliases: ["WaveOne", "WaveOne Gold", "Вейвон", "Вейв Ван"],
	},
	{
		id: "endo_reciproc_blue",
		domain: "endo_file",
		nameRu: "Reciproc Blue (VDW, Германия)",
		brandName: "Reciproc Blue",
		manufacturer: "VDW Dental",
		country: "Германия",
		marketRank: 4,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Инновационный синий термообработанный сплав с колоссальной гибкостью и устойчивостью к перелому в апикальной трети.",
		clinicalIndicationsRu: "Ретритмент, перелечивание каналов, распломбировка гуттаперчи, сложные S-образные изгибы.",
		defaultUnit: "упак. (6 шт)",
		approximatePriceRub: 5200,
		requiresLotTracking: false,
		aliases: ["Reciproc Blue", "Реципрок Блю", "VDW"],
	},
	{
		id: "endo_mtwo",
		domain: "endo_file",
		nameRu: "M-Two / M-Wire (VDW, Германия)",
		brandName: "M-Two",
		manufacturer: "VDW Dental",
		country: "Германия",
		marketRank: 5,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "S-образное поперечное сечение с двумя активными режущими гранями, минимальное радиальное трение.",
		clinicalIndicationsRu: "Быстрое формирование апикального уступа без проталкивания опилок за верхушку.",
		defaultUnit: "упак. (6 шт)",
		approximatePriceRub: 4800,
		requiresLotTracking: false,
		aliases: ["M-Two", "Mtwo", "Эм-Ту"],
	},

	// Силеры
	{
		id: "endo_sealer_ah_plus",
		domain: "endo_sealer",
		nameRu: "AH Plus (Dentsply Sirona, эпоксидный силер)",
		brandName: "AH Plus",
		manufacturer: "Dentsply Sirona",
		country: "Германия",
		marketRank: 1,
		isMarketLeader: true,
		tier: "premium",
		descriptionRu: "Мировой эталон обтурации: термостойкая эпоксидно-аминовая смола с близкой к нулю усадкой и рентгеноконтрастностью.",
		clinicalIndicationsRu: "Постоянное пломбирование каналов методом холодной латеральной конденсации и горячей гуттаперчи.",
		defaultUnit: "тюбик (паста A+B)",
		approximatePriceRub: 7800,
		requiresLotTracking: true,
		aliases: ["AH Plus", "АН Плюс", "АХ Плюс", "Эпоксидный силер"],
	},
	{
		id: "endo_sealer_2seal",
		domain: "endo_sealer",
		nameRu: "2Seal (VDW, эпоксидный герметик)",
		brandName: "2Seal",
		manufacturer: "VDW Dental",
		country: "Германия",
		marketRank: 2,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Эпоксидно-аминовый герметик каналов в автоматическом двойном шприце со смесителями.",
		clinicalIndicationsRu: "Герметичная трехмерная обтурация гуттаперчей без раздражения периапикальных тканей.",
		defaultUnit: "шприц 15 г",
		approximatePriceRub: 6900,
		requiresLotTracking: true,
		aliases: ["2Seal", "Ту Сил", "2 Сил"],
	},
	{
		id: "endo_sealer_bioc",
		domain: "endo_sealer",
		nameRu: "Bio-C Sealer / TotalFill BC Sealer (биокерамика)",
		brandName: "Bio-C Sealer",
		manufacturer: "Angelus / FKG",
		country: "Бразилия / Швейцария",
		marketRank: 3,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Готовый к применению гидрофильный биокерамический силер на основе силикатов кальция, выделяет Ca2+ и расширяется при застывании.",
		clinicalIndicationsRu: "Моноштифтовая обтурация (Single-Cone), влажные каналы, широкие апексы, резорбции корня.",
		defaultUnit: "шприц 2 г",
		approximatePriceRub: 9500,
		requiresLotTracking: true,
		aliases: ["Bio-C Sealer", "TotalFill BC Sealer", "Биокерамический силер"],
	},
	{
		id: "endo_sealer_forfenan",
		domain: "endo_sealer",
		nameRu: "Forfenan / Эндометазон (Septodont)",
		brandName: "Эндометазон / Forfenan",
		manufacturer: "Septodont",
		country: "Франция",
		marketRank: 4,
		isMarketLeader: false,
		tier: "budget",
		descriptionRu: "Классический цинкоксидэвгенольный силер с дексаметазоном для выраженного противовоспалительного эффекта.",
		clinicalIndicationsRu: "Купирование острых периодонтитов, экономичные клинические протоколы.",
		defaultUnit: "фл. 14 г",
		approximatePriceRub: 3200,
		requiresLotTracking: false,
		aliases: ["Эндометазон", "Endomethasone", "Forfenan", "Форфенан"],
	},

	// Ирригация
	{
		id: "endo_irr_naocl",
		domain: "endo_irrigation",
		nameRu: "Гипохлорит натрия 3% / 5.25% (Белодез, ВладМиВа)",
		brandName: "Белодез NaOCl",
		manufacturer: "ВладМиВа",
		country: "Россия",
		marketRank: 1,
		isMarketLeader: true,
		tier: "mainstream",
		descriptionRu: "Основной протеолитический и бактерицидный ирригант: растворяет некротизированную ткань пульпы и смазанный слой.",
		clinicalIndicationsRu: "Обязательное первичное и межэтапное промывание системы корневых каналов.",
		defaultUnit: "фл. 250 мл",
		approximatePriceRub: 450,
		requiresLotTracking: false,
		aliases: ["Белодез", "Гипохлорит", "NaOCl 3%", "NaOCl 5.25%"],
	},
	{
		id: "endo_irr_edta",
		domain: "endo_irrigation",
		nameRu: "ЭДТА 17% гель / жидкость (ЭндоЖи №2, ВладМиВа)",
		brandName: "ЭДТА 17%",
		manufacturer: "ВладМиВа",
		country: "Россия",
		marketRank: 2,
		isMarketLeader: true,
		tier: "mainstream",
		descriptionRu: "Хелатный агент: растворяет неорганический компонент смазанного слоя и декальцинирует дентинные трубочки.",
		clinicalIndicationsRu: "Финишная хелатная обработка каналов перед обтурацией, облегчение прохождения узких кальцифицированных каналов.",
		defaultUnit: "шприц 3 мл",
		approximatePriceRub: 350,
		requiresLotTracking: false,
		aliases: ["ЭДТА", "EDTA 17%", "ЭндоЖи №2", "Хелатный агент"],
	},
	{
		id: "endo_irr_chx",
		domain: "endo_irrigation",
		nameRu: "Хлоргексидина биглюконат 2% эндодонтический",
		brandName: "Хлоргексидин 2%",
		manufacturer: "ВладМиВа / Омега-Дент",
		country: "Россия",
		marketRank: 3,
		isMarketLeader: false,
		tier: "mainstream",
		descriptionRu: "Финальный антисептический лаваж с продленным антибактериальным действием (субстантивность к дентину до 72 ч).",
		clinicalIndicationsRu: "Уничтожение Enterococcus faecalis при повторном эндодонтическом лечении.",
		defaultUnit: "фл. 100 мл",
		approximatePriceRub: 290,
		requiresLotTracking: false,
		aliases: ["Хлоргексидин 2%", "CHX 2%"],
	},

	// Временные вложения (Ca(OH)2)
	{
		id: "endo_dress_calasept",
		domain: "endo_dressing",
		nameRu: "Каласепт (Calasept, Nordiska Dental)",
		brandName: "Calasept",
		manufacturer: "Nordiska Dental",
		country: "Швеция",
		marketRank: 1,
		isMarketLeader: true,
		tier: "premium",
		descriptionRu: "Стерильная чистая паста гидроксида кальция (pH > 12.4) без масляных примесей, легко вымывается из каналов.",
		clinicalIndicationsRu: "Временное антибактериальное пломбирование на 7–14 дней при остром и хроническом периодонтите.",
		defaultUnit: "шприц 1.5 г",
		approximatePriceRub: 1450,
		requiresLotTracking: false,
		aliases: ["Каласепт", "Calasept", "Гидроксид кальция"],
	},
	{
		id: "endo_dress_metapex",
		domain: "endo_dressing",
		nameRu: "Метапекс (Metapex с йодоформом, Meta Biomed)",
		brandName: "Metapex",
		manufacturer: "Meta Biomed",
		country: "Южная Корея",
		marketRank: 2,
		isMarketLeader: false,
		tier: "mainstream",
		descriptionRu: "Паста гидроксида кальция с 40% йодоформом на силиконовом масле, пролонгированное антисептическое и остеоиндуктивное действие.",
		clinicalIndicationsRu: "Деструктивные формы апикального периодонтита, кистогранулемы, временные зубы у детей.",
		defaultUnit: "шприц 2.2 г",
		approximatePriceRub: 1850,
		requiresLotTracking: false,
		aliases: ["Метапекс", "Metapex", "Йодоформ"],
	},
	{
		id: "endo_dress_calcicur",
		domain: "endo_dressing",
		nameRu: "Кальцикур (Calcicur, VOCO)",
		brandName: "Calcicur",
		manufacturer: "VOCO",
		country: "Германия",
		marketRank: 3,
		isMarketLeader: false,
		tier: "mainstream",
		descriptionRu: "Рентгеноконтрастная водная паста гидроксида кальция, стимулирует реминерализацию дентина.",
		clinicalIndicationsRu: "Непрямое и прямое покрытие пульпы, апексификация, временное вложение.",
		defaultUnit: "шприц 2 мл",
		approximatePriceRub: 2100,
		requiresLotTracking: false,
		aliases: ["Кальцикур", "Calcicur", "VOCO"],
	},
];

// ─────────────────────────────────────────────────────────────────────────────
// 4. ОРТОДОНТИЯ (Брекеты, дуги, элайнеры, микровинты)
// ─────────────────────────────────────────────────────────────────────────────
export const ORTHODONTIC_MATERIALS_REGISTRY: readonly ClinicalMarketMaterialItem[] = [
	// Брекет-системы
	{
		id: "ortho_bracket_damon_q2",
		domain: "ortho_bracket",
		nameRu: "Damon Q2 / Damon Clear 2 (Ormco, пассивное самолигирование)",
		brandName: "Damon Q2",
		manufacturer: "Ormco",
		country: "США",
		marketRank: 1,
		isMarketLeader: true,
		tier: "premium",
		descriptionRu: "Мировой лидер пассивного самолигирования: минимальное трение дуги в пазе, ускоренное расширение зубных рядов без удаления.",
		clinicalIndicationsRu: "Скученность любой тяжести, коррекция дистального и мезиального прикуса, дефицит места.",
		defaultUnit: "набор на 2 челюсти",
		approximatePriceRub: 48000,
		requiresLotTracking: true,
		aliases: ["Damon Q2", "Damon Clear 2", "Деймон", "Даймон", "Ormco"],
	},
	{
		id: "ortho_bracket_clarity",
		domain: "ortho_bracket",
		nameRu: "3M Clarity Advanced (керамические эстетические)",
		brandName: "3M Clarity",
		manufacturer: "3M Oral Care",
		country: "США",
		marketRank: 2,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Микрокристаллическая керамика с незаметным цветовым переходом под естественный оттенок эмали и запатентованным концентратором напряжений.",
		clinicalIndicationsRu: "Высочайшие эстетические требования пациента во фронтальном отделе.",
		defaultUnit: "набор на 2 челюсти",
		approximatePriceRub: 42000,
		requiresLotTracking: true,
		aliases: ["3M Clarity", "Clarity Advanced", "Кларити", "Керамические брекеты 3M"],
	},
	{
		id: "ortho_bracket_empower",
		domain: "ortho_bracket",
		nameRu: "American Orthodontics Empower (интерактивное самолигирование)",
		brandName: "Empower",
		manufacturer: "American Orthodontics",
		country: "США",
		marketRank: 3,
		isMarketLeader: false,
		tier: "mainstream",
		descriptionRu: "Двойной контроль: пассивный клипс в боковых отделах для снижения трения и активный во фронте для прецизионного торка.",
		clinicalIndicationsRu: "Максимальный контроль положения резцов и торка на завершающих этапах.",
		defaultUnit: "набор",
		approximatePriceRub: 36000,
		requiresLotTracking: true,
		aliases: ["Empower", "Американ Ортодонтикс", "Эмпауэр"],
	},
	{
		id: "ortho_bracket_pitts21",
		domain: "ortho_bracket",
		nameRu: "Pitts 21 (квадратный паз .021, OC Orthodontics)",
		brandName: "Pitts 21",
		manufacturer: "OC Orthodontics",
		country: "США",
		marketRank: 4,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Революционная философия SAP (Smile Arc Protection) с ранним 3D-контролем торка в квадратном пазе .021x.021.",
		clinicalIndicationsRu: "Создание широкой сияющей улыбки с защитой дуги улыбки (Smile Arc).",
		defaultUnit: "набор",
		approximatePriceRub: 45000,
		requiresLotTracking: true,
		aliases: ["Pitts 21", "Питтс 21", "SAP"],
	},
	{
		id: "ortho_bracket_h4",
		domain: "ortho_bracket",
		nameRu: "H4 самолигирующие металлические (Orthocentric)",
		brandName: "H4",
		manufacturer: "Orthocentric",
		country: "США",
		marketRank: 5,
		isMarketLeader: false,
		tier: "mainstream",
		descriptionRu: "Низкопрофильные пассивные самолигирующие металлические брекеты с гладкими контурами.",
		clinicalIndicationsRu: "Комфортное лечение с минимумом травмирования слизистой губ и щек.",
		defaultUnit: "набор",
		approximatePriceRub: 28000,
		requiresLotTracking: true,
		aliases: ["H4", "Н4"],
	},
	{
		id: "ortho_bracket_mini_master",
		domain: "ortho_bracket",
		nameRu: "Mini Master лигатурные классические (American Orthodontics)",
		brandName: "Mini Master",
		manufacturer: "American Orthodontics",
		country: "США",
		marketRank: 6,
		isMarketLeader: false,
		tier: "budget",
		descriptionRu: "Проверенная временем классика лигатурных металлических брекетов уменьшенного размера с диагональной сеткой основания.",
		clinicalIndicationsRu: "Бюджетное ортодонтическое лечение с возможностью использования цветных лигатур.",
		defaultUnit: "набор",
		approximatePriceRub: 18000,
		requiresLotTracking: true,
		aliases: ["Mini Master", "Мини Мастер", "Лигатурные брекеты"],
	},

	// Дуги
	{
		id: "ortho_wire_cuniti",
		domain: "ortho_archwire",
		nameRu: "Cu-Ni-Ti термоактивные 27°C / 35°C (Ormco)",
		brandName: "Cu-Ni-Ti",
		manufacturer: "Ormco",
		country: "США",
		marketRank: 1,
		isMarketLeader: true,
		tier: "premium",
		descriptionRu: "Медно-никель-титановые дуги с истинной термодинамической трансформацией фаз: малые постоянные физиологические силы.",
		clinicalIndicationsRu: "Первичное нивелирование и распутывание тяжелой скученности зубов.",
		defaultUnit: "шт.",
		approximatePriceRub: 1450,
		requiresLotTracking: false,
		aliases: ["CuNiTi", "КуНиТи", "Термоактивные дуги Ormco"],
	},
	{
		id: "ortho_wire_niti",
		domain: "ortho_archwire",
		nameRu: "Ni-Ti SuperElastic суперэластичные",
		brandName: "Ni-Ti",
		manufacturer: "Ormco / Hubit / AO",
		country: "США / Корея",
		marketRank: 2,
		isMarketLeader: false,
		tier: "mainstream",
		descriptionRu: "Классические никель-титановые дуги круглого и прямоугольного сечения (.014 - .019x.025).",
		clinicalIndicationsRu: "Базовое выравнивание и контроль формы зубной дуги.",
		defaultUnit: "шт.",
		approximatePriceRub: 650,
		requiresLotTracking: false,
		aliases: ["НиТи", "NiTi", "Суперэластик"],
	},
	{
		id: "ortho_wire_tma",
		domain: "ortho_archwire",
		nameRu: "ТМА (бета-титан / титан-молибден) (Ormco)",
		brandName: "TMA",
		manufacturer: "Ormco",
		country: "США",
		marketRank: 3,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Бета-титановая дуга без содержания никеля: превосходная пластичность, возможность нанесения любых изгибов.",
		clinicalIndicationsRu: "Юстировка, детализация прикуса, закрытие одиночных промежутков, пациенты с аллергией на никель.",
		defaultUnit: "шт.",
		approximatePriceRub: 1850,
		requiresLotTracking: false,
		aliases: ["ТМА", "TMA", "Бета-титан"],
	},
	{
		id: "ortho_wire_ss",
		domain: "ortho_archwire",
		nameRu: "Сталь нержавеющая медицинская (SS Stainless Steel)",
		brandName: "SS Wire",
		manufacturer: "Ormco / 3M",
		country: "США",
		marketRank: 4,
		isMarketLeader: false,
		tier: "mainstream",
		descriptionRu: "Жесткая стальная дуга максимального модуля упругости (.019x.025, .021x.025).",
		clinicalIndicationsRu: "Этап механики закрытия постэкстракционных промежутков (скольжение), удержание формы дуги.",
		defaultUnit: "шт.",
		approximatePriceRub: 550,
		requiresLotTracking: false,
		aliases: ["Стальная дуга", "SS Wire", "Stainless Steel"],
	},

	// Элайнеры
	{
		id: "ortho_aligner_3d_smile",
		domain: "ortho_aligner",
		nameRu: "3D Smile (прозрачные элайнеры, Россия)",
		brandName: "3D Smile",
		manufacturer: "3D Smile",
		country: "Россия",
		marketRank: 1,
		isMarketLeader: true,
		tier: "mainstream",
		descriptionRu: "Лидер отечественного рынка элайнеров с интеграцией анализа КЛКТ корней зубов и челюстной кости.",
		clinicalIndicationsRu: "Коррекция аномалий положения зубов, ротаций, закрытие диастем и трем без брекетов.",
		defaultUnit: "кейс (курс капп)",
		approximatePriceRub: 135000,
		requiresLotTracking: true,
		aliases: ["3D Smile", "3Д Смайл", "3ДСмайл"],
	},
	{
		id: "ortho_aligner_flexiligner",
		domain: "ortho_aligner",
		nameRu: "FlexiLigner (флексы, Россия/Италия)",
		brandName: "FlexiLigner",
		manufacturer: "FlexiLigner",
		country: "Россия/Италия",
		marketRank: 2,
		isMarketLeader: false,
		tier: "mainstream",
		descriptionRu: "Высокоэластичные каппы FlexiLigner из многослойного термопласта для плавного биомеханического перемещения.",
		clinicalIndicationsRu: "Взрослая и детская ортодонтия (FlexiKids), коррекция открытого и глубокого прикуса.",
		defaultUnit: "кейс (курс)",
		approximatePriceRub: 140000,
		requiresLotTracking: true,
		aliases: ["FlexiLigner", "Флексилайнер", "Флексы"],
	},
	{
		id: "ortho_aligner_spark",
		domain: "ortho_aligner",
		nameRu: "Spark Aligners (Ormco, США)",
		brandName: "Spark",
		manufacturer: "Ormco",
		country: "США",
		marketRank: 3,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Премиальный трехслойный материал TruGEN: максимальная прозрачность, устойчивость к окрашиванию и постоянство силы.",
		clinicalIndicationsRu: "Комплексные случаи лечения элайнерами, максимальные требования к эстетике.",
		defaultUnit: "кейс (курс)",
		approximatePriceRub: 210000,
		requiresLotTracking: true,
		aliases: ["Spark", "Спарк", "TruGEN"],
	},
	{
		id: "ortho_aligner_eurokappa",
		domain: "ortho_aligner",
		nameRu: "Eurokappa (прозрачные элайнеры, Россия)",
		brandName: "Eurokappa",
		manufacturer: "Eurokappa",
		country: "Россия",
		marketRank: 4,
		isMarketLeader: false,
		tier: "mainstream",
		descriptionRu: "Российский производитель элайнеров с быстрым сроком печати и доставки сетов капп в клинику.",
		clinicalIndicationsRu: "Ортодонтическое выравнивание зубных рядов со сжатыми сроками подготовки.",
		defaultUnit: "кейс",
		approximatePriceRub: 125000,
		requiresLotTracking: true,
		aliases: ["Eurokappa", "Еврокаппа", "Еврокаппы"],
	},
	{
		id: "ortho_aligner_invisalign",
		domain: "ortho_aligner",
		nameRu: "Invisalign (Align Technology, США)",
		brandName: "Invisalign",
		manufacturer: "Align Technology",
		country: "США",
		marketRank: 5,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Мировой родоначальник технологии элайнеров: материал SmartTrack и аттачменты SmartForce.",
		clinicalIndicationsRu: "Международный стандарт прозрачной ортодонтии высшего ценового сегмента.",
		defaultUnit: "кейс",
		approximatePriceRub: 280000,
		requiresLotTracking: true,
		aliases: ["Invisalign", "Инвизилайн", "Align"],
	},
	{
		id: "ortho_aligner_star_smile",
		domain: "ortho_aligner",
		nameRu: "Star Smile (прозрачные элайнеры, Россия)",
		brandName: "Star Smile",
		manufacturer: "Star Smile",
		country: "Россия",
		marketRank: 6,
		isMarketLeader: false,
		tier: "budget",
		descriptionRu: "Доступная отечественная система элайнеров с 3D-моделированием и протоколом виртуального сетапа.",
		clinicalIndicationsRu: "Бюджетное выравнивание фронтальной группы зубов, подготовка к протезированию.",
		defaultUnit: "кейс",
		approximatePriceRub: 110000,
		requiresLotTracking: true,
		aliases: ["Star Smile", "Стар Смайл"],
	},

	// Микроимпланты / ортодонтические винты
	{
		id: "ortho_screw_bioray",
		domain: "ortho_miniscrew",
		nameRu: "Bio-Ray ортодонтические мини-винты (Южная Корея)",
		brandName: "Bio-Ray",
		manufacturer: "Bio-Ray",
		country: "Южная Корея",
		marketRank: 1,
		isMarketLeader: true,
		tier: "mainstream",
		descriptionRu: "Титановые самонарезающие микровинты с перекрестной головкой под эластики и пружины (Ø 1.4-2.0 мм, длина 6-12 мм).",
		clinicalIndicationsRu: "Абсолютный скелетный анкораж (дистализация, интрузия моляров, мезиализация).",
		defaultUnit: "шт.",
		approximatePriceRub: 4500,
		requiresLotTracking: true,
		aliases: ["Bio-Ray", "Биорей", "Микровинты Bio-Ray"],
	},
	{
		id: "ortho_screw_vectortas",
		domain: "ortho_miniscrew",
		nameRu: "VectorTAS временная скелетная опора (Ormco, США)",
		brandName: "VectorTAS",
		manufacturer: "Ormco",
		country: "США",
		marketRank: 2,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Комплексная система временного скелетного анкоража с цветовой кодировкой длин и хирургическим набором.",
		clinicalIndicationsRu: "Скелетная опора для сложных перемещений без потери анкоража опорных моляров.",
		defaultUnit: "шт.",
		approximatePriceRub: 6800,
		requiresLotTracking: true,
		aliases: ["VectorTAS", "Вектор ТАС", "ВекторТАС"],
	},
	{
		id: "ortho_screw_absoanchor",
		domain: "ortho_miniscrew",
		nameRu: "Dentos AbsoAnchor ортодонтические микроимпланты (Корея)",
		brandName: "AbsoAnchor",
		manufacturer: "Dentos Inc",
		country: "Южная Корея",
		marketRank: 3,
		isMarketLeader: false,
		tier: "mainstream",
		descriptionRu: "Классические микровинты профессора Парка: коническая форма резьбы, минимальный риск контакта с корнями.",
		clinicalIndicationsRu: "Интрарадикулярная и экстрарадикулярная установка (IZC, шельф нижней челюсти).",
		defaultUnit: "шт.",
		approximatePriceRub: 4900,
		requiresLotTracking: true,
		aliases: ["AbsoAnchor", "Dentos", "Абсоанкер"],
	},
];
