/**
 * implantAndBoneMaterialsData.ts — Реестр имплантационных систем и костно-мембранных материалов
 * с охватом до 90%+ рынка РФ/СНГ (ранжирование строго по убыванию популярности).
 *
 * Mandate 8b: строго <= 800 строк
 * Mandate 8e: Doctor Autonomy (1 клик)
 * Mandate 8d: ноль мультяшных эмодзи
 * UTF-8 без BOM
 */

export type ClinicalMaterialDomain =
	| "implant_system"
	| "bone_graft"
	| "bone_membrane"
	| "bone_graft_membrane"
	| "surg_suture"
	| "surg_hemostatic"
	| "therapy_composite"
	| "therapy_adhesive"
	| "endo_file"
	| "endo_sealer"
	| "endo_irrigation"
	| "endo_dressing"
	| "ortho_bracket"
	| "ortho_archwire"
	| "ortho_aligner"
	| "ortho_miniscrew"
	| "prostho_a_silicone"
	| "prostho_c_silicone"
	| "prostho_bite_reg"
	| "prostho_cement_perm"
	| "prostho_cement_temp"
	| "prostho_retraction"
	| "lab_cad_material";

export interface ClinicalMarketMaterialItem {
	readonly id: string;
	readonly domain: ClinicalMaterialDomain;
	readonly nameRu: string;
	readonly brandName: string;
	readonly manufacturer: string;
	readonly country: string;
	readonly marketRank: number; // 1 = лидер рынка
	readonly isMarketLeader: boolean;
	readonly tier: "premium" | "mainstream" | "budget";
	readonly descriptionRu: string;
	readonly clinicalIndicationsRu: string;
	readonly defaultUnit: string;
	readonly approximatePriceRub: number;
	readonly requiresLotTracking: boolean;
	readonly aliases?: readonly string[];
}

export const IMPLANT_SYSTEMS_MARKET_REGISTRY: readonly ClinicalMarketMaterialItem[] = [
	{
		id: "implant_osstem",
		domain: "implant_system",
		nameRu: "Osstem TS III / TS IV SA/CA (Южная Корея)",
		brandName: "Osstem",
		manufacturer: "Osstem Implant",
		country: "Южная Корея",
		marketRank: 1,
		isMarketLeader: true,
		tier: "mainstream",
		descriptionRu: "Титановый дентальный имплантат с гидрофильной SA/CA поверхностью, самонарезающая резьба, высокая первичная стабильность.",
		clinicalIndicationsRu: "Универсальный протокол: одиночные и мостовидные реставрации, протоколы All-on-4/6, немедленная нагрузка.",
		defaultUnit: "шт.",
		approximatePriceRub: 18500,
		requiresLotTracking: true,
		aliases: ["Osstem TS3", "Osstem TS4", "Осстем", "TS III", "TS IV", "Osstem TSIII CA"],
	},
	{
		id: "implant_dentium",
		domain: "implant_system",
		nameRu: "Dentium SuperLine / Implantium (Южная Корея)",
		brandName: "Dentium",
		manufacturer: "Dentium",
		country: "Южная Корея",
		marketRank: 2,
		isMarketLeader: false,
		tier: "mainstream",
		descriptionRu: "Конический имплантат с выраженной двойной резьбой и SLA-поверхностью, высокая приживаемость в кости типа D2-D4.",
		clinicalIndicationsRu: "Универсальное применение, одномоментная имплантация в лунку удаленного зуба, синус-лифтинг.",
		defaultUnit: "шт.",
		approximatePriceRub: 19000,
		requiresLotTracking: true,
		aliases: ["Dentium SuperLine", "Dentium Implantium", "Дентиум", "SuperLine", "Имплантиум"],
	},
	{
		id: "implant_straumann",
		domain: "implant_system",
		nameRu: "Straumann BLX / Bone Level SLA (Швейцария)",
		brandName: "Straumann",
		manufacturer: "Straumann Group",
		country: "Швейцария",
		marketRank: 3,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Премиальный швейцарский имплантат из сплава Roxolid с гидрофильной поверхностью SLActive/SLA, сверхбыстрая остеоинтеграция 3–4 недели.",
		clinicalIndicationsRu: "Сложные клинические случаи, скомпрометированная кость, немедленная нагрузка, пациенты с диабетом и после лучевой терапии.",
		defaultUnit: "шт.",
		approximatePriceRub: 38500,
		requiresLotTracking: true,
		aliases: ["Straumann BLX", "Straumann BLT", "Straumann Bone Level", "Штрауман", "Штрауманн", "Roxolid"],
	},
	{
		id: "implant_nobel_biocare",
		domain: "implant_system",
		nameRu: "Nobel Biocare Active / Conical / Replace (Швейцария/США)",
		brandName: "Nobel Biocare",
		manufacturer: "Nobel Biocare (Envista)",
		country: "Швейцария/США",
		marketRank: 4,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Премиальная система с поверхностью TiUltra и утолщенным оксидным слоем, выраженная конденсация губчатой кости.",
		clinicalIndicationsRu: "Эстетическая зона, немедленная нагрузка в мягкой кости (D3-D4), оригинальные протоколы All-on-4.",
		defaultUnit: "шт.",
		approximatePriceRub: 39500,
		requiresLotTracking: true,
		aliases: ["NobelActive", "NobelReplace", "Nobel Biocare", "Нобель", "Нобель Биокеар", "Nobel Conical CC"],
	},
	{
		id: "implant_megagen_anyridge",
		domain: "implant_system",
		nameRu: "MegaGen AnyRidge / AnyOne (Южная Корея)",
		brandName: "MegaGen",
		manufacturer: "MegaGen",
		country: "Южная Корея",
		marketRank: 5,
		isMarketLeader: false,
		tier: "mainstream",
		descriptionRu: "Инновационная резьба KnifeThread с поверхностью Xpeed (ионы кальция), максимальная торк-стабильность при минимуме остеотомии.",
		clinicalIndicationsRu: "Узкий альвеолярный гребень, расщепление гребня, одномоментная имплантация, мягкая кость D4.",
		defaultUnit: "шт.",
		approximatePriceRub: 21000,
		requiresLotTracking: true,
		aliases: ["AnyRidge", "AnyOne", "MegaGen", "Мегаджен", "Эниридж"],
	},
	{
		id: "implant_astra_tech",
		domain: "implant_system",
		nameRu: "Astra Tech OsseoSpeed TX / EV (Dentsply Sirona, Швеция)",
		brandName: "Astra Tech",
		manufacturer: "Dentsply Sirona",
		country: "Швеция",
		marketRank: 6,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Поверхность с нанофторидом OsseoSpeed, микрорезьба на шейке MicroThread и коническое соединение Conical Seal Design.",
		clinicalIndicationsRu: "Сохранение маргинальной кости в долгосрочной перспективе, высокая эстетика десны.",
		defaultUnit: "шт.",
		approximatePriceRub: 37000,
		requiresLotTracking: true,
		aliases: ["Astra Tech", "OsseoSpeed EV", "Астра Тек"],
	},
	{
		id: "implant_neobiotech",
		domain: "implant_system",
		nameRu: "NeoBiotech IS-II / IS-III active (Южная Корея)",
		brandName: "NeoBiotech",
		manufacturer: "NeoBiotech",
		country: "Южная Корея",
		marketRank: 7,
		isMarketLeader: false,
		tier: "mainstream",
		descriptionRu: "SLA-поверхность с гидрофильной активацией, биодизайн Magic Thread для щадящего распределения окклюзионной нагрузки.",
		clinicalIndicationsRu: "Стандартные протоколы двухэтапной и одноэтапной имплантации, щадящее препарирование ложа.",
		defaultUnit: "шт.",
		approximatePriceRub: 16500,
		requiresLotTracking: true,
		aliases: ["Neobiotech", "Необиотек", "IS-II active", "IS-III"],
	},
	{
		id: "implant_hitec",
		domain: "implant_system",
		nameRu: "Hi-Tec Implants Logic / Spark (Израиль)",
		brandName: "Hi-Tec",
		manufacturer: "Hi-Tec Implants",
		country: "Израиль",
		marketRank: 8,
		isMarketLeader: false,
		tier: "budget",
		descriptionRu: "Надежная израильская система из медицинского титана Grade 5, встроенное переключение платформ.",
		clinicalIndicationsRu: "Бюджетная реабилитация, включенные и концевые дефекты зубного ряда.",
		defaultUnit: "шт.",
		approximatePriceRub: 14500,
		requiresLotTracking: true,
		aliases: ["Hi-Tec", "Хай-Тек", "Хай Тек", "Logic"],
	},
	{
		id: "implant_impro",
		domain: "implant_system",
		nameRu: "Impro (Неметчина / Германия)",
		brandName: "Impro",
		manufacturer: "BioMetiqua / Impro",
		country: "Германия",
		marketRank: 9,
		isMarketLeader: false,
		tier: "mainstream",
		descriptionRu: "Немецкая система дентальных имплантатов из чистого титана Grade 4 с микропористой поверхностью SuperHole.",
		clinicalIndicationsRu: "Универсальный хирургический протокол, одномоментная имплантация, надежная остеоинтеграция.",
		defaultUnit: "шт.",
		approximatePriceRub: 21500,
		requiresLotTracking: true,
		aliases: ["Impro", "Импро", "Impro Dental"],
	},
	{
		id: "implant_biohorizons",
		domain: "implant_system",
		nameRu: "BioHorizons Tapered Internal (США)",
		brandName: "BioHorizons",
		manufacturer: "BioHorizons IPH Inc.",
		country: "США",
		marketRank: 10,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Патентованная технология лазерных микробороздок Laser-Lok на шейке для истинного прикрепления соединительнотканных волокон.",
		clinicalIndicationsRu: "Зона высокой эстетики, профилактика периимплантита, стабилизация костного пика.",
		defaultUnit: "шт.",
		approximatePriceRub: 31000,
		requiresLotTracking: true,
		aliases: ["BioHorizons", "Биогоризонт", "Биохорайзонс", "Laser-Lok"],
	},
	{
		id: "implant_mis",
		domain: "implant_system",
		nameRu: "MIS Seven / C1 / V3 (Израиль)",
		brandName: "MIS",
		manufacturer: "MIS Implants (Dentsply Sirona)",
		country: "Израиль",
		marketRank: 11,
		isMarketLeader: false,
		tier: "mainstream",
		descriptionRu: "Популярный конический имплантат с микрокольцами шейки и коническим соединением 12°.",
		clinicalIndicationsRu: "Все типы костной ткани, протоколы немедленной и отсроченной нагрузки.",
		defaultUnit: "шт.",
		approximatePriceRub: 19500,
		requiresLotTracking: true,
		aliases: ["MIS Seven", "MIS C1", "MIS V3", "МИС"],
	},
	{
		id: "implant_alpha_bio",
		domain: "implant_system",
		nameRu: "Alpha-Bio SPI / DFI (Израиль)",
		brandName: "Alpha-Bio",
		manufacturer: "Alpha-Bio Tec",
		country: "Израиль",
		marketRank: 12,
		isMarketLeader: false,
		tier: "budget",
		descriptionRu: "Спиральный самонарезающий имплантат NanoTec с глубокой резьбой, классика израильской школы.",
		clinicalIndicationsRu: "Узкая кость, экспансия костного ложа, высокая первичная стабилизация.",
		defaultUnit: "шт.",
		approximatePriceRub: 14000,
		requiresLotTracking: true,
		aliases: ["Alpha-Bio", "Альфа-Био", "Альфа Био", "SPI"],
	},
	{
		id: "implant_anthogyr",
		domain: "implant_system",
		nameRu: "Anthogyr Axiom REG / 2.8 (Франция)",
		brandName: "Anthogyr",
		manufacturer: "Anthogyr (Straumann Group)",
		country: "Франция",
		marketRank: 13,
		isMarketLeader: false,
		tier: "mainstream",
		descriptionRu: "Французская система с BCP-поверхностью и постоянным коническим соединением без микрозазоров.",
		clinicalIndicationsRu: "Узкие межзубные промежутки (диаметр 2.8 мм), сохранение десневого сосочка.",
		defaultUnit: "шт.",
		approximatePriceRub: 23000,
		requiresLotTracking: true,
		aliases: ["Anthogyr", "Axiom", "Антожир"],
	},
	{
		id: "implant_ankylos",
		domain: "implant_system",
		nameRu: "Ankylos C/X (Dentsply Sirona, Германия)",
		brandName: "Ankylos",
		manufacturer: "Dentsply Sirona",
		country: "Германия",
		marketRank: 14,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Конусное соединение TissueCare Cone с субкрестальным заглублением, отсутствие резорбции шейки.",
		clinicalIndicationsRu: "Высочайшие требования к эстетике передней группы зубов, длительное сохранение кости.",
		defaultUnit: "шт.",
		approximatePriceRub: 35000,
		requiresLotTracking: true,
		aliases: ["Ankylos", "Анкилоз", "Анкилос"],
	},
	{
		id: "implant_medentika",
		domain: "implant_system",
		nameRu: "Medentika Microcone / Quattrocone (Германия)",
		brandName: "Medentika",
		manufacturer: "Medentika (Straumann Group)",
		country: "Германия",
		marketRank: 15,
		isMarketLeader: false,
		tier: "mainstream",
		descriptionRu: "Высокоточное немецкое фрезерование, стабильное конусное соединение и переключение платформ.",
		clinicalIndicationsRu: "Классическая хирургия, высокая механическая выносливость при жевательных нагрузках.",
		defaultUnit: "шт.",
		approximatePriceRub: 22000,
		requiresLotTracking: true,
		aliases: ["Medentika", "Медентика"],
	},
	{
		id: "implant_iris",
		domain: "implant_system",
		nameRu: "ИРИС Лидер / Эволюция (Россия)",
		brandName: "ИРИС",
		manufacturer: "ИРИС (Россия)",
		country: "Россия",
		marketRank: 16,
		isMarketLeader: false,
		tier: "budget",
		descriptionRu: "Отечественная дентальная система профессора Никольского из титана ВТ6, адаптирована под российские клинические реалии.",
		clinicalIndicationsRu: "Импортозамещение, бюджетная реабилитация, клиники ОМС/ДМС и частный сегмент.",
		defaultUnit: "шт.",
		approximatePriceRub: 11000,
		requiresLotTracking: true,
		aliases: ["ИРИС", "IRIS", "Лидер"],
	},
];

export const BONE_GRAFT_MEMBRANES_REGISTRY: readonly ClinicalMarketMaterialItem[] = [
	// Костные материалы (гранулы, блоки)
	{
		id: "bone_bio_oss",
		domain: "bone_graft_membrane",
		nameRu: "Geistlich Bio-Oss (гранулы S / L, блоки) (Швейцария)",
		brandName: "Bio-Oss",
		manufacturer: "Geistlich Pharma",
		country: "Швейцария",
		marketRank: 1,
		isMarketLeader: true,
		tier: "premium",
		descriptionRu: "Золотой стандарт костной пластики: натуральный бычий ксеногенный гидроксиапатит с естественной пористой структурой.",
		clinicalIndicationsRu: "Синус-лифтинг, направленная костная регенерация (НКР), заполнение лунок удаленных зубов.",
		defaultUnit: "фл. (0.5 г)",
		approximatePriceRub: 14500,
		requiresLotTracking: true,
		aliases: ["Bio-Oss", "Био-Осс", "Био Осс", "Geistlich"],
	},
	{
		id: "bone_cerabone",
		domain: "bone_graft_membrane",
		nameRu: "Botiss Cerabone (гранулы / блоки, Германия)",
		brandName: "Cerabone",
		manufacturer: "Botiss biomaterials",
		country: "Германия",
		marketRank: 2,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Чистый бычий гидроксиапатит термической обработки (1200°C), максимальная остеокондуктивность и стабильность объема.",
		clinicalIndicationsRu: "Долговременная стабильность объема при обширных костных дефектах и синус-лифтинге.",
		defaultUnit: "фл. (0.5 см³)",
		approximatePriceRub: 12500,
		requiresLotTracking: true,
		aliases: ["Cerabone", "Церабон", "Ботисс", "Botiss"],
	},
	{
		id: "bone_sureoss",
		domain: "bone_graft_membrane",
		nameRu: "SureOss (кортикально-губчатый аллографт, HansBiomed, Корея)",
		brandName: "SureOss",
		manufacturer: "HansBiomed Corp.",
		country: "Южная Корея",
		marketRank: 3,
		isMarketLeader: false,
		tier: "mainstream",
		descriptionRu: "Лиофилизированный деминерализованный аллографт (DBM) высокой чистоты, остеоиндуктивный и остеокондуктивный потенциал.",
		clinicalIndicationsRu: "НКР, ускоренное формирование собственной кости, сохранение объема лунки (Socket Preservation).",
		defaultUnit: "фл. (0.5 см³)",
		approximatePriceRub: 9800,
		requiresLotTracking: true,
		aliases: ["SureOss", "ШурОсс", "ШуреОсс", "HansBiomed"],
	},
	{
		id: "bone_genoss",
		domain: "bone_graft_membrane",
		nameRu: "Gen-Oss / Apatos (OsteoBiol, Италия)",
		brandName: "Gen-Oss",
		manufacturer: "Tecnoss / OsteoBiol",
		country: "Италия",
		marketRank: 4,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Кортикально-губчатая ксеноколлагеновая смесь, обработанная без высокотемпературного спекания (сохраняет природный коллаген).",
		clinicalIndicationsRu: "Горизонтальная аугментация альвеолярного гребня, синус-лифтинг, заполнение костных карманов.",
		defaultUnit: "фл. (0.5 г)",
		approximatePriceRub: 11200,
		requiresLotTracking: true,
		aliases: ["Gen-Oss", "OsteoBiol", "Ген-Осс", "Остеобиол", "Apatos"],
	},
	{
		id: "bone_collapol_tacho",
		domain: "bone_graft_membrane",
		nameRu: "Коллапол (КП, КП-2, КП-3) / Тахокомб (гемостатики и пластины)",
		brandName: "Коллапол",
		manufacturer: "Полистом / Takeda",
		country: "Россия / Япония",
		marketRank: 5,
		isMarketLeader: false,
		tier: "mainstream",
		descriptionRu: "Коллагеновые остеопластические пластины с антимикробными компонентами (метронидазол, линкомицин, гидроксиапатит).",
		clinicalIndicationsRu: "Остановка капиллярного кровотечения, заполнение пародонтальных дефектов, изоляция перфораций шнайдеровой мембраны.",
		defaultUnit: "упак.",
		approximatePriceRub: 1800,
		requiresLotTracking: false,
		aliases: ["Коллапол", "Тахокомб", "ТахоКомб", "Полистом"],
	},
	{
		id: "bone_lioplast",
		domain: "bone_graft_membrane",
		nameRu: "Лиопласт (ЦТК Самара, лиофилизированный аллографт, Россия)",
		brandName: "Лиопласт",
		manufacturer: "Самарский банк тканей (ЦТК)",
		country: "Россия",
		marketRank: 6,
		isMarketLeader: false,
		tier: "budget",
		descriptionRu: "Отечественный аллогенный остеопластический биоматериал радиационной стерилизации с сохраненными костными морфогенетическими белками (BMP).",
		clinicalIndicationsRu: "Бюджетная костная пластика, синус-лифтинг, реконструктивная хирургия альвеолярного отростка.",
		defaultUnit: "фл. (0.5 см³)",
		approximatePriceRub: 3500,
		requiresLotTracking: true,
		aliases: ["Лиопласт", "Lioplast", "ЦТК"],
	},
	{
		id: "bone_osteomatrix",
		domain: "bone_graft_membrane",
		nameRu: "Остеоматрикс / Биоматрикс (Коннектбиофарм, Россия)",
		brandName: "Остеоматрикс",
		manufacturer: "Коннектбиофарм",
		country: "Россия",
		marketRank: 7,
		isMarketLeader: false,
		tier: "mainstream",
		descriptionRu: "Отечественный биопластический материал на основе костного коллагена и сульфатированных ГАГ.",
		clinicalIndicationsRu: "Заполнение пародонтальных карманов, лунок, пластика кости при цистэктомии.",
		defaultUnit: "фл. (0.5 см³)",
		approximatePriceRub: 4500,
		requiresLotTracking: true,
		aliases: ["Остеоматрикс", "Биоматрикс", "Коннектбиофарм"],
	},

	// Мембраны барьерные
	{
		id: "membrane_bio_gide",
		domain: "bone_graft_membrane",
		nameRu: "Geistlich Bio-Gide (коллагеновая мембрана, Швейцария)",
		brandName: "Bio-Gide",
		manufacturer: "Geistlich Pharma",
		country: "Швейцария",
		marketRank: 1,
		isMarketLeader: true,
		tier: "premium",
		descriptionRu: "Резорбируемая двухслойная свиная коллагеновая мембрана, обеспечивает барьер от прорастания эпителия на 24 недели.",
		clinicalIndicationsRu: "Перекрытие аугментатов при НКР, закрытие окна латерального синус-лифтинга.",
		defaultUnit: "шт. (25x25 мм)",
		approximatePriceRub: 16500,
		requiresLotTracking: true,
		aliases: ["Bio-Gide", "Био-Гайд", "Био Гайд", "Geistlich"],
	},
	{
		id: "membrane_botiss_jason",
		domain: "bone_graft_membrane",
		nameRu: "Botiss Jason Membrane (перикардиальная нативная, Германия)",
		brandName: "Jason Membrane",
		manufacturer: "Botiss biomaterials",
		country: "Германия",
		marketRank: 2,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Нативная свиная перикардиальная мембрана исключительной прочности на разрыв, барьерная функция 12–28 недель.",
		clinicalIndicationsRu: "Обширные вертикальные и горизонтальные костные дефекты, фиксация пинами без риска прорезывания.",
		defaultUnit: "шт. (20x30 мм)",
		approximatePriceRub: 15500,
		requiresLotTracking: true,
		aliases: ["Jason Membrane", "Джейсон мембрана", "Botiss Jason", "Ботисс Джейсон"],
	},
	{
		id: "membrane_cytoplast_ptfe",
		domain: "bone_graft_membrane",
		nameRu: "Cytoplast TXT-200 / Ti-250 (d-PTFE нерезорбируемая, Osteogenics, США)",
		brandName: "Cytoplast",
		manufacturer: "Osteogenics Biomedical",
		country: "США",
		marketRank: 3,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Плотная политетрафторэтиленовая мембрана высокой плотности (d-PTFE) с титановым усилением или без, непроницаема для бактерий при открытом ведении.",
		clinicalIndicationsRu: "Консервация лунки без первичного ушивания лоскута, 3D вертикальная костная аугментация.",
		defaultUnit: "шт. (12x24 мм)",
		approximatePriceRub: 18500,
		requiresLotTracking: true,
		aliases: ["Cytoplast", "Цитопласт", "PTFE мембрана", "Ti-250"],
	},
	{
		id: "membrane_osteoplast",
		domain: "bone_graft_membrane",
		nameRu: "Остеопласт (коллагеновая барьерная мембрана, КБФ, Россия)",
		brandName: "Остеопласт",
		manufacturer: "КБФ / ВладМиВа",
		country: "Россия",
		marketRank: 4,
		isMarketLeader: false,
		tier: "budget",
		descriptionRu: "Отечественная резорбируемая коллагеновая мембрана для защиты костного регенерата на срок 6–8 недель.",
		clinicalIndicationsRu: "Бюджетная костная пластика, пародонтальная хирургия, закрытие костных полостей.",
		defaultUnit: "шт. (20x30 мм)",
		approximatePriceRub: 4200,
		requiresLotTracking: true,
		aliases: ["Остеопласт", "Osteoplast", "КБФ мембрана"],
	},
	{
		id: "mesh_titanium_pins",
		domain: "bone_graft_membrane",
		nameRu: "Титановые сетки и пины (Ким, Meisinger, Frios)",
		brandName: "Титановые пины и сетки",
		manufacturer: "Meisinger / Dentsply Frios / Kim",
		country: "Германия / Южная Корея",
		marketRank: 5,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Микропины и 3D-титановые сетки для жесткой пространственной фиксации аугментата при 3D-НКР.",
		clinicalIndicationsRu: "Вертикальная и горизонтальная костная аугментация экстремальных атрофий альвеолярного отростка.",
		defaultUnit: "набор",
		approximatePriceRub: 8500,
		requiresLotTracking: true,
		aliases: ["Титановые сетки", "Титановые пины", "Пины Frios", "Пины Ким"],
	},
];
