/**
 * prosthoMaterialsData.ts — Реестр ортопедических материалов
 * (оттискные массы, полиэфиры, регистраторы прикуса, цементы, ретракция и конструкции ЗТЛ)
 * с охватом до 90%+ рынка РФ/СНГ (ранжирование строго по убыванию популярности).
 *
 * Mandate 8b: строго <= 800 строк
 * Mandate 8e: Doctor Autonomy (1 клик)
 * Mandate 8d: ноль мультяшных эмодзи
 * UTF-8 без BOM
 */

import type { ClinicalMarketMaterialItem } from "./implantAndBoneMaterialsData.js";

// ─────────────────────────────────────────────────────────────────────────────
// 5. ОРТОПЕДИЯ (Оттискные массы, цементы, ретракция, CAD/CAM материалы)
// ─────────────────────────────────────────────────────────────────────────────
export const PROSTHODONTIC_MATERIALS_REGISTRY: readonly ClinicalMarketMaterialItem[] = [
	// А-силиконы и полиэфиры для прецизионных оттисков
	{
		id: "prostho_asilicone_elite_hd",
		domain: "prostho_a_silicone",
		nameRu: "Elite HD+ Putty Soft / Light Body (Zhermack, Италия)",
		brandName: "Elite HD+",
		manufacturer: "Zhermack",
		country: "Италия",
		marketRank: 1,
		isMarketLeader: true,
		tier: "mainstream",
		descriptionRu: "Самый распространенный А-силикон в РФ/СНГ: идеальный гидроконтроль, высокая прочность на разрыв и точность отображения зубодесневой борозды.",
		clinicalIndicationsRu: "Двухслойные одномоментные и двухэтапные слепки под коронки, мосты, вкладки и бюгели.",
		defaultUnit: "база (2x250 мл) + картридж (50 мл)",
		approximatePriceRub: 5900,
		requiresLotTracking: false,
		aliases: ["Elite HD+", "Элит ХД", "Zhermack А-силикон", "Элит"],
	},
	{
		id: "prostho_asilicone_express",
		domain: "prostho_a_silicone",
		nameRu: "Express XT / Imprint 4 (3M Oral Care, А-силикон)",
		brandName: "Express XT / Imprint 4",
		manufacturer: "3M Oral Care",
		country: "США",
		marketRank: 2,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Премиальная винилполисилоксановая оттискная масса с активным саморазогревом и сверхвысокой гидрофильностью во влажной среде.",
		clinicalIndicationsRu: "Прецизионные двухслойные оттиски под цельнокерамические коронки, виниры и балочные конструкции.",
		defaultUnit: "база (2x300 мл) + картридж (50 мл)",
		approximatePriceRub: 9800,
		requiresLotTracking: false,
		aliases: ["Express XT", "Imprint 4", "3M А-силикон", "Импринт"],
	},
	{
		id: "prostho_polyether_impregum",
		domain: "prostho_a_silicone",
		nameRu: "Impregum Penta / Soft (3M Oral Care, полиэфирная масса)",
		brandName: "Impregum",
		manufacturer: "3M Oral Care",
		country: "Германия / США",
		marketRank: 3,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Полиэфирный эталон оттискного материала: непревзойденная начальная гидрофильность, идеальная жесткость для трансферных слепков на имплантатах.",
		clinicalIndicationsRu: "Снятие оттисков с имплантатов открытой/закрытой ложкой, протяженные тотальные работы, виниры.",
		defaultUnit: "туба Pentamix (300 мл + 60 мл)",
		approximatePriceRub: 14500,
		requiresLotTracking: false,
		aliases: ["Impregum", "Импрегум", "Полиэфир 3M", "Penta Soft"],
	},
	{
		id: "prostho_asilicone_hydrorise",
		domain: "prostho_a_silicone",
		nameRu: "Hydrorise Maxi Putty / Extra Light (Zhermack, Италия)",
		brandName: "Hydrorise",
		manufacturer: "Zhermack",
		country: "Италия",
		marketRank: 4,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Гипергидросовместимый А-силикон с контактным углом смачивания < 10°, исключительная четкость воспроизведения поддесневых уступов.",
		clinicalIndicationsRu: "Сложные субгингивальные границы препарирования, безметалловые реставрации, виниры.",
		defaultUnit: "набор",
		approximatePriceRub: 8900,
		requiresLotTracking: false,
		aliases: ["Hydrorise", "Гидрорайз", "Zhermack Hydrorise"],
	},
	{
		id: "prostho_asilicone_silagum",
		domain: "prostho_a_silicone",
		nameRu: "Silagum Putty / Light (DMG, Германия)",
		brandName: "Silagum",
		manufacturer: "DMG Dental",
		country: "Германия",
		marketRank: 5,
		isMarketLeader: false,
		tier: "mainstream",
		descriptionRu: "Проверенная немецкая А-силиконовая система с легким извлечением из полости рта и устойчивостью к деформациям.",
		clinicalIndicationsRu: "Коронки, мостовидные протезы, мостовидные вкладки Inlay/Onlay.",
		defaultUnit: "набор",
		approximatePriceRub: 6800,
		requiresLotTracking: false,
		aliases: ["Silagum", "Силагум", "DMG Silagum"],
	},
	{
		id: "prostho_asilicone_variotime",
		domain: "prostho_a_silicone",
		nameRu: "Variotime Dynamix / Light Flow (Kulzer, Германия)",
		brandName: "Variotime",
		manufacturer: "Kulzer",
		country: "Германия",
		marketRank: 6,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Инновационная концепция вариабельного времени схватывания (от 1:00 до 2:30 мин), адаптация под темп работы врача.",
		clinicalIndicationsRu: "Протяженные мостовидные протезы и тотальные реабилитации на зубах и имплантатах.",
		defaultUnit: "набор",
		approximatePriceRub: 7500,
		requiresLotTracking: false,
		aliases: ["Variotime", "Вариотайм", "Kulzer"],
	},

	// С-силиконы
	{
		id: "prostho_csilicone_zetaplus",
		domain: "prostho_c_silicone",
		nameRu: "Zetaplus / Oranwash L (Zhermack, С-силикон)",
		brandName: "Zetaplus",
		manufacturer: "Zhermack",
		country: "Италия",
		marketRank: 1,
		isMarketLeader: true,
		tier: "budget",
		descriptionRu: "Абсолютный лидер рынка С-силиконов в РФ/СНГ: классический слепочный полисилоксан с мятным вкусом и катализатором Indurent Gel.",
		clinicalIndicationsRu: "Предварительные слепки, диагностические модели, временные коронки, прикусные шаблоны.",
		defaultUnit: "банка 900 мл + туба 140 мл + гель",
		approximatePriceRub: 3200,
		requiresLotTracking: false,
		aliases: ["Zetaplus", "Зетаплюс", "Оранвош", "Oranwash", "Зета"],
	},
	{
		id: "prostho_csilicone_speedex",
		domain: "prostho_c_silicone",
		nameRu: "Speedex Putty / Light Body (Coltene, Швейцария)",
		brandName: "Speedex",
		manufacturer: "Coltene",
		country: "Швейцария",
		marketRank: 2,
		isMarketLeader: false,
		tier: "budget",
		descriptionRu: "С-силикон с усадкой, близкой к А-силиконам (патентованная технология поверхностного натяжения Coltene).",
		clinicalIndicationsRu: "Точные оттиски для мостовидных протезов и коронок в бюджетном протоколе.",
		defaultUnit: "набор",
		approximatePriceRub: 3900,
		requiresLotTracking: false,
		aliases: ["Speedex", "Спидекс", "Coltene"],
	},

	// Регистраторы прикуса (Bite Registration)
	{
		id: "prostho_bite_obite",
		domain: "prostho_bite_reg",
		nameRu: "O-Bite (DMG, А-силиконовый регистратор прикуса)",
		brandName: "O-Bite",
		manufacturer: "DMG Dental",
		country: "Германия",
		marketRank: 1,
		isMarketLeader: true,
		tier: "premium",
		descriptionRu: "Один из самых твердых винилполисилоксановых регистраторов прикуса (Shore D 93), нулевое пружинение при сопоставлении гипсовых моделей в артикуляторе.",
		clinicalIndicationsRu: "Регистрация центральной окклюзии, сопоставление зубных дуг, перенос в артикулятор.",
		defaultUnit: "картридж 50 мл + насадки",
		approximatePriceRub: 3800,
		requiresLotTracking: false,
		aliases: ["O-Bite", "О-Байт", "Обайт", "DMG O-Bite"],
	},
	{
		id: "prostho_bite_blumousse",
		domain: "prostho_bite_reg",
		nameRu: "Blu-Mousse (Parkell, быстротвердеющий регистратор окклюзии)",
		brandName: "Blu-Mousse",
		manufacturer: "Parkell Inc.",
		country: "США",
		marketRank: 2,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Легендарный безусадочный силиконовый мусс с консистенцией вспененного крема, застывает до твердости гипса (Shore A 85) за 30 секунд.",
		clinicalIndicationsRu: "Прецизионная регистрация межокклюзионных контактов, сканирование в интраоральных сканерах.",
		defaultUnit: "картридж 50 мл",
		approximatePriceRub: 4200,
		requiresLotTracking: false,
		aliases: ["Blu-Mousse", "Блю Мусс", "Блюмусс", "Parkell"],
	},
	{
		id: "prostho_bite_futard",
		domain: "prostho_bite_reg",
		nameRu: "Futar D / Futar Fast (Kettenbach, Германия)",
		brandName: "Futar D",
		manufacturer: "Kettenbach Dental",
		country: "Германия",
		marketRank: 3,
		isMarketLeader: false,
		tier: "mainstream",
		descriptionRu: "Сверхтвердый эластомерный А-силиконовый материал для регистрации прикуса (Shore D 43), легко фрезеруется и обрезается скальпелем.",
		clinicalIndicationsRu: "Снятие окклюзионных оттисков, функциональная диагностика височно-нижнечелюстного сустава (ВНЧС).",
		defaultUnit: "картридж 50 мл",
		approximatePriceRub: 3600,
		requiresLotTracking: false,
		aliases: ["Futar D", "Футар Д", "Futar Fast", "Кеттенбах"],
	},

	// Цементы постоянной и временной фиксации
	{
		id: "prostho_cement_relyx_u200",
		domain: "prostho_cement_perm",
		nameRu: "RelyX U200 / Universal (3M Oral Care, самоадгезивный цемент)",
		brandName: "RelyX",
		manufacturer: "3M Oral Care",
		country: "США",
		marketRank: 1,
		isMarketLeader: true,
		tier: "premium",
		descriptionRu: "Мировой золотой стандарт: самоадгезивный композитный цемент двойного отверждения в дозаторе Automix.",
		clinicalIndicationsRu: "Фиксация коронок и мостовидных протезов из диоксида циркония (ZrO2), металлокерамики, стекловолоконных штифтов.",
		defaultUnit: "дозатор 8.5 г",
		approximatePriceRub: 9800,
		requiresLotTracking: true,
		aliases: ["RelyX U200", "RelyX Universal", "Реликс", "Реликс У200", "3M Цемент"],
	},
	{
		id: "prostho_cement_panavia",
		domain: "prostho_cement_perm",
		nameRu: "Panavia V5 / SA Cement Plus (Kuraray Noritake, Япония)",
		brandName: "Panavia",
		manufacturer: "Kuraray Noritake",
		country: "Япония",
		marketRank: 2,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Оригинальный патентованный MDP-мономер от создателей технологии, абсолютная химическая связь с диоксидом циркония и титаном.",
		clinicalIndicationsRu: "Адгезивная фиксация при дефиците ретенционной высоты культи зуба, адгезивные мосты, индивидуальные циркониевые абатменты.",
		defaultUnit: "шприц 8.1 г",
		approximatePriceRub: 10800,
		requiresLotTracking: true,
		aliases: ["Panavia V5", "Панавиа", "Panavia SA", "Kuraray"],
	},
	{
		id: "prostho_cement_speedcem",
		domain: "prostho_cement_perm",
		nameRu: "SpeedCEM Plus / Multilink Automix (Ivoclar Vivadent)",
		brandName: "SpeedCEM Plus",
		manufacturer: "Ivoclar Vivadent",
		country: "Лихтенштейн",
		marketRank: 3,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Самоадгезивный полимерный цемент с ускоренной фиксацией и легким удалением излишков после 1-секундного засвечивания.",
		clinicalIndicationsRu: "Фиксация цельнокерамических коронок из дисиликата лития (IPS e.max), оксида циркония и металлокерамики.",
		defaultUnit: "шприц 9 г",
		approximatePriceRub: 11500,
		requiresLotTracking: true,
		aliases: ["SpeedCEM Plus", "Multilink", "Спидцем", "Мультилинк", "Ivoclar"],
	},
	{
		id: "prostho_temp_tempbond",
		domain: "prostho_cement_temp",
		nameRu: "Temp-Bond NE (безэвгенольный, Kerr, США)",
		brandName: "Temp-Bond NE",
		manufacturer: "Kerr Dental",
		country: "США",
		marketRank: 4,
		isMarketLeader: true,
		tier: "mainstream",
		descriptionRu: "Самый популярный временный цемент на основе оксида цинка без эвгенола: не ингибирует полимеризацию постоянных композитных цементов.",
		clinicalIndicationsRu: "Временная фиксация коронок и мостов на срок от нескольких дней до месяцев, легкое снятие без сколов.",
		defaultUnit: "тюбик 50 г + 15 г",
		approximatePriceRub: 2900,
		requiresLotTracking: false,
		aliases: ["Temp-Bond", "Темп-Бонд", "TempBond NE", "Kerr"],
	},
	{
		id: "prostho_cement_fuji_plus",
		domain: "prostho_cement_perm",
		nameRu: "Fuji I / Fuji PLUS / Fuji CEM (GC, стеклоиономер, Япония)",
		brandName: "Fuji",
		manufacturer: "GC Corporation",
		country: "Япония",
		marketRank: 5,
		isMarketLeader: false,
		tier: "mainstream",
		descriptionRu: "Модифицированный полимерами стеклоиономерный цемент с пролонгированным выделением фтора и нулевой токсичностью для живой пульпы.",
		clinicalIndicationsRu: "Фиксация металлических и металлокерамических конструкций, культевых вкладок, моляров.",
		defaultUnit: "фл. 15 г + жидкость 7 мл",
		approximatePriceRub: 5200,
		requiresLotTracking: false,
		aliases: ["Fuji I", "Fuji Plus", "Fuji CEM", "Фуджи", "GC Fuji"],
	},
	{
		id: "prostho_temp_relyx_temp",
		domain: "prostho_cement_temp",
		nameRu: "RelyX Temp NE (безэвгенольный, 3M Oral Care)",
		brandName: "RelyX Temp NE",
		manufacturer: "3M Oral Care",
		country: "США",
		marketRank: 6,
		isMarketLeader: false,
		tier: "mainstream",
		descriptionRu: "Удобная паста-паста для временной фиксации, минимальная толщина пленки, легкое удаление излишков.",
		clinicalIndicationsRu: "Временные коронки из PMMA и композитов Protemp.",
		defaultUnit: "тюбик 36 г + 16 г",
		approximatePriceRub: 3400,
		requiresLotTracking: false,
		aliases: ["RelyX Temp", "Реликс Темп", "3M Temp NE"],
	},

	// Ретракционные нити
	{
		id: "prostho_cord_ultrapak",
		domain: "prostho_retraction",
		nameRu: "Ultrapack (Ultradent) #000, #00, #0, #1 (чистые и пропитанные)",
		brandName: "Ultrapack",
		manufacturer: "Ultradent Products",
		country: "США",
		marketRank: 1,
		isMarketLeader: true,
		tier: "premium",
		descriptionRu: "Вязаная из 100% хлопка нить с уникальным плетением цепочкой петель: превосходная компрессия и ретенция гемостатика.",
		clinicalIndicationsRu: "Механическая и химическая ретракция десневой борозды перед снятием оттисков и фиксацией виниров.",
		defaultUnit: "фл. с лезвием (244 см)",
		approximatePriceRub: 1650,
		requiresLotTracking: false,
		aliases: ["Ultrapack", "Ультрапак", "Ultradent", "Ретракционная нить"],
	},

	// Зуботехнические конструкции и CAD/CAM материалы
	{
		id: "lab_mat_zirconia_katana",
		domain: "lab_cad_material",
		nameRu: "Диоксид циркония многослойный (Katana STML/UTML, Kuraray / Upcera)",
		brandName: "Katana Zirconia / Upcera",
		manufacturer: "Kuraray Noritake / Upcera",
		country: "Япония / Китай",
		marketRank: 1,
		isMarketLeader: true,
		tier: "premium",
		descriptionRu: "Многослойный высокотранслюцентный диск ZrO2 (STML 750 МПа, UTML 550 МПа) с плавным градиентом цвета от шейки к режущему краю.",
		clinicalIndicationsRu: "Анатомические коронки и мосты во фронтальной и жевательной зонах, винтовая фиксация на имплантатах.",
		defaultUnit: "диск CAD/CAM Ø98 мм",
		approximatePriceRub: 14500,
		requiresLotTracking: true,
		aliases: ["Katana", "Катана", "Upcera", "Диоксид циркония", "STML", "UTML", "ZrO2"],
	},
	{
		id: "lab_mat_emax_cad_press",
		domain: "lab_cad_material",
		nameRu: "Дисиликат лития (IPS e.max CAD / Press, Ivoclar Vivadent)",
		brandName: "IPS e.max",
		manufacturer: "Ivoclar Vivadent",
		country: "Лихтенштейн",
		marketRank: 2,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Стеклокерамика на основе дисиликата лития прочностью 500 МПа: идеальная оптическая интеграция, флюоресценция и адгезивный потенциал.",
		clinicalIndicationsRu: "Эстетические виниры, вкладки Inlay/Onlay/Overlay, коронки во фронтальном отделе.",
		defaultUnit: "блок CAD / таблетка Press",
		approximatePriceRub: 7500,
		requiresLotTracking: true,
		aliases: ["e.max", "Емакс", "Имакс", "IPS e.max", "Дисиликат лития"],
	},
	{
		id: "lab_mat_cocr_nicr",
		domain: "lab_cad_material",
		nameRu: "Кобальт-хром / Никель-хром (КХС / НХС фрезерованный и литой)",
		brandName: "CoCr / NiCr КХС",
		manufacturer: "Bego / Scheftner / Duceram",
		country: "Германия",
		marketRank: 3,
		isMarketLeader: false,
		tier: "mainstream",
		descriptionRu: "Биосовместимый металлургический сплав CoCr без содержания никеля и бериллия для точного лазерного спекания (SLM) и фрезерования.",
		clinicalIndicationsRu: "Каркасы металлокерамических коронок и мостовидных протезов, литые культевые штифтовые вкладки, бюгели.",
		defaultUnit: "диск / слиток",
		approximatePriceRub: 3500,
		requiresLotTracking: false,
		aliases: ["КХС", "НХС", "Кобальт-хром", "CoCr", "Металлокерамика"],
	},
	{
		id: "lab_mat_pmma_cadcam",
		domain: "lab_cad_material",
		nameRu: "ПММА временные фрезерованные коронки (Telio CAD / Yamahachi PMMA)",
		brandName: "PMMA CAD/CAM",
		manufacturer: "Ivoclar / Yamahachi",
		country: "Германия / Япония",
		marketRank: 4,
		isMarketLeader: false,
		tier: "mainstream",
		descriptionRu: "Высокосшитый органический полиметилметакрилат (PMMA) заводской полимеризации: биоинертный, гипоаллергенный, прочный.",
		clinicalIndicationsRu: "Длительное временное ношение (до 12 мес), провизорные мосты при тотальной имплантации All-on-4/6.",
		defaultUnit: "диск Ø98 мм",
		approximatePriceRub: 4200,
		requiresLotTracking: false,
		aliases: ["PMMA", "ПММА", "Telio CAD", "Временная пластмасса"],
	},
	{
		id: "lab_mat_titanium_bars",
		domain: "lab_cad_material",
		nameRu: "Титановые балки и абатменты CAD/CAM (Ti-Base Grade 5)",
		brandName: "Titanium CAD/CAM",
		manufacturer: "Zirkonzahn / Medentika",
		country: "Италия / Германия",
		marketRank: 5,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Фрезерованные титановые каркасы и балки Дольдера/Хадера из медицинского титана Ti-6Al-4V ELI с шахтами винтов.",
		clinicalIndicationsRu: "Балочные условно-съемные протезы на имплантатах, индивидуальные титановые абатменты.",
		defaultUnit: "титановый диск / балка",
		approximatePriceRub: 18000,
		requiresLotTracking: true,
		aliases: ["Титановая балка", "Ti-Base", "Титан CAD/CAM", "Абатмент титановый"],
	},
];
