/**
 * prosthoMaterialsData.ts — Реестр ортопедических материалов
 * (оттискные массы, цементы постоянной и временной фиксации, ретракционные нити)
 * с охватом до 90% рынка РФ/СНГ (ранжирование строго по убыванию популярности).
 *
 * Mandate 8b: строго <= 800 строк
 * Mandate 8e: Doctor Autonomy (1 клик)
 * Mandate 8d: ноль мультяшных эмодзи
 * UTF-8 без BOM
 */

import type { ClinicalMarketMaterialItem } from "./implantAndBoneMaterialsData.js";

// ─────────────────────────────────────────────────────────────────────────────
// 5. ОРТОПЕДИЯ (Оттискные массы, цементы, ретракция)
// ─────────────────────────────────────────────────────────────────────────────
export const PROSTHODONTIC_MATERIALS_REGISTRY: readonly ClinicalMarketMaterialItem[] = [
	// А-силиконы
	{
		id: "prostho_asilicone_express",
		domain: "prostho_a_silicone",
		nameRu: "Express XT / Imprint 4 (3M Oral Care, А-силикон)",
		brandName: "Express XT / Imprint 4",
		manufacturer: "3M Oral Care",
		country: "США",
		marketRank: 1,
		isMarketLeader: true,
		tier: "premium",
		descriptionRu: "Премиальная винилполисилоксановая оттискная масса с активным саморазогревом и сверхвысокой гидрофильностью во влажной среде.",
		clinicalIndicationsRu: "Прецизионные двухслойные оттиски под цельнокерамические коронки, виниры и балочные конструкции.",
		defaultUnit: "база (2x300 мл) + картридж (50 мл)",
		approximatePriceRub: 9800,
		requiresLotTracking: false,
		aliases: ["Express XT", "Imprint 4", "3M А-силикон", "Импринт"],
	},
	{
		id: "prostho_asilicone_elite_hd",
		domain: "prostho_a_silicone",
		nameRu: "Elite HD+ Putty Soft / Light Body (Zhermack, Италия)",
		brandName: "Elite HD+",
		manufacturer: "Zhermack",
		country: "Италия",
		marketRank: 2,
		isMarketLeader: false,
		tier: "mainstream",
		descriptionRu: "Самый распространенный А-силикон в стоматологиях РФ: оптимальное соотношение цены, эластичности и размерной стабильности.",
		clinicalIndicationsRu: "Одномоментные и двухэтапные двухслойные слепки под металлокерамику, вкладки и бюгельные протезы.",
		defaultUnit: "база (2x250 мл) + картридж (50 мл)",
		approximatePriceRub: 5900,
		requiresLotTracking: false,
		aliases: ["Elite HD+", "Элит ХД", "Zhermack А-силикон", "Элит"],
	},
	{
		id: "prostho_asilicone_variotime",
		domain: "prostho_a_silicone",
		nameRu: "Variotime Dynamix / Light Flow (Kulzer, Германия)",
		brandName: "Variotime",
		manufacturer: "Kulzer",
		country: "Германия",
		marketRank: 3,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Инновационная концепция вариабельного времени схватывания (от 1:00 до 2:30 мин), адаптация под темп работы врача.",
		clinicalIndicationsRu: "Протяженные мостовидные протезы и тотальные реабилитации на зубах и имплантатах.",
		defaultUnit: "набор",
		approximatePriceRub: 7500,
		requiresLotTracking: false,
		aliases: ["Variotime", "Вариотайм", "Kulzer"],
	},
	{
		id: "prostho_asilicone_honigum",
		domain: "prostho_a_silicone",
		nameRu: "Honigum Pro Putty / Light (DMG, Германия)",
		brandName: "Honigum",
		manufacturer: "DMG Dental",
		country: "Германия",
		marketRank: 4,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Микрокристаллическая матрица реологического контроля: уникальная текучесть под давлением без капельного стекания с зуба.",
		clinicalIndicationsRu: "Субгингивальные уступы, сверхточные слепки при множественном препарировании.",
		defaultUnit: "набор",
		approximatePriceRub: 8200,
		requiresLotTracking: false,
		aliases: ["Honigum", "Хонигум", "DMG"],
	},

	// С-силиконы
	{
		id: "prostho_csilicone_zetaplus",
		domain: "prostho_c_silicone",
		nameRu: "Zetaplus / Oranwash L (Zhermack, С-силикон)",
		brandName: "Zetaplus",
		manufacturer: "Zhermack",
		country: "Италия",
		marketRank: 1,
		isMarketLeader: true,
		tier: "budget",
		descriptionRu: "Абсолютный лидер рынка С-силиконов в РФ/СНГ: классический слепочный полисилоксан с мятным вкусом и катализатором Indurent Gel.",
		clinicalIndicationsRu: "Предварительные слепки, диагностические модели, временные коронки, прикусные шаблоны.",
		defaultUnit: "банка 900 мл + туба 140 мл + гель",
		approximatePriceRub: 3200,
		requiresLotTracking: false,
		aliases: ["Zetaplus", "Зетаплюс", "Оранвош", "Oranwash", "Зета"],
	},
	{
		id: "prostho_csilicone_speedex",
		domain: "prostho_c_silicone",
		nameRu: "Speedex Putty / Light Body (Coltene, Швейцария)",
		brandName: "Speedex",
		manufacturer: "Coltene",
		country: "Швейцария",
		marketRank: 2,
		isMarketLeader: false,
		tier: "budget",
		descriptionRu: "С-силикон с усадкой, близкой к А-силиконам (патентованная технология поверхностного натяжения Coltene).",
		clinicalIndicationsRu: "Точные оттиски для мостовидных протезов и коронок в бюджетном протоколе.",
		defaultUnit: "набор",
		approximatePriceRub: 3900,
		requiresLotTracking: false,
		aliases: ["Speedex", "Спидекс", "Coltene"],
	},

	// Цементы постоянной фиксации
	{
		id: "prostho_cement_relyx_u200",
		domain: "prostho_cement_perm",
		nameRu: "RelyX U200 / Ultimate (3M Oral Care, композитный цемент)",
		brandName: "RelyX",
		manufacturer: "3M Oral Care",
		country: "США",
		marketRank: 1,
		isMarketLeader: true,
		tier: "premium",
		descriptionRu: "Мировой золотой стандарт: самоадгезивный композитный цемент двойного отверждения в дозаторе Automix.",
		clinicalIndicationsRu: "Фиксация коронок и мостовидных протезов из диоксида циркония (ZrO2), металлокерамики, стекловолоконных штифтов.",
		defaultUnit: "дозатор 8.5 г",
		approximatePriceRub: 9800,
		requiresLotTracking: true,
		aliases: ["RelyX U200", "RelyX Ultimate", "Реликс", "Реликс У200", "3M Цемент"],
	},
	{
		id: "prostho_cement_fuji_plus",
		domain: "prostho_cement_perm",
		nameRu: "Fuji I / Fuji PLUS / Fuji CEM (GC, стеклоиономер)",
		brandName: "Fuji",
		manufacturer: "GC Corporation",
		country: "Япония",
		marketRank: 2,
		isMarketLeader: false,
		tier: "mainstream",
		descriptionRu: "Модифицированный полимерами стеклоиономерный цемент с пролонгированным выделением фтора и нулевой токсичностью для пульпы.",
		clinicalIndicationsRu: "Фиксация металлических и металлокерамических конструкций, культевых вкладок, моляров.",
		defaultUnit: "фл. 15 г + жидкость 7 мл",
		approximatePriceRub: 5200,
		requiresLotTracking: false,
		aliases: ["Fuji I", "Fuji Plus", "Fuji CEM", "Фуджи", "GC Fuji"],
	},
	{
		id: "prostho_cement_multilink",
		domain: "prostho_cement_perm",
		nameRu: "Multilink Automix / SpeedCEM Plus (Ivoclar Vivadent)",
		brandName: "Multilink",
		manufacturer: "Ivoclar Vivadent",
		country: "Лихтенштейн",
		marketRank: 3,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Универсальная адгезивная система фиксации для стеклокерамики на основе дисиликата лития (IPS e.max).",
		clinicalIndicationsRu: "Фиксация цельнокерамических виниров, вкладок Inlay/Onlay и циркониевых абатментов.",
		defaultUnit: "шприц 9 г",
		approximatePriceRub: 11500,
		requiresLotTracking: true,
		aliases: ["Multilink", "SpeedCEM Plus", "Мультилинк", "Спидцем", "Ivoclar"],
	},
	{
		id: "prostho_cement_panavia",
		domain: "prostho_cement_perm",
		nameRu: "Panavia V5 / SA Cement Plus (Kuraray, Япония)",
		brandName: "Panavia",
		manufacturer: "Kuraray Noritake",
		country: "Япония",
		marketRank: 4,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Оригинальный MDP-мономер от создателей технологии, абсолютная химическая связь с диоксидом циркония и металлами.",
		clinicalIndicationsRu: "Адгезивная фиксация при дефиците ретенционной высоты культи зуба, адгезивные мосты.",
		defaultUnit: "шприц 8.1 г",
		approximatePriceRub: 10800,
		requiresLotTracking: true,
		aliases: ["Panavia V5", "Панавиа", "Panavia SA", "Kuraray"],
	},

	// Временные цементы
	{
		id: "prostho_temp_tempbond",
		domain: "prostho_cement_temp",
		nameRu: "Temp-Bond NE (безэвгенольный, Kerr, США)",
		brandName: "Temp-Bond NE",
		manufacturer: "Kerr Dental",
		country: "США",
		marketRank: 1,
		isMarketLeader: true,
		tier: "mainstream",
		descriptionRu: "Самый популярный временный цемент на основе оксида цинка без эвгенола: не ингибирует полимеризацию постоянных композитов.",
		clinicalIndicationsRu: "Временная фиксация коронок и мостов на срок от нескольких дней до месяцев, легкое снятие без сколов.",
		defaultUnit: "тюбик 50 г + 15 г",
		approximatePriceRub: 2900,
		requiresLotTracking: false,
		aliases: ["Temp-Bond", "Темп-Бонд", "TempBond NE", "Kerr"],
	},
	{
		id: "prostho_temp_relyx_temp",
		domain: "prostho_cement_temp",
		nameRu: "RelyX Temp NE (безэвгенольный, 3M Oral Care)",
		brandName: "RelyX Temp NE",
		manufacturer: "3M Oral Care",
		country: "США",
		marketRank: 2,
		isMarketLeader: false,
		tier: "mainstream",
		descriptionRu: "Удобная паста-паста для временной фиксации, минимальная толщина пленки, легкое удаление излишков.",
		clinicalIndicationsRu: "Временные коронки из PMMA и композитов Protemp.",
		defaultUnit: "тюбик 36 г + 16 г",
		approximatePriceRub: 3400,
		requiresLotTracking: false,
		aliases: ["RelyX Temp", "Реликс Темп", "3M Temp NE"],
	},

	// Ретракционные нити
	{
		id: "prostho_cord_ultrapak",
		domain: "prostho_retraction",
		nameRu: "Ultrapack (Ultradent) #000, #00, #0, #1 (чистые и пропитанные)",
		brandName: "Ultrapack",
		manufacturer: "Ultradent Products",
		country: "США",
		marketRank: 1,
		isMarketLeader: true,
		tier: "premium",
		descriptionRu: "Вязаная из 100% хлопка нить с уникальным плетением цепочкой петель: превосходная компрессия и ретенция гемостатика.",
		clinicalIndicationsRu: "Механическая и химическая ретракция десневой борозды перед снятием оттисков и фиксацией виниров.",
		defaultUnit: "фл. с лезвием (244 см)",
		approximatePriceRub: 1650,
		requiresLotTracking: false,
		aliases: ["Ultrapack", "Ультрапак", "Ultradent", "Ретракционная нить"],
	},
];
