/**
 * surgerySutureAndHemostaticsData.ts — Реестр хирургических шовных материалов и гемостатиков
 * с охватом до 90%+ рынка РФ/СНГ (ранжирование строго по убыванию популярности).
 *
 * Mandate 8b: строго <= 800 строк
 * Mandate 8e: Doctor Autonomy (1 клик)
 * Mandate 8d: ноль мультяшных эмодзи
 * UTF-8 без BOM
 */

import type { ClinicalMarketMaterialItem } from "./implantAndBoneMaterialsData.js";

export const SURGICAL_SUTURE_REGISTRY: readonly ClinicalMarketMaterialItem[] = [
	{
		id: "surg_suture_vicryl",
		domain: "surg_suture",
		nameRu: "Vicryl (Ethicon, полиглактин 910, USP 3-0, 4-0, 5-0)",
		brandName: "Vicryl",
		manufacturer: "Ethicon (Johnson & Johnson)",
		country: "США",
		marketRank: 1,
		isMarketLeader: true,
		tier: "premium",
		descriptionRu: "Плетеный синтетический рассасывающийся шовный материал с покрытием из полиглактина 370 и стеарата кальция. Срок поддержки раны 28–35 дней.",
		clinicalIndicationsRu: "Ушивание слизисто-надкостничных лоскутов после удаления зубов, резекций, синус-лифтинга и пластики десны.",
		defaultUnit: "шт.",
		approximatePriceRub: 580,
		requiresLotTracking: true,
		aliases: ["Vicryl", "Викрил", "Ethicon Vicryl", "Викрил 4-0", "Викрил 5-0"],
	},
	{
		id: "surg_suture_prolene",
		domain: "surg_suture",
		nameRu: "Prolene (Ethicon, полипропилен монофиламент, USP 4-0, 5-0, 6-0)",
		brandName: "Prolene",
		manufacturer: "Ethicon (Johnson & Johnson)",
		country: "США",
		marketRank: 2,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Нерассасывающийся монофиламентный полипропиленовый шовный материал с предельно гладкой поверхностью. Нулевая фиксация бактериального налета.",
		clinicalIndicationsRu: "Фиксация трансплантатов соединительной ткани, имплантология, пародонтологическая пластическая микрохирургия.",
		defaultUnit: "шт.",
		approximatePriceRub: 650,
		requiresLotTracking: true,
		aliases: ["Prolene", "Пролен", "Ethicon Prolene", "Пролен 5-0", "Пролен 6-0"],
	},
	{
		id: "surg_suture_monocryl",
		domain: "surg_suture",
		nameRu: "Monocryl (Ethicon, полиглекапрон 25, монофиламент, USP 4-0, 5-0)",
		brandName: "Monocryl",
		manufacturer: "Ethicon (Johnson & Johnson)",
		country: "США",
		marketRank: 3,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Рассасывающийся монофиламентный шовный материал с высокой начальной прочностью и минимальной тканевой реактивностью. Полная резорбция за 90–120 дней.",
		clinicalIndicationsRu: "Ушивание разрезов в эстетически значимой зоне, лоскутные операции без воспалительного отека краев раны.",
		defaultUnit: "шт.",
		approximatePriceRub: 690,
		requiresLotTracking: true,
		aliases: ["Monocryl", "Монокрил", "Ethicon Monocryl", "Монокрил 4-0"],
	},
	{
		id: "surg_suture_ptfe",
		domain: "surg_suture",
		nameRu: "Cytoplast PTFE Suture (Osteogenics, политетрафторэтилен, USP 3-0, 4-0)",
		brandName: "Cytoplast PTFE",
		manufacturer: "Osteogenics Biomedical",
		country: "США",
		marketRank: 4,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "100% медицинский микропористый PTFE: абсолютно биологически инертный, полное отсутствие фитильного эффекта, мягкий для языка и щек.",
		clinicalIndicationsRu: "Костная аугментация (НКР), синус-лифтинг, фиксация коллагеновых и титановых мембран.",
		defaultUnit: "шт.",
		approximatePriceRub: 1200,
		requiresLotTracking: true,
		aliases: ["Cytoplast Suture", "PTFE шовный", "Цитопласт нить", "ПТФЭ"],
	},
	{
		id: "surg_suture_pga_resorba",
		domain: "surg_suture",
		nameRu: "PGA Resorba / ПГА (полигликолид плетеный, USP 3-0, 4-0, 5-0)",
		brandName: "PGA Resorba",
		manufacturer: "Resorba / МедТехника",
		country: "Германия / Россия",
		marketRank: 5,
		isMarketLeader: false,
		tier: "mainstream",
		descriptionRu: "Синтетический плетеный рассасывающийся полигликолидный шовный материал с прецизионной атравматической иглой.",
		clinicalIndicationsRu: "Рутинные хирургические вмешательства, сложное удаление зубов мудрости, цистэктомия, периостотомия.",
		defaultUnit: "шт.",
		approximatePriceRub: 350,
		requiresLotTracking: true,
		aliases: ["PGA Resorba", "Резорба", "ПГА", "ПГА 4-0", "Полигликолид"],
	},
];

export const SURGICAL_HEMOSTATICS_REGISTRY: readonly ClinicalMarketMaterialItem[] = [
	{
		id: "surg_hemo_spongostan",
		domain: "surg_hemostatic",
		nameRu: "Спонгостан (Spongostan Standard / Dental, Ethicon)",
		brandName: "Spongostan",
		manufacturer: "Ethicon (Johnson & Johnson)",
		country: "США",
		marketRank: 1,
		isMarketLeader: true,
		tier: "premium",
		descriptionRu: "Абсорбируемая желатиновая губка с высокой пористостью, удерживает объем крови в 45 раз превышающий собственный вес. Полное рассасывание за 4–6 недель.",
		clinicalIndicationsRu: "Остановка венозного и капиллярного кровотечения из костных полостей и лунок удаленных зубов.",
		defaultUnit: "кубик (10x10x10 мм)",
		approximatePriceRub: 320,
		requiresLotTracking: false,
		aliases: ["Spongostan", "Спонгостан", "Желатиновая губка Ethicon"],
	},
	{
		id: "surg_hemo_surgicel",
		domain: "surg_hemostatic",
		nameRu: "Серджисел (Surgicel Original / Fibrillar, Ethicon)",
		brandName: "Surgicel",
		manufacturer: "Ethicon (Johnson & Johnson)",
		country: "США",
		marketRank: 2,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Окисленная регенерированная целлюлоза: мгновенный гемостаз при контакте с кровью плюс доказанный бактерицидный эффект против грамположительных и грамотрицательных бактерий.",
		clinicalIndicationsRu: "Диффузные костные и мягкотканные кровотечения при сложных хирургических операциях, пациенты на антикоагулянтах.",
		defaultUnit: "пластина",
		approximatePriceRub: 1450,
		requiresLotTracking: false,
		aliases: ["Surgicel", "Серджисел", "Серджисель", "Окисленная целлюлоза"],
	},
	{
		id: "surg_hemo_alvogyl",
		domain: "surg_hemostatic",
		nameRu: "Альвожил (Alveogyl / Alvogyl, Septodont)",
		brandName: "Alvogyl",
		manufacturer: "Septodont",
		country: "Франция",
		marketRank: 3,
		isMarketLeader: false,
		tier: "mainstream",
		descriptionRu: "Антисептическая и гемостатическая волокнистая паста с экстрактом пенгхавара, эвгенолом и лаурилсульфатом натрия. Оказывает выраженное анальгезирующее действие.",
		clinicalIndicationsRu: "Профилактика и лечение сухого альвеолита после сложного удаления зуба, гемостаз лунки.",
		defaultUnit: "банка 10 г",
		approximatePriceRub: 2800,
		requiresLotTracking: false,
		aliases: ["Alvogyl", "Альвожил", "Альвеожил", "Septodont Alvogyl"],
	},
	{
		id: "surg_hemo_capramin",
		domain: "surg_hemostatic",
		nameRu: "Капрамин (гемостатическая жидкость, ВладМиВа)",
		brandName: "Капрамин",
		manufacturer: "ВладМиВа",
		country: "Россия",
		marketRank: 4,
		isMarketLeader: false,
		tier: "budget",
		descriptionRu: "Водный раствор хлористого алюминия и центимониум бромида для мгновенной коагуляции мелких сосудов без окрашивания твердых тканей зуба.",
		clinicalIndicationsRu: "Остановка капиллярного кровотечения из десневого края при препарировании, снятии оттисков и кюретаже.",
		defaultUnit: "фл. 30 мл",
		approximatePriceRub: 290,
		requiresLotTracking: false,
		aliases: ["Капрамин", "Capramin", "Гемостатик ВладМиВа"],
	},
];
