/**
 * therapyMaterialsData.ts — Реестр терапевтических композитов и адгезивных систем
 * с охватом до 90%+ рынка РФ/СНГ (ранжирование строго по убыванию популярности).
 *
 * Mandate 8b: строго <= 800 строк
 * Mandate 8e: Doctor Autonomy (1 клик)
 * Mandate 8d: ноль мультяшных эмодзи
 * UTF-8 без BOM
 */

import type { ClinicalMarketMaterialItem } from "./implantAndBoneMaterialsData.js";

export const THERAPY_COMPOSITES_REGISTRY: readonly ClinicalMarketMaterialItem[] = [
	{
		id: "comp_filtek_ultimate",
		domain: "therapy_composite",
		nameRu: "Filtek Ultimate / Z250 (3M Oral Care, США)",
		brandName: "Filtek Ultimate",
		manufacturer: "3M Oral Care",
		country: "США",
		marketRank: 1,
		isMarketLeader: true,
		tier: "premium",
		descriptionRu: "Истинный нанокластерный композит с непревзойденной полируемостью и сохранением блеска. Доступен в 4 опаковостях (Dentina, Body, Enamel, Translucent).",
		clinicalIndicationsRu: "Высокоэстетичные прямые реставрации фронтальных и жевательных зубов (I–VI классы по Блэку).",
		defaultUnit: "шприц 4 г",
		approximatePriceRub: 3800,
		requiresLotTracking: false,
		aliases: ["Filtek", "Филтек", "Filtek Ultimate", "Filtek Z250", "3M Filtek"],
	},
	{
		id: "comp_estelite_asteria",
		domain: "therapy_composite",
		nameRu: "Estelite Asteria / Sigma Quick (Tokuyama Dental, Япония)",
		brandName: "Estelite Asteria",
		manufacturer: "Tokuyama Dental",
		country: "Япония",
		marketRank: 2,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Субмикронный сферический наполнитель 82% по весу с патентованной технологией ускоренной фотополимеризации RAP и эффектом оптического хамелеона.",
		clinicalIndicationsRu: "Упрощенная стратификация слоев (Body + Enamel) во фронтальном отделе, невидимая граница реставрации.",
		defaultUnit: "шприц 4 г",
		approximatePriceRub: 4200,
		requiresLotTracking: false,
		aliases: ["Estelite", "Эстелайт", "Estelite Asteria", "Sigma Quick", "Токуяма"],
	},
	{
		id: "comp_harmonize",
		domain: "therapy_composite",
		nameRu: "Harmonize (Kerr, США)",
		brandName: "Harmonize",
		manufacturer: "Kerr Dental",
		country: "США",
		marketRank: 3,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Универсальный композит с технологией адаптивного отклика (Adaptive Response Technology): непревзойденная моделируемость без прилипания к гладилке.",
		clinicalIndicationsRu: "Анатомическое моделирование жевательных бугров, реставрация полостей II и IV классов.",
		defaultUnit: "шприц 4 г",
		approximatePriceRub: 3900,
		requiresLotTracking: false,
		aliases: ["Harmonize", "Гармонайз", "Kerr Harmonize"],
	},
	{
		id: "comp_gradia_direct",
		domain: "therapy_composite",
		nameRu: "Gradia Direct (GC Corporation, Япония)",
		brandName: "Gradia Direct",
		manufacturer: "GC Corporation",
		country: "Япония",
		marketRank: 4,
		isMarketLeader: false,
		tier: "mainstream",
		descriptionRu: "Микрогибридный композитный материал с естественной опалесценцией, адаптирован под оптические свойства дентина и эмали.",
		clinicalIndicationsRu: "Широкий выбор оттенков для реставрации некариозных поражений и клиновидных дефектов.",
		defaultUnit: "шприц 4 г",
		approximatePriceRub: 3200,
		requiresLotTracking: false,
		aliases: ["Gradia Direct", "Градиа", "GC Gradia"],
	},
	{
		id: "comp_sdr_plus",
		domain: "therapy_composite",
		nameRu: "SDR Plus Flowable Bulk Fill (Dentsply Sirona)",
		brandName: "SDR Plus",
		manufacturer: "Dentsply Sirona",
		country: "Германия",
		marketRank: 5,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Текучий базовый композит технологии Bulk Fill: самовыравнивание, полимеризация слоем до 4 мм с минимальным стрессом усадки.",
		clinicalIndicationsRu: "Адаптивный базовый слой полостей I и II классов, перекрытие устьев после эндодонтии.",
		defaultUnit: "шприц 1 г / унидозы",
		approximatePriceRub: 2900,
		requiresLotTracking: false,
		aliases: ["SDR", "SDR Plus", "СДР", "Балк филл"],
	},
	{
		id: "comp_beautifil_flow",
		domain: "therapy_composite",
		nameRu: "Beautifil Flow Plus F00 / F03 (Shofu, Япония)",
		brandName: "Beautifil",
		manufacturer: "Shofu Inc.",
		country: "Япония",
		marketRank: 6,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Биоактивный инжектируемый гиомер Giomer с эффектом длительного выделения и перезарядки ионами фтора, устойчив к окклюзионным нагрузкам.",
		clinicalIndicationsRu: "Клиновидные дефекты, пришеечный кариес V класса, детская стоматология, защита от вторичного кариеса.",
		defaultUnit: "шприц 2.2 г",
		approximatePriceRub: 3100,
		requiresLotTracking: false,
		aliases: ["Beautifil", "Бьютифил", "Shofu", "Гиомер"],
	},
	{
		id: "comp_ceramx_spectra",
		domain: "therapy_composite",
		nameRu: "Ceram.x Spectra ST (Dentsply Sirona)",
		brandName: "Ceram.x Spectra",
		manufacturer: "Dentsply Sirona",
		country: "Германия",
		marketRank: 7,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Нанокерамический композит с технологией наполнителя SphereTEC: легко моделируется, быстрая полировка до зеркального блеска.",
		clinicalIndicationsRu: "Прямые реставрации жевательных и передних зубов по системе Cloud shades (5 оттенков перекрывают всю шкалу VITA).",
		defaultUnit: "шприц 3 г",
		approximatePriceRub: 3600,
		requiresLotTracking: false,
		aliases: ["Ceram.x", "CeramX", "Церам Икс", "Spectra ST"],
	},
	{
		id: "comp_charisma",
		domain: "therapy_composite",
		nameRu: "Charisma Classic / Diamond (Kulzer, Германия)",
		brandName: "Charisma",
		manufacturer: "Kulzer",
		country: "Германия",
		marketRank: 8,
		isMarketLeader: false,
		tier: "mainstream",
		descriptionRu: "Классический микрогибридный композит субмикронного размера с наполнителем из бариевого стекла Microglass.",
		clinicalIndicationsRu: "Бюджетные надежные терапевтические реставрации, шинирование подвижных зубов.",
		defaultUnit: "шприц 4 г",
		approximatePriceRub: 2100,
		requiresLotTracking: false,
		aliases: ["Charisma", "Харизма", "Каризма", "Kulzer Charisma"],
	},
];

export const THERAPY_ADHESIVES_REGISTRY: readonly ClinicalMarketMaterialItem[] = [
	{
		id: "adh_optibond_fl",
		domain: "therapy_adhesive",
		nameRu: "OptiBond FL (Kerr, 4-е поколение, золотой стандарт)",
		brandName: "OptiBond FL",
		manufacturer: "Kerr Dental",
		country: "США",
		marketRank: 1,
		isMarketLeader: true,
		tier: "premium",
		descriptionRu: "Мировой золотой стандарт адгезии: 2-бутылочная система тотального протравливания (Total-Etch) с 48% наполненным бондом.",
		clinicalIndicationsRu: "Прямые композитные реставрации с абсолютной силой сцепления с эмалью (>30 МПа) и дентином, нулевая постоперационная чувствительность.",
		defaultUnit: "праймер 8 мл + адгезив 8 мл",
		approximatePriceRub: 9400,
		requiresLotTracking: false,
		aliases: ["OptiBond FL", "Оптибонд ФЛ", "Оптибонд", "Kerr OptiBond"],
	},
	{
		id: "adh_single_bond_2",
		domain: "therapy_adhesive",
		nameRu: "Single Bond 2 / Scotchbond 1 XT (3M Oral Care, 5-е поколение)",
		brandName: "Single Bond 2",
		manufacturer: "3M Oral Care",
		country: "США",
		marketRank: 2,
		isMarketLeader: false,
		tier: "mainstream",
		descriptionRu: "Самый массовый однобутылочный адгезив тотального протравливания с нанонаполнителем (5 нм) на этанол-водной основе.",
		clinicalIndicationsRu: "Прямые композитные пломбы, фиксация непрямых реставраций в сочетании с композитными цементами.",
		defaultUnit: "фл. 6 мл",
		approximatePriceRub: 4200,
		requiresLotTracking: false,
		aliases: ["Single Bond 2", "Сингл Бонд 2", "Scotchbond 1 XT", "3M Single Bond"],
	},
	{
		id: "adh_clearfil_se_bond",
		domain: "therapy_adhesive",
		nameRu: "Clearfil SE Bond (Kuraray Noritake, 6-е поколение, Япония)",
		brandName: "Clearfil SE Bond",
		manufacturer: "Kuraray Noritake",
		country: "Япония",
		marketRank: 3,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Оригинальный двухшаговый самопротравливающий адгезив с патентованным мономером 10-MDP: стабильная химическая связь с гидроксиапатитом без травления дентина.",
		clinicalIndicationsRu: "Полное исключение постоперационной чувствительности, глубокие полости близко к пульпе.",
		defaultUnit: "праймер 6 мл + бонд 5 мл",
		approximatePriceRub: 8800,
		requiresLotTracking: false,
		aliases: ["Clearfil SE Bond", "Клеарфил", "Клирфил", "10-MDP бонд"],
	},
	{
		id: "adh_optibond_universal",
		domain: "therapy_adhesive",
		nameRu: "OptiBond Universal (Kerr, 8-е поколение)",
		brandName: "OptiBond Universal",
		manufacturer: "Kerr Dental",
		country: "США",
		marketRank: 4,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Универсальный однокомпонентный адгезив с мономером GPDM: селективное, само- или тотальное протравливание одним флаконом.",
		clinicalIndicationsRu: "Прямые и непрямые реставрации, починка керамики и металлокерамики без отдельного праймера.",
		defaultUnit: "фл. 5 мл",
		approximatePriceRub: 5600,
		requiresLotTracking: false,
		aliases: ["OptiBond Universal", "Оптибонд Универсал"],
	},
	{
		id: "adh_single_bond_universal",
		domain: "therapy_adhesive",
		nameRu: "Single Bond Universal (3M Oral Care, 8-е поколение)",
		brandName: "Single Bond Universal",
		manufacturer: "3M Oral Care",
		country: "США",
		marketRank: 5,
		isMarketLeader: false,
		tier: "premium",
		descriptionRu: "Универсальный адгезив с мономером MDP и силаном в одном флаконе: связывается с эмалью, дентином, цирконием и стеклокерамикой.",
		clinicalIndicationsRu: "Универсальный протокол в 1 клик, фиксация стекловолоконных штифтов, адгезивная фиксация коронок.",
		defaultUnit: "фл. 5 мл",
		approximatePriceRub: 5900,
		requiresLotTracking: false,
		aliases: ["Single Bond Universal", "Сингл Бонд Универсал", "3M Universal"],
	},
];
