/**
 * sensorModelsCatalog.ts — Layer 0: Канонический реестр моделей дентальных сенсоров (30+ моделей мировых брендов).
 *
 * Implements Mandates 8e, 8s, 8p.
 */

import type { UniversalSensorModel } from "./types";

/**
 * Canonical Multi-Vendor RVG Sensor Catalog (30+ models covering all world brands).
 */
export const UNIVERSAL_SENSOR_CATALOG: readonly UniversalSensorModel[] = [
	// ─── VATECH ───
	{
		id: "vatech_ezsensor",
		name: "Vatech EzSensor",
		brand: "vatech",
		brandName: "Vatech",
		resolution: "25.0 lp/mm (35.0 мкм)",
		pixelSpacing: 0.035,
		pixelSpacingMicrons: 35.0,
		opticalResolutionLpMm: 25.0,
		dimensions: "1920x1440",
		bitDepth: 14,
		sensorSize: "Size 1.5",
		activeAreaMm: "24x33 mm",
		technology: "CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\EzSensor\\Capture",
	},
	{
		id: "vatech_ezsensor_classic",
		name: "Vatech EzSensor Classic",
		brand: "vatech",
		brandName: "Vatech",
		resolution: "25.0 lp/mm (35.0 мкм)",
		pixelSpacing: 0.035,
		pixelSpacingMicrons: 35.0,
		opticalResolutionLpMm: 25.0,
		dimensions: "1920x1440",
		bitDepth: 14,
		sensorSize: "Size 1.5",
		activeAreaMm: "24x33 mm",
		technology: "CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\EzSensor\\Capture",
	},
	{
		id: "vatech_ezsensor_soft",
		name: "Vatech EzSensor Soft",
		brand: "vatech",
		brandName: "Vatech",
		resolution: "29.2 lp/mm (29.0 мкм)",
		pixelSpacing: 0.029,
		pixelSpacingMicrons: 29.0,
		opticalResolutionLpMm: 29.2,
		dimensions: "1920x1440",
		bitDepth: 14,
		sensorSize: "Size 1.5",
		activeAreaMm: "24x33 mm",
		technology: "CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\EzDent-i\\Capture",
	},
	{
		id: "vatech_ezsensor_hd",
		name: "Vatech EzSensor HD",
		brand: "vatech",
		brandName: "Vatech",
		resolution: "29.2 lp/mm (35.0 мкм)",
		pixelSpacing: 0.035,
		pixelSpacingMicrons: 35.0,
		opticalResolutionLpMm: 29.2,
		dimensions: "1920x1440",
		bitDepth: 14,
		sensorSize: "Size 1.5",
		activeAreaMm: "24x33 mm",
		technology: "CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\EzDent-i\\Capture",
	},
	{
		id: "vatech_ezsensor_hd_hires",
		name: "Vatech EzSensor HD Hi-Res (14.8 мкм)",
		brand: "vatech",
		brandName: "Vatech",
		resolution: "33.7 lp/mm (14.8 мкм)",
		pixelSpacing: 0.0148,
		pixelSpacingMicrons: 14.8,
		opticalResolutionLpMm: 33.7,
		dimensions: "1920x1440",
		bitDepth: 14,
		sensorSize: "Size 1.5",
		activeAreaMm: "24x33 mm",
		technology: "CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\EzDent-i\\Capture",
	},
	{
		id: "vatech_ezsensor_1_5",
		name: "Vatech EzSensor 1.5",
		brand: "vatech",
		brandName: "Vatech",
		resolution: "29.2 lp/mm (35.0 мкм)",
		pixelSpacing: 0.035,
		pixelSpacingMicrons: 35.0,
		opticalResolutionLpMm: 29.2,
		dimensions: "1920x1440",
		bitDepth: 14,
		sensorSize: "Size 1.5",
		activeAreaMm: "24x33 mm",
		technology: "CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\EzSensor\\Capture",
	},
	{
		id: "vatech_ezsensor_2_0",
		name: "Vatech EzSensor 2.0",
		brand: "vatech",
		brandName: "Vatech",
		resolution: "29.2 lp/mm (35.0 мкм)",
		pixelSpacing: 0.035,
		pixelSpacingMicrons: 35.0,
		opticalResolutionLpMm: 29.2,
		dimensions: "1920x1440",
		bitDepth: 14,
		sensorSize: "Size 2",
		activeAreaMm: "26x36 mm",
		technology: "CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\EzSensor\\Capture",
	},

	// ─── CARESTREAM / KODAK ───
	{
		id: "carestream_rvg_5100",
		name: "Carestream RVG 5100",
		brand: "carestream",
		brandName: "Carestream / Kodak",
		resolution: "14.0 lp/mm (19.0 мкм)",
		pixelSpacing: 0.019,
		pixelSpacingMicrons: 19.0,
		opticalResolutionLpMm: 14.0,
		dimensions: "1600x1200",
		bitDepth: 12,
		sensorSize: "Size 1",
		activeAreaMm: "22x30 mm",
		technology: "CCD",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\Carestream\\Capture",
	},
	{
		id: "carestream_rvg_5200",
		name: "Carestream RVG 5200",
		brand: "carestream",
		brandName: "Carestream / Kodak",
		resolution: "16.0 lp/mm (19.0 мкм)",
		pixelSpacing: 0.019,
		pixelSpacingMicrons: 19.0,
		opticalResolutionLpMm: 16.0,
		dimensions: "1600x1200",
		bitDepth: 14,
		sensorSize: "Size 1",
		activeAreaMm: "22x30 mm",
		technology: "CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\Carestream\\Capture",
	},
	{
		id: "carestream_rvg_6100",
		name: "Carestream / Kodak RVG 6100",
		brand: "carestream",
		brandName: "Carestream / Kodak",
		resolution: ">20.0 lp/mm (18.5 мкм)",
		pixelSpacing: 0.0185,
		pixelSpacingMicrons: 18.5,
		opticalResolutionLpMm: 20.0,
		dimensions: "1840x1380",
		bitDepth: 14,
		sensorSize: "Size 1.5",
		activeAreaMm: "24x34 mm",
		technology: "Fiber-Optic CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\KDIS\\Capture",
	},
	{
		id: "carestream_rvg_6200",
		name: "Carestream RVG 6200",
		brand: "carestream",
		brandName: "Carestream / Kodak",
		resolution: "24.0 lp/mm (19.0 мкм)",
		pixelSpacing: 0.019,
		pixelSpacingMicrons: 19.0,
		opticalResolutionLpMm: 24.0,
		dimensions: "1920x1440",
		bitDepth: 14,
		sensorSize: "Size 2",
		activeAreaMm: "26x36 mm",
		technology: "Fiber-Optic CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\Carestream\\Capture",
	},
	{
		id: "carestream_rvg_6500",
		name: "Carestream RVG 6500 Wireless",
		brand: "carestream",
		brandName: "Carestream / Kodak",
		resolution: ">20.0 lp/mm (18.5 мкм)",
		pixelSpacing: 0.0185,
		pixelSpacingMicrons: 18.5,
		opticalResolutionLpMm: 20.0,
		dimensions: "1920x1440",
		bitDepth: 14,
		sensorSize: "Size 1.5",
		activeAreaMm: "24x34 mm",
		technology: "Fiber-Optic CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\Carestream\\Capture",
	},

	// ─── PLANMECA ───
	{
		id: "planmeca_prosensor",
		name: "Planmeca ProSensor",
		brand: "planmeca",
		brandName: "Planmeca",
		resolution: "17.0 lp/mm (30.0 мкм)",
		pixelSpacing: 0.03,
		pixelSpacingMicrons: 30.0,
		opticalResolutionLpMm: 17.0,
		dimensions: "1600x1200",
		bitDepth: 14,
		sensorSize: "Size 1",
		activeAreaMm: "24x30 mm",
		technology: "CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\Planmeca\\Temp",
	},
	{
		id: "planmeca_prosensor_hd",
		name: "Planmeca ProSensor HD",
		brand: "planmeca",
		brandName: "Planmeca",
		resolution: "33.7 lp/mm (15.0 мкм)",
		pixelSpacing: 0.015,
		pixelSpacingMicrons: 15.0,
		opticalResolutionLpMm: 33.7,
		dimensions: "2000x1500",
		bitDepth: 16,
		sensorSize: "Size 2",
		activeAreaMm: "26x36 mm",
		technology: "Fiber-Optic CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\Planmeca\\Temp",
	},

	// ─── DENTSPLY SIRONA / SCHICK ───
	{
		id: "sirona_xios_xg",
		name: "Dentsply Sirona Xios XG",
		brand: "sirona",
		brandName: "Dentsply Sirona",
		resolution: "16.7 lp/mm (30.0 мкм)",
		pixelSpacing: 0.03,
		pixelSpacingMicrons: 30.0,
		opticalResolutionLpMm: 16.7,
		dimensions: "1600x1200",
		bitDepth: 14,
		sensorSize: "Size 1",
		activeAreaMm: "20x30 mm",
		technology: "CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\Sidexis\\Export",
	},
	{
		id: "sirona_xios_plus",
		name: "Dentsply Sirona Xios Plus",
		brand: "sirona",
		brandName: "Dentsply Sirona",
		resolution: "20.0 lp/mm (25.0 мкм)",
		pixelSpacing: 0.025,
		pixelSpacingMicrons: 25.0,
		opticalResolutionLpMm: 20.0,
		dimensions: "1600x1200",
		bitDepth: 14,
		sensorSize: "Size 1.5",
		activeAreaMm: "24x33 mm",
		technology: "CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\Sidexis\\Export",
	},
	{
		id: "sirona_xios_supreme",
		name: "Dentsply Sirona Xios Supreme",
		brand: "sirona",
		brandName: "Dentsply Sirona",
		resolution: "33.3 lp/mm (15.0 мкм)",
		pixelSpacing: 0.015,
		pixelSpacingMicrons: 15.0,
		opticalResolutionLpMm: 33.3,
		dimensions: "2048x1536",
		bitDepth: 16,
		sensorSize: "Size 2",
		activeAreaMm: "26x36 mm",
		technology: "Fiber-Optic CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\Sidexis\\Export",
	},
	{
		id: "schick_33",
		name: "Schick 33",
		brand: "sirona",
		brandName: "Schick",
		resolution: "33.3 lp/mm (15.0 мкм)",
		pixelSpacing: 0.015,
		pixelSpacingMicrons: 15.0,
		opticalResolutionLpMm: 33.3,
		dimensions: "2048x1536",
		bitDepth: 16,
		sensorSize: "Size 2",
		activeAreaMm: "26x36 mm",
		technology: "CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\Sidexis\\Export",
	},
	{
		id: "schick_elite",
		name: "Schick Elite",
		brand: "sirona",
		brandName: "Schick",
		resolution: "25.0 lp/mm (20.0 мкм)",
		pixelSpacing: 0.02,
		pixelSpacingMicrons: 20.0,
		opticalResolutionLpMm: 25.0,
		dimensions: "1680x1260",
		bitDepth: 14,
		sensorSize: "Size 1.5",
		activeAreaMm: "24x33 mm",
		technology: "CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\Sidexis\\Export",
	},

	// ─── DEXIS ───
	{
		id: "dexis_titanium",
		name: "Dexis Titanium",
		brand: "dexis",
		brandName: "Dexis",
		resolution: "25.0 lp/mm (20.0 мкм)",
		pixelSpacing: 0.02,
		pixelSpacingMicrons: 20.0,
		opticalResolutionLpMm: 25.0,
		dimensions: "1800x1350",
		bitDepth: 16,
		sensorSize: "Size 2",
		activeAreaMm: "26x34 mm",
		technology: "CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\Dexis\\Data",
	},
	{
		id: "dexis_platinum",
		name: "Dexis Platinum",
		brand: "dexis",
		brandName: "Dexis",
		resolution: "20.0 lp/mm (20.0 мкм)",
		pixelSpacing: 0.02,
		pixelSpacingMicrons: 20.0,
		opticalResolutionLpMm: 20.0,
		dimensions: "1800x1350",
		bitDepth: 14,
		sensorSize: "Size 1.5",
		activeAreaMm: "24x32 mm",
		technology: "CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\Dexis\\Data",
	},

	// ─── ACTEON / SOPRO ───
	{
		id: "acteon_sopix",
		name: "Acteon / Sopro Sopix",
		brand: "acteon",
		brandName: "Acteon / Sopro",
		resolution: "22.7 lp/mm (22.0 мкм)",
		pixelSpacing: 0.022,
		pixelSpacingMicrons: 22.0,
		opticalResolutionLpMm: 22.7,
		dimensions: "1700x1275",
		bitDepth: 12,
		sensorSize: "Size 1",
		activeAreaMm: "20x30 mm",
		technology: "CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\Sopro\\Capture",
	},
	{
		id: "acteon_sopix2",
		name: "Acteon / Sopro Sopix2 (ACE)",
		brand: "acteon",
		brandName: "Acteon / Sopro",
		resolution: "25.0 lp/mm (22.0 мкм)",
		pixelSpacing: 0.022,
		pixelSpacingMicrons: 22.0,
		opticalResolutionLpMm: 25.0,
		dimensions: "1700x1275",
		bitDepth: 14,
		sensorSize: "Size 1.5",
		activeAreaMm: "24x33 mm",
		technology: "CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\Sopro\\Capture",
	},
	{
		id: "acteon_pspix",
		name: "Acteon PSPIX (PSP Scanner)",
		brand: "acteon",
		brandName: "Acteon / Sopro",
		resolution: "20.0 lp/mm (25.0 мкм)",
		pixelSpacing: 0.025,
		pixelSpacingMicrons: 25.0,
		opticalResolutionLpMm: 20.0,
		dimensions: "1600x1200",
		bitDepth: 16,
		sensorSize: "PSP Plate",
		activeAreaMm: "31x41 mm",
		technology: "PSP Storage Phosphor",
		isDirectUsbSupported: false,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\PSPIX\\Export",
	},

	// ─── WOODPECKER / DTE ───
	{
		id: "woodpecker_isensor_h1",
		name: "Woodpecker i-Sensor H1",
		brand: "woodpecker",
		brandName: "Woodpecker / DTE",
		resolution: "25.0 lp/mm (20.0 мкм)",
		pixelSpacing: 0.02,
		pixelSpacingMicrons: 20.0,
		opticalResolutionLpMm: 25.0,
		dimensions: "1500x1000",
		bitDepth: 16,
		sensorSize: "Size 1",
		activeAreaMm: "20x30 mm",
		technology: "CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\i-Sensor\\Images",
	},
	{
		id: "woodpecker_isensor_h2",
		name: "Woodpecker i-Sensor H2",
		brand: "woodpecker",
		brandName: "Woodpecker / DTE",
		resolution: "25.0 lp/mm (20.0 мкм)",
		pixelSpacing: 0.02,
		pixelSpacingMicrons: 20.0,
		opticalResolutionLpMm: 25.0,
		dimensions: "1900x1300",
		bitDepth: 16,
		sensorSize: "Size 2",
		activeAreaMm: "26x36 mm",
		technology: "CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\i-Sensor\\Images",
	},
	{
		id: "woodpecker_rvg",
		name: "Woodpecker RVG / DTE Sensor",
		brand: "woodpecker",
		brandName: "Woodpecker / DTE",
		resolution: "25.0 lp/mm (20.0 мкм)",
		pixelSpacing: 0.02,
		pixelSpacingMicrons: 20.0,
		opticalResolutionLpMm: 25.0,
		dimensions: "1500x1000",
		bitDepth: 16,
		sensorSize: "Size 1",
		activeAreaMm: "20x30 mm",
		technology: "CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\i-Sensor\\Images",
	},

	// ─── HANDY DENTAL ───
	{
		id: "handy_hdr_500",
		name: "Handy HDR-500",
		brand: "handy",
		brandName: "Handy Dental",
		resolution: "26.3 lp/mm (19.0 мкм)",
		pixelSpacing: 0.019,
		pixelSpacingMicrons: 19.0,
		opticalResolutionLpMm: 26.3,
		dimensions: "1500x1050",
		bitDepth: 14,
		sensorSize: "Size 1",
		activeAreaMm: "20x30 mm",
		technology: "CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\Handy\\Capture",
	},
	{
		id: "handy_hdr_600",
		name: "Handy HDR-600",
		brand: "handy",
		brandName: "Handy Dental",
		resolution: "26.3 lp/mm (19.0 мкм)",
		pixelSpacing: 0.019,
		pixelSpacingMicrons: 19.0,
		opticalResolutionLpMm: 26.3,
		dimensions: "1900x1300",
		bitDepth: 14,
		sensorSize: "Size 2",
		activeAreaMm: "26x36 mm",
		technology: "CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\Handy\\Capture",
	},

	// ─── KAVO / GENDEX ───
	{
		id: "kavo_gxs_700",
		name: "KaVo Gendex GXS-700",
		brand: "kavo",
		brandName: "KaVo Dental",
		resolution: "25.6 lp/mm (19.5 мкм)",
		pixelSpacing: 0.0195,
		pixelSpacingMicrons: 19.5,
		opticalResolutionLpMm: 25.6,
		dimensions: "1800x1350",
		bitDepth: 14,
		sensorSize: "Size 1.5",
		activeAreaMm: "25x31 mm",
		technology: "CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\KaVo\\Export",
	},

	// ─── FONA ───
	{
		id: "fona_cdr",
		name: "FONA CDR",
		brand: "fona",
		brandName: "FONA Dental",
		resolution: "25.0 lp/mm (20.0 мкм)",
		pixelSpacing: 0.02,
		pixelSpacingMicrons: 20.0,
		opticalResolutionLpMm: 25.0,
		dimensions: "1600x1200",
		bitDepth: 12,
		sensorSize: "Size 1",
		activeAreaMm: "20x30 mm",
		technology: "CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\Fona\\Capture",
	},
	{
		id: "fona_stellaris",
		name: "FONA Stellaris",
		brand: "fona",
		brandName: "FONA Dental",
		resolution: "28.0 lp/mm (17.8 мкм)",
		pixelSpacing: 0.0178,
		pixelSpacingMicrons: 17.8,
		opticalResolutionLpMm: 28.0,
		dimensions: "1800x1350",
		bitDepth: 14,
		sensorSize: "Size 1.5",
		activeAreaMm: "24x33 mm",
		technology: "CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\Fona\\Capture",
	},
	{
		id: "fona_cdrelite",
		name: "FONA CDRelite / Schick",
		brand: "fona",
		brandName: "FONA Dental",
		resolution: "28.0 lp/mm (17.8 мкм)",
		pixelSpacing: 0.0178,
		pixelSpacingMicrons: 17.8,
		opticalResolutionLpMm: 28.0,
		dimensions: "1800x1350",
		bitDepth: 14,
		sensorSize: "Size 1.5",
		activeAreaMm: "24x33 mm",
		technology: "CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\Fona\\Capture",
	},

	// ─── MYRAY ───
	{
		id: "myray_zen_x",
		name: "MyRay Zen-X",
		brand: "myray",
		brandName: "MyRay",
		resolution: "25.0 lp/mm (20.0 мкм)",
		pixelSpacing: 0.02,
		pixelSpacingMicrons: 20.0,
		opticalResolutionLpMm: 25.0,
		dimensions: "1700x1250",
		bitDepth: 14,
		sensorSize: "Size 1.5",
		activeAreaMm: "24x32 mm",
		technology: "CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\iRYS\\Export",
	},

	// ─── OWANDY ───
	{
		id: "owandy_opteo",
		name: "Owandy Opteo",
		brand: "owandy",
		brandName: "Owandy Radiology",
		resolution: "25.0 lp/mm (20.0 мкм)",
		pixelSpacing: 0.02,
		pixelSpacingMicrons: 20.0,
		opticalResolutionLpMm: 25.0,
		dimensions: "1700x1300",
		bitDepth: 14,
		sensorSize: "Size 1.5",
		activeAreaMm: "24x32 mm",
		technology: "CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\Owandy\\QuickVision\\Images",
	},
	{
		id: "owandy_one",
		name: "Owandy One",
		brand: "owandy",
		brandName: "Owandy Radiology",
		resolution: "22.0 lp/mm (22.7 мкм)",
		pixelSpacing: 0.0227,
		pixelSpacingMicrons: 22.7,
		opticalResolutionLpMm: 22.0,
		dimensions: "1600x1200",
		bitDepth: 14,
		sensorSize: "Size 1",
		activeAreaMm: "20x30 mm",
		technology: "CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\Owandy\\QuickVision\\Images",
	},

	// ─── EIGHTEETH ───
	{
		id: "eighteeth_nanopix_1",
		name: "Eighteeth NanoPix 1",
		brand: "eighteeth",
		brandName: "Eighteeth",
		resolution: "25.0 lp/mm (20.0 мкм)",
		pixelSpacing: 0.02,
		pixelSpacingMicrons: 20.0,
		opticalResolutionLpMm: 25.0,
		dimensions: "1500x1000",
		bitDepth: 16,
		sensorSize: "Size 1",
		activeAreaMm: "20x30 mm",
		technology: "CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\NanoPix\\Incoming",
	},
	{
		id: "eighteeth_nanopix_2",
		name: "Eighteeth NanoPix 2",
		brand: "eighteeth",
		brandName: "Eighteeth",
		resolution: "25.0 lp/mm (20.0 мкм)",
		pixelSpacing: 0.02,
		pixelSpacingMicrons: 20.0,
		opticalResolutionLpMm: 25.0,
		dimensions: "1900x1300",
		bitDepth: 16,
		sensorSize: "Size 2",
		activeAreaMm: "26x36 mm",
		technology: "CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\NanoPix\\Incoming",
	},

	// ─── XPECT VISION ───
	{
		id: "xpect_vision_photon",
		name: "Xpect Vision Photon-Counting",
		brand: "xpect_vision",
		brandName: "Xpect Vision",
		resolution: "33.0 lp/mm (15.0 мкм)",
		pixelSpacing: 0.015,
		pixelSpacingMicrons: 15.0,
		opticalResolutionLpMm: 33.0,
		dimensions: "2048x1536",
		bitDepth: 16,
		sensorSize: "Size 2",
		activeAreaMm: "26x36 mm",
		technology: "Photon-Counting",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\XpectVision\\Scans",
	},

	// ─── DÜRR DENTAL ───
	{
		id: "duerr_vistaray_7_size1",
		name: "Dürr Dental VistaRay 7 Size 1",
		brand: "duerr",
		brandName: "Dürr Dental",
		resolution: "26.3 lp/mm (19.0 мкм)",
		pixelSpacing: 0.019,
		pixelSpacingMicrons: 19.0,
		opticalResolutionLpMm: 26.3,
		dimensions: "1580x1050",
		bitDepth: 14,
		sensorSize: "Size 1",
		activeAreaMm: "20x30 mm",
		technology: "CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\VistaSoft\\Capture",
	},
	{
		id: "duerr_vistaray_7_size2",
		name: "Dürr Dental VistaRay 7 Size 2",
		brand: "duerr",
		brandName: "Dürr Dental",
		resolution: "26.3 lp/mm (19.0 мкм)",
		pixelSpacing: 0.019,
		pixelSpacingMicrons: 19.0,
		opticalResolutionLpMm: 26.3,
		dimensions: "1896x1368",
		bitDepth: 14,
		sensorSize: "Size 2",
		activeAreaMm: "26x36 mm",
		technology: "CMOS",
		isDirectUsbSupported: true,
		isTwainSupported: true,
		recommendedHotFolder: "C:\\VistaSoft\\Capture",
	},
];
