// Re-export all schema modules
export * from "./_common.js";
export * from "./auth.js";
export * from "./patients.js";
export * from "./schedule.js";
export * from "./billing.js";
export * from "./clinical.js";
export * from "./imaging.js";
export * from "./inventory.js";
export * from "./communications.js";
export * from "./system.js";
export * from "./sanpin.js";
export * from "./sync.js";
export * from "./copilot.js";
export * from "./rag.js";
export * from "./aiTelemetry.js";
export * from "./documents_v2.js";
export * from "./outpatientCore.js";
export * from "./finance_v2.js";
