import React, { useCallback, useEffect, useState } from "react";
import { Check, RefreshCw } from "lucide-react";
import { showToast } from "../../../GlobalToast";
import { getDenteAuthHeaders } from "../../../../lib/denteRequestHeaders";
import type { TelegramQrData } from "./types";

export interface QrAuthCardProps {
	clinicId?: string;
	userId?: string;
	onSuccess: () => Promise<void> | void;
}

export function QrAuthCard({
	clinicId,
	userId,
	onSuccess,
}: QrAuthCardProps) {
	const [qrData, setQrData] = useState<TelegramQrData | null>(null);
	const [isRequestingQr, setIsRequestingQr] = useState<boolean>(false);
	const [isConfirmingQr, setIsConfirmingQr] = useState<boolean>(false);

	const handleRequestQr = useCallback(async () => {
		try {
			setIsRequestingQr(true);
			const res = await fetch("/api/telegram/account/request-qr", {
				method: "POST",
				headers: getDenteAuthHeaders({ "Content-Type": "application/json" }),
				body: JSON.stringify({ clinicId, userId }),
			});

			const data = await res.json();
			if (res.ok && data.ok) {
				setQrData({
					token: data.token,
					svg: data.qrSvg || data.svg,
					expiresAt: data.expiresAt,
				});
			} else {
				showToast(data.error || "Не удалось сгенерировать QR-код", "error");
			}
		} catch (err) {
			showToast(`Ошибка сети: ${String(err)}`, "error");
		} finally {
			setIsRequestingQr(false);
		}
	}, [clinicId, userId]);

	const handleConfirmQr = async () => {
		if (!qrData?.token) {
			showToast("Сначала сгенерируйте QR-код", "warning");
			return;
		}

		try {
			setIsConfirmingQr(true);
			const res = await fetch("/api/telegram/account/confirm-qr", {
				method: "POST",
				headers: getDenteAuthHeaders({ "Content-Type": "application/json" }),
				body: JSON.stringify({
					token: qrData.token,
					clinicId,
					userId,
				}),
			});

			const data = await res.json();
			if (res.ok && data.ok && data.connected) {
				showToast("Вход по QR-коду успешно подтвержден!", "success");
				setQrData(null);
				await onSuccess();
			} else {
				showToast(data.error || "Ожидание сканирования QR-кода...", "info");
			}
		} catch (err) {
			showToast(`Ошибка сети: ${String(err)}`, "error");
		} finally {
			setIsConfirmingQr(false);
		}
	};

	useEffect(() => {
		if (!qrData && !isRequestingQr) {
			handleRequestQr();
		}
	}, [qrData, isRequestingQr, handleRequestQr]);

	return (
		<div className="tg-qr-layout">
			{/* Окно QR-кода */}
			<div className="tg-qr-box">
				<div className="tg-qr-white-card">
					{qrData?.svg ? (
						<div
							// biome-ignore lint/security/noDangerouslySetInnerHtml: safe SVG string generated by backend
							dangerouslySetInnerHTML={{ __html: qrData.svg }}
							style={{ width: "100%", height: "100%" }}
						/>
					) : (
						<div
							style={{
								display: "flex",
								flexDirection: "column",
								alignItems: "center",
								gap: "8px",
								color: "var(--muted)",
								fontSize: "13px",
							}}
						>
							<RefreshCw size={24} className="animate-spin" />
							<span>Генерация QR...</span>
						</div>
					)}
				</div>

				<div
					style={{
						display: "flex",
						gap: "8px",
						width: "100%",
						justifyContent: "center",
					}}
				>
					<button
						type="button"
						className="tg-btn-secondary"
						style={{
							minHeight: "36px",
							padding: "6px 12px",
							fontSize: "12px",
						}}
						onClick={handleRequestQr}
						disabled={isRequestingQr}
					>
						<RefreshCw
							size={12}
							className={isRequestingQr ? "animate-spin" : ""}
						/>
						<span>Обновить QR-код</span>
					</button>
					<button
						type="button"
						className="tg-btn-primary"
						style={{
							minHeight: "36px",
							padding: "6px 14px",
							fontSize: "12px",
						}}
						onClick={handleConfirmQr}
						disabled={isConfirmingQr}
					>
						<Check size={12} />
						<span>Я отсканировал</span>
					</button>
				</div>
			</div>

			{/* Инструкции по сканированию */}
			<div
				style={{
					display: "flex",
					flexDirection: "column",
					gap: "14px",
				}}
			>
				<div
					style={{
						fontWeight: 700,
						fontSize: "16px",
						color: "var(--ink)",
					}}
				>
					Быстрый вход через мобильное приложение Telegram
				</div>
				<div
					style={{
						display: "flex",
						flexDirection: "column",
						gap: "10px",
					}}
				>
					<div className="tg-guide-step">
						<div className="tg-step-badge">1</div>
						<div className="tg-step-text">
							Откройте <strong>Telegram</strong> на смартфоне.
						</div>
					</div>
					<div className="tg-guide-step">
						<div className="tg-step-badge">2</div>
						<div className="tg-step-text">
							Перейдите в <strong>Настройки → Устройства</strong> (или
							«Устройства и сеансы»).
						</div>
					</div>
					<div className="tg-guide-step">
						<div className="tg-step-badge">3</div>
						<div className="tg-step-text">
							Нажмите <strong>«Подключить устройство»</strong> и
							наведите камеру на QR-код слева.
						</div>
					</div>
				</div>

				<div
					style={{
						fontSize: "12px",
						color: "var(--muted)",
						background: "var(--paper-soft)",
						padding: "10px 14px",
						borderRadius: "8px",
						border: "1px solid var(--line)",
					}}
				>
					Сессия сохраняется в защищенном хранилище и используется
					только для разрешенных клинических сообщений.
				</div>
			</div>
		</div>
	);
}
