import type { StomxOutpatientTemplateMetadata } from "./stomtOutpatientCatalog.js";

/**
 * StomX Templates Metadata Part 2
 */
export const STOMX_TEMPLATES_PART_2: readonly StomxOutpatientTemplateMetadata[] =
	[
		{
			id: 76,
			categoryId: 8,
			name: "Вывих зуба",
			categoryName: "Жалобы",
			specialty: "surgery",
			mkbCode: "K08.1",
			order: 76,
		},
		{
			id: 77,
			categoryId: 8,
			name: "Имплантация 1",
			categoryName: "Жалобы",
			specialty: "surgery",
			mkbCode: "K08.1",
			order: 77,
		},
		{
			id: 78,
			categoryId: 8,
			name: "Имплантация 2",
			categoryName: "Жалобы",
			specialty: "surgery",
			mkbCode: "K08.1",
			order: 78,
		},
		{
			id: 79,
			categoryId: 8,
			name: "Острый гнойный одонтогенный остеомиелит",
			categoryName: "Жалобы",
			specialty: "surgery",
			mkbCode: "K08.1",
			order: 79,
		},
		{
			id: 80,
			categoryId: 9,
			name: "Кариес поверхностный",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K02",
			order: 80,
		},
		{
			id: 81,
			categoryId: 9,
			name: "Кариес средний 1",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K02",
			order: 81,
		},
		{
			id: 82,
			categoryId: 9,
			name: "Кариес средний 2",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K02",
			order: 82,
		},
		{
			id: 83,
			categoryId: 9,
			name: "Кариес глубокий",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K02",
			order: 83,
		},
		{
			id: 84,
			categoryId: 9,
			name: "Пульпит острый очаговый",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 84,
		},
		{
			id: 85,
			categoryId: 9,
			name: "Пульпит острый диффузный 1",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 85,
		},
		{
			id: 86,
			categoryId: 9,
			name: "Пульпит острый диффузный 2",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 86,
		},
		{
			id: 87,
			categoryId: 9,
			name: "Пульпит хронический фиброзный",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 87,
		},
		{
			id: 88,
			categoryId: 9,
			name: "Пульпит хронический гангренозный 1",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 88,
		},
		{
			id: 89,
			categoryId: 9,
			name: "Пульпит хронический гангренозный 2",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 89,
		},
		{
			id: 90,
			categoryId: 9,
			name: "Пульпит хронический гипертрофический",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 90,
		},
		{
			id: 91,
			categoryId: 9,
			name: "Обострение хронического пульпита",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 91,
		},
		{
			id: 92,
			categoryId: 9,
			name: "Состояние после частичного удаления пульпы",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K08.1",
			order: 92,
		},
		{
			id: 93,
			categoryId: 9,
			name: "Состояние после полного удаления пульпы",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K08.1",
			order: 93,
		},
		{
			id: 94,
			categoryId: 9,
			name: "Периодонтит острый 1",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K04.7",
			order: 94,
		},
		{
			id: 95,
			categoryId: 9,
			name: "Периодонтит острый 2",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K04.7",
			order: 95,
		},
		{
			id: 96,
			categoryId: 9,
			name: "Периодонтит хронический фиброзный",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K04.7",
			order: 96,
		},
		{
			id: 97,
			categoryId: 9,
			name: "Периодонтит хронический гранулирующий",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K04.7",
			order: 97,
		},
		{
			id: 98,
			categoryId: 9,
			name: "Периодонтит хронический гранулематозный",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K04.7",
			order: 98,
		},
		{
			id: 99,
			categoryId: 9,
			name: "Радикулярная киста",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K04.8",
			order: 99,
		},
		{
			id: 100,
			categoryId: 9,
			name: "Гингивит хронический катаральный",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K05.1",
			order: 100,
		},
		{
			id: 101,
			categoryId: 9,
			name: "Гингивит язвенно – некротический",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K05.1",
			order: 101,
		},
		{
			id: 102,
			categoryId: 9,
			name: "Гингивит хронический гипертрофический 1",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K05.1",
			order: 102,
		},
		{
			id: 103,
			categoryId: 9,
			name: "Гингивит хронический гипертрофический 2",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K05.1",
			order: 103,
		},
		{
			id: 104,
			categoryId: 9,
			name: "Пародонтит хронический генерализованный легкой ст.",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K05.3",
			order: 104,
		},
		{
			id: 105,
			categoryId: 9,
			name: "Пародонтит хронический генерализованный средней ст.",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K05.3",
			order: 105,
		},
		{
			id: 106,
			categoryId: 9,
			name: "Пародонтит хронический генерализованный тяжелой ст.",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K05.3",
			order: 106,
		},
		{
			id: 107,
			categoryId: 9,
			name: "Парадонтоз",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K02",
			order: 107,
		},
		{
			id: 108,
			categoryId: 9,
			name: "Обострение генерализованного пародонтита. Абсцесс.",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K12.2",
			order: 108,
		},
		{
			id: 109,
			categoryId: 9,
			name: "Кандидоз",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K02",
			order: 109,
		},
		{
			id: 110,
			categoryId: 9,
			name: "Травматическая язва",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K02",
			order: 110,
		},
		{
			id: 111,
			categoryId: 9,
			name: "Хронический рецидивирующий герпес",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K02",
			order: 111,
		},
		{
			id: 112,
			categoryId: 9,
			name: "Хронический рецидивирующий афтозный стоматит",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K02",
			order: 112,
		},
		{
			id: 113,
			categoryId: 9,
			name: "Плоский лишай",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K02",
			order: 113,
		},
		{
			id: 114,
			categoryId: 9,
			name: "Многоформная эксудативная эритема",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K02",
			order: 114,
		},
		{
			id: 115,
			categoryId: 9,
			name: "Клиновидный дефект 1",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K03.1",
			order: 115,
		},
		{
			id: 116,
			categoryId: 9,
			name: "Клиновидный дефект 2",
			categoryName: "Развитие заболевания",
			specialty: "therapy",
			mkbCode: "K03.1",
			order: 116,
		},
		{
			id: 117,
			categoryId: 10,
			name: "Развитие заболевания 1",
			categoryName: "Развитие заболевания",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 117,
		},
		{
			id: 118,
			categoryId: 10,
			name: "Развитие заболевания 2",
			categoryName: "Развитие заболевания",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 118,
		},
		{
			id: 119,
			categoryId: 10,
			name: "Развитие заболевания 3",
			categoryName: "Развитие заболевания",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 119,
		},
		{
			id: 120,
			categoryId: 10,
			name: "Развитие заболевания 4",
			categoryName: "Развитие заболевания",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 120,
		},
		{
			id: 121,
			categoryId: 10,
			name: "Развитие заболевания 5",
			categoryName: "Развитие заболевания",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 121,
		},
		{
			id: 122,
			categoryId: 10,
			name: "Развитие заболевания 6",
			categoryName: "Развитие заболевания",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 122,
		},
		{
			id: 123,
			categoryId: 11,
			name: "Обострение хронического периодонтита",
			categoryName: "Развитие заболевания",
			specialty: "surgery",
			mkbCode: "K04.7",
			order: 123,
		},
		{
			id: 124,
			categoryId: 11,
			name: "Острый гнойный периостит верхней челюсти",
			categoryName: "Развитие заболевания",
			specialty: "surgery",
			mkbCode: "K10.2",
			order: 124,
		},
		{
			id: 125,
			categoryId: 11,
			name: "Острый гнойный периодонтит",
			categoryName: "Развитие заболевания",
			specialty: "surgery",
			mkbCode: "K04.7",
			order: 125,
		},
		{
			id: 126,
			categoryId: 11,
			name: "Острый гнойный периостит нижней челюсти",
			categoryName: "Развитие заболевания",
			specialty: "surgery",
			mkbCode: "K10.2",
			order: 126,
		},
		{
			id: 127,
			categoryId: 11,
			name: "Небный абсцесс",
			categoryName: "Развитие заболевания",
			specialty: "surgery",
			mkbCode: "K12.2",
			order: 127,
		},
		{
			id: 128,
			categoryId: 11,
			name: "Острый гнойный одонтогенный остеомиелит",
			categoryName: "Развитие заболевания",
			specialty: "surgery",
			mkbCode: "K08.1",
			order: 128,
		},
		{
			id: 129,
			categoryId: 11,
			name: "Одонтогенная кистогранулема",
			categoryName: "Развитие заболевания",
			specialty: "surgery",
			mkbCode: "K04.8",
			order: 129,
		},
		{
			id: 130,
			categoryId: 11,
			name: "Полуретенция и дистопия зубов",
			categoryName: "Развитие заболевания",
			specialty: "surgery",
			mkbCode: "K08.1",
			order: 130,
		},
		{
			id: 131,
			categoryId: 11,
			name: "Перикоронорит",
			categoryName: "Развитие заболевания",
			specialty: "surgery",
			mkbCode: "K05.2",
			order: 131,
		},
		{
			id: 132,
			categoryId: 11,
			name: "Ретанционная киста малой слюнной железы",
			categoryName: "Развитие заболевания",
			specialty: "surgery",
			mkbCode: "K04.8",
			order: 132,
		},
		{
			id: 133,
			categoryId: 11,
			name: "Папилома, Фиброма и др.новообразования языка языка",
			categoryName: "Развитие заболевания",
			specialty: "surgery",
			mkbCode: "K08.1",
			order: 133,
		},
		{
			id: 134,
			categoryId: 11,
			name: "Эпулис",
			categoryName: "Развитие заболевания",
			specialty: "surgery",
			mkbCode: "K08.1",
			order: 134,
		},
		{
			id: 135,
			categoryId: 11,
			name: "Радикулярная киста",
			categoryName: "Развитие заболевания",
			specialty: "surgery",
			mkbCode: "K04.8",
			order: 135,
		},
		{
			id: 136,
			categoryId: 11,
			name: "Альвеолит",
			categoryName: "Развитие заболевания",
			specialty: "surgery",
			mkbCode: "K10.3",
			order: 136,
		},
		{
			id: 137,
			categoryId: 11,
			name: "Слюннокаменая болезнь поднижнечелюстного протока",
			categoryName: "Развитие заболевания",
			specialty: "surgery",
			mkbCode: "K08.1",
			order: 137,
		},
		{
			id: 138,
			categoryId: 11,
			name: "Абсцесс челюстно-язычного желобка",
			categoryName: "Развитие заболевания",
			specialty: "surgery",
			mkbCode: "K12.2",
			order: 138,
		},
		{
			id: 139,
			categoryId: 11,
			name: "Абсцесс щечной области",
			categoryName: "Развитие заболевания",
			specialty: "surgery",
			mkbCode: "K12.2",
			order: 139,
		},
		{
			id: 140,
			categoryId: 11,
			name: "Абсцесс крыловидно-нижнечелюстного пространства",
			categoryName: "Развитие заболевания",
			specialty: "surgery",
			mkbCode: "K12.2",
			order: 140,
		},
		{
			id: 141,
			categoryId: 11,
			name: "Вывих зуба",
			categoryName: "Развитие заболевания",
			specialty: "surgery",
			mkbCode: "K08.1",
			order: 141,
		},
		{
			id: 142,
			categoryId: 11,
			name: "Имплантация",
			categoryName: "Развитие заболевания",
			specialty: "surgery",
			mkbCode: "K08.1",
			order: 142,
		},
		{
			id: 143,
			categoryId: 11,
			name: "Эпулис",
			categoryName: "Развитие заболевания",
			specialty: "surgery",
			mkbCode: "K08.1",
			order: 143,
		},
		{
			id: 144,
			categoryId: 13,
			name: "Кариес",
			categoryName: "Описание",
			specialty: "therapy",
			mkbCode: "K02",
			order: 144,
		},
		{
			id: 145,
			categoryId: 13,
			name: "Пульпит",
			categoryName: "Описание",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 145,
		},
		{
			id: 146,
			categoryId: 13,
			name: "Вторичный кариес",
			categoryName: "Описание",
			specialty: "therapy",
			mkbCode: "K02",
			order: 146,
		},
		{
			id: 147,
			categoryId: 14,
			name: "Кариес",
			categoryName: "Заключение",
			specialty: "therapy",
			mkbCode: "K02",
			order: 147,
		},
		{
			id: 148,
			categoryId: 14,
			name: "Пульпит",
			categoryName: "Заключение",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 148,
		},
		{
			id: 149,
			categoryId: 14,
			name: "Периодонтит",
			categoryName: "Заключение",
			specialty: "therapy",
			mkbCode: "K04.7",
			order: 149,
		},
		{
			id: 150,
			categoryId: 14,
			name: "Пародонтит",
			categoryName: "Заключение",
			specialty: "periodontics",
			mkbCode: "K05.3",
			order: 150,
		},
	];
