import type { StomxOutpatientTemplateMetadata } from "./stomtOutpatientCatalog.js";

/**
 * StomX Templates Metadata Part 5
 */
export const STOMX_TEMPLATES_PART_5: readonly StomxOutpatientTemplateMetadata[] =
	[
		{
			id: 301,
			categoryId: 65,
			name: "Лечение перелома с повреждением пульпы методом Витальной ампутации",
			categoryName: "Травмы зубов",
			specialty: "therapy",
			mkbCode: "K02",
			order: 301,
		},
		{
			id: 302,
			categoryId: 65,
			name: "Лечение перелома с повреждением пульпы методом Витальной ампутации 2 плсещение",
			categoryName: "Травмы зубов",
			specialty: "therapy",
			mkbCode: "K02",
			order: 302,
		},
		{
			id: 303,
			categoryId: 65,
			name: "Лечение перелома с повреждением пульпы методом Витальной экстирпации",
			categoryName: "Травмы зубов",
			specialty: "therapy",
			mkbCode: "K02",
			order: 303,
		},
		{
			id: 304,
			categoryId: 65,
			name: "Лечение перелома с повреждением пульпы методом Витальной экстирпации 2 посещение",
			categoryName: "Травмы зубов",
			specialty: "therapy",
			mkbCode: "K02",
			order: 304,
		},
		{
			id: 305,
			categoryId: 67,
			name: "Восстановление зуба виниром с адгезивной фиксацией 1 посещение",
			categoryName: "Виниры",
			specialty: "orthopedics",
			mkbCode: "K03.8",
			order: 305,
		},
		{
			id: 306,
			categoryId: 67,
			name: "Восстановление зуба виниром с адгезивной фиксацией 2 посещение ",
			categoryName: "Виниры",
			specialty: "orthopedics",
			mkbCode: "K03.8",
			order: 306,
		},
		{
			id: 307,
			categoryId: 67,
			name: "Лечение гипоплазии эмали виниром 1 посещение",
			categoryName: "Виниры",
			specialty: "orthopedics",
			mkbCode: "K03.8",
			order: 307,
		},
		{
			id: 308,
			categoryId: 67,
			name: "Лечение гипоплазии эмали виниром 1 посещение",
			categoryName: "Виниры",
			specialty: "orthopedics",
			mkbCode: "K03.8",
			order: 308,
		},
		{
			id: 309,
			categoryId: 67,
			name: "Лечение дисколорита виниром 1 посещение",
			categoryName: "Виниры",
			specialty: "orthopedics",
			mkbCode: "K03.8",
			order: 309,
		},
		{
			id: 310,
			categoryId: 67,
			name: "Лечение дисколорита виниром 1 посещение",
			categoryName: "Виниры",
			specialty: "orthopedics",
			mkbCode: "K03.8",
			order: 310,
		},
		{
			id: 311,
			categoryId: 67,
			name: "Лечение дистопии зуба виниром 1 посещение",
			categoryName: "Виниры",
			specialty: "orthopedics",
			mkbCode: "K03.8",
			order: 311,
		},
		{
			id: 312,
			categoryId: 67,
			name: "Лечение дистопии зуба виниром 2 посещение",
			categoryName: "Виниры",
			specialty: "orthopedics",
			mkbCode: "K03.8",
			order: 312,
		},
		{
			id: 313,
			categoryId: 67,
			name: "Лечение клиновидного дефекта виниром  1 посещение",
			categoryName: "Виниры",
			specialty: "orthopedics",
			mkbCode: "K03.1",
			order: 313,
		},
		{
			id: 314,
			categoryId: 67,
			name: "Лечение клиновидного дефекта виниром  1 посещение",
			categoryName: "Виниры",
			specialty: "orthopedics",
			mkbCode: "K03.1",
			order: 314,
		},
		{
			id: 315,
			categoryId: 67,
			name: "Лечение перелома зуба без повреждения пульпы виниром 1 посещение",
			categoryName: "Виниры",
			specialty: "orthopedics",
			mkbCode: "K03.8",
			order: 315,
		},
		{
			id: 316,
			categoryId: 67,
			name: "Лечение перелома зуба без повреждения пульпы виниром 2 посещение",
			categoryName: "Виниры",
			specialty: "orthopedics",
			mkbCode: "K03.8",
			order: 316,
		},
		{
			id: 317,
			categoryId: 67,
			name: "Лечение скола эмали виниром 1 посещение",
			categoryName: "Виниры",
			specialty: "orthopedics",
			mkbCode: "K03.8",
			order: 317,
		},
		{
			id: 318,
			categoryId: 67,
			name: "Лечение скола эмали виниром 2 посещение",
			categoryName: "Виниры",
			specialty: "orthopedics",
			mkbCode: "K03.8",
			order: 318,
		},
		{
			id: 319,
			categoryId: 67,
			name: "Лечение стираемости зуба виниром  1 посещение",
			categoryName: "Виниры",
			specialty: "orthopedics",
			mkbCode: "K03.8",
			order: 319,
		},
		{
			id: 320,
			categoryId: 67,
			name: "Лечение стираемости зуба виниром  2 посещение",
			categoryName: "Виниры",
			specialty: "orthopedics",
			mkbCode: "K03.8",
			order: 320,
		},
		{
			id: 321,
			categoryId: 67,
			name: "Лечение флюороза виниром 1 посещение",
			categoryName: "Виниры",
			specialty: "orthopedics",
			mkbCode: "K03.0",
			order: 321,
		},
		{
			id: 322,
			categoryId: 67,
			name: "Лечение флюороза виниром 2 посещение",
			categoryName: "Виниры",
			specialty: "orthopedics",
			mkbCode: "K03.0",
			order: 322,
		},
		{
			id: 323,
			categoryId: 67,
			name: "Лечение эрозии 2-3 степени виниром 1 посещение",
			categoryName: "Виниры",
			specialty: "orthopedics",
			mkbCode: "K03.2",
			order: 323,
		},
		{
			id: 324,
			categoryId: 67,
			name: "Лечение эрозии 2-3 степени виниром 2 посещение",
			categoryName: "Виниры",
			specialty: "orthopedics",
			mkbCode: "K03.2",
			order: 324,
		},
		{
			id: 325,
			categoryId: 68,
			name: "Восстановление культи зуба внутриканальной штифтовой вкладкой 1 посещение",
			categoryName: "Вкладки",
			specialty: "orthopedics",
			mkbCode: "K02.1",
			order: 325,
		},
		{
			id: 326,
			categoryId: 68,
			name: "Восстановление культи зуба внутриканальной штифтовой вкладкой 2 посещение",
			categoryName: "Вкладки",
			specialty: "orthopedics",
			mkbCode: "K02.1",
			order: 326,
		},
		{
			id: 327,
			categoryId: 68,
			name: "Лечение глубокого кариеса вкладкой из золото-платинового сплава 1 посещение",
			categoryName: "Вкладки",
			specialty: "orthopedics",
			mkbCode: "K02",
			order: 327,
		},
		{
			id: 328,
			categoryId: 68,
			name: "Лечение глубокого кариеса вкладкой из золото-платинового сплава 2 посещение",
			categoryName: "Вкладки",
			specialty: "orthopedics",
			mkbCode: "K02",
			order: 328,
		},
		{
			id: 329,
			categoryId: 68,
			name: "Лечение глубокого кариеса вкладкой по технологии CAD\\CAM. 1 посещение",
			categoryName: "Вкладки",
			specialty: "orthopedics",
			mkbCode: "K02",
			order: 329,
		},
		{
			id: 330,
			categoryId: 68,
			name: " Лечение глубокого кариеса керамической вкладкой. 1 посещение",
			categoryName: "Вкладки",
			specialty: "orthopedics",
			mkbCode: "K02",
			order: 330,
		},
		{
			id: 331,
			categoryId: 68,
			name: " Лечение глубокого кариеса керамической вкладкой. 2 посещение",
			categoryName: "Вкладки",
			specialty: "orthopedics",
			mkbCode: "K02",
			order: 331,
		},
		{
			id: 332,
			categoryId: 68,
			name: "Лечение глубокого кариеса вкладкой из композита. 1 посещение",
			categoryName: "Вкладки",
			specialty: "orthopedics",
			mkbCode: "K02",
			order: 332,
		},
		{
			id: 333,
			categoryId: 68,
			name: "Лечение глубокого кариеса вкладкой из композита. 2 посещение",
			categoryName: "Вкладки",
			specialty: "orthopedics",
			mkbCode: "K02",
			order: 333,
		},
		{
			id: 334,
			categoryId: 68,
			name: "Лечение дистопии зуба керамической вкладкой  1 посещение",
			categoryName: "Вкладки",
			specialty: "orthopedics",
			mkbCode: "K02.1",
			order: 334,
		},
		{
			id: 335,
			categoryId: 68,
			name: "Лечение дистопии зуба керамической вкладкой  2 посещение",
			categoryName: "Вкладки",
			specialty: "orthopedics",
			mkbCode: "K02.1",
			order: 335,
		},
		{
			id: 336,
			categoryId: 68,
			name: "Лечение кариеса депульпированного зуба вкладкой из золото-платинового сплава",
			categoryName: "Вкладки",
			specialty: "orthopedics",
			mkbCode: "K02",
			order: 336,
		},
		{
			id: 337,
			categoryId: 68,
			name: "Лечение кариеса депульпированного зуба вкладкой из золото-платинового сплава 2 посещение",
			categoryName: "Вкладки",
			specialty: "orthopedics",
			mkbCode: "K02",
			order: 337,
		},
		{
			id: 338,
			categoryId: 68,
			name: "Лечение кариеса депульпированного зуба вкладкой из композита",
			categoryName: "Вкладки",
			specialty: "orthopedics",
			mkbCode: "K02",
			order: 338,
		},
		{
			id: 339,
			categoryId: 68,
			name: "Лечение кариеса депульпированного зуба вкладкой из композита 2 посещение",
			categoryName: "Вкладки",
			specialty: "orthopedics",
			mkbCode: "K02",
			order: 339,
		},
		{
			id: 340,
			categoryId: 68,
			name: "Лечение кариеса депульпированного зуба вкладкой по технологии CAD\\CAM",
			categoryName: "Вкладки",
			specialty: "orthopedics",
			mkbCode: "K02",
			order: 340,
		},
		{
			id: 341,
			categoryId: 68,
			name: "Лечение кариеса депульпированного зуба керамической вкладкой 1 посещение",
			categoryName: "Вкладки",
			specialty: "orthopedics",
			mkbCode: "K02",
			order: 341,
		},
		{
			id: 342,
			categoryId: 68,
			name: "Лечение кариеса депульпированного зуба керамической вкладкой 2 посещение",
			categoryName: "Вкладки",
			specialty: "orthopedics",
			mkbCode: "K02",
			order: 342,
		},
		{
			id: 343,
			categoryId: 68,
			name: "Лечение среднего кариеса вкладкой из золото-платинового сплава. 1 посещение",
			categoryName: "Вкладки",
			specialty: "orthopedics",
			mkbCode: "K02",
			order: 343,
		},
		{
			id: 344,
			categoryId: 68,
			name: "Лечение среднего кариеса вкладкой из золото-платинового сплава. 2 посещение",
			categoryName: "Вкладки",
			specialty: "orthopedics",
			mkbCode: "K02",
			order: 344,
		},
		{
			id: 345,
			categoryId: 68,
			name: "Лечение среднего кариеса вкладкой по технологии CAD\\CAM. 1 посещение",
			categoryName: "Вкладки",
			specialty: "orthopedics",
			mkbCode: "K02",
			order: 345,
		},
		{
			id: 346,
			categoryId: 68,
			name: "Лечение среднего кариеса керамической вкладкой. 1 посещение",
			categoryName: "Вкладки",
			specialty: "orthopedics",
			mkbCode: "K02",
			order: 346,
		},
		{
			id: 347,
			categoryId: 68,
			name: "Лечение среднего кариеса керамической вкладкой. 2 посещение",
			categoryName: "Вкладки",
			specialty: "orthopedics",
			mkbCode: "K02",
			order: 347,
		},
		{
			id: 348,
			categoryId: 68,
			name: "Лечение среднего кариеса вкладкой из композита. 1 посещение",
			categoryName: "Вкладки",
			specialty: "orthopedics",
			mkbCode: "K02",
			order: 348,
		},
		{
			id: 349,
			categoryId: 68,
			name: "Лечение среднего кариеса вкладкой из композита. 2 посещение",
			categoryName: "Вкладки",
			specialty: "orthopedics",
			mkbCode: "K02",
			order: 349,
		},
		{
			id: 350,
			categoryId: 69,
			name: " Восстановление зуба коронкой с адгезивной фиксацией. 1 посещение",
			categoryName: "Коронки",
			specialty: "orthopedics",
			mkbCode: "K02.1",
			order: 350,
		},
		{
			id: 351,
			categoryId: 69,
			name: " Восстановление зуба коронкой с адгезивной фиксацией. 2 посещение",
			categoryName: "Коронки",
			specialty: "orthopedics",
			mkbCode: "K02.1",
			order: 351,
		},
		{
			id: 352,
			categoryId: 69,
			name: " Восстановление зуба коронкой с цементной фиксацией. 1 посещение ",
			categoryName: "Коронки",
			specialty: "orthopedics",
			mkbCode: "K02.1",
			order: 352,
		},
		{
			id: 353,
			categoryId: 69,
			name: " Восстановление зуба коронкой с цементной фиксацией. 2 посещение ",
			categoryName: "Коронки",
			specialty: "orthopedics",
			mkbCode: "K02.1",
			order: 353,
		},
		{
			id: 354,
			categoryId: 69,
			name: "Лечение гипоплазии эмали коронкой 1 посещение",
			categoryName: "Коронки",
			specialty: "orthopedics",
			mkbCode: "K02.1",
			order: 354,
		},
		{
			id: 355,
			categoryId: 69,
			name: "Лечение гипоплазии эмали коронкой 2 посещение",
			categoryName: "Коронки",
			specialty: "orthopedics",
			mkbCode: "K02.1",
			order: 355,
		},
		{
			id: 356,
			categoryId: 69,
			name: "Лечение дисколорита зуба коронкой 1 посещение",
			categoryName: "Коронки",
			specialty: "orthopedics",
			mkbCode: "K02.1",
			order: 356,
		},
		{
			id: 357,
			categoryId: 69,
			name: "Лечение дисколорита зуба коронкой 2 посещение",
			categoryName: "Коронки",
			specialty: "orthopedics",
			mkbCode: "K02.1",
			order: 357,
		},
		{
			id: 358,
			categoryId: 69,
			name: "Лечение дистопии зуба коронкой 1 посещение",
			categoryName: "Коронки",
			specialty: "orthopedics",
			mkbCode: "K02.1",
			order: 358,
		},
		{
			id: 359,
			categoryId: 69,
			name: "Лечение дистопии зуба коронкой 2 посещение",
			categoryName: "Коронки",
			specialty: "orthopedics",
			mkbCode: "K02.1",
			order: 359,
		},
		{
			id: 360,
			categoryId: 69,
			name: "Лечение клиновидного дефекта коронкой 1 посещение",
			categoryName: "Коронки",
			specialty: "orthopedics",
			mkbCode: "K03.1",
			order: 360,
		},
		{
			id: 361,
			categoryId: 69,
			name: "Лечение клиновидного дефекта коронкой 2 посещение",
			categoryName: "Коронки",
			specialty: "orthopedics",
			mkbCode: "K03.1",
			order: 361,
		},
		{
			id: 362,
			categoryId: 69,
			name: "Лечение перелома коронки зуба без повреждения пульпы коронкой 1 посещение",
			categoryName: "Коронки",
			specialty: "orthopedics",
			mkbCode: "K02.1",
			order: 362,
		},
		{
			id: 363,
			categoryId: 69,
			name: "Лечение перелома коронки зуба без повреждения пульпы коронкой 2 посещение",
			categoryName: "Коронки",
			specialty: "orthopedics",
			mkbCode: "K02.1",
			order: 363,
		},
		{
			id: 364,
			categoryId: 69,
			name: " Лечение перелома только эмали зуба (откол эмали) коронкой 1 посещение",
			categoryName: "Коронки",
			specialty: "orthopedics",
			mkbCode: "K02.1",
			order: 364,
		},
		{
			id: 365,
			categoryId: 69,
			name: " Лечение перелома только эмали зуба (откол эмали) коронкой 2 посещение",
			categoryName: "Коронки",
			specialty: "orthopedics",
			mkbCode: "K02.1",
			order: 365,
		},
		{
			id: 366,
			categoryId: 69,
			name: "Лечение стираемости зуба коронкой 1 посещение",
			categoryName: "Коронки",
			specialty: "orthopedics",
			mkbCode: "K02.1",
			order: 366,
		},
		{
			id: 367,
			categoryId: 69,
			name: "Лечение стираемости зуба коронкой 2 посещение",
			categoryName: "Коронки",
			specialty: "orthopedics",
			mkbCode: "K02.1",
			order: 367,
		},
		{
			id: 368,
			categoryId: 69,
			name: "Лечение флюороза коронкой 1 посещение",
			categoryName: "Коронки",
			specialty: "orthopedics",
			mkbCode: "K03.0",
			order: 368,
		},
		{
			id: 369,
			categoryId: 69,
			name: "Лечение флюороза коронкой 2 посещение",
			categoryName: "Коронки",
			specialty: "orthopedics",
			mkbCode: "K03.0",
			order: 369,
		},
		{
			id: 370,
			categoryId: 69,
			name: "Лечение эрозии 2-3 степени коронкой 1 посещение",
			categoryName: "Коронки",
			specialty: "orthopedics",
			mkbCode: "K03.2",
			order: 370,
		},
		{
			id: 371,
			categoryId: 69,
			name: "Лечение эрозии 2-3 степени коронкой 2 посещение",
			categoryName: "Коронки",
			specialty: "orthopedics",
			mkbCode: "K03.2",
			order: 371,
		},
		{
			id: 372,
			categoryId: 70,
			name: " Восстановление включенного дефекта зубного ряда мостовидным протезом. 1 посещение",
			categoryName: "Несъемные мостовидные протезы на зубах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 372,
		},
		{
			id: 373,
			categoryId: 70,
			name: " Восстановление включенного дефекта зубного ряда мостовидным протезом. 2 посещение",
			categoryName: "Несъемные мостовидные протезы на зубах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 373,
		},
		{
			id: 374,
			categoryId: 70,
			name: " Восстановление дефекта зубного ряда консольным протезом. 1 посещение",
			categoryName: "Несъемные мостовидные протезы на зубах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 374,
		},
		{
			id: 375,
			categoryId: 70,
			name: " Восстановление дефекта зубного ряда консольным протезом. 2 посещение",
			categoryName: "Несъемные мостовидные протезы на зубах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 375,
		},
	];
