import type { StomxOutpatientTemplateMetadata } from "./stomtOutpatientCatalog.js";

/**
 * StomX Templates Metadata Part 3
 */
export const STOMX_TEMPLATES_PART_3: readonly StomxOutpatientTemplateMetadata[] =
	[
		{
			id: 151,
			categoryId: 16,
			name: "Периодонтит",
			categoryName: "Терапия",
			specialty: "therapy",
			mkbCode: "K04.7",
			order: 151,
		},
		{
			id: 152,
			categoryId: 16,
			name: "Периодонтит удаление",
			categoryName: "Терапия",
			specialty: "therapy",
			mkbCode: "K04.7",
			order: 152,
		},
		{
			id: 153,
			categoryId: 16,
			name: "Пульпит",
			categoryName: "Терапия",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 153,
		},
		{
			id: 154,
			categoryId: 16,
			name: "Средний кариес",
			categoryName: "Терапия",
			specialty: "therapy",
			mkbCode: "K02",
			order: 154,
		},
		{
			id: 155,
			categoryId: 16,
			name: "Глубокий кариес",
			categoryName: "Терапия",
			specialty: "therapy",
			mkbCode: "K02",
			order: 155,
		},
		{
			id: 156,
			categoryId: 16,
			name: "Хронический фиброзный пульпит первое посещение",
			categoryName: "Терапия",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 156,
		},
		{
			id: 157,
			categoryId: 16,
			name: "Хронический фиброзный пульпит второе посещение",
			categoryName: "Терапия",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 157,
		},
		{
			id: 158,
			categoryId: 16,
			name: "Хронический фиброзный пульпит третье посещение",
			categoryName: "Терапия",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 158,
		},
		{
			id: 159,
			categoryId: 16,
			name: "Хронический фиброзный пульпит в стадии обострения первое посещение",
			categoryName: "Терапия",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 159,
		},
		{
			id: 160,
			categoryId: 16,
			name: "Хронический фиброзный пульпит в стадии обострения второе посещение",
			categoryName: "Терапия",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 160,
		},
		{
			id: 161,
			categoryId: 16,
			name: "Хронический фиброзный пульпит в стадии обострения третье посещение",
			categoryName: "Терапия",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 161,
		},
		{
			id: 162,
			categoryId: 16,
			name: "Лечение хронического гиперпластического пульпита методом витальной экстирпации",
			categoryName: "Терапия",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 162,
		},
		{
			id: 163,
			categoryId: 16,
			name: "Гиперестезия твердых тканей зубов",
			categoryName: "Терапия",
			specialty: "therapy",
			mkbCode: "K02",
			order: 163,
		},
		{
			id: 164,
			categoryId: 16,
			name: "Хронический катаральный гингивит",
			categoryName: "Терапия",
			specialty: "therapy",
			mkbCode: "K05.1",
			order: 164,
		},
		{
			id: 165,
			categoryId: 16,
			name: "Хронический катаральный гингивит",
			categoryName: "Терапия",
			specialty: "therapy",
			mkbCode: "K05.1",
			order: 165,
		},
		{
			id: 166,
			categoryId: 16,
			name: "Обострение хронического катарального гингивита",
			categoryName: "Терапия",
			specialty: "therapy",
			mkbCode: "K05.1",
			order: 166,
		},
		{
			id: 167,
			categoryId: 16,
			name: "Хронический генерализованный пародонтит",
			categoryName: "Терапия",
			specialty: "therapy",
			mkbCode: "K05.3",
			order: 167,
		},
		{
			id: 168,
			categoryId: 16,
			name: "Обострение хронического генерализованного пародонтита",
			categoryName: "Терапия",
			specialty: "therapy",
			mkbCode: "K05.3",
			order: 168,
		},
		{
			id: 169,
			categoryId: 17,
			name: "Хронический периодонтит",
			categoryName: "Хирургия",
			specialty: "surgery",
			mkbCode: "K04.7",
			order: 169,
		},
		{
			id: 170,
			categoryId: 17,
			name: "Обострение хронического периодонтита",
			categoryName: "Хирургия",
			specialty: "surgery",
			mkbCode: "K04.7",
			order: 170,
		},
		{
			id: 171,
			categoryId: 17,
			name: "Острый гнойный периостит верхней (нижней челюсти ) от    зуба первое посещение",
			categoryName: "Хирургия",
			specialty: "surgery",
			mkbCode: "K10.2",
			order: 171,
		},
		{
			id: 172,
			categoryId: 17,
			name: "Острый гнойный периостит верхней (нижней челюсти ) от    зуба  второе посещение",
			categoryName: "Хирургия",
			specialty: "surgery",
			mkbCode: "K10.2",
			order: 172,
		},
		{
			id: 173,
			categoryId: 17,
			name: "Пародонтит",
			categoryName: "Хирургия",
			specialty: "surgery",
			mkbCode: "K05.3",
			order: 173,
		},
		{
			id: 174,
			categoryId: 17,
			name: "Перикоронарит",
			categoryName: "Хирургия",
			specialty: "surgery",
			mkbCode: "K05.2",
			order: 174,
		},
		{
			id: 175,
			categoryId: 17,
			name: "Поражение беззубого альвеолярного края, обусловленное травмой в области",
			categoryName: "Хирургия",
			specialty: "surgery",
			mkbCode: "K08.1",
			order: 175,
		},
		{
			id: 176,
			categoryId: 17,
			name: "Удаление зуба",
			categoryName: "Хирургия",
			specialty: "surgery",
			mkbCode: "K08.1",
			order: 176,
		},
		{
			id: 177,
			categoryId: 16,
			name: "Домашнее отбеливание зубов с каппами",
			categoryName: "Терапия",
			specialty: "therapy",
			mkbCode: "K03.7",
			order: 177,
		},
		{
			id: 178,
			categoryId: 16,
			name: "Профессиональное отбеливание зубов офисное  (аппаратная фотоактивация отбеливающего препарата)",
			categoryName: "Терапия",
			specialty: "therapy",
			mkbCode: "K03.7",
			order: 178,
		},
		{
			id: 179,
			categoryId: 16,
			name: "Лечение острого периодонтита пульпарного происхождения",
			categoryName: "Терапия",
			specialty: "therapy",
			mkbCode: "K04.7",
			order: 179,
		},
		{
			id: 180,
			categoryId: 16,
			name: "Лечение хронического периодонтита ранее леченного эндодонтически зуба",
			categoryName: "Терапия",
			specialty: "therapy",
			mkbCode: "K04.7",
			order: 180,
		},
		{
			id: 181,
			categoryId: 16,
			name: "Лечение хронического периодонтита ранее не леченного эндодонтически зуба",
			categoryName: "Терапия",
			specialty: "therapy",
			mkbCode: "K04.7",
			order: 181,
		},
		{
			id: 182,
			categoryId: 16,
			name: "Лечение гнойного пульпита методом витальной экстирпации",
			categoryName: "Терапия",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 182,
		},
		{
			id: 183,
			categoryId: 16,
			name: "Лечение начального пульпита с исходом в острый пульпит композитной пломбой",
			categoryName: "Терапия",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 183,
		},
		{
			id: 184,
			categoryId: 16,
			name: "Лечение пульпита методом витальной ампутации (препарат Пульпотек, препарат кальция ___________________)",
			categoryName: "Терапия",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 184,
		},
		{
			id: 185,
			categoryId: 16,
			name: "Лечение острого пульпита методом витальной экстирпации",
			categoryName: "Терапия",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 185,
		},
		{
			id: 186,
			categoryId: 16,
			name: "Лечение острого пульпита методом девитальной экстирпации",
			categoryName: "Терапия",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 186,
		},
		{
			id: 187,
			categoryId: 16,
			name: "Лечение хронического пульпита методом витальной экстирпации",
			categoryName: "Терапия",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 187,
		},
		{
			id: 188,
			categoryId: 16,
			name: "Лечение хронического пульпита методом девитальной экстирпации",
			categoryName: "Терапия",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 188,
		},
		{
			id: 189,
			categoryId: 16,
			name: "Лечение изменений цвета зубов при флюорозе методом микроабразии",
			categoryName: "Терапия",
			specialty: "therapy",
			mkbCode: "K03.0",
			order: 189,
		},
		{
			id: 190,
			categoryId: 58,
			name: "2.1\tКерамическая вкладка. 1 посещение ",
			categoryName:
				"Восстановление зубов с диагнозом пульпит и периодонтит после эндодонтического лечения",
			specialty: "therapy",
			mkbCode: "K02.1",
			order: 190,
		},
		{
			id: 191,
			categoryId: 58,
			name: "2.1\tКерамическая вкладка. 2 посещение",
			categoryName:
				"Восстановление зубов с диагнозом пульпит и периодонтит после эндодонтического лечения",
			specialty: "therapy",
			mkbCode: "K02.1",
			order: 191,
		},
		{
			id: 192,
			categoryId: 58,
			name: "Лабораторные вкладки. 2.2\tЗолото-платиновая вкладка. 1 посещение ",
			categoryName:
				"Восстановление зубов с диагнозом пульпит и периодонтит после эндодонтического лечения",
			specialty: "therapy",
			mkbCode: "K02.1",
			order: 192,
		},
		{
			id: 193,
			categoryId: 58,
			name: "Лабораторные вкладки. 2.2 Золото-платиновая вкладка. 2 посещение",
			categoryName:
				"Восстановление зубов с диагнозом пульпит и периодонтит после эндодонтического лечения",
			specialty: "therapy",
			mkbCode: "K02.1",
			order: 193,
		},
		{
			id: 194,
			categoryId: 58,
			name: "2.3  Композитная вкладка. 1 посещение ",
			categoryName:
				"Восстановление зубов с диагнозом пульпит и периодонтит после эндодонтического лечения",
			specialty: "therapy",
			mkbCode: "K02.1",
			order: 194,
		},
		{
			id: 195,
			categoryId: 58,
			name: "2.3  Композитная вкладка. 2 посещение ",
			categoryName:
				"Восстановление зубов с диагнозом пульпит и периодонтит после эндодонтического лечения",
			specialty: "therapy",
			mkbCode: "K02.1",
			order: 195,
		},
		{
			id: 196,
			categoryId: 58,
			name: "Фрезерованные вкладки",
			categoryName:
				"Восстановление зубов с диагнозом пульпит и периодонтит после эндодонтического лечения",
			specialty: "therapy",
			mkbCode: "K02.1",
			order: 196,
		},
		{
			id: 197,
			categoryId: 58,
			name: "1.\tВосстановление композитной пломбой.",
			categoryName:
				"Восстановление зубов с диагнозом пульпит и периодонтит после эндодонтического лечения",
			specialty: "therapy",
			mkbCode: "K02",
			order: 197,
		},
		{
			id: 198,
			categoryId: 58,
			name: "1.\tВосстановление пломбой из амальгамы",
			categoryName:
				"Восстановление зубов с диагнозом пульпит и периодонтит после эндодонтического лечения",
			specialty: "therapy",
			mkbCode: "K02",
			order: 198,
		},
		{
			id: 199,
			categoryId: 58,
			name: "2.\tВосстановление пломбой из СИЦ",
			categoryName:
				"Восстановление зубов с диагнозом пульпит и периодонтит после эндодонтического лечения",
			specialty: "therapy",
			mkbCode: "K02",
			order: 199,
		},
		{
			id: 200,
			categoryId: 58,
			name: "Вариант 1. Восстановление с использованием стекловолоконного штифта.",
			categoryName:
				"Восстановление зубов с диагнозом пульпит и периодонтит после эндодонтического лечения",
			specialty: "therapy",
			mkbCode: "K02",
			order: 200,
		},
		{
			id: 201,
			categoryId: 58,
			name: "2. Восстановление с использованием металлического штифта.",
			categoryName:
				"Восстановление зубов с диагнозом пульпит и периодонтит после эндодонтического лечения",
			specialty: "therapy",
			mkbCode: "K02",
			order: 201,
		},
		{
			id: 202,
			categoryId: 60,
			name: "Лечение кариеса дентина материалом «Биодентин» в 2 посещения.",
			categoryName: "Кариес",
			specialty: "therapy",
			mkbCode: "K02",
			order: 202,
		},
		{
			id: 203,
			categoryId: 60,
			name: "Лечение  кариеса дентина пломбой в 1 посещение",
			categoryName: "Кариес",
			specialty: "therapy",
			mkbCode: "K02",
			order: 203,
		},
		{
			id: 204,
			categoryId: 60,
			name: "Лечение  кариеса дентина пломбой в 2 посещения",
			categoryName: "Кариес",
			specialty: "therapy",
			mkbCode: "K02",
			order: 204,
		},
		{
			id: 205,
			categoryId: 60,
			name: "Лечение кариеса дентина Biodentine  1 посещение ",
			categoryName: "Кариес",
			specialty: "therapy",
			mkbCode: "K02",
			order: 205,
		},
		{
			id: 206,
			categoryId: 60,
			name: "Лечение кариеса дентина сэндвич-техникой",
			categoryName: "Кариес",
			specialty: "therapy",
			mkbCode: "K02",
			order: 206,
		},
		{
			id: 207,
			categoryId: 60,
			name: "Лечение кариеса депульпированного зуба пломбой из композита",
			categoryName: "Кариес",
			specialty: "therapy",
			mkbCode: "K02",
			order: 207,
		},
		{
			id: 208,
			categoryId: 60,
			name: "Лечение кариеса цемента без препарирования",
			categoryName: "Кариес",
			specialty: "therapy",
			mkbCode: "K02",
			order: 208,
		},
		{
			id: 209,
			categoryId: 60,
			name: "Лечение кариеса цемента зуба при поддесневом расположении",
			categoryName: "Кариес",
			specialty: "therapy",
			mkbCode: "K02",
			order: 209,
		},
		{
			id: 210,
			categoryId: 60,
			name: "Лечение кариеса цемента при наддесневом расположении",
			categoryName: "Кариес",
			specialty: "therapy",
			mkbCode: "K02",
			order: 210,
		},
		{
			id: 211,
			categoryId: 60,
			name: "Лечение кариеса эмали в стадии белого пятна пломбой",
			categoryName: "Кариес",
			specialty: "therapy",
			mkbCode: "K02",
			order: 211,
		},
		{
			id: 212,
			categoryId: 60,
			name: "Лечение кариеса эмали в стадии белого пятна препаратом Айкон",
			categoryName: "Кариес",
			specialty: "therapy",
			mkbCode: "K02",
			order: 212,
		},
		{
			id: 213,
			categoryId: 60,
			name: "Лечение кариеса эмали в стадии белого пятна реминерализацией",
			categoryName: "Кариес",
			specialty: "therapy",
			mkbCode: "K02",
			order: 213,
		},
		{
			id: 214,
			categoryId: 60,
			name: "Лечение приостановившего кариеса пломбой",
			categoryName: "Кариес",
			specialty: "therapy",
			mkbCode: "K02",
			order: 214,
		},
		{
			id: 215,
			categoryId: 60,
			name: "Лечение приостановившего кариеса препаратом Айкон",
			categoryName: "Кариес",
			specialty: "therapy",
			mkbCode: "K02",
			order: 215,
		},
		{
			id: 216,
			categoryId: 60,
			name: "Лечение приостановившегося кариеса реминерализацией",
			categoryName: "Кариес",
			specialty: "therapy",
			mkbCode: "K02",
			order: 216,
		},
		{
			id: 217,
			categoryId: 60,
			name: "Диагностическая ревизия полости при диагнозе кариес зубов",
			categoryName: "Кариес",
			specialty: "therapy",
			mkbCode: "K02",
			order: 217,
		},
		{
			id: 218,
			categoryId: 60,
			name: "Терапевтическое восстановление зубов с диагнозом кариес. Восстановление пломбой из амальгамы.",
			categoryName: "Кариес",
			specialty: "therapy",
			mkbCode: "K02",
			order: 218,
		},
		{
			id: 219,
			categoryId: 60,
			name: "Терапевтическое восстановление зубов с диагнозом кариес. Восстановление пломбой из композита",
			categoryName: "Кариес",
			specialty: "therapy",
			mkbCode: "K02",
			order: 219,
		},
		{
			id: 220,
			categoryId: 60,
			name: "Терапевтическое восстановление зубов с диагнозом кариес. Восстановление пломбой из СИЦ",
			categoryName: "Кариес",
			specialty: "therapy",
			mkbCode: "K02",
			order: 220,
		},
		{
			id: 221,
			categoryId: 60,
			name: "Микроабразия_гипоплазия",
			categoryName: "Кариес",
			specialty: "therapy",
			mkbCode: "K02",
			order: 221,
		},
		{
			id: 222,
			categoryId: 60,
			name: "Микроабразия_кариес",
			categoryName: "Кариес",
			specialty: "therapy",
			mkbCode: "K02",
			order: 222,
		},
		{
			id: 223,
			categoryId: 61,
			name: "Микроабразия_флюороз",
			categoryName: "Некариозные поражения",
			specialty: "therapy",
			mkbCode: "K03.0",
			order: 223,
		},
		{
			id: 224,
			categoryId: 61,
			name: "Лечение клиновидного дефекта пломбой из композита",
			categoryName: "Некариозные поражения",
			specialty: "therapy",
			mkbCode: "K03.1",
			order: 224,
		},
		{
			id: 225,
			categoryId: 61,
			name: "Лечение клиновидного дефекта пломбой из СИЦ",
			categoryName: "Некариозные поражения",
			specialty: "therapy",
			mkbCode: "K03.1",
			order: 225,
		},
	];
