import type { StomxOutpatientTemplateMetadata } from "./stomtOutpatientCatalog.js";

/**
 * StomX Templates Metadata Part 6
 */
export const STOMX_TEMPLATES_PART_6: readonly StomxOutpatientTemplateMetadata[] =
	[
		{
			id: 376,
			categoryId: 71,
			name: "Восстановление дефекта зубного ряда консольным протезом с опорой на имплантаты. 1 посещение",
			categoryName: "Несъемные протезы на имплантатах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 376,
		},
		{
			id: 377,
			categoryId: 71,
			name: "Восстановление дефекта зубного ряда консольным протезом с опорой на имплантаты. 2 посещение",
			categoryName: "Несъемные протезы на имплантатах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 377,
		},
		{
			id: 378,
			categoryId: 71,
			name: " Восстановление дефекта зубного ряда мостовидным протезом с опорой на имплантаты. 1 посещение",
			categoryName: "Несъемные протезы на имплантатах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 378,
		},
		{
			id: 379,
			categoryId: 71,
			name: " Восстановление дефекта зубного ряда мостовидным протезом с опорой на имплантаты. 2 посещение",
			categoryName: "Несъемные протезы на имплантатах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 379,
		},
		{
			id: 380,
			categoryId: 71,
			name: " Восстановление дефекта зубного ряда одиночной коронкой с опорой на имплантат. 1 посещение",
			categoryName: "Несъемные протезы на имплантатах",
			specialty: "orthopedics",
			mkbCode: "K02.1",
			order: 380,
		},
		{
			id: 381,
			categoryId: 71,
			name: " Восстановление дефекта зубного ряда одиночной коронкой с опорой на имплантат. 2 посещение",
			categoryName: "Несъемные протезы на имплантатах",
			specialty: "orthopedics",
			mkbCode: "K02.1",
			order: 381,
		},
		{
			id: 382,
			categoryId: 72,
			name: " Восстановление дефекта зубного ряда бюгельным протезом с замковой фиксацией. 1 посещение",
			categoryName: "Съемные протезы на зубах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 382,
		},
		{
			id: 383,
			categoryId: 72,
			name: " Восстановление дефекта зубного ряда бюгельным протезом с замковой фиксацией. 2 посещение",
			categoryName: "Съемные протезы на зубах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 383,
		},
		{
			id: 384,
			categoryId: 72,
			name: " Восстановление дефекта зубного ряда бюгельным протезом с замковой фиксацией. 3 посещение",
			categoryName: "Съемные протезы на зубах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 384,
		},
		{
			id: 385,
			categoryId: 72,
			name: " Восстановление дефекта зубного ряда бюгельным протезом с замковой фиксацией. 4 посещение",
			categoryName: "Съемные протезы на зубах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 385,
		},
		{
			id: 386,
			categoryId: 72,
			name: " Восстановление дефекта зубного ряда бюгельным протезом с кламмерной фиксацией. 1 посещение",
			categoryName: "Съемные протезы на зубах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 386,
		},
		{
			id: 387,
			categoryId: 72,
			name: " Восстановление дефекта зубного ряда бюгельным протезом с кламмерной фиксацией. 2 посещение",
			categoryName: "Съемные протезы на зубах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 387,
		},
		{
			id: 388,
			categoryId: 72,
			name: " Восстановление дефекта зубного ряда бюгельным протезом с кламмерной фиксацией. 3 посещение",
			categoryName: "Съемные протезы на зубах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 388,
		},
		{
			id: 389,
			categoryId: 72,
			name: " Восстановление дефекта зубного ряда бюгельным протезом с кламмерной фиксацией. 4 посещение",
			categoryName: "Съемные протезы на зубах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 389,
		},
		{
			id: 390,
			categoryId: 72,
			name: " Восстановление дефекта зубного ряда полным съемным протезом  1 посещение",
			categoryName: "Съемные протезы на зубах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 390,
		},
		{
			id: 391,
			categoryId: 72,
			name: " Восстановление дефекта зубного ряда полным съемным протезом  2 посещение",
			categoryName: "Съемные протезы на зубах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 391,
		},
		{
			id: 392,
			categoryId: 72,
			name: " Восстановление дефекта зубного ряда полным съемным протезом  3 посещение",
			categoryName: "Съемные протезы на зубах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 392,
		},
		{
			id: 393,
			categoryId: 72,
			name: " Восстановление дефекта зубного ряда полным съемным протезом  4 посещение",
			categoryName: "Съемные протезы на зубах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 393,
		},
		{
			id: 394,
			categoryId: 72,
			name: " Восстановление дефекта зубного ряда полным съемным протезом  5 посещение",
			categoryName: "Съемные протезы на зубах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 394,
		},
		{
			id: 395,
			categoryId: 72,
			name: "Восстановление дефекта зубного ряда бюгельным протезом с телескопической фиксацией. 1 посещение",
			categoryName: "Съемные протезы на зубах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 395,
		},
		{
			id: 396,
			categoryId: 72,
			name: "Восстановление дефекта зубного ряда бюгельным протезом с телескопической фиксацией. 2 посещение",
			categoryName: "Съемные протезы на зубах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 396,
		},
		{
			id: 397,
			categoryId: 72,
			name: "Восстановление дефекта зубного ряда бюгельным протезом с телескопической фиксацией. 3 посещение",
			categoryName: "Съемные протезы на зубах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 397,
		},
		{
			id: 398,
			categoryId: 72,
			name: "Восстановление дефекта зубного ряда бюгельным протезом с телескопической фиксацией. 4 посещение",
			categoryName: "Съемные протезы на зубах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 398,
		},
		{
			id: 399,
			categoryId: 72,
			name: " Восстановление дефекта зубного ряда частичным съемным пластиночным протезом из гибкого полимера. 1 посещение",
			categoryName: "Съемные протезы на зубах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 399,
		},
		{
			id: 400,
			categoryId: 72,
			name: " Восстановление дефекта зубного ряда частичным съемным пластиночным протезом из гибкого полимера. 2 посещение",
			categoryName: "Съемные протезы на зубах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 400,
		},
		{
			id: 401,
			categoryId: 72,
			name: " Восстановление дефекта зубного ряда частичным съемным пластиночным протезом из гибкого полимера. 3 посещение",
			categoryName: "Съемные протезы на зубах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 401,
		},
		{
			id: 402,
			categoryId: 72,
			name: " Восстановление дефекта зубного ряда частичным съемным пластиночным протезом из гибкого полимера. 4 посещение",
			categoryName: "Съемные протезы на зубах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 402,
		},
		{
			id: 403,
			categoryId: 72,
			name: " Восстановление дефекта зубного ряда частичным съемным пластиночным протезом.",
			categoryName: "Съемные протезы на зубах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 403,
		},
		{
			id: 404,
			categoryId: 72,
			name: " Восстановление дефекта зубного ряда частичным съемным пластиночным протезом.2 посещение",
			categoryName: "Съемные протезы на зубах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 404,
		},
		{
			id: 405,
			categoryId: 72,
			name: " Восстановление дефекта зубного ряда частичным съемным пластиночным протезом.3 посещение",
			categoryName: "Съемные протезы на зубах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 405,
		},
		{
			id: 406,
			categoryId: 72,
			name: " Восстановление дефекта зубного ряда частичным съемным пластиночным протезом.4 посещение",
			categoryName: "Съемные протезы на зубах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 406,
		},
		{
			id: 407,
			categoryId: 73,
			name: " Восстановление дефекта зубного ряда полным съемным протезом  1 посещение",
			categoryName: "Съемные протезы на имплантатах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 407,
		},
		{
			id: 408,
			categoryId: 73,
			name: " Восстановление дефекта зубного ряда полным съемным протезом  2 посещение",
			categoryName: "Съемные протезы на имплантатах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 408,
		},
		{
			id: 409,
			categoryId: 73,
			name: " Восстановление дефекта зубного ряда полным съемным протезом  3 посещение",
			categoryName: "Съемные протезы на имплантатах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 409,
		},
		{
			id: 410,
			categoryId: 73,
			name: " Восстановление дефекта зубного ряда полным съемным протезом  4 посещение",
			categoryName: "Съемные протезы на имплантатах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 410,
		},
		{
			id: 411,
			categoryId: 73,
			name: " Восстановление дефекта зубного ряда полным съемным протезом  5 посещение",
			categoryName: "Съемные протезы на имплантатах",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 411,
		},
		{
			id: 412,
			categoryId: 75,
			name: "Имплантация с аугментацией костно-пластическим материалом",
			categoryName: "Имплантация",
			specialty: "implantology",
			mkbCode: "K08.1",
			order: 412,
		},
		{
			id: 413,
			categoryId: 75,
			name: "Имплантация + закрытый синус-лифтинг",
			categoryName: "Имплантация",
			specialty: "implantology",
			mkbCode: "K08.1",
			order: 413,
		},
		{
			id: 414,
			categoryId: 75,
			name: "Восстановление дефекта зубного ряда  с помощью дентальной имплантации с одномоментным проведением открытого синус-лифтинга.",
			categoryName: "Имплантация",
			specialty: "implantology",
			mkbCode: "K08.1",
			order: 414,
		},
		{
			id: 415,
			categoryId: 75,
			name: "Восстановление дефекта зубного ряда  с помощью дентальной имплантации с одномоментным проведением открытого синус-лифтинга",
			categoryName: "Имплантация",
			specialty: "implantology",
			mkbCode: "K08.1",
			order: 415,
		},
		{
			id: 416,
			categoryId: 75,
			name: " Восстановление дефекта зубного ряда  с помощью дентальной имплантации без аугментации.",
			categoryName: "Имплантация",
			specialty: "implantology",
			mkbCode: "K08.1",
			order: 416,
		},
		{
			id: 417,
			categoryId: 75,
			name: "Удаление имплантата",
			categoryName: "Имплантация",
			specialty: "implantology",
			mkbCode: "K08.1",
			order: 417,
		},
		{
			id: 418,
			categoryId: 75,
			name: " Создание опоры для ортодонтического лечения  с помощью установки ортодонтического имплантата.",
			categoryName: "Имплантация",
			specialty: "implantology",
			mkbCode: "K08.1",
			order: 418,
		},
		{
			id: 419,
			categoryId: 76,
			name: "Цистэктомия с резекцией верхушки корня зуба и ретроградным пломбированием корневого канала 1 посещение",
			categoryName: "Лечение корневых кист",
			specialty: "surgery",
			mkbCode: "K08.1",
			order: 419,
		},
		{
			id: 420,
			categoryId: 76,
			name: "Цистэктомия с резекцией верхушки корня зуба и ретроградным пломбированием корневого канала 2 посещение",
			categoryName: "Лечение корневых кист",
			specialty: "surgery",
			mkbCode: "K08.1",
			order: 420,
		},
		{
			id: 421,
			categoryId: 76,
			name: "Цистэктомия с резекцией верхушки корня зуба и ретроградным пломбированием корневого канала 3 посещение",
			categoryName: "Лечение корневых кист",
			specialty: "surgery",
			mkbCode: "K08.1",
			order: 421,
		},
		{
			id: 422,
			categoryId: 76,
			name: "Цистэктомия без резекции верхушки корня. 2 посещение",
			categoryName: "Лечение корневых кист",
			specialty: "surgery",
			mkbCode: "K08.1",
			order: 422,
		},
		{
			id: 423,
			categoryId: 76,
			name: "Цистэктомия без резекции верхушки корня. 3 посещение",
			categoryName: "Лечение корневых кист",
			specialty: "surgery",
			mkbCode: "K08.1",
			order: 423,
		},
		{
			id: 424,
			categoryId: 77,
			name: "Гингивэктомия",
			categoryName: "Пародонтология",
			specialty: "periodontics",
			mkbCode: "K05.3",
			order: 424,
		},
		{
			id: 425,
			categoryId: 77,
			name: "Закрытый кюретаж",
			categoryName: "Пародонтология",
			specialty: "periodontics",
			mkbCode: "K05.3",
			order: 425,
		},
		{
			id: 426,
			categoryId: 77,
			name: "Открытый кюретаж",
			categoryName: "Пародонтология",
			specialty: "periodontics",
			mkbCode: "K05.3",
			order: 426,
		},
		{
			id: 427,
			categoryId: 78,
			name: "Острый перикоронит. Гнойная форма",
			categoryName: "Перикоронит",
			specialty: "surgery",
			mkbCode: "K05.2",
			order: 427,
		},
		{
			id: 428,
			categoryId: 78,
			name: "Острый перикоронит. Катаральная форма",
			categoryName: "Перикоронит",
			specialty: "surgery",
			mkbCode: "K05.2",
			order: 428,
		},
		{
			id: 429,
			categoryId: 78,
			name: "Хронический перикоронит 1",
			categoryName: "Перикоронит",
			specialty: "surgery",
			mkbCode: "K05.2",
			order: 429,
		},
		{
			id: 430,
			categoryId: 78,
			name: "Хронический перикоронит 2",
			categoryName: "Перикоронит",
			specialty: "surgery",
			mkbCode: "K05.2",
			order: 430,
		},
		{
			id: 431,
			categoryId: 79,
			name: "Периостит острый гнойный без удаления зуба 1 посещение",
			categoryName: "Периостит",
			specialty: "surgery",
			mkbCode: "K08.1",
			order: 431,
		},
		{
			id: 432,
			categoryId: 79,
			name: "Периостит острый гнойный без удаления зуба 2  посещение",
			categoryName: "Периостит",
			specialty: "surgery",
			mkbCode: "K08.1",
			order: 432,
		},
		{
			id: 433,
			categoryId: 79,
			name: "Периостит острый гнойный без удаления зуба 3  посещение",
			categoryName: "Периостит",
			specialty: "surgery",
			mkbCode: "K08.1",
			order: 433,
		},
		{
			id: 434,
			categoryId: 79,
			name: "Периостит острый гнойный с удалением зуба  1 посещение ",
			categoryName: "Периостит",
			specialty: "surgery",
			mkbCode: "K08.1",
			order: 434,
		},
		{
			id: 435,
			categoryId: 79,
			name: "Периостит острый гнойный с удалением зуба  2 посещение ",
			categoryName: "Периостит",
			specialty: "surgery",
			mkbCode: "K08.1",
			order: 435,
		},
		{
			id: 436,
			categoryId: 80,
			name: "Проведение операции открытого синус-лифтинга.",
			categoryName: "Синус-лифтинг",
			specialty: "implantology",
			mkbCode: "K08.8",
			order: 436,
		},
		{
			id: 437,
			categoryId: 80,
			name: "Проведение открытого синус-лифтинга.",
			categoryName: "Синус-лифтинг",
			specialty: "implantology",
			mkbCode: "K08.8",
			order: 437,
		},
		{
			id: 438,
			categoryId: 81,
			name: "Удаление зуба кариес цемента",
			categoryName: "Удаление зубов",
			specialty: "surgery",
			mkbCode: "K02",
			order: 438,
		},
		{
			id: 439,
			categoryId: 81,
			name: "Удаление зуба корневая киста ",
			categoryName: "Удаление зубов",
			specialty: "surgery",
			mkbCode: "K08.1",
			order: 439,
		},
		{
			id: 440,
			categoryId: 81,
			name: "Удаление зуба корневая киста",
			categoryName: "Удаление зубов",
			specialty: "surgery",
			mkbCode: "K08.1",
			order: 440,
		},
		{
			id: 441,
			categoryId: 81,
			name: "Удаление зуба перелом корня",
			categoryName: "Удаление зубов",
			specialty: "surgery",
			mkbCode: "K08.1",
			order: 441,
		},
		{
			id: 442,
			categoryId: 81,
			name: "Удаление зуба перелом коронки и корня",
			categoryName: "Удаление зубов",
			specialty: "surgery",
			mkbCode: "K02.1",
			order: 442,
		},
		{
			id: 443,
			categoryId: 81,
			name: "Удаление зуба периапикальный абсцесс без свища",
			categoryName: "Удаление зубов",
			specialty: "surgery",
			mkbCode: "K08.1",
			order: 443,
		},
		{
			id: 444,
			categoryId: 81,
			name: "Удаление зуба периапикальный абсцесс со свищом",
			categoryName: "Удаление зубов",
			specialty: "surgery",
			mkbCode: "K08.1",
			order: 444,
		},
		{
			id: 445,
			categoryId: 81,
			name: "Удаление зуба хронический периодонтит",
			categoryName: "Удаление зубов",
			specialty: "surgery",
			mkbCode: "K04.7",
			order: 445,
		},
		{
			id: 446,
			categoryId: 81,
			name: "Удаление зуба хронический периодонтит",
			categoryName: "Удаление зубов",
			specialty: "surgery",
			mkbCode: "K04.7",
			order: 446,
		},
		{
			id: 447,
			categoryId: 81,
			name: "Удаление зубов шаблон острый периодонтит",
			categoryName: "Удаление зубов",
			specialty: "surgery",
			mkbCode: "K04.7",
			order: 447,
		},
		{
			id: 448,
			categoryId: 82,
			name: "Установка формирователя десны",
			categoryName: "Формирователь десны",
			specialty: "implantology",
			mkbCode: "K08.1",
			order: 448,
		},
	];
