import type { StomxOutpatientTemplateMetadata } from "./stomtOutpatientCatalog.js";

/**
 * StomX Templates Metadata Part 4
 */
export const STOMX_TEMPLATES_PART_4: readonly StomxOutpatientTemplateMetadata[] =
	[
		{
			id: 226,
			categoryId: 61,
			name: "Лечение клиновидного дефекта реминерализацией",
			categoryName: "Некариозные поражения",
			specialty: "therapy",
			mkbCode: "K03.1",
			order: 226,
		},
		{
			id: 227,
			categoryId: 61,
			name: "Лечение повышенной стираемости зубов терапевтическое",
			categoryName: "Некариозные поражения",
			specialty: "therapy",
			mkbCode: "K02",
			order: 227,
		},
		{
			id: 228,
			categoryId: 61,
			name: "Лечение эрозии  1 степени реминерализацией",
			categoryName: "Некариозные поражения",
			specialty: "therapy",
			mkbCode: "K03.2",
			order: 228,
		},
		{
			id: 229,
			categoryId: 61,
			name: "Лечение эрозии 2-3 степени пломбой из композита",
			categoryName: "Некариозные поражения",
			specialty: "therapy",
			mkbCode: "K03.2",
			order: 229,
		},
		{
			id: 230,
			categoryId: 61,
			name: "Лечение эрозии 2-3 степени пломбой из СИЦ",
			categoryName: "Некариозные поражения",
			specialty: "therapy",
			mkbCode: "K03.2",
			order: 230,
		},
		{
			id: 231,
			categoryId: 61,
			name: "Лечение гипоплазии эмали пломбой",
			categoryName: "Некариозные поражения",
			specialty: "therapy",
			mkbCode: "K02",
			order: 231,
		},
		{
			id: 232,
			categoryId: 61,
			name: "Лечение флюороза пломбой",
			categoryName: "Некариозные поражения",
			specialty: "therapy",
			mkbCode: "K03.0",
			order: 232,
		},
		{
			id: 233,
			categoryId: 62,
			name: "  Домашнее отбеливание зубов с каппами - 1 посещение ",
			categoryName: "Отбеливание",
			specialty: "therapy",
			mkbCode: "K03.7",
			order: 233,
		},
		{
			id: 234,
			categoryId: 62,
			name: "  Домашнее отбеливание зубов с каппами 2 посещение",
			categoryName: "Отбеливание",
			specialty: "therapy",
			mkbCode: "K03.7",
			order: 234,
		},
		{
			id: 235,
			categoryId: 62,
			name: "Профессиональное отбеливание зубов офисное ",
			categoryName: "Отбеливание",
			specialty: "therapy",
			mkbCode: "K03.7",
			order: 235,
		},
		{
			id: 236,
			categoryId: 62,
			name: " Профессиональное отбеливание зубов офисное  (химическая активация препарата)",
			categoryName: "Отбеливание",
			specialty: "therapy",
			mkbCode: "K03.7",
			order: 236,
		},
		{
			id: 237,
			categoryId: 63,
			name: "Диагностическая ревизия корневых каналов при диагнозе хронический периодонтит",
			categoryName: "Периодонтит",
			specialty: "therapy",
			mkbCode: "K04.7",
			order: 237,
		},
		{
			id: 238,
			categoryId: 63,
			name: "Корневая киста первичное эндо - 1 посещение ",
			categoryName: "Периодонтит",
			specialty: "therapy",
			mkbCode: "K04.8",
			order: 238,
		},
		{
			id: 239,
			categoryId: 63,
			name: "Корневая киста первичное эндо - 2 посещение ",
			categoryName: "Периодонтит",
			specialty: "therapy",
			mkbCode: "K04.8",
			order: 239,
		},
		{
			id: 240,
			categoryId: 63,
			name: "Корневая киста повторное эндо - 1 посещение ",
			categoryName: "Периодонтит",
			specialty: "therapy",
			mkbCode: "K04.8",
			order: 240,
		},
		{
			id: 241,
			categoryId: 63,
			name: "Корневая киста повторное эндо - 2 посещение",
			categoryName: "Периодонтит",
			specialty: "therapy",
			mkbCode: "K04.8",
			order: 241,
		},
		{
			id: 242,
			categoryId: 63,
			name: "Лечение острого периодонтита пульпарного происхождения - 1 посещение ",
			categoryName: "Периодонтит",
			specialty: "therapy",
			mkbCode: "K04.7",
			order: 242,
		},
		{
			id: 243,
			categoryId: 63,
			name: "Лечение острого периодонтита пульпарного происхождения - 2 посещение ",
			categoryName: "Периодонтит",
			specialty: "therapy",
			mkbCode: "K04.7",
			order: 243,
		},
		{
			id: 244,
			categoryId: 63,
			name: "Лечение периапикального абсцесса без свища первичное эндо - 1 посещение ",
			categoryName: "Периодонтит",
			specialty: "therapy",
			mkbCode: "K12.2",
			order: 244,
		},
		{
			id: 245,
			categoryId: 63,
			name: "Лечение периапикального абсцесса без свища первичное эндо - 2 посещение ",
			categoryName: "Периодонтит",
			specialty: "therapy",
			mkbCode: "K12.2",
			order: 245,
		},
		{
			id: 246,
			categoryId: 63,
			name: "Лечение периапикального абсцесса со свищом первичное эндо зуба - 1 посещение",
			categoryName: "Периодонтит",
			specialty: "therapy",
			mkbCode: "K12.2",
			order: 246,
		},
		{
			id: 247,
			categoryId: 63,
			name: "Лечение периапикального абсцесса со свищом первичное эндо зуба - 2 посещение",
			categoryName: "Периодонтит",
			specialty: "therapy",
			mkbCode: "K12.2",
			order: 247,
		},
		{
			id: 248,
			categoryId: 63,
			name: "Лечение периапикального абсцесса со свищом повторное эндо - 1 посещение",
			categoryName: "Периодонтит",
			specialty: "therapy",
			mkbCode: "K12.2",
			order: 248,
		},
		{
			id: 249,
			categoryId: 63,
			name: "Лечение периапикального абсцесса со свищом повторное эндо - 2 посещение",
			categoryName: "Периодонтит",
			specialty: "therapy",
			mkbCode: "K12.2",
			order: 249,
		},
		{
			id: 250,
			categoryId: 63,
			name: "Лечение периодонтального абсцесса без свища повторное эндо - 1 посещение",
			categoryName: "Периодонтит",
			specialty: "therapy",
			mkbCode: "K12.2",
			order: 250,
		},
		{
			id: 251,
			categoryId: 63,
			name: "Лечение периодонтального абсцесса без свища повторное эндо - 2 посещение",
			categoryName: "Периодонтит",
			specialty: "therapy",
			mkbCode: "K12.2",
			order: 251,
		},
		{
			id: 252,
			categoryId: 63,
			name: "Лечение хронического периодонтита ранее леченного эндодонтически зуба - 1 посещение",
			categoryName: "Периодонтит",
			specialty: "therapy",
			mkbCode: "K04.7",
			order: 252,
		},
		{
			id: 253,
			categoryId: 63,
			name: "Лечение хронического периодонтита ранее леченного эндодонтически зуба - 2 посещение",
			categoryName: "Периодонтит",
			specialty: "therapy",
			mkbCode: "K04.7",
			order: 253,
		},
		{
			id: 254,
			categoryId: 63,
			name: "Лечение хронического периодонтита ранее не леченного эндодонтически зуба 1 посещение",
			categoryName: "Периодонтит",
			specialty: "therapy",
			mkbCode: "K04.7",
			order: 254,
		},
		{
			id: 255,
			categoryId: 63,
			name: "Лечение хронического периодонтита ранее не леченного эндодонтически зуба 2 посещение",
			categoryName: "Периодонтит",
			specialty: "therapy",
			mkbCode: "K04.7",
			order: 255,
		},
		{
			id: 256,
			categoryId: 63,
			name: "Лечение начального пульпита методом полного сохранения пульпы с восстановлением композитной пломбой в 1 посещения (непрямое покрытие ProRoot MTA ).",
			categoryName: "Периодонтит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 256,
		},
		{
			id: 257,
			categoryId: 63,
			name: "Лечение начального пульпита методом полного сохранения пульпы с восстановлением композитной пломбой в 1 посещения (прямое покрытие Biodentine).",
			categoryName: "Периодонтит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 257,
		},
		{
			id: 258,
			categoryId: 63,
			name: "Лечение начального пульпита методом полного сохранения пульпы с восстановлением композитной пломбой в 1 посещения (прямое покрытие ProRoot MTA ).",
			categoryName: "Периодонтит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 258,
		},
		{
			id: 259,
			categoryId: 63,
			name: "Лечение начального пульпита методом полного сохранения пульпы с восстановлением композитной пломбой в 2 посещения (непрямое покрытие Biodentine)  . 1 посещение",
			categoryName: "Периодонтит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 259,
		},
		{
			id: 260,
			categoryId: 63,
			name: "Лечение начального пульпита методом полного сохранения пульпы с восстановлением композитной пломбой в 2 посещения (непрямое покрытие Biodentine)  . 2 посещение",
			categoryName: "Периодонтит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 260,
		},
		{
			id: 261,
			categoryId: 64,
			name: "Лечение начального пульпита методом полного сохранения пульпы с восстановлением композитной пломбой в 1 посещения ",
			categoryName: "Пульпит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 261,
		},
		{
			id: 262,
			categoryId: 64,
			name: "Лечение начального пульпита методом полного сохранения пульпы с восстановлением композитной пломбой в 1 посещения (непрямое покрытие ProRoot MTA).",
			categoryName: "Пульпит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 262,
		},
		{
			id: 263,
			categoryId: 64,
			name: "Лечение начального пульпита методом полного сохранения пульпы с восстановлением композитной пломбой в 1 посещения (прямое покрытие Biodentine).",
			categoryName: "Пульпит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 263,
		},
		{
			id: 264,
			categoryId: 64,
			name: "Лечение начального пульпита методом полного сохранения пульпы с восстановлением композитной пломбой в 1 посещения (прямое покрытие ProRoot MTA).",
			categoryName: "Пульпит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 264,
		},
		{
			id: 265,
			categoryId: 64,
			name: "Лечение начального пульпита методом полного сохранения пульпы с восстановлением композитной пломбой в 2 посещения (непрямое покрытие Biodentine).",
			categoryName: "Пульпит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 265,
		},
		{
			id: 266,
			categoryId: 64,
			name: "Лечение начального пульпита методом полного сохранения пульпы с восстановлением композитной пломбой в 2 посещения (непрямое покрытие ProRoot MTA).",
			categoryName: "Пульпит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 266,
		},
		{
			id: 267,
			categoryId: 64,
			name: "Лечение начального пульпита методом полного сохранения пульпы с восстановлением композитной пломбой в 2 посещения (прямое покрытие ProRoot MTA).",
			categoryName: "Пульпит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 267,
		},
		{
			id: 268,
			categoryId: 64,
			name: "Лечение начального пульпита методом полного сохранения пульпы с восстановлением композитной пломбой в 2 посещения (прямое покрытие Biodentine).",
			categoryName: "Пульпит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 268,
		},
		{
			id: 269,
			categoryId: 64,
			name: "Лечение начального пульпита с исходом в острый пульпит композитной пломбой.",
			categoryName: "Пульпит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 269,
		},
		{
			id: 270,
			categoryId: 64,
			name: "Лечение начального пульпита методом полного сохранения пульпы с восстановлением композитной пломбой в 2 посещения.",
			categoryName: "Пульпит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 270,
		},
		{
			id: 271,
			categoryId: 64,
			name: "Лечение начального пульпита методом полного сохранения пульпы с восстановлением композитной пломбой в 1 посещения (непрямое покрытие Biodentine).",
			categoryName: "Пульпит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 271,
		},
		{
			id: 272,
			categoryId: 64,
			name: "Лечение начального пульпита методом полного сохранения пульпы с восстановлением композитной пломбой в 2 посещения (прямое покрытие ProRoot MTA ).",
			categoryName: "Пульпит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 272,
		},
		{
			id: 273,
			categoryId: 64,
			name: "Лечение начального пульпита методом полного сохранения пульпы с восстановлением композитной пломбой в 2 посещения (прямое покрытие ProRoot MTA ). 2 посещение ",
			categoryName: "Пульпит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 273,
		},
		{
			id: 274,
			categoryId: 64,
			name: "Лечение начального пульпита методом полного сохранения пульпы с восстановлением композитной пломбой в 2 посещения.",
			categoryName: "Пульпит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 274,
		},
		{
			id: 275,
			categoryId: 64,
			name: "Лечение начального пульпита методом полного сохранения пульпы с восстановлением композитной пломбой в 2 посещения. - 2 посещение",
			categoryName: "Пульпит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 275,
		},
		{
			id: 276,
			categoryId: 64,
			name: "Лечение начального пульпита с исходом в острый пульпит композитной пломбой.",
			categoryName: "Пульпит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 276,
		},
		{
			id: 277,
			categoryId: 64,
			name: "Лечение начального пульпита с исходом в острый пульпит композитной пломбой. 2 посещение",
			categoryName: "Пульпит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 277,
		},
		{
			id: 278,
			categoryId: 64,
			name: "Лечение гнойного пульпита методом витальной экстирпации 1 посещение",
			categoryName: "Пульпит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 278,
		},
		{
			id: 279,
			categoryId: 64,
			name: "Лечение гнойного пульпита методом витальной экстирпации 2 посещение",
			categoryName: "Пульпит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 279,
		},
		{
			id: 280,
			categoryId: 64,
			name: "Лечение острого пульпита методом Витальной ампутации",
			categoryName: "Пульпит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 280,
		},
		{
			id: 281,
			categoryId: 64,
			name: "Лечение острого пульпита методом Витальной ампутации 2 посещение",
			categoryName: "Пульпит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 281,
		},
		{
			id: 282,
			categoryId: 64,
			name: "Лечение острого пульпита методом витальной экстирпации",
			categoryName: "Пульпит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 282,
		},
		{
			id: 283,
			categoryId: 64,
			name: "Лечение острого пульпита методом витальной экстирпации 2 посещение",
			categoryName: "Пульпит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 283,
		},
		{
			id: 284,
			categoryId: 64,
			name: "Лечение острого пульпита методом девитальной экстирпации",
			categoryName: "Пульпит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 284,
		},
		{
			id: 285,
			categoryId: 64,
			name: "Лечение острого пульпита методом девитальной экстирпации 2 посещение",
			categoryName: "Пульпит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 285,
		},
		{
			id: 286,
			categoryId: 64,
			name: "Лечение острого пульпита методом девитальной экстирпации 3 посещение",
			categoryName: "Пульпит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 286,
		},
		{
			id: 287,
			categoryId: 64,
			name: "Лечение хронического гиперпластического пульпита методом витальной экстирпации",
			categoryName: "Пульпит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 287,
		},
		{
			id: 288,
			categoryId: 64,
			name: "Лечение хронического гиперпластического пульпита методом витальной экстирпации 2 посещение",
			categoryName: "Пульпит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 288,
		},
		{
			id: 289,
			categoryId: 64,
			name: "Лечение хронического пульпита методом витальной экстирпации",
			categoryName: "Пульпит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 289,
		},
		{
			id: 290,
			categoryId: 64,
			name: "Лечение хронического пульпита методом витальной экстирпации 2 посещение",
			categoryName: "Пульпит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 290,
		},
		{
			id: 291,
			categoryId: 64,
			name: "Лечение хронического пульпита методом девитальной экстирпации",
			categoryName: "Пульпит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 291,
		},
		{
			id: 292,
			categoryId: 64,
			name: "Лечение хронического пульпита методом девитальной экстирпации 2 посещение",
			categoryName: "Пульпит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 292,
		},
		{
			id: 293,
			categoryId: 64,
			name: "Лечение хронического язвенного пульпита методом витальной экстирпации",
			categoryName: "Пульпит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 293,
		},
		{
			id: 294,
			categoryId: 64,
			name: "Лечение хронического язвенного пульпита методом витальной экстирпации 2 посещения",
			categoryName: "Пульпит",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 294,
		},
		{
			id: 295,
			categoryId: 65,
			name: "Лечение перелома зуба без повреждения пульпы пломбой в 1 посещение",
			categoryName: "Травмы зубов",
			specialty: "therapy",
			mkbCode: "K02",
			order: 295,
		},
		{
			id: 296,
			categoryId: 65,
			name: "Лечение перелома зуба без повреждения пульпы пломбой в 2 посещения",
			categoryName: "Травмы зубов",
			specialty: "therapy",
			mkbCode: "K02",
			order: 296,
		},
		{
			id: 297,
			categoryId: 65,
			name: "Лечение перелома зуба без повреждения пульпы пломбой в 2 посещения 2 посещение",
			categoryName: "Травмы зубов",
			specialty: "therapy",
			mkbCode: "K02",
			order: 297,
		},
		{
			id: 298,
			categoryId: 65,
			name: "Лечение скола эмали методом приклеивания отломка",
			categoryName: "Травмы зубов",
			specialty: "therapy",
			mkbCode: "K02",
			order: 298,
		},
		{
			id: 299,
			categoryId: 65,
			name: "Лечение скола эмали методом шлифования и полирования дефекта",
			categoryName: "Травмы зубов",
			specialty: "therapy",
			mkbCode: "K02",
			order: 299,
		},
		{
			id: 300,
			categoryId: 65,
			name: "Лечение скола эмали пломбой",
			categoryName: "Травмы зубов",
			specialty: "therapy",
			mkbCode: "K02",
			order: 300,
		},
	];
