import type { StomxOutpatientTemplateMetadata } from "./stomtOutpatientCatalog.js";

/**
 * StomX Templates Metadata Part 1
 */
export const STOMX_TEMPLATES_PART_1: readonly StomxOutpatientTemplateMetadata[] =
	[
		{
			id: 1,
			categoryId: 2,
			name: "Внешний осмотр",
			categoryName: "Объективное обследование",
			specialty: "therapy",
			mkbCode: "K02",
			order: 1,
		},
		{
			id: 2,
			categoryId: 2,
			name: "Состояние СОПР",
			categoryName: "Объективное обследование",
			specialty: "therapy",
			mkbCode: "K02",
			order: 2,
		},
		{
			id: 3,
			categoryId: 2,
			name: "Височно-нижнечелюстной сустав",
			categoryName: "Объективное обследование",
			specialty: "therapy",
			mkbCode: "K02",
			order: 3,
		},
		{
			id: 4,
			categoryId: 4,
			name: "Хронический генерализованный пародонтит тяжелой ст.",
			categoryName: "Жалобы",
			specialty: "therapy",
			mkbCode: "K05.3",
			order: 4,
		},
		{
			id: 5,
			categoryId: 4,
			name: "Пульпит острый очаговый",
			categoryName: "Жалобы",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 5,
		},
		{
			id: 6,
			categoryId: 4,
			name: "Пульпит острый диффузный",
			categoryName: "Жалобы",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 6,
		},
		{
			id: 7,
			categoryId: 4,
			name: "Пульпит хронический фиброзный 1",
			categoryName: "Жалобы",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 7,
		},
		{
			id: 8,
			categoryId: 4,
			name: "Пульпит хронический фиброзный 2",
			categoryName: "Жалобы",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 8,
		},
		{
			id: 9,
			categoryId: 4,
			name: "Пульпит хронический гангренозный",
			categoryName: "Жалобы",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 9,
		},
		{
			id: 10,
			categoryId: 4,
			name: "Пульпит хронический гипертрофический",
			categoryName: "Жалобы",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 10,
		},
		{
			id: 11,
			categoryId: 4,
			name: "Обострение хронического пульпита",
			categoryName: "Жалобы",
			specialty: "therapy",
			mkbCode: "K04.0",
			order: 11,
		},
		{
			id: 12,
			categoryId: 4,
			name: "Состояние после частичного удаления пульпы 1",
			categoryName: "Жалобы",
			specialty: "therapy",
			mkbCode: "K08.1",
			order: 12,
		},
		{
			id: 13,
			categoryId: 4,
			name: "Состояние после частичного удаления пульпы 2",
			categoryName: "Жалобы",
			specialty: "therapy",
			mkbCode: "K08.1",
			order: 13,
		},
		{
			id: 14,
			categoryId: 4,
			name: "Состояние после полного удаления пульпы 1",
			categoryName: "Жалобы",
			specialty: "therapy",
			mkbCode: "K08.1",
			order: 14,
		},
		{
			id: 15,
			categoryId: 4,
			name: "Состояние после полного удаления пульпы 2",
			categoryName: "Жалобы",
			specialty: "therapy",
			mkbCode: "K08.1",
			order: 15,
		},
		{
			id: 16,
			categoryId: 4,
			name: "Периодонтит острый",
			categoryName: "Жалобы",
			specialty: "therapy",
			mkbCode: "K04.7",
			order: 16,
		},
		{
			id: 17,
			categoryId: 4,
			name: "Периодонтит хронический фиброзный 1",
			categoryName: "Жалобы",
			specialty: "therapy",
			mkbCode: "K04.7",
			order: 17,
		},
		{
			id: 18,
			categoryId: 4,
			name: "Периодонтит хронический фиброзный 1",
			categoryName: "Жалобы",
			specialty: "therapy",
			mkbCode: "K04.7",
			order: 18,
		},
		{
			id: 19,
			categoryId: 4,
			name: "Периодонтит хронический гранулирующий 1",
			categoryName: "Жалобы",
			specialty: "therapy",
			mkbCode: "K04.7",
			order: 19,
		},
		{
			id: 20,
			categoryId: 4,
			name: "Периодонтит хронический гранулирующий 2",
			categoryName: "Жалобы",
			specialty: "therapy",
			mkbCode: "K04.7",
			order: 20,
		},
		{
			id: 21,
			categoryId: 4,
			name: "Периодонтит хронический гранулематозный",
			categoryName: "Жалобы",
			specialty: "therapy",
			mkbCode: "K04.7",
			order: 21,
		},
		{
			id: 22,
			categoryId: 4,
			name: "Радикулярная киста",
			categoryName: "Жалобы",
			specialty: "therapy",
			mkbCode: "K04.8",
			order: 22,
		},
		{
			id: 23,
			categoryId: 4,
			name: "Гингивит хронический катаральный",
			categoryName: "Жалобы",
			specialty: "therapy",
			mkbCode: "K05.1",
			order: 23,
		},
		{
			id: 24,
			categoryId: 4,
			name: "Гингивит язвенно-некротический",
			categoryName: "Жалобы",
			specialty: "therapy",
			mkbCode: "K05.1",
			order: 24,
		},
		{
			id: 25,
			categoryId: 4,
			name: "Гингивит хронический гипертрофический",
			categoryName: "Жалобы",
			specialty: "therapy",
			mkbCode: "K05.1",
			order: 25,
		},
		{
			id: 26,
			categoryId: 4,
			name: "Хронический генерализованный пародонтит легкой ст.",
			categoryName: "Жалобы",
			specialty: "therapy",
			mkbCode: "K05.3",
			order: 26,
		},
		{
			id: 27,
			categoryId: 4,
			name: "Парадонтоз",
			categoryName: "Жалобы",
			specialty: "therapy",
			mkbCode: "K02",
			order: 27,
		},
		{
			id: 28,
			categoryId: 4,
			name: "Обострение генерализованного пародонтита. Абсцесс.",
			categoryName: "Жалобы",
			specialty: "therapy",
			mkbCode: "K12.2",
			order: 28,
		},
		{
			id: 29,
			categoryId: 4,
			name: "Кандидоз",
			categoryName: "Жалобы",
			specialty: "therapy",
			mkbCode: "K02",
			order: 29,
		},
		{
			id: 30,
			categoryId: 4,
			name: "Травматическая язва",
			categoryName: "Жалобы",
			specialty: "therapy",
			mkbCode: "K02",
			order: 30,
		},
		{
			id: 31,
			categoryId: 4,
			name: "Хронический рецидивирующий герпес",
			categoryName: "Жалобы",
			specialty: "therapy",
			mkbCode: "K02",
			order: 31,
		},
		{
			id: 32,
			categoryId: 4,
			name: "Хронический рецидивирующий афтозный стоматит",
			categoryName: "Жалобы",
			specialty: "therapy",
			mkbCode: "K02",
			order: 32,
		},
		{
			id: 33,
			categoryId: 4,
			name: "Плоский лишай",
			categoryName: "Жалобы",
			specialty: "therapy",
			mkbCode: "K02",
			order: 33,
		},
		{
			id: 34,
			categoryId: 4,
			name: "Лейкоплакия",
			categoryName: "Жалобы",
			specialty: "therapy",
			mkbCode: "K02",
			order: 34,
		},
		{
			id: 35,
			categoryId: 4,
			name: "Многоформная эксудативная эритема",
			categoryName: "Жалобы",
			specialty: "therapy",
			mkbCode: "K02",
			order: 35,
		},
		{
			id: 36,
			categoryId: 4,
			name: "Клиновидный дефект 1",
			categoryName: "Жалобы",
			specialty: "therapy",
			mkbCode: "K03.1",
			order: 36,
		},
		{
			id: 37,
			categoryId: 4,
			name: "Клиновидный дефект 2",
			categoryName: "Жалобы",
			specialty: "therapy",
			mkbCode: "K03.1",
			order: 37,
		},
		{
			id: 38,
			categoryId: 6,
			name: "Коронки 1",
			categoryName: "Жалобы",
			specialty: "orthopedics",
			mkbCode: "K02.1",
			order: 38,
		},
		{
			id: 39,
			categoryId: 6,
			name: "Коронки 2",
			categoryName: "Жалобы",
			specialty: "orthopedics",
			mkbCode: "K02.1",
			order: 39,
		},
		{
			id: 40,
			categoryId: 6,
			name: "Коронки 3",
			categoryName: "Жалобы",
			specialty: "orthopedics",
			mkbCode: "K02.1",
			order: 40,
		},
		{
			id: 41,
			categoryId: 6,
			name: "Коронки 4",
			categoryName: "Жалобы",
			specialty: "orthopedics",
			mkbCode: "K02.1",
			order: 41,
		},
		{
			id: 42,
			categoryId: 6,
			name: "Мостовидный протез 1",
			categoryName: "Жалобы",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 42,
		},
		{
			id: 43,
			categoryId: 6,
			name: "Мостовидный протез 2",
			categoryName: "Жалобы",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 43,
		},
		{
			id: 44,
			categoryId: 6,
			name: "Мостовидный протез 3",
			categoryName: "Жалобы",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 44,
		},
		{
			id: 45,
			categoryId: 6,
			name: "Мостовидный протез 4",
			categoryName: "Жалобы",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 45,
		},
		{
			id: 46,
			categoryId: 6,
			name: "Мостовидный протез 5",
			categoryName: "Жалобы",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 46,
		},
		{
			id: 47,
			categoryId: 6,
			name: "Бюгельные протезы 1",
			categoryName: "Жалобы",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 47,
		},
		{
			id: 48,
			categoryId: 6,
			name: "Бюгельные протезы 2",
			categoryName: "Жалобы",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 48,
		},
		{
			id: 49,
			categoryId: 6,
			name: "Бюгельные протезы 3",
			categoryName: "Жалобы",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 49,
		},
		{
			id: 50,
			categoryId: 6,
			name: "Бюгельные протезы 4",
			categoryName: "Жалобы",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 50,
		},
		{
			id: 51,
			categoryId: 6,
			name: "Съемные протезы 1",
			categoryName: "Жалобы",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 51,
		},
		{
			id: 52,
			categoryId: 6,
			name: "Съемные протезы 2",
			categoryName: "Жалобы",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 52,
		},
		{
			id: 53,
			categoryId: 6,
			name: "Съемные протезы 3",
			categoryName: "Жалобы",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 53,
		},
		{
			id: 54,
			categoryId: 6,
			name: "Съемные протезы 4",
			categoryName: "Жалобы",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 54,
		},
		{
			id: 55,
			categoryId: 6,
			name: "Съемные протезы 5",
			categoryName: "Жалобы",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 55,
		},
		{
			id: 56,
			categoryId: 6,
			name: "Съемные протезы 6",
			categoryName: "Жалобы",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 56,
		},
		{
			id: 57,
			categoryId: 6,
			name: "Съемные протезы 7",
			categoryName: "Жалобы",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 57,
		},
		{
			id: 58,
			categoryId: 6,
			name: "Шинирующий бюгельный протез с кламерами",
			categoryName: "Жалобы",
			specialty: "orthopedics",
			mkbCode: "K08.1",
			order: 58,
		},
		{
			id: 59,
			categoryId: 8,
			name: "Обострение Хронического Периодонтита",
			categoryName: "Жалобы",
			specialty: "surgery",
			mkbCode: "K04.7",
			order: 59,
		},
		{
			id: 60,
			categoryId: 8,
			name: "Острый гнойный периостит верхней челюсти",
			categoryName: "Жалобы",
			specialty: "surgery",
			mkbCode: "K10.2",
			order: 60,
		},
		{
			id: 61,
			categoryId: 8,
			name: "Острый гнойный периодонтит",
			categoryName: "Жалобы",
			specialty: "surgery",
			mkbCode: "K04.7",
			order: 61,
		},
		{
			id: 62,
			categoryId: 8,
			name: "Острый гнойный периостит нижней челюсти",
			categoryName: "Жалобы",
			specialty: "surgery",
			mkbCode: "K10.2",
			order: 62,
		},
		{
			id: 63,
			categoryId: 8,
			name: "Небный абсцесс",
			categoryName: "Жалобы",
			specialty: "surgery",
			mkbCode: "K12.2",
			order: 63,
		},
		{
			id: 64,
			categoryId: 8,
			name: "Одонтогенная кистогранулема",
			categoryName: "Жалобы",
			specialty: "surgery",
			mkbCode: "K04.8",
			order: 64,
		},
		{
			id: 65,
			categoryId: 8,
			name: "Полуретенция и дистопия зубов",
			categoryName: "Жалобы",
			specialty: "surgery",
			mkbCode: "K08.1",
			order: 65,
		},
		{
			id: 66,
			categoryId: 8,
			name: "Перикоронорит",
			categoryName: "Жалобы",
			specialty: "surgery",
			mkbCode: "K05.2",
			order: 66,
		},
		{
			id: 67,
			categoryId: 8,
			name: "Ретанционная киста малой слюнной железы",
			categoryName: "Жалобы",
			specialty: "surgery",
			mkbCode: "K04.8",
			order: 67,
		},
		{
			id: 68,
			categoryId: 8,
			name: "Папилома, Фиброма и др.новообразования языка",
			categoryName: "Жалобы",
			specialty: "surgery",
			mkbCode: "K08.1",
			order: 68,
		},
		{
			id: 69,
			categoryId: 8,
			name: "Эпулис",
			categoryName: "Жалобы",
			specialty: "surgery",
			mkbCode: "K08.1",
			order: 69,
		},
		{
			id: 70,
			categoryId: 8,
			name: "Радикулярная киста",
			categoryName: "Жалобы",
			specialty: "surgery",
			mkbCode: "K04.8",
			order: 70,
		},
		{
			id: 71,
			categoryId: 8,
			name: "Альвеолит",
			categoryName: "Жалобы",
			specialty: "surgery",
			mkbCode: "K10.3",
			order: 71,
		},
		{
			id: 72,
			categoryId: 8,
			name: "Слюннокаменая болезнь поднижнечелюстного протока",
			categoryName: "Жалобы",
			specialty: "surgery",
			mkbCode: "K08.1",
			order: 72,
		},
		{
			id: 73,
			categoryId: 8,
			name: "Абсцесс челюстно-язычного желобка",
			categoryName: "Жалобы",
			specialty: "surgery",
			mkbCode: "K12.2",
			order: 73,
		},
		{
			id: 74,
			categoryId: 8,
			name: "Абсцесс щечной области",
			categoryName: "Жалобы",
			specialty: "surgery",
			mkbCode: "K12.2",
			order: 74,
		},
		{
			id: 75,
			categoryId: 8,
			name: "Абсцесс крыловидно-нижнечелюстного пространства",
			categoryName: "Жалобы",
			specialty: "surgery",
			mkbCode: "K12.2",
			order: 75,
		},
	];
