import { useAppLogicContext } from "../../contexts/AppLogicContext";
import { useSettingsStore } from "../../store/settingsStore";
import { deriveBillingSettings } from "./billingDerivations";
import { deriveHardwareSettings } from "./hardwareDerivations";
import { deriveMigrationSettings } from "./migrationDerivations";
import { deriveScheduleSettings } from "./scheduleDerivations";
import { deriveStaffSettings } from "./staffDerivations";
import { deriveTelegramSettings } from "./telegramDerivations";

export function useSettingsDerivations() {
	const appLogic = useAppLogicContext();
	const settingsStore = useSettingsStore();

	const {
		activeWorkspaceProfile,
		cbctWorkbenchProjections,
		cbctWorkbenchSeries,
		cbctWorkbenchTools,
		clinicModeLabels,
		clinicProfileDraft,
		clinicProfileSaveState,
		clinicalRuleActionLabels,
		clinicalRuleSeverityLabels,
		clinicPublicLookup,
		ctPlanningActiveQuickActionId,
		ctPlanningImplantPlan,
		dashboard,
		defaultDicomFirstFrameViewerState,
		dicomFirstFramePreview,
		dicomFirstFrameViewerState,
		dicomFolderSeriesScan,
		dicomFolderWorkupPlan,
		dicomLocalFolderDiscovery,
		dicomRenderCachePlan,
		dicomSeriesPreview,
		dicomViewerToolStateBundle,
		dicomViewerWorkbenchManifest,
		dicomWebEndpointUrl,
		dicomWorkstationReadiness,
		discoverMigrationSources,
		documentIngestion,
		hiddenTelegramOutboxItemCount,
		imagingConnectorCards,
		imagingFolderScan,
		imagingFolderPath,
		imagingImportPreview,
		imagingImportText,
		imagingSourceChoices,
		imagingViewerActiveTool,
		imagingViewerCapabilities,
		importIntake,
		importPreview,
		importSourceLabels,
		importText,
		ingestionTargetLabels,
		isBrowserMigrationScanning,
		isClinicPublicLookupLoading,
		isDicomFirstFramePreviewing,
		isMigrationAutopilotLoading,
		isMigrationSourceDiscovering,
		isMigrationSourceProbeLoading,
		isMigrationSourceWorkupLoading,
		isSmartImportLoading,
		isTelegramLoading,
		isTelegramSendingDue,
		localBridgeReadiness,
		localBridgeUsePlans,
		localImagingFolderDraft,
		localImagingOrganizer,
		lookupClinicPublicProfile,
		migrationAutopilot,
		migrationSourceDiscovery,
		migrationSourceProbe,
		migrationSourceWorkup,
		mprAxisDeg,
		mprCrosshairEnabled,
		mprLinkedPlanesEnabled,
		mprProjection,
		mprProjectionLabels,
		mprSlabMm,
		mprSliceIndex,
		mprWindowPreset,
		mprWindowPresetLabels,
		newChairName,
		newStaffName,
		persistenceIntegrity,
		pickBrowserMigrationSource,
		planMigrationDiscoveryCandidate,
		previewMigrationAutopilotSources,
		probeMigrationDiscoveryCandidate,
		recognitionJob,
		recognitionPresets,
		recognitionText,
		runMigrationAutopilot,
		selectCtPlanningImplant,
		serviceCategoryLabels,
		setCtPlanningActiveQuickActionId,
		setDicomFirstFrameViewerState,
		setImagingViewerActiveTool,
		setMprAxisDeg,
		setMprCrosshairEnabled,
		setMprLinkedPlanesEnabled,
		setMprProjection,
		setMprSlabMm,
		setMprSliceIndex,
		setMprWindowPreset,
		setSmartImportMode,
		settingsTab,
		smartImportPreview,
		smartImportText,
		speechRecordingRecovery,
		telegramAdminSecretDraft,
		telegramChatLinks,
		telegramEnabledFeaturesDraft,
		telegramFeatureHelp,
		telegramFeatureOptions,
		telegramFeaturePlan,
		telegramInlineButtonKindLabels,
		telegramInlineButtonRowsFromReplyMarkup,
		telegramLinkCodes,
		telegramLinkStaffOptions,
		telegramOutbox,
		telegramOutboxStatusFilterOptions,
		telegramOutboxTemplateFilterOptions,
		telegramPostVisitCheckupDelayDrafts,
		telegramPostVisitCheckupDelayFields,
		telegramPreview,
		telegramSendingItemId,
		telegramStatus,
		telegramVisualCardFields,
		uiLanguageOptions,
		updateClinicProfileDraft,
		visibleTelegramOutboxItems,
		weekdayOptions,
		browserContinuityChecks,
		browserMigrationDiscovery,
		addMigrationDiscoveryCandidateToSmartImport,
	} = appLogic;

	const schedule = deriveScheduleSettings({
		clinicProfileSaveState,
		clinicModeLabels,
		dashboard,
		weekdayOptions,
		uiLanguageOptions,
	});

	const staff = deriveStaffSettings({
		newStaffName,
		newChairName,
		telegramAdminSecretDraft:
			telegramAdminSecretDraft || settingsStore.telegramAdminSecretDraft,
		settingsTab,
		dashboard,
		telegramLinkStaffOptions,
		activeWorkspaceProfile,
	});

	const billing = deriveBillingSettings({
		dashboard,
		clinicalRuleActionLabels,
		clinicalRuleSeverityLabels,
		serviceCategoryLabels,
	});

	const hardware = deriveHardwareSettings({
		dashboard,
		dicomWebEndpointUrl,
		recognitionText,
		imagingImportText,
		importText,
		imagingFolderPath,
		imagingConnectorCards,
		imagingViewerCapabilities,
		ctPlanningImplantPlan,
		ctPlanningActiveQuickActionId,
		imagingViewerActiveTool,
		recognitionPresets,
		recognitionJob,
		speechRecordingRecovery,
		imagingSourceChoices,
		imagingImportPreview,
		browserContinuityChecks,
		localBridgeReadiness,
		localBridgeUsePlans,
		persistenceIntegrity,
		dicomFirstFramePreview,
		dicomFirstFrameViewerState,
		defaultDicomFirstFrameViewerState,
		isDicomFirstFramePreviewing,
		dicomSeriesPreview,
		cbctWorkbenchSeries,
		dicomViewerWorkbenchManifest,
		dicomWorkstationReadiness,
		dicomRenderCachePlan,
		dicomViewerToolStateBundle,
		dicomLocalFolderDiscovery,
		localImagingOrganizer,
		localImagingFolderDraft,
		imagingFolderScan,
		dicomFolderSeriesScan,
		dicomFolderWorkupPlan,
		cbctWorkbenchTools,
		cbctWorkbenchProjections,
		mprSliceIndex,
		mprAxisDeg,
		mprSlabMm,
		mprProjection,
		mprWindowPreset,
		mprCrosshairEnabled,
		mprLinkedPlanesEnabled,
		mprProjectionLabels,
		mprWindowPresetLabels,
		setDicomFirstFrameViewerState,
		setMprProjection,
		setMprAxisDeg,
		setMprSlabMm,
		setMprSliceIndex,
		setMprWindowPreset,
		setMprCrosshairEnabled,
		setMprLinkedPlanesEnabled,
		setCtPlanningActiveQuickActionId,
		setImagingViewerActiveTool,
		selectCtPlanningImplant,
	});

	const telegram = deriveTelegramSettings({
		isTelegramLoading,
		isTelegramSendingDue,
		telegramSendingItemId,
		telegramChatLinks,
		telegramLinkCodes,
		telegramPreview,
		telegramOutbox,
		visibleTelegramOutboxItems,
		hiddenTelegramOutboxItemCount,
		telegramStatus,
		telegramOutboxStatusFilterOptions,
		telegramOutboxTemplateFilterOptions,
		telegramInlineButtonKindLabels,
		telegramFeaturePlan,
		telegramEnabledFeaturesDraft,
		telegramFeatureOptions,
		telegramFeatureHelp,
		telegramPostVisitCheckupDelayFields,
		telegramPostVisitCheckupDelayDrafts,
		telegramVisualCardFields,
		telegramInlineButtonRowsFromReplyMarkup,
	});

	const migration = deriveMigrationSettings({
		dashboard,
		smartImportText,
		clinicProfileDraft,
		migrationAutopilot,
		migrationSourceDiscovery,
		browserMigrationDiscovery,
		migrationSourceWorkup,
		migrationSourceProbe,
		clinicPublicLookup,
		smartImportPreview,
		importSourceLabels,
		ingestionTargetLabels,
		documentIngestion,
		importIntake,
		importPreview,
		updateClinicProfileDraft,
		setSmartImportMode,
		runMigrationAutopilot,
		discoverMigrationSources,
		pickBrowserMigrationSource,
		planMigrationDiscoveryCandidate,
		probeMigrationDiscoveryCandidate,
		addMigrationDiscoveryCandidateToSmartImport,
		lookupClinicPublicProfile,
		previewMigrationAutopilotSources,
		isMigrationSourceDiscovering,
		isBrowserMigrationScanning,
		isMigrationAutopilotLoading,
		isMigrationSourceWorkupLoading,
		isMigrationSourceProbeLoading,
		isSmartImportLoading,
		isClinicPublicLookupLoading,
	});

	return {
		...appLogic,
		...staff,
		...schedule,
		...telegram,
		dicomArchiveAddressGuidanceId: hardware.dicomArchiveAddressGuidanceId,
		localDicomFolderGuidanceId: hardware.localDicomFolderGuidanceId,
		migrationHandoffReportGuidanceId: migration.migrationHandoffReportGuidanceId,
		dicomArchiveAddressReady: hardware.dicomArchiveAddressReady,
		clinicLookupSuggestionFieldEntries: migration.clinicLookupSuggestionFieldEntries,
		clinicLookupSuggestionApplySummary: migration.clinicLookupSuggestionApplySummary,
		applyClinicLookupSuggestion: migration.applyClinicLookupSuggestion,
		clinicProfileSaveButtonText: schedule.clinicProfileSaveButtonText,
		typedMigrationAutopilot: migration.typedMigrationAutopilot,
		typedMigrationSourceDiscovery: migration.typedMigrationSourceDiscovery,
		activeMigrationDiscoveryForSettingsAutopilot:
			migration.activeMigrationDiscoveryForSettingsAutopilot,
		typedMigrationSourceWorkup: migration.typedMigrationSourceWorkup,
		typedMigrationSourceProbe: migration.typedMigrationSourceProbe,
		typedClinicPublicLookup: migration.typedClinicPublicLookup,
		typedDicomFirstFramePreview: hardware.typedDicomFirstFramePreview,
		typedDicomFirstFrameViewerState: hardware.typedDicomFirstFrameViewerState,
		typedDefaultDicomFirstFrameViewerState:
			hardware.typedDefaultDicomFirstFrameViewerState,
		dicomFirstFrameSelectableCount: hardware.dicomFirstFrameSelectableCount,
		dicomFirstFrameCurrentIndex: hardware.dicomFirstFrameCurrentIndex,
		dicomFirstFrameSliceMaxIndex: hardware.dicomFirstFrameSliceMaxIndex,
		dicomFirstFrameLandmarkSlices: hardware.dicomFirstFrameLandmarkSlices,
		dicomFirstFrameCanSelectPrevious: hardware.dicomFirstFrameCanSelectPrevious,
		dicomFirstFrameCanSelectNext: hardware.dicomFirstFrameCanSelectNext,
		typedDicomSeriesPreviewSeries: hardware.typedDicomSeriesPreviewSeries,
		typedDicomSeriesPreviewParserNotes: hardware.typedDicomSeriesPreviewParserNotes,
		typedCbctWorkbenchSeries: hardware.typedCbctWorkbenchSeries,
		typedDicomViewerWorkbenchManifest: hardware.typedDicomViewerWorkbenchManifest,
		typedDicomWorkstationReadiness: hardware.typedDicomWorkstationReadiness,
		typedDicomRenderCachePlan: hardware.typedDicomRenderCachePlan,
		typedDicomViewerToolStateBundle: hardware.typedDicomViewerToolStateBundle,
		typedDicomLocalFolderDiscovery: hardware.typedDicomLocalFolderDiscovery,
		typedLocalImagingOrganizer: hardware.typedLocalImagingOrganizer,
		typedImagingFolderScan: hardware.typedImagingFolderScan,
		typedDicomFolderSeriesScan: hardware.typedDicomFolderSeriesScan,
		typedDicomFolderWorkupPlan: hardware.typedDicomFolderWorkupPlan,
		typedCbctWorkbenchTools: hardware.typedCbctWorkbenchTools,
		typedCbctMprBlockers: hardware.typedCbctMprBlockers,
		typedCbctMprWarnings: hardware.typedCbctMprWarnings,
		typedCbctResourceSafetyCaps: hardware.typedCbctResourceSafetyCaps,
		mprControlsReady: hardware.mprControlsReady,
		mprSliceMaxIndex: hardware.mprSliceMaxIndex,
		mprCenterSliceIndex: hardware.mprCenterSliceIndex,
		typedCbctWorkbenchProjections: hardware.typedCbctWorkbenchProjections,
		mprSafeSliceIndex: hardware.mprSafeSliceIndex,
		updateDicomFirstFrameViewerState: hardware.updateDicomFirstFrameViewerState,
		updateDicomFirstFrameViewerNumber: hardware.updateDicomFirstFrameViewerNumber,
		typedMprProjection: hardware.typedMprProjection,
		mprAxisDirectionLabel: hardware.mprAxisDirectionLabel,
		mprAxisAngleBadge: hardware.mprAxisAngleBadge,
		mprSlabBadge: hardware.mprSlabBadge,
		mprSliceBadge: hardware.mprSliceBadge,
		mprSlabVisualWidth: hardware.mprSlabVisualWidth,
		mprSlicePositionPercent: hardware.mprSlicePositionPercent,
		mprCurrentSliceFraction: hardware.mprCurrentSliceFraction,
		mprSliceLabel: hardware.mprSliceLabel,
		mprAxisRangeValue: hardware.mprAxisRangeValue,
		mprSlabRangeValue: hardware.mprSlabRangeValue,
		mprSliceRangeValue: hardware.mprSliceRangeValue,
		mprActiveProjectionLabel: hardware.mprActiveProjectionLabel,
		mprActiveProjectionOrientation: hardware.mprActiveProjectionOrientation,
		mprProjectionCompass: hardware.mprProjectionCompass,
		mprAxisGuidance: hardware.mprAxisGuidance,
		mprNearestClinicalPreset: hardware.mprNearestClinicalPreset,
		mprClinicalInput: hardware.mprClinicalInput,
		mprWorkbenchSummaryText: hardware.mprWorkbenchSummaryText,
		mprOperatorSummaryCards: hardware.mprOperatorSummaryCards,
		mprAxisVisualizerLabel: hardware.mprAxisVisualizerLabel,
		mprClinicalChecklist: hardware.mprClinicalChecklist,
		mprClinicalNextStep: hardware.mprClinicalNextStep,
		mprClinicalPresetButtonClass: hardware.mprClinicalPresetButtonClass,
		resetMprControls: hardware.resetMprControls,
		applyMprClinicalPreset: hardware.applyMprClinicalPreset,
		applyCtPlanningQuickAction: hardware.applyCtPlanningQuickAction,
		selectCtPlanningImplantFromSettings:
			hardware.selectCtPlanningImplantFromSettings,
		applyNearestMprClinicalPreset: hardware.applyNearestMprClinicalPreset,
		handleMprKeyboardNavigation: hardware.handleMprKeyboardNavigation,
		typedMigrationAutopilotSources: migration.typedMigrationAutopilotSources,
		typedMigrationAutopilotClinicLookup:
			migration.typedMigrationAutopilotClinicLookup,
		typedMigrationAutopilotSteps: migration.typedMigrationAutopilotSteps,
		typedMigrationOperatorLanes: migration.typedMigrationOperatorLanes,
		typedMigrationHandoffChecklist: migration.typedMigrationHandoffChecklist,
		migrationDryRunSummary: migration.migrationDryRunSummary,
		migrationTriageItems: migration.migrationTriageItems,
		typedMigrationDiscoveryCandidates: migration.typedMigrationDiscoveryCandidates,
		typedMigrationWorkupReadinessIssues:
			migration.typedMigrationWorkupReadinessIssues,
		typedMigrationProbeReadinessIssues:
			migration.typedMigrationProbeReadinessIssues,
		typedClinicPublicLookupSuggestions:
			migration.typedClinicPublicLookupSuggestions,
		typedClinicPublicLookupTargets: migration.typedClinicPublicLookupTargets,
		migrationOperatorScriptSteps: migration.migrationOperatorScriptSteps,
		migrationPrimaryOperatorStep: migration.migrationPrimaryOperatorStep,
		migrationPrimaryOperatorCandidate: migration.migrationPrimaryOperatorCandidate,
		migrationCandidatePreviewReady: migration.migrationCandidatePreviewReady,
		migrationCandidatePreviewHint: migration.migrationCandidatePreviewHint,
		migrationPreviewableSourceCount: migration.migrationPreviewableSourceCount,
		migrationPreAutopilotSourceCount: migration.migrationPreAutopilotSourceCount,
		migrationKnownSourceCount: migration.migrationKnownSourceCount,
		migrationHandoffReportReady: migration.migrationHandoffReportReady,
		migrationPreviewReadyRows: migration.migrationPreviewReadyRows,
		migrationClinicLookupFieldCount: migration.migrationClinicLookupFieldCount,
		migrationSmartClinicFieldCount: migration.migrationSmartClinicFieldCount,
		migrationClinicFieldsFound: migration.migrationClinicFieldsFound,
		migrationProgressItems: migration.migrationProgressItems,
		focusSmartImportWorkbench: migration.focusSmartImportWorkbench,
		renderMigrationOperatorStepActions:
			migration.renderMigrationOperatorStepActions,
		renderMigrationTechnicalNotes: migration.renderMigrationTechnicalNotes,
		typedClinicalRuleActionLabels: billing.typedClinicalRuleActionLabels,
		typedClinicalRuleActions: billing.typedClinicalRuleActions,
		typedClinicalRuleSeverityLabels: billing.typedClinicalRuleSeverityLabels,
		typedClinicalRuleSeverities: billing.typedClinicalRuleSeverities,
		typedClinicalRules: billing.typedClinicalRules,
		typedServiceCatalog: billing.typedServiceCatalog,
		typedServiceCategoryLabels: billing.typedServiceCategoryLabels,
		typedServiceCategories: billing.typedServiceCategories,
	};
}

export * from "./complianceAnchors";
export type * from "./types";
export * from "./scheduleDerivations";
export * from "./staffDerivations";
export * from "./billingDerivations";
export * from "./hardwareDerivations";
export * from "./telegramDerivations";
export * from "./migrationDerivations";
