/**
 * ═══════════════════════════════════════════════════════════════════════════
 * CLINICAL DDI PHARMACOLOGICAL KNOWLEDGE BASE & CLASS MATCHERS
 * Evidence-based pharmacological classifications for dental pharmacotherapy
 * ═══════════════════════════════════════════════════════════════════════════
 */


export interface DrugClassMatcher {
	readonly classId: string;
	readonly labelRu: string;
	readonly keywords: readonly string[];
}

export const DRUG_CLASS_MATCHERS: readonly DrugClassMatcher[] = [
	{
		classId: "penicillin_beta_lactam",
		labelRu: "Пенициллины и бета-лактамы",
		keywords: [
			"amox",
			"амокс",
			"amoxicillin",
			"амоксициллин",
			"amoxiclav",
			"амоксиклав",
			"augmentin",
			"аугментин",
			"flemoxin",
			"флемоксин",
			"ampicillin",
			"ампициллин",
			"penicillin",
			"пенициллин",
			"пеницилин",
			"sultamicillin",
			"сультамициллин",
			"unasyn",
			"уназин",
			"cefal",
			"cefaz",
			"цефазолин",
			"цефалексин",
			"ceftriaxone",
			"цефтриаксон",
			"cefixime",
			"цефиксим",
			"suprax",
			"супракс",
			"бета-лактам",
			"beta_lactam",
		],
	},
	{
		classId: "nsaid",
		labelRu: "НПВС / Анальгетики-антипиретики",
		keywords: [
			"ibu",
			"ибупрофен",
			"ибуклин",
			"nurofen",
			"нурофен",
			"ketorol",
			"кеторолак",
			"ketorolac",
			"ketanov",
			"кетанов",
			"ketorol",
			"кеторол",
			"ketoprofen",
			"кетопрофен",
			"ketonal",
			"кетонал",
			"dexketoprofen",
			"декскетопрофен",
			"dexalgin",
			"дексалгин",
			"diclofenac",
			"диклофенак",
			"voltaren",
			"вольтарен",
			"nimesulide",
			"нимесулид",
			"nimesil",
			"нимесил",
			"nise",
			"найз",
			"meloxicam",
			"мелоксикам",
			"movalis",
			"мовалис",
			"aspirin",
			"аспирин",
			"ацетилсалициловая",
			"acetylsalicylic",
			"нпвс",
			"нпвп",
			"nsaid",
		],
	},
	{
		classId: "anticoagulant_antiplatelet",
		labelRu: "Антикоагулянты и дезагреганты",
		keywords: [
			"warfarin",
			"варфарин",
			"xarelto",
			"ксарелто",
			"rivaroxaban",
			"ривароксабан",
			"eliquis",
			"эликвис",
			"apixaban",
			"апиксабан",
			"pradaxa",
			"прадакса",
			"dabigatran",
			"дабигатран",
			"clopidogrel",
			"клопидогрел",
			"plavix",
			"плавикс",
			"brilinta",
			"брилинта",
			"ticagrelor",
			"тикагрелор",
			"heparin",
			"гепарин",
			"clexane",
			"клексан",
			"enoxaparin",
			"эноксапарин",
			"anticoagulant",
			"антикоагулянт",
			"дезагрегант",
			"doac",
			"поак",
		],
	},
	{
		classId: "metronidazole",
		labelRu: "Метронидазол / Нитроимидазолы",
		keywords: [
			"metron",
			"метронидазол",
			"трихопол",
			"trichopol",
			"flagyl",
			"флагил",
			"клион",
			"klion",
			"metrogyl",
			"метрогил",
		],
	},
	{
		classId: "epinephrine_anesthetic",
		labelRu: "Местные анестетики с эпинефрином (адреналином)",
		keywords: [
			"1:100",
			"1:200",
			"1:100000",
			"1:200000",
			"1:100 000",
			"1:200 000",
			"эпинефрин",
			"адреналин",
			"epinephrine",
			"adrenaline",
			"ultracain",
			"ультракаин",
			"septanest",
			"септанест",
			"ubistesin",
			"убистезин",
			"alphacaine",
			"альфакаин",
			"articaine_4_epi",
			"lidocaine_2_epi",
		],
	},
	{
		classId: "sulfite_preservative",
		labelRu: "Сульфиты / Метабисульфит натрия (E223)",
		keywords: [
			"сульфит",
			"метабисульфит",
			"дисульфит",
			"sulfite",
			"bisulfite",
			"metabisulfite",
			"e223",
		],
	},
	{
		classId: "beta_blocker_non_selective",
		labelRu: "Неселективные бета-адреноблокаторы",
		keywords: [
			"propranolol",
			"пропранолол",
			"anaprilin",
			"анаприлин",
			"sotalol",
			"соталол",
			"sotagamma",
			"сотагексал",
			"timolol",
			"тимолол",
			"non_selective_beta_blockers",
		],
	},
	{
		classId: "paracetamol",
		labelRu: "Парацетамол / Ацетаминофен",
		keywords: [
			"paracetamol",
			"парацетамол",
			"acetaminophen",
			"ацетаминофен",
			"panadol",
			"панадол",
			"efferalgan",
			"эффералган",
		],
	},
	{
		classId: "macrolide_lincosamide",
		labelRu: "Макролиды и линкозамиды",
		keywords: [
			"azithro",
			"азитромицин",
			"sumamed",
			"сумамед",
			"clindamycin",
			"клиндамицин",
			"dalacin",
			"далацин",
			"lincomycin",
			"линкомицин",
			"clarithro",
			"кларитромицин",
			"fromilid",
			"фромилид",
			"klacid",
			"клацид",
			"josamycin",
			"джозамицин",
			"vilprafen",
			"вильпрафен",
			"эритромицин",
			"erythromycin",
		],
	},
	{
		classId: "macrolide_cyp3a4_inhibitor",
		labelRu: "Макролиды — ингибиторы CYP3A4 (Кларитромицин, Эритромицин)",
		keywords: [
			"clarithro",
			"кларитромицин",
			"fromilid",
			"фромилид",
			"klacid",
			"клацид",
			"erythromycin",
			"эритромицин",
		],
	},
	{
		classId: "azalide_macrolide",
		labelRu: "Азалиды / Макролиды (Азитромицин)",
		keywords: [
			"azithro",
			"азитромицин",
			"sumamed",
			"сумамед",
			"azitral",
			"азитрал",
			"zitrolid",
			"зитролид",
			"josamycin",
			"джозамицин",
			"vilprafen",
			"вильпрафен",
		],
	},
	{
		classId: "lincosamide",
		labelRu: "Линкозамиды (Клиндамицин, Линкомицин)",
		keywords: [
			"clindamycin",
			"клиндамицин",
			"dalacin",
			"далацин",
			"lincomycin",
			"линкомицин",
			"клиндацин",
		],
	},
	{
		classId: "fluoroquinolone",
		labelRu: "Фторхинолоны (Ципрофлоксацин, Офлоксацин, Левофлоксацин)",
		keywords: [
			"cipro",
			"ципрофлоксацин",
			"ciprofloxacin",
			"ципролет",
			"цифран",
			"ofloxacin",
			"офлоксацин",
			"levofloxacin",
			"левофлоксацин",
			"tavanic",
			"таваник",
			"moxifloxacin",
			"моксифлоксацин",
			"avelox",
			"авелокс",
		],
	},
	{
		classId: "opioid_analgesic",
		labelRu: "Опиоидные анальгетики (Трамадол, Промедол)",
		keywords: [
			"tramadol",
			"трамадол",
			"tramal",
			"трамал",
			"promedol",
			"промедол",
			"опиоид",
		],
	},
	{
		classId: "benzodiazepine_sedative",
		labelRu: "Бензодиазепины и седативные (Диазепам, Реланиум, Феназепам)",
		keywords: [
			"diazepam",
			"диазепам",
			"relanium",
			"реланиум",
			"seduxen",
			"седуксен",
			"phenazepam",
			"феназепам",
			"бензодиазепин",
		],
	},
	{
		classId: "alcohol_ethanol",
		labelRu: "Алкоголь / Этанолсодержащие препараты",
		keywords: [
			"alcohol",
			"алкоголь",
			"этанол",
			"спирт",
			"настойка",
		],
	},
	{
		classId: "iodine_antiseptic",
		labelRu: "Препараты йода и йодоформа (Бетадин, Метапекс, Альвожил)",
		keywords: [
			"йод",
			"йодоформ",
			"повидон-йод",
			"povidone",
			"betadine",
			"бетадин",
			"metapex",
			"метапекс",
			"йодинол",
			"yodinol",
			"alveogyl",
			"альвожил",
			"люголь",
			"lugol",
			"iodine",
		],
	},
	{
		classId: "ester_anesthetic",
		labelRu: "Эфирные местные анестетики (Новокаин, Прокаин, Бензокаин, Дикаин)",
		keywords: [
			"novocaine",
			"новокаин",
			"procaine",
			"прокаин",
			"benzocaine",
			"бензокаин",
			"анестезин",
			"dicaine",
			"дикаин",
			"tetracaine",
			"тетракаин",
			"hurricaine",
			"харрикейн",
			"dispodent",
			"topex",
			"топекс",
			"дентинокс",
		],
	},
	{
		classId: "latex_material",
		labelRu: "Изделия из натурального латекса (перчатки, коффердам)",
		keywords: [
			"латекс",
			"latex",
			"коффердам латекс",
			"перчатки латекс",
		],
	},
	{
		classId: "mepivacaine_plain",
		labelRu: "Мепивакаин без вазоконстриктора",
		keywords: [
			"mepivacaine",
			"мепивакаин",
			"scandonest",
			"скандонест",
			"mepivastesin",
			"мепивастезин",
			"mepivacaine_3_plain",
			"скандонест 3%",
		],
	},
	{
		classId: "bisphosphonate_antiresorptive",
		labelRu: "Бисфосфонаты и антирезорбтивные препараты (Риск остеонекроза челюстей MRONJ/БРОНЖ)",
		keywords: [
			"zoledron",
			"золедронат",
			"золедроновая",
			"aclasta",
			"акласта",
			"zometa",
			"зомета",
			"alendron",
			"алендронат",
			"fosamax",
			"фосамакс",
			"ibandron",
			"ибандронат",
			"bonviva",
			"бонвива",
			"denosumab",
			"деносумаб",
			"prolia",
			"пролиа",
			"xgeva",
			"эксджива",
			"бисфосфонат",
			"bisphosphonate",
			"mronj",
			"бронж",
		],
	},
];


/**
 * Matches a string against pharmacological class definitions.
 */
export function matchDrugClasses(text: string): string[] {
	const lower = text.toLowerCase().trim();
	const matches: string[] = [];

	for (const matcher of DRUG_CLASS_MATCHERS) {
		if (matcher.keywords.some((kw) => lower.includes(kw))) {
			matches.push(matcher.classId);
		}
	}

	return matches;
}
