/**
 * packages/shared/src/clinical/stomtDefectsData.ts
 *
 * StomX Complete Tooth Defects Catalog & Hierarchical Tree Data.
 * Parity with StomX tooth_defects.json and tooth_defects_tree.json.
 *
 * Compliant with:
 * - Supreme Law: THE HAMMER (Zero Mocks, Absolute Parity)
 * - Mandate 8e: Doctor Autonomy
 * - Engineering Rule: Anti-monolith <= 800 lines
 */

import type { StomxToothDefect } from "./stomtDefectsCatalog.js";

/**
 * Полный каталог дефектов StomX с привязкой к CRM-состояниям зубной формулы.
 * Клинические нозологии (outpatient) и реставрации имеют приоритет перед аномалиями положения.
 */
export const STOMX_TOOTH_DEFECTS: readonly StomxToothDefect[] = [
	// 1. Здоров (Healthy)
	{
		id: 2,
		name: "здоров",
		alias: "ok",
		color: "green",
		order: 4,
		type: "outpatient",
		key: null,
		require_treatment: false,
		crmToothState: "Healthy",
		category: "healthy",
		description: "Здоровый интактный зуб без признаков патологии",
	},

	// 2. Нозологии, требующие лечения (require_treatment, color="red")
	{
		id: 10,
		name: "пародонтит",
		alias: "A",
		color: "red",
		order: 1000,
		type: "outpatient",
		key: "require_treatment",
		require_treatment: true,
		crmToothState: "Periodontitis",
		category: "pathology",
		description: "Пародонтит (стадии I–III)",
		items: [
			{
				id: 10,
				alias: "AI",
				name: "Пародонтит I степени",
				color: "red",
				order: 1000,
				type: "outpatient",
				number: "I",
			},
			{
				id: 11,
				alias: "AII",
				name: "Пародонтит II степени",
				color: "red",
				order: 1010,
				type: "outpatient",
				number: "II",
			},
			{
				id: 12,
				alias: "AIII",
				name: "Пародонтит III степени",
				color: "red",
				order: 1020,
				type: "outpatient",
				number: "III",
			},
		],
	},
	{
		id: 6,
		name: "кариес",
		alias: "С",
		color: "red",
		order: 1030,
		type: "outpatient",
		key: "require_treatment",
		require_treatment: true,
		crmToothState: "Caries",
		category: "pathology",
		description: "Кариес эмали / дентина (K02)",
	},
	{
		id: 7,
		name: "пульпит",
		alias: "Р",
		color: "red",
		order: 1040,
		type: "outpatient",
		key: "require_treatment",
		require_treatment: true,
		crmToothState: "Pulpitis",
		category: "pathology",
		description: "Пульпит зуба (K04.0)",
	},
	{
		id: 8,
		name: "периодонтит",
		alias: "Pt",
		color: "red",
		order: 1050,
		type: "outpatient",
		key: "require_treatment",
		require_treatment: true,
		crmToothState: "Periodontitis",
		category: "pathology",
		description: "Апикальный периодонтит (K04.4, K04.5)",
	},
	{
		id: 9,
		name: "корень",
		alias: "R",
		color: "red",
		order: 1060,
		type: "outpatient",
		key: "require_treatment",
		require_treatment: true,
		crmToothState: "Root",
		category: "pathology",
		description: "Разрушенный корень зуба, подлежащий лечению или удалению",
	},
	{
		id: 58,
		name: "кариес корня",
		alias: "CR",
		color: "red",
		order: 1070,
		type: "outpatient",
		key: "require_treatment",
		require_treatment: true,
		crmToothState: "Caries",
		category: "pathology",
		description: "Кариес корня / цемента зуба (K02.2)",
	},
	{
		id: 1,
		name: "отсутствует",
		alias: "О",
		color: "white",
		order: 1080,
		type: "outpatient",
		key: "require_treatment",
		require_treatment: true,
		crmToothState: "Missing",
		category: "pathology",
		description: "Отсутствующий зуб, требующий протезирования/имплантации",
	},
	{
		id: 59,
		name: "пигментация",
		alias: "Пг",
		color: "red",
		order: 1090,
		type: "outpatient",
		key: "require_treatment",
		require_treatment: true,
		category: "pathology",
		description: "Пигментация эмали / пятно",
	},
	{
		id: 60,
		name: "дефект пломбы",
		alias: "Дп",
		color: "red",
		order: 1100,
		type: "outpatient",
		key: "require_treatment",
		require_treatment: true,
		category: "pathology",
		description: "Нарушение краевого прилегания / вторичный кариес пломбы",
	},
	{
		id: 76,
		name: "дефект коронки",
		alias: "Дк",
		color: "red",
		order: 1110,
		type: "outpatient",
		key: "require_treatment",
		require_treatment: true,
		category: "pathology",
		description: "Скол облицовки или расцементировка коронки",
	},
	{
		id: 61,
		name: "клин дефект",
		alias: "Кд",
		color: "red",
		order: 1120,
		type: "outpatient",
		key: "require_treatment",
		require_treatment: true,
		category: "pathology",
		description: "Клиновидный дефект пришеечной области твердых тканей (K03.1)",
	},
	{
		id: 62,
		name: "гипоплазия",
		alias: "Г",
		color: "red",
		order: 1130,
		type: "outpatient",
		key: "require_treatment",
		require_treatment: true,
		category: "pathology",
		description: "Гипоплазия эмали (K00.4)",
	},
	{
		id: 63,
		name: "флюороз",
		alias: "Фл",
		color: "red",
		order: 1140,
		type: "outpatient",
		key: "require_treatment",
		require_treatment: true,
		category: "pathology",
		description: "Эндемический флюороз зубов (K00.3)",
	},
	{
		id: 78,
		name: "рецессия десны",
		alias: "Рд",
		color: "red",
		order: 1271,
		type: "outpatient",
		key: "require_treatment",
		require_treatment: true,
		category: "pathology",
		description: "Рецессия десны по Миллеру (классы 1–4)",
		items: [
			{
				id: 78,
				alias: "Рд1",
				name: "Рецессия десны 1 класс",
				color: "red",
				order: 1271,
				type: "outpatient",
				number: "1",
			},
			{
				id: 79,
				alias: "Рд2",
				name: "Рецессия десны 2 класс",
				color: "red",
				order: 1272,
				type: "outpatient",
				number: "2",
			},
			{
				id: 80,
				alias: "Рд3",
				name: "Рецессия десны 3 класс",
				color: "red",
				order: 1273,
				type: "outpatient",
				number: "3",
			},
			{
				id: 81,
				alias: "Рд4",
				name: "Рецессия десны 4 класс",
				color: "red",
				order: 1274,
				type: "outpatient",
				number: "4",
			},
		],
	},
	{
		id: 82,
		name: "гингивит",
		alias: "Гн",
		color: "red",
		order: 1275,
		type: "outpatient",
		key: "require_treatment",
		require_treatment: true,
		category: "pathology",
		description: "Катаральный или гипертрофический гингивит (K05.0, K05.1)",
	},
	{
		id: 83,
		name: "зубной камень",
		alias: "Зк",
		color: "red",
		order: 1276,
		type: "outpatient",
		key: "require_treatment",
		require_treatment: true,
		category: "pathology",
		description: "Наддесневые и поддесневые зубные отложения",
	},

	// 3. Вылеченные / Восстановленные зубы (cured_teeth, color="yellow")
	{
		id: 3,
		name: "пломба",
		alias: "П",
		color: "yellow",
		order: 1150,
		type: "outpatient",
		key: "cured_teeth",
		require_treatment: false,
		crmToothState: "Filled",
		category: "restoration",
		description: "Состоятельная пломба из композита или амальгамы",
	},
	{
		id: 90,
		name: "каналы лечены",
		alias: "Кл",
		color: "yellow",
		order: 1155,
		type: "outpatient",
		key: "cured_teeth",
		require_treatment: false,
		category: "restoration",
		description: "Ранее качественно обтурированные корневые каналы",
	},
	{
		id: 4,
		name: "коронка",
		alias: "К",
		color: "yellow",
		order: 1160,
		type: "outpatient",
		key: "cured_teeth",
		require_treatment: false,
		crmToothState: "Crown",
		category: "restoration",
		description: "Искусственная коронка (металлокерамика, цирконий, e.max)",
	},
	{
		id: 5,
		name: "искусственный",
		alias: "И",
		color: "yellow",
		order: 1170,
		type: "outpatient",
		key: "cured_teeth",
		require_treatment: false,
		category: "restoration",
		description: "Искусственный зуб мостовидного или съемного протеза",
	},
	{
		id: 13,
		name: "имплантат",
		alias: "ИМ",
		color: "yellow",
		order: 1180,
		type: "outpatient",
		key: "cured_teeth",
		require_treatment: false,
		crmToothState: "Implant",
		category: "restoration",
		description: "Остеоинтегрированный дентальный имплантат",
	},
	{
		id: 14,
		name: "винир",
		alias: "В",
		color: "yellow",
		order: 1190,
		type: "outpatient",
		key: "cured_teeth",
		require_treatment: false,
		category: "restoration",
		description: "Керамический или композитный винир",
	},
	{
		id: 15,
		name: "вкладка",
		alias: "ВК",
		color: "yellow",
		order: 1200,
		type: "outpatient",
		key: "cured_teeth",
		require_treatment: false,
		category: "restoration",
		description: "Культевая или восстановительная вкладка (inlay)",
	},
	{
		id: 91,
		name: "накладка",
		alias: "НК",
		color: "yellow",
		order: 1205,
		type: "outpatient",
		key: "cured_teeth",
		require_treatment: false,
		category: "restoration",
		description: "Окклюзионная накладка (onlay/overlay)",
	},
	{
		id: 64,
		name: "герм. фиссур",
		alias: "Гф",
		color: "yellow",
		order: 1210,
		type: "outpatient",
		key: "cured_teeth",
		require_treatment: false,
		category: "restoration",
		description: "Герметизация фиссур силантом",
	},
	{
		id: 65,
		name: "фасетка",
		alias: "Ф",
		color: "yellow",
		order: 1220,
		type: "outpatient",
		key: "cured_teeth",
		require_treatment: false,
		category: "restoration",
		description: "Фасетка мостовидного протеза",
	},

	// 4. Рентген / КЛКТ (rg_klkt, color=null)
	{
		id: 16,
		name: "дистопия",
		alias: "Д",
		color: null,
		order: 1230,
		type: "outpatient",
		key: "rg_klkt",
		require_treatment: true,
		crmToothState: "Retained",
		category: "radiology",
		description: "Дистопия зуба по рентгенологическим данным / КЛКТ",
	},
	{
		id: 17,
		name: "ретенция",
		alias: "Rt",
		color: null,
		order: 1240,
		type: "outpatient",
		key: "rg_klkt",
		require_treatment: true,
		crmToothState: "Retained",
		category: "radiology",
		description: "Ретенция зуба по рентгенологическим данным / КЛКТ",
	},
	{
		id: 18,
		name: "периодонтит",
		alias: "Pt",
		color: null,
		order: 1250,
		type: "outpatient",
		key: "rg_klkt",
		require_treatment: true,
		crmToothState: "Periodontitis",
		category: "radiology",
		description: "Периодонтит / деструкция кости по данным КЛКТ",
	},
	{
		id: 19,
		name: "кариес",
		alias: "С",
		color: null,
		order: 1260,
		type: "outpatient",
		key: "rg_klkt",
		require_treatment: true,
		crmToothState: "Caries",
		category: "radiology",
		description: "Скрытый проксимальный кариес по данным рентгена",
	},
	{
		id: 20,
		name: "отсутствует",
		alias: "О",
		color: null,
		order: 1270,
		type: "outpatient",
		key: "rg_klkt",
		require_treatment: true,
		crmToothState: "Missing",
		category: "radiology",
		description: "Отсутствие зуба / зачатка по рентгену",
	},

	// 5. Хирургическое удаление (medplan_only)
	{
		id: 1,
		name: "удаление",
		alias: "У",
		image_alias: "U",
		display_as: "removal",
		medplan_only: true,
		color: "white",
		key: "removal",
		order: 9999,
		type: "outpatient",
		require_treatment: true,
		crmToothState: "Missing",
		category: "surgery",
		description: "Назначено / запланировано удаление зуба",
	},

	// 6. Аномалии положения зуба (type="anomaly", key="position")
	{
		id: 38,
		name: "вестибулярное",
		alias: "В",
		color: "white",
		order: 200,
		type: "anomaly",
		key: "position",
		require_treatment: false,
		category: "position_anomaly",
		description: "Вестибулярное положение зуба",
	},
	{
		id: 39,
		name: "оральное",
		alias: "О",
		color: "white",
		order: 201,
		type: "anomaly",
		key: "position",
		require_treatment: false,
		category: "position_anomaly",
		description: "Оральное положение зуба",
	},
	{
		id: 40,
		name: "дистальное",
		alias: "Д",
		color: "white",
		order: 202,
		type: "anomaly",
		key: "position",
		require_treatment: false,
		category: "position_anomaly",
		description: "Дистальное положение зуба",
	},
	{
		id: 41,
		name: "мезиальное",
		alias: "М",
		color: "white",
		order: 203,
		type: "anomaly",
		key: "position",
		require_treatment: false,
		category: "position_anomaly",
		description: "Мезиальное положение зуба",
	},
	{
		id: 42,
		name: "супраположение",
		alias: "С",
		color: "white",
		order: 204,
		type: "anomaly",
		key: "position",
		require_treatment: false,
		category: "position_anomaly",
		description: "Супраположение зуба",
	},
	{
		id: 43,
		name: "инфраположение",
		alias: "И",
		color: "white",
		order: 205,
		type: "anomaly",
		key: "position",
		require_treatment: false,
		category: "position_anomaly",
		description: "Инфраположение зуба",
	},
	{
		id: 44,
		name: "тортоаномалия",
		alias: "Т",
		color: "white",
		order: 206,
		type: "anomaly",
		key: "position",
		require_treatment: false,
		category: "position_anomaly",
		description: "Тортоаномалия / тортоокклюзия зуба",
	},
	{
		id: 45,
		name: "транспозиция",
		alias: "Тр",
		color: "white",
		order: 207,
		type: "anomaly",
		key: "position",
		require_treatment: false,
		category: "position_anomaly",
		description: "Транспозиция зуба",
	},
	{
		id: 46,
		name: "протрузия",
		alias: "Пр",
		color: "white",
		order: 208,
		type: "anomaly",
		key: "position",
		require_treatment: false,
		category: "position_anomaly",
		description: "Протрузия резцов",
	},
	{
		id: 47,
		name: "ретрузия",
		alias: "Рт",
		color: "white",
		order: 209,
		type: "anomaly",
		key: "position",
		require_treatment: false,
		category: "position_anomaly",
		description: "Ретрузия резцов",
	},

	// 7. Аномалии прорезывания (time_cut)
	{
		id: 48,
		name: "ретенция",
		alias: "Rt",
		color: "white",
		order: 210,
		type: "anomaly",
		key: "time_cut",
		require_treatment: true,
		crmToothState: "Retained",
		category: "time_cut_anomaly",
		description: "Ретенция зуба",
	},
	{
		id: 49,
		name: "персистентный",
		alias: "П",
		color: "white",
		order: 211,
		type: "anomaly",
		key: "time_cut",
		require_treatment: false,
		category: "time_cut_anomaly",
		description: "Персистентный (задержавшийся) молочный зуб",
	},
	{
		id: 50,
		name: "ранее удаленный",
		alias: "РУ",
		color: "white",
		order: 212,
		type: "anomaly",
		key: "time_cut",
		require_treatment: false,
		crmToothState: "Missing",
		category: "time_cut_anomaly",
		description: "Ранее удаленный постоянный или молочный зуб",
	},

	// 8. Аномалии количества (amount)
	{
		id: 51,
		name: "адентия первичная",
		alias: "АД",
		color: "white",
		order: 213,
		type: "anomaly",
		key: "amount",
		require_treatment: true,
		crmToothState: "Missing",
		category: "amount_anomaly",
		description: "Врожденная первичная адентия",
	},
	{
		id: 52,
		name: "адентия вторичная",
		alias: "АВ",
		color: "white",
		order: 214,
		type: "anomaly",
		key: "amount",
		require_treatment: true,
		crmToothState: "Missing",
		category: "amount_anomaly",
		description: "Вторичная приобретенная адентия (потеря зуба)",
	},
	{
		id: 53,
		name: "сверхкомплектный",
		alias: "СК",
		color: "white",
		order: 215,
		type: "anomaly",
		key: "amount",
		require_treatment: true,
		category: "amount_anomaly",
		description: "Сверхкомплектный зуб",
	},
] as const;

/**
 * Иерархическое дерево дефектов StomX (tooth_defects_tree.json)
 */
export const STOMX_DEFECTS_TREE: readonly StomxToothDefect[] = [
	{ id: 2, name: "здоров", alias: "ok", color: "green", order: 4, type: "outpatient", key: null, require_treatment: false, crmToothState: "Healthy", category: "healthy" },
	{
		id: 10,
		name: "пародонтит",
		alias: "A",
		color: "red",
		order: 1000,
		type: "outpatient",
		key: "require_treatment",
		require_treatment: true,
		crmToothState: "Periodontitis",
		category: "pathology",
		items: [
			{ id: 10, alias: "AI", name: "пародонтит I ст.", color: "red", order: 1000, type: "outpatient", number: "I" },
			{ id: 11, alias: "AII", name: "пародонтит II ст.", color: "red", order: 1010, type: "outpatient", number: "II" },
			{ id: 12, alias: "AIII", name: "пародонтит III ст.", color: "red", order: 1020, type: "outpatient", number: "III" },
		],
	},
	{ id: 6, name: "кариес", alias: "С", color: "red", order: 1030, type: "outpatient", key: "require_treatment", require_treatment: true, crmToothState: "Caries", category: "pathology" },
	{ id: 7, name: "пульпит", alias: "Р", color: "red", order: 1040, type: "outpatient", key: "require_treatment", require_treatment: true, crmToothState: "Pulpitis", category: "pathology" },
	{ id: 8, name: "периодонтит", alias: "Pt", color: "red", order: 1050, type: "outpatient", key: "require_treatment", require_treatment: true, crmToothState: "Periodontitis", category: "pathology" },
	{ id: 9, name: "корень", alias: "R", color: "red", order: 1060, type: "outpatient", key: "require_treatment", require_treatment: true, crmToothState: "Root", category: "pathology" },
	{ id: 58, name: "кариес корня", alias: "CR", color: "red", order: 1070, type: "outpatient", key: "require_treatment", require_treatment: true, crmToothState: "Caries", category: "pathology" },
	{ id: 1, name: "отсутствует", alias: "О", color: "white", order: 1080, type: "outpatient", key: "require_treatment", require_treatment: true, crmToothState: "Missing", category: "pathology" },
	{ id: 59, name: "пигментация", alias: "Пг", color: "red", order: 1090, type: "outpatient", key: "require_treatment", require_treatment: true, category: "pathology" },
	{ id: 60, name: "дефект пломбы", alias: "Дп", color: "red", order: 1100, type: "outpatient", key: "require_treatment", require_treatment: true, category: "pathology" },
	{ id: 76, name: "дефект коронки", alias: "Дк", color: "red", order: 1110, type: "outpatient", key: "require_treatment", require_treatment: true, category: "pathology" },
	{ id: 61, name: "клин дефект", alias: "Кд", color: "red", order: 1120, type: "outpatient", key: "require_treatment", require_treatment: true, category: "pathology" },
	{ id: 62, name: "гипоплазия", alias: "Г", color: "red", order: 1130, type: "outpatient", key: "require_treatment", require_treatment: true, category: "pathology" },
	{ id: 63, name: "флюороз", alias: "Фл", color: "red", order: 1140, type: "outpatient", key: "require_treatment", require_treatment: true, category: "pathology" },
	{ id: 3, name: "пломба", alias: "П", color: "yellow", order: 1150, type: "outpatient", key: "cured_teeth", require_treatment: false, crmToothState: "Filled", category: "restoration" },
	{ id: 90, name: "каналы лечены", alias: "Кл", color: "yellow", order: 1155, type: "outpatient", key: "cured_teeth", require_treatment: false, category: "restoration" },
	{ id: 4, name: "коронка", alias: "К", color: "yellow", order: 1160, type: "outpatient", key: "cured_teeth", require_treatment: false, crmToothState: "Crown", category: "restoration" },
	{ id: 5, name: "искусственный", alias: "И", color: "yellow", order: 1170, type: "outpatient", key: "cured_teeth", require_treatment: false, category: "restoration" },
	{ id: 13, name: "имплантат", alias: "ИМ", color: "yellow", order: 1180, type: "outpatient", key: "cured_teeth", require_treatment: false, crmToothState: "Implant", category: "restoration" },
	{ id: 14, name: "винир", alias: "В", color: "yellow", order: 1190, type: "outpatient", key: "cured_teeth", require_treatment: false, category: "restoration" },
	{ id: 15, name: "вкладка", alias: "ВК", color: "yellow", order: 1200, type: "outpatient", key: "cured_teeth", require_treatment: false, category: "restoration" },
	{ id: 91, name: "накладка", alias: "НК", color: "yellow", order: 1205, type: "outpatient", key: "cured_teeth", require_treatment: false, category: "restoration" },
	{ id: 64, name: "герм. фиссур", alias: "Гф", color: "yellow", order: 1210, type: "outpatient", key: "cured_teeth", require_treatment: false, category: "restoration" },
	{ id: 65, name: "фасетка", alias: "Ф", color: "yellow", order: 1220, type: "outpatient", key: "cured_teeth", require_treatment: false, category: "restoration" },
	{ id: 16, name: "дистопия", alias: "Д", color: null, order: 1230, type: "outpatient", key: "rg_klkt", require_treatment: true, crmToothState: "Retained", category: "radiology" },
	{ id: 17, name: "ретенция", alias: "Rt", color: null, order: 1240, type: "outpatient", key: "rg_klkt", require_treatment: true, crmToothState: "Retained", category: "radiology" },
	{ id: 18, name: "периодонтит", alias: "Pt", color: null, order: 1250, type: "outpatient", key: "rg_klkt", require_treatment: true, crmToothState: "Periodontitis", category: "radiology" },
	{ id: 19, name: "кариес", alias: "С", color: null, order: 1260, type: "outpatient", key: "rg_klkt", require_treatment: true, crmToothState: "Caries", category: "radiology" },
	{ id: 20, name: "отсутствует", alias: "О", color: null, order: 1270, type: "outpatient", key: "rg_klkt", require_treatment: true, crmToothState: "Missing", category: "radiology" },
	{
		id: 78,
		name: "рецессия десны",
		alias: "Рд",
		color: "red",
		order: 1271,
		type: "outpatient",
		key: "require_treatment",
		require_treatment: true,
		category: "pathology",
		items: [
			{ id: 78, alias: "Рд1", name: "рецессия 1 класс", color: "red", order: 1271, type: "outpatient", number: "1" },
			{ id: 79, alias: "Рд2", name: "рецессия 2 класс", color: "red", order: 1272, type: "outpatient", number: "2" },
			{ id: 80, alias: "Рд3", name: "рецессия 3 класс", color: "red", order: 1273, type: "outpatient", number: "3" },
			{ id: 81, alias: "Рд4", name: "рецессия 4 класс", color: "red", order: 1274, type: "outpatient", number: "4" },
		],
	},
	{ id: 82, name: "гингивит", alias: "Гн", color: "red", order: 1275, type: "outpatient", key: "require_treatment", require_treatment: true, category: "pathology" },
	{ id: 83, name: "зубной камень", alias: "Зк", color: "red", order: 1276, type: "outpatient", key: "require_treatment", require_treatment: true, category: "pathology" },
	{ id: 1, name: "удаление", alias: "У", image_alias: "U", display_as: "removal", medplan_only: true, color: "white", key: "removal", order: 9999, type: "outpatient", require_treatment: true, crmToothState: "Missing", category: "surgery" },
] as const;
