import type { ThemeMode } from "../../store/themeStore";
import type {
	AdhesiveSystem,
	AnestheticKey,
	ClinicalMaterialOption,
	CompositeMaterial,
	DoctorSpecialtyKey,
	EtchantGel,
	IsolationType,
} from "../../store/doctorPreferencesStore";

export interface ThemeOptionItem {
	readonly mode: ThemeMode;
	readonly title: string;
	readonly desc: string;
	readonly badge: string;
	readonly previewColors: readonly [string, string, string];
}

export interface QuickProtocolItem {
	readonly id: string;
	readonly title: string;
	readonly icd: string;
}

export interface SpecialtyPresetItem {
	readonly key: DoctorSpecialtyKey;
	readonly label: string;
}

export const THEME_OPTIONS: readonly ThemeOptionItem[] = [
	{
		mode: "light",
		title: "Клиническая светлая",
		desc: "Высокая четкость при дневном свете кабинета",
		badge: "Стандарт",
		previewColors: ["#f8fafc", "#ffffff", "#0d9488"],
	},
	{
		mode: "dark",
		title: "Графит (Dark Slate)",
		desc: "Мягкая тёмная палитра для вечерних смен",
		badge: "Популярная",
		previewColors: ["#0f172a", "#1e293b", "#14b8a6"],
	},
	{
		mode: "night",
		title: "Ночь (OLED Warm Dark)",
		desc: "Ультра-тёмный теплый фон, минимум синего света",
		badge: "Щадящий свет",
		previewColors: ["#090d16", "#111827", "#10b981"],
	},
	{
		mode: "calm_teal",
		title: "Спокойная бирюза",
		desc: "Морской освежающий оттенок морской волны",
		badge: "Релакс",
		previewColors: ["#f0fdfa", "#ffffff", "#0f766e"],
	},
	{
		mode: "ocean",
		title: "Глубокий океан",
		desc: "Насыщенный сапфировый ультрамарин",
		badge: "Контраст",
		previewColors: ["#0b132b", "#1c2541", "#38bdf8"],
	},
	{
		mode: "emerald",
		title: "Изумрудный бор",
		desc: "Хвойный зеленый, успокаивающий зрение",
		badge: "Эко",
		previewColors: ["#061a14", "#0a2e23", "#10b981"],
	},
	{
		mode: "contrast",
		title: "Высокий контраст (WCAG AAA)",
		desc: "Максимальная видимость для слабовидящих",
		badge: "a11y",
		previewColors: ["#000000", "#18181b", "#fbbf24"],
	},
];

export const AVAILABLE_QUICK_PROTOCOLS: readonly QuickProtocolItem[] = [
	{ id: "caries_medium_k02_1", title: "Лечение среднего кариеса", icd: "К02.1" },
	{ id: "caries_deep_k02_1", title: "Лечение глубокого кариеса", icd: "К02.1" },
	{ id: "pulpitis_acute_k04_0", title: "Острый пульпит", icd: "К04.0" },
	{ id: "periodontitis_chronic_k04_5", title: "Хронический периодонтит", icd: "К04.5" },
	{ id: "extraction_simple_k08_1", title: "Удаление зуба простое", icd: "К08.1" },
	{ id: "extraction_complex_k01_1", title: "Сложное атипичное удаление", icd: "К01.1" },
	{ id: "implant_installation_k08_1", title: "Дентальная имплантация", icd: "К08.1" },
	{ id: "bone_graft_sinus_k08_2", title: "Костная пластика: Синус-лифтинг", icd: "К08.2" },
	{ id: "bone_graft_gbr_k08_2", title: "НКР альвеолярного гребня", icd: "К08.2" },
	{ id: "prophy_hygiene_k05_0", title: "Комплексная гигиена", icd: "К05.0" },
];

export const SPECIALTY_PRESET_ITEMS: readonly SpecialtyPresetItem[] = [
	{ key: "therapist", label: "Терапевт" },
	{ key: "surgeon", label: "Хирург-имплантолог" },
	{ key: "orthopedist", label: "Ортопед" },
	{ key: "orthodontist", label: "Ортодонт" },
	{ key: "pediatric", label: "Детский врач" },
	{ key: "universal", label: "Универсальный" },
];

export const ANESTHETIC_OPTIONS: readonly ClinicalMaterialOption<AnestheticKey>[] = [
	{
		id: "articaine_100k",
		key: "articaine_100k",
		name: "Ультракаин Д-С форте 1:100 000 (Sanofi)",
		title: "Артикаин 4% + Адреналин 1:100 000 (Ультракаин Форте / Септанест)",
		manufacturer: "Sanofi (Германия / Франция)",
		badge: "Норма (1:100k)",
		description: "Стандарт глубокого обезболивания: 1.7 мл, аспирация (-), для хирургии и пульпитов",
		hasAdrenaline: true,
		popularityRank: 1,
		isFavoriteDefault: true,
	},
	{
		id: "articaine_200k",
		key: "articaine_200k",
		name: "Ультракаин Д-С 1:200 000 (Sanofi)",
		title: "Артикаин 4% + Адреналин 1:200 000 (Ультракаин Д-С / Убистезин)",
		manufacturer: "Sanofi (Германия / Франция)",
		badge: "Щадящий (1:200k)",
		description: "Сниженная нагрузка на миокард и сосуды, препарат выбора для рутинной терапии",
		hasAdrenaline: true,
		popularityRank: 2,
		isFavoriteDefault: false,
	},
	{
		id: "septanest_100k",
		key: "septanest_100k",
		name: "Септанест 1:100 000 / 1:200 000 (Septodont)",
		title: "Септанест 1:100 000 / 1:200 000 (Артикаин)",
		manufacturer: "Septodont (Франция)",
		badge: "Septanest",
		description: "Французский артикаин с эпинефрином, быстрое наступление анестезии 1.7 мл",
		hasAdrenaline: true,
		popularityRank: 3,
		isFavoriteDefault: false,
	},
	{
		id: "ubistesin_forte",
		key: "ubistesin_forte",
		name: "Убистезин / Убистезин форте (3M)",
		title: "Убистезин / Убистезин форте (3M)",
		manufacturer: "3M (Германия)",
		badge: "Ubistesin",
		description: "Артикаин 4% с адреналином 1:100 000 / 1:200 000 в жестяных банках по 50 карпул",
		hasAdrenaline: true,
		popularityRank: 4,
		isFavoriteDefault: false,
	},
	{
		id: "articaine_binergia",
		key: "articaine_binergia",
		name: "Артикаин Бинергия / Артифрин (РФ)",
		title: "Артикаин Бинергия / Артифрин — РФ",
		manufacturer: "Бинергия / Фармстандарт (Россия)",
		badge: "РФ стандарт",
		description: "Отечественный артикаин 4% с адреналином высокой степени очистки, карпулы 1.7 мл",
		hasAdrenaline: true,
		popularityRank: 5,
		isFavoriteDefault: false,
	},
	{
		id: "scandonest_mepivacaine_3",
		key: "scandonest_mepivacaine_3",
		name: "Скандонест 3% Мепивакаин (Septodont)",
		title: "Мепивакаин / Скандонест 3% (без адреналина)",
		manufacturer: "Septodont (Франция)",
		badge: "Без адреналина",
		description: "Препарат выбора для гипертоников, глаукомы, ССЗ, беременных и аллергии на сульфиты",
		hasAdrenaline: false,
		popularityRank: 6,
		isFavoriteDefault: false,
	},
	{
		id: "mepivastesin_3",
		key: "mepivastesin_3",
		name: "Мепивастезин 3% без адреналина (3M)",
		title: "Мепивастезин 3% (Мепивакаин без адреналина)",
		manufacturer: "3M (Германия)",
		badge: "Мепивакаин 3M",
		description: "Мепивакаин 3% без вазоконстриктора, кардиоваскулярная безопасность",
		hasAdrenaline: false,
		popularityRank: 7,
		isFavoriteDefault: false,
	},
	{
		id: "lidocaine_2",
		key: "lidocaine_2",
		name: "Ксилонор 2% / Лидокаин 2% (Septodont / РФ)",
		title: "Ксилонор 2% / Лидокаин 2%",
		manufacturer: "Septodont / РФ",
		badge: "Лидокаин 2%",
		description: "Классический амидный анестетик для инфильтрации и мандибулярной анестезии",
		hasAdrenaline: false,
		popularityRank: 8,
		isFavoriteDefault: false,
	},
	{
		id: "topical_lidoxor",
		key: "topical_lidoxor",
		name: "Лидоксор гель / Дикаин / Дентинокс",
		title: "Дикаин / Лидоксор гель / Дентинокс",
		manufacturer: "Омега-Дент / ВладМиВа (Россия)",
		badge: "Аппликационный",
		description: "Аппликационное поверхностное обезболивание места вкола иглы, фруктовые вкусы",
		hasAdrenaline: false,
		popularityRank: 9,
		isFavoriteDefault: false,
	},
];

export const ISOLATION_OPTIONS: readonly ClinicalMaterialOption<IsolationType>[] = [
	{
		id: "cofferdam",
		key: "cofferdam",
		name: "Sanctuary Dental Dam (латекс/безлатекс)",
		title: "Коффердам (Sanctuary / Tor VM / Nic Tone)",
		manufacturer: "Sanctuary Health (Малайзия)",
		description: "Полная изоляция зуба платком и клампом — золотой стандарт эндодонтии и реставраций",
		popularityRank: 1,
		isFavoriteDefault: true,
		category: "Коффердам премиум",
	},
	{
		id: "cofferdam_tor_vm",
		key: "cofferdam_tor_vm",
		name: "Тор ВМ (платки, пробойник, клампы)",
		title: "Тор ВМ (платки, пробойник, клампы с крыльями и без)",
		manufacturer: "Тор ВМ (Россия)",
		description: "Отечественный стандарт раббердама: клампы с крыльями и без, рамки, пробойники",
		popularityRank: 2,
		isFavoriteDefault: false,
		category: "Раббердам РФ",
	},
	{
		id: "cofferdam_nic_tone",
		key: "cofferdam_nic_tone",
		name: "Nic Tone Dental Dam (высокая эластичность)",
		title: "Nic Tone Dental Dam (высокая эластичность на разрыв)",
		manufacturer: "MDC Dental (Мексика)",
		description: "Высококонтрастные платки с максимальной прочностью на разрыв для сложной изоляции",
		popularityRank: 3,
		isFavoriteDefault: false,
		category: "Высокая эластичность",
	},
	{
		id: "cofferdam_ksk_dentech",
		key: "cofferdam_ksk_dentech",
		name: "KSK Dentech (Япония)",
		title: "KSK Dentech (Япония)",
		manufacturer: "Dentech Corporation (Япония)",
		description: "Прецизионные клампы и тонкие эластичные завесы из японской пружинной стали",
		popularityRank: 4,
		isFavoriteDefault: false,
		category: "Премиум Япония",
	},
	{
		id: "optidam",
		key: "optidam",
		name: "OptiDam анатомический 3D (Kerr)",
		title: "OptiDam (Kerr) — анатомический 3D коффердам",
		manufacturer: "Kerr (США)",
		description: "Анатомический трехмерный коффердам с формованными выступами, быстрая установка",
		popularityRank: 5,
		isFavoriteDefault: false,
		category: "3D Анатомический",
	},
	{
		id: "liquid_dam",
		key: "liquid_dam",
		name: "Жидкий коффердам (OpalDam / LC Block-Out)",
		title: "Жидкий коффердам (гингивальный барьер)",
		manufacturer: "Ultradent (США)",
		description: "Светоотверждаемый полимерный барьер для защиты краевой десны и отбеливания",
		popularityRank: 6,
		isFavoriteDefault: false,
		category: "Гингивальный барьер",
	},
	{
		id: "optragate",
		key: "optragate",
		name: "ОптраГейт (OptraGate Ivoclar)",
		title: "ОптраГейт (OptraGate Ivoclar Vivadent)",
		manufacturer: "Ivoclar Vivadent (Лихтенштейн)",
		description: "Круговой мягкий безлатексный ретрактор губ и щек для реставраций и профгигиены",
		popularityRank: 7,
		isFavoriteDefault: false,
		category: "Ретрактор мягких тканей",
	},
	{
		id: "cotton_rolls",
		key: "cotton_rolls",
		name: "Ватные валики + слюноотсос",
		title: "Ватные валики + слюноотсос",
		manufacturer: "Стандарт (Россия / Германия)",
		description: "Базовая барьерная изоляция и постоянная аспирация слюны",
		popularityRank: 8,
		isFavoriteDefault: false,
		category: "Базовая изоляция",
	},
];

export const COMPOSITE_OPTIONS: readonly ClinicalMaterialOption<CompositeMaterial>[] = [
	{
		id: "filtek_ultimate",
		key: "filtek_ultimate",
		name: "Filtek Ultimate / Z250 / Z550 (3M ESPE)",
		title: "Filtek Ultimate / Z250 / Z550 (3M ESPE)",
		manufacturer: "3M ESPE (США)",
		description: "Наногибрид, универсал для всех групп зубов с высокой прочностью и стойким блеском",
		popularityRank: 1,
		isFavoriteDefault: false,
		category: "Наногибрид универсал",
	},
	{
		id: "estelite_asteria",
		key: "estelite_asteria",
		name: "Estelite Asteria / Sigma Quick (Tokuyama Dental)",
		title: "Estelite Asteria / Sigma Quick",
		manufacturer: "Tokuyama Dental (Япония)",
		description: "Субмикронный сферический наполнитель, непревзойденный эффект хамелеона",
		popularityRank: 2,
		isFavoriteDefault: true,
		category: "Субмикронный хамелеон",
	},
	{
		id: "gradia_direct",
		key: "gradia_direct",
		name: "Gradia Direct / G-aenial (GC)",
		title: "Gradia Direct / G-aenial (GC)",
		manufacturer: "GC (Япония)",
		description: "Микрогибридный композит с опалесценцией, естественная эстетика живого зуба",
		popularityRank: 3,
		isFavoriteDefault: false,
		category: "Микрогибрид",
	},
	{
		id: "harmonize",
		key: "harmonize",
		name: "Harmonize / Herculite Ultra (Kerr)",
		title: "Harmonize наногибридный (Kerr)",
		manufacturer: "Kerr (США)",
		description: "Наногибридный композит с технологией адаптивного отклика частиц ART",
		popularityRank: 4,
		isFavoriteDefault: false,
		category: "Наногибрид адаптивный",
	},
	{
		id: "charisma_classic",
		key: "charisma_classic",
		name: "Charisma Classic / Diamond (Kulzer)",
		title: "Charisma Classic / Diamond (Kulzer)",
		manufacturer: "Kulzer (Германия)",
		description: "Микрогибрид второго поколения Microglass II, высокая надежность и полируемость",
		popularityRank: 5,
		isFavoriteDefault: false,
		category: "Микрогибрид",
	},
	{
		id: "ceram_x_sphere_tec",
		key: "ceram_x_sphere_tec",
		name: "Ceram.x SphereTEC one / SDR Plus (Dentsply Sirona)",
		title: "Ceram.X SphereTEC One (Dentsply Sirona)",
		manufacturer: "Dentsply Sirona (Германия)",
		description: "Гранулированный сферический наполнитель SphereTEC, идеальная адаптация без прилипания",
		popularityRank: 6,
		isFavoriteDefault: false,
		category: "Сферический наполнитель",
	},
	{
		id: "brilliant_everglow",
		key: "brilliant_everglow",
		name: "Brilliant EverGlow (Coltene)",
		title: "Brilliant EverGlow (Coltene)",
		manufacturer: "Coltene (Швейцария)",
		description: "Субмикронный гибрид с легким моделированием и длительным сохранением зеркального блеска",
		popularityRank: 7,
		isFavoriteDefault: false,
		category: "Субмикронный гибрид",
	},
	{
		id: "tetric_n_ceram",
		key: "tetric_n_ceram",
		name: "Tetric N-Ceram / EvoCeram (Ivoclar Vivadent)",
		title: "Tetric N-Ceram / EvoCeram (Ivoclar)",
		manufacturer: "Ivoclar Vivadent (Лихтенштейн)",
		description: "Наногибрид с нано-оптимизированной матрицей для высокопрочных реставраций",
		popularityRank: 8,
		isFavoriteDefault: false,
		category: "Наногибрид",
	},
	{
		id: "omnichroma",
		key: "omnichroma",
		name: "Omnichroma (Tokuyama Dental)",
		title: "Omnichroma (Tokuyama Dental)",
		manufacturer: "Tokuyama Dental (Япония)",
		description: "Структурный цвет без добавления химических пигментов, один оттенок на все зубы",
		popularityRank: 9,
		isFavoriteDefault: false,
		category: "Структурный цвет",
	},
	{
		id: "esthet_x_hd",
		key: "esthet_x_hd",
		name: "Esthet-X HD (Dentsply Sirona)",
		title: "Esthet-X HD (Dentsply Sirona)",
		manufacturer: "Dentsply Sirona (США)",
		description: "Микроматричный композит высокой плотности для высокохудожественных реставраций",
		popularityRank: 10,
		isFavoriteDefault: false,
		category: "Микроматричный",
	},
	{
		id: "grandio_admira",
		key: "grandio_admira",
		name: "Grandio / Admira Fusion (Voco)",
		title: "Grandio / Admira Fusion (Voco)",
		manufacturer: "Voco (Германия)",
		description: "Ормокер на основе чистого кремния, наногибрид со сверхнизкой полимеризационной усадкой",
		popularityRank: 11,
		isFavoriteDefault: false,
		category: "Ормокер / Наногибрид",
	},
	{
		id: "enamel_plus_hri",
		key: "enamel_plus_hri",
		name: "Enamel Plus HRi (Micerium)",
		title: "Enamel Plus HRi (Micerium)",
		manufacturer: "Micerium (Италия)",
		description: "Высокоэстетичный композит со светопреломлением, строго идентичным натуральной эмали зуба",
		popularityRank: 12,
		isFavoriteDefault: false,
		category: "Эмалево-преломляющий",
	},
	{
		id: "clearfil_majesty_es2",
		key: "clearfil_majesty_es2",
		name: "Clearfil Majesty ES-2 (Kuraray Noritake)",
		title: "Clearfil Majesty ES-2 (Kuraray)",
		manufacturer: "Kuraray Noritake (Япония)",
		description: "Наногибридная точность подбора оттенков по шкале VITA с технологией светорассеяния",
		popularityRank: 13,
		isFavoriteDefault: false,
		category: "Наногибрид VITA",
	},
	{
		id: "spectrum_tph3",
		key: "spectrum_tph3",
		name: "Spectrum TPH3 (Dentsply Sirona)",
		title: "Spectrum TPH3 (Dentsply Sirona)",
		manufacturer: "Dentsply Sirona (Германия)",
		description: "Проверенный субмикронный гибридный композит для реставрации всех полостей I–V",
		popularityRank: 14,
		isFavoriteDefault: false,
		category: "Субмикронный гибрид",
	},
	{
		id: "dentlight",
		key: "dentlight",
		name: "ДентЛайт (ВладМиВа)",
		title: "ДентЛайт (ВладМиВа)",
		manufacturer: "ВладМиВа (Россия)",
		description: "Отечественный светоотверждаемый микрогибридный композит высокой прочности и рентгеноконтрастности",
		popularityRank: 15,
		isFavoriteDefault: false,
		category: "Микрогибрид РФ",
	},
	{
		id: "sdr_plus_bulk_fill",
		key: "sdr_plus_bulk_fill",
		name: "SDR Plus Bulk-Fill Flow (Dentsply Sirona)",
		title: "SDR Plus Bulk-Fill Flow",
		manufacturer: "Dentsply Sirona (Германия)",
		description: "Текучий базовый композит объемного внесения до 4 мм с эффектом самовыравнивания",
		popularityRank: 16,
		isFavoriteDefault: false,
		category: "Bulk-Fill Flow",
	},
];

export const ADHESIVE_OPTIONS: readonly ClinicalMaterialOption<AdhesiveSystem>[] = [
	{
		id: "optibond_fl",
		key: "optibond_fl",
		name: "OptiBond FL (Kerr) — IV поколение",
		title: "OptiBond FL (Kerr)",
		manufacturer: "Kerr (США)",
		generation: "IV поколение (золотой стандарт тотального протравливания)",
		description: "4-е поколение, 2 бутылька (праймер + адгезив с 48% наполнителем), эталон прочности",
		popularityRank: 1,
		isFavoriteDefault: true,
	},
	{
		id: "clearfil_se_bond_2",
		key: "clearfil_se_bond_2",
		name: "Clearfil SE Bond 2 (Kuraray) — VI поколение",
		title: "Clearfil SE Bond 2 (Kuraray)",
		manufacturer: "Kuraray Noritake (Япония)",
		generation: "VI поколение (двухэтапный самопротравливающий с 10-MDP)",
		description: "6-е поколение, самопротравливающий двухшаговый адгезив с оригинальным мономером 10-MDP",
		popularityRank: 2,
		isFavoriteDefault: false,
	},
	{
		id: "single_bond_universal",
		key: "single_bond_universal",
		name: "Single Bond Universal / Single Bond 2 (3M)",
		title: "Single Bond Universal (3M)",
		manufacturer: "3M (США)",
		generation: "VIII поколение (универсальный)",
		description: "5-е / 8-е универсальное поколение, совместим с тотальным, селективным и самопротравливанием",
		popularityRank: 3,
		isFavoriteDefault: false,
	},
	{
		id: "prime_and_bond_universal",
		key: "prime_and_bond_universal",
		name: "Prime & Bond Universal / NT (Dentsply Sirona)",
		title: "Prime&Bond Universal (Dentsply)",
		manufacturer: "Dentsply Sirona (Германия)",
		generation: "VIII поколение (универсальный)",
		description: "Универсальный адгезив с технологией Active-Guard для надежного сцепления при гипергидратации дентина",
		popularityRank: 4,
		isFavoriteDefault: false,
	},
	{
		id: "g_premio_bond",
		key: "g_premio_bond",
		name: "G-Premio BOND (GC) — универсальный",
		title: "G-Premio BOND (GC)",
		manufacturer: "GC (Япония)",
		generation: "VIII поколение (универсальный)",
		description: "Универсальный самопротравливающий адгезив с 3 мономерами (4-MET, MDP, MDTP), толщина пленки 3 мкм",
		popularityRank: 5,
		isFavoriteDefault: false,
	},
	{
		id: "optibond_universal",
		key: "optibond_universal",
		name: "OptiBond Universal / Solo Plus (Kerr)",
		title: "OptiBond Universal / Solo Plus (Kerr)",
		manufacturer: "Kerr (США)",
		generation: "VIII / V поколение",
		description: "Однокомпонентный универсальный адгезив с проверенной мономерной формулой OptiBond",
		popularityRank: 6,
		isFavoriteDefault: false,
	},
	{
		id: "gluma_2bond",
		key: "gluma_2bond",
		name: "Gluma 2Bond / Gluma Self Etch (Kulzer)",
		title: "Gluma 2Bond / Gluma Self Etch (Kulzer)",
		manufacturer: "Kulzer (Германия)",
		generation: "V / VII поколение",
		description: "Адгезивная система с десенсибилизирующим компонентом Gluma против постоперационной чувствительности",
		popularityRank: 7,
		isFavoriteDefault: false,
	},
	{
		id: "tokuyama_universal_bond",
		key: "tokuyama_universal_bond",
		name: "Tokuyama Universal Bond (Tokuyama)",
		title: "Tokuyama Universal Bond (Tokuyama)",
		manufacturer: "Tokuyama Dental (Япония)",
		generation: "VIII поколение (самоотверждаемый)",
		description: "Двухкомпонентный адгезив без светоотверждения, моментальное склеивание без ожидания",
		popularityRank: 8,
		isFavoriteDefault: false,
	},
	{
		id: "futurabond_u",
		key: "futurabond_u",
		name: "Futurabond U / M (Voco)",
		title: "Futurabond U / M (Voco)",
		manufacturer: "Voco (Германия)",
		generation: "VIII поколение (Dual-Cure)",
		description: "Универсальный адгезив двойного отверждения в практичных блистерах SingleDose",
		popularityRank: 9,
		isFavoriteDefault: false,
	},
	{
		id: "adhese_universal",
		key: "adhese_universal",
		name: "Adhese Universal (Ivoclar Vivadent)",
		title: "Adhese Universal (Ivoclar Vivadent)",
		manufacturer: "Ivoclar Vivadent (Лихтенштейн)",
		generation: "VIII поколение (ручка VivaPen)",
		description: "Универсальный адгезив в удобной ручке VivaPen с контролем капель и минимальным расходом",
		popularityRank: 10,
		isFavoriteDefault: false,
	},
	{
		id: "all_bond_universal",
		key: "all_bond_universal",
		name: "All-Bond Universal (Bisco)",
		title: "All-Bond Universal (Bisco)",
		manufacturer: "Bisco (США)",
		generation: "VIII поколение (Universal)",
		description: "Светоотверждаемый универсальный адгезив с pH > 3.0, совместим с композитами двойного отверждения",
		popularityRank: 11,
		isFavoriteDefault: false,
	},
];

export const ETCHANT_OPTIONS: readonly ClinicalMaterialOption<EtchantGel>[] = [
	{
		id: "ultra_etch",
		key: "ultra_etch",
		name: "Ultra-Etch 35% (Ultradent)",
		title: "Ultra-Etch (Ultradent)",
		manufacturer: "Ultradent (США)",
		description: "Самолимитирующийся тиксотропный 35% гель фосфорной кислоты, не проникает глубже нормы в дентин",
		popularityRank: 1,
		isFavoriteDefault: true,
		category: "Тиксотропный 35%",
	},
	{
		id: "scotchbond_etch",
		key: "scotchbond_etch",
		name: "Scotchbond Universal Etchant (3M)",
		title: "Scotchbond Universal Etchant (3M)",
		manufacturer: "3M (США)",
		description: "32% ортофосфорная кислота пониженной вязкости с четкой синей индикацией и легким смыванием",
		popularityRank: 2,
		isFavoriteDefault: false,
		category: "Универсальный 32%",
	},
	{
		id: "total_etch",
		key: "total_etch",
		name: "Total Etch 37% (Ivoclar Vivadent)",
		title: "Total Etch (Ivoclar)",
		manufacturer: "Ivoclar Vivadent (Лихтенштейн)",
		description: "37% ортофосфорная кислота классической вязкости для тотального и селективного травления",
		popularityRank: 3,
		isFavoriteDefault: false,
		category: "Классический 37%",
	},
	{
		id: "travis_vladmiva",
		key: "travis_vladmiva",
		name: "Травис 37% (ВладМиВа)",
		title: "Травис (ВладМиВа)",
		manufacturer: "ВладМиВа (Россия)",
		description: "Отечественный гель 37% ортофосфорной кислоты со стабилизированной формулой и контрастным цветом",
		popularityRank: 4,
		isFavoriteDefault: false,
		category: "Гель 37% РФ",
	},
];
