import React from "react";
import {
	MigrationAutopilotSection,
	MigrationDicomViewerSection,
	MigrationDiscoverySection,
	MigrationImagingDiscoverySection,
	MigrationImagingOrganizerSection,
	MigrationKickstartPanel,
	MigrationPreviewSection,
	MigrationProbeSection,
	MigrationWorkupSection,
	useSettingsImportsLogic,
} from "./imports";

export * from "./imports";

export function SettingsImportsTab(props: Record<string, any>) {
	const {
		addMigrationDiscoveryCandidateToSmartImport,
		browserDirectoryInputRef,
		browserDirectoryPickerAvailable,
		browserImagingFileInputAccept,
		browserImagingFilesInputRef,
		browserImagingScanProgress,
		browserMigrationInputRef,
		browserMigrationScanProgress,
		browserPickedImagingFolder,
		cancelBrowserImagingFolderScan,
		cancelBrowserMigrationScan,
		cancelLocalDicomOperation,
		clearBrowserPickedImagingFolderPreview,
		clearLocalImagingFolderRecovery,
		clinicProfileSaveState,
		clinicPublicLookup,
		commitImagingImport,
		commitImport,
		commitSmartImport,
		dicomFirstFrameImageStyle,
		dicomFirstFrameStatusLabels,
		dicomFolderWorkupPathLabels,
		dicomLabel,
		dicomSeriesPreview,
		dicomSeriesViewerLabels,
		dicomTextureStrategyLabels,
		discoverDicomFolders,
		discoverMigrationSources,
		documentDetectedKindLabel,
		documentIngestionQualityLabels,
		documentIngestionTarget,
		downloadMigrationHandoffReport,
		downloadSmartImportSafeHandoffReport,
		formatByteSize,
		formatDateTime,
		handleBrowserDirectoryInputChange,
		handleBrowserMigrationInputChange,
		imagingFolderPath,
		imagingImportCommit,
		imagingImportText,
		imagingKindLabels,
		importCommit,
		importSourceKind,
		importSourceLabels,
		importText,
		ingestImportFile,
		ingestionTargetLabels,
		isBrowserImagingFolderPicking,
		isBrowserMigrationScanning,
		isClinicPublicLookupLoading,
		isDicomFirstFramePreviewing,
		isDicomFolderWorkupPlanning,
		isDicomLocalDiscovering,
		isDicomSeriesPreviewLoading,
		isDicomWorkbenchBuilding,
		isDocumentIngesting,
		isImagingImportCommitting,
		isImagingImportLoading,
		isImportCommitting,
		isImportLoading,
		isLocalDicomOperationActive,
		isLocalImagingOrganizing,
		isMigrationAutopilotLoading,
		isMigrationSourceDiscovering,
		isMigrationSourceProbeLoading,
		isMigrationSourceWorkupLoading,
		isSmartImportCommitting,
		isSmartImportLoading,
		isSmartReportLoading,
		isSmartSafeReportLoading,
		localImagingFolderDraft,
		localImagingModelRoleLabels,
		localImagingOrganizerActionLabels,
		lookupClinicPublicProfile,
		mprLoadStrategyLabels,
		mprResourceTierLabels,
		organizeLocalImagingSources,
		pickBrowserImagingFiles,
		pickBrowserImagingFolder,
		pickBrowserMigrationSource,
		planMigrationDiscoveryCandidate,
		prepareDicomWorkbenchFromFolder,
		previewDicomFirstFrame,
		previewDicomFirstFrameSlice,
		previewDicomSeries,
		previewImagingImport,
		previewImport,
		previewMigrationAutopilotSources,
		previewMigrationDiscoveryCandidate,
		probeMigrationDiscoveryCandidate,
		rememberLocalImagingFolder,
		runMigrationAutopilot,
		saveClinicProfileFromDraft,
		setDicomFirstFramePreview,
		setDicomFirstFrameViewerState,
		setDicomFolderSeriesScan,
		setDicomFolderWorkupPlan,
		setDicomSeriesPreview,
		setDicomLocalFolderDiscovery,
		setDocumentIngestionTarget,
		setImagingFolderPath,
		setImagingFolderScan,
		setImagingImportCommit,
		setImagingImportPreview,
		setImagingImportSourceKind,
		setImagingImportText,
		setImportCommit,
		setImportIntake,
		setImportPreview,
		setImportSourceKind,
		setImportText,
		setLocalImagingOrganizer,
		settingsTab,
		smartImportCommit,
		stageLocalImagingFolderRecovery,
	} = props;

	const logic = useSettingsImportsLogic(props);

	return (
		<div className="settings-content" id="settings-tabpanel-imports">
			<MigrationKickstartPanel
				migrationAutopilot={logic.typedMigrationAutopilot}
				migrationProgressItems={logic.migrationProgressItems}
				migrationSourceDiscovery={logic.typedMigrationSourceDiscovery}
				typedBrowserMigrationDiscovery={logic.typedBrowserMigrationDiscovery}
				browserDirectoryPickerAvailable={browserDirectoryPickerAvailable}
				browserMigrationScanProgress={browserMigrationScanProgress}
				browserMigrationInputRef={browserMigrationInputRef}
				isMigrationSourceDiscovering={isMigrationSourceDiscovering}
				isMigrationAutopilotLoading={isMigrationAutopilotLoading}
				isBrowserMigrationScanning={isBrowserMigrationScanning}
				isClinicPublicLookupLoading={isClinicPublicLookupLoading}
				isSmartSafeReportLoading={isSmartSafeReportLoading}
				isSmartReportLoading={isSmartReportLoading}
				migrationHandoffReportReady={logic.migrationHandoffReportReady}
				discoverMigrationSources={discoverMigrationSources}
				pickBrowserMigrationSource={pickBrowserMigrationSource}
				cancelBrowserMigrationScan={cancelBrowserMigrationScan}
				runMigrationAutopilot={runMigrationAutopilot}
				lookupClinicPublicProfile={lookupClinicPublicProfile}
				handleBrowserMigrationInputChange={handleBrowserMigrationInputChange}
				downloadSmartImportSafeHandoffReport={downloadSmartImportSafeHandoffReport}
				downloadMigrationHandoffReport={downloadMigrationHandoffReport}
				focusSmartImportWorkbench={logic.focusSmartImportWorkbench}
			/>

			<MigrationAutopilotSection
				migrationAutopilot={logic.typedMigrationAutopilot}
				typedMigrationAutopilotSources={logic.typedMigrationAutopilotSources}
				typedMigrationAutopilotClinicLookup={logic.typedMigrationAutopilotClinicLookup}
				typedMigrationAutopilotSteps={logic.typedMigrationAutopilotSteps}
				typedMigrationOperatorLanes={logic.typedMigrationOperatorLanes}
				typedMigrationHandoffChecklist={logic.typedMigrationHandoffChecklist}
				migrationDryRunSummary={logic.migrationDryRunSummary}
				migrationTriageItems={logic.migrationTriageItems}
				migrationOperatorScriptSteps={logic.migrationOperatorScriptSteps}
				migrationPrimaryOperatorStep={logic.migrationPrimaryOperatorStep}
				migrationPrimaryOperatorCandidate={logic.migrationPrimaryOperatorCandidate}
				migrationCandidatePreviewReady={logic.migrationCandidatePreviewReady}
				migrationCandidatePreviewHint={logic.migrationCandidatePreviewHint}
				smartImportInputReady={logic.smartImportInputReady}
				isMigrationAutopilotLoading={isMigrationAutopilotLoading}
				isMigrationSourceDiscovering={isMigrationSourceDiscovering}
				isBrowserMigrationScanning={isBrowserMigrationScanning}
				isMigrationSourceWorkupLoading={isMigrationSourceWorkupLoading}
				isMigrationSourceProbeLoading={isMigrationSourceProbeLoading}
				isClinicPublicLookupLoading={isClinicPublicLookupLoading}
				isSmartImportLoading={isSmartImportLoading}
				clinicProfileSaveState={clinicProfileSaveState}
				clinicProfileSaveButtonText={logic.clinicProfileSaveButtonText}
				runMigrationAutopilot={runMigrationAutopilot}
				discoverMigrationSources={discoverMigrationSources}
				pickBrowserMigrationSource={pickBrowserMigrationSource}
				lookupClinicPublicProfile={lookupClinicPublicProfile}
				planMigrationDiscoveryCandidate={planMigrationDiscoveryCandidate}
				probeMigrationDiscoveryCandidate={probeMigrationDiscoveryCandidate}
				addMigrationDiscoveryCandidateToSmartImport={addMigrationDiscoveryCandidateToSmartImport}
				previewMigrationDiscoveryCandidate={previewMigrationDiscoveryCandidate}
				previewMigrationAutopilotSources={previewMigrationAutopilotSources}
				saveClinicProfileFromDraft={saveClinicProfileFromDraft}
				applyClinicLookupSuggestion={logic.applyClinicLookupSuggestion}
				clinicLookupSuggestionFieldEntries={logic.clinicLookupSuggestionFieldEntries}
				clinicLookupSuggestionApplySummary={logic.clinicLookupSuggestionApplySummary}
			/>

			<MigrationDiscoverySection
				typedMigrationSourceDiscovery={logic.typedMigrationSourceDiscovery}
				typedMigrationDiscoveryCandidates={logic.typedMigrationDiscoveryCandidates}
				migrationAutopilot={logic.typedMigrationAutopilot}
				isMigrationSourceWorkupLoading={isMigrationSourceWorkupLoading}
				isMigrationSourceProbeLoading={isMigrationSourceProbeLoading}
				isSmartImportLoading={isSmartImportLoading}
				isBrowserMigrationScanning={isBrowserMigrationScanning}
				isMigrationAutopilotLoading={isMigrationAutopilotLoading}
				isClinicPublicLookupLoading={isClinicPublicLookupLoading}
				formatDateTime={formatDateTime}
				migrationCandidatePreviewReady={logic.migrationCandidatePreviewReady}
				migrationCandidatePreviewHint={logic.migrationCandidatePreviewHint}
				planMigrationDiscoveryCandidate={planMigrationDiscoveryCandidate}
				probeMigrationDiscoveryCandidate={probeMigrationDiscoveryCandidate}
				addMigrationDiscoveryCandidateToSmartImport={addMigrationDiscoveryCandidateToSmartImport}
				previewMigrationDiscoveryCandidate={previewMigrationDiscoveryCandidate}
				pickBrowserMigrationSource={pickBrowserMigrationSource}
				focusSmartImportWorkbench={logic.focusSmartImportWorkbench}
				lookupClinicPublicProfile={lookupClinicPublicProfile}
			/>

			<MigrationWorkupSection
				typedMigrationSourceWorkup={logic.typedMigrationSourceWorkup}
				typedMigrationWorkupReadinessIssues={logic.typedMigrationWorkupReadinessIssues}
			/>

			<MigrationProbeSection
				typedMigrationSourceProbe={logic.typedMigrationSourceProbe}
				typedMigrationProbeReadinessIssues={logic.typedMigrationProbeReadinessIssues}
				clinicPublicLookup={clinicPublicLookup}
				typedClinicPublicLookupSuggestions={logic.typedClinicPublicLookupSuggestions}
				typedClinicPublicLookupTargets={logic.typedClinicPublicLookupTargets}
				typedSmartImportPreview={logic.typedSmartImportPreview}
				smartImportCommit={smartImportCommit}
				smartImportInputReady={logic.smartImportInputReady}
				isSmartImportCommitting={isSmartImportCommitting}
				clinicProfileSaveState={clinicProfileSaveState}
				clinicProfileSaveButtonText={logic.clinicProfileSaveButtonText}
				formatByteSize={formatByteSize}
				applyClinicLookupSuggestion={logic.applyClinicLookupSuggestion}
				clinicLookupSuggestionFieldEntries={logic.clinicLookupSuggestionFieldEntries}
				clinicLookupSuggestionApplySummary={logic.clinicLookupSuggestionApplySummary}
				saveClinicProfileFromDraft={saveClinicProfileFromDraft}
				commitSmartImport={commitSmartImport}
			/>

			<MigrationImagingDiscoverySection
				settingsTab={settingsTab}
				typedImagingSourceChoices={logic.typedImagingSourceChoices}
				imagingImportSourceKind={props.imagingImportSourceKind}
				imagingSourceLabels={props.imagingSourceLabels}
				imagingSourceDetails={props.imagingSourceDetails}
				imagingFolderPath={imagingFolderPath}
				localImagingFolderDraft={localImagingFolderDraft}
				browserDirectoryPickerAvailable={browserDirectoryPickerAvailable}
				browserImagingFileInputAccept={browserImagingFileInputAccept}
				browserImagingScanProgress={browserImagingScanProgress}
				isBrowserImagingFolderPicking={isBrowserImagingFolderPicking}
				isLocalDicomOperationActive={isLocalDicomOperationActive}
				isDicomLocalDiscovering={isDicomLocalDiscovering}
				isLocalImagingOrganizing={isLocalImagingOrganizing}
				isDicomFirstFramePreviewing={isDicomFirstFramePreviewing}
				isDicomFolderWorkupPlanning={isDicomFolderWorkupPlanning}
				isDicomWorkbenchBuilding={isDicomWorkbenchBuilding}
				browserPickedImagingFolder={browserPickedImagingFolder}
				typedDicomLocalFolderDiscovery={logic.typedDicomLocalFolderDiscovery}
				browserDirectoryInputRef={browserDirectoryInputRef}
				browserImagingFilesInputRef={browserImagingFilesInputRef}
				setImagingImportSourceKind={setImagingImportSourceKind}
				setImagingImportPreview={setImagingImportPreview}
				setImagingImportCommit={setImagingImportCommit}
				setImagingFolderPath={setImagingFolderPath}
				stageLocalImagingFolderRecovery={stageLocalImagingFolderRecovery}
				rememberLocalImagingFolder={rememberLocalImagingFolder}
				clearLocalImagingFolderRecovery={clearLocalImagingFolderRecovery}
				setImagingFolderScan={setImagingFolderScan}
				setDicomFolderSeriesScan={setDicomFolderSeriesScan}
				setDicomFolderWorkupPlan={setDicomFolderWorkupPlan}
				setDicomFirstFramePreview={setDicomFirstFramePreview}
				setDicomLocalFolderDiscovery={setDicomLocalFolderDiscovery}
				setLocalImagingOrganizer={setLocalImagingOrganizer}
				handleBrowserDirectoryInputChange={handleBrowserDirectoryInputChange}
				pickBrowserImagingFolder={pickBrowserImagingFolder}
				pickBrowserImagingFiles={pickBrowserImagingFiles}
				cancelBrowserImagingFolderScan={cancelBrowserImagingFolderScan}
				cancelLocalDicomOperation={cancelLocalDicomOperation}
				discoverDicomFolders={discoverDicomFolders}
				organizeLocalImagingSources={organizeLocalImagingSources}
				previewDicomFirstFrame={previewDicomFirstFrame}
				prepareDicomWorkbenchFromFolder={prepareDicomWorkbenchFromFolder}
				clearBrowserPickedImagingFolderPreview={clearBrowserPickedImagingFolderPreview}
			/>

			<MigrationImagingOrganizerSection
				typedLocalImagingOrganizer={logic.typedLocalImagingOrganizer}
				typedImagingFolderScan={logic.typedImagingFolderScan}
				typedDicomFolderSeriesScan={logic.typedDicomFolderSeriesScan}
				typedDicomFolderWorkupPlan={logic.typedDicomFolderWorkupPlan}
				localImagingOrganizerActionLabels={localImagingOrganizerActionLabels}
				localImagingModelRoleLabels={localImagingModelRoleLabels}
				dicomFolderWorkupPathLabels={dicomFolderWorkupPathLabels}
				dicomTextureStrategyLabels={dicomTextureStrategyLabels}
				dicomLabel={dicomLabel}
				isDicomFolderWorkupPlanning={isDicomFolderWorkupPlanning}
				isDicomWorkbenchBuilding={isDicomWorkbenchBuilding}
				isDicomFirstFramePreviewing={isDicomFirstFramePreviewing}
				rememberLocalImagingFolder={rememberLocalImagingFolder}
				setDicomFolderSeriesScan={setDicomFolderSeriesScan}
				setDicomFolderWorkupPlan={setDicomFolderWorkupPlan}
				setDicomFirstFramePreview={setDicomFirstFramePreview}
				setImagingFolderScan={setImagingFolderScan}
				setDicomLocalFolderDiscovery={setDicomLocalFolderDiscovery}
				prepareDicomWorkbenchFromFolder={prepareDicomWorkbenchFromFolder}
				previewDicomFirstFrame={previewDicomFirstFrame}
			/>

			<MigrationDicomViewerSection
				dicomFirstFramePreview={logic.typedDicomFirstFramePreview}
				typedDicomFirstFramePreview={logic.typedDicomFirstFramePreview}
				typedDicomFirstFrameViewerState={logic.typedDicomFirstFrameViewerState}
				typedDefaultDicomFirstFrameViewerState={logic.typedDefaultDicomFirstFrameViewerState}
				dicomFirstFrameStatusLabels={dicomFirstFrameStatusLabels}
				dicomFirstFrameSelectableCount={logic.dicomFirstFrameSelectableCount}
				dicomFirstFrameCurrentIndex={logic.dicomFirstFrameCurrentIndex ?? 0}
				dicomFirstFrameSliceMaxIndex={logic.dicomFirstFrameSliceMaxIndex}
				dicomFirstFrameLandmarkSlices={logic.dicomFirstFrameLandmarkSlices}
				dicomFirstFrameCanSelectPrevious={logic.dicomFirstFrameCanSelectPrevious}
				dicomFirstFrameCanSelectNext={logic.dicomFirstFrameCanSelectNext}
				isDicomFirstFramePreviewing={isDicomFirstFramePreviewing}
				dicomFirstFrameImageStyle={dicomFirstFrameImageStyle}
				imagingImportText={imagingImportText}
				imagingImportInputReady={logic.imagingImportInputReady}
				isDicomSeriesPreviewLoading={isDicomSeriesPreviewLoading}
				isImagingImportLoading={isImagingImportLoading}
				isImagingImportCommitting={isImagingImportCommitting}
				dicomSeriesPreview={dicomSeriesPreview}
				typedDicomSeriesPreviewSeries={logic.typedDicomSeriesPreviewSeries}
				imagingKindLabels={imagingKindLabels}
				dicomSeriesViewerLabels={dicomSeriesViewerLabels}
				mprLoadStrategyLabels={mprLoadStrategyLabels}
				mprResourceTierLabels={mprResourceTierLabels}
				typedImagingImportPreview={logic.typedImagingImportPreview}
				imagingImportCommit={imagingImportCommit}
				updateDicomFirstFrameViewerState={logic.updateDicomFirstFrameViewerState}
				updateDicomFirstFrameViewerNumber={logic.updateDicomFirstFrameViewerNumber}
				setDicomFirstFrameViewerState={setDicomFirstFrameViewerState}
				previewDicomFirstFrameSlice={previewDicomFirstFrameSlice}
				setImagingImportSourceKind={setImagingImportSourceKind}
				setImagingImportText={setImagingImportText}
				setImagingImportPreview={setImagingImportPreview}
				setImagingImportCommit={setImagingImportCommit}
				setDicomSeriesPreview={setDicomSeriesPreview}
				setDicomFolderSeriesScan={setDicomFolderSeriesScan}
				setDicomFolderWorkupPlan={setDicomFolderWorkupPlan}
				previewDicomSeries={previewDicomSeries}
				previewImagingImport={previewImagingImport}
				commitImagingImport={commitImagingImport}
			/>

			<MigrationPreviewSection
				settingsTab={settingsTab}
				typedImportSourceKinds={logic.typedImportSourceKinds}
				importSourceKind={importSourceKind}
				importSourceLabels={importSourceLabels}
				typedDocumentIngestionTargets={logic.typedDocumentIngestionTargets}
				documentIngestionTarget={documentIngestionTarget}
				ingestionTargetLabels={ingestionTargetLabels}
				isDocumentIngesting={isDocumentIngesting}
				typedDocumentIngestion={logic.typedDocumentIngestion}
				documentDetectedKindLabel={documentDetectedKindLabel}
				documentIngestionQualityLabels={documentIngestionQualityLabels}
				importText={importText}
				patientImportInputReady={logic.patientImportInputReady}
				isImportLoading={isImportLoading}
				isImportCommitting={isImportCommitting}
				typedImportIntake={logic.typedImportIntake}
				typedImportPreview={logic.typedImportPreview}
				importCommit={importCommit}
				setImportSourceKind={setImportSourceKind}
				setImportPreview={setImportPreview}
				setImportCommit={setImportCommit}
				setImportIntake={setImportIntake}
				setDocumentIngestionTarget={setDocumentIngestionTarget}
				ingestImportFile={ingestImportFile}
				setImportText={setImportText}
				previewImport={previewImport}
				commitImport={commitImport}
			/>
		</div>
	);
}
