/**
 * Header column aliases for Infodent, Infoclinica, and Denta Office CSV formats.
 */

export const PATIENT_HEADER_ALIASES = {
	externalId: [
		"nkart",
		"nomkart",
		"nomerkarty",
		"номеркарты",
		"номер_карты",
		"код",
		"kod",
		"id",
		"idpac",
		"npac",
		"код_пациента",
		"кодпациента",
		"kart",
		"karta",
	],
	fullName: [
		"fio",
		"фио",
		"fam_io",
		"pacient",
		"пациент",
		"клиент",
		"полноеимя",
		"полное_имя",
		"fullname",
		"name",
	],
	lastName: ["fam", "familia", "familiya", "фамилия", "surname", "lastname"],
	firstName: ["im", "imya", "имя", "firstname", "first_name"],
	middleName: [
		"ot",
		"otch",
		"otchestvo",
		"отчество",
		"middlename",
		"patronymic",
	],
	birthDate: [
		"drojd",
		"ddr",
		"datar",
		"datarojd",
		"datarojdeniya",
		"датарождения",
		"дата_рождения",
		"др",
		"д.р.",
		"birth",
		"birthday",
		"birthdate",
	],
	phone: [
		"tel",
		"telef",
		"telefon",
		"телефон",
		"моб",
		"мобильный",
		"мобтелефон",
		"сотовый",
		"phone",
		"mobile",
		"mobtel",
	],
	secondaryPhone: [
		"tel2",
		"teldom",
		"telrab",
		"доптелефон",
		"доп_телефон",
		"домашний",
		"рабочий",
		"второйтелефон",
	],
	email: ["email", "e-mail", "почта", "элпочта", "эл_почта", "epochta"],
	gender: ["pol", "пол", "sex", "gender"],
	address: [
		"adres",
		"adr",
		"адрес",
		"адреспроживания",
		"адрес_проживания",
		"address",
	],
	notes: [
		"prim",
		"primech",
		"primechanie",
		"примечание",
		"коммент",
		"комментарий",
		"notes",
		"zamet",
	],
	discountCard: [
		"skidka",
		"скидка",
		"картаскидки",
		"дисконт",
		"discount",
		"procent",
	],
	balance: ["balans", "баланс", "dolg", "долг", "balance"],
	passport: ["pasport", "паспорт", "passport", "doc"],
	snils: ["snils", "снилс"],
	inn: ["inn", "инн"],
};

// Алиасы колонок визитов Инфодент/Инфоклиника
export const VISIT_HEADER_ALIASES = {
	externalId: ["kod", "id", "idpriem", "номер", "номер_приема", "id_visit"],
	patientRef: [
		"nkart",
		"nomkart",
		"idpac",
		"kodpac",
		"pacient",
		"пациент",
		"номеркарты",
	],
	doctorRef: [
		"kodvracha",
		"idvrach",
		"vrach_id",
		"doctor_id",
		"код_врача",
		"табельный",
	],
	doctorName: ["vrach", "врач", "doctor", "специалист", "фио_врача"],
	date: ["data", "datapriem", "datapriema", "дата", "дата_приема", "date"],
	time: ["vremya", "время", "time", "nachalo", "начало"],
	duration: ["dlit", "длительность", "минут", "duration"],
	status: ["status", "статус", "sostoyanie", "состояние"],
	reason: ["povod", "повод", "prichina", "причина", "жалобы", "цель"],
	diagnosis: ["diagnoz", "диагноз", "mkb", "мкб", "diagnosis"],
	treatment: ["lechenie", "лечение", "usluga", "услуга", "treatment"],
	notes: ["prim", "primech", "примечание", "комментарий", "notes"],
};

// Алиасы колонок оплат/счетов Инфодент/Инфоклиника
export const PAYMENT_HEADER_ALIASES = {
	externalId: ["kod", "id", "nom", "номер", "id_check", "номер_счета"],
	patientRef: [
		"nkart",
		"nomkart",
		"idpac",
		"kodpac",
		"npac",
		"пациент",
		"номеркарты",
	],
	amount: [
		"summa",
		"сумма",
		"sum",
		"cena",
		"цена",
		"itogo",
		"итого",
		"koplate",
		"оплачено",
		"amount",
	],
	paidAt: [
		"data",
		"datopl",
		"dataopl",
		"dataoplaty",
		"дата",
		"дата_оплаты",
		"date",
	],
	method: [
		"vid",
		"vidopl",
		"sposob",
		"тип_оплаты",
		"способ_оплаты",
		"вид_оплаты",
		"kassa",
		"касса",
	],
	note: ["prim", "primech", "примечание", "назначение", "комментарий"],
	serviceName: ["usluga", "услуга", "naimenovanie", "наименование", "работа"],
};

// Алиасы колонок прайс-листа Инфодент/Инфоклиника
export const PRICELIST_HEADER_ALIASES = {
	code: ["artikul", "артикул", "kod", "код", "id", "code", "номер"],
	name: [
		"naimenovanie",
		"наименование",
		"usluga",
		"услуга",
		"nazvanie",
		"название",
		"name",
		"title",
	],
	price: [
		"cena",
		"цена",
		"stoimost",
		"стоимость",
		"price",
		"tarif",
		"тариф",
		"сумма",
	],
	category: [
		"kategoriya",
		"категория",
		"razdel",
		"раздел",
		"gruppa",
		"группа",
		"otdel",
		"отделение",
	],
	unit: ["ed", "ед", "edizm", "ед_изм", "unit", "штука"],
};

