/**
 * DENTE Dental CRM — Statutory Minzdrav Order № 804n Service Catalog & Nomenclature Presets
 *
 * Layer 1: Consultations, Pediatric Dentistry, Radiology, Anesthesia & Clinic Packages Presets
 */

import { STATUTORY_VAT_EXEMPTION_NOTE } from './constants';
import type { ServicePricelistItem } from './types';

/**
 * Section 1: КОНСУЛЬТАЦИИ И ОСМОТРЫ (B01.065)
 */
export const CONSULTATION_STATUTORY_PRESETS: readonly ServicePricelistItem[] = [
	// =========================================================================
	// 1. КОНСУЛЬТАЦИИ И ОСМОТРЫ (B01.065)
	// =========================================================================
	{
		id: 'srv-b01-065-001',
		code804n: 'B01.065.001',
		statutoryTitle804n: 'Прием (осмотр, консультация) врача-стоматолога-терапевта первичный',
		commercialTitle: 'Первичная консультация врача-стоматолога с осмотром и составлением плана лечения',
		category: 'consultation',
		specialty: 'therapist',
		basePriceRub: 1500,
		basePriceKopecks: 150000,
		materialCostRub: 250,
		labCostRub: 0,
		tierPrices: { vip: 2000, dms: 1200, promo: 0 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['Z01.2'],
		estimatedDurationMin: 30,
		isActive: true,
		isArchived: false,
		tags: ['консультация', 'осмотр', 'план лечения', 'первичный прием'],
	},
	{
		id: 'srv-b01-065-002',
		code804n: 'B01.065.002',
		statutoryTitle804n: 'Прием (осмотр, консультация) врача-стоматолога-терапевта повторный',
		commercialTitle: 'Повторный прием врача-стоматолога (контрольный осмотр / коррекция)',
		category: 'consultation',
		specialty: 'therapist',
		basePriceRub: 800,
		basePriceKopecks: 80000,
		materialCostRub: 150,
		labCostRub: 0,
		tierPrices: { vip: 1000, dms: 700, promo: 500 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['Z01.2'],
		estimatedDurationMin: 20,
		isActive: true,
		isArchived: false,
		tags: ['повторный прием', 'контроль', 'осмотр'],
	},
	{
		id: 'srv-b01-065-003',
		code804n: 'B01.065.003',
		statutoryTitle804n: 'Прием (осмотр, консультация) врача-стоматолога-хирурга первичный',
		commercialTitle: 'Консультация хирурга-имплантолога с анализом КЛКТ и 3D-планированием',
		category: 'consultation',
		specialty: 'surgeon',
		basePriceRub: 2000,
		basePriceKopecks: 200000,
		materialCostRub: 300,
		labCostRub: 0,
		tierPrices: { vip: 2800, dms: 1500, promo: 1000 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K08.1', 'Z01.2'],
		estimatedDurationMin: 40,
		isActive: true,
		isArchived: false,
		tags: ['хирург', 'имплантация', 'консультация', '3d-планирование'],
	},
	{
		id: 'srv-b01-065-007',
		code804n: 'B01.065.007',
		statutoryTitle804n: 'Прием (осмотр, консультация) врача-стоматолога-ортопеда первичный',
		commercialTitle: 'Консультация врача-стоматолога-ортопеда с фотопротоколом и диагностическими моделями',
		category: 'consultation',
		specialty: 'orthopedist',
		basePriceRub: 2200,
		basePriceKopecks: 220000,
		materialCostRub: 400,
		labCostRub: 0,
		tierPrices: { vip: 3000, dms: 1800, promo: 1500 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K08.1', 'K08.2'],
		estimatedDurationMin: 45,
		isActive: true,
		isArchived: false,
		tags: ['ортопед', 'протезирование', 'виниры', 'коронки'],
	},
	{
		id: 'srv-b01-065-009',
		code804n: 'B01.065.009',
		statutoryTitle804n: 'Прием (осмотр, консультация) врача-стоматолога-ортодонта первичный',
		commercialTitle: 'Консультация врача-ортодонта (диагностика прикуса, расчет ТРГ, подбор брекетов/элайнеров)',
		category: 'consultation',
		specialty: 'orthodontist',
		basePriceRub: 2500,
		basePriceKopecks: 250000,
		materialCostRub: 350,
		labCostRub: 0,
		tierPrices: { vip: 3500, dms: 2000, promo: 1500 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K07.2', 'K07.4'],
		estimatedDurationMin: 45,
		isActive: true,
		isArchived: false,
		tags: ['ортодонт', 'прикус', 'брекеты', 'элайнеры'],
	},

];

/**
 * Section 6: ДЕТСКАЯ СТОМАТОЛОГИЯ (A16.07 / B01.065)
 */
export const PEDIATRIC_STATUTORY_PRESETS: readonly ServicePricelistItem[] = [
	// =========================================================================
	// 6. ДЕТСКАЯ СТОМАТОЛОГИЯ (A16.07 / B01.065)
	// =========================================================================
	{
		id: 'srv-a16-07-002-010',
		code804n: 'A16.07.002.010',
		statutoryTitle804n: 'Восстановление зуба пломбой из стеклоиономерного цемента (молочный зуб)',
		commercialTitle: 'Лечение кариеса временного (молочного) зуба с пломбой Fuji IX / Twinky Star',
		category: 'pediatric',
		specialty: 'pediatric',
		basePriceRub: 3800,
		basePriceKopecks: 380000,
		materialCostRub: 650,
		labCostRub: 0,
		tierPrices: { vip: 4900, dms: 3100, promo: 3200 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K02.0', 'K02.1'],
		estimatedDurationMin: 30,
		isActive: true,
		isArchived: false,
		tags: ['дети', 'молочный зуб', 'кариес', 'fuji', 'сиц'],
	},
	{
		id: 'srv-a16-07-057',
		code804n: 'A16.07.057',
		statutoryTitle804n: 'Герметизация фиссур одного зуба',
		commercialTitle: 'Неинвазивная герметизация фиссур моляра материалом Clinpro / Fissurit',
		category: 'pediatric',
		specialty: 'pediatric',
		basePriceRub: 2200,
		basePriceKopecks: 220000,
		materialCostRub: 450,
		labCostRub: 0,
		tierPrices: { vip: 2800, dms: 1800, promo: 1800 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K02.0', 'Z29.8'],
		estimatedDurationMin: 20,
		isActive: true,
		isArchived: false,
		tags: ['герметизация', 'фиссуры', 'профилактика', 'дети'],
	},
	{
		id: 'srv-a16-07-001-010',
		code804n: 'A16.07.001.010',
		statutoryTitle804n: 'Удаление временного (молочного) зуба',
		commercialTitle: 'Бережное удаление временного зуба с аппликационной/инфильтрационной анестезией',
		category: 'pediatric',
		specialty: 'pediatric',
		basePriceRub: 2500,
		basePriceKopecks: 250000,
		materialCostRub: 350,
		labCostRub: 0,
		tierPrices: { vip: 3200, dms: 2000, promo: 2100 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K00.6', 'K04.7'],
		estimatedDurationMin: 20,
		isActive: true,
		isArchived: false,
		tags: ['удаление молочного', 'детская хирургия', 'смена прикуса'],
	},

];

/**
 * Section 7: ДИАГНОСТИКА И РЕНТГЕН (A06.07)
 */
export const RADIOLOGY_STATUTORY_PRESETS: readonly ServicePricelistItem[] = [
	// =========================================================================
	// 7. ДИАГНОСТИКА И РЕНТГЕН (A06.07)
	// =========================================================================
	{
		id: 'srv-a06-07-007',
		code804n: 'A06.07.007',
		statutoryTitle804n: 'Прицельная внутриротовая контактная рентгенография',
		commercialTitle: 'Цифровой прицельный снимок зуба на радиовизиографе (RVG)',
		category: 'radiology',
		specialty: 'radiologist',
		basePriceRub: 600,
		basePriceKopecks: 60000,
		materialCostRub: 80,
		labCostRub: 0,
		tierPrices: { vip: 800, dms: 500, promo: 450 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['Z01.2', 'K02', 'K04'],
		estimatedDurationMin: 10,
		isActive: true,
		isArchived: false,
		tags: ['снимок', 'rvg', 'визиограф', 'рентген'],
	},
	{
		id: 'srv-a06-07-013',
		code804n: 'A06.07.013',
		statutoryTitle804n: 'Ортопантомография (панорамный снимок)',
		commercialTitle: 'Панорамный снимок челюстей (ОПТГ) в высоком разрешении',
		category: 'radiology',
		specialty: 'radiologist',
		basePriceRub: 1600,
		basePriceKopecks: 160000,
		materialCostRub: 150,
		labCostRub: 0,
		tierPrices: { vip: 2000, dms: 1300, promo: 1200 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['Z01.2', 'K08'],
		estimatedDurationMin: 15,
		isActive: true,
		isArchived: false,
		tags: ['оптг', 'панорама', 'ортопантомограмма'],
	},
	{
		id: 'srv-a06-07-012',
		code804n: 'A06.07.012',
		statutoryTitle804n: 'Компьютерная томография челюстно-лицевой области (КЛКТ)',
		commercialTitle: '3D Компьютерная томография (КЛКТ) обеих челюстей (FOV 12x9 см / Vatech)',
		category: 'radiology',
		specialty: 'radiologist',
		basePriceRub: 3800,
		basePriceKopecks: 380000,
		materialCostRub: 300,
		labCostRub: 0,
		tierPrices: { vip: 4900, dms: 3000, promo: 2900 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['Z01.2', 'K08.1', 'K01.1'],
		estimatedDurationMin: 20,
		isActive: true,
		isArchived: false,
		tags: ['клкт', '3d снимок', 'томография', 'vatech', 'ct'],
	},

];

/**
 * Section 9: АНЕСТЕЗИОЛОГИЯ (A16.07.004)
 */
export const ANESTHESIA_STATUTORY_PRESETS: readonly ServicePricelistItem[] = [
	// =========================================================================
	// 9. АНЕСТЕЗИОЛОГИЯ (A16.07.004)
	// =========================================================================
	{
		id: 'srv-a16-07-004-001',
		code804n: 'A16.07.004.001',
		statutoryTitle804n: 'Анестезия местная инфильтрационная',
		commercialTitle: 'Местная инфильтрационная анестезия (Ультракаин Д-С форте 1:100 000)',
		category: 'anesthesia',
		specialty: 'therapist',
		basePriceRub: 950,
		basePriceKopecks: 95000,
		materialCostRub: 220,
		labCostRub: 0,
		tierPrices: { vip: 1300, dms: 750, promo: 750 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['Z01.2'],
		estimatedDurationMin: 10,
		isActive: true,
		isArchived: false,
		tags: ['анестезия', 'инфильтрация', 'ультракаин', 'обезболивание'],
	},
	{
		id: 'srv-a16-07-004-002',
		code804n: 'A16.07.004.002',
		statutoryTitle804n: 'Анестезия местная проводниковая',
		commercialTitle: 'Проводниковая (мандибулярная / торусальная) анестезия',
		category: 'anesthesia',
		specialty: 'surgeon',
		basePriceRub: 1200,
		basePriceKopecks: 120000,
		materialCostRub: 280,
		labCostRub: 0,
		tierPrices: { vip: 1600, dms: 950, promo: 950 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['Z01.2'],
		estimatedDurationMin: 15,
		isActive: true,
		isArchived: false,
		tags: ['проводниковая', 'мандибулярная', 'торусальная'],
	},
	{
		id: 'srv-a16-07-004-003',
		code804n: 'A16.07.004.003',
		statutoryTitle804n: 'Анестезия местная без адреналина (мепивакаин)',
		commercialTitle: 'Безадреналиновая анестезия Мепивакаин / Скандонест 3% (для пациентов группы риска)',
		category: 'anesthesia',
		specialty: 'therapist',
		basePriceRub: 1100,
		basePriceKopecks: 110000,
		materialCostRub: 260,
		labCostRub: 0,
		tierPrices: { vip: 1500, dms: 900, promo: 900 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['Z01.2'],
		estimatedDurationMin: 10,
		isActive: true,
		isArchived: false,
		tags: ['мепивакаин', 'без адреналина', 'сердечники', 'беременные'],
	},

];

/**
 * Section 10: ВНУТРИКЛИНИЧЕСКИЕ ПАКЕТЫ И УСЛУГИ (СВОБОДА КЛИНИКИ — MANDATE 8E)
 */
export const PACKAGE_STATUTORY_PRESETS: readonly ServicePricelistItem[] = [
	// =========================================================================
	// 10. ВНУТРИКЛИНИЧЕСКИЕ ПАКЕТЫ И УСЛУГИ (СВОБОДА КЛИНИКИ — MANDATE 8E)
	// =========================================================================
	{
		id: 'srv-clinic-gift-010',
		code804n: 'CLINIC.GIFT.010',
		statutoryTitle804n: 'Депозитный авансовый платеж / сертификат на медицинские услуги',
		commercialTitle: 'Подарочный сертификат клиники (депозит 10 000 ₽)',
		category: 'package',
		specialty: 'general',
		basePriceRub: 10000,
		basePriceKopecks: 1000000,
		materialCostRub: 200,
		labCostRub: 0,
		tierPrices: { vip: 10000, dms: 10000, promo: 9000 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['Z01.2'],
		estimatedDurationMin: 15,
		isClinicPackage: true,
		isActive: true,
		isArchived: false,
		tags: ['сертификат', 'подарочный сертификат', 'депозит', 'аванс', 'подарок', 'пакет'],
	},
	{
		id: 'srv-clinic-kapa-001',
		code804n: 'CLINIC.KAPA.001',
		statutoryTitle804n: 'Изготовление индивидуального защитного/окклюзионного разобщающего аппарата (капы)',
		commercialTitle: 'Индивидуальная капа (ночная при бруксизме / спортивная защитная)',
		category: 'package',
		specialty: 'orthopedist',
		basePriceRub: 9500,
		basePriceKopecks: 950000,
		materialCostRub: 1500,
		labCostRub: 3500,
		tierPrices: { vip: 12500, dms: 8000, promo: 8500 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['F45.8', 'K07.6'],
		estimatedDurationMin: 45,
		isClinicPackage: true,
		isActive: true,
		isArchived: false,
		tags: ['индивидуальная капа', 'капа', 'бруксизм', 'сплинт', 'каппа', 'защитная капа', 'спорт'],
	},
	{
		id: 'srv-clinic-sut-001',
		code804n: 'CLINIC.SUT.001',
		statutoryTitle804n: 'Снятие послеоперационных швов (лигатур) с антисептической обработкой раны',
		commercialTitle: 'Снятие швов сторонней клиники с антисептической обработкой',
		category: 'package',
		specialty: 'surgeon',
		basePriceRub: 1500,
		basePriceKopecks: 150000,
		materialCostRub: 250,
		labCostRub: 0,
		tierPrices: { vip: 2000, dms: 1200, promo: 1200 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['Z48.0'],
		estimatedDurationMin: 20,
		isClinicPackage: true,
		isActive: true,
		isArchived: false,
		tags: ['снятие швов', 'швы', 'сторонняя клиника', 'перевязка', 'лигатуры', 'антисептика'],
	},
	{
		id: 'srv-pkg-smile-001',
		code804n: 'PKG.SMILE.001',
		statutoryTitle804n: 'Комплексная диагностика и профилактика заболеваний полости рта',
		commercialTitle: 'Комплексный пакет «Здоровая улыбка» (Осмотр + КЛКТ + Профгигиена)',
		category: 'package',
		specialty: 'general',
		basePriceRub: 9900,
		basePriceKopecks: 990000,
		materialCostRub: 1600,
		labCostRub: 0,
		tierPrices: { vip: 13000, dms: 8500, promo: 8500 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['Z01.2', 'K03.6'],
		estimatedDurationMin: 75,
		isClinicPackage: true,
		isActive: true,
		isArchived: false,
		tags: ['пакет', 'комплекс', 'здоровая улыбка', 'чекап', 'акция', 'гигиена', 'чистка', 'снимок'],
	},
];

/**
 * Baseline 804n Services: Primary Consultation (srv-base-27)
 */
export const CONSULTATION_BASELINE_SERVICES: readonly ServicePricelistItem[] = [
	{
		id: 'srv-base-27',
		code804n: 'B01.065.001',
		statutoryTitle804n: 'Прием (осмотр, консультация) врача-стоматолога-терапевта первичный',
		commercialTitle: 'Первичный прием врача-стоматолога с осмотром и составлением плана лечения',
		category: 'consultation',
		specialty: 'therapist',
		basePriceRub: 1000,
		basePriceKopecks: 100000,
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['Z01.2'],
		estimatedDurationMin: 30,
		isActive: true,
		isArchived: false,
		tags: ['консультация', 'осмотр', 'первичный прием'],
	},
];

/**
 * Baseline 804n Services: Radiology - RVG & OPG (srv-base-28 to srv-base-29)
 */
export const RADIOLOGY_BASELINE_SERVICES: readonly ServicePricelistItem[] = [
	{
		id: 'srv-base-28',
		code804n: 'A06.07.003',
		statutoryTitle804n: 'Прицельная внутриротовая контактная радиовизиография',
		commercialTitle: 'Прицельная радиовизиография зуба (цифровой снимок)',
		category: 'radiology',
		specialty: 'radiologist',
		basePriceRub: 650,
		basePriceKopecks: 65000,
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['Z01.2'],
		estimatedDurationMin: 10,
		isActive: true,
		isArchived: false,
		tags: ['снимок', 'визиограф', 'рентген'],
	},
	{
		id: 'srv-base-29',
		code804n: 'A06.07.004',
		statutoryTitle804n: 'Ортопантомография челюстей (панорамный снимок ОПТГ)',
		commercialTitle: 'Панорамный снимок зубных рядов (ОПТГ)',
		category: 'radiology',
		specialty: 'radiologist',
		basePriceRub: 1400,
		basePriceKopecks: 140000,
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['Z01.2'],
		estimatedDurationMin: 15,
		isActive: true,
		isArchived: false,
		tags: ['оптг', 'панорама', 'рентген'],
	},
];
