/**
 * DENTE Dental CRM — Statutory Minzdrav Order № 804n Service Catalog & Nomenclature Presets
 *
 * Layer 1: Orthopedics, Prosthetics, Veneers, Crowns & Orthodontics Presets
 */

import { STATUTORY_VAT_EXEMPTION_NOTE } from './constants';
import type { ServicePricelistItem } from './types';

/**
 * Section 4: ОРТОПЕДИЯ И ПРОТЕЗИРОВАНИЕ (A16.07)
 */
export const ORTHOPEDIC_STATUTORY_PRESETS: readonly ServicePricelistItem[] = [
	// =========================================================================
	// 4. ОРТОПЕДИЯ И ПРОТЕЗИРОВАНИЕ (A16.07)
	// =========================================================================
	{
		id: 'srv-a16-07-006-001',
		code804n: 'A16.07.006.001',
		statutoryTitle804n: 'Протезирование зуба коронкой постоянной металлокерамической',
		commercialTitle: 'Металлокерамическая коронка на каркасе из CoCr сплава',
		category: 'orthopedics',
		specialty: 'orthopedist',
		basePriceRub: 14500,
		basePriceKopecks: 1450000,
		materialCostRub: 1200,
		labCostRub: 4500,
		tierPrices: { vip: 18500, dms: 11500, promo: 12000 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K08.1', 'K02.2'],
		estimatedDurationMin: 60,
		isActive: true,
		isArchived: false,
		tags: ['металлокерамика', 'коронка', 'протезирование'],
	},
	{
		id: 'srv-a16-07-006-002',
		code804n: 'A16.07.006.002',
		statutoryTitle804n: 'Протезирование зуба коронкой из диоксида циркония',
		commercialTitle: 'Коронка из диоксида циркония цельнофрезерованная MultiLayer (Katana/Prettau)',
		category: 'orthopedics',
		specialty: 'orthopedist',
		basePriceRub: 24000,
		basePriceKopecks: 2400000,
		materialCostRub: 1800,
		labCostRub: 7500,
		tierPrices: { vip: 31000, dms: 19500, promo: 21000 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K08.1', 'K02.2'],
		estimatedDurationMin: 60,
		isActive: true,
		isArchived: false,
		tags: ['цирконий', 'zirconia', 'коронка', 'katana', 'prettau'],
	},
	{
		id: 'srv-a16-07-006-003',
		code804n: 'A16.07.006.003',
		statutoryTitle804n: 'Протезирование цельнокерамической коронкой / виниром',
		commercialTitle: 'Керамический винир / коронка из прессованной керамики E.max (IPS e.max Press)',
		category: 'orthopedics',
		specialty: 'orthopedist',
		basePriceRub: 28000,
		basePriceKopecks: 2800000,
		materialCostRub: 2200,
		labCostRub: 9000,
		tierPrices: { vip: 36000, dms: 23000, promo: 24900 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K03.8', 'K08.1'],
		estimatedDurationMin: 75,
		isActive: true,
		isArchived: false,
		tags: ['винир', 'emax', 'керамика', 'эстетика', 'e.max'],
	},
	{
		id: 'srv-a16-07-006-005',
		code804n: 'A16.07.006.005',
		statutoryTitle804n: 'Протезирование коронкой на имплантате с винтовой фиксацией',
		commercialTitle: 'Коронка из диоксида циркония на имплантате с винтовой фиксацией на Ti-base',
		category: 'orthopedics',
		specialty: 'orthopedist',
		basePriceRub: 34000,
		basePriceKopecks: 3400000,
		materialCostRub: 3500,
		labCostRub: 11000,
		tierPrices: { vip: 44000, dms: 28000, promo: 29900 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K08.1'],
		estimatedDurationMin: 60,
		isActive: true,
		isArchived: false,
		tags: ['коронка на импланте', 'винтовая фиксация', 'титановое основание', 'tibase'],
	},
	{
		id: 'srv-a16-07-006-004-zirconia',
		code804n: 'A16.07.006.004',
		statutoryTitle804n: 'Восстановление зуба коронкой из диоксида циркония с винтовой фиксацией на имплантате',
		commercialTitle: 'Анатомическая коронка из диоксида циркония (Zirconia Prettau/Katana) на имплантате с винтовой фиксацией',
		category: 'orthopedics',
		specialty: 'orthopedist',
		basePriceRub: 26000,
		basePriceKopecks: 2600000,
		materialCostRub: 2800,
		labCostRub: 8500,
		tierPrices: { vip: 33000, dms: 22000, promo: 23500 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K08.1'],
		estimatedDurationMin: 60,
		isActive: true,
		isArchived: false,
		tags: ['коронка на импланте', 'винтовая фиксация', 'цирконий', 'zirconia', 'dentalia', 'prettau'],
	},
	{
		id: 'srv-a16-07-006-004',
		code804n: 'A16.07.006.004',
		statutoryTitle804n: 'Протезирование временной коронкой',
		commercialTitle: 'Временная коронка длительного ношения PMMA Cad/Cam',
		category: 'orthopedics',
		specialty: 'orthopedist',
		basePriceRub: 4500,
		basePriceKopecks: 450000,
		materialCostRub: 500,
		labCostRub: 1500,
		tierPrices: { vip: 5800, dms: 3600, promo: 3800 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K08.1'],
		estimatedDurationMin: 30,
		isActive: true,
		isArchived: false,
		tags: ['временная коронка', 'pmma', 'пластмасса'],
	},
	{
		id: 'srv-a16-07-003-001',
		code804n: 'A16.07.003.001',
		statutoryTitle804n: 'Восстановление зуба культевой штифтовой вкладкой',
		commercialTitle: 'Культевая штифтовая вкладка цельнолитая CoCr / диоксид циркония',
		category: 'orthopedics',
		specialty: 'orthopedist',
		basePriceRub: 7500,
		basePriceKopecks: 750000,
		materialCostRub: 800,
		labCostRub: 2500,
		tierPrices: { vip: 9800, dms: 6000, promo: 6500 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K02.2'],
		estimatedDurationMin: 45,
		isActive: true,
		isArchived: false,
		tags: ['культевая вкладка', 'вкладка', 'кшв', 'штифт'],
	},

];

/**
 * Section 5: ОРТОДОНТИЯ (A16.07)
 */
export const ORTHODONTIC_STATUTORY_PRESETS: readonly ServicePricelistItem[] = [
	// =========================================================================
	// 5. ОРТОДОНТИЯ (A16.07)
	// =========================================================================
	{
		id: 'srv-a16-07-047-001',
		code804n: 'A16.07.047.001',
		statutoryTitle804n: 'Ортодонтическая коррекция с применением брекет-системы (металлическая)',
		commercialTitle: 'Фиксация самолигирующей металлической брекет-системы Damon Q (1 челюсть)',
		category: 'orthodontics',
		specialty: 'orthodontist',
		basePriceRub: 45000,
		basePriceKopecks: 4500000,
		materialCostRub: 18000,
		labCostRub: 0,
		tierPrices: { vip: 58000, dms: 38000, promo: 39000 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K07.2', 'K07.4'],
		estimatedDurationMin: 90,
		isActive: true,
		isArchived: false,
		tags: ['брекеты', 'damon q', 'металл', 'ортодонтия'],
	},
	{
		id: 'srv-a16-07-047-002',
		code804n: 'A16.07.047.002',
		statutoryTitle804n: 'Ортодонтическая коррекция с применением брекет-системы (керамическая)',
		commercialTitle: 'Фиксация эстетической керамической брекет-системы Damon Clear (1 челюсть)',
		category: 'orthodontics',
		specialty: 'orthodontist',
		basePriceRub: 65000,
		basePriceKopecks: 6500000,
		materialCostRub: 28000,
		labCostRub: 0,
		tierPrices: { vip: 85000, dms: 55000, promo: 58000 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K07.2', 'K07.4'],
		estimatedDurationMin: 90,
		isActive: true,
		isArchived: false,
		tags: ['керамика', 'damon clear', 'эстетика', 'сапфир'],
	},
	{
		id: 'srv-a16-07-047-003',
		code804n: 'A16.07.047.003',
		statutoryTitle804n: 'Активация ортодонтического аппарата / брекет-системы',
		commercialTitle: 'Плановый прием с заменой ортодонтической дуги и активацией брекетов (1 челюсть)',
		category: 'orthodontics',
		specialty: 'orthodontist',
		basePriceRub: 4500,
		basePriceKopecks: 450000,
		materialCostRub: 1100,
		labCostRub: 0,
		tierPrices: { vip: 5800, dms: 3800, promo: 3900 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K07.2'],
		estimatedDurationMin: 30,
		isActive: true,
		isArchived: false,
		tags: ['активация', 'дуга', 'прием ортодонта'],
	},
	{
		id: 'srv-a16-07-047-004',
		code804n: 'A16.07.047.004',
		statutoryTitle804n: 'Ортодонтическое лечение с применением элайнеров (прозрачных капп)',
		commercialTitle: 'Комплексный курс лечения на элайнерах Star Smile / FlexiLigner (полный кейс)',
		category: 'orthodontics',
		specialty: 'orthodontist',
		basePriceRub: 240000,
		basePriceKopecks: 24000000,
		materialCostRub: 90000,
		labCostRub: 0,
		tierPrices: { vip: 300000, dms: 210000, promo: 219000 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K07.2', 'K07.4'],
		estimatedDurationMin: 60,
		isActive: true,
		isArchived: false,
		tags: ['элайнеры', 'каппы', 'star smile', 'flexiligner', 'invisalign'],
	},

];

/**
 * Baseline 804n Services: Orthopedics Part 1 - Crowns, Inlays, Impressions (srv-base-12 to srv-base-16)
 */
export const ORTHOPEDIC_BASELINE_SERVICES_PART1: readonly ServicePricelistItem[] = [
	{
		id: 'srv-base-12',
		code804n: 'A16.07.006.004',
		statutoryTitle804n: 'Восстановление зуба коронкой из диоксида циркония',
		commercialTitle: 'Коронка из цельного диоксида циркония (Prettau / Katana)',
		category: 'orthopedics',
		specialty: 'orthopedist',
		basePriceRub: 25000,
		basePriceKopecks: 2500000,
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K08.1', 'K08.2'],
		estimatedDurationMin: 60,
		isActive: true,
		isArchived: false,
		tags: ['коронка', 'цирконий', 'диоксид циркония'],
	},
	{
		id: 'srv-base-13',
		code804n: 'A16.07.006.002',
		statutoryTitle804n: 'Восстановление зуба коронкой металлокерамической',
		commercialTitle: 'Коронка металлокерамическая (Duceram / Vita)',
		category: 'orthopedics',
		specialty: 'orthopedist',
		basePriceRub: 14500,
		basePriceKopecks: 1450000,
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K08.1'],
		estimatedDurationMin: 60,
		isActive: true,
		isArchived: false,
		tags: ['коронка', 'металлокерамика'],
	},
	{
		id: 'srv-base-14',
		code804n: 'A16.07.003.001',
		statutoryTitle804n: 'Восстановление зуба керамической вкладкой / виниром (E.max)',
		commercialTitle: 'Керамическая вкладка / винир E.max Press',
		category: 'orthopedics',
		specialty: 'orthopedist',
		basePriceRub: 24000,
		basePriceKopecks: 2400000,
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K02.1', 'K03.0'],
		estimatedDurationMin: 60,
		isActive: true,
		isArchived: false,
		tags: ['винир', 'керамика', 'e.max', 'вкладка'],
	},
	{
		id: 'srv-base-15',
		code804n: 'A02.07.010.001',
		statutoryTitle804n: 'Снятие оттиска с одной челюсти эластомерным материалом (А-силикон)',
		commercialTitle: 'Снятие двухслойного прецизионного слепка А-силиконом (Elite HD+ / Honigum)',
		category: 'orthopedics',
		specialty: 'orthopedist',
		basePriceRub: 2500,
		basePriceKopecks: 250000,
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['Z01.2'],
		estimatedDurationMin: 20,
		isActive: true,
		isArchived: false,
		tags: ['слепок', 'оттиск', 'а-силикон'],
	},
	{
		id: 'srv-base-16',
		code804n: 'A16.07.053',
		statutoryTitle804n: 'Фиксация на постоянный цемент несъемных ортопедических конструкций (1 единица)',
		commercialTitle: 'Постоянная фиксация коронки на цемент двойного отверждения (Fuji Plus / RelyX)',
		category: 'orthopedics',
		specialty: 'orthopedist',
		basePriceRub: 1500,
		basePriceKopecks: 150000,
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['Z01.2'],
		estimatedDurationMin: 20,
		isActive: true,
		isArchived: false,
		tags: ['фиксация', 'цемент', 'коронка'],
	},
];

/**
 * Baseline 804n Services: Orthopedics Part 2 - Custom Zirconia Abutment (srv-base-26)
 */
export const ORTHOPEDIC_BASELINE_SERVICES_PART2: readonly ServicePricelistItem[] = [
	{
		id: 'srv-base-26',
		code804n: 'A16.07.006.007',
		statutoryTitle804n: 'Протезирование с использованием индивидуального циркониевого абатмента',
		commercialTitle: 'Индивидуальный абатмент из диоксида циркония на титановом основании',
		category: 'orthopedics',
		specialty: 'orthopedist',
		basePriceRub: 12000,
		basePriceKopecks: 1200000,
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K08.1'],
		estimatedDurationMin: 45,
		isActive: true,
		isArchived: false,
		tags: ['абатмент', 'цирконий', 'титан', 'протезирование'],
	},
];

/**
 * All Baseline 804n Orthopedic Services
 */
export const ORTHOPEDIC_BASELINE_SERVICES: readonly ServicePricelistItem[] = [
	...ORTHOPEDIC_BASELINE_SERVICES_PART1,
	...ORTHOPEDIC_BASELINE_SERVICES_PART2,
];
