/**
 * DENTE Dental CRM — Statutory Minzdrav Order № 804n Service Catalog & Nomenclature Presets
 *
 * Layer 1: Surgery, Extraction, Bone Grafting & Dental Implantology Presets
 */

import { STATUTORY_VAT_EXEMPTION_NOTE } from './constants';
import type { ServicePricelistItem } from './types';

/**
 * Section 3: ХИРУРГИЯ И ИМПЛАНТАЦИЯ (A16.07)
 */
export const SURGERY_STATUTORY_PRESETS: readonly ServicePricelistItem[] = [
	// =========================================================================
	// 3. ХИРУРГИЯ И ИМПЛАНТАЦИЯ (A16.07)
	// =========================================================================
	{
		id: 'srv-a16-07-001-001',
		code804n: 'A16.07.001.001',
		statutoryTitle804n: 'Удаление постоянного зуба простое',
		commercialTitle: 'Простое атравматичное удаление зуба щипцами/элеватором',
		category: 'surgery',
		specialty: 'surgeon',
		basePriceRub: 3500,
		basePriceKopecks: 350000,
		materialCostRub: 500,
		labCostRub: 0,
		tierPrices: { vip: 4500, dms: 2800, promo: 2900 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K08.3', 'K04.7'],
		estimatedDurationMin: 30,
		isActive: true,
		isArchived: false,
		tags: ['удаление', 'простое удаление', 'экстракция'],
	},
	{
		id: 'srv-a16-07-001-002',
		code804n: 'A16.07.001.002',
		statutoryTitle804n: 'Удаление постоянного зуба сложное с разъединением корней',
		commercialTitle: 'Сложное удаление зуба с сепарацией корней, остеотомией и наложением швов',
		category: 'surgery',
		specialty: 'surgeon',
		basePriceRub: 6500,
		basePriceKopecks: 650000,
		materialCostRub: 900,
		labCostRub: 0,
		tierPrices: { vip: 8500, dms: 5000, promo: 5200 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K08.3', 'K04.8'],
		estimatedDurationMin: 60,
		isActive: true,
		isArchived: false,
		tags: ['сложное удаление', 'сепарация', 'швы'],
	},
	{
		id: 'srv-a16-07-024',
		code804n: 'A16.07.024',
		statutoryTitle804n: 'Операция удаления ретинированного, дистопированного или сверхкомплектного зуба',
		commercialTitle: 'Удаление ретинированного/дистопированного зуба мудрости (8-ки) с пьезохирургией',
		category: 'surgery',
		specialty: 'surgeon',
		basePriceRub: 9500,
		basePriceKopecks: 950000,
		materialCostRub: 1400,
		labCostRub: 0,
		tierPrices: { vip: 12500, dms: 7500, promo: 7900 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K01.0', 'K01.1'],
		estimatedDurationMin: 60,
		isActive: true,
		isArchived: false,
		tags: ['зуб мудрости', 'ретинированный', 'восьмерка', 'дистопия'],
	},
	{
		id: 'srv-a16-07-054-001',
		code804n: 'A16.07.054.001',
		statutoryTitle804n: 'Внутрикостная дентальная имплантация (установка имплантата)',
		commercialTitle: 'Установка дентального имплантата системы Osstem TS III (Южная Корея)',
		category: 'surgery',
		specialty: 'surgeon',
		basePriceRub: 35000,
		basePriceKopecks: 3500000,
		materialCostRub: 11500,
		labCostRub: 0,
		tierPrices: { vip: 45000, dms: 30000, promo: 28900 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K08.1'],
		estimatedDurationMin: 60,
		isActive: true,
		isArchived: false,
		tags: ['имплантация', 'osstem', 'титан', 'имплант'],
	},
	{
		id: 'srv-a16-07-054-002',
		code804n: 'A16.07.054.002',
		statutoryTitle804n: 'Внутрикостная дентальная имплантация премиум-системы',
		commercialTitle: 'Установка дентального имплантата Straumann Roxolid SLActive (Швейцария)',
		category: 'surgery',
		specialty: 'surgeon',
		basePriceRub: 65000,
		basePriceKopecks: 6500000,
		materialCostRub: 24000,
		labCostRub: 0,
		tierPrices: { vip: 85000, dms: 55000, promo: 59000 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K08.1'],
		estimatedDurationMin: 60,
		isActive: true,
		isArchived: false,
		tags: ['straumann', 'швейцария', 'премиум', 'имплант'],
	},
	{
		id: 'srv-a16-07-007',
		code804n: 'A16.07.007',
		statutoryTitle804n: 'Установка формирователя десны на имплантат',
		commercialTitle: 'Установка формирователя десны (раскрытие имплантата, 2-й хирургический этап)',
		category: 'surgery',
		specialty: 'surgeon',
		basePriceRub: 4500,
		basePriceKopecks: 450000,
		materialCostRub: 1200,
		labCostRub: 0,
		tierPrices: { vip: 6000, dms: 3600, promo: 3800 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K08.1'],
		estimatedDurationMin: 30,
		isActive: true,
		isArchived: false,
		tags: ['формирователь', 'фдм', 'десна', 'имплант'],
	},
	{
		id: 'srv-a16-07-041',
		code804n: 'A16.07.041',
		statutoryTitle804n: 'Костная пластика челюстно-лицевой области (синус-лифтинг)',
		commercialTitle: 'Закрытый синус-лифтинг с остеопластическим материалом (Bio-Oss)',
		category: 'surgery',
		specialty: 'surgeon',
		basePriceRub: 25000,
		basePriceKopecks: 2500000,
		materialCostRub: 9000,
		labCostRub: 0,
		tierPrices: { vip: 32000, dms: 21000, promo: 22000 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K08.2'],
		estimatedDurationMin: 45,
		isActive: true,
		isArchived: false,
		tags: ['синус-лифтинг', 'кость', 'bio-oss', 'аугментация'],
	},
	{
		id: 'srv-a16-07-055',
		code804n: 'A16.07.055',
		statutoryTitle804n: 'Синус-лифтинг открытый (латеральный доступ)',
		commercialTitle: 'Открытый синус-лифтинг с латеральным окном и коллагеновой мембраной (Bio-Gide)',
		category: 'surgery',
		specialty: 'surgeon',
		basePriceRub: 45000,
		basePriceKopecks: 4500000,
		materialCostRub: 16000,
		labCostRub: 0,
		tierPrices: { vip: 58000, dms: 38000, promo: 39900 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K08.2'],
		estimatedDurationMin: 90,
		isActive: true,
		isArchived: false,
		tags: ['открытый синус', 'латеральный', 'мембрана', 'bio-gide'],
	},

];

/**
 * Baseline 804n Services: Surgery Part 1 - Extractions & Sutures (srv-base-17 to srv-base-20)
 */
export const SURGERY_BASELINE_SERVICES_PART1: readonly ServicePricelistItem[] = [
	{
		id: 'srv-base-17',
		code804n: 'A16.07.001.001',
		statutoryTitle804n: 'Удаление постоянного зуба простое',
		commercialTitle: 'Простое удаление однокорневого зуба с гемостазом',
		category: 'surgery',
		specialty: 'surgeon',
		basePriceRub: 3200,
		basePriceKopecks: 320000,
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K04.7', 'K08.1'],
		estimatedDurationMin: 30,
		isActive: true,
		isArchived: false,
		tags: ['удаление', 'хирургия', 'зуб'],
	},
	{
		id: 'srv-base-18',
		code804n: 'A16.07.001.002',
		statutoryTitle804n: 'Удаление зуба сложное с разъединением корней',
		commercialTitle: 'Сложное атравматичное удаление многокорневого зуба с фрагментацией корней',
		category: 'surgery',
		specialty: 'surgeon',
		basePriceRub: 5500,
		basePriceKopecks: 550000,
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K04.7', 'K08.1'],
		estimatedDurationMin: 45,
		isActive: true,
		isArchived: false,
		tags: ['удаление сложное', 'фрагментация', 'хирургия'],
	},
	{
		id: 'srv-base-19',
		code804n: 'A16.07.001.003',
		statutoryTitle804n: 'Операция удаления ретинированного, дистопированного зуба (8-й зуб)',
		commercialTitle: 'Атипичное удаление ретинированного / дистопированного зуба мудрости',
		category: 'surgery',
		specialty: 'surgeon',
		basePriceRub: 8500,
		basePriceKopecks: 850000,
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K01.1'],
		estimatedDurationMin: 60,
		isActive: true,
		isArchived: false,
		tags: ['зуб мудрости', 'ретинированный', 'восьмерка', 'хирургия'],
	},
	{
		id: 'srv-base-20',
		code804n: 'A16.07.097',
		statutoryTitle804n: 'Наложение шва на слизистую оболочку рта при хирургических операциях',
		commercialTitle: 'Наложение хирургического шва (Викрил / Монофиламент)',
		category: 'surgery',
		specialty: 'surgeon',
		basePriceRub: 900,
		basePriceKopecks: 90000,
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K08.1'],
		estimatedDurationMin: 15,
		isActive: true,
		isArchived: false,
		tags: ['шов', 'ушивание', 'слизистая'],
	},
];

/**
 * Baseline 804n Services: Surgery Part 2 - Implants & Healing Abutments (srv-base-24 to srv-base-25)
 */
export const SURGERY_BASELINE_SERVICES_PART2: readonly ServicePricelistItem[] = [
	{
		id: 'srv-base-24',
		code804n: 'A16.07.054',
		statutoryTitle804n: 'Внутрикостная дентальная имплантация (установка дентального имплантата)',
		commercialTitle: 'Установка дентального имплантата премиум-класса',
		category: 'surgery',
		specialty: 'surgeon',
		basePriceRub: 35000,
		basePriceKopecks: 3500000,
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K08.1'],
		estimatedDurationMin: 60,
		isActive: true,
		isArchived: false,
		tags: ['имплантация', 'имплант', 'хирургия'],
	},
	{
		id: 'srv-base-25',
		code804n: 'A16.07.055',
		statutoryTitle804n: 'Установка формирователя десны на дентальный имплантат',
		commercialTitle: 'Установка формирователя десны (гингивопластика в области имплантата)',
		category: 'surgery',
		specialty: 'surgeon',
		basePriceRub: 4500,
		basePriceKopecks: 450000,
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K08.1'],
		estimatedDurationMin: 30,
		isActive: true,
		isArchived: false,
		tags: ['формирователь', 'десна', 'имплант'],
	},
];

/**
 * Baseline 804n Services: Surgery Part 3 - Suture Removal (srv-base-30)
 */
export const SURGERY_BASELINE_SERVICES_PART3: readonly ServicePricelistItem[] = [
	{
		id: 'srv-base-30',
		code804n: 'A16.01.008',
		statutoryTitle804n: 'Снятие послеоперационных швов (лигатур)',
		commercialTitle: 'Снятие послеоперационных швов с антисептической обработкой',
		category: 'surgery',
		specialty: 'surgeon',
		basePriceRub: 500,
		basePriceKopecks: 50000,
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['Z01.2'],
		estimatedDurationMin: 15,
		isActive: true,
		isArchived: false,
		tags: ['снятие швов', 'швы', 'лигатуры'],
	},
];

/**
 * All Baseline 804n Surgery Services
 */
export const SURGERY_BASELINE_SERVICES: readonly ServicePricelistItem[] = [
	...SURGERY_BASELINE_SERVICES_PART1,
	...SURGERY_BASELINE_SERVICES_PART2,
	...SURGERY_BASELINE_SERVICES_PART3,
];
