/**
 * DENTE Dental CRM — Statutory Minzdrav Order № 804n Service Catalog & Nomenclature Presets
 *
 * Layer 1: Therapy, Endodontics, Hygiene & Preventive Dentistry Presets
 */

import { STATUTORY_VAT_EXEMPTION_NOTE } from './constants';
import type { ServicePricelistItem } from './types';

/**
 * Section 2: ТЕРАПИЯ И ЭНДОДОНТИЯ (A16.07)
 */
export const THERAPY_STATUTORY_PRESETS: readonly ServicePricelistItem[] = [
	// =========================================================================
	// 2. ТЕРАПИЯ И ЭНДОДОНТИЯ (A16.07)
	// =========================================================================
	{
		id: 'srv-a16-07-002-001',
		code804n: 'A16.07.002.001',
		statutoryTitle804n: 'Восстановление зуба пломбой I, V, VI класс по Блэку с использованием материалов из фотополимеров',
		commercialTitle: 'Лечение поверхностного/среднего кариеса с фотополимерной пломбой (Estelite/Filtek)',
		category: 'therapy',
		specialty: 'therapist',
		basePriceRub: 5500,
		basePriceKopecks: 550000,
		materialCostRub: 950,
		labCostRub: 0,
		tierPrices: { vip: 7200, dms: 4500, promo: 4500 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K02.0', 'K02.1'],
		estimatedDurationMin: 45,
		isActive: true,
		isArchived: false,
		tags: ['кариес', 'пломба', 'композит', 'estelite', 'filtek'],
	},
	{
		id: 'srv-a16-07-002-002',
		code804n: 'A16.07.002.002',
		statutoryTitle804n: 'Восстановление зуба пломбой II, III класс по Блэку с использованием материалов из фотополимеров',
		commercialTitle: 'Лечение глубокого кариеса с лечебной прокладкой и контактным пунктом',
		category: 'therapy',
		specialty: 'therapist',
		basePriceRub: 6800,
		basePriceKopecks: 680000,
		materialCostRub: 1300,
		labCostRub: 0,
		tierPrices: { vip: 8800, dms: 5500, promo: 5800 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K02.1', 'K02.2'],
		estimatedDurationMin: 60,
		isActive: true,
		isArchived: false,
		tags: ['глубокий кариес', 'пломба', 'контактный пункт', 'прокладка'],
	},
	{
		id: 'srv-a16-07-002-003',
		code804n: 'A16.07.002.003',
		statutoryTitle804n: 'Восстановление зуба пломбой IV класс по Блэку с использованием материалов из фотополимеров',
		commercialTitle: 'Художественная эстетическая реставрация фронтального зуба (прямой композитный винир)',
		category: 'therapy',
		specialty: 'therapist',
		basePriceRub: 9500,
		basePriceKopecks: 950000,
		materialCostRub: 1800,
		labCostRub: 0,
		tierPrices: { vip: 12500, dms: 7800, promo: 8000 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K03.8', 'K02.1'],
		estimatedDurationMin: 90,
		isActive: true,
		isArchived: false,
		tags: ['реставрация', 'прямой винир', 'эстетика', 'фронт'],
	},
	{
		id: 'srv-a16-07-003',
		code804n: 'A16.07.003',
		statutoryTitle804n: 'Восстановление зуба пломбировочными материалами с использованием штифта',
		commercialTitle: 'Восстановление культи зуба с фиксацией стекловолоконного штифта (Build-Up)',
		category: 'therapy',
		specialty: 'therapist',
		basePriceRub: 4500,
		basePriceKopecks: 450000,
		materialCostRub: 1100,
		labCostRub: 0,
		tierPrices: { vip: 5800, dms: 3800, promo: 3900 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K02.2', 'K04.0'],
		estimatedDurationMin: 45,
		isActive: true,
		isArchived: false,
		tags: ['штифт', 'билдап', 'стекловолокно', 'культя'],
	},
	{
		id: 'srv-a16-07-030-001',
		code804n: 'A16.07.030.001',
		statutoryTitle804n: 'Инструментальная и медикаментозная обработка корневого канала (1-канальный зуб)',
		commercialTitle: 'Механическая и медикаментозная обработка корневого канала машинным NiTi-инструментом (1 канал)',
		category: 'therapy',
		specialty: 'therapist',
		basePriceRub: 3500,
		basePriceKopecks: 350000,
		materialCostRub: 800,
		labCostRub: 0,
		tierPrices: { vip: 4500, dms: 2900, promo: 3000 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K04.0', 'K04.1'],
		estimatedDurationMin: 40,
		isAnatomicalCanalScalable: true,
		isActive: true,
		isArchived: false,
		tags: ['эндодонтия', 'обработка канала', 'пульпит', 'периодонтит', 'нерв', 'удаление нерва', 'депульпирование'],
	},
	{
		id: 'srv-a16-07-008-001',
		code804n: 'A16.07.008.001',
		statutoryTitle804n: 'Пломбирование корневого канала зуба пастой/гуттаперчей (1 канал)',
		commercialTitle: 'Обтурация корневого канала горячей гуттаперчей / биокерамическим силером (1 канал)',
		category: 'therapy',
		specialty: 'therapist',
		basePriceRub: 4000,
		basePriceKopecks: 400000,
		materialCostRub: 900,
		labCostRub: 0,
		tierPrices: { vip: 5200, dms: 3300, promo: 3500 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K04.0', 'K04.1'],
		estimatedDurationMin: 35,
		isAnatomicalCanalScalable: true,
		isActive: true,
		isArchived: false,
		tags: ['обтурация', 'гуттаперча', 'силер', 'пломбирование канала', 'лечение нерва', 'нерв'],
	},
	{
		id: 'srv-a16-07-082',
		code804n: 'A16.07.082',
		statutoryTitle804n: 'Распломбирование корневого канала ранее леченного пастой/гуттаперчей',
		commercialTitle: 'Ревизия и распломбирование корневого канала (перелечивание зуба)',
		category: 'therapy',
		specialty: 'therapist',
		basePriceRub: 2800,
		basePriceKopecks: 280000,
		materialCostRub: 600,
		labCostRub: 0,
		tierPrices: { vip: 3600, dms: 2200, promo: 2300 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K04.5', 'K04.4'],
		estimatedDurationMin: 45,
		isActive: true,
		isArchived: false,
		tags: ['перелечивание', 'распломбирование', 'ревизия', 'лечение нерва', 'нерв'],
	},
	{
		id: 'srv-a16-07-091',
		code804n: 'A16.07.091',
		statutoryTitle804n: 'Временное пломбирование лекарственным препаратом корневого канала',
		commercialTitle: 'Временное пломбирование корневого канала гидроксидом кальция Ca(OH)2 при периодонтите',
		category: 'therapy',
		specialty: 'therapist',
		basePriceRub: 2000,
		basePriceKopecks: 200000,
		materialCostRub: 450,
		labCostRub: 0,
		tierPrices: { vip: 2600, dms: 1600, promo: 1700 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K04.4', 'K04.5'],
		estimatedDurationMin: 30,
		isActive: true,
		isArchived: false,
		tags: ['кальций', 'caoh2', 'периодонтит', 'лекарство', 'лечение нерва', 'нерв'],
	},
	{
		id: 'srv-a16-07-002-005',
		code804n: 'A16.07.002.005',
		statutoryTitle804n: 'Наложение коффердама (раббердама)',
		commercialTitle: 'Изоляция операционного поля системой Коффердам / ОптраГейт',
		category: 'therapy',
		specialty: 'therapist',
		basePriceRub: 900,
		basePriceKopecks: 90000,
		materialCostRub: 250,
		labCostRub: 0,
		tierPrices: { vip: 1200, dms: 700, promo: 700 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K02.0', 'K04.0'],
		estimatedDurationMin: 10,
		isActive: true,
		isArchived: false,
		tags: ['коффердам', 'раббердам', 'изоляция', 'оптрагейт'],
	},
	{
		id: 'srv-a16-07-002-005-erosion',
		code804n: 'A16.07.002.005',
		statutoryTitle804n: 'Наложение пломбы при клиновидных дефектах и эрозии эмали',
		commercialTitle: 'Пломбирование пришеечного клиновидного дефекта / эрозии эмали (V класс по Блэку)',
		category: 'therapy',
		specialty: 'therapist',
		basePriceRub: 4200,
		basePriceKopecks: 420000,
		materialCostRub: 800,
		labCostRub: 0,
		tierPrices: { vip: 5500, dms: 3500, promo: 3600 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K03.1', 'K03.2', 'K02.1'],
		estimatedDurationMin: 40,
		isActive: true,
		isArchived: false,
		tags: ['клиновидный дефект', 'эрозия', 'пришеечный кариес', 'v класс', 'пломба'],
	},

];

/**
 * Section 8: ГИГИЕНА И ПРОФИЛАКТИКА (A16.07 / A11.07)
 */
export const HYGIENE_STATUTORY_PRESETS: readonly ServicePricelistItem[] = [
	// =========================================================================
	// 8. ГИГИЕНА И ПРОФИЛАКТИКА (A16.07 / A11.07)
	// =========================================================================
	{
		id: 'srv-a16-07-051-001',
		code804n: 'A16.07.051.001',
		statutoryTitle804n: 'Профессиональная гигиена полости рта и зубов (комплекс)',
		commercialTitle: 'Комплексная гигиена полости рта (УЗ-скейлинг + Air-Flow + полировка + фторирование)',
		category: 'hygiene',
		specialty: 'hygienist',
		basePriceRub: 6500,
		basePriceKopecks: 650000,
		materialCostRub: 1200,
		labCostRub: 0,
		tierPrices: { vip: 8500, dms: 5000, promo: 4900 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K03.6', 'K05.0'],
		estimatedDurationMin: 60,
		isActive: true,
		isArchived: false,
		tags: ['гигиена', 'чистка', 'air flow', 'ультразвук', 'фторирование'],
	},
	{
		id: 'srv-a16-07-051-002',
		code804n: 'A16.07.051.001',
		statutoryTitle804n: 'Ультразвуковое удаление наддесневых и поддесневых зубных отложений',
		commercialTitle: 'Ультразвуковой скейлинг зубных отложений (снятие зубного камня в области челюстей)',
		category: 'hygiene',
		specialty: 'hygienist',
		basePriceRub: 3800,
		basePriceKopecks: 380000,
		materialCostRub: 500,
		labCostRub: 0,
		tierPrices: { vip: 4900, dms: 3100, promo: 3200 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K03.6', 'K05.0'],
		estimatedDurationMin: 40,
		isActive: true,
		isArchived: false,
		tags: ['ультразвук', 'скейлинг', 'зубной камень', 'чистка'],
	},
	{
		id: 'srv-a16-07-050',
		code804n: 'A16.07.050',
		statutoryTitle804n: 'Профессиональное отбеливание зубов в условиях стоматологического кабинета',
		commercialTitle: 'Клиническое отбеливание зубов холодным светом (Philips ZOOM 4 / Beyond Polus)',
		category: 'hygiene',
		specialty: 'hygienist',
		basePriceRub: 29000,
		basePriceKopecks: 2900000,
		materialCostRub: 9500,
		labCostRub: 0,
		tierPrices: { vip: 37000, dms: 25000, promo: 24900 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K03.7', 'K03.8'],
		estimatedDurationMin: 90,
		isActive: true,
		isArchived: false,
		tags: ['отбеливание', 'zoom 4', 'beyond', 'белоснежная улыбка'],
	},

];

/**
 * Baseline 804n Services: Therapy & Endodontics (srv-base-01 to srv-base-11)
 */
export const THERAPY_BASELINE_SERVICES: readonly ServicePricelistItem[] = [
	{
		id: 'srv-base-01',
		code804n: 'A11.07.012',
		statutoryTitle804n: 'Инъекционное введение лекарственных препаратов в челюстно-лицевую область (инфильтрационная анестезия)',
		commercialTitle: 'Инфильтрационная анестезия (Артикаин/Ультракаин)',
		category: 'therapy',
		specialty: 'therapist',
		basePriceRub: 950,
		basePriceKopecks: 95000,
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K02.1', 'K04.0'],
		estimatedDurationMin: 15,
		isActive: true,
		isArchived: false,
		tags: ['анестезия', 'инфильтрационная', 'укол', 'обезболивание'],
	},
	{
		id: 'srv-base-02',
		code804n: 'A11.07.010',
		statutoryTitle804n: 'Введение лекарственных препаратов в область периферического нерва (проводниковая анестезия)',
		commercialTitle: 'Проводниковая анестезия (Торусальная / Мандибулярная)',
		category: 'therapy',
		specialty: 'therapist',
		basePriceRub: 1100,
		basePriceKopecks: 110000,
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K02.1', 'K04.0'],
		estimatedDurationMin: 15,
		isActive: true,
		isArchived: false,
		tags: ['анестезия', 'проводниковая', 'мандибулярная'],
	},
	{
		id: 'srv-base-03',
		code804n: 'A16.07.002.009',
		statutoryTitle804n: 'Изоляция операционного поля (наложение коффердама / раббердама)',
		commercialTitle: 'Изоляция зуба коффердамом / раббердамом (Sanctuary / OptiDam)',
		category: 'therapy',
		specialty: 'therapist',
		basePriceRub: 650,
		basePriceKopecks: 65000,
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K02.1', 'K04.0'],
		estimatedDurationMin: 15,
		isActive: true,
		isArchived: false,
		tags: ['коффердам', 'раббердам', 'изоляция'],
	},
	{
		id: 'srv-base-04',
		code804n: 'A16.07.002.010',
		statutoryTitle804n: 'Восстановление зуба пломбой при лечении поверхностного кариеса (светоотверждаемый композит)',
		commercialTitle: 'Лечение поверхностного кариеса светоотверждаемым композитом',
		category: 'therapy',
		specialty: 'therapist',
		basePriceRub: 3500,
		basePriceKopecks: 350000,
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K02.0'],
		estimatedDurationMin: 30,
		isActive: true,
		isArchived: false,
		tags: ['кариес', 'пломба', 'поверхностный кариес'],
	},
	{
		id: 'srv-base-05',
		code804n: 'A16.07.002.011',
		statutoryTitle804n: 'Восстановление зуба пломбой при лечении среднего кариеса (светоотверждаемый композит)',
		commercialTitle: 'Лечение среднего кариеса светоотверждаемым композитом (Estelite / Filtek)',
		category: 'therapy',
		specialty: 'therapist',
		basePriceRub: 4200,
		basePriceKopecks: 420000,
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K02.1'],
		estimatedDurationMin: 45,
		isActive: true,
		isArchived: false,
		tags: ['кариес', 'пломба', 'средний кариес', 'композит'],
	},
	{
		id: 'srv-base-06',
		code804n: 'A16.07.002.012',
		statutoryTitle804n: 'Восстановление зуба пломбой при лечении глубокого кариеса с наложением лечебной прокладки',
		commercialTitle: 'Лечение глубокого кариеса с изолирующей и лечебной прокладкой',
		category: 'therapy',
		specialty: 'therapist',
		basePriceRub: 4800,
		basePriceKopecks: 480000,
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K02.1', 'K02.2'],
		estimatedDurationMin: 45,
		isActive: true,
		isArchived: false,
		tags: ['глубокий кариес', 'прокладка', 'пломба'],
	},
	{
		id: 'srv-base-07',
		code804n: 'A16.07.030.001',
		statutoryTitle804n: 'Инструментальная и медикаментозная обработка 1 корневого канала',
		commercialTitle: 'Эндодонтическая обработка 1 корневого канала (машинные Ni-Ti файлы)',
		category: 'therapy',
		specialty: 'therapist',
		basePriceRub: 2100,
		basePriceKopecks: 210000,
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K04.0', 'K04.1'],
		estimatedDurationMin: 30,
		isActive: true,
		isArchived: false,
		tags: ['эндодонтия', 'канал', 'обработка канала'],
	},
	{
		id: 'srv-base-08',
		code804n: 'A16.07.030.002',
		statutoryTitle804n: 'Инструментальная и медикаментозная обработка 2 корневых каналов',
		commercialTitle: 'Эндодонтическая обработка 2 корневых каналов',
		category: 'therapy',
		specialty: 'therapist',
		basePriceRub: 3800,
		basePriceKopecks: 380000,
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K04.0', 'K04.1'],
		estimatedDurationMin: 45,
		isActive: true,
		isArchived: false,
		tags: ['эндодонтия', '2 канала'],
	},
	{
		id: 'srv-base-09',
		code804n: 'A16.07.030.003',
		statutoryTitle804n: 'Инструментальная и медикаментозная обработка 3 корневых каналов',
		commercialTitle: 'Эндодонтическая обработка 3 корневых каналов',
		category: 'therapy',
		specialty: 'therapist',
		basePriceRub: 5200,
		basePriceKopecks: 520000,
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K04.0', 'K04.1'],
		estimatedDurationMin: 60,
		isActive: true,
		isArchived: false,
		tags: ['эндодонтия', '3 канала'],
	},
	{
		id: 'srv-base-10',
		code804n: 'A16.07.030.004',
		statutoryTitle804n: 'Инструментальная и медикаментозная обработка 4 корневых каналов',
		commercialTitle: 'Эндодонтическая обработка 4 корневых каналов',
		category: 'therapy',
		specialty: 'therapist',
		basePriceRub: 6500,
		basePriceKopecks: 650000,
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K04.0', 'K04.1'],
		estimatedDurationMin: 60,
		isActive: true,
		isArchived: false,
		tags: ['эндодонтия', '4 канала'],
	},
	{
		id: 'srv-base-11',
		code804n: 'A16.07.008.002',
		statutoryTitle804n: 'Пломбирование корневого канала зуба гуттаперчевыми штифтами (1 канал)',
		commercialTitle: 'Пломбирование корневого канала гуттаперчей и силером (1 канал)',
		category: 'therapy',
		specialty: 'therapist',
		basePriceRub: 2400,
		basePriceKopecks: 240000,
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K04.0', 'K04.1'],
		estimatedDurationMin: 30,
		isActive: true,
		isArchived: false,
		tags: ['гуттаперча', 'пломбирование канала'],
	},
];

/**
 * Baseline 804n Services: Hygiene & Prevention (srv-base-21 to srv-base-23)
 */
export const HYGIENE_BASELINE_SERVICES: readonly ServicePricelistItem[] = [
	{
		id: 'srv-base-21',
		code804n: 'A16.07.051.001',
		statutoryTitle804n: 'Ультразвуковое удаление наддесневых и поддесневых зубных отложений (УЗ-скейлинг)',
		commercialTitle: 'Ультразвуковое удаление зубных отложений и поддесневого камня',
		category: 'hygiene',
		specialty: 'hygienist',
		basePriceRub: 3500,
		basePriceKopecks: 350000,
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K03.6', 'K05.1'],
		estimatedDurationMin: 30,
		isActive: true,
		isArchived: false,
		tags: ['гигиена', 'уз-чистка', 'скейлинг', 'зубной камень'],
	},
	{
		id: 'srv-base-22',
		code804n: 'A16.07.051',
		statutoryTitle804n: 'Снятие пигментированного зубного налета аппаратом Air-Flow',
		commercialTitle: 'Снятие пигментированного налета и биопленки системой Air-Flow (порошок KaVo)',
		category: 'hygiene',
		specialty: 'hygienist',
		basePriceRub: 2500,
		basePriceKopecks: 250000,
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K03.6'],
		estimatedDurationMin: 30,
		isActive: true,
		isArchived: false,
		tags: ['air-flow', 'чистка', 'налет курильщика', 'полировка'],
	},
	{
		id: 'srv-base-23',
		code804n: 'A11.07.024',
		statutoryTitle804n: 'Глубокое фторирование эмали зубов (реминерализующая терапия)',
		commercialTitle: 'Глубокое фторирование эмали и дентина (Tiefenfluorid)',
		category: 'hygiene',
		specialty: 'hygienist',
		basePriceRub: 1200,
		basePriceKopecks: 120000,
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K02.0', 'K03.1'],
		estimatedDurationMin: 20,
		isActive: true,
		isArchived: false,
		tags: ['фторирование', 'реминерализация', 'эмаль'],
	},
];
