/**
 * DENTE Dental CRM — Statutory Minzdrav Order № 804n Service Catalog & Nomenclature Presets
 *
 * Statutory reference: Приказ Минздрава России от 13.10.2017 N 804н
 * "Об утверждении номенклатуры медицинских услуг" (с изменениями и дополнениями).
 *
 * Tax compliance: пп. 2 п. 2 ст. 149 НК РФ — медицинские услуги, оказываемые медицинскими
 * организациями, не подлежат налогообложению (освобождаются от налогообложения) НДС (0%).
 */

export type Order804nCategory =
	| 'therapy'
	| 'surgery'
	| 'orthopedics'
	| 'orthodontics'
	| 'pediatric'
	| 'radiology'
	| 'hygiene'
	| 'periodontics'
	| 'anesthesia'
	| 'consultation'
	| 'other';

export type DoctorSpecialty =
	| 'therapist'
	| 'surgeon'
	| 'orthopedist'
	| 'orthodontist'
	| 'pediatric'
	| 'hygienist'
	| 'radiologist'
	| 'anesthesiologist'
	| 'general';

export type PriceTierKind = 'standard' | 'vip' | 'dms' | 'promo';

export interface ServicePricelistItem {
	readonly id: string;
	readonly code804n: string;
	readonly statutoryTitle804n: string;
	readonly commercialTitle: string;
	readonly category: Order804nCategory;
	readonly specialty: DoctorSpecialty;
	readonly basePriceRub: number;
	readonly basePriceKopecks: number;
	readonly materialCostRub?: number | undefined;
	readonly labCostRub?: number | undefined;
	readonly tierPrices?: Partial<Record<PriceTierKind, number>> | undefined;
	readonly vatRate: 0;
	readonly vatExemptionArticle: string;
	readonly icd10Indications: readonly string[];
	readonly estimatedDurationMin: number;
	readonly isAnatomicalCanalScalable?: boolean | undefined;
	readonly isActive: boolean;
	readonly isArchived: boolean;
	readonly tags: readonly string[];
}

export const CATEGORY_LABELS: Record<Order804nCategory, string> = {
	consultation: 'Консультации и осмотры',
	therapy: 'Терапия и эндодонтия',
	surgery: 'Хирургия и имплантация',
	orthopedics: 'Ортопедия и протезирование',
	orthodontics: 'Ортодонтия',
	pediatric: 'Детская стоматология',
	radiology: 'Диагностика и рентген',
	hygiene: 'Гигиена и профилактика',
	periodontics: 'Пародонтология',
	anesthesia: 'Анестезиология',
	other: 'Прочие услуги',
};

export const SPECIALTY_LABELS: Record<DoctorSpecialty, string> = {
	therapist: 'Стоматолог-терапевт',
	surgeon: 'Стоматолог-хирург / имплантолог',
	orthopedist: 'Стоматолог-ортопед',
	orthodontist: 'Стоматолог-ортодонт',
	pediatric: 'Детский стоматолог',
	hygienist: 'Гигиенист стоматологический',
	radiologist: 'Рентгенолог / диагност',
	anesthesiologist: 'Врач анестезиолог-реаниматолог',
	general: 'Врач общей практики / универсал',
};

export const PRICE_TIER_LABELS: Record<PriceTierKind, string> = {
	standard: 'Основной прайс (100%)',
	vip: 'VIP прейскурант (+20%)',
	dms: 'Тариф ДМС (СОГАЗ/Ингосстрах)',
	promo: 'Акционный / Спеццена (-10%)',
};

export const STATUTORY_VAT_EXEMPTION_NOTE = 'НДС не облагается (пп. 2 п. 2 ст. 149 НК РФ)';

/**
 * Canonical Presets of Statutory Russian Order 804n Nomenclature for Dental Practices
 */
export const STATUTORY_ORDER_804N_PRESETS: readonly ServicePricelistItem[] = [
	// =========================================================================
	// 1. КОНСУЛЬТАЦИИ И ОСМОТРЫ (B01.065)
	// =========================================================================
	{
		id: 'srv-b01-065-001',
		code804n: 'B01.065.001',
		statutoryTitle804n: 'Прием (осмотр, консультация) врача-стоматолога-терапевта первичный',
		commercialTitle: 'Первичная консультация врача-стоматолога с осмотром и составлением плана лечения',
		category: 'consultation',
		specialty: 'therapist',
		basePriceRub: 1500,
		basePriceKopecks: 150000,
		materialCostRub: 250,
		labCostRub: 0,
		tierPrices: { vip: 2000, dms: 1200, promo: 0 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['Z01.2'],
		estimatedDurationMin: 30,
		isActive: true,
		isArchived: false,
		tags: ['консультация', 'осмотр', 'план лечения', 'первичный прием'],
	},
	{
		id: 'srv-b01-065-002',
		code804n: 'B01.065.002',
		statutoryTitle804n: 'Прием (осмотр, консультация) врача-стоматолога-терапевта повторный',
		commercialTitle: 'Повторный прием врача-стоматолога (контрольный осмотр / коррекция)',
		category: 'consultation',
		specialty: 'therapist',
		basePriceRub: 800,
		basePriceKopecks: 80000,
		materialCostRub: 150,
		labCostRub: 0,
		tierPrices: { vip: 1000, dms: 700, promo: 500 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['Z01.2'],
		estimatedDurationMin: 20,
		isActive: true,
		isArchived: false,
		tags: ['повторный прием', 'контроль', 'осмотр'],
	},
	{
		id: 'srv-b01-065-003',
		code804n: 'B01.065.003',
		statutoryTitle804n: 'Прием (осмотр, консультация) врача-стоматолога-хирурга первичный',
		commercialTitle: 'Консультация хирурга-имплантолога с анализом КЛКТ и 3D-планированием',
		category: 'consultation',
		specialty: 'surgeon',
		basePriceRub: 2000,
		basePriceKopecks: 200000,
		materialCostRub: 300,
		labCostRub: 0,
		tierPrices: { vip: 2800, dms: 1500, promo: 1000 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K08.1', 'Z01.2'],
		estimatedDurationMin: 40,
		isActive: true,
		isArchived: false,
		tags: ['хирург', 'имплантация', 'консультация', '3d-планирование'],
	},
	{
		id: 'srv-b01-065-007',
		code804n: 'B01.065.007',
		statutoryTitle804n: 'Прием (осмотр, консультация) врача-стоматолога-ортопеда первичный',
		commercialTitle: 'Консультация врача-стоматолога-ортопеда с фотопротоколом и диагностическими моделями',
		category: 'consultation',
		specialty: 'orthopedist',
		basePriceRub: 2200,
		basePriceKopecks: 220000,
		materialCostRub: 400,
		labCostRub: 0,
		tierPrices: { vip: 3000, dms: 1800, promo: 1500 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K08.1', 'K08.2'],
		estimatedDurationMin: 45,
		isActive: true,
		isArchived: false,
		tags: ['ортопед', 'протезирование', 'виниры', 'коронки'],
	},
	{
		id: 'srv-b01-065-009',
		code804n: 'B01.065.009',
		statutoryTitle804n: 'Прием (осмотр, консультация) врача-стоматолога-ортодонта первичный',
		commercialTitle: 'Консультация врача-ортодонта (диагностика прикуса, расчет ТРГ, подбор брекетов/элайнеров)',
		category: 'consultation',
		specialty: 'orthodontist',
		basePriceRub: 2500,
		basePriceKopecks: 250000,
		materialCostRub: 350,
		labCostRub: 0,
		tierPrices: { vip: 3500, dms: 2000, promo: 1500 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K07.2', 'K07.4'],
		estimatedDurationMin: 45,
		isActive: true,
		isArchived: false,
		tags: ['ортодонт', 'прикус', 'брекеты', 'элайнеры'],
	},

	// =========================================================================
	// 2. ТЕРАПИЯ И ЭНДОДОНТИЯ (A16.07)
	// =========================================================================
	{
		id: 'srv-a16-07-002-001',
		code804n: 'A16.07.002.001',
		statutoryTitle804n: 'Восстановление зуба пломбой I, V, VI класс по Блэку с использованием материалов из фотополимеров',
		commercialTitle: 'Лечение поверхностного/среднего кариеса с фотополимерной пломбой (Estelite/Filtek)',
		category: 'therapy',
		specialty: 'therapist',
		basePriceRub: 5500,
		basePriceKopecks: 550000,
		materialCostRub: 950,
		labCostRub: 0,
		tierPrices: { vip: 7200, dms: 4500, promo: 4500 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K02.0', 'K02.1'],
		estimatedDurationMin: 45,
		isActive: true,
		isArchived: false,
		tags: ['кариес', 'пломба', 'композит', 'estelite', 'filtek'],
	},
	{
		id: 'srv-a16-07-002-002',
		code804n: 'A16.07.002.002',
		statutoryTitle804n: 'Восстановление зуба пломбой II, III класс по Блэку с использованием материалов из фотополимеров',
		commercialTitle: 'Лечение глубокого кариеса с лечебной прокладкой и контактным пунктом',
		category: 'therapy',
		specialty: 'therapist',
		basePriceRub: 6800,
		basePriceKopecks: 680000,
		materialCostRub: 1300,
		labCostRub: 0,
		tierPrices: { vip: 8800, dms: 5500, promo: 5800 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K02.1', 'K02.2'],
		estimatedDurationMin: 60,
		isActive: true,
		isArchived: false,
		tags: ['глубокий кариес', 'пломба', 'контактный пункт', 'прокладка'],
	},
	{
		id: 'srv-a16-07-002-003',
		code804n: 'A16.07.002.003',
		statutoryTitle804n: 'Восстановление зуба пломбой IV класс по Блэку с использованием материалов из фотополимеров',
		commercialTitle: 'Художественная эстетическая реставрация фронтального зуба (прямой композитный винир)',
		category: 'therapy',
		specialty: 'therapist',
		basePriceRub: 9500,
		basePriceKopecks: 950000,
		materialCostRub: 1800,
		labCostRub: 0,
		tierPrices: { vip: 12500, dms: 7800, promo: 8000 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K03.8', 'K02.1'],
		estimatedDurationMin: 90,
		isActive: true,
		isArchived: false,
		tags: ['реставрация', 'прямой винир', 'эстетика', 'фронт'],
	},
	{
		id: 'srv-a16-07-003',
		code804n: 'A16.07.003',
		statutoryTitle804n: 'Восстановление зуба пломбировочными материалами с использованием штифта',
		commercialTitle: 'Восстановление культи зуба с фиксацией стекловолоконного штифта (Build-Up)',
		category: 'therapy',
		specialty: 'therapist',
		basePriceRub: 4500,
		basePriceKopecks: 450000,
		materialCostRub: 1100,
		labCostRub: 0,
		tierPrices: { vip: 5800, dms: 3800, promo: 3900 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K02.2', 'K04.0'],
		estimatedDurationMin: 45,
		isActive: true,
		isArchived: false,
		tags: ['штифт', 'билдап', 'стекловолокно', 'культя'],
	},
	{
		id: 'srv-a16-07-030-001',
		code804n: 'A16.07.030.001',
		statutoryTitle804n: 'Инструментальная и медикаментозная обработка корневого канала (1-канальный зуб)',
		commercialTitle: 'Механическая и медикаментозная обработка корневого канала машинным NiTi-инструментом (1 канал)',
		category: 'therapy',
		specialty: 'therapist',
		basePriceRub: 3500,
		basePriceKopecks: 350000,
		materialCostRub: 800,
		labCostRub: 0,
		tierPrices: { vip: 4500, dms: 2900, promo: 3000 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K04.0', 'K04.1'],
		estimatedDurationMin: 40,
		isAnatomicalCanalScalable: true,
		isActive: true,
		isArchived: false,
		tags: ['эндодонтия', 'обработка канала', 'пульпит', 'периодонтит'],
	},
	{
		id: 'srv-a16-07-008-001',
		code804n: 'A16.07.008.001',
		statutoryTitle804n: 'Пломбирование корневого канала зуба пастой/гуттаперчей (1 канал)',
		commercialTitle: 'Обтурация корневого канала горячей гуттаперчей / биокерамическим силером (1 канал)',
		category: 'therapy',
		specialty: 'therapist',
		basePriceRub: 4000,
		basePriceKopecks: 400000,
		materialCostRub: 900,
		labCostRub: 0,
		tierPrices: { vip: 5200, dms: 3300, promo: 3500 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K04.0', 'K04.1'],
		estimatedDurationMin: 35,
		isAnatomicalCanalScalable: true,
		isActive: true,
		isArchived: false,
		tags: ['обтурация', 'гуттаперча', 'силер', 'пломбирование канала'],
	},
	{
		id: 'srv-a16-07-082',
		code804n: 'A16.07.082',
		statutoryTitle804n: 'Распломбирование корневого канала ранее леченного пастой/гуттаперчей',
		commercialTitle: 'Ревизия и распломбирование корневого канала (перелечивание зуба)',
		category: 'therapy',
		specialty: 'therapist',
		basePriceRub: 2800,
		basePriceKopecks: 280000,
		materialCostRub: 600,
		labCostRub: 0,
		tierPrices: { vip: 3600, dms: 2200, promo: 2300 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K04.5', 'K04.4'],
		estimatedDurationMin: 45,
		isActive: true,
		isArchived: false,
		tags: ['перелечивание', 'распломбирование', 'ревизия'],
	},
	{
		id: 'srv-a16-07-091',
		code804n: 'A16.07.091',
		statutoryTitle804n: 'Временное пломбирование лекарственным препаратом корневого канала',
		commercialTitle: 'Временное пломбирование корневого канала гидроксидом кальция Ca(OH)2 при периодонтите',
		category: 'therapy',
		specialty: 'therapist',
		basePriceRub: 2000,
		basePriceKopecks: 200000,
		materialCostRub: 450,
		labCostRub: 0,
		tierPrices: { vip: 2600, dms: 1600, promo: 1700 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K04.4', 'K04.5'],
		estimatedDurationMin: 30,
		isActive: true,
		isArchived: false,
		tags: ['кальций', 'caoh2', 'периодонтит', 'лекарство'],
	},
	{
		id: 'srv-a16-07-002-005',
		code804n: 'A16.07.002.005',
		statutoryTitle804n: 'Наложение коффердама (раббердама)',
		commercialTitle: 'Изоляция операционного поля системой Коффердам / ОптраГейт',
		category: 'therapy',
		specialty: 'therapist',
		basePriceRub: 900,
		basePriceKopecks: 90000,
		materialCostRub: 250,
		labCostRub: 0,
		tierPrices: { vip: 1200, dms: 700, promo: 700 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K02.0', 'K04.0'],
		estimatedDurationMin: 10,
		isActive: true,
		isArchived: false,
		tags: ['коффердам', 'раббердам', 'изоляция', 'оптрагейт'],
	},

	// =========================================================================
	// 3. ХИРУРГИЯ И ИМПЛАНТАЦИЯ (A16.07)
	// =========================================================================
	{
		id: 'srv-a16-07-001-001',
		code804n: 'A16.07.001.001',
		statutoryTitle804n: 'Удаление постоянного зуба простое',
		commercialTitle: 'Простое атравматичное удаление зуба щипцами/элеватором',
		category: 'surgery',
		specialty: 'surgeon',
		basePriceRub: 3500,
		basePriceKopecks: 350000,
		materialCostRub: 500,
		labCostRub: 0,
		tierPrices: { vip: 4500, dms: 2800, promo: 2900 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K08.3', 'K04.7'],
		estimatedDurationMin: 30,
		isActive: true,
		isArchived: false,
		tags: ['удаление', 'простое удаление', 'экстракция'],
	},
	{
		id: 'srv-a16-07-001-002',
		code804n: 'A16.07.001.002',
		statutoryTitle804n: 'Удаление постоянного зуба сложное с разъединением корней',
		commercialTitle: 'Сложное удаление зуба с сепарацией корней, остеотомией и наложением швов',
		category: 'surgery',
		specialty: 'surgeon',
		basePriceRub: 6500,
		basePriceKopecks: 650000,
		materialCostRub: 900,
		labCostRub: 0,
		tierPrices: { vip: 8500, dms: 5000, promo: 5200 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K08.3', 'K04.8'],
		estimatedDurationMin: 60,
		isActive: true,
		isArchived: false,
		tags: ['сложное удаление', 'сепарация', 'швы'],
	},
	{
		id: 'srv-a16-07-024',
		code804n: 'A16.07.024',
		statutoryTitle804n: 'Операция удаления ретинированного, дистопированного или сверхкомплектного зуба',
		commercialTitle: 'Удаление ретинированного/дистопированного зуба мудрости (8-ки) с пьезохирургией',
		category: 'surgery',
		specialty: 'surgeon',
		basePriceRub: 9500,
		basePriceKopecks: 950000,
		materialCostRub: 1400,
		labCostRub: 0,
		tierPrices: { vip: 12500, dms: 7500, promo: 7900 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K01.0', 'K01.1'],
		estimatedDurationMin: 60,
		isActive: true,
		isArchived: false,
		tags: ['зуб мудрости', 'ретинированный', 'восьмерка', 'дистопия'],
	},
	{
		id: 'srv-a16-07-054-001',
		code804n: 'A16.07.054.001',
		statutoryTitle804n: 'Внутрикостная дентальная имплантация (установка имплантата)',
		commercialTitle: 'Установка дентального имплантата системы Osstem TS III (Южная Корея)',
		category: 'surgery',
		specialty: 'surgeon',
		basePriceRub: 35000,
		basePriceKopecks: 3500000,
		materialCostRub: 11500,
		labCostRub: 0,
		tierPrices: { vip: 45000, dms: 30000, promo: 28900 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K08.1'],
		estimatedDurationMin: 60,
		isActive: true,
		isArchived: false,
		tags: ['имплантация', 'osstem', 'титан', 'имплант'],
	},
	{
		id: 'srv-a16-07-054-002',
		code804n: 'A16.07.054.002',
		statutoryTitle804n: 'Внутрикостная дентальная имплантация премиум-системы',
		commercialTitle: 'Установка дентального имплантата Straumann Roxolid SLActive (Швейцария)',
		category: 'surgery',
		specialty: 'surgeon',
		basePriceRub: 65000,
		basePriceKopecks: 6500000,
		materialCostRub: 24000,
		labCostRub: 0,
		tierPrices: { vip: 85000, dms: 55000, promo: 59000 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K08.1'],
		estimatedDurationMin: 60,
		isActive: true,
		isArchived: false,
		tags: ['straumann', 'швейцария', 'премиум', 'имплант'],
	},
	{
		id: 'srv-a16-07-007',
		code804n: 'A16.07.007',
		statutoryTitle804n: 'Установка формирователя десны на имплантат',
		commercialTitle: 'Установка формирователя десны (раскрытие имплантата, 2-й хирургический этап)',
		category: 'surgery',
		specialty: 'surgeon',
		basePriceRub: 4500,
		basePriceKopecks: 450000,
		materialCostRub: 1200,
		labCostRub: 0,
		tierPrices: { vip: 6000, dms: 3600, promo: 3800 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K08.1'],
		estimatedDurationMin: 30,
		isActive: true,
		isArchived: false,
		tags: ['формирователь', 'фдм', 'десна', 'имплант'],
	},
	{
		id: 'srv-a16-07-041',
		code804n: 'A16.07.041',
		statutoryTitle804n: 'Костная пластика челюстно-лицевой области (синус-лифтинг)',
		commercialTitle: 'Закрытый синус-лифтинг с остеопластическим материалом (Bio-Oss)',
		category: 'surgery',
		specialty: 'surgeon',
		basePriceRub: 25000,
		basePriceKopecks: 2500000,
		materialCostRub: 9000,
		labCostRub: 0,
		tierPrices: { vip: 32000, dms: 21000, promo: 22000 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K08.2'],
		estimatedDurationMin: 45,
		isActive: true,
		isArchived: false,
		tags: ['синус-лифтинг', 'кость', 'bio-oss', 'аугментация'],
	},
	{
		id: 'srv-a16-07-055',
		code804n: 'A16.07.055',
		statutoryTitle804n: 'Синус-лифтинг открытый (латеральный доступ)',
		commercialTitle: 'Открытый синус-лифтинг с латеральным окном и коллагеновой мембраной (Bio-Gide)',
		category: 'surgery',
		specialty: 'surgeon',
		basePriceRub: 45000,
		basePriceKopecks: 4500000,
		materialCostRub: 16000,
		labCostRub: 0,
		tierPrices: { vip: 58000, dms: 38000, promo: 39900 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K08.2'],
		estimatedDurationMin: 90,
		isActive: true,
		isArchived: false,
		tags: ['открытый синус', 'латеральный', 'мембрана', 'bio-gide'],
	},

	// =========================================================================
	// 4. ОРТОПЕДИЯ И ПРОТЕЗИРОВАНИЕ (A16.07)
	// =========================================================================
	{
		id: 'srv-a16-07-006-001',
		code804n: 'A16.07.006.001',
		statutoryTitle804n: 'Протезирование зуба коронкой постоянной металлокерамической',
		commercialTitle: 'Металлокерамическая коронка на каркасе из CoCr сплава',
		category: 'orthopedics',
		specialty: 'orthopedist',
		basePriceRub: 14500,
		basePriceKopecks: 1450000,
		materialCostRub: 1200,
		labCostRub: 4500,
		tierPrices: { vip: 18500, dms: 11500, promo: 12000 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K08.1', 'K02.2'],
		estimatedDurationMin: 60,
		isActive: true,
		isArchived: false,
		tags: ['металлокерамика', 'коронка', 'протезирование'],
	},
	{
		id: 'srv-a16-07-006-002',
		code804n: 'A16.07.006.002',
		statutoryTitle804n: 'Протезирование зуба коронкой из диоксида циркония',
		commercialTitle: 'Коронка из диоксида циркония цельнофрезерованная MultiLayer (Katana/Prettau)',
		category: 'orthopedics',
		specialty: 'orthopedist',
		basePriceRub: 24000,
		basePriceKopecks: 2400000,
		materialCostRub: 1800,
		labCostRub: 7500,
		tierPrices: { vip: 31000, dms: 19500, promo: 21000 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K08.1', 'K02.2'],
		estimatedDurationMin: 60,
		isActive: true,
		isArchived: false,
		tags: ['цирконий', 'zirconia', 'коронка', 'katana', 'prettau'],
	},
	{
		id: 'srv-a16-07-006-003',
		code804n: 'A16.07.006.003',
		statutoryTitle804n: 'Протезирование цельнокерамической коронкой / виниром',
		commercialTitle: 'Керамический винир / коронка из прессованной керамики E.max (IPS e.max Press)',
		category: 'orthopedics',
		specialty: 'orthopedist',
		basePriceRub: 28000,
		basePriceKopecks: 2800000,
		materialCostRub: 2200,
		labCostRub: 9000,
		tierPrices: { vip: 36000, dms: 23000, promo: 24900 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K03.8', 'K08.1'],
		estimatedDurationMin: 75,
		isActive: true,
		isArchived: false,
		tags: ['винир', 'emax', 'керамика', 'эстетика', 'e.max'],
	},
	{
		id: 'srv-a16-07-006-005',
		code804n: 'A16.07.006.005',
		statutoryTitle804n: 'Протезирование коронкой на имплантате с винтовой фиксацией',
		commercialTitle: 'Коронка из диоксида циркония на имплантате с винтовой фиксацией на Ti-base',
		category: 'orthopedics',
		specialty: 'orthopedist',
		basePriceRub: 34000,
		basePriceKopecks: 3400000,
		materialCostRub: 3500,
		labCostRub: 11000,
		tierPrices: { vip: 44000, dms: 28000, promo: 29900 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K08.1'],
		estimatedDurationMin: 60,
		isActive: true,
		isArchived: false,
		tags: ['коронка на импланте', 'винтовая фиксация', 'титановое основание', 'tibase'],
	},
	{
		id: 'srv-a16-07-006-004',
		code804n: 'A16.07.006.004',
		statutoryTitle804n: 'Протезирование временной коронкой',
		commercialTitle: 'Временная коронка длительного ношения PMMA Cad/Cam',
		category: 'orthopedics',
		specialty: 'orthopedist',
		basePriceRub: 4500,
		basePriceKopecks: 450000,
		materialCostRub: 500,
		labCostRub: 1500,
		tierPrices: { vip: 5800, dms: 3600, promo: 3800 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K08.1'],
		estimatedDurationMin: 30,
		isActive: true,
		isArchived: false,
		tags: ['временная коронка', 'pmma', 'пластмасса'],
	},
	{
		id: 'srv-a16-07-003-001',
		code804n: 'A16.07.003.001',
		statutoryTitle804n: 'Восстановление зуба культевой штифтовой вкладкой',
		commercialTitle: 'Культевая штифтовая вкладка цельнолитая CoCr / диоксид циркония',
		category: 'orthopedics',
		specialty: 'orthopedist',
		basePriceRub: 7500,
		basePriceKopecks: 750000,
		materialCostRub: 800,
		labCostRub: 2500,
		tierPrices: { vip: 9800, dms: 6000, promo: 6500 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K02.2'],
		estimatedDurationMin: 45,
		isActive: true,
		isArchived: false,
		tags: ['культевая вкладка', 'вкладка', 'кшв', 'штифт'],
	},

	// =========================================================================
	// 5. ОРТОДОНТИЯ (A16.07)
	// =========================================================================
	{
		id: 'srv-a16-07-047-001',
		code804n: 'A16.07.047.001',
		statutoryTitle804n: 'Ортодонтическая коррекция с применением брекет-системы (металлическая)',
		commercialTitle: 'Фиксация самолигирующей металлической брекет-системы Damon Q (1 челюсть)',
		category: 'orthodontics',
		specialty: 'orthodontist',
		basePriceRub: 45000,
		basePriceKopecks: 4500000,
		materialCostRub: 18000,
		labCostRub: 0,
		tierPrices: { vip: 58000, dms: 38000, promo: 39000 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K07.2', 'K07.4'],
		estimatedDurationMin: 90,
		isActive: true,
		isArchived: false,
		tags: ['брекеты', 'damon q', 'металл', 'ортодонтия'],
	},
	{
		id: 'srv-a16-07-047-002',
		code804n: 'A16.07.047.002',
		statutoryTitle804n: 'Ортодонтическая коррекция с применением брекет-системы (керамическая)',
		commercialTitle: 'Фиксация эстетической керамической брекет-системы Damon Clear (1 челюсть)',
		category: 'orthodontics',
		specialty: 'orthodontist',
		basePriceRub: 65000,
		basePriceKopecks: 6500000,
		materialCostRub: 28000,
		labCostRub: 0,
		tierPrices: { vip: 85000, dms: 55000, promo: 58000 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K07.2', 'K07.4'],
		estimatedDurationMin: 90,
		isActive: true,
		isArchived: false,
		tags: ['керамика', 'damon clear', 'эстетика', 'сапфир'],
	},
	{
		id: 'srv-a16-07-047-003',
		code804n: 'A16.07.047.003',
		statutoryTitle804n: 'Активация ортодонтического аппарата / брекет-системы',
		commercialTitle: 'Плановый прием с заменой ортодонтической дуги и активацией брекетов (1 челюсть)',
		category: 'orthodontics',
		specialty: 'orthodontist',
		basePriceRub: 4500,
		basePriceKopecks: 450000,
		materialCostRub: 1100,
		labCostRub: 0,
		tierPrices: { vip: 5800, dms: 3800, promo: 3900 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K07.2'],
		estimatedDurationMin: 30,
		isActive: true,
		isArchived: false,
		tags: ['активация', 'дуга', 'прием ортодонта'],
	},
	{
		id: 'srv-a16-07-047-004',
		code804n: 'A16.07.047.004',
		statutoryTitle804n: 'Ортодонтическое лечение с применением элайнеров (прозрачных капп)',
		commercialTitle: 'Комплексный курс лечения на элайнерах Star Smile / FlexiLigner (полный кейс)',
		category: 'orthodontics',
		specialty: 'orthodontist',
		basePriceRub: 240000,
		basePriceKopecks: 24000000,
		materialCostRub: 90000,
		labCostRub: 0,
		tierPrices: { vip: 300000, dms: 210000, promo: 219000 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K07.2', 'K07.4'],
		estimatedDurationMin: 60,
		isActive: true,
		isArchived: false,
		tags: ['элайнеры', 'каппы', 'star smile', 'flexiligner', 'invisalign'],
	},

	// =========================================================================
	// 6. ДЕТСКАЯ СТОМАТОЛОГИЯ (A16.07 / B01.065)
	// =========================================================================
	{
		id: 'srv-a16-07-002-010',
		code804n: 'A16.07.002.010',
		statutoryTitle804n: 'Восстановление зуба пломбой из стеклоиономерного цемента (молочный зуб)',
		commercialTitle: 'Лечение кариеса временного (молочного) зуба с пломбой Fuji IX / Twinky Star',
		category: 'pediatric',
		specialty: 'pediatric',
		basePriceRub: 3800,
		basePriceKopecks: 380000,
		materialCostRub: 650,
		labCostRub: 0,
		tierPrices: { vip: 4900, dms: 3100, promo: 3200 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K02.0', 'K02.1'],
		estimatedDurationMin: 30,
		isActive: true,
		isArchived: false,
		tags: ['дети', 'молочный зуб', 'кариес', 'fuji', 'сиц'],
	},
	{
		id: 'srv-a16-07-057',
		code804n: 'A16.07.057',
		statutoryTitle804n: 'Герметизация фиссур одного зуба',
		commercialTitle: 'Неинвазивная герметизация фиссур моляра материалом Clinpro / Fissurit',
		category: 'pediatric',
		specialty: 'pediatric',
		basePriceRub: 2200,
		basePriceKopecks: 220000,
		materialCostRub: 450,
		labCostRub: 0,
		tierPrices: { vip: 2800, dms: 1800, promo: 1800 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K02.0', 'Z29.8'],
		estimatedDurationMin: 20,
		isActive: true,
		isArchived: false,
		tags: ['герметизация', 'фиссуры', 'профилактика', 'дети'],
	},
	{
		id: 'srv-a16-07-001-010',
		code804n: 'A16.07.001.010',
		statutoryTitle804n: 'Удаление временного (молочного) зуба',
		commercialTitle: 'Бережное удаление временного зуба с аппликационной/инфильтрационной анестезией',
		category: 'pediatric',
		specialty: 'pediatric',
		basePriceRub: 2500,
		basePriceKopecks: 250000,
		materialCostRub: 350,
		labCostRub: 0,
		tierPrices: { vip: 3200, dms: 2000, promo: 2100 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K00.6', 'K04.7'],
		estimatedDurationMin: 20,
		isActive: true,
		isArchived: false,
		tags: ['удаление молочного', 'детская хирургия', 'смена прикуса'],
	},

	// =========================================================================
	// 7. ДИАГНОСТИКА И РЕНТГЕН (A06.07)
	// =========================================================================
	{
		id: 'srv-a06-07-007',
		code804n: 'A06.07.007',
		statutoryTitle804n: 'Прицельная внутриротовая контактная рентгенография',
		commercialTitle: 'Цифровой прицельный снимок зуба на радиовизиографе (RVG)',
		category: 'radiology',
		specialty: 'radiologist',
		basePriceRub: 600,
		basePriceKopecks: 60000,
		materialCostRub: 80,
		labCostRub: 0,
		tierPrices: { vip: 800, dms: 500, promo: 450 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['Z01.2', 'K02', 'K04'],
		estimatedDurationMin: 10,
		isActive: true,
		isArchived: false,
		tags: ['снимок', 'rvg', 'визиограф', 'рентген'],
	},
	{
		id: 'srv-a06-07-013',
		code804n: 'A06.07.013',
		statutoryTitle804n: 'Ортопантомография (панорамный снимок)',
		commercialTitle: 'Панорамный снимок челюстей (ОПТГ) в высоком разрешении',
		category: 'radiology',
		specialty: 'radiologist',
		basePriceRub: 1600,
		basePriceKopecks: 160000,
		materialCostRub: 150,
		labCostRub: 0,
		tierPrices: { vip: 2000, dms: 1300, promo: 1200 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['Z01.2', 'K08'],
		estimatedDurationMin: 15,
		isActive: true,
		isArchived: false,
		tags: ['оптг', 'панорама', 'ортопантомограмма'],
	},
	{
		id: 'srv-a06-07-012',
		code804n: 'A06.07.012',
		statutoryTitle804n: 'Компьютерная томография челюстно-лицевой области (КЛКТ)',
		commercialTitle: '3D Компьютерная томография (КЛКТ) обеих челюстей (FOV 12x9 см / Vatech)',
		category: 'radiology',
		specialty: 'radiologist',
		basePriceRub: 3800,
		basePriceKopecks: 380000,
		materialCostRub: 300,
		labCostRub: 0,
		tierPrices: { vip: 4900, dms: 3000, promo: 2900 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['Z01.2', 'K08.1', 'K01.1'],
		estimatedDurationMin: 20,
		isActive: true,
		isArchived: false,
		tags: ['клкт', '3d снимок', 'томография', 'vatech', 'ct'],
	},

	// =========================================================================
	// 8. ГИГИЕНА И ПРОФИЛАКТИКА (A16.07 / A11.07)
	// =========================================================================
	{
		id: 'srv-a16-07-051-001',
		code804n: 'A16.07.051.001',
		statutoryTitle804n: 'Профессиональная гигиена полости рта и зубов (комплекс)',
		commercialTitle: 'Комплексная гигиена полости рта (УЗ-скейлинг + Air-Flow + полировка + фторирование)',
		category: 'hygiene',
		specialty: 'hygienist',
		basePriceRub: 6500,
		basePriceKopecks: 650000,
		materialCostRub: 1200,
		labCostRub: 0,
		tierPrices: { vip: 8500, dms: 5000, promo: 4900 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K03.6', 'K05.0'],
		estimatedDurationMin: 60,
		isActive: true,
		isArchived: false,
		tags: ['гигиена', 'чистка', 'air flow', 'ультразвук', 'фторирование'],
	},
	{
		id: 'srv-a16-07-050',
		code804n: 'A16.07.050',
		statutoryTitle804n: 'Профессиональное отбеливание зубов в условиях стоматологического кабинета',
		commercialTitle: 'Клиническое отбеливание зубов холодным светом (Philips ZOOM 4 / Beyond Polus)',
		category: 'hygiene',
		specialty: 'hygienist',
		basePriceRub: 29000,
		basePriceKopecks: 2900000,
		materialCostRub: 9500,
		labCostRub: 0,
		tierPrices: { vip: 37000, dms: 25000, promo: 24900 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['K03.7', 'K03.8'],
		estimatedDurationMin: 90,
		isActive: true,
		isArchived: false,
		tags: ['отбеливание', 'zoom 4', 'beyond', 'белоснежная улыбка'],
	},

	// =========================================================================
	// 9. АНЕСТЕЗИОЛОГИЯ (A16.07.004)
	// =========================================================================
	{
		id: 'srv-a16-07-004-001',
		code804n: 'A16.07.004.001',
		statutoryTitle804n: 'Анестезия местная инфильтрационная',
		commercialTitle: 'Местная инфильтрационная анестезия (Ультракаин Д-С форте 1:100 000)',
		category: 'anesthesia',
		specialty: 'therapist',
		basePriceRub: 950,
		basePriceKopecks: 95000,
		materialCostRub: 220,
		labCostRub: 0,
		tierPrices: { vip: 1300, dms: 750, promo: 750 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['Z01.2'],
		estimatedDurationMin: 10,
		isActive: true,
		isArchived: false,
		tags: ['анестезия', 'инфильтрация', 'ультракаин', 'обезболивание'],
	},
	{
		id: 'srv-a16-07-004-002',
		code804n: 'A16.07.004.002',
		statutoryTitle804n: 'Анестезия местная проводниковая',
		commercialTitle: 'Проводниковая (мандибулярная / торусальная) анестезия',
		category: 'anesthesia',
		specialty: 'surgeon',
		basePriceRub: 1200,
		basePriceKopecks: 120000,
		materialCostRub: 280,
		labCostRub: 0,
		tierPrices: { vip: 1600, dms: 950, promo: 950 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['Z01.2'],
		estimatedDurationMin: 15,
		isActive: true,
		isArchived: false,
		tags: ['проводниковая', 'мандибулярная', 'торусальная'],
	},
	{
		id: 'srv-a16-07-004-003',
		code804n: 'A16.07.004.003',
		statutoryTitle804n: 'Анестезия местная без адреналина (мепивакаин)',
		commercialTitle: 'Безадреналиновая анестезия Мепивакаин / Скандонест 3% (для пациентов группы риска)',
		category: 'anesthesia',
		specialty: 'therapist',
		basePriceRub: 1100,
		basePriceKopecks: 110000,
		materialCostRub: 260,
		labCostRub: 0,
		tierPrices: { vip: 1500, dms: 900, promo: 900 },
		vatRate: 0,
		vatExemptionArticle: STATUTORY_VAT_EXEMPTION_NOTE,
		icd10Indications: ['Z01.2'],
		estimatedDurationMin: 10,
		isActive: true,
		isArchived: false,
		tags: ['мепивакаин', 'без адреналина', 'сердечники', 'беременные'],
	},
];
