/**
 * anesthesiaTechniqueCatalog.ts — Catalogs for Dental Needles, Anesthetic Drugs, and Conduction Techniques
 * Standards: Минздрав РФ, СтАР, ФАР, Malamed
 */

import {
	AnestheticDrugKey,
	AnestheticDrugSpec,
	ConductionTechniqueId,
	NeedleGaugeId,
	NeedleSpecification,
	TechniqueSpecification,
} from './anesthesiaTechniqueTypes';

// ---------------------------------------------------------------------------
// 1. Dental Needle Catalog
// ---------------------------------------------------------------------------

export const DENTAL_NEEDLE_CATALOG: Record<NeedleGaugeId, NeedleSpecification> = {
	gauge_27_long_35mm: {
		id: 'gauge_27_long_35mm',
		gauge: '27G',
		externalDiameterMm: 0.4,
		internalDiameterMm: 0.2,
		lengthMm: 35,
		colorCode: '#eab308', // Yellow
		capColorRu: 'Желтый',
		nameRu: '27G × 35 мм (Длинная, желтая)',
		primaryIndicationsRu:
			'Мандибулярная (Вайсбрем, Гоу-Гейтс, Акинози), торусальная проводниковая блокада. Надежный просвет для аспирации.',
		aspirationLumenSafety: 'high',
		deflectionResistancePercent: 92,
	},
	gauge_30_medium_25mm: {
		id: 'gauge_30_medium_25mm',
		gauge: '30G',
		externalDiameterMm: 0.3,
		internalDiameterMm: 0.15,
		lengthMm: 25,
		colorCode: '#3b82f6', // Blue
		capColorRu: 'Синий',
		nameRu: '30G × 25 мм (Средняя, синяя)',
		primaryIndicationsRu:
			'Инфильтрационная анестезия на верхней челюсти, ментальная блокада, неглубокая туберальная анестезия.',
		aspirationLumenSafety: 'medium',
		deflectionResistancePercent: 65,
	},
	gauge_30_short_21mm: {
		id: 'gauge_30_short_21mm',
		gauge: '30G',
		externalDiameterMm: 0.3,
		internalDiameterMm: 0.15,
		lengthMm: 21,
		colorCode: '#06b6d4', // Cyan/Light Blue
		capColorRu: 'Голубой',
		nameRu: '30G × 21 мм (Короткая)',
		primaryIndicationsRu:
			'Стандартная инфильтрационная анестезия, папиллярная блокада, ментальная блокада у подростков.',
		aspirationLumenSafety: 'medium',
		deflectionResistancePercent: 78,
	},
	gauge_30_ultrashort_12mm: {
		id: 'gauge_30_ultrashort_12mm',
		gauge: '30G',
		externalDiameterMm: 0.3,
		internalDiameterMm: 0.15,
		lengthMm: 12,
		colorCode: '#22c55e', // Green
		capColorRu: 'Зеленый',
		nameRu: '30G × 12 мм (Ультракороткая, зеленая)',
		primaryIndicationsRu:
			'Небная (большое небное отверстие), резцовая (резцовый сосочек), интралигаментарная анестезия (PDL).',
		aspirationLumenSafety: 'medium',
		deflectionResistancePercent: 95,
	},
	gauge_30_extrashort_8mm: {
		id: 'gauge_30_extrashort_8mm',
		gauge: '30G',
		externalDiameterMm: 0.3,
		internalDiameterMm: 0.15,
		lengthMm: 8,
		colorCode: '#a855f7', // Purple
		capColorRu: 'Фиолетовый',
		nameRu: '30G × 8 мм (Экстракороткая STA, фиолетовая)',
		primaryIndicationsRu:
			'Компьютерная STA интралигаментарная и интрасептальная анестезия под контролем давления.',
		aspirationLumenSafety: 'restricted_lumen',
		deflectionResistancePercent: 98,
	},
};

// ---------------------------------------------------------------------------
// 2. Anesthetic Drugs Catalog
// ---------------------------------------------------------------------------

export const ANESTHETIC_DRUGS_CATALOG: Record<AnestheticDrugKey, AnestheticDrugSpec> = {
	articaine_1_100k: {
		drugId: 'articaine_1_100k',
		tradeNamesRu: ['Ультракаин Д-С форте', 'Септонест 1:100 000', 'Убистезин форте', 'Брилокаин форте'],
		activeSubstanceRu: 'Артикаина гидрохлорид 4% + Эпинефрин 1:100 000',
		activeConcentrationPercent: 4.0,
		mgPerMlActive: 40.0,
		vasoconstrictorRatio: '1:100000',
		vasoconstrictorNameRu: 'Эпинефрин 1:100 000',
		epinephrineMgPerMl: 0.01,
		standardCarpuleVolumeMl: 1.7,
		maxDoseMgPerKgAdult: 7.0,
		absoluteMaxDoseMgAdult: 500.0,
		isAdrenalineFree: false,
		containsSulfites: true,
	},
	articaine_1_200k: {
		drugId: 'articaine_1_200k',
		tradeNamesRu: ['Ультракаин Д-С', 'Убистезин', 'Септонест 1:200 000', 'Артифрин'],
		activeSubstanceRu: 'Артикаина гидрохлорид 4% + Эпинефрин 1:200 000',
		activeConcentrationPercent: 4.0,
		mgPerMlActive: 40.0,
		vasoconstrictorRatio: '1:200000',
		vasoconstrictorNameRu: 'Эпинефрин 1:200 000',
		epinephrineMgPerMl: 0.005,
		standardCarpuleVolumeMl: 1.7,
		maxDoseMgPerKgAdult: 7.0,
		absoluteMaxDoseMgAdult: 500.0,
		isAdrenalineFree: false,
		containsSulfites: true,
	},
	mepivacaine_plain_3: {
		drugId: 'mepivacaine_plain_3',
		tradeNamesRu: ['Скандонест 3%', 'Мепивастезин 3%', 'Мепивакаин-Бинергия 3%'],
		activeSubstanceRu: 'Мепивакаина гидрохлорид 3% (без вазоконстриктора)',
		activeConcentrationPercent: 3.0,
		mgPerMlActive: 30.0,
		vasoconstrictorRatio: 'none',
		vasoconstrictorNameRu: 'Без вазоконстриктора',
		epinephrineMgPerMl: 0.0,
		standardCarpuleVolumeMl: 1.7,
		maxDoseMgPerKgAdult: 4.4,
		absoluteMaxDoseMgAdult: 300.0,
		isAdrenalineFree: true,
		containsSulfites: false,
	},
	lidocaine_2_100k: {
		drugId: 'lidocaine_2_100k',
		tradeNamesRu: ['Ксилонор 2%', 'Лидокаин-Адреналин', 'Лидокаин 2% карпульный'],
		activeSubstanceRu: 'Лидокаина гидрохлорид 2% + Эпинефрин 1:100 000',
		activeConcentrationPercent: 2.0,
		mgPerMlActive: 20.0,
		vasoconstrictorRatio: '1:100000',
		vasoconstrictorNameRu: 'Эпинефрин 1:100 000',
		epinephrineMgPerMl: 0.01,
		standardCarpuleVolumeMl: 1.8,
		maxDoseMgPerKgAdult: 4.4,
		absoluteMaxDoseMgAdult: 300.0,
		isAdrenalineFree: false,
		containsSulfites: true,
	},
	bupivacaine_05: {
		drugId: 'bupivacaine_05',
		tradeNamesRu: ['Маркаин 0.5%', 'Бупивакаин Гриндекс'],
		activeSubstanceRu: 'Бупивакаина гидрохлорид 0.5% + Эпинефрин 1:200 000',
		activeConcentrationPercent: 0.5,
		mgPerMlActive: 5.0,
		vasoconstrictorRatio: '1:200000',
		vasoconstrictorNameRu: 'Эпинефрин 1:200 000',
		epinephrineMgPerMl: 0.005,
		standardCarpuleVolumeMl: 1.8,
		maxDoseMgPerKgAdult: 2.0,
		absoluteMaxDoseMgAdult: 90.0,
		isAdrenalineFree: false,
		containsSulfites: true,
	},
};

// ---------------------------------------------------------------------------
// 3. Conduction & Infiltration Techniques Catalog
// ---------------------------------------------------------------------------

export const CONDUCTION_TECHNIQUES_CATALOG: Record<ConductionTechniqueId, TechniqueSpecification> = {
	mandibular_weisbrem: {
		id: 'mandibular_weisbrem',
		nameRu: 'Мандибулярная проводниковая по Вайсбрему (Торусальная)',
		shortNameRu: 'Мандибулярная (Вайсбрем)',
		category: 'conduction_mandibular',
		anatomicalLandmarksRu:
			'Нижнечелюстной валик (torus mandibulae), борозда позади коронки 8-го нижнего зуба, крыловидно-челюстная складка.',
		puncturePointRu:
			'В бороздку нижнечелюстного валика на 0.5 см ниже жевательной поверхности верхних моляров при широко открытом рте.',
		targetNervesRu: [
			'Нижний альвеолярный нерв (n. alveolaris inferior)',
			'Язычный нерв (n. lingualis)',
			'Щечный нерв (n. buccalis)',
		],
		recommendedNeedle: 'gauge_27_long_35mm',
		allowedNeedles: ['gauge_27_long_35mm', 'gauge_30_medium_25mm'],
		insertionDepthMm: { min: 15, max: 20, target: 18 },
		requiresBoneContact: true,
		typicalVolumeCarpules: 1.0,
		typicalVolumeMl: 1.7,
		minVolumeMl: 1.5,
		maxVolumeMl: 2.0,
		targetPressureAtm: { min: 1.0, max: 2.0, isHighPressure: false },
		baseVascularHitRiskPercent: 12.5,
		vascularRiskTier: 'critical_high',
		onsetMinutes: { min: 10, max: 15, defaultWaitTimeSec: 600 },
		pulpalDurationMinutes: { min: 60, max: 90 },
		softTissueDurationMinutes: { min: 180, max: 300 },
		anatomicZones: {
			teethDescRu: 'Все зубы нижней челюсти соответствующей стороны (1-8)',
			targetQuadrantRu: 'Нижний квадрант (зубы 41–48 или 31–38)',
			tongueNumbness: true,
			lowerLipNumbness: true,
			cheekMucosaNumbness: true,
			hardPalateNumbness: false,
			softTissueCollateral: true,
			sensoryNervesRu: ['n. alveolaris inferior', 'n. lingualis', 'n. buccalis'],
			summaryRu: 'Блокада половины нижней челюсти: зубы 1-8, 2/3 языка, половина нижней губы, щечная десна моляров.',
		},
		aspirationPlanesRequired: 2,
		clinicalRecommendationsRu:
			'Обязательна аспирационная проба в 2-х плоскостях (0° и 180°). Скорость введения не более 1 мл/мин. Дождаться контакта с костью перед введением.',
		contraindicationsOrCautionsRu: [
			'Ограничение открывания рта (тризм III степени)',
			'Гнойно-воспалительный процесс в крыловидно-челюстном пространстве',
		],
	},

	mandibular_gow_gates: {
		id: 'mandibular_gow_gates',
		nameRu: 'Мандибулярная блокада по Гоу-Гейтсу (Высокая блокада V3)',
		shortNameRu: 'По Гоу-Гейтсу (Gow-Gates)',
		category: 'conduction_mandibular',
		anatomicalLandmarksRu:
			'Шейка мыщелкового отростка нижней челюсти, мезио-язычный бугор второго верхнего моляра, межкозелковая вырезка уха.',
		puncturePointRu:
			'Слизистая оболочка латеральнее крыловидно-челюстной складки на уровне мезио-язычного бугра второго моляра верхней челюсти.',
		targetNervesRu: [
			'Нижний альвеолярный нерв',
			'Язычный нерв',
			'Щечный нерв',
			'Ушно-височный нерв (n. auriculotemporalis)',
			'Челюстно-подъязычный нерв (n. mylohyoideus)',
		],
		recommendedNeedle: 'gauge_27_long_35mm',
		allowedNeedles: ['gauge_27_long_35mm'],
		insertionDepthMm: { min: 23, max: 27, target: 25 },
		requiresBoneContact: true,
		typicalVolumeCarpules: 1.0,
		typicalVolumeMl: 1.7,
		minVolumeMl: 1.7,
		maxVolumeMl: 2.0,
		targetPressureAtm: { min: 1.0, max: 2.0, isHighPressure: false },
		baseVascularHitRiskPercent: 2.0,
		vascularRiskTier: 'moderate',
		onsetMinutes: { min: 10, max: 15, defaultWaitTimeSec: 600 },
		pulpalDurationMinutes: { min: 75, max: 100 },
		softTissueDurationMinutes: { min: 240, max: 360 },
		anatomicZones: {
			teethDescRu: 'Все зубы нижней челюсти квадранта (1-8), ветвь и тело нижней челюсти',
			targetQuadrantRu: 'Нижний квадрант с височной и околоушной областью',
			tongueNumbness: true,
			lowerLipNumbness: true,
			cheekMucosaNumbness: true,
			hardPalateNumbness: false,
			softTissueCollateral: true,
			sensoryNervesRu: ['n. alveolaris inferior', 'n. lingualis', 'n. buccalis', 'n. auriculotemporalis'],
			summaryRu:
				'Тотальная блокада нижнечелюстного нерва: все зубы квадранта, язык, губа, щека, кожа височной и ушной зоны.',
		},
		aspirationPlanesRequired: 2,
		clinicalRecommendationsRu:
			'Пациент держит рот широко открытым 1-2 минуты после инъекции для депонирования раствора вокруг шейки мыщелка.',
		contraindicationsOrCautionsRu: [
			'Пациенты с нестабильностью ВНЧС и вывихами',
			'Ограничение открывания рта',
		],
	},

	mandibular_akinosi: {
		id: 'mandibular_akinosi',
		nameRu: 'Мандибулярная блокада по Акинози-Вазирани (При закрытом рте)',
		shortNameRu: 'По Акинози (Akinosi)',
		category: 'conduction_mandibular',
		anatomicalLandmarksRu:
			'Слизисто-десневая граница верхних моляров, медиальная поверхность ветви нижней челюсти при сомкнутых челюстях.',
		puncturePointRu:
			'Мягкие ткани медиальнее ветви челюсти на уровне переходной складки верхних моляров при сомкнутых зубах.',
		targetNervesRu: ['Нижний альвеолярный нерв', 'Язычный нерв', 'Челюстно-подъязычный нерв'],
		recommendedNeedle: 'gauge_27_long_35mm',
		allowedNeedles: ['gauge_27_long_35mm'],
		insertionDepthMm: { min: 22, max: 26, target: 25 },
		requiresBoneContact: false,
		typicalVolumeCarpules: 1.0,
		typicalVolumeMl: 1.7,
		minVolumeMl: 1.5,
		maxVolumeMl: 1.8,
		targetPressureAtm: { min: 1.0, max: 2.0, isHighPressure: false },
		baseVascularHitRiskPercent: 10.0,
		vascularRiskTier: 'critical_high',
		onsetMinutes: { min: 10, max: 15, defaultWaitTimeSec: 600 },
		pulpalDurationMinutes: { min: 60, max: 90 },
		softTissueDurationMinutes: { min: 180, max: 280 },
		anatomicZones: {
			teethDescRu: 'Зубы половины нижней челюсти 1-8',
			targetQuadrantRu: 'Нижний квадрант',
			tongueNumbness: true,
			lowerLipNumbness: true,
			cheekMucosaNumbness: false,
			hardPalateNumbness: false,
			softTissueCollateral: true,
			sensoryNervesRu: ['n. alveolaris inferior', 'n. lingualis', 'n. mylohyoideus'],
			summaryRu:
				'Блокада для сложных пациентов с тризмом и контрактурой челюстей: зубы квадранта, 2/3 языка, нижняя губа.',
		},
		aspirationPlanesRequired: 2,
		clinicalRecommendationsRu:
			'Метод выбора при невозможности открыть рот (тризм при перикороните, флегмоне, травме). Без контакта с костью.',
		contraindicationsOrCautionsRu: [
			'Инфекционный инфильтрат в крыловидно-нижнечелюстном пространстве',
		],
	},

	torusal: {
		id: 'torusal',
		nameRu: 'Торусальная проводниковая анестезия (Классический нижнечелюстной валик)',
		shortNameRu: 'Торусальная',
		category: 'conduction_mandibular',
		anatomicalLandmarksRu:
			'Нижнечелюстной валик (torus mandibulae) на внутренней поверхности ветви, ретромолярная ямка.',
		puncturePointRu: 'В угол между крыловидно-челюстной складкой и слизистой щеки в проекции валика.',
		targetNervesRu: ['Нижний альвеолярный', 'Язычный', 'Щечный нервы'],
		recommendedNeedle: 'gauge_27_long_35mm',
		allowedNeedles: ['gauge_27_long_35mm', 'gauge_30_medium_25mm'],
		insertionDepthMm: { min: 15, max: 20, target: 18 },
		requiresBoneContact: true,
		typicalVolumeCarpules: 1.0,
		typicalVolumeMl: 1.7,
		minVolumeMl: 1.5,
		maxVolumeMl: 2.0,
		targetPressureAtm: { min: 1.0, max: 2.0, isHighPressure: false },
		baseVascularHitRiskPercent: 11.5,
		vascularRiskTier: 'critical_high',
		onsetMinutes: { min: 10, max: 15, defaultWaitTimeSec: 600 },
		pulpalDurationMinutes: { min: 60, max: 90 },
		softTissueDurationMinutes: { min: 180, max: 300 },
		anatomicZones: {
			teethDescRu: 'Все зубы нижней челюсти соответствующей стороны',
			targetQuadrantRu: 'Нижний квадрант',
			tongueNumbness: true,
			lowerLipNumbness: true,
			cheekMucosaNumbness: true,
			hardPalateNumbness: false,
			softTissueCollateral: true,
			sensoryNervesRu: ['n. alveolaris inferior', 'n. lingualis', 'n. buccalis'],
			summaryRu: 'Одновременная блокада 3-х нервов: зубы, передние 2/3 языка, нижняя губа, щека.',
		},
		aspirationPlanesRequired: 2,
		clinicalRecommendationsRu:
			'Обязательна аспирация в двух плоскостях. При положительной пробе немедленно сменить карпулу.',
		contraindicationsOrCautionsRu: ['Анатомическое отсутствие выраженного валика (до 5% пациентов)'],
	},

	tuberal: {
		id: 'tuberal',
		nameRu: 'Туберальная анестезия (Tuber maxillae / Блокада задних верхних альвеолярных нервов)',
		shortNameRu: 'Туберальная',
		category: 'conduction_maxillary',
		anatomicalLandmarksRu:
			'Бугор верхней челюсти (tuber maxillae), скулоальвеолярный гребень, переходная складка за 2-м моляром.',
		puncturePointRu: 'Переходная складка над вторым верхним моляром с направлением иглы кзади, кверху и внутрь.',
		targetNervesRu: ['Задние верхние альвеолярные ветви (rr. alveolares superiores posteriores)'],
		recommendedNeedle: 'gauge_30_medium_25mm',
		allowedNeedles: ['gauge_30_medium_25mm', 'gauge_27_long_35mm', 'gauge_30_short_21mm'],
		insertionDepthMm: { min: 15, max: 20, target: 18 },
		requiresBoneContact: true,
		typicalVolumeCarpules: 1.0,
		typicalVolumeMl: 1.7,
		minVolumeMl: 1.0,
		maxVolumeMl: 1.7,
		targetPressureAtm: { min: 1.0, max: 2.0, isHighPressure: false },
		baseVascularHitRiskPercent: 18.0,
		vascularRiskTier: 'critical_high',
		onsetMinutes: { min: 3, max: 5, defaultWaitTimeSec: 240 },
		pulpalDurationMinutes: { min: 60, max: 80 },
		softTissueDurationMinutes: { min: 120, max: 180 },
		anatomicZones: {
			teethDescRu: 'Моляры верхней челюсти (18, 17, 16 кроме мезио-щечного корня в 28% случаев)',
			targetQuadrantRu: 'Верхнечелюстные моляры',
			tongueNumbness: false,
			lowerLipNumbness: false,
			cheekMucosaNumbness: true,
			hardPalateNumbness: false,
			softTissueCollateral: false,
			sensoryNervesRu: ['rr. alveolares superiores posteriores'],
			summaryRu:
				'Онемение верхних моляров (18, 17, 16), вестибулярной надкостницы и слизистой, задней стенки гайморовой пазухи.',
		},
		aspirationPlanesRequired: 2,
		clinicalRecommendationsRu:
			'КРИТИЧЕСКИЙ РИСК ГЕМАТОМЫ! Крыловидное венозное сплетение (plexus venosus pterygoideus) и a. maxillaris. Двухплоскостная аспирация СТРОГО ОБЯЗАТЕЛЬНА.',
		contraindicationsOrCautionsRu: [
			'Пациенты на антикоагулянтах / дезагрегантах с высоким риском кровотечения',
			'Коагулопатии (гемофилия, тромбоцитопения)',
		],
	},

	incisive_canal: {
		id: 'incisive_canal',
		nameRu: 'Резцовая анестезия в резцовый сосочек (Носонебная / Foramen incisivum)',
		shortNameRu: 'Резцовая (Носонебная)',
		category: 'conduction_palatal',
		anatomicalLandmarksRu: 'Резцовый сосочек (papilla incisiva) по средней линии неба позади резцов 11 и 21.',
		puncturePointRu: 'Сбоку от резцового сосочка с предварительной аппликационной анестезией.',
		targetNervesRu: ['Носонебный нерв (n. nasopalatinus / n. incisivus)'],
		recommendedNeedle: 'gauge_30_ultrashort_12mm',
		allowedNeedles: ['gauge_30_ultrashort_12mm', 'gauge_30_short_21mm'],
		insertionDepthMm: { min: 3, max: 6, target: 5 },
		requiresBoneContact: true,
		typicalVolumeCarpules: 0.2,
		typicalVolumeMl: 0.3,
		minVolumeMl: 0.2,
		maxVolumeMl: 0.5,
		targetPressureAtm: { min: 3.0, max: 6.0, isHighPressure: false },
		baseVascularHitRiskPercent: 0.5,
		vascularRiskTier: 'minimal',
		onsetMinutes: { min: 2, max: 3, defaultWaitTimeSec: 120 },
		pulpalDurationMinutes: { min: 30, max: 50 },
		softTissueDurationMinutes: { min: 60, max: 120 },
		anatomicZones: {
			teethDescRu: 'Небная десна и надкостница в области резцов и клыков (13–23)',
			targetQuadrantRu: 'Фронтальный отдел твердого неба',
			tongueNumbness: false,
			lowerLipNumbness: false,
			cheekMucosaNumbness: false,
			hardPalateNumbness: true,
			softTissueCollateral: false,
			sensoryNervesRu: ['n. nasopalatinus'],
			summaryRu: 'Слизистая и надкостница твердого неба от клыка до клыка (зубы 13, 12, 11, 21, 22, 23).',
		},
		aspirationPlanesRequired: 1,
		clinicalRecommendationsRu:
			'Плотная надкостница. Вводить микродозами (0.2–0.3 мл), очень медленно под постоянным контролем побледнения ишемической зоны.',
		contraindicationsOrCautionsRu: ['Воспаление резцового сосочка (папиллит)'],
	},

	greater_palatine: {
		id: 'greater_palatine',
		nameRu: 'Небная анестезия (Большое небное отверстие / Foramen palatinum majus)',
		shortNameRu: 'Небная',
		category: 'conduction_palatal',
		anatomicalLandmarksRu:
			'Большое небное отверстие на уровне дистального края 2-го моляра верхней челюсти, 1 см медиальнее десны.',
		puncturePointRu: 'Слизистая неба в проекции небного отверстия до контакта с костной каймой.',
		targetNervesRu: ['Большой небный нерв (n. palatinus major)'],
		recommendedNeedle: 'gauge_30_ultrashort_12mm',
		allowedNeedles: ['gauge_30_ultrashort_12mm', 'gauge_30_short_21mm'],
		insertionDepthMm: { min: 4, max: 8, target: 5 },
		requiresBoneContact: true,
		typicalVolumeCarpules: 0.3,
		typicalVolumeMl: 0.5,
		minVolumeMl: 0.2,
		maxVolumeMl: 0.6,
		targetPressureAtm: { min: 3.0, max: 5.0, isHighPressure: false },
		baseVascularHitRiskPercent: 0.8,
		vascularRiskTier: 'minimal',
		onsetMinutes: { min: 2, max: 3, defaultWaitTimeSec: 120 },
		pulpalDurationMinutes: { min: 40, max: 60 },
		softTissueDurationMinutes: { min: 90, max: 150 },
		anatomicZones: {
			teethDescRu: 'Слизистая твердого неба от моляров до первого премоляра соответствующей стороны',
			targetQuadrantRu: 'Дистальный отдел твердого неба',
			tongueNumbness: false,
			lowerLipNumbness: false,
			cheekMucosaNumbness: false,
			hardPalateNumbness: true,
			softTissueCollateral: false,
			sensoryNervesRu: ['n. palatinus major'],
			summaryRu: 'Небная слизистая и надкостница в области премоляров и моляров (зубы 14-18 или 24-28).',
		},
		aspirationPlanesRequired: 1,
		clinicalRecommendationsRu:
			'Не вводить более 0.5 мл во избежание некроза слизистой от компрессии вазоконстриктором.',
		contraindicationsOrCautionsRu: ['Некроз слизистой при быстром введении высоких доз'],
	},

	infiltration_supraperiosteal: {
		id: 'infiltration_supraperiosteal',
		nameRu: 'Инфильтрационная наднадкостничная анестезия (Supraperiosteal)',
		shortNameRu: 'Инфильтрационная',
		category: 'infiltration',
		anatomicalLandmarksRu:
			'Переходная складка преддверия рта в проекции верхушки корня причинного зуба, угол скоса 45° к надкостнице.',
		puncturePointRu: 'В подвижную слизистую переходной складки на 2-3 мм выше верхушки корня зуба.',
		targetNervesRu: ['Терминальные ветви зубного нервного сплетения (plexus dentalis superior/inferior)'],
		recommendedNeedle: 'gauge_30_medium_25mm',
		allowedNeedles: ['gauge_30_medium_25mm', 'gauge_30_short_21mm', 'gauge_30_ultrashort_12mm'],
		insertionDepthMm: { min: 3, max: 8, target: 5 },
		requiresBoneContact: true,
		typicalVolumeCarpules: 1.0,
		typicalVolumeMl: 1.7,
		minVolumeMl: 0.8,
		maxVolumeMl: 1.8,
		targetPressureAtm: { min: 1.0, max: 2.0, isHighPressure: false },
		baseVascularHitRiskPercent: 1.5,
		vascularRiskTier: 'low',
		onsetMinutes: { min: 3, max: 5, defaultWaitTimeSec: 180 },
		pulpalDurationMinutes: { min: 45, max: 60 },
		softTissueDurationMinutes: { min: 120, max: 180 },
		anatomicZones: {
			teethDescRu: '1-2 причинных зуба в зоне инфильтрации',
			targetQuadrantRu: 'Сегмент 1–2 зубов',
			tongueNumbness: false,
			lowerLipNumbness: false,
			cheekMucosaNumbness: true,
			hardPalateNumbness: false,
			softTissueCollateral: false,
			sensoryNervesRu: ['rr. dentales', 'rr. gingivales'],
			summaryRu: 'Локальное онемение причинного зуба, периодонта, вестибулярной надкостницы и десны.',
		},
		aspirationPlanesRequired: 1,
		clinicalRecommendationsRu:
			'Основной метод для верхней челюсти и фронтального отдела нижней челюсти. Введение со скоростью 1 мл/мин.',
		contraindicationsOrCautionsRu: [
			'Инфильтрат или абсцесс в месте инъекции (вводить только в здоровую ткань)',
		],
	},

	intraligamentary_pdl: {
		id: 'intraligamentary_pdl',
		nameRu: 'Интралигаментарная периодонтальная анестезия (PDL / Гидравлическое давление 10–15 атм)',
		shortNameRu: 'Интралигаментарная (PDL)',
		category: 'intraligamentary_pressure',
		anatomicalLandmarksRu: 'Периодонтальная щель причинного зуба, угол 30° к продольной оси корня.',
		puncturePointRu:
			'В десневую бороздку на глубину 1–2 мм с упором скоса иглы в корень зуба под давлением 10–15 атм.',
		targetNervesRu: ['Периодонтальные и пульпарные терминальные рецепторы изолированного зуба'],
		recommendedNeedle: 'gauge_30_ultrashort_12mm',
		allowedNeedles: ['gauge_30_ultrashort_12mm', 'gauge_30_extrashort_8mm'],
		insertionDepthMm: { min: 1, max: 3, target: 2 },
		requiresBoneContact: true,
		typicalVolumeCarpules: 0.2,
		typicalVolumeMl: 0.3,
		minVolumeMl: 0.2,
		maxVolumeMl: 0.6,
		targetPressureAtm: { min: 10.0, max: 15.0, isHighPressure: true },
		baseVascularHitRiskPercent: 0.3,
		vascularRiskTier: 'minimal',
		onsetMinutes: { min: 0.5, max: 1.0, defaultWaitTimeSec: 60 },
		pulpalDurationMinutes: { min: 30, max: 45 },
		softTissueDurationMinutes: { min: 30, max: 60 },
		anatomicZones: {
			teethDescRu: 'Строго 1 причинный зуб (пульпа + периодонт)',
			targetQuadrantRu: '1 изолированный зуб',
			tongueNumbness: false,
			lowerLipNumbness: false,
			cheekMucosaNumbness: false,
			hardPalateNumbness: false,
			softTissueCollateral: false,
			sensoryNervesRu: ['n. periodontalis terminalis'],
			summaryRu:
				'Изолированная анестезия 1 зуба. НЕТ онемения губы, щеки и языка! Пациент сохраняет четкую дикцию.',
		},
		aspirationPlanesRequired: 1,
		clinicalRecommendationsRu:
			'Требует высокого гидравлического давления (10–15 атм). Идеально для детей, пожилых, пациентов с риском прикусывания губы.',
		contraindicationsOrCautionsRu: [
			'Острый пародонтит или пародонтальный карман > 5 мм с гноетечением',
			'Риск бактериемии у пациентов с эндокардитом',
		],
	},

	intraosseous_quicksleeper: {
		id: 'intraosseous_quicksleeper',
		nameRu: 'Внутрикостная анестезия (Quicksleeper / Перфорация кортикальной пластинки)',
		shortNameRu: 'Внутрикостная (Quicksleeper)',
		category: 'intraosseous',
		anatomicalLandmarksRu:
			'Межзубная костная перегородка на 2 мм апикальнее вершины межзубного сосочка между корнями.',
		puncturePointRu:
			'Через прикрепленную десну перпендикулярно кортикальной пластинке с ротационной микроперфорацией кости.',
		targetNervesRu: ['Внутрикостное нервное сплетение губчатого вещества'],
		recommendedNeedle: 'gauge_30_short_21mm',
		allowedNeedles: ['gauge_30_short_21mm', 'gauge_30_medium_25mm', 'gauge_27_long_35mm'],
		insertionDepthMm: { min: 5, max: 10, target: 8 },
		requiresBoneContact: true,
		typicalVolumeCarpules: 0.5,
		typicalVolumeMl: 0.9,
		minVolumeMl: 0.5,
		maxVolumeMl: 1.2,
		targetPressureAtm: { min: 2.0, max: 4.0, isHighPressure: false },
		baseVascularHitRiskPercent: 4.0,
		vascularRiskTier: 'moderate',
		onsetMinutes: { min: 0.5, max: 1.0, defaultWaitTimeSec: 60 },
		pulpalDurationMinutes: { min: 45, max: 70 },
		softTissueDurationMinutes: { min: 45, max: 90 },
		anatomicZones: {
			teethDescRu: '1–3 зуба в зоне костной перфузии',
			targetQuadrantRu: 'Костный сегмент альвеолярного отростка',
			tongueNumbness: false,
			lowerLipNumbness: false,
			cheekMucosaNumbness: false,
			hardPalateNumbness: false,
			softTissueCollateral: false,
			sensoryNervesRu: ['plexus intraosseus'],
			summaryRu:
				'Мгновенная анестезия зубов сегмента в губчатой кости. Отсутствие пареза мимических мышц и мягких тканей.',
		},
		aspirationPlanesRequired: 1,
		clinicalRecommendationsRu:
			'Высокая васкуляризация губчатой кости. Вводить плавно. При выраженной тахикардии использовать препараты 1:200 000.',
		contraindicationsOrCautionsRu: ['Тонкая кортикальная пластинка, близость корней соседних зубов'],
	},

	mental_incisive: {
		id: 'mental_incisive',
		nameRu: 'Ментальная / Подбородочная блокада (Foramen mentale)',
		shortNameRu: 'Ментальная',
		category: 'conduction_mandibular',
		anatomicalLandmarksRu:
			'Подбородочное отверстие (foramen mentale) между корнями 1-го и 2-го премоляров нижней челюсти.',
		puncturePointRu: 'Переходная складка между корнями премоляров с направлением иглы кзади и книзу.',
		targetNervesRu: ['Подбородочный нерв (n. mentalis)', 'Резцовая ветвь (n. incisivus)'],
		recommendedNeedle: 'gauge_30_medium_25mm',
		allowedNeedles: ['gauge_30_medium_25mm', 'gauge_30_short_21mm'],
		insertionDepthMm: { min: 5, max: 10, target: 8 },
		requiresBoneContact: true,
		typicalVolumeCarpules: 0.6,
		typicalVolumeMl: 1.0,
		minVolumeMl: 0.6,
		maxVolumeMl: 1.2,
		targetPressureAtm: { min: 1.0, max: 2.0, isHighPressure: false },
		baseVascularHitRiskPercent: 3.5,
		vascularRiskTier: 'moderate',
		onsetMinutes: { min: 3, max: 5, defaultWaitTimeSec: 240 },
		pulpalDurationMinutes: { min: 45, max: 60 },
		softTissueDurationMinutes: { min: 120, max: 180 },
		anatomicZones: {
			teethDescRu: 'Премоляры, клык и резцы нижней челюсти (зубы 45–41 или 35–31)',
			targetQuadrantRu: 'Передний квадрант нижней челюсти',
			tongueNumbness: false,
			lowerLipNumbness: true,
			cheekMucosaNumbness: true,
			hardPalateNumbness: false,
			softTissueCollateral: true,
			sensoryNervesRu: ['n. mentalis', 'n. incisivus'],
			summaryRu: 'Онемение нижней губы, подбородка, вестибулярной десны и зубов от премоляров до центрального резца.',
		},
		aspirationPlanesRequired: 1,
		clinicalRecommendationsRu:
			'После введения провести пальцевое прижатие на 1 минуту для направления раствора в резцовый канал.',
		contraindicationsOrCautionsRu: ['Воспаление в проекции верхушек премоляров'],
	},

	infraorbital: {
		id: 'infraorbital',
		nameRu: 'Инфраорбитальная / Подглазничная анестезия (Foramen infraorbitale)',
		shortNameRu: 'Инфраорбитальная',
		category: 'conduction_maxillary',
		anatomicalLandmarksRu:
			'Подглазничный край, подглазничное отверстие на 5–8 мм ниже края глазницы по среднезрачковой линии.',
		puncturePointRu: 'Переходная складка между центральным и боковым резцом с направлением иглы к подглазничному каналу.',
		targetNervesRu: [
			'Передние и средние верхние альвеолярные нервы (rr. alveolares superiores anteriores et medii)',
			'Малая гусиная лапка (pes anserinus minor)',
		],
		recommendedNeedle: 'gauge_27_long_35mm',
		allowedNeedles: ['gauge_27_long_35mm', 'gauge_30_medium_25mm'],
		insertionDepthMm: { min: 15, max: 20, target: 18 },
		requiresBoneContact: true,
		typicalVolumeCarpules: 0.8,
		typicalVolumeMl: 1.2,
		minVolumeMl: 0.8,
		maxVolumeMl: 1.5,
		targetPressureAtm: { min: 1.0, max: 2.0, isHighPressure: false },
		baseVascularHitRiskPercent: 4.5,
		vascularRiskTier: 'moderate',
		onsetMinutes: { min: 3, max: 5, defaultWaitTimeSec: 240 },
		pulpalDurationMinutes: { min: 50, max: 70 },
		softTissueDurationMinutes: { min: 120, max: 200 },
		anatomicZones: {
			teethDescRu: 'Резцы, клык и премоляры верхней челюсти (11–15 или 21–25)',
			targetQuadrantRu: 'Передний и средний отдел верхней челюсти',
			tongueNumbness: false,
			lowerLipNumbness: false,
			cheekMucosaNumbness: true,
			hardPalateNumbness: false,
			softTissueCollateral: true,
			sensoryNervesRu: ['n. infraorbitalis', 'pes anserinus minor'],
			summaryRu:
				'Онемение зубов 11-15, передней стенки гайморовой пазухи, верхней губы, крыла носа и нижнего века.',
		},
		aspirationPlanesRequired: 2,
		clinicalRecommendationsRu:
			'Фиксировать палец на подглазничном крае во избежание провала иглы в глазницу. Аспирация обязательна.',
		contraindicationsOrCautionsRu: ['Гнойные процессы подглазничной области'],
	},
};
