import type { DocumentTemplateVariableSpec } from "./types.js";

/**
 * Токены домена doctor и персонала (активный врач, последний врач, администраторы, текущий пользователь).
 * Layer 1: Domain Variable Token Group.
 */
export const DOCTOR_DOCUMENT_TEMPLATE_VARIABLES: readonly DocumentTemplateVariableSpec[] = [
	// Врачи и персонал
	{
		token: "ПоследнийПриём.Врач.ФИО",
		domain: "doctor",
		name: "ФИО врача последнего приема",
		description: "ФИО врача, проводившего предыдущий прием",
		exampleValue: "Васильев Иван Петрович",
		resolverPath: "lastDoctor.fullName",
	},
	{
		token: "ПоследнийПриём.Врач.ФамилияИнициалы",
		domain: "doctor",
		name: "Фамилия и инициалы врача последнего приема",
		description: "Фамилия и инициалы лечащего врача",
		exampleValue: "Васильев И. П.",
		resolverPath: "lastDoctor.initials",
	},
	{
		token: "ПоследнийПриём.Врач.Должность",
		domain: "doctor",
		name: "Должность врача последнего приема",
		description: "Штатная медицинская должность врача",
		exampleValue: "Врач-стоматолог терапевт",
		resolverPath: "lastDoctor.position",
	},
	{
		token: "ПоследнийПриём.Врач.Специальность",
		domain: "doctor",
		name: "Специальность врача последнего приема",
		description: "Врачебная специальность",
		exampleValue: "Стоматология терапевтическая",
		resolverPath: "lastDoctor.specialty",
	},
	{
		token: "Администратор.ФИО",
		domain: "administrator",
		name: "ФИО администратора",
		description: "ФИО администратора клиники, оформившего документ",
		exampleValue: "Васильев Иван Петрович",
		resolverPath: "administrator.fullName",
	},
	{
		token: "Администратор.ФамилияИнициалы",
		domain: "administrator",
		name: "Фамилия и инициалы администратора",
		description: "Фамилия и инициалы администратора",
		exampleValue: "Васильев И. П.",
		resolverPath: "administrator.initials",
	},
	{
		token: "Администратор.Должность",
		domain: "administrator",
		name: "Должность администратора",
		description: "Штатная должность сотрудника регистратуры",
		exampleValue: "Администратор",
		resolverPath: "administrator.position",
	},
	{
		token: "Администратор.Специальность",
		domain: "administrator",
		name: "Специальность администратора",
		description: "Специальность сотрудника",
		exampleValue: "Администратор клиники",
		resolverPath: "administrator.specialty",
	},
	{
		token: "АктивныйВрач.ФИО",
		domain: "doctor",
		name: "ФИО активного врача",
		description: "ФИО врача текущего приема / подписывающего врача",
		exampleValue: "Васильев Иван Петрович",
		resolverPath: "doctor.fullName",
	},
	{
		token: "АктивныйВрач.ФамилияИнициалы",
		domain: "doctor",
		name: "Фамилия и инициалы активного врача",
		description: "Фамилия и инициалы врача текущего приема",
		exampleValue: "Васильев И. П.",
		resolverPath: "doctor.initials",
	},
	{
		token: "АктивныйВрач.Должность",
		domain: "doctor",
		name: "Должность активного врача",
		description: "Должность врача текущего приема",
		exampleValue: "Врач-стоматолог терапевт",
		resolverPath: "doctor.position",
	},
	{
		token: "АктивныйВрач.Специальность",
		domain: "doctor",
		name: "Специальность активного врача",
		description: "Клиническая специальность врача",
		exampleValue: "Стоматология общей практики",
		resolverPath: "doctor.specialty",
	},


	{
		token: "ТекущийПользователь.Должность",
		domain: "administrator",
		name: "Должность текущего пользователя",
		description: "Штатная должность сотрудника, печатающего документ",
		exampleValue: "Администратор",
		resolverPath: "currentUser.position",
	},
	{
		token: "ТекущийПользователь.ФАМИЛИЯИмяОтчество",
		domain: "administrator",
		name: "ФАМИЛИЯ Имя Отчество текущего пользователя",
		description: "ФИО сотрудника с фамилией заглавными буквами",
		exampleValue: "МАРТЮКОВА Галина Александровна",
		resolverPath: "currentUser.lastNameUpperFullName",
	},
	{
		token: "ТекущийПользователь.ФамилияИмяОтчество",
		domain: "administrator",
		name: "Фамилия Имя Отчество текущего пользователя",
		description: "Полное имя сотрудника, печатающего документ",
		exampleValue: "Мартюкова Галина Александровна",
		resolverPath: "currentUser.fullName",
	},
	{
		token: "ТекущийПользователь.ФамилияИО",
		domain: "administrator",
		name: "Фамилия и инициалы текущего пользователя",
		description: "Фамилия и инициалы сотрудника (Мартюкова Г. А.)",
		exampleValue: "Мартюкова Г. А.",
		resolverPath: "currentUser.initials",
	},
	{
		token: "ТекущийПользователь.Фамилия",
		domain: "administrator",
		name: "Фамилия текущего пользователя",
		description: "Фамилия сотрудника клиники",
		exampleValue: "Мартюкова",
		resolverPath: "currentUser.lastName",
	},
	{
		token: "ТекущийПользователь.Имя",
		domain: "administrator",
		name: "Имя текущего пользователя",
		description: "Имя сотрудника клиники",
		exampleValue: "Галина",
		resolverPath: "currentUser.firstName",
	},
	{
		token: "ТекущийПользователь.Отчество",
		domain: "administrator",
		name: "Отчество текущего пользователя",
		description: "Отчество сотрудника клиники",
		exampleValue: "Александровна",
		resolverPath: "currentUser.middleName",
	},

] as const;
