import type { DocumentTemplateVariableSpec } from "./types.js";

/**
 * Токены домена patient: ФИО, паспорт, СНИЛС, полис ОМС/ДМС, контакты, адрес,
 * плоские теги IDENT/DentalPRO и соматический статус.
 * Layer 1: Domain Variable Token Group.
 */
export const PATIENT_DOCUMENT_TEMPLATE_VARIABLES: readonly DocumentTemplateVariableSpec[] = [
	// Пациент
	{
		token: "Пациент.ФИО",
		domain: "patient",
		name: "ФИО пациента",
		description: "Фамилия Имя Отчество пациента полностью",
		exampleValue: "Иванов Петр Алексеевич",
		resolverPath: "patient.fullName",
	},
	{
		token: "Пациент.ID",
		domain: "patient",
		name: "ID пациента",
		description: "Уникальный идентификатор пациента в базе данных",
		exampleValue: "101",
		resolverPath: "patient.id",
	},
	{
		token: "Пациент.НомерКарты",
		domain: "patient",
		name: "Номер амбулаторной карты",
		description: "Номер медицинской карты стоматологического больного (Карта приёма)",
		exampleValue: "333",
		resolverPath: "patient.cardNumber",
	},
	{
		token: "Пациент.Фамилия",
		domain: "patient",
		name: "Фамилия пациента",
		description: "Фамилия пациента",
		exampleValue: "Иванов",
		resolverPath: "patient.lastName",
	},
	{
		token: "Пациент.Имя",
		domain: "patient",
		name: "Имя пациента",
		description: "Имя пациента",
		exampleValue: "Петр",
		resolverPath: "patient.firstName",
	},
	{
		token: "Пациент.Отчество",
		domain: "patient",
		name: "Отчество пациента",
		description: "Отчество пациента",
		exampleValue: "Алексеевич",
		resolverPath: "patient.middleName",
	},
	{
		token: "Пациент.Пол",
		domain: "patient",
		name: "Пол пациента",
		description: "Пол пациента (муж / жен)",
		exampleValue: "муж",
		resolverPath: "patient.gender",
	},
	{
		token: "Пациент.Адрес",
		domain: "patient",
		name: "Адрес регистрации пациента",
		description: "Адрес регистрации по паспорту",
		exampleValue: "ул. Ленина, д. 33, кв. 115",
		resolverPath: "patient.address",
	},
	{
		token: "Пациент.Телефон",
		domain: "patient",
		name: "Телефон пациента",
		description: "Основной контактный телефон пациента",
		exampleValue: "+7 911 090 5544",
		resolverPath: "patient.phone",
	},
	{
		token: "Пациент.ИНН",
		domain: "patient",
		name: "ИНН пациента",
		description: "Идентификационный номер налогоплательщика",
		exampleValue: "123456789012",
		resolverPath: "patient.inn",
	},
	{
		token: "Пациент.ФамилияИО",
		domain: "patient",
		name: "Фамилия и инициалы пациента",
		description: "Фамилия и сокращенные инициалы (Иванов П.А.)",
		exampleValue: "Иванов П.А.",
		resolverPath: "patient.initials",
	},
	{
		token: "Пациент.ДеньРождения",
		domain: "patient",
		name: "Дата рождения пациента",
		description: "Дата рождения пациента в формате ДД.ММ.ГГГГ",
		exampleValue: "20.12.1985",
		resolverPath: "patient.birthDate",
	},
	{
		token: "Пациент.Возраст",
		domain: "patient",
		name: "Возраст пациента",
		description: "Полных лет с русским склонением",
		exampleValue: "30 лет",
		resolverPath: "patient.age",
	},
	{
		token: "Пациент.ФактическийАдрес",
		domain: "patient",
		name: "Фактический адрес пациента",
		description: "Адрес фактического проживания",
		exampleValue: "ул. Ленина, д. 33, кв. 115",
		resolverPath: "patient.actualAddress",
	},
	{
		token: "Пациент.Email",
		domain: "patient",
		name: "Электронная почта пациента",
		description: "Email адрес пациента",
		exampleValue: "email@email.ru",
		resolverPath: "patient.email",
	},
	{
		token: "Пациент.СНИЛС",
		domain: "patient",
		name: "СНИЛС пациента",
		description: "Страховой номер индивидуального лицевого счета",
		exampleValue: "123-456-789-01",
		resolverPath: "patient.snils",
	},
	{
		token: "Пациент.Инвалидность",
		domain: "patient",
		name: "Инвалидность пациента",
		description: "Группа инвалидности или отметка об отсутствии",
		exampleValue: "нет",
		resolverPath: "patient.disability",
	},
	{
		token: "Пациент.Льготы",
		domain: "patient",
		name: "Льготы пациента",
		description: "Категория льгот пациента",
		exampleValue: "нет",
		resolverPath: "patient.benefits",
	},
	{
		token: "Пациент.Профессия",
		domain: "patient",
		name: "Профессия пациента",
		description: "Род деятельности или профессия",
		exampleValue: "водитель",
		resolverPath: "patient.profession",
	},
	{
		token: "Пациент.ОсобыеОтметки",
		domain: "patient",
		name: "Особые клинические отметки",
		description: "Аллергологический анамнез, соматические патологии",
		exampleValue: "Аллергия на пенициллин",
		resolverPath: "patient.specialNotes",
	},
	{
		token: "Пациент.Полисы",
		domain: "patient",
		name: "Все полисы пациента",
		description: "Сводные данные полисов ОМС и ДМС",
		exampleValue: "ОМС 123-456-789-01",
		resolverPath: "patient.policies",
	},
	{
		token: "Пациент.ПолисОМС",
		domain: "patient",
		name: "Полис ОМС",
		description: "Номер полиса обязательного медицинского страхования",
		exampleValue: "123-456-789-01",
		resolverPath: "patient.omsPolicy",
	},
	{
		token: "Пациент.ПолисДМС",
		domain: "patient",
		name: "Полис ДМС",
		description: "Номер полиса добровольного медицинского страхования",
		exampleValue: "123-456-789-01",
		resolverPath: "patient.dmsPolicy",
	},
	{
		token: "Пациент.Аванс",
		domain: "patient",
		name: "Аванс / Баланс пациента",
		description: "Текущий финансовый баланс пациента в рублях",
		exampleValue: "25 000",
		resolverPath: "patient.advance",
	},
	{
		token: "Пациент.Паспорт.Номер",
		domain: "patient",
		name: "Паспорт: номер",
		description: "Номер паспорта пациента",
		exampleValue: "123456",
		resolverPath: "patient.passport.number",
	},
	{
		token: "Пациент.Паспорт.СерияНомер",
		domain: "patient",
		name: "Паспорт: серия и номер",
		description: "Серия и номер паспорта пациента через пробел",
		exampleValue: "4510 123456",
		resolverPath: "patient.passport.seriesNumber",
	},
	{
		token: "Пациент.Паспорт.Серия",
		domain: "patient",
		name: "Серия паспорта пациента",
		description: "4 цифры серии паспорта",
		exampleValue: "4321",
		resolverPath: "patient.passport.series",
	},
	{
		token: "Пациент.Паспорт.ДатаВыдачи",
		domain: "patient",
		name: "Дата выдачи паспорта пациента",
		description: "Дата выдачи паспорта (ДД.ММ.ГГГГ)",
		exampleValue: "20.01.2001",
		resolverPath: "patient.passport.issuedDate",
	},
	{
		token: "Пациент.Паспорт.КемВыдан",
		domain: "patient",
		name: "Кем выдан паспорт пациента",
		description: "Орган, выдавший документ, удостоверяющий личность",
		exampleValue: "Отдел УФМС России по г. Москве №133",
		resolverPath: "patient.passport.issuedBy",
	},
	{
		token: "Пациент.Паспорт.КодПодразделения",
		domain: "patient",
		name: "Код подразделения паспорта пациента",
		description: "Код подразделения (XXX-XXX)",
		exampleValue: "123-456",
		resolverPath: "patient.passport.divisionCode",
	},


	// ─── ИДЕНТ (IDENT) & DENTALPRO СОВМЕСТИМОСТЬ: ПЛОСКИЕ ТЕГИ ПАЦИЕНТА ───
	{
		token: "ФАМИЛИЯИмяОтчество",
		domain: "patient",
		name: "ФАМИЛИЯ Имя Отчество пациента",
		description: "ФИО пациента с фамилией заглавными буквами (ИВАНОВ Петр Алексеевич)",
		exampleValue: "ИВАНОВ Петр Алексеевич",
		resolverPath: "patient.lastNameUpperFullName",
	},
	{
		token: "ФамилияИмяОтчество",
		domain: "patient",
		name: "Фамилия Имя Отчество пациента",
		description: "ФИО пациента полностью в формате Фамилия Имя Отчество",
		exampleValue: "Иванов Петр Алексеевич",
		resolverPath: "patient.fullName",
	},
	{
		token: "ФамилияИО",
		domain: "patient",
		name: "Фамилия и инициалы пациента",
		description: "Фамилия и сокращенные инициалы (Иванов П. А.)",
		exampleValue: "Иванов П. А.",
		resolverPath: "patient.initials",
	},
	{
		token: "Фамилия",
		domain: "patient",
		name: "Фамилия пациента",
		description: "Фамилия пациента",
		exampleValue: "Иванов",
		resolverPath: "patient.lastName",
	},
	{
		token: "Имя",
		domain: "patient",
		name: "Имя пациента",
		description: "Имя пациента",
		exampleValue: "Петр",
		resolverPath: "patient.firstName",
	},
	{
		token: "Отчество",
		domain: "patient",
		name: "Отчество пациента",
		description: "Отчество пациента",
		exampleValue: "Алексеевич",
		resolverPath: "patient.middleName",
	},
	{
		token: "ДатаРождения",
		domain: "patient",
		name: "Дата рождения пациента",
		description: "Дата рождения пациента прописью (20 декабря 1985)",
		exampleValue: "20 декабря 1985",
		resolverPath: "patient.birthDateFull",
	},
	{
		token: "ГодРождения",
		domain: "patient",
		name: "Год рождения пациента",
		description: "Год рождения пациента (ГГГГ)",
		exampleValue: "1985",
		resolverPath: "patient.birthYear",
	},
	{
		token: "Возраст",
		domain: "patient",
		name: "Возраст пациента",
		description: "Возраст пациента полных лет",
		exampleValue: "30 лет",
		resolverPath: "patient.age",
	},
	{
		token: "Пол",
		domain: "patient",
		name: "Пол пациента",
		description: "Пол пациента (мужской / женский)",
		exampleValue: "мужской",
		resolverPath: "patient.gender",
	},
	{
		token: "Телефоны",
		domain: "patient",
		name: "Телефоны пациента",
		description: "Контактные телефоны пациента (мобильный и домашний)",
		exampleValue: "+7 (911) 090-55-44; (812) 123-45-67",
		resolverPath: "patient.phones",
	},
	{
		token: "МобТелефон",
		domain: "patient",
		name: "Мобильный телефон пациента",
		description: "Основной мобильный телефон пациента",
		exampleValue: "+7 (911) 090-55-44",
		resolverPath: "patient.mobilePhone",
	},
	{
		token: "ДомТелефон",
		domain: "patient",
		name: "Домашний телефон пациента",
		description: "Стационарный или домашний телефон пациента",
		exampleValue: "(812) 123-45-67",
		resolverPath: "patient.homePhone",
	},
	{
		token: "Email",
		domain: "patient",
		name: "Email пациента",
		description: "Адрес электронной почты пациента",
		exampleValue: "patient@example.ru",
		resolverPath: "patient.email",
	},
	{
		token: "Адрес",
		domain: "patient",
		name: "Адрес проживания пациента",
		description: "Фактический адрес проживания пациента",
		exampleValue: "г. Москва, ул. Ленина, д. 33, кв. 115",
		resolverPath: "patient.address",
	},
	{
		token: "АдресРегистрации",
		domain: "patient",
		name: "Адрес регистрации пациента",
		description: "Адрес постоянной регистрации по паспорту",
		exampleValue: "г. Москва, ул. Ленина, д. 33, кв. 115",
		resolverPath: "patient.registrationAddress",
	},
	{
		token: "ДатаРегистрации",
		domain: "patient",
		name: "Дата регистрации пациента",
		description: "Дата регистрации по месту жительства (ДД.ММ.ГГГГ)",
		exampleValue: "05.04.1994",
		resolverPath: "patient.registrationDate",
	},
	{
		token: "ИНН",
		domain: "patient",
		name: "ИНН пациента",
		description: "Идентификационный номер налогоплательщика",
		exampleValue: "123456789012",
		resolverPath: "patient.inn",
	},
	{
		token: "СНИЛС",
		domain: "patient",
		name: "СНИЛС пациента",
		description: "Страховой номер индивидуального лицевого счета",
		exampleValue: "123-456-789 01",
		resolverPath: "patient.snils",
	},
	{
		token: "ИИН",
		domain: "patient",
		name: "ИИН пациента (Казахстан)",
		description: "Индивидуальный идентификационный номер",
		exampleValue: "760724300757",
		resolverPath: "patient.iin",
	},
	{
		token: "МестоРаботы",
		domain: "patient",
		name: "Место работы пациента",
		description: "Организация или предприятие — место работы",
		exampleValue: "ООО СтомХ",
		resolverPath: "patient.workplace",
	},
	{
		token: "Профессия",
		domain: "patient",
		name: "Профессия пациента",
		description: "Профессия или род занятий",
		exampleValue: "Инженер",
		resolverPath: "patient.profession",
	},
	{
		token: "Полисы",
		domain: "patient",
		name: "Все полисы пациента",
		description: "Сводные данные полисов ОМС и ДМС",
		exampleValue: "ОМС 123-456-789-01",
		resolverPath: "patient.policies",
	},
	{
		token: "Комментарий",
		domain: "patient",
		name: "Клинический комментарий",
		description: "Комментарий к карточке пациента (аллергии, соматика)",
		exampleValue: "Аллергик",
		resolverPath: "patient.comment",
	},
	{
		token: "НомерКарты",
		domain: "patient",
		name: "Номер амбулаторной карты",
		description: "Номер карты пациента",
		exampleValue: "123",
		resolverPath: "patient.cardNumber",
	},
	{
		token: "НомерМедкарты",
		domain: "patient",
		name: "Номер медицинской карты",
		description: "Номер медицинской карты пациента",
		exampleValue: "123",
		resolverPath: "patient.cardNumber",
	},
	{
		token: "ДатаПервогоПриема",
		domain: "patient",
		name: "Дата первого приема прописью",
		description: "Дата первого визита в формате: число месяц год г.",
		exampleValue: "22 мар 2022 г.",
		resolverPath: "patient.firstVisitDate",
	},
	{
		token: "ДатаПервогоПриемаЧислом",
		domain: "patient",
		name: "Дата первого приема числом",
		description: "Дата первого приема в формате ДД.ММ.ГГГГ",
		exampleValue: "22.03.2022",
		resolverPath: "patient.firstVisitDateShort",
	},
	{
		token: "Родитель",
		domain: "patient",
		name: "Данные родителя",
		description: "ФИО родителя из карточки ребенка",
		exampleValue: "Иванов Алексей Иванович",
		resolverPath: "patient.parentName",
	},
	{
		token: "МестоРождения",
		domain: "patient",
		name: "Место рождения пациента",
		description: "Город / населенный пункт места рождения по паспорту",
		exampleValue: "г. Москва",
		resolverPath: "patient.birthPlace",
	},
	{
		token: "Документ",
		domain: "patient",
		name: "Документ удостоверяющий личность",
		description: "Полная сводная строка паспортных данных пациента",
		exampleValue: "Паспорт РФ: 4010 №232567, Выдан: 10.09.2010, ТП № 42, Код подразделения: 600-004",
		resolverPath: "patient.passportFull",
	},
	{
		token: "Документ.ТипДокумента",
		domain: "patient",
		name: "Тип документа пациента",
		description: "Наименование документа (Паспорт РФ, Свидетельство о рождении)",
		exampleValue: "Паспорт РФ",
		resolverPath: "patient.passport.type",
	},
	{
		token: "Документ.СерияНомер",
		domain: "patient",
		name: "Серия и номер документа",
		description: "Серия и номер паспорта через пробел",
		exampleValue: "4010 232567",
		resolverPath: "patient.passport.seriesNumber",
	},
	{
		token: "Документ.СерияНомер.Серия",
		domain: "patient",
		name: "Серия документа",
		description: "Серия паспорта пациента",
		exampleValue: "4010",
		resolverPath: "patient.passport.series",
	},
	{
		token: "Документ.СерияНомер.Номер",
		domain: "patient",
		name: "Номер документа",
		description: "Номер паспорта пациента",
		exampleValue: "232567",
		resolverPath: "patient.passport.number",
	},
	{
		token: "Документ.Выдан",
		domain: "patient",
		name: "Сведения о выдаче документа",
		description: "Строка выдачи паспорта (дата, кем выдан, код)",
		exampleValue: "Выдан: 10.09.2010, ТП № 42, Код подразделения: 420-017",
		resolverPath: "patient.passport.issuedFull",
	},
	{
		token: "Документ.Выдан.ДатаВыдачи",
		domain: "patient",
		name: "Дата выдачи документа",
		description: "Дата выдачи паспорта (ДД.ММ.ГГГГ)",
		exampleValue: "10.09.2010",
		resolverPath: "patient.passport.issuedDate",
	},
	{
		token: "Документ.Выдан.КодПодразделения",
		domain: "patient",
		name: "Код подразделения",
		description: "Код подразделения органа выдачи (XXX-XXX)",
		exampleValue: "420-017",
		resolverPath: "patient.passport.divisionCode",
	},
	{
		token: "Документ.Выдан.КемВыдан",
		domain: "patient",
		name: "Орган выдачи документа",
		description: "Наименование органа, выдавшего паспорт",
		exampleValue: "ТП № 42 ОУФМС",
		resolverPath: "patient.passport.issuedBy",
	},


	// ─── СОМАТИЧЕСКИЙ И АЛЛЕРГОЛОГИЧЕСКИЙ СТАТУС ───
	{
		token: "Пациент.СоматическийСтатус",
		domain: "patient",
		name: "Соматический статус пациента",
		description: "Общий соматический статус (соматически здоров / сопутствующие патологии)",
		exampleValue: "Соматически здоров, хронических заболеваний не выявлено",
		resolverPath: "patient.somaticStatus",
	},
	{
		token: "СоматическийСтатус",
		domain: "patient",
		name: "Соматический статус",
		description: "Соматический статус пациента (алиас)",
		exampleValue: "Соматически здоров, сопутствующих патологий нет",
		resolverPath: "patient.somaticStatus",
	},
	{
		token: "Аллергостатус",
		domain: "patient",
		name: "Аллергологический статус",
		description: "Аллергологический анамнез пациента",
		exampleValue: "Аллергологический анамнез не отягощен",
		resolverPath: "patient.allergyStatus",
	},
	{
		token: "Аллергии",
		domain: "patient",
		name: "Аллергии пациента",
		description: "Перечень выявленных аллергических реакций",
		exampleValue: "Аллергии не выявлены",
		resolverPath: "patient.allergyStatus",
	},
	{
		token: "НепереносимостьПрепаратов",
		domain: "patient",
		name: "Непереносимость лекарственных препаратов",
		description: "Сведения о лекарственной непереносимости",
		exampleValue: "Непереносимость местных анестетиков и антибиотиков отрицает",
		resolverPath: "patient.drugIntolerance",
	},

] as const;
