import type { DocumentTemplateVariableSpec } from "./types.js";

/**
 * Токены законных представителей и полномочных лиц (включая алиасы IDENT).
 * Layer 1: Domain Variable Token Group.
 */
export const REPRESENTATIVE_DOCUMENT_TEMPLATE_VARIABLES: readonly DocumentTemplateVariableSpec[] = [
	// Представитель
	{
		token: "Представитель.ФИО",
		domain: "representative",
		name: "ФИО законного представителя",
		description: "ФИО родителя, опекуна или попечителя полностью",
		exampleValue: "Петров Алексей Иванович",
		resolverPath: "representative.fullName",
	},
	{
		token: "Представитель.ФамилияИнициалы",
		domain: "representative",
		name: "Фамилия и инициалы представителя",
		description: "Фамилия и инициалы представителя",
		exampleValue: "Петров А. И.",
		resolverPath: "representative.initials",
	},
	{
		token: "Представитель.Телефон",
		domain: "representative",
		name: "Телефон представителя",
		description: "Контактный телефон законного представителя",
		exampleValue: "+7 933 090 5544",
		resolverPath: "representative.phone",
	},
	{
		token: "Представитель.Паспорт.Номер",
		domain: "representative",
		name: "Номер паспорта представителя",
		description: "Номер паспорта законного представителя",
		exampleValue: "123456",
		resolverPath: "representative.passport.number",
	},
	{
		token: "Представитель.Паспорт.Серия",
		domain: "representative",
		name: "Серия паспорта представителя",
		description: "Серия паспорта законного представителя",
		exampleValue: "4321",
		resolverPath: "representative.passport.series",
	},
	{
		token: "Представитель.Паспорт.ДатаВыдачи",
		domain: "representative",
		name: "Дата выдачи паспорта представителя",
		description: "Дата выдачи паспорта представителя (ДД.ММ.ГГГГ)",
		exampleValue: "20.01.2001",
		resolverPath: "representative.passport.issuedDate",
	},
	{
		token: "Представитель.Паспорт.КемВыдан",
		domain: "representative",
		name: "Кем выдан паспорт представителя",
		description: "Орган, выдавший паспорт законному представителю",
		exampleValue: "Отдел УФМС России по г. Москве №133",
		resolverPath: "representative.passport.issuedBy",
	},
	{
		token: "Представитель.Паспорт.КодПодразделения",
		domain: "representative",
		name: "Код подразделения представителя",
		description: "Код подразделения органа выдачи паспорта",
		exampleValue: "123-456",
		resolverPath: "representative.passport.divisionCode",
	},
	{
		token: "Представитель.ДеньРождения",
		domain: "representative",
		name: "Дата рождения представителя",
		description: "Дата рождения представителя (ДД.ММ.ГГГГ)",
		exampleValue: "20.12.1985",
		resolverPath: "representative.birthDate",
	},
	{
		token: "Представитель.Адрес",
		domain: "representative",
		name: "Адрес представителя",
		description: "Адрес места жительства законного представителя",
		exampleValue: "ул. Ленина, д. 33, кв. 115",
		resolverPath: "representative.address",
	},
	{
		token: "Представитель.СНИЛС",
		domain: "representative",
		name: "СНИЛС представителя",
		description: "СНИЛС законного представителя",
		exampleValue: "123-456-789-01",
		resolverPath: "representative.snils",
	},
	{
		token: "Представитель.НаОсновании",
		domain: "representative",
		name: "Основание полномочий представителя",
		description: "Документ-основание (Паспорт, Свидетельство о рождении)",
		exampleValue: "Паспорт",
		resolverPath: "representative.basis",
	},
	{
		token: "Представитель.Тип",
		domain: "representative",
		name: "Тип родства законного представителя",
		description: "родитель, опекун, Муж, Жена, Отец, Мать, Дочь, Сын, Сестра, Брат",
		exampleValue: "Отец",
		resolverPath: "representative.relationType",
	},
	{
		token: "Представитель.Основание",
		domain: "representative",
		name: "Основание представителя (алиас)",
		description: "Документ-основание (Паспорт, Свидетельство о рождении)",
		exampleValue: "Паспорт",
		resolverPath: "representative.basis",
	},
	{
		token: "Представитель.Родство",
		domain: "representative",
		name: "Родство представителя (алиас)",
		description: "Отец, Мать, Опекун и т.д.",
		exampleValue: "Мать",
		resolverPath: "representative.relationType",
	},


	// Полномочный
	{
		token: "Полномочный.ФИО",
		domain: "authorizedPerson",
		name: "ФИО уполномоченного лица",
		description: "ФИО лица по доверенности",
		exampleValue: "Петров Алексей Иванович",
		resolverPath: "authorizedPerson.fullName",
	},
	{
		token: "Полномочный.ФамилияИнициалы",
		domain: "authorizedPerson",
		name: "Фамилия и инициалы уполномоченного",
		description: "Фамилия и инициалы поверенного",
		exampleValue: "Петров А.И.",
		resolverPath: "authorizedPerson.initials",
	},
	{
		token: "Полномочный.Телефон",
		domain: "authorizedPerson",
		name: "Телефон уполномоченного лица",
		description: "Телефон поверенного по доверенности",
		exampleValue: "+7 933 090 5544",
		resolverPath: "authorizedPerson.phone",
	},
	{
		token: "Полномочный.Паспорт.Номер",
		domain: "authorizedPerson",
		name: "Номер паспорта уполномоченного",
		description: "Номер паспорта доверенного лица",
		exampleValue: "123456",
		resolverPath: "authorizedPerson.passport.number",
	},
	{
		token: "Полномочный.Паспорт.Серия",
		domain: "authorizedPerson",
		name: "Серия паспорта уполномоченного",
		description: "Серия паспорта доверенного лица",
		exampleValue: "4321",
		resolverPath: "authorizedPerson.passport.series",
	},
	{
		token: "Полномочный.Паспорт.ДатаВыдачи",
		domain: "authorizedPerson",
		name: "Дата выдачи паспорта уполномоченного",
		description: "Дата выдачи паспорта (ДД.ММ.ГГГГ)",
		exampleValue: "20.01.2001",
		resolverPath: "authorizedPerson.passport.issuedDate",
	},
	{
		token: "Полномочный.Паспорт.КемВыдан",
		domain: "authorizedPerson",
		name: "Кем выдан паспорт уполномоченного",
		description: "Орган, выдавший паспорт доверенному лицу",
		exampleValue: "Отдел УФМС России по г. Москве №133",
		resolverPath: "authorizedPerson.passport.issuedBy",
	},
	{
		token: "Полномочный.Паспорт.КодПодразделения",
		domain: "authorizedPerson",
		name: "Код подразделения уполномоченного",
		description: "Код подразделения паспорта доверенного лица",
		exampleValue: "123-456",
		resolverPath: "authorizedPerson.passport.divisionCode",
	},
	{
		token: "Полномочный.ДеньРождения",
		domain: "authorizedPerson",
		name: "Дата рождения уполномоченного",
		description: "Дата рождения доверенного лица (ДД.ММ.ГГГГ)",
		exampleValue: "20.12.1985",
		resolverPath: "authorizedPerson.birthDate",
	},
	{
		token: "Полномочный.Адрес",
		domain: "authorizedPerson",
		name: "Адрес уполномоченного лица",
		description: "Адрес регистрации доверенного лица",
		exampleValue: "ул. Ленина, д. 33, кв. 115",
		resolverPath: "authorizedPerson.address",
	},
	{
		token: "Полномочный.СНИЛС",
		domain: "authorizedPerson",
		name: "СНИЛС уполномоченного лица",
		description: "СНИЛС доверенного лица",
		exampleValue: "123-456-789-01",
		resolverPath: "authorizedPerson.snils",
	},


	// ─── ПРЕДСТАВИТЕЛЬ (ИДЕНТ АЛИАСЫ) ───
	{
		token: "Представитель.ФАМИЛИЯИмяОтчество",
		domain: "representative",
		name: "ФАМИЛИЯ Имя Отчество представителя",
		description: "ФИО законного представителя с фамилией заглавными буквами",
		exampleValue: "ПЕТРОВ Алексей Иванович",
		resolverPath: "representative.lastNameUpperFullName",
	},
	{
		token: "Представитель.ФамилияИмяОтчество",
		domain: "representative",
		name: "Фамилия Имя Отчество представителя",
		description: "ФИО законного представителя полностью",
		exampleValue: "Петров Алексей Иванович",
		resolverPath: "representative.fullName",
	},
	{
		token: "Представитель.ФамилияИО",
		domain: "representative",
		name: "Фамилия и инициалы представителя",
		description: "Фамилия и инициалы представителя (Петров А. И.)",
		exampleValue: "Петров А. И.",
		resolverPath: "representative.initials",
	},
	{
		token: "Представитель.Фамилия",
		domain: "representative",
		name: "Фамилия представителя",
		description: "Фамилия представителя",
		exampleValue: "Петров",
		resolverPath: "representative.lastName",
	},
	{
		token: "Представитель.Имя",
		domain: "representative",
		name: "Имя представителя",
		description: "Имя представителя",
		exampleValue: "Алексей",
		resolverPath: "representative.firstName",
	},
	{
		token: "Представитель.Отчество",
		domain: "representative",
		name: "Отчество представителя",
		description: "Отчество представителя",
		exampleValue: "Иванович",
		resolverPath: "representative.middleName",
	},
	{
		token: "Представитель.ДатаРождения",
		domain: "representative",
		name: "Дата рождения представителя",
		description: "Дата рождения законного представителя",
		exampleValue: "28 января 1960",
		resolverPath: "representative.birthDate",
	},
	{
		token: "Представитель.ГодРождения",
		domain: "representative",
		name: "Год рождения представителя",
		description: "Год рождения представителя (ГГГГ)",
		exampleValue: "1960",
		resolverPath: "representative.birthYear",
	},
	{
		token: "Представитель.Возраст",
		domain: "representative",
		name: "Возраст представителя",
		description: "Возраст представителя в годах",
		exampleValue: "62 года",
		resolverPath: "representative.age",
	},
	{
		token: "Представитель.Пол",
		domain: "representative",
		name: "Пол представителя",
		description: "Пол представителя (мужской / женский)",
		exampleValue: "мужской",
		resolverPath: "representative.gender",
	},
	{
		token: "Представитель.Телефоны",
		domain: "representative",
		name: "Телефоны представителя",
		description: "Контактные телефоны представителя",
		exampleValue: "+7 (973) 014-24-76",
		resolverPath: "representative.phones",
	},
	{
		token: "Представитель.МобТелефон",
		domain: "representative",
		name: "Мобильный телефон представителя",
		description: "Мобильный телефон представителя",
		exampleValue: "+7 (973) 014-24-76",
		resolverPath: "representative.phone",
	},
	{
		token: "Представитель.ДомТелефон",
		domain: "representative",
		name: "Домашний телефон представителя",
		description: "Домашний телефон представителя",
		exampleValue: "(812) 529-89-55",
		resolverPath: "representative.homePhone",
	},
	{
		token: "Представитель.Email",
		domain: "representative",
		name: "Email представителя",
		description: "Адрес электронной почты представителя",
		exampleValue: "representative@ident.ru",
		resolverPath: "representative.email",
	},
	{
		token: "Представитель.АдресРегистрации",
		domain: "representative",
		name: "Адрес регистрации представителя",
		description: "Адрес постоянной регистрации представителя",
		exampleValue: "г. Москва, ул. Арбат, д. 10, кв. 25",
		resolverPath: "representative.address",
	},
	{
		token: "Представитель.ДатаРегистрации",
		domain: "representative",
		name: "Дата регистрации представителя",
		description: "Дата регистрации представителя (ДД.ММ.ГГГГ)",
		exampleValue: "05.05.1995",
		resolverPath: "representative.registrationDate",
	},
	{
		token: "Представитель.ИНН",
		domain: "representative",
		name: "ИНН представителя",
		description: "ИНН законного представителя",
		exampleValue: "780204893183",
		resolverPath: "representative.inn",
	},
	{
		token: "Представитель.ИИН",
		domain: "representative",
		name: "ИИН представителя (Казахстан)",
		description: "ИИН представителя",
		exampleValue: "760720302335",
		resolverPath: "representative.iin",
	},
	{
		token: "Представитель.МестоРождения",
		domain: "representative",
		name: "Место рождения представителя",
		description: "Место рождения представителя по паспорту",
		exampleValue: "г. Вологда",
		resolverPath: "representative.birthPlace",
	},
	{
		token: "Представитель.Документ",
		domain: "representative",
		name: "Документ представителя",
		description: "Полная строка реквизитов документа представителя",
		exampleValue: "Паспорт РФ: 4015 №235542, Выдан: 01.05.2001, ТП № 42, Код подразделения: 600-004",
		resolverPath: "representative.passportFull",
	},
	{
		token: "Представитель.Документ.ТипДокумента",
		domain: "representative",
		name: "Тип документа представителя",
		description: "Тип документа представителя",
		exampleValue: "Паспорт РФ",
		resolverPath: "representative.passport.type",
	},
	{
		token: "Представитель.Документ.СерияНомер",
		domain: "representative",
		name: "Серия и номер документа представителя",
		description: "Серия и номер документа представителя",
		exampleValue: "4010 232567",
		resolverPath: "representative.passport.seriesNumber",
	},
	{
		token: "Представитель.Документ.СерияНомер.Серия",
		domain: "representative",
		name: "Серия документа представителя",
		description: "Серия паспорта представителя",
		exampleValue: "4010",
		resolverPath: "representative.passport.series",
	},
	{
		token: "Представитель.Документ.СерияНомер.Номер",
		domain: "representative",
		name: "Номер документа представителя",
		description: "Номер паспорта представителя",
		exampleValue: "232567",
		resolverPath: "representative.passport.number",
	},
	{
		token: "Представитель.Документ.Выдан",
		domain: "representative",
		name: "Сведения о выдаче документа представителя",
		description: "Строка выдачи документа представителя",
		exampleValue: "Выдан: 10.09.2010, ТП № 42, Код подразделения: 420-017",
		resolverPath: "representative.passport.issuedFull",
	},
	{
		token: "Представитель.Документ.Выдан.ДатаВыдачи",
		domain: "representative",
		name: "Дата выдачи документа представителя",
		description: "Дата выдачи паспорта представителя",
		exampleValue: "10.09.2010",
		resolverPath: "representative.passport.issuedDate",
	},
	{
		token: "Представитель.Документ.Выдан.КодПодразделения",
		domain: "representative",
		name: "Код подразделения представителя",
		description: "Код подразделения паспорта представителя",
		exampleValue: "420-017",
		resolverPath: "representative.passport.divisionCode",
	},
	{
		token: "Представитель.Документ.Выдан.КемВыдан",
		domain: "representative",
		name: "Орган выдачи документа представителя",
		description: "Кем выдан паспорт представителя",
		exampleValue: "ТП № 42 ОУФМС",
		resolverPath: "representative.passport.issuedBy",
	},

] as const;
