import type { StaffRole, DentalSpecialty, ClinicMode } from "@dental/shared";
import type { Dispatch, SetStateAction } from "react";

export interface AppTopBarProps {
	dashboard: any;
	clinicName: string;
	todayIso: string;
	defaultClinicNoticeHidden: boolean;
	setDefaultClinicNoticeHidden: Dispatch<SetStateAction<boolean>>;
	reopenOnboarding: () => void;
	goToVisitDictation: () => void;
	setSelectedWorkspaceRole: (role: StaffRole) => void;
	selectedWorkspaceRole: StaffRole;
	roleFocusOrder: StaffRole[];
	showAdministrationTopActions: boolean;
	showDoctorVisitShortcut: boolean;
	staffRoleLabels: Record<StaffRole, string>;
	handleLockSession: () => void;
	openDoctorShiftCockpit: () => void;
	setIsCbctDirectModalOpen: (open: boolean) => void;
	activeCitoAlerts: any[];
	dismissCitoAlert: (alertId: string) => void;
	browserContinuityCritical: boolean;
	browserContinuity: any;
	isOnline: boolean;
	isPendingVisitSyncing: boolean;
	refreshBrowserContinuity: (opts: { silent: boolean }) => Promise<void>;
	flushPendingSpeechChunks: (opts: { silent: boolean }) => Promise<void>;
	flushPendingVisitSaves: (opts: { silent: boolean }) => Promise<void>;
	pendingSpeechChunkCount: number;
	pendingVisitSaveCount: number;
	networkState: any;
	pendingMutationCount: number;
	syncOfflineMutations: () => Promise<void>;
	isSyncingMutations: boolean;
	error: string | null;
	setError: Dispatch<SetStateAction<string | null>>;
	uiPreferencesSyncError: string | null;
	setUiPreferencesSyncError: Dispatch<SetStateAction<string | null>>;
	telegramHandoffNotice: any;
	setTelegramHandoffNotice: Dispatch<SetStateAction<any>>;
	onboardingDismissed: boolean;
	showFullOnboardingGuide: boolean;
	isLocalOnboardingDismissed: boolean;
	isStripDismissedLocally: boolean;
	setIsStripDismissedLocally: Dispatch<SetStateAction<boolean>>;
	currentView: string;
	currentOnboardingIndex: number;
	onboardingSteps: any[];
	legalReadinessPercent: number;
	continueOnboardingInDraftMode: (view?: string) => Promise<void> | void;
	openOnboardingGuide: () => void;
	dismissOnboarding: () => void;
	onboardingDraftMode: boolean;
	onboardingReadyToFinish: boolean;
	onboardingBlockingIssues: string[];
	onboardingDocumentsReady: boolean;
	onboardingDocumentReadinessIssues: string[];
	setCurrentView: (view: string) => void;
	setSettingsTab: (tab: string) => void;
	isDoctorShiftCockpitOpen: boolean;
	closeDoctorShiftCockpit: () => void;
	activeDoctor: any;
	onboardingRoleChoices: any[];
	moveOnboardingTo: (step: string | number) => Promise<void> | void;
	onboardingStep: any;
	onboardingFinishGuidanceId: string;
	specialtyLabels: Record<DentalSpecialty, string>;
	selectedSpecialty: DentalSpecialty;
	setSelectedSpecialty: (spec: DentalSpecialty) => void;
	clinicModeLabels: Record<ClinicMode, { title: string; detail: string }>;
	changeClinicMode: (mode: ClinicMode) => void;
	clinicProfileDraft: any;
	updateClinicProfileDraft: (patch: any) => void;
	uiLanguage: string;
	setUiLanguage: (lang: string) => void;
	normalizeUiLanguageInput: (input: string) => string;
	uiLanguageOptions: any[];
	selectedUiLanguageOption: any;
	weekdayOptions: any[];
	toggleClinicWorkingDay: (day: number) => void;
	legalMissingFields: string[];
	newStaffName: string;
	setNewStaffName: Dispatch<SetStateAction<string>>;
	newStaffRole: StaffRole;
	setNewStaffRole: Dispatch<SetStateAction<StaffRole>>;
	newStaffSpecialty: DentalSpecialty;
	setNewStaffSpecialty: Dispatch<SetStateAction<DentalSpecialty>>;
	addStaffMember: () => Promise<void>;
	newStaffReadyToCreate: boolean;
	onboardingStaffCreateGuidanceId: string;
	newChairName: string;
	setNewChairName: Dispatch<SetStateAction<string>>;
	addChair: () => Promise<void>;
	newChairReadyToCreate: boolean;
	onboardingChairCreateGuidanceId: string;
	staffScheduleDrafts: any;
	staffScheduleDraftFromWorkingHours: any;
	staffScheduleSaveStates: any;
	staffScheduleDirtyIds: any;
	staffScheduleSavingId: any;
	updateStaffScheduleDraft: any;
	toggleStaffWorkingDay: any;
	saveStaffSchedule: any;
	chairScheduleDrafts: any;
	chairScheduleSaveStates: any;
	chairScheduleDirtyIds: any;
	chairScheduleSavingId: any;
	updateChairScheduleDraft: any;
	toggleChairWorkingDay: any;
	saveChairSchedule: any;
	pricelistSourceKindLabels: any;
	pricelistSourceKind: any;
	setPricelistSourceKind: any;
	clearPricelistImage: any;
	setPricelistAnalysis: any;
	importSourceLabels: any;
	importSourceKind: any;
	setImportSourceKind: any;
	setImportPreview: any;
	setImportCommit: any;
	smartImportModeLabels: any;
	smartImportMode: any;
	setSmartImportMode: any;
	setSmartImportPreview: any;
	setSmartImportCommit: any;
	ingestionTargetLabels: any;
	documentIngestionTarget: any;
	setDocumentIngestionTarget: any;
	imagingSourceChoices: any;
	imagingImportSourceKind: any;
	imagingSourceLabels: any;
	setImagingImportSourceKind: any;
	setImagingImportPreview: any;
	setImagingImportCommit: any;
	setDicomSeriesPreview: any;
	dicomWebEndpointUrl: any;
	setDicomWebEndpointUrl: any;
	setDicomWebCheck: any;
	setDicomViewerLaunchManifest: any;
	setDicomViewerToolStateBundle: any;
	setDicomViewerWorkbenchManifest: any;
	ohifBaseUrl: any;
	setOhifBaseUrl: any;
	telegramStatus: any;
	telegramBotUsernameDraft: any;
	setTelegramBotUsernameDraft: any;
	markTelegramSettingsDirty: any;
	telegramPatientPortalBaseUrlDraft: any;
	setTelegramPatientPortalBaseUrlDraft: any;
	telegramWelcomeImageUrlDraft: any;
	setTelegramWelcomeImageUrlDraft: any;
	telegramReviewUrlDraft: any;
	setTelegramReviewUrlDraft: any;
	telegramMapsUrlDraft: any;
	setTelegramMapsUrlDraft: any;
	telegramTokenTtlDraft: any;
	setTelegramTokenTtlDraft: any;
	telegramReminderLeadTimesDraft: any;
	setTelegramReminderLeadTimesDraft: any;
	telegramReviewRequestDelayDraft: any;
	setTelegramReviewRequestDelayDraft: any;
	telegramPostVisitCheckupDelayFields: any;
	telegramPostVisitCheckupDelayDrafts: any;
	updateTelegramPostVisitCheckupDelayDraft: any;
	telegramAdminSecretDraft: any;
	setTelegramAdminSecretDraft: any;
	unlockTelegramAdminSession: any;
	telegramAdminSecretSession: any;
	telegramPrivacyModeDraft: any;
	setTelegramPrivacyModeDraft: any;
	normalizedTelegramPrivacyMode: any;
	telegramPrivacyModeLabels: any;
	telegramVisualCardFields: any;
	onboardingTelegramVisualCardKeys: any;
	telegramVisualCardUrlDrafts: any;
	updateTelegramVisualCardUrlDraft: any;
	telegramFeatureOptions: any;
	telegramEnabledFeaturesDraft: any;
	toggleTelegramFeature: any;
	telegramFeatureLabel: any;
	saveTelegramSettings: any;
	isTelegramSettingsSaving: boolean;
	telegramSettingsSaveState: any;
	telegramSettingsSaveError: any;
	telegramSettingsDirty: boolean;
	documentFactoryGroups: any;
	saveClinicProfileFromDraft: any;
	clinicProfileSaveState: any;
	onboardingTelegramRecommendations?: readonly string[] | any;
	previousOnboardingStep: any;
	nextOnboardingStep: any;
}

export interface AppSidebarProps {
	currentView: string;
	selectedWorkspaceRole: StaffRole;
	sidebarCollapsed: boolean;
	toggleSidebarCollapsed: () => void;
	handleLockSession: () => void;
	setCurrentView: (view: string) => void;
}

export interface AppViewRouterProps {
	currentView: string;
	dashboard: any;
	activeStaffUser: any;
	activeVisitPatient: any;
	activePatient: any;
	activePatientInsight: any;
	activeCommunicationTasks: any;
	activeImagingStudies: any;
	activeUsableDocuments: any;
	patientId: string | null;
	perspective?: string;
	clinicProfileDraft: any;
	appLogicValue: any;
	topBar?: React.ReactNode;
	toastPortal?: React.ReactNode;
}

export interface AppModalsContainerProps {
	isCbctTunerOpen: boolean;
	setIsCbctTunerOpen: Dispatch<SetStateAction<boolean>>;
	isCbctDirectModalOpen: boolean;
	setIsCbctDirectModalOpen: Dispatch<SetStateAction<boolean>>;
	isConsentDirectModalOpen: boolean;
	setIsConsentDirectModalOpen: Dispatch<SetStateAction<boolean>>;
	isCephDirectModalOpen: boolean;
	setIsCephDirectModalOpen: Dispatch<SetStateAction<boolean>>;
	isEgiszRemdModalOpen: boolean;
	setIsEgiszRemdModalOpen: Dispatch<SetStateAction<boolean>>;
	isSmartSlotRecoveryDemoOpen: boolean;
	setIsSmartSlotRecoveryDemoOpen: Dispatch<SetStateAction<boolean>>;
	isPrivacyShieldActive: boolean;
	setIsPrivacyShieldActive: Dispatch<SetStateAction<boolean>>;
	isSessionLocked?: boolean;
	setIsSessionLocked?: Dispatch<SetStateAction<boolean>>;
	activeStaffUser: any;
	setActiveStaffUser: Dispatch<SetStateAction<any>>;
	handleClinicLogout: () => void;
	handleFullStaffLock: () => void;
}

export interface AppToastPortalProps {
	setCurrentView: (view: string) => void;
	setQuery: (q: string) => void;
	setScheduleDateFilter: (date: string) => void;
}
