import type {
	StomxDocumentRegistryItem,
	StomxLegalConsentTemplateMetadata,
} from "./types.js";
import {
	STOMX_CONSENT_DEEP_CARIES,
	STOMX_CONSENT_FIXED_PROSTHETICS,
	STOMX_CONSENT_PERIODONTOLOGY,
	STOMX_CONSENT_PROFESSIONAL_HYGIENE,
	STOMX_CONSENT_PULPITIS_ENDODONTICS,
	STOMX_CONSENT_REMOVABLE_PROSTHETICS,
	STOMX_CONSENT_SOMATIC_HEALTH,
	STOMX_CONSENT_SUPERFICIAL_MEDIUM_CARIES,
	STOMX_CONSENT_TEETH_WHITENING,
	STOMX_CONSENT_VENEERS,
} from "./therapyAndOrthoConsents.js";
import {
	STOMX_CONSENT_BONE_GRAFTING,
	STOMX_CONSENT_EXTRACTION,
	STOMX_CONSENT_IMPLANTATION,
	STOMX_CONSENT_SEDATION,
	STOMX_CONSENT_SINUS_LIFTING,
} from "./surgeryAndImplantConsents.js";

export * from "./variableResolver.js";

/**
 * ══════════════════════════════════════════════════════════════════════════════
 * STOMX SPECIALIZED, REFUSAL & STATUTORY CONSENTS (LAYER 2)
 *
 * Специализированные ИДС StomX: ортодонтия, элайнеры, детская стоматология,
 * рентгенодиагностика/КЛКТ, лист дозовых нагрузок (СанПиН 2.6.1.1192-03),
 * фотопротокол, отказ от ЕГИСЗ (323-ФЗ ст. 13), отказ от мед. вмешательства (323-ФЗ ст. 20),
 * гарантийная политика и гарантийный паспорт пациента.
 * Также объединяет мастер-каталог STOMX_LEGAL_CONSENTS_CATALOG и реестр всех 49 документов.
 * ══════════════════════════════════════════════════════════════════════════════
 */

export const STOMX_CONSENT_ORTHODONTICS: StomxLegalConsentTemplateMetadata = {
	id: 65,
	systemAlias: "ids_ortodontiya",
	name: "ИДС Ортодонтия",
	procedureType: "orthodontics",
	category: "orthodontics",
	categoryLabel: "Ортодонтия",
	statutoryBasis: "ФЗ № 323-ФЗ (ст. 19-23), Приказ МЗ РФ № 1051н",
	isEgisz: false,
	esiaRequired: false,
	isXrayIds: false,
	keyVariables: ["Пациент.ФИО", "Клиника.Название", "Врач.ФИО", "Прием.Дата"],
};

export const STOMX_CONSENT_ALIGNERS: StomxLegalConsentTemplateMetadata = {
	id: 79,
	systemAlias: "ids_aligners",
	name: "ИДС Элайнеры и ортодонтические каппы",
	procedureType: "aligners",
	category: "orthodontics",
	categoryLabel: "Ортодонтия",
	statutoryBasis: "ФЗ № 323-ФЗ (ст. 19-23), Приказ МЗ РФ № 1051н, ПП РФ № 736",
	isEgisz: false,
	esiaRequired: false,
	isXrayIds: false,
	keyVariables: ["Пациент.ФИО", "Клиника.Название", "Врач.ФИО", "Прием.Дата"],
};

export const STOMX_CONSENT_MINOR_GENERAL: StomxLegalConsentTemplateMetadata = {
	id: 64,
	systemAlias: "ids_nesovershennoletnie",
	name: "ИДС Общее для несовершеннолетних (представитель)",
	procedureType: "minor_general",
	category: "legal",
	categoryLabel: "Детская стоматология и право",
	statutoryBasis: "ФЗ № 323-ФЗ (ст. 20 ч. 2), Приказ МЗ РФ № 1051н",
	isEgisz: false,
	esiaRequired: false,
	isXrayIds: false,
	keyVariables: [
		"Пациент.ФИО",
		"Пациент.ПредставительФИО",
		"Пациент.ПредставительПаспорт",
		"Клиника.Название",
		"Врач.ФИО",
		"Прием.Дата",
	],
};

export const STOMX_CONSENT_XRAY_CBCT: StomxLegalConsentTemplateMetadata = {
	id: 71,
	systemAlias: "ids_rentgen_cbct",
	name: "ИДС Рентгенологическое исследование и КЛКТ",
	procedureType: "xray_cbct",
	category: "radiology",
	categoryLabel: "Рентгенодиагностика",
	statutoryBasis: "ФЗ № 323-ФЗ (ст. 19-23), СанПиН 2.6.1.1192-03, НРБ-99/2009",
	isEgisz: false,
	esiaRequired: false,
	isXrayIds: true,
	standardDoseMsv: 0.055,
	keyVariables: ["Пациент.ФИО", "Клиника.Название", "Врач.ФИО", "Прием.Дата"],
};

export const STOMX_CONSENT_PHOTOPROTOCOL: StomxLegalConsentTemplateMetadata = {
	id: 77,
	systemAlias: "ids_fotoprotokol",
	name: "ИДС Фотопротокол",
	procedureType: "photoprotocol",
	category: "legal",
	categoryLabel: "Фотопротокол и согласие",
	statutoryBasis: "ФЗ № 323-ФЗ (ст. 13 врачебная тайна), ст. 152.1 ГК РФ (охрана изображения)",
	isEgisz: false,
	esiaRequired: false,
	isXrayIds: false,
	keyVariables: ["Пациент.ФИО", "Клиника.Название", "Врач.ФИО", "Прием.Дата"],
};

export const STOMX_CONSENT_EGISZ_REFUSAL: StomxLegalConsentTemplateMetadata = {
	id: 80,
	systemAlias: "otkaz_egisz",
	name: "Отказ от передачи данных в ЕГИСЗ (ФЗ-323 ст. 13)",
	procedureType: "egisz_refusal",
	category: "legal",
	categoryLabel: "Правовые отказы",
	statutoryBasis: "ФЗ № 323-ФЗ (ст. 13 врачебная тайна), ФЗ № 152-ФЗ (О персональных данных)",
	isEgisz: true,
	esiaRequired: false,
	isXrayIds: false,
	keyVariables: [
		"Пациент.ФИО",
		"Пациент.СНИЛС",
		"Пациент.ПаспортДанные",
		"Клиника.Название",
		"Клиника.ИНН",
		"Клиника.ОГРН",
		"Прием.Дата",
	],
};

export const STOMX_CONSENT_INTERVENTION_REFUSAL: StomxLegalConsentTemplateMetadata = {
	id: 81,
	systemAlias: "otkaz_lechenie",
	name: "Отказ от медицинского вмешательства",
	procedureType: "medical_intervention_refusal",
	category: "legal",
	categoryLabel: "Правовые отказы",
	statutoryBasis: "ФЗ № 323-ФЗ (ст. 20 ч. 3), Приказ МЗ РФ № 1051н",
	isEgisz: false,
	esiaRequired: false,
	isXrayIds: false,
	keyVariables: [
		"Пациент.ФИО",
		"Пациент.ПаспортДанные",
		"Клиника.Название",
		"Врач.ФИО",
		"Прием.Диагноз",
		"Прием.Дата",
	],
};

export const STOMX_CONSENT_WARRANTY_POLICY: StomxLegalConsentTemplateMetadata = {
	id: 82,
	systemAlias: "polozhenie_o_garantiyah",
	name: "Положение о гарантийных обязательствах и сроках службы",
	procedureType: "warranty_policy",
	category: "legal",
	categoryLabel: "Гарантии и права потребителя",
	statutoryBasis: "Закон РФ № 2300-1 «О защите прав потребителей», ст. 720-725 ГК РФ, ПП РФ № 736",
	isEgisz: false,
	esiaRequired: false,
	isXrayIds: false,
	keyVariables: ["Пациент.ФИО", "Клиника.Название", "Клиника.ДиректорФИО", "Прием.Дата"],
};

export const STOMX_CONSENT_XRAY_DOSE_SHEET: StomxLegalConsentTemplateMetadata = {
	id: 15,
	systemAlias: "list_ucheta_dozovyh_nagruzok",
	name: "Лист учета дозовых нагрузок пациента при рентгенологических исследованиях",
	procedureType: "xray_dose_load_sheet",
	category: "radiology",
	categoryLabel: "Радиационная безопасность СанПиН",
	statutoryBasis: "Приложение № 4 к СанПиН 2.6.1.1192-03, СанПиН 2.6.1.2523-09 (НРБ-99/2009)",
	isEgisz: false,
	esiaRequired: false,
	isXrayIds: true,
	standardDoseMsv: 0.055,
	keyVariables: ["Пациент.ФИО", "Пациент.НомерКарты", "Клиника.Название", "Врач.ФИО", "Прием.Дата"],
};

export const STOMX_CONSENT_WARRANTY_PASSPORT: StomxLegalConsentTemplateMetadata = {
	id: 54,
	systemAlias: "garantiynyy_pasport",
	name: "Гарантийный паспорт стоматологического пациента",
	procedureType: "warranty_passport",
	category: "legal",
	categoryLabel: "Гарантии и сервис",
	statutoryBasis: "Закон РФ № 2300-1 «О защите прав потребителей», ст. 720-725 ГК РФ, ПП РФ № 736",
	isEgisz: false,
	esiaRequired: false,
	isXrayIds: false,
	keyVariables: ["Пациент.ФИО", "Клиника.Название", "Врач.ФИО", "Прием.Зуб", "Прием.Дата"],
};

export const STOMX_SPECIALIZED_AND_REFUSAL_CONSENTS: readonly StomxLegalConsentTemplateMetadata[] = [
	STOMX_CONSENT_ORTHODONTICS,
	STOMX_CONSENT_ALIGNERS,
	STOMX_CONSENT_MINOR_GENERAL,
	STOMX_CONSENT_XRAY_CBCT,
	STOMX_CONSENT_PHOTOPROTOCOL,
	STOMX_CONSENT_EGISZ_REFUSAL,
	STOMX_CONSENT_INTERVENTION_REFUSAL,
	STOMX_CONSENT_WARRANTY_POLICY,
	STOMX_CONSENT_XRAY_DOSE_SHEET,
	STOMX_CONSENT_WARRANTY_PASSPORT,
] as const;

export const STOMX_LEGAL_CONSENTS_CATALOG: readonly StomxLegalConsentTemplateMetadata[] = [
	STOMX_CONSENT_VENEERS,
	STOMX_CONSENT_IMPLANTATION,
	STOMX_CONSENT_SINUS_LIFTING,
	STOMX_CONSENT_SEDATION,
	STOMX_CONSENT_EXTRACTION,
	STOMX_CONSENT_FIXED_PROSTHETICS,
	STOMX_CONSENT_REMOVABLE_PROSTHETICS,
	STOMX_CONSENT_DEEP_CARIES,
	STOMX_CONSENT_SUPERFICIAL_MEDIUM_CARIES,
	STOMX_CONSENT_PULPITIS_ENDODONTICS,
	STOMX_CONSENT_PERIODONTOLOGY,
	STOMX_CONSENT_PROFESSIONAL_HYGIENE,
	STOMX_CONSENT_TEETH_WHITENING,
	STOMX_CONSENT_ORTHODONTICS,
	STOMX_CONSENT_MINOR_GENERAL,
	STOMX_CONSENT_XRAY_CBCT,
	STOMX_CONSENT_PHOTOPROTOCOL,
	STOMX_CONSENT_EGISZ_REFUSAL,
	STOMX_CONSENT_INTERVENTION_REFUSAL,
	STOMX_CONSENT_WARRANTY_POLICY,
	STOMX_CONSENT_XRAY_DOSE_SHEET,
	STOMX_CONSENT_WARRANTY_PASSPORT,
	STOMX_CONSENT_SOMATIC_HEALTH,
	STOMX_CONSENT_BONE_GRAFTING,
	STOMX_CONSENT_ALIGNERS,
] as const;

export function getStomxTemplateMetadata(
	aliasOrId: string | number,
): StomxLegalConsentTemplateMetadata | undefined {
	if (typeof aliasOrId === "number") {
		return STOMX_LEGAL_CONSENTS_CATALOG.find((item) => item.id === aliasOrId);
	}
	const normalized = String(aliasOrId).trim().toLowerCase();
	return STOMX_LEGAL_CONSENTS_CATALOG.find(
		(item) =>
			item.systemAlias.toLowerCase() === normalized ||
			item.procedureType.toLowerCase() === normalized ||
			String(item.id) === normalized,
	);
}

export const STOMX_ALL_49_DOCUMENTS_REGISTRY: readonly StomxDocumentRegistryItem[] = [
	{
		id: 1,
		name: "Акт выполненных работ",
		category: "financial",
		categoryLabel: "Бухгалтерия и расчеты",
		statutoryBasis: "ст. 779-783 ГК РФ, ст. 9 Федерального закона № 402-ФЗ «О бухгалтерском учете»",
		targetDenteModule: "billing",
		isConsentOrLegalContract: true,
		inSharedCatalog: false,
	},
	{
		id: 2,
		name: "План лечения",
		category: "clinical",
		categoryLabel: "Планы лечения",
		statutoryBasis: "ст. 70-71 Федерального закона № 323-ФЗ, Приказ МЗ РФ № 834н",
		targetDenteModule: "emr",
		isConsentOrLegalContract: true,
		inSharedCatalog: false,
	},
	{
		id: 3,
		name: "Амбулаторная карта 043/у",
		category: "clinical",
		categoryLabel: "Медицинская документация",
		statutoryBasis: "Приказ Минздрава СССР № 1030, Приказ МЗ РФ № 834н",
		targetDenteModule: "emr",
		isConsentOrLegalContract: true,
		inSharedCatalog: false,
	},
	{
		id: 4,
		name: "Заказ-наряд в зуботехническую лабораторию",
		category: "clinical",
		categoryLabel: "Лаборатория и ортопедия",
		statutoryBasis: "ст. 720-725 ГК РФ",
		targetDenteModule: "lab",
		isConsentOrLegalContract: true,
		inSharedCatalog: false,
	},
	{
		id: 5,
		name: "Расписание врачей",
		category: "clinical",
		categoryLabel: "Расписание и приёмы",
		statutoryBasis: "Трудовой кодекс РФ, СанПиН 2.1.3678-20",
		targetDenteModule: "schedule",
		isConsentOrLegalContract: false,
		inSharedCatalog: false,
	},
	{
		id: 6,
		name: "Протокол рентген исследования",
		category: "radiology",
		categoryLabel: "Рентгенодиагностика",
		statutoryBasis: "СанПиН 2.6.1.1192-03, Приказ МЗ РФ № 560н",
		targetDenteModule: "radiology",
		isConsentOrLegalContract: true,
		inSharedCatalog: false,
	},
	{
		id: 7,
		name: "Справка об оплате медицинских услуг для ФНС",
		category: "financial",
		categoryLabel: "Налоговый вычет",
		statutoryBasis: "НК РФ ст. 219 п. 1 пп. 3, Приказ ФНС России КНД 1151156",
		targetDenteModule: "billing",
		isConsentOrLegalContract: true,
		inSharedCatalog: false,
	},
	{
		id: 8,
		name: "Ортодонтическая карта",
		category: "orthodontics",
		categoryLabel: "Ортодонтия",
		statutoryBasis: "Приказ МЗ РФ № 834н",
		targetDenteModule: "orthodontics",
		isConsentOrLegalContract: true,
		inSharedCatalog: false,
	},
	{
		id: 9,
		name: "Остатки на складе (инвентаризационная ведомость)",
		category: "warehouse",
		categoryLabel: "Складской учет",
		statutoryBasis: "ст. 11 Федерального закона № 402-ФЗ",
		targetDenteModule: "warehouse",
		isConsentOrLegalContract: false,
		inSharedCatalog: false,
	},
	{
		id: 11,
		name: "Запись в эпикризе ортокарты",
		category: "orthodontics",
		categoryLabel: "Ортодонтия",
		statutoryBasis: "Приказ МЗ РФ № 834н",
		targetDenteModule: "orthodontics",
		isConsentOrLegalContract: false,
		inSharedCatalog: false,
	},
	{
		id: 12,
		name: "План лечения с агрегацией по визитам",
		category: "clinical",
		categoryLabel: "Планы лечения",
		statutoryBasis: "ст. 70-71 Федерального закона № 323-ФЗ",
		targetDenteModule: "emr",
		isConsentOrLegalContract: true,
		inSharedCatalog: false,
	},
	{
		id: 13,
		name: "Акт выполненных работ для рентгена",
		category: "radiology",
		categoryLabel: "Рентген и расчеты",
		statutoryBasis: "ст. 779 ГК РФ, Федеральный закон № 402-ФЗ",
		targetDenteModule: "billing",
		isConsentOrLegalContract: true,
		inSharedCatalog: false,
	},
	{
		id: 15,
		name: "Лист учета дозовых нагрузок пациента при рентгенологических исследованиях",
		category: "radiology",
		categoryLabel: "Радиационная безопасность СанПиН",
		statutoryBasis: "Приложение № 4 к СанПиН 2.6.1.1192-03, СанПиН 2.6.1.2523-09 (НРБ-99/2009)",
		targetDenteModule: "radiology",
		isConsentOrLegalContract: true,
		inSharedCatalog: true,
	},
	{
		id: 16,
		name: "Акт оказанных услуг ДМС",
		category: "financial",
		categoryLabel: "Страховая медицина (ДМС)",
		statutoryBasis: "Закон РФ № 4015-1 «Об организации страхового дела в РФ»",
		targetDenteModule: "billing",
		isConsentOrLegalContract: true,
		inSharedCatalog: false,
	},
	{
		id: 18,
		name: "Запись в наблюдении ортокарты",
		category: "orthodontics",
		categoryLabel: "Ортодонтия",
		statutoryBasis: "Приказ МЗ РФ № 834н",
		targetDenteModule: "orthodontics",
		isConsentOrLegalContract: false,
		inSharedCatalog: false,
	},
	{
		id: 50,
		name: "График платежей по рассрочке",
		category: "financial",
		categoryLabel: "Финансы и рассрочка",
		statutoryBasis: "ст. 823 ГК РФ (Коммерческий кредит)",
		targetDenteModule: "billing",
		isConsentOrLegalContract: true,
		inSharedCatalog: false,
	},
	{
		id: 51,
		name: "План лечения с агрегацией по зубам",
		category: "clinical",
		categoryLabel: "Планы лечения",
		statutoryBasis: "ст. 70-71 Федерального закона № 323-ФЗ, Приказ МЗ РФ № 834н",
		targetDenteModule: "emr",
		isConsentOrLegalContract: true,
		inSharedCatalog: false,
	},
	{
		id: 52,
		name: "AI-заключение и клинико-экспертный аудит для главного врача",
		category: "analytics",
		categoryLabel: "Контроль качества медпомощи",
		statutoryBasis: "Приказ МЗ РФ № 785н (Внутренний контроль качества и безопасности медицинской деятельности)",
		targetDenteModule: "analytics",
		isConsentOrLegalContract: false,
		inSharedCatalog: false,
	},
	{
		id: 53,
		name: "Анкета общего состояния здоровья пациента",
		category: "clinical",
		categoryLabel: "Анамнез и соматика",
		statutoryBasis: "ФЗ № 323-ФЗ (ст. 19-22), Приказ МЗ РФ № 834н / 043/у",
		targetDenteModule: "emr",
		isConsentOrLegalContract: true,
		inSharedCatalog: true,
	},
	{
		id: 54,
		name: "Гарантийный паспорт стоматологического пациента",
		category: "legal",
		categoryLabel: "Гарантии и сервис",
		statutoryBasis: "Закон РФ № 2300-1 «О защите прав потребителей», ст. 720-725 ГК РФ, ПП РФ № 736",
		targetDenteModule: "legal",
		isConsentOrLegalContract: true,
		inSharedCatalog: true,
	},
	{
		id: 55,
		name: "Договор на оказание платных медицинских услуг (взрослый)",
		category: "legal",
		categoryLabel: "Договорная база",
		statutoryBasis: "ПП РФ № 736 от 11.05.2023, ст. 779-783 ГК РФ",
		targetDenteModule: "legal",
		isConsentOrLegalContract: true,
		inSharedCatalog: false,
	},
	{
		id: 56,
		name: "Договор на оказание мед. услуг несовершеннолетнего (законный представитель)",
		category: "legal",
		categoryLabel: "Детская стоматология и право",
		statutoryBasis: "ПП РФ № 736 от 11.05.2023, ст. 20, 26, 28 ГК РФ",
		targetDenteModule: "legal",
		isConsentOrLegalContract: true,
		inSharedCatalog: false,
	},
	{
		id: 57,
		name: "ИДС Местная анестезия",
		category: "legal",
		categoryLabel: "Анестезиология",
		statutoryBasis: "ФЗ № 323-ФЗ (ст. 20), Приказ МЗ РФ № 1051н",
		targetDenteModule: "legal",
		isConsentOrLegalContract: true,
		inSharedCatalog: true,
	},
	{
		id: 58,
		name: "ИДС Виниры",
		category: "legal",
		categoryLabel: "Ортопедия и эстетика",
		statutoryBasis: "ФЗ № 323-ФЗ (ст. 19-23), Приказ МЗ РФ № 1051н, ПП РФ № 736",
		targetDenteModule: "legal",
		isConsentOrLegalContract: true,
		inSharedCatalog: true,
	},
	{
		id: 59,
		name: "ИДС Глубокий кариес",
		category: "legal",
		categoryLabel: "Терапия и кариес",
		statutoryBasis: "ФЗ № 323-ФЗ (ст. 19-23), Приказ МЗ РФ № 1051н",
		targetDenteModule: "legal",
		isConsentOrLegalContract: true,
		inSharedCatalog: true,
	},
	{
		id: 60,
		name: "ИДС Имплантация",
		category: "legal",
		categoryLabel: "Хирургия и имплантация",
		statutoryBasis: "ФЗ № 323-ФЗ (ст. 19-23), Приказ МЗ РФ № 1051н, ПП РФ № 736",
		targetDenteModule: "legal",
		isConsentOrLegalContract: true,
		inSharedCatalog: true,
	},
	{
		id: 61,
		name: "ИДС На лечение поверхностного и среднего кариеса",
		category: "legal",
		categoryLabel: "Терапия и кариес",
		statutoryBasis: "ФЗ № 323-ФЗ (ст. 19-23), Приказ МЗ РФ № 1051н",
		targetDenteModule: "legal",
		isConsentOrLegalContract: true,
		inSharedCatalog: true,
	},
	{
		id: 62,
		name: "ИДС На медицинское вмешательство (Общее)",
		category: "legal",
		categoryLabel: "Статутные согласия МЗ РФ",
		statutoryBasis: "Приказ МЗ РФ № 1051н, ст. 20 ФЗ-323",
		targetDenteModule: "legal",
		isConsentOrLegalContract: true,
		inSharedCatalog: true,
	},
	{
		id: 63,
		name: "ИДС Несъемные ортопедические конструкции",
		category: "legal",
		categoryLabel: "Ортопедическая стоматология",
		statutoryBasis: "ФЗ № 323-ФЗ (ст. 19-23), Приказ МЗ РФ № 1051н, ПП РФ № 736",
		targetDenteModule: "legal",
		isConsentOrLegalContract: true,
		inSharedCatalog: true,
	},
	{
		id: 64,
		name: "ИДС Общее для несовершеннолетних (законный представитель)",
		category: "legal",
		categoryLabel: "Детская стоматология и право",
		statutoryBasis: "ФЗ № 323-ФЗ (ст. 20 ч. 2), Приказ МЗ РФ № 1051н",
		targetDenteModule: "legal",
		isConsentOrLegalContract: true,
		inSharedCatalog: true,
	},
	{
		id: 65,
		name: "ИДС Ортодонтия общее",
		category: "legal",
		categoryLabel: "Ортодонтия",
		statutoryBasis: "ФЗ № 323-ФЗ (ст. 19-23), Приказ МЗ РФ № 1051н",
		targetDenteModule: "legal",
		isConsentOrLegalContract: true,
		inSharedCatalog: true,
	},
	{
		id: 66,
		name: "ИДС Ортопедия (Протезирование)",
		category: "legal",
		categoryLabel: "Ортопедическая стоматология",
		statutoryBasis: "ФЗ № 323-ФЗ (ст. 19-23), Приказ МЗ РФ № 1051н",
		targetDenteModule: "legal",
		isConsentOrLegalContract: true,
		inSharedCatalog: true,
	},
	{
		id: 67,
		name: "ИДС Отбеливание зубов",
		category: "legal",
		categoryLabel: "Эстетика и отбеливание",
		statutoryBasis: "ФЗ № 323-ФЗ (ст. 19-23), Приказ МЗ РФ № 1051н",
		targetDenteModule: "legal",
		isConsentOrLegalContract: true,
		inSharedCatalog: true,
	},
	{
		id: 68,
		name: "ИДС Пародонтология",
		category: "legal",
		categoryLabel: "Пародонтология",
		statutoryBasis: "ФЗ № 323-ФЗ (ст. 19-23), Приказ МЗ РФ № 1051н",
		targetDenteModule: "legal",
		isConsentOrLegalContract: true,
		inSharedCatalog: true,
	},
	{
		id: 69,
		name: "ИДС Профессиональная гигиена",
		category: "legal",
		categoryLabel: "Гигиена и профилактика",
		statutoryBasis: "ФЗ № 323-ФЗ (ст. 19-23), Приказ МЗ РФ № 1051н",
		targetDenteModule: "legal",
		isConsentOrLegalContract: true,
		inSharedCatalog: true,
	},
	{
		id: 70,
		name: "ИДС Пульпит и эндодонтия",
		category: "legal",
		categoryLabel: "Эндодонтия и пульпит",
		statutoryBasis: "ФЗ № 323-ФЗ (ст. 19-23), Приказ МЗ РФ № 1051н",
		targetDenteModule: "legal",
		isConsentOrLegalContract: true,
		inSharedCatalog: true,
	},
	{
		id: 71,
		name: "ИДС Рентгенологическое исследование и КЛКТ",
		category: "radiology",
		categoryLabel: "Рентгенодиагностика",
		statutoryBasis: "ФЗ № 323-ФЗ (ст. 19-23), СанПиН 2.6.1.1192-03, НРБ-99/2009",
		targetDenteModule: "radiology",
		isConsentOrLegalContract: true,
		inSharedCatalog: true,
	},
	{
		id: 72,
		name: "ИДС Седация (ЗАКС / в/в)",
		category: "legal",
		categoryLabel: "Анестезиология и седация",
		statutoryBasis: "ФЗ № 323-ФЗ (ст. 19-23), Приказ МЗ РФ № 1051н",
		targetDenteModule: "legal",
		isConsentOrLegalContract: true,
		inSharedCatalog: true,
	},
	{
		id: 73,
		name: "ИДС Синус-лифтинг",
		category: "legal",
		categoryLabel: "Хирургия и имплантация",
		statutoryBasis: "ФЗ № 323-ФЗ (ст. 19-23), Приказ МЗ РФ № 1051н",
		targetDenteModule: "legal",
		isConsentOrLegalContract: true,
		inSharedCatalog: true,
	},
	{
		id: 74,
		name: "ИДС Съемные ортопедические конструкции",
		category: "legal",
		categoryLabel: "Ортопедическая стоматология",
		statutoryBasis: "ФЗ № 323-ФЗ (ст. 19-23), Приказ МЗ РФ № 1051н, ПП РФ № 736",
		targetDenteModule: "legal",
		isConsentOrLegalContract: true,
		inSharedCatalog: true,
	},
	{
		id: 75,
		name: "ИДС Терапевтическое лечение",
		category: "legal",
		categoryLabel: "Терапевтическая стоматология",
		statutoryBasis: "ФЗ № 323-ФЗ (ст. 19-23), Приказ МЗ РФ № 1051н",
		targetDenteModule: "legal",
		isConsentOrLegalContract: true,
		inSharedCatalog: true,
	},
	{
		id: 76,
		name: "ИДС Удаление зуба (хирургическое)",
		category: "legal",
		categoryLabel: "Хирургия и удаление",
		statutoryBasis: "ФЗ № 323-ФЗ (ст. 19-23), Приказ МЗ РФ № 1051н",
		targetDenteModule: "legal",
		isConsentOrLegalContract: true,
		inSharedCatalog: true,
	},
	{
		id: 77,
		name: "ИДС Фотопротокол",
		category: "legal",
		categoryLabel: "Фотопротокол и согласие",
		statutoryBasis: "ФЗ № 323-ФЗ (ст. 13 врачебная тайна), ст. 152.1 ГК РФ",
		targetDenteModule: "legal",
		isConsentOrLegalContract: true,
		inSharedCatalog: true,
	},
	{
		id: 78,
		name: "ИДС Хирургическое лечение (амбулаторное)",
		category: "legal",
		categoryLabel: "Хирургическая стоматология",
		statutoryBasis: "ФЗ № 323-ФЗ (ст. 19-23), Приказ МЗ РФ № 1051н",
		targetDenteModule: "legal",
		isConsentOrLegalContract: true,
		inSharedCatalog: true,
	},
	{
		id: 79,
		name: "ИДС Эндодонтическое лечение",
		category: "legal",
		categoryLabel: "Эндодонтия",
		statutoryBasis: "ФЗ № 323-ФЗ (ст. 19-23), Приказ МЗ РФ № 1051н",
		targetDenteModule: "legal",
		isConsentOrLegalContract: true,
		inSharedCatalog: true,
	},
	{
		id: 80,
		name: "Отказ от передачи данных в ЕГИСЗ (ФЗ-323 ст. 13)",
		category: "legal",
		categoryLabel: "Правовые отказы",
		statutoryBasis: "ФЗ № 323-ФЗ (ст. 13 врачебная тайна), Федеральный закон № 152-ФЗ, ПП РФ № 140",
		targetDenteModule: "legal",
		isConsentOrLegalContract: true,
		inSharedCatalog: true,
	},
	{
		id: 81,
		name: "Отказ от медицинского вмешательства",
		category: "legal",
		categoryLabel: "Правовые отказы",
		statutoryBasis: "ФЗ № 323-ФЗ (ст. 20 ч. 3), Приказ МЗ РФ № 1051н",
		targetDenteModule: "legal",
		isConsentOrLegalContract: true,
		inSharedCatalog: true,
	},
	{
		id: 82,
		name: "Положение о гарантийных обязательствах и сроках службы",
		category: "legal",
		categoryLabel: "Гарантии и права потребителя",
		statutoryBasis: "Закон РФ № 2300-1 «О защите прав потребителей», ст. 720-725 ГК РФ, ПП РФ № 736",
		targetDenteModule: "legal",
		isConsentOrLegalContract: true,
		inSharedCatalog: true,
	},
	{
		id: 83,
		name: "Согласие на обработку персональных данных (152-ФЗ)",
		category: "legal",
		categoryLabel: "Персональные данные",
		statutoryBasis: "Федеральный закон № 152-ФЗ «О персональных данных»",
		targetDenteModule: "legal",
		isConsentOrLegalContract: true,
		inSharedCatalog: true,
	},
] as const;

export function getAllStomx49Documents(): readonly StomxDocumentRegistryItem[] {
	return STOMX_ALL_49_DOCUMENTS_REGISTRY;
}

export function getStomxDocumentRegistryItem(
	idOrName: number | string,
): StomxDocumentRegistryItem | undefined {
	if (typeof idOrName === "number") {
		return STOMX_ALL_49_DOCUMENTS_REGISTRY.find((item) => item.id === idOrName);
	}
	const normalized = String(idOrName).trim().toLowerCase();
	return STOMX_ALL_49_DOCUMENTS_REGISTRY.find(
		(item) =>
			item.name.toLowerCase() === normalized ||
			item.name.toLowerCase().includes(normalized) ||
			String(item.id) === normalized,
	);
}
